BattleFrontier_Lounge8_MapScripts::
	.byte 0

BattleFrontier_Lounge8_EventScript_Man::
	msgbox BattleFrontier_Lounge8_Text_WhatATrainerNeeds, MSGBOX_NPC
	end

BattleFrontier_Lounge8_EventScript_Woman::
	msgbox BattleFrontier_Lounge8_Text_KnowAboutFrontierBrains, MSGBOX_NPC
	end

BattleFrontier_Lounge8_EventScript_NinjaBoy::
	msgbox BattleFrontier_Lounge8_Text_ToldMeIHaveTalentForBattling, MSGBOX_NPC
	end

BattleFrontier_Lounge8_Text_WhatATrainerNeeds:
	.string "ENTRENATZAILE batek behar duena…\p"
	.string "Jakinduria…\n"
	.string "Estrategia…\l"
	.string "Zortea…\l"
	.string "Sena…\l"
	.string "Espiritua…\l"
	.string "Ausardia…\l"
	.string "Eta trebetasuna…\p"
	.string "Beno, guztia daukat nik!\n"
	.string "Garaitezina izango naiz leku guztietan!\p"
	.string "Zer? POKéMONAK?\n"
	.string "Zer da hori?$"

BattleFrontier_Lounge8_Text_KnowAboutFrontierBrains:
	.string "Ezagutzen al dituzu FRONTEKO\n"
	.string "BURMUINAK?\p"
	.string "Hala deitzen die TRIKIK BORROKA\n"
	.string "FRONTEKO zazpi eraikinetan dauden\l"
	.string "zazpi ENTRENATZAILE bereziei.$"

BattleFrontier_Lounge8_Text_ToldMeIHaveTalentForBattling:
	.string "BORROKA DORREAN, neska nagusi batek\n"
	.string "esan dit borrokarako talentu\l"
	.string "handia daukadala! POKéMON\p"
	.string "TXAPELKETAK ditut gustoko, ordea!\p"
	.string "Baina ez naiz ona TXAPELKETETAN!\p"
	.string "Zerbait gustatzea eta horretarako\n"
	.string "talentua izatea ez da gauza bera.$"

