SootopolisCity_House5_MapScripts::
	.byte 0

SootopolisCity_House5_EventScript_Maniac::
	msgbox SootopolisCity_House5_Text_SootopolisMtPyreConnection, MSGBOX_NPC
	end

SootopolisCity_House5_EventScript_Girl::
	msgbox SootopolisCity_House5_Text_BrotherUsedToStudySea, MSGBOX_NPC
	end

SootopolisCity_House5_Text_SootopolisMtPyreConnection:
	.string "Badirudi konexioren bat dagoela\n"
	.string "ARREZIPOLIS eta PIRO MENDIAREN artean.\p"
	.string "Nire lagunek eta nik aztertu genuen\n"
	.string "lehen lan egiten nuen laborategian.$"

SootopolisCity_House5_Text_BrotherUsedToStudySea:
	.string "Nire anaia nagusiak itsasoa aztertzen zuen.$"

