RustboroCity_House2_MapScripts::
	.byte 0

RustboroCity_House2_EventScript_PokefanF::
	msgbox RustboroCity_House2_Text_TrainerSchoolExcellent, MSGBOX_NPC
	end

RustboroCity_House2_EventScript_LittleGirl::
	msgbox RustboroCity_House2_Text_RoxanneKnowsALot, MSGBOX_NPC
	end

RustboroCity_House2_Text_TrainerSchoolExcellent:
	.string "ENTRENATZAILE ESKOLA bikaina da.\p"
	.string "Bertan ikasiz gero, GIMNASIOKO\n"
	.string "LIDERRA ere bilakatu zaitezke.$"

RustboroCity_House2_Text_RoxanneKnowsALot:
	.string "HAITZIBERREK, GIMNASIOKO LIDERRAK,\n"
	.string "asko daki POKéMONEN inguruan.\p"
	.string "Oso indartsua da, gainera!$"

