gText_ApprenticeChallenge0::
	.string "Ein… {STR_VAR_1}ren {STR_VAR_2}garren ikaslea naiz.\n"
	.string "Jope… Ezi dut tentsio honekin guztiarekin…$"

gText_ApprenticeChallenge1::
	.string "{STR_VAR_1}ren {STR_VAR_2}. ikaslea naiz!\n"
	.string "Banator!$"

gText_ApprenticeChallenge2::
	.string "{STR_VAR_1}ren {STR_VAR_2}. ikaslea naiz!\n"
	.string "Borrokatu dezagun!$"

gText_ApprenticeChallenge3::
	.string "Ein… {STR_VAR_1}ren {STR_VAR_2}. ikaslea naiz…\n"
	.string "Uset duzu inoiz irabaziko dudala?$"

gText_ApprenticeChallenge4::
	.string "{STR_VAR_1}ren {STR_VAR_2}. ikaslea naiz!\n"
	.string "Nire kontra borrokatzen utziko dizut!$"

gText_ApprenticeChallenge5::
	.string "Oso oso okupatuta nago, baina\n"
	.string "kasualitatez, {STR_VAR_1}ren {STR_VAR_2}. ikaslea ere banaiz.$"

gText_ApprenticeChallenge6::
	.string "{STR_VAR_1}ren {STR_VAR_2}. ikaslea naiz.\n"
	.string "Urte askoan!$"

gText_ApprenticeChallenge7::
	.string "{STR_VAR_1}ren {STR_VAR_2}. ikaslea naiz.\n"
	.string "Has naiteke?$"

gText_ApprenticeChallenge8::
	.string "Ene! {STR_VAR_1}ren {STR_VAR_2}. ikaslea naiz!\n"
	.string "Ahalik ondoen borrokatuko dut!$"

gText_ApprenticeChallenge9::
	.string "Iuju! {STR_VAR_1}ren {STR_VAR_2}. ikaslea naiz!\n"
	.string "Goazen ba!$"

gText_ApprenticeChallenge10::
	.string "{STR_VAR_1}ren 1000. ikaslea naiz!\n"
	.string "Txantxa da, {STR_VAR_2}.a naiz! Goazen!$"

gText_ApprenticeChallenge11::
	.string "Bai, {STR_VAR_1}ren {STR_VAR_2}. ikaslea naiz!\n"
	.string "Egurra ematera!$"

gText_ApprenticeChallenge12::
	.string "Iujujuju! Esan daiteke\n"
	.string "{STR_VAR_1}ren {STR_VAR_2}. ikaslea naizela!$"

gText_ApprenticeChallenge13::
	.string "Tuju! {STR_VAR_1}ren {STR_VAR_2}. ikaslea naiz.\n"
	.string "Pozten naiz ezagutzeaz! Tuju!$"

gText_ApprenticeChallenge14::
	.string "Urduriegi nago…\n"
	.string "{STR_VAR_1}ren {STR_VAR_2}. ikaslea naiz.$"

gText_ApprenticeChallenge15::
	.string "{STR_VAR_1}ren {STR_VAR_2}. ikaslea naiz,\n"
	.string "bene-benetan.$"

gText_ApprenticePleaseTeach0::
	.string "Zu al zara… {PLAYER}?\n"
	.string "Ene! Zintz…zintz…\p"
	.string "Oi! B-Barkatu…\n"
	.string "Ze urduri nagoen, ezin ditut malkoak eutsi…\p"
	.string "{STR_VAR_1} naiz, eta asko miresten\n"
	.string "zaitut, {PLAYER}.\p"
	.string "Nire ametsa izan da zu ezagutu\n"
	.string "eta POKÉMONEN inguruan galderak egitea.\p"
	.string "Mesedez, faborez, {PLAYER}!\n"
	.string "mesedez, irakatsi POKÉMONEN inguruan!$"

gText_ApprenticeRejectTeaching0::
	.string "B-Baina…\n"
	.string "zintz… Buaaaaaa!\p"
	.string "Faborez!\n"
	.string "Erregutzen dizut, mesedez!$"

gText_ApprenticeWhichLevelMode0::
	.string "Benetan? Irakatsiko didazu?\n"
	.string "Onaaaaa! Bikain! Iujuu!\p"
	.string "Ene… Barkatu…\n"
	.string "Hain pozik nago, negarrez hasi naizela…\p"
	.string "Ba… Orduan esan!\n"
	.string "BORROKA DORREAREN inguruan da.\p"
	.string "Zer da niretzat hobe: 50. Maila\n"
	.string "edo Maila Irekia?$"

gText_ApprenticeLevelModeThanks0::
	.string "{STR_VAR_1}?\n"
	.string "Buaaaaaa!\p"
	.string "Ene! Barkatu!\n"
	.string "Oso oso pozik jarri naiz zuk maila\l"
	.string "gomendatzean eta negarrez hasi naiz…\p"
	.string "Zintz…\n"
	.string "Eskerrik asko!\l"
	.string "Hitz egin berriro nirekin, faborez!$"

gText_ApprenticePleaseTeach1::
	.string "Uau! {PLAYER} zara, ezta?\n"
	.string "Izugarri indartsua zara, baietz?\p"
	.string "Ni {STR_VAR_1} naiz!\n"
	.string "ENTRENATZAILE bihurtu berri naiz!\p"
	.string "Mesedez, {PLAYER}!\n"
	.string "Izango zara nire irakaslea eta\l"
	.string "ENTRENATZAILE izaten erakutsi?$"

gText_ApprenticeRejectTeaching1::
	.string "Oh, ez, zergatik?\n"
	.string "Mesedez? Faborez?\l"
	.string "Irakatsi, mesedeeeez!$"

gText_ApprenticeWhichLevelMode1::
	.string "Bai! Ederki!\p"
	.string "Lehenengo egin nahi dizudan galdera\n"
	.string "BORROKA DORREAREN inguruan da!\p"
	.string "50. Maila eta Maila irekiko gelen artean…\n"
	.string "Zein da nrietzat egokiena?$"

gText_ApprenticeLevelModeThanks1::
	.string "{STR_VAR_1}, ezta? Arrazoia!\n"
	.string "Pila bat saiatuko naiz!\p"
	.string "Berriz elkartzen bagara, erakutsi\n"
	.string "zerbait berria, mesedez!$"

gText_ApprenticePleaseTeach2::
	.string "Em… Zu al zara {PLAYER}?\n"
	.string "Ni {STR_VAR_1} naiz.\p"
	.string "POKéMON ENTRENATZAILEA izan nahi\n"
	.string "dut, baina ez dakit nola…\p"
	.string "Zuri galdetzea pentsatu dut, horren\n"
	.string "famatua zarenez.\p"
	.string "{PLAYER}, lagunduko zenidake?$"

gText_ApprenticeRejectTeaching2::
	.string "Baina, baina…\p"
	.string "Benetan POKéMON ENTRENATZAILE\n"
	.string "izan nahi dut!\p"
	.string "Erantzungo nire galderak, mesedez?$"

gText_ApprenticeWhichLevelMode2::
	.string "Esker mila!\n"
	.string "Hona hemen nire galdera!\p"
	.string "BORROKA DORREAK bi modu ditu,\n"
	.string "50 Maila eta Maila Irekia, ezta?\p"
	.string "Zure iritziz, zein da niretzat\n"
	.string "egokiena?$"

gText_ApprenticeLevelModeThanks2::
	.string "Ah, {STR_VAR_1} beraz?\n"
	.string "Ulertuta!\p"
	.string "Beste galdera bat dudanean,\n"
	.string "zure bila etorriko naiz hona!$"

gText_ApprenticePleaseTeach3::
	.string "Baina… Ein? Zu al zara…\n"
	.string "Ez, ezinezkoa da hori.\p"
	.string "Ni bezalako batek ezin du\n"
	.string "{PLAYER} bezalako norbait ezagutu.\p"
	.string "…Benetan {PLAYER} zarela?\n"
	.string "Ezin dutsinetsi zurekin hizketan nabilela!\p"
	.string "Horren gauza ona jazo bazait,\n"
	.string "hemendik aurrera gauza txarrak besterik\l"
	.string "ez zaizkit gertatuko, seguru nago…\p"
	.string "…Barkatu…\n"
	.string "Ni… {STR_VAR_1} naiz…\p"
	.string "Ez dut nitaz harro egoteko\n"
	.string "ezer egin inoiz…\p"
	.string "Ez nintzateke aurkeztu ere egin behar,\n"
	.string "seguru ahaztuko zenukeela…\p"
	.string "Amets bat izan nuen, egunen batean zu,\n"
	.string "{PLAYER}, ezagutu eta galdetuko nizula\l"
	.string "nola izan ENTRENATZAILE ona.\p"
	.string "Baina ez dut uste lagunduko\n"
	.string "zenidakeenik.\p"
	.string "…Edo agian lagunduko zenidake\n"
	.string "pista bat edo beste emanda?$"

gText_ApprenticeRejectTeaching3::
	.string "Banekien…\p"
	.string "Normala, horren aspergarria naizenez\n"
	.string "ezin zuen beste inola izan…\p"
	.string "Baina uste nuen, beharbada…\n"
	.string "Berriz kontsidera zenezake esandakoa?\p"
	.string "Ezin naiz horren erraz errenditu.\n"
	.string "Berriz galdetuko dizut!\p"
	.string "Faborez, lagunduko zenidake\n"
	.string "gomendio bat edo beste emanda?$"

gText_ApprenticeWhichLevelMode3::
	.string "Benetan? Ezin dut sinestu!\n"
	.string "Benetan lagunduko didazu!\l"
	.string "Ze pozik nagoen…\p"
	.string "Galdetu nahi dizudana nahiko sinplea\n"
	.string "da, baina ezin aukeratu nabil…\p"
	.string "BORROKA DORREAN 50 Maila edo\n"
	.string "Maila Irekia aukeartu daitezke.\p"
	.string "Zure iritziz, zein izango litzateke\n"
	.string "niretzat egokiena?$"

gText_ApprenticeLevelModeThanks3::
	.string "{STR_VAR_1}? Ados!\n"
	.string "Ni bezalako norbaitek aukerarik izango\l"
	.string "lukeela uste duzu?\p"
	.string "Bueno,ni saiatuko naiz, nahiz eta\n"
	.string "ez dudan uste lortuko dudanik.\p"
	.string "Mila esker zure denbora\n"
	.string "niri eskaintzeagatik.$"

gText_ApprenticePleaseTeach4::
	.string "Ene! {PLAYER}{KUN}, zara, ezta?\p"
	.string "Entzun dut oso ona zarela\n"
	.string "POKÉMONEKIN!\p"
	.string "Ni {STR_VAR_1} naiz!\n"
	.string "Zure laguna izango naiz!\p"
	.string "Bazekenien?\p"
	.string "Ezin duzu BORROKA FRONTEAN irabazi\n"
	.string "ENTRENATZAILE ESKOLAKO gauzak\l"
	.string "soilik badakizkizu.\p"
	.string "Beraz, zure aholkua entzun nahiko nuke.\n"
	.string "Ondo deritzozu, edo?$"

gText_ApprenticeRejectTeaching4::
	.string "Nola? Zregatik diozu ezetz?\n"
	.string "Baina begira nork eskatu dizun!\l"
	.string "Berriz pentsatu beharko duzu!$"

gText_ApprenticeWhichLevelMode4::
	.string "Bueno, ba hau da kontua.\n"
	.string "Nire partez erabaki bat hartu behar duzu.\p"
	.string "BATAILA DORREAK 50 Maila eta Maila\n"
	.string "Irekiko gelak dituela badakizu, ez?\p"
	.string "Niretzat zein da egokiena zure ustez,\n"
	.string "{PLAYER}{KUN}?$"

gText_ApprenticeLevelModeThanks4::
	.string "Ongi, {STR_VAR_1} da egokiena, beraz?\n"
	.string "Esker anitz!\p"
	.string "Erabakiz zuk hartuta,\n"
	.string "{PLAYER}{KUN}, ez zait hainbeste\l"
	.string "inporta galtzen badut ere.\p"
	.string "Ados, Etorriko naiz laguntza eske berriro.\n"
	.string "Aio!$"

gText_ApprenticePleaseTeach5::
	.string "Aupa kaixo! {PLAYER}{KUN}!\n"
	.string "Ezagutzen zaitut, famatua zara!\l"
	.string "{STR_VAR_1} naiz ni! Urte askoan!\p"
	.string "TRIATLETA naiz, beraz, sasoian\n"
	.string "mantentzen naiz, POKéMONak entrenatzean ere.\p"
	.string "Gauza gehiago ere egiten ditut:\n"
	.string "lana, siesta, aretoko dantzak…\p"
	.string "Horren okupatuta nago, ezin\n"
	.string "dudala tamainako ENTRENATZAILE izan.\p"
	.string "beraz, hor doa proposamena!\p"
	.string "Gu ezagutu izanak arrazoiren bat behar du.\n"
	.string "Beraz, {PLAYER}{KUN}, zer iruditzen zaizu\l"
	.string "noizean behin irakasten badidazu?$"

gText_ApprenticeRejectTeaching5::
	.string "Oh, baina, mesedez eskatuz gero?\n"
	.string "Ni bezalako norbaitek zu bezalako\l"
	.string "norbait behar du, {PLAYER}{KUN}!\p"
	.string "Benetan, zure aholkuak behar ditut!$"

gText_ApprenticeWhichLevelMode5::
	.string "Esker mila! Horrela askoz hobe!\n"
	.string "Erraz batekin has gaitezen!\p"
	.string "BATAILA DORREKO bi moduak\n"
	.string "ezagutzen dituzu, baietz?\l"
	.string "50 Maila eta Maila Irekia, hori da.\p"
	.string "Ni bezalako pertsona okupatu batek\n"
	.string "zein aukeratu behar luke?$"

gText_ApprenticeLevelModeThanks5::
	.string "{STR_VAR_1}, beraz? Ulertuta.\n"
	.string "Aterako dut denbora nonbaitetik!\p"
	.string "…Eneeee, lanera joan behar dut!\n"
	.string "Eskerrik asko! Laister arte!$"

gText_ApprenticePleaseTeach6::
	.string "Bai zera! Ez, ez!\n"
	.string "Zu al zara {PLAYER} famatua?\p"
	.string "Izugarria! Ni {STR_VAR_1},\n"
	.string "pozten naiz ezagutzeaz!\p"
	.string "{PLAYER}, zu oso indartsua zara,\n"
	.string "ez al da hala?\p"
	.string "Mundu guztiak hitz egiten du zutaz!\p"
	.string "Ideia bat izan dut!\n"
	.string "Zure aholkuak entzungo ditut, {PLAYER}!\l"
	.string "Horrela seguru indartu egingo naizela!\p"
	.string "Ideia ederra, ezta?\n"
	.string "Mesedez, eman aholkuren bat!$"

gText_ApprenticeRejectTeaching6::
	.string "Kar kar kar, desatseginarena eginda\n"
	.string "ere, ni ez nauzu engainatuko!\l"
	.string "Izatez baiezkoa ematen ari zara, ezta?$"

gText_ApprenticeWhichLevelMode6::
	.string "Bai! Banekien bihotz onekoa zinela,\n"
	.string "{PLAYER}!\p"
	.string "Zer galdetu behar nizuke lehenengo?\n"
	.string "…Ah, Badakit!\p"
	.string "Erredoblea, mesedez!\n"
	.string "Eta nire galdera da…\p"
	.string "BORROKA DORREKO erronka hartzekotan\n"
	.string "zein gomendatuko zenidake?\p"
	.string "50 Maila edo Maila Irekia?\n"
	.string "Zein da egokiagoa?$"

gText_ApprenticeLevelModeThanks6::
	.string "Oh-oh-oh!\n"
	.string "{STR_VAR_1}, orduan!\l"
	.string "Mila esker erantzunagatik!\p"
	.string "Hori da gaurkoz galdetu\n"
	.string "nahi nizun guztia.\p"
	.string "Hurrengoan hemen elkartuko gara\n"
	.string "berriz, ados? Esker mila!$"

gText_ApprenticePleaseTeach7::
	.string "Aizu, barkatu, baina…\n"
	.string "{PLAYER} al zara?\p"
	.string "{STR_VAR_1} naiz, eta asko pozten naiz\n"
	.string "zu ezagutzeaz.\p"
	.string "Aspaldidanik izan naiz zure\n"
	.string "jarraitzailea…\p"
	.string "… … … … … …\p"
	.string "… Espero dut ez dela zuretzat\n"
	.string "enbarazu handia izango, baina…\p"
	.string "Izan al naiteke zure ikaslea,\n"
	.string "{PLAYER}?$"

gText_ApprenticeRejectTeaching7::
	.string "Ene…!\p"
	.string "… … … … … …\n"
	.string "… … … … … …\p"
	.string "…Uste dut konortea galdu dudala.\n"
	.string "Barkatu, gaizki ulertu dizut, uste dut.\p"
	.string "Mesedez! Esan zure ikasle bezala\n"
	.string "onartuko nauzula, mesedez!$"

gText_ApprenticeWhichLevelMode7::
	.string "Ene… Zeinen ongi!\p"
	.string "Ez dizut denbora alferrik galaraziko,\n"
	.string "beraz, lagundu iezadazu honekin.\p"
	.string "BORROKA DORREKO erronkara aurkezteko\n"
	.string "asmotan nabil.\p"
	.string "Hala ere, bi maila daude…\p"
	.string "Zein izango litzateke niretzat onena?\n"
	.string "50 Maila edo Maila Irekia?$"

gText_ApprenticeLevelModeThanks7::
	.string "{STR_VAR_1} da zure aukera, beraz!\n"
	.string "Ongi. Ahal dudan guztia egingo dut!\p"
	.string "Eskerrik asko, {PLAYER}.\n"
	.string "Ea berriro lagun diezadakezun.\l"
	.string "Zaindu zaitez!$"

gText_ApprenticePleaseTeach8::
	.string "Aizu! Aizu! {PLAYER}!\n"
	.string "Nirekin hitz egni duzu!\l"
	.string "Ni… Zein pozik nagoen!\p"
	.string "Ni! Nire izena {STR_VAR_1} da!\n"
	.string "ENTRENATZAILE bilakatu berri naiz!\p"
	.string "Pozten naiz ezagutzeaz, {PLAYER},\n"
	.string "POKéMON munduan entzutetsua zara!\p"
	.string "Oh-oh-oh, badakit!\n"
	.string "Eska diezazuket mesede bat, {PLAYER}?\p"
	.string "Har nazazu zure ikasle gisan!\n"
	.string "Zugandik ikasi nahi nuke!$"

gText_ApprenticeRejectTeaching8::
	.string "Waaaah!\n"
	.string "{PLAYER}, ezetz esan didazu…\l"
	.string "Baina… Izugarria izan behar zen!\p"
	.string "{PLAYER}, faborez! Oraingoan baietz\n"
	.string "esango didazu, ezta?\p"
	.string "Zure laguntza behar dut!$"

gText_ApprenticeWhichLevelMode8::
	.string "Iujuuuu! {PLAYER}(e)k baiez esan dit!\n"
	.string "{PLAYER}(e)k baietz esan dit!\p"
	.string "Ezingo dut lorik egin gaur…\n"
	.string "Mila esker, zinez!\p"
	.string "Orduan, hau da nire galdera!\p"
	.string "BORROKA DORREAN, zein da niretzat\n"
	.string "egokiena, 50. Maila edo Maila irekia?$"

gText_ApprenticeLevelModeThanks8::
	.string "{STR_VAR_1}! Ulertuta!\n"
	.string "Ederki ulertuta, gainera!\l"
	.string "Zinez pozik nago orain!\p"
	.string "Espero dut hurrengo batean gehiago\n"
	.string "irakatsi ahalko didazula.$"

gText_ApprenticePleaseTeach9::
	.string "Baina! Ez al zara zu…\n"
	.string "Zu al zara benetan… {PLAYER}{KUN}?!\l"
	.string "ENTRENATZAILE famatu eta indartsua?\l"
	.string "Ene, nolako zortea izan dudan!\p"
	.string "Kaixo, ni {STR_VAR_1} naiz!\p"
	.string "POKéMON irakasle baten bila\n"
	.string "aritu naiz aspaldian.\p"
	.string "Eta justu zurekin gurutzatu,\n"
	.string "nolako zortea, {PLAYER}{KUN}!\p"
	.string "Ba horixe, {PLAYER}{KUN}!\n"
	.string "Utzi zure ikaslea izaten!$"

gText_ApprenticeRejectTeaching9::
	.string "Eeeeeez!\n"
	.string "Zu guaia eta gogorra zara…\p"
	.string "Ez izan horrelakoa, mesedez.\n"
	.string "Bihotzez eskatzen ari naiz!$"

gText_ApprenticeWhichLevelMode9::
	.string "Izugarria! Hori bai erantzuna!\n"
	.string "Bikaina, esango nuke!\p"
	.string "Hasi gaitezen orduan BORROKA DORREAREN\n"
	.string "inguruko galdera batekin.\p"
	.string "Nire kasuan zein litzateke egokiena?\n"
	.string "50. Maila edo Maila Irekia?$"

gText_ApprenticeLevelModeThanks9::
	.string "Ados, {STR_VAR_1}, beraz!\n"
	.string "Bai jauna!\l"
	.string "Nire indarra erakutsiko dut!\p"
	.string "Ederki, nire irakasletzat hartuko zaitut!\n"
	.string "Aio!$"

gText_ApprenticePleaseTeach10::
	.string "Kaixo, {PLAYER}{KUN}, ezta?\n"
	.string "Polizia zure bila dabil!\p"
	.string "… … …\n"
	.string "Noski gezurretan ari naizela!\p"
	.string "{STR_VAR_1} naiz. Nire itxura\n"
	.string "gorabehera, POKéMON TXAPELDUNA Naiz!\l"
	.string "…Hori ere gezurra zen, bada!\p"
	.string "Honakoa ez da gezurra ordea.\n"
	.string "Ez naiz oso ona borrokan.\p"
	.string "Zer iruditzen zaizu nire irakasle\n"
	.string "bihurtzen bazara?$"

gText_ApprenticeRejectTeaching10::
	.string "Horrela erantzun behar badidazu,\n"
	.string "Zer egin dezakedan erakutsiko dizut!\p"
	.string "Buaaaa! Buaaaa! Buaaaa!\n"
	.string "Zintz!\p"
	.string "Kar-kar, nire MALKO FALTSUAK entzun dituzu!\p"
	.string "Aizu, izango al zara nire POKéMON\n"
	.string "irakaslea, mesedez?$"

gText_ApprenticeWhichLevelMode10::
	.string "Iujuuuu!\n"
	.string "Itsasontzi bat erosiko dizut!\p"
	.string "Hori ere gezurra zen, noski!\n"
	.string "Baina… Eskerrik asko, irakasle!\p"
	.string "BORROKA DORREAN badakizu 50. Maila\n"
	.string "eta Maila Irekia daudela, ezta?\p"
	.string "Duda itzelak izaten ari naiz, eta\n"
	.string "ez dakit zein maila aukeratu…\p"
	.string "Aukeratu dezakezu zuk, irakasle?$"

gText_ApprenticeLevelModeThanks10::
	.string "Ados, {STR_VAR_1} hobe da, orduan!\n"
	.string "Orduan beste mailara apuntutatuko naiz!\p"
	.string "Txantxa da!\n"
	.string "Kasu egindo dizut, irakasle!\p"
	.string "Mila esker, irakasle!\n"
	.string "Gehiago irakatsiko didazula espero dut!$"

gText_ApprenticePleaseTeach11::
	.string "I-E-P-A T-X-O!\n"
	.string "Horrek iepa txo osatzen du!\p"
	.string "{STR_VAR_1} naiz, MARINEL raperoa\n"
	.string "alajaina!\p"
	.string "Zure txanda orain, kontatu zerbait\n"
	.string "zure inguruan, nik ezagutzeko lain!\p"
	.string "Uh-huh, uh-huh!\n"
	.string "{PLAYER}{KUN} zure izena,\l"
	.string "POKÉMONEKIN onena!\p"
	.string "Gaztea zara gainera,\n"
	.string "mundua esploratzeko tankera!\p"
	.string "Bestalde, esan nahi dut\n"
	.string "gaur hitz egin diodan hamargarrena\l"
	.string "zarela, zin egiten dizut.\p"
	.string "Ospatu dezagun biok, orduan!\n"
	.string "Nire irakasle izateko iritsi den orduan!$"

gText_ApprenticeRejectTeaching11::
	.string "Baina!\n"
	.string "Egin lan nirekin!\p"
	.string "Nire galderei erantzunez,\n"
	.string "izan nire irakasle, mesedez!$"

gText_ApprenticeWhichLevelMode11::
	.string "Hori bai itzela!\n"
	.string "{PLAYER}, benetan onena zarela!\p"
	.string "Hau da nire lehen galdera\n"
	.string "zuk erantzute aldera!\p"
	.string "BORROKA DORREAren inguruan da,\n"
	.string "eman iezadazu bultzada!\p"
	.string "50. Maila edo Maila Irekia,\n"
	.string "zein da bietan niretzat egokia?$"

gText_ApprenticeLevelModeThanks11::
	.string "Ongi, {STR_VAR_1} beraz!\n"
	.string "banoa, eta irabaziko dut erraz!\p"
	.string "Zure laguntza behar badut,\n"
	.string "{PLAYER}, dudarik gabe galdetuko dizut!$"

gText_ApprenticePleaseTeach12::
	.string "Ei, kaixo, {PLAYER} al zara?\n"
	.string "Zer egin behar dut? Zurekin hitz egin?\l"
	.string "Zergatik ez? Jada ari naiz eta!\p"
	.string "{PLAYER}, harrituta al zaude?\n"
	.string "Nor naizen kontatuko dizut, berandutu gabe!\p"
	.string "{STR_VAR_1} deitzen didate.\n"
	.string "Munduko gitarrajole onena,\l"
	.string "ezbairik gabe!\p"
	.string "Entzuten al didazu?\n"
	.string "Entzuten didazu!\p"
	.string "Hau zortea nirea,\n"
	.string "eskari hau izango da zurea!\p"
	.string "{PLAYER}, utzi zure ikaslea izaten!\n"
	.string "Guztia ikasi nahi dut, goraipa nazaten!$"

gText_ApprenticeRejectTeaching12::
	.string "Ezezkoa, beraz?\n"
	.string "Berriz galdetuko dizut orduan, erraz!\p"
	.string "{PLAYER}, utzi zure ikaslea izaten!\n"
	.string "Guztia ikasi nahi dut, goraipa nazaten!$"

gText_ApprenticeWhichLevelMode12::
	.string "Hori da, bikain, aizu!\n"
	.string "Bada orduan tipo honek galdera botako dizu.\p"
	.string "BORROKA DORRE inguruan gaudenez,\n"
	.string "horren inguruan egingo dizut galdera, ez?\p"
	.string "Aukera hautetik guztietatik,\n"
	.string "zen hartu behar nuke nik?$"

gText_ApprenticeLevelModeThanks12::
	.string "{STR_VAR_1} dela onena uste baduzu,\n"
	.string "egia izango da, ziur nauzu!\p"
	.string "Beno, {PLAYER}, banoa mundu zabalera,\n"
	.string "ez nazazu ahaztu, itzuliko naiz, atzera.\p"
	.string "Hurrengora arte, nire lagun azkarra!$"

gText_ApprenticePleaseTeach13::
	.string "Iepa, kaixo! Zu, bai!\n"
	.string "Emango zenidake masaje bat sorbaldan?\p"
	.string "…Bai, hortxe! Hori da!\n"
	.string "Ai, ai! Hau bai masaje bikaina!\p"
	.string "Nire izena {STR_VAR_1} da.\n"
	.string "karatea egiten dut, baina nire gorputza\l"
	.string "ez dago kolpeetara ohitua…\p"
	.string "POKéMONAK entrenatzea erabaki dut\n"
	.string "ni ere gogortzeko.\p"
	.string "{PLAYER}{KUN} zara, ezta?\n"
	.string "POKéMON LIGAKO TXAPELDUNA?\p"
	.string "Entzun, emango zenizkidake\n"
	.string "aholku batzuk?$"

gText_ApprenticeRejectTeaching13::
	.string "Zergatik?\p"
	.string "Ez dizut traba handirik egingo!\n"
	.string "Mesedez?$"

gText_ApprenticeWhichLevelMode13::
	.string "Eskerrik asko. Zu bai jatorra!\n"
	.string "…Atxu! Atxu!\p"
	.string "Azkarrago indartu beharko naiz…\p"
	.string "BORROKA DORRERA noa oraintxe, zein\n"
	.string "maila izango litzateke egokiagoa\l"
	.string "niretzat? 50. Maila edo Maila Irekia?$"

gText_ApprenticeLevelModeThanks13::
	.string "Ados. {STR_VAR_1}, orduan.\n"
	.string "Banoa bertara, orduan.\p"
	.string "Espero dut gehiagotan laguntzeko prest egongo\n"
	.string "zarela. Azkenean, nire irakaslea zara!$"

gText_ApprenticePleaseTeach14::
	.string "Bueno… E…\n"
	.string "{PLAYER}{KUN}…?\p"
	.string "Mesedez, ez begiratu horrela.\n"
	.string "Urduri jartzen ari naiz.\p"
	.string "Ni… {STR_VAR_1} naiz.\p"
	.string "Lotsa ematen dit esateak, baina\n"
	.string "antzinako hondakinak aztertzen ditut.\p"
	.string "Are lotsa handiago ematen dit BORROKA\n"
	.string "FRONTEAN dudan interesa adierazteak.\p"
	.string "{PLAYER}{KUN}, jakina da zu ENTRENATZAILE\n"
	.string "indartsua zarela…\p"
	.string "Zaila da niretzat hau esatea, baina\n"
	.string "zeozer galdetu nahi dizut.\p"
	.string "Izango zara nire irakaslea niri\n"
	.string "aholkuak emateko?$"

gText_ApprenticeRejectTeaching14::
	.string "Mesedez, ez esan ezetz!\n"
	.string "Ezingo nuke umiliazio honekin.\p"
	.string "izan nire irakaslea!\n"
	.string "Zure aholkuak behar ditut!$"

gText_ApprenticeWhichLevelMode14::
	.string "Mi-mila esker…\p"
	.string "Baina ez begiratu horrela, mesedez.\n"
	.string "Asko lotsatzen naiz eta.\p"
	.string "Mesedez, erantzun begietara begiratu\n"
	.string "gabe, ahal baduzu.\p"
	.string "BORROKA DORREAN…\n"
	.string "Zein maila aukeratu behar nuke?$"

gText_ApprenticeLevelModeThanks14::
	.string "Bada… Ados!\n"
	.string "Saiatuko naiz, orduan.\p"
	.string "Ea lortzen dudan lotsatu gabe\n"
	.string "erronkan ongi moldatzea…\p"
	.string "Eskerrik asko, {PLAYER}{KUN}.\n"
	.string "Berriz aurkitzen bazaitut, ziur nago\l"
	.string "lagungarria izango zarela.$"

gText_ApprenticePleaseTeach15::
	.string "Nola? {PLAYER}{KUN} zara, esango nuke…\n"
	.string "Benetakoa zara, ordea?\p"
	.string "Niri {STR_VAR_1} dei diezadakezu.\p"
	.string "ENTRENATZAILE indartsu baten ikasle\n"
	.string "izatea pentsatzen aritu naiz azkenaldian.\p"
	.string "Beno, badirudi zortea izan dudala!\n"
	.string "…{PLAYER}{KUN} zara benetan, ezta?\p"
	.string "Ez, ez, hala bada, bikain.\n"
	.string "Zure ikasle bezala hartzea soilik\l"
	.string "nahi nuke.$"

gText_ApprenticeRejectTeaching15::
	.string "Zer?\n"
	.string "Baina zergatik esan didazu ezetz?\p"
	.string "Barkatu ez sinesteagatik nor zinen\n"
	.string "benetan.\p"
	.string "Mesedez, barka iezadazu eta\n"
	.string "har nazazu ikasletzat.$"

gText_ApprenticeWhichLevelMode15::
	.string "Benetan hartuko nauzu?\n"
	.string "Ez dut aldez aurretik ospatuko.\p"
	.string "Egiatan ari bazara, barkatu.\n"
	.string "Baina orain zure aholkua behar dut.\p"
	.string "BORROKA DORRERA joatekoa naiz,\n"
	.string "zein maila aukeratu behar nuke?\l"
	.string "50. Maila edo Maila Irekia?$"

gText_ApprenticeLevelModeThanks15::
	.string "{STR_VAR_1}?\n"
	.string "Ziur al zaude?\p"
	.string "Ongi. Zuk hala badiozu, hala izango da.\n"
	.string "Eskerrik asko zure denboragatik.\p"
	.string "Badakit astuna izan naitekeea, baina\n"
	.string "eskertzen dizut ni onartu izana.\p"
	.string "Ea berriz elkartzen garen!$"

gText_ApprenticeWhatHeldItem0::
	.string "Ai… Zintz…\n"
	.string "Ene, {PLAYER}!\p"
	.string "Dilema izugarria daukat eta ez\n"
	.string "dakiz zer aukeratu.\p"
	.string "Ez dakit zein item eman nire\n"
	.string "{STR_VAR_1}(e)ri.\p"
	.string "mesedez, esan, {PLAYER}.\n"
	.string "Zein item eduki behar luke?$"

gText_ApprenticeHoldNothing0::
	.string "Benetan? Ez nioke objekturik\n"
	.string "eman behar {STR_VAR_1}(e)ri?$"

gText_ApprenticeThanksNoHeldItem0::
	.string "Ongi! Eskerrak lagundu didazun!\n"
	.string "Bikain! Itzel! Iujuuu!\p"
	.string "Eskerrik asko, zinez!$"

gText_ApprenticeThanksHeldItem0::
	.string "Ah, eskerrak…\n"
	.string "Uste dut badaukadala {STR_VAR_1} bat.\p"
	.string "Eskerrak lagundu didazun!\n"
	.string "Bikain! Itzel! Iujuuu!\p"
	.string "Eskerrik asko, zinez!$"

gText_ApprenticeItemAlreadyRecommended0::
	.string "Eeeez! Ez izan horrelakoa, faborez!\p"
	.string "{STR_VAR_1} itema jada gomendatu\n"
	.string "didate lehenago. Zintz…\p"
	.string "Edo hobe al litzateke ez ematea\n"
	.string "itemik {STR_VAR_2}(e)ri?$"

gText_ApprenticeWhatHeldItem1::
	.string "Bai jauna! {PLAYER} da eta!\n"
	.string "Itzel! Zerbait galdetu behar dizut!\p"
	.string "Ematen dizkiezu itemak zure POKéMONEI?\n"
	.string "Nireei eman nahi nizkieke, baina…\p"
	.string "Zein item litzateke egokia nire\n"
	.string "{STR_VAR_1}(r)entzat?\p"
	.string "Zer uste duzu?$"

gText_ApprenticeHoldNothing1::
	.string "Zer? Nire {STR_VAR_1}(e)k ez luke\n"
	.string "objekturik eduki behar?$"

gText_ApprenticeThanksNoHeldItem1::
	.string "Ados, ulertuta! Horixe egingo dut!\n"
	.string "Eskerrik asko aholkuagatik!$"

gText_ApprenticeThanksHeldItem1::
	.string "Ados! {STR_VAR_1}, beraz?\n"
	.string "Bikain, Horixe egingo dut!\p"
	.string "Eskerrik asko aholkuagatik!$"

gText_ApprenticeItemAlreadyRecommended1::
	.string "Ez, ez. Ez nuen hori esan nahi.\n"
	.string "Ezagutzen ditudan itemak ez, zerbait\l"
	.string "berria izan behar da.\p"
	.string "Edo esan nahi duzu nire POKéMONAK\n"
	.string "ez duela itemik behar?$"

gText_ApprenticeWhatHeldItem2::
	.string "{PLAYER}, kaixo!\n"
	.string "Nire {STR_VAR_1}(r)en inguruan da…\p"
	.string "Item egoki bat eman nahi diot.\n"
	.string "Zer eman behar nioke zure ustez?$"

gText_ApprenticeHoldNothing2::
	.string "Orduan nire {STR_VAR_1}(e)k ez du\n"
	.string "itemik behar?$"

gText_ApprenticeThanksNoHeldItem2::
	.string "ongi, ulertuta!\n"
	.string "Hurrengora arte!$"

gText_ApprenticeThanksHeldItem2::
	.string "Beraz, {STR_VAR_1} itema?\n"
	.string "Ulertuta!\p"
	.string "Saiatuko naiz bat aurkitzen!\n"
	.string "Hurrengora arte!$"

gText_ApprenticeItemAlreadyRecommended2::
	.string "Norbaitek esan zidan emateko\n"
	.string "{STR_VAR_1}, bai.\p"
	.string "Beste item mota bat nahi dut\n"
	.string "nire POKéMONARENTZAT.\p"
	.string "Edo agian {STR_VAR_2}(e)k ez du\n"
	.string "itemik behar?$"

gText_ApprenticeWhatHeldItem3::
	.string "Kaixo, {PLAYER}…\n"
	.string "Barkatu traba egitea, baina beste\l"
	.string "galdera bat dut zuretzat.\p"
	.string "Uste dut orain nabilen bezala ez\n"
	.string "naizela gai borrokak irabazteko, beraz,\l"
	.string "{STR_VAR_1}(e)ri item bat eman nahi diot.\p"
	.string "Baina ez dakit zein item eman.\p"
	.string "{PLAYER}, mesedez, erabakiko zenuke\n"
	.string "nire partez?$"

gText_ApprenticeHoldNothing3::
	.string "Nire POKéMONAK hobe egongo lirateke\n"
	.string "inolako itemik gabe?$"

gText_ApprenticeThanksNoHeldItem3::
	.string "Ulertzen dut…\n"
	.string "Ez nintzateke itemen menpe egon behar.\l"
	.string "Saiatuko naiz ez erabiltzen!\p"
	.string "Eskerrik asko, benetan!$"

gText_ApprenticeThanksHeldItem3::
	.string "{STR_VAR_1} itema, beraz.\n"
	.string "Ez dakit ea bat lortuko dudan…\l"
	.string "Ez! Noski lortuko dudala.\p"
	.string "Eskerrik asko, benetan!$"

gText_ApprenticeItemAlreadyRecommended3::
	.string "Baina, baina…\n"
	.string "Uste dut ezagutzen dudala itema jada…\p"
	.string "Agian ez dut ondo erabili {STR_VAR_1}\n"
	.string "itema orain arte?\p"
	.string "Edo ez nioke itemik eman behar\n"
	.string "nire {STR_VAR_2}(e)ri?$"

gText_ApprenticeWhatHeldItem4::
	.string "Ei, {PLAYER}{KUN}.\n"
	.string "Zerbait galdetu nahi nizuke.\p"
	.string "gogoratzen zara niretzako POKéMON\n"
	.string "bat aukeratzeko eskatu nizula?\p"
	.string "Bada, ez nizun galdetu zein\n"
	.string "item eman behar nion.\p"
	.string "Jada lagundu didazunez,\n"
	.string "lagunduko zenidake bigarrenez?\p"
	.string "Zer litzateke egokia? Zeozer eman\n"
	.string "nahi diot {STR_VAR_1}(e)ri.$"

gText_ApprenticeHoldNothing4::
	.string "Ah! Nire {STR_VAR_1}(e)k orduan\n"
	.string "ezer gabe borrokatu behar luke?$"

gText_ApprenticeThanksNoHeldItem4::
	.string "Hori dela onena uste baduzu, hala bedi.\p"
	.string "Zuk hartu duzunez erabakia,\n"
	.string "{PLAYER}{KUN}, ez naiz haserretuko\l"
	.string "galtzen badut.\p"
	.string "Ongi, bueltatuko naiz aholku bila.\n"
	.string "Aio!$"

gText_ApprenticeThanksHeldItem4::
	.string "{STR_VAR_1} itema, beraz?\n"
	.string "Ez dago gaizki. Erabiliko dut!\p"
	.string "Zuk hartu duzunez erabakia,\n"
	.string "{PLAYER}{KUN}, ez naiz haserretuko\l"
	.string "galtzen badut.\p"
	.string "Ongi, bueltatuko naiz aholku bila.\n"
	.string "Aio!$"

gText_ApprenticeItemAlreadyRecommended4::
	.string "Zer? Zer diozu, baina?\n"
	.string "Jada esan zenidan {STR_VAR_1}\l"
	.string "emateko.\p"
	.string "Edo esan nahi duzu {STR_VAR_2} itemik\n"
	.string "gabe ibili behar dela?$"

gText_ApprenticeWhatHeldItem5::
	.string "Ei, {PLAYER}{KUN}!\p"
	.string "Biok okupatuta, baina hala ere\n"
	.string "beti elkar ikusten dugu azkenean!\p"
	.string "Gaur, pixka bat ibili, garbitu\n"
	.string "eta erratza pasa behar dut.\p"
	.string "Ez dut denborarik izan ezer erosteko\n"
	.string "nire {STR_VAR_1} maitearentzat.\p"
	.string "Denborarik ez dudanez, aholkatuko\n"
	.string "zenidake zein item eman nire\l"
	.string "{STR_VAR_1}(e)ri?$"

gText_ApprenticeHoldNothing5::
	.string "Mutil okupatua naizenez, ez nioke\n"
	.string "itemik eman behar {STR_VAR_1}(e)ri?$"

gText_ApprenticeThanksNoHeldItem5::
	.string "Ongi, ulertuta.\n"
	.string "Ez dut horretarako denborarik behar.\p"
	.string "Mila esker!\n"
	.string "Ondo ibili!$"

gText_ApprenticeThanksHeldItem5::
	.string "Ongi, ulertuta.\n"
	.string "Aterako dut denbora gomendatutako\l"
	.string "{STR_VAR_1} erosteko.\p"
	.string "Eskerrak irakasle bikaina zaren.\n"
	.string "Mila esker! Ondo ibili!$"

gText_ApprenticeItemAlreadyRecommended5::
	.string "Zer? jada ezagutzen dut\n"
	.string "{STR_VAR_1}, ordea.\p"
	.string "Ah, ulertzen dut.\n"
	.string "Mutil okupatua naizenez, ez nioke\l"
	.string "itemik eman behar {STR_VAR_2}(e)ri?$"

gText_ApprenticeWhatHeldItem6::
	.string "Iepa, {PLAYER}! Ni naiz!\n"
	.string "Zure laguntza bila nator gaur.\l"
	.string "Mesedez, zure aholkua behar dut!\p"
	.string "Erredoblea, mesedez!\n"
	.string "Nire galdera da…\p"
	.string "Nire {STR_VAR_1}(e)ri item bat\n"
	.string "ematekotan, zein eman behar nioke?$"

gText_ApprenticeHoldNothing6::
	.string "Benetan? Nire {STR_VAR_1}(e)k ez du\n"
	.string "itemik behar, zure iritziz.$"

gText_ApprenticeThanksNoHeldItem6::
	.string "Ongi, hori egingo dut orduan!\p"
	.string "Hori da gaurkoz galdetu nahi\n"
	.string "nizun guztia.\p"
	.string "Hemen elkartuko gara berriz, bai?\n"
	.string "Eskerrik asko!$"

gText_ApprenticeThanksHeldItem6::
	.string "Bikain! {STR_VAR_1}, beraz.\n"
	.string "Hori bai aukera bikaina!\l"
	.string "Probatuko dut, bai!\p"
	.string "hori da gaurkoz galdetu nahi\n"
	.string "nizun guztia.\p"
	.string "Hemen elkartuko gara berriz, bai?\n"
	.string "Eskerrik asko!$"

gText_ApprenticeItemAlreadyRecommended6::
	.string "Kar-kar! Zu bai zu bromazalea!\n"
	.string "Jada esan zenidan {STR_VAR_1}\l"
	.string "erabiltzeko aurrekoan!\p"
	.string "Ondo al zaude, {PLAYER}?\p"
	.string "Itxaron! Nire {STR_VAR_2}(e)k ez\n"
	.string "duela itemik behar esan nahi duzu.$"

gText_ApprenticeWhatHeldItem7::
	.string "Kaixo, {PLAYER}. Ondo zaudela\n"
	.string "espero dut.\p"
	.string "galde diezazuket zerbait?\p"
	.string "Duela gutxi, borroka batean,\n"
	.string "nire aurkariak item bat eman\l"
	.string "zion bere POKéMONARI.\p"
	.string "Horregatik galdu nuen…\p"
	.string "Eta ez nuke nahi atzean gelditu.\n"
	.string "Nire {STR_VAR_1}(e)k item bat\l"
	.string "edukitzea nahi dut.\p"
	.string "Nire POKéMONARENTZAT item bat\n"
	.string "aukeratzen lagunduko bazenit…$"

gText_ApprenticeHoldNothing7::
	.string "Bestela esanda… Nire POKéMONAK ez\n"
	.string "du itemik behar?$"

gText_ApprenticeThanksNoHeldItem7::
	.string "Ondo ulertzen dut orain!\n"
	.string "Horrela saiatuko naiz orduan.\p"
	.string "Eskerrik asko, {PLAYER}.\n"
	.string "Espero dut gehiagotan lagunduko didazula.\l"
	.string "Zaindu zaitez!$"

gText_ApprenticeThanksHeldItem7::
	.string "{STR_VAR_1}, orduan!\n"
	.string "Oraintxe bertan eskatuko dut.\p"
	.string "Eskerrik asko, {PLAYER}.\n"
	.string "Espero dut gehiagotan lagunduko didazula.\l"
	.string "Zaindu zaitez!$"

gText_ApprenticeItemAlreadyRecommended7::
	.string "Bai, esan zenidan hori aurrekoan,\n"
	.string "eta jada probatu nuen.\p"
	.string "Edo esan nahi duzu… Nire POKéMONAK\n"
	.string "ez duela itemik behar?$"

gText_ApprenticeWhatHeldItem8::
	.string "Iei! {PLAYER}!\n"
	.string "Nolako poza ematen didan zu berriz ikusteak!\p"
	.string "Oh-oh-oh! Zerbait galdetu nahi\n"
	.string "nizuke, {PLAYER}!\p"
	.string "Mesedez esan zein item eman\n"
	.string "nire {STR_VAR_1}(e)ri!$"

gText_ApprenticeHoldNothing8::
	.string "Ene! Ez nuen erantzun hori espero!\n"
	.string "Beraz, ez da beharrezkoa item bat ematea?$"

gText_ApprenticeThanksNoHeldItem8::
	.string "Bikain, ulertuta!\n"
	.string "Ez diot itemik emango, orduan!\p"
	.string "Beste batean are gehiago erakutsiko\n"
	.string "didazula espero dut.$"

gText_ApprenticeThanksHeldItem8::
	.string "{STR_VAR_1}! Hori erabiliko du!\p"
	.string "Eta… Posible da, {PLAYER}, zuk ere\n"
	.string "POKéMONARI item hori ematea?\p"
	.string "Nik behintzat bat lortuko dut!\n"
	.string "Hurrengoan are gehiago erakutsiko\l"
	.string "didazula espero dut.$"

gText_ApprenticeItemAlreadyRecommended8::
	.string "Zer? Gomendatu zenida\n"
	.string "{STR_VAR_1} lehenago, baina.\p"
	.string "Hori al da objektu onena?\n"
	.string "Edo esan nahi duzu {STR_VAR_2}(e)k\l"
	.string "ez duela itemik behar?$"

gText_ApprenticeWhatHeldItem9::
	.string "Aupa!\n"
	.string "Nire irakaslea, {PLAYER}{KUN}!\p"
	.string "Zure aholkua behar dut POKéMON\n"
	.string "erreminten gainean.\p"
	.string "Zein litzateke objektu on bat\n"
	.string "nire {STR_VAR_1}(r)entzat?\p"
	.string "Ez izan lotsarik.\n"
	.string "Bota, bota!$"

gText_ApprenticeHoldNothing9::
	.string "Zer? Nire {STR_VAR_1}(e)k ez duela\n"
	.string "zertan itemik eduki?$"

gText_ApprenticeThanksNoHeldItem9::
	.string "Bai, bikain!\n"
	.string "Horrela saiatuko naiz, beraz!\p"
	.string "Bikain, eskerrik asko, beti legez!\n"
	.string "Aio!$"

gText_ApprenticeThanksHeldItem9::
	.string "Ados, {STR_VAR_1}, orduan?\n"
	.string "Bai, bikain!\l"
	.string "Saiatuko naiz ziztuan bat bilatzen!\p"
	.string "Bikain, eskerrik asko, beti legez!\n"
	.string "Aio!$"

gText_ApprenticeItemAlreadyRecommended9::
	.string "Ez, ez! Jada esan zenidan\n"
	.string "{STR_VAR_1} erabiltzeko.\p"
	.string "Itxaron segundu bat…\n"
	.string "Esan nahi duzu {STR_VAR_2}(e)k\l"
	.string "itemik gabe irabazi dezakeela?$"

gText_ApprenticeWhatHeldItem10::
	.string "{PLAYER}{KUN}, zerbait izugarria\n"
	.string "gertatu da!\p"
	.string "Goizean esnatu eta nire POKéMONAK\n"
	.string "10 URREZKO PIPITA zituen!\p"
	.string "Noski gezurra dela!\n"
	.string "Kar-kar!\p"
	.string "Hau egia da, ordea.\n"
	.string "Ez naiz oso ona nire POKéMONARENTZAT\l"
	.string "item egokiak aukeratzen.\p"
	.string "Aukeratuko zenuke nire partez\n"
	.string "zein item eman {STR_VAR_1}(e)ri?$"

gText_ApprenticeHoldNothing10::
	.string "Zer esan nahi duzu?\n"
	.string "Ez emateko objekturik?$"

gText_ApprenticeThanksNoHeldItem10::
	.string "Ongi, beraz, ez ezer emateko diozu.\n"
	.string "Beno, ba orduan banoa zerbait erostera!\p"
	.string "Txantxa da!\n"
	.string "Kasu egingo dizut, irakasle!\p"
	.string "Eskerrik asko, irakasle!\n"
	.string "Gehiago irakatsiko didazula espero dut!$"

gText_ApprenticeThanksHeldItem10::
	.string "Ongi, orduan, {STR_VAR_1}!\n"
	.string "Hori ez, beste edozer emango diot orduan!\p"
	.string "Txantxa da!\n"
	.string "Kasu egingo dizut, irakasle!\p"
	.string "Eskerrik asko, irakasle!\n"
	.string "Gehiago irakatsiko didazula espero dut!$"

gText_ApprenticeItemAlreadyRecommended10::
	.string "Baina, esan didazu hori lehenago,\n"
	.string "ez da hala?\p"
	.string "Ez al dago beste ezer, bada?\p"
	.string "Edo esan nahi duzula ez emateko\n"
	.string "ezer {STR_VAR_2}(e)ri?$"

gText_ApprenticeWhatHeldItem11::
	.string "I-E-P-A T-X-O!\n"
	.string "Horrek iepa txo osatzen du!\p"
	.string "MARINEL raperoa naiz ni!\n"
	.string "Eta zuretzat galdera bat\l"
	.string "dut, hala bedi!\p"
	.string "Galdera itemen inguruan da,\n"
	.string "ea erantzuten didazun, di-da!\p"
	.string "Nire {STR_VAR_1}(e)k itema behar du.\n"
	.string "Zer emango diot, irabazi nahi badu?$"

gText_ApprenticeHoldNothing11::
	.string "Benetan ari al zara?\n"
	.string "Nire {STR_VAR_1}(e)k ez duela\l"
	.string "itemik behar? Hara!$"

gText_ApprenticeThanksNoHeldItem11::
	.string "Ongi, ongi. Ulertze dizut!\n"
	.string "Nire POKéMONA esku hutsik utziko dut!\p"
	.string "Eta aholkurik behar badut,\n"
	.string "{PLAYER}, zuri galdetuko dizut!$"

gText_ApprenticeThanksHeldItem11::
	.string "Ongi, {STR_VAR_1} orduan,\n"
	.string "aise erabiliko dut hurrengo enkontruan.\l"
	.string "Zuri galdetzea ideia bikaina da beti!\p"
	.string "Eta aholkurik behar badut,\n"
	.string "{PLAYER}, zuri galdetuko dizut!$"

gText_ApprenticeItemAlreadyRecommended11::
	.string "Ongi, {STR_VAR_1}, beraz?\n"
	.string "Hori esan zenidan aurrekoan.\l"
	.string "Zeozer berria behar dut gaurkoan.\p"
	.string "Edo, zer esan nahi duzu?\n"
	.string "Nire POKéMONAK itemik ez duela\l"
	.string "behar, aizu?$"

gText_ApprenticeWhatHeldItem12::
	.string "Ei, aupa, {PLAYER}!\n"
	.string "Aurkitu zaitut berriro!\p"
	.string "Zer egin behar nuke? Zuri aholkua eskatu?\n"
	.string "Zergatik ez? Jada ari naiz eta!\p"
	.string "{PLAYER}, nitaz nazkatzen ari zara?\n"
	.string "Ez, bai zera, hori ezinezkoa da.\p"
	.string "Entzungo zenidake?\n"
	.string "Aholku bila nabil, zureak\l"
	.string "asko lagunduko lidake.\p"
	.string "{STR_VAR_1}(r)entzat item\n"
	.string "egoki baten bila ari naiz.\l"
	.string "Aukeratzea kostatzen zait maiz.$"

gText_ApprenticeHoldNothing12::
	.string "Nire {STR_VAR_1}(e)k ez du ezer behar?\n"
	.string "Nahiz borroka egin egun guztian zehar?$"

gText_ApprenticeThanksNoHeldItem12::
	.string "Ezer ez edukitzea bada onena,\n"
	.string "hori da izango duena!\p"
	.string "Beno, {PLAYER}, banoa mundu zabalera,\n"
	.string "ez nazazu ahaztu, itzuliko naiz, atzera.\p"
	.string "Hurrengora arte, nire lagun azkarra!$"

gText_ApprenticeThanksHeldItem12::
	.string "{STR_VAR_1} edukitzea bada onena,\n"
	.string "horixe da izango duena!\p"
	.string "Beno, {PLAYER}, banoa mundu zabalera,\n"
	.string "ez nazazu ahaztu, itzuliko naiz, atzera.\p"
	.string "Hurrengora arte, nire lagun azkarra!$"

gText_ApprenticeItemAlreadyRecommended12::
	.string "Ez al didazu lehenago esan\n"
	.string "{STR_VAR_1} emateko?\l"
	.string "Badakit baietz, ni bainaiz memoria oneko!\p"
	.string "Zeozer berria esan behar didazu!\n"
	.string "Edo {STR_VAR_2}(e)k ez du ezer behar, aizu?\l"
	.string "Ez al du objekturik behar benetan?$"

gText_ApprenticeWhatHeldItem13::
	.string "Ai! Autx! {PLAYER}{KUN}, besoa hautsia dut!\n"
	.string "Ez ukitu, mesedez!\p"
	.string "Agian itemak eusten probatzen ari nintzela\n"
	.string "hautsi dut, POKéMONEN plantak egitea\l"
	.string "ez da gauza makala!\p"
	.string "Beraz, kontuak kontu, erabakitzen\n"
	.string "lagundu behar didazu.\p"
	.string "{PLAYER}{KUN}, zei item da nire\n"
	.string "{STR_VAR_1}(r)entzat egokia?$"

gText_ApprenticeHoldNothing13::
	.string "Autx…\p"
	.string "Beraz, nire {STR_VAR_1}(e)k itemik\n"
	.string "ez edukitzea gomendatzen didazu?$"

gText_ApprenticeThanksNoHeldItem13::
	.string "Ados, bada. Errazago niretzat,\n"
	.string "besoa nola dudan kontuan hartuta.\p"
	.string "Gehiagotan laguntza eske etorriko\n"
	.string "naiz, inporta ez badizu.$"

gText_ApprenticeThanksHeldItem13::
	.string "Ados, bada. {STR_VAR_1} orduan.\n"
	.string "Nire POKéMONAK ondo du besoa,\l"
	.string "ez du arazorik izango hartzeko.\p"
	.string "Gehiagotan laguntza eske etorriko\n"
	.string "naiz, inporta ez badizu.$"

gText_ApprenticeItemAlreadyRecommended13::
	.string "Ez, ez, gomendatu zenidan\n"
	.string "{STR_VAR_1} lehenago, gogoratzen?\p"
	.string "Zergatik ez didazu beste zerbait\n"
	.string "esaten, are hobea?\p"
	.string "Ene, itxaron.\n"
	.string "Esan nahi duzuna da {STR_VAR_2}(e)k\l"
	.string "ez duela ezer eduki beharrik?$"

gText_ApprenticeWhatHeldItem14::
	.string "E… Bueno…\n"
	.string "{PLAYER}{KUN}…\p"
	.string "Mesedez, ez begiratu horrela.\n"
	.string "Nire POKéMONEK ez daukate ezer.\p"
	.string "Niri… Lotsa handia ematen dit honek,\n"
	.string "baina zure aholkua behar dut, zinez.\p"
	.string "Ez dakit zein item erabili nire\n"
	.string "{STR_VAR_1} indartsuagoa izan dadin.\p"
	.string "{PLAYER}{KUN}, zure ustez zer litzateke\n"
	.string "egokia?$"

gText_ApprenticeHoldNothing14::
	.string "Beraz… Uste duzu egokiena {STR_VAR_1}\n"
	.string "item gabe uztea dela?$"

gText_ApprenticeThanksNoHeldItem14::
	.string "Beno… Ados!\n"
	.string "Item gabe utziko dut orduan.\p"
	.string "Pixka bat urduritzen nau, baina.\n"
	.string "Ez al litzateke apartegia izango?\p"
	.string "Eskerrik asko, {PLAYER}{KUN}.\n"
	.string "Berriz aurkitzen bazaitut, ziur nago\l"
	.string "lagungarria izango zarela.$"

gText_ApprenticeThanksHeldItem14::
	.string "Beno… Ados!\n"
	.string "{STR_VAR_1} emango diot orduan.\p"
	.string "Pixka bat urduritzen nau, baina.\n"
	.string "Ez al litzateke apartegia izango?\p"
	.string "Eskerrik asko, {PLAYER}{KUN}.\n"
	.string "Berriz aurkitzen bazaitut, ziur nago\l"
	.string "lagungarria izango zarela.$"

gText_ApprenticeItemAlreadyRecommended14::
	.string "B-baina jada ezagutzen dut hori.\p"
	.string "mesedez, zerbait berria behar dut!\n"
	.string "Ezingo nuke umiliazio honekin.\p"
	.string "Edo oker ari ote naiz?\n"
	.string "Uste duzu {STR_VAR_2} hobe moldatuko\l"
	.string "litzatekeela itemik gabe?$"

gText_ApprenticeWhatHeldItem15::
	.string "Zer? {PLAYER}{KUN} zarela dirudi…\n"
	.string "Baina zu al zara benetan?\l"
	.string "Agian bere bikia zara?\p"
	.string "Ez, ez, ez, ez kezkatu!\n"
	.string "Benetan {PLAYER} bazara, barkatu\l"
	.string "nire atrebentzia, mesedez.\p"
	.string "Zure aholku bikainen bila\n"
	.string "nabil gaur ere.\p"
	.string "Nire {STR_VAR_1} dut hemen eta\n"
	.string "item egoki bat eman nahi nioke.\p"
	.string "Zein litzateke egokiena?$"

gText_ApprenticeHoldNothing15::
	.string "Hobe dela ezer ez ematea?\n"
	.string "Ziur al zaude?$"

gText_ApprenticeThanksNoHeldItem15::
	.string "Ados. Zuk hala badiozu, hala izango da.\n"
	.string "Eskerrik asko zure denboragatik.\p"
	.string "Hurrengora arte!$"

gText_ApprenticeThanksHeldItem15::
	.string "{STR_VAR_1}, beraz?\n"
	.string "Ziur al zaude?\p"
	.string "Ados. Zuk hala badiozu, hala izango da.\n"
	.string "Eskerrik asko zure denboragatik.\p"
	.string "Espero dut nire POKéMONAK gai\n"
	.string "izango direla ondo erabiltzeko.\p"
	.string "Hurrengora arte!$"

gText_ApprenticeItemAlreadyRecommended15::
	.string "Ez, ez, itxaron pixka bat.\n"
	.string "Esango nuke hori jada gomendatu didazula.\p"
	.string "Gaur zerbait desberdina gomendatzea\n"
	.string "gustatuko litzaidake.\p"
	.string "Agian esan nahi duzu ez lukeela\n"
	.string "ezer eduki behar {STR_VAR_2}(e)k?\l"
	.string "Ziur al zaude?$"

gText_ApprenticeWhichMonFirst0::
	.string "Buaa, {PLAYER}!\n"
	.string "Dilema bat dut, zintz…\p"
	.string "Beste batzuen aurka borrokan hasi\n"
	.string "nahi dut, baina ez dakit zer egin.\p"
	.string "Nola atera behar nituzke POKéMONAK\n"
	.string "ahalik eta talde indartsuena izateko?\p"
	.string "Esan mesedez, {PLAYER}.\n"
	.string "Nire lekuan, POKéMON hauetatik zein\l"
	.string "aterako zenuke lehenengo?$"

gText_ApprenticeMonFirstThanks0::
	.string "Nire {STR_VAR_1} atera behar nuke?\n"
	.string "Buaaaaa!\p"
	.string "Ai! Barkatu!\n"
	.string "Horren pozik jarri naiz zure\l"
	.string "aholkuagatik, negarrez hasi naizela…\p"
	.string "Eskerrik asko, benetan!$"

gText_ApprenticeWhichMonFirst1::
	.string "Bai! {PLAYER} zara!\n"
	.string "Bikain! galdera bat dut zuretzat!\p"
	.string "Em, nire POKéMONEN artean,\n"
	.string "zein aterako zenuke lehenengo?$"

gText_ApprenticeMonFirstThanks1::
	.string "{STR_VAR_1}? Egia, hala behar du.\n"
	.string "Ados, hori egingo dut!\p"
	.string "Eskerrik asko irakasteagatik!$"

gText_ApprenticeWhichMonFirst2::
	.string "{PLAYER}, kaixo!\p"
	.string "Nire ustez, borroka batean oso garrantzitsua\n"
	.string "da zein POKéMON atera lehenengo.\p"
	.string "Nire POKéMONEN artean,\n"
	.string "zein atera behar nuke lehenengo?$"

gText_ApprenticeMonFirstThanks2::
	.string "Nire {STR_VAR_1} aterako zenuke?\n"
	.string "Ados, ulertuta!\p"
	.string "Hurrengora arte!$"

gText_ApprenticeWhichMonFirst3::
	.string "Kaixo, {PLAYER}…\n"
	.string "Beste galdera bat egin behar dizut,\l"
	.string "barkatu eragozpenak.\p"
	.string "Horren konfidantza gutx dut nire buruan,\n"
	.string "zu gabe galdua nintzateke, {PLAYER}.\p"
	.string "Agian denbora galtze bat soilik\n"
	.string "izango da, baina ez dakit zein erabaki\l"
	.string "hartu oraindik…\p"
	.string "Zein POKéMON atera behar nuke lehenengo\n"
	.string "bororka batean?$"

gText_ApprenticeMonFirstThanks3::
	.string "Nire {STR_VAR_1}?\n"
	.string "Ulertuta!\p"
	.string "Ezin dut sinetsi horrenbestetan nire\n"
	.string "galderak erantzuteko prest egotea!\p"
	.string "Bihotzez eskertzen dizut nirekin hitz\n"
	.string "egiteko denbora hartzea… Mila esker!$"

gText_ApprenticeWhichMonFirst4::
	.string "Ei, {PLAYER}{KUN}! Ni naiz!\n"
	.string "Eskerrak aurkitu zaitudan, arazo\l"
	.string "txiki bat dut eta.\p"
	.string "Ez dakit zein ordenatan jarri nire\n"
	.string "POKéMONAK. Lagunduko zenidake?\p"
	.string "Ez duzu talde osoa aukeratu behar\n"
	.string "oraintxe bertan.\p"
	.string "Zer iruditzen zaizu lehenengo\n"
	.string "POKéMONA aukeratzen badidazu?$"

gText_ApprenticeMonFirstThanks4::
	.string "Nire {STR_VAR_1}? Bikain!\p"
	.string "Erabakia zuk hartu duzunez,\n"
	.string "{PLAYER}{KUN}, ez naiz haserretuko\l"
	.string "galtzen badut ere.\p"
	.string "Ongi. Etorriko naiz laguntza eske berriz.\n"
	.string "Aio!$"

gText_ApprenticeWhichMonFirst5::
	.string "Kaixo, {PLAYER}{KUN} irakaslea!\n"
	.string "Gaur ere lanpetuta nabil!\p"
	.string "Bizikletan ibili behar naiz eta erosketak\n"
	.string "egin eta beste mila gauza.\p"
	.string "Ez daukat denborarik nire POKéMONEN\n"
	.string "taldearen ordena aukeratzeko ere.\p"
	.string "Zer iruditzen zaizu nire taldea?\n"
	.string "Zein jarri behar nuke lehenengo?$"

gText_ApprenticeMonFirstThanks5::
	.string "Ados, ulertuta.\n"
	.string "Badut denbora behintzat {STR_VAR_1}\l"
	.string "taldearen buru jartzeko!\p"
	.string "Uuuups, neskalaguna zain dut!\n"
	.string "Mila esker! Ikusi arte!$"

gText_ApprenticeWhichMonFirst6::
	.string "Iujuuu! Aupa, {PLAYER}!\n"
	.string "Beti indartsu itxura duzu ibiltzean!\p"
	.string "Entzun, zerbait galdetu behar dizut\n"
	.string "berriro! Betiko antzean!\p"
	.string "Erredoblea, mesedez!\n"
	.string "Nire taldearen inguruko galdera da.\p"
	.string "Zein POKéMON jarri behar nuke\n"
	.string "lehenengo borroka baterako?$"

gText_ApprenticeMonFirstThanks6::
	.string "Ados!\n"
	.string "Nire {STR_VAR_1}, diozu!\l"
	.string "Hori bai erantzun bikaina!\p"
	.string "Hori da gaurkoz galdetu nahi\n"
	.string "nizun guztia.\p"
	.string "Hemen elkartuko gara berriz, bai?\n"
	.string "Eskerrik asko!$"

gText_ApprenticeWhichMonFirst7::
	.string "Eskerrik asko nirekin hizketan\n"
	.string "geratzeagatik, {PLAYER}.\p"
	.string "Badakit zure apaltasuna aprobetxatzen\n"
	.string "ari naizela, baina aholkua eska dakizuket?\p"
	.string "Nire POKéMON taldearen ordena aukeratzeko\n"
	.string "eskatu nahi nizuke.\p"
	.string "Asko eskertuko nizuke lehenengo zein\n"
	.string "POKéMON atera esango bazenit.$"

gText_ApprenticeMonFirstThanks7::
	.string "Nire {STR_VAR_1} orduan!\n"
	.string "Oraintxe bertan jarriko dut!\p"
	.string "Eskerrik asko, {PLAYER}.\n"
	.string "Berriz lagunduko didazula espero dut.\l"
	.string "Zaindu zaitez!$"

gText_ApprenticeWhichMonFirst8::
	.string "Ei! {PLAYER}!\n"
	.string "A zer nolako poza zu berriz ikusita!\p"
	.string "Nire POKéMONAK pila bat indartu\n"
	.string "dira azkenekotik!\p"
	.string "Baina ez dut beti irabazten. Badirudi axola\n"
	.string "duela hasieran ateratzen dudan POKéMONAK.\p"
	.string "{PLAYER}, mesedez, zure laguntza behar dut!\p"
	.string "Aukeratu zein POKéMON atera behar\n"
	.string "nukeen lehenengo!$"

gText_ApprenticeMonFirstThanks8::
	.string "Ai… Zoriontasunez beteta nago…\p"
	.string "Amets bat bezalakoa da nire POKéMONEN\n"
	.string "ordena zuk aukeratzea, {PLAYER}.\p"
	.string "Ulertu dut, hala ere!\n"
	.string "Nire {STR_VAR_1} jarriko dut lehenengo!\p"
	.string "Espero dut hurrengo batean are gehiago\n"
	.string "erakutsiko didazula.$"

gText_ApprenticeWhichMonFirst9::
	.string "Kaixo, kaixo!\n"
	.string "Nire irakaslea, {PLAYER}{KUN}!\l"
	.string "Bota zure betiko aholku bikainetako bat!\p"
	.string "Beno, hiru POKéMONEKO talde bat osatu\n"
	.string "dut. Horra arte, dena ondo.\p"
	.string "Baina borrokarako ordena oraindik ez\n"
	.string "dut erabaki.\p"
	.string "Hemen lagunduko didazu, {PLAYER}{KUN}!\n"
	.string "Aukeratu zein POKéMON aterako den lehenengo!\p"
	.string "Ez izan lotsarik.\n"
	.string "Bota beldurrik gabe!$"

gText_ApprenticeMonFirstThanks9::
	.string "Ados, nire {STR_VAR_1} hasieran, beraz!\n"
	.string "Bai, bai!\l"
	.string "Ordena aldatuko dut ziztu batean!\p"
	.string "Ongi, mila esker, beti bezala!\n"
	.string "Agur!$"

gText_ApprenticeWhichMonFirst10::
	.string "{PLAYER}{KUN}, entzun!\n"
	.string "A zer nolako krisia!\p"
	.string "Nire POKéMONAK, hirurak, batera\n"
	.string "ateratzen dira borrokara!\p"
	.string "Noski ezinezkoa dela!\n"
	.string "Kar-kar!\p"
	.string "Hau ez da gezurra, ordea.\n"
	.string "Ez naiz oso ona nire POKéMONEN\l"
	.string "ordena aukeratzeko garaian.\p"
	.string "Eta nire partez aukeratzen baduzu\n"
	.string "zein POKéMON atera lehenengo, irakasle?$"

gText_ApprenticeMonFirstThanks10::
	.string "Ongi, nire {STR_VAR_1} aukeratu duzu?\n"
	.string "Hori ez, beste edozein aterako dut!\p"
	.string "Txantxa da!\n"
	.string "Kasu egingo dizut, irakasle!\p"
	.string "Eskerrik asko, irakasle!\n"
	.string "Gehiago irakatsiko didazula espero dut!$"

gText_ApprenticeWhichMonFirst11::
	.string "I-E-P-A T-X-O!\n"
	.string "Horrek iepa txo osatzen du!\p"
	.string "MARINEL raperoa naiz ni!\n"
	.string "Eta zuretzat galdera bat\l"
	.string "daukat beti!\p"
	.string "Nire taldearen ordena da kontua\n"
	.string "eman iezadazu zure aholkua!\p"
	.string "Talde honetan zein atera behar nuke\n"
	.string "hauek borroka irabaziko badute?$"

gText_ApprenticeMonFirstThanks11::
	.string "Ondo, ulertuta!\n"
	.string "Aldatuko dut ordena, guztiak nahastuta!\p"
	.string "Zure laguntza behar badut,\n"
	.string "{PLAYER}, dudarik gabe galdetuko dizut!$"

gText_ApprenticeWhichMonFirst12::
	.string "Iujuuu, {PLAYER}!\n"
	.string "Zer moduz zabiltza?\p"
	.string "Zer egin behar nuke? Ausartu eta galdetu?\n"
	.string "Bada, bai, galdera bat dut, tentu!\l"
	.string "Entzuten al didazu?\l"
	.string "Entzuten didazu!\p"
	.string "Aukeratu behar duzu, nik zein\n"
	.string "POKéMON atera lehenengo, aizu!\l"
	.string "Borroka batean, esan nahi dut.$"

gText_ApprenticeMonFirstThanks12::
	.string "Nire {STR_VAR_1}? bai!\n"
	.string "Horrela bai nagoela lasai!\p"
	.string "Beno, {PLAYER}, banoa mundu zabalera,\n"
	.string "ez nazazu ahaztu, itzuliko naiz, atzera.\p"
	.string "Hurrengora arte, nire lagun azkarra!$"

gText_ApprenticeWhichMonFirst13::
	.string "…Oof…ooch… {PLAYER}{KUN}…\n"
	.string "My stomach's hurting all of a sudden…\p"
	.string "…It's getting better now…\p"
	.string "I must've worried myself sick racking\n"
	.string "my brains on how I should line up\l"
	.string "my posse of POKéMON.\p"
	.string "So, things being this way,\n"
	.string "I need you to decide for me.\p"
	.string "{PLAYER}{KUN}, which of my POKéMON should\n"
	.string "go first? So I'd win, I mean.$"

gText_ApprenticeMonFirstThanks13::
	.string "Hm, all right.\n"
	.string "My {STR_VAR_1} goes first.\p"
	.string "I'll fix the lineup like that after\n"
	.string "I have my supper.\p"
	.string "I hope I can keep hitting you up\n"
	.string "for help like this.$"

gText_ApprenticeWhichMonFirst14::
	.string "Er… Um…\n"
	.string "{PLAYER}{KUN}?\p"
	.string "Please, don't look at me that way.\n"
	.string "You're making me feel all flustered.\p"
	.string "Um…\n"
	.string "I really need your advice.\p"
	.string "It makes me bashful to say this,\n"
	.string "but I chose my 3-POKéMON team.\l"
	.string "I can't decide on the order, though.\p"
	.string "Which POKéMON should I send out first\n"
	.string "so I at least look capable?$"

gText_ApprenticeMonFirstThanks14::
	.string "Oh… Okay!\n"
	.string "I'll lead with my {STR_VAR_1}.\p"
	.string "I hope I can do my best without\n"
	.string "getting all flustered.\p"
	.string "Thank you, {PLAYER}{KUN}.\n"
	.string "If we meet again, I hope you will be\l"
	.string "as helpful.$"

gText_ApprenticeWhichMonFirst15::
	.string "Hm? You appear to be {PLAYER}{KUN}…\n"
	.string "But are you really?\l"
	.string "Perhaps you're a clever look-alike?\p"
	.string "Oh, no, no, no, don't worry!\n"
	.string "If you really are {PLAYER}, please\l"
	.string "forget about my rudeness.\p"
	.string "What I would like is your fine advice.\p"
	.string "I have here my POKéMON team.\n"
	.string "I would like you to tell me which one\l"
	.string "should go first in a battle.$"

gText_ApprenticeMonFirstThanks15::
	.string "My {STR_VAR_1}…\n"
	.string "You aren't pulling my leg?\p"
	.string "I see. If that's the case, that's fine.\n"
	.string "I thank you for your time.\p"
	.string "I am as you see, but I shall do\n"
	.string "my best.\p"
	.string "Let us meet again!$"

gText_ApprenticeWhichMon0::
	.string "Snivel…\n"
	.string "Oh, {PLAYER}!\p"
	.string "What perfect timing!\n"
	.string "There's something I just can't decide…\p"
	.string "I can't decide which POKéMON I should\n"
	.string "be using.\p"
	.string "I can't decide between the POKéMON\n"
	.string "{STR_VAR_1} and {STR_VAR_2}…\p"
	.string "{PLAYER}, which do you think will give\n"
	.string "even me a chance at winning?$"

gText_ApprenticeMonThanks0::
	.string "Snivel… I… I understand!\n"
	.string "Oh! I'm so sorry!\l"
	.string "You've made me so happy, I'm crying…\p"
	.string "I'll do my best to catch one\n"
	.string "{STR_VAR_1}!\p"
	.string "Thank you so much!$"

gText_ApprenticeWhichMon1::
	.string "Yay! It's {PLAYER}!\n"
	.string "Yay, you came at the right time, too!\l"
	.string "I need your advice again!\p"
	.string "Um, I'm all mixed up--should I use\n"
	.string "my {STR_VAR_1} or {STR_VAR_2}…\p"
	.string "Which do you think I should raise,\n"
	.string "{PLAYER}?$"

gText_ApprenticeMonThanks1::
	.string "Oh, so my {STR_VAR_1} is better!\n"
	.string "Okay, I'll do that!\p"
	.string "Thanks for teaching me!$"

gText_ApprenticeWhichMon2::
	.string "{PLAYER}, hello!\n"
	.string "I have a question I wanted to ask.\p"
	.string "I'm in a dilemma over whether I should\n"
	.string "raise one {STR_VAR_1} or {STR_VAR_2}.\p"
	.string "Which POKéMON do you think will\n"
	.string "be stronger?$"

gText_ApprenticeMonThanks2::
	.string "{STR_VAR_1} is your choice?\n"
	.string "Okay, I got it!\p"
	.string "I'll go catch a strong {STR_VAR_1}\n"
	.string "right away!\p"
	.string "See you again!$"

gText_ApprenticeWhichMon3::
	.string "Hello, {PLAYER}…\p"
	.string "Um, you've probably already forgotten\n"
	.string "about someone like me…\p"
	.string "…But that doesn't matter if you\n"
	.string "could give me advice…\p"
	.string "I can't decide on the one kind of\n"
	.string "POKéMON I should raise…\p"
	.string "I've narrowed the field to the POKéMON\n"
	.string "{STR_VAR_1} and {STR_VAR_2}, but that's\l"
	.string "where I became stuck…\p"
	.string "{PLAYER}, you probably don't want to\n"
	.string "bother, but please decide for me.$"

gText_ApprenticeMonThanks3::
	.string "But will a wild {STR_VAR_1} even pay\n"
	.string "attention to me?\p"
	.string "I will try!\p"
	.string "But will I even be able to catch one…\n"
	.string "No! I'll do my best!\p"
	.string "Thank you!$"

gText_ApprenticeWhichMon4::
	.string "Oh, {PLAYER}{KUN}! I'm so glad to see you!\n"
	.string "I was about to go looking for you!\p"
	.string "Can you decide what kind of POKéMON\n"
	.string "I should use?\p"
	.string "For instance…\n"
	.string "How about the POKéMON {STR_VAR_1}\l"
	.string "and {STR_VAR_2}?\p"
	.string "Which one do you think would be\n"
	.string "better?$"

gText_ApprenticeMonThanks4::
	.string "{STR_VAR_1}? That's great!\p"
	.string "Knowing that you made the decision,\n"
	.string "{PLAYER}{KUN}, I won't be so upset if\l"
	.string "I lose.\p"
	.string "Okay, I'll look to you for advice again.\n"
	.string "Bye!$"

gText_ApprenticeWhichMon5::
	.string "If it isn't {PLAYER}{KUN}! How's it going?\n"
	.string "I'm busy again as always!\p"
	.string "I want to do good with POKéMON, too,\n"
	.string "but I haven't been able to decide\l"
	.string "which POKéMON I should use.\p"
	.string "You know how {STR_VAR_1} look strong?\n"
	.string "But {STR_VAR_2} are tough to ignore.\p"
	.string "{PLAYER}{KUN}, give me some of your good\n"
	.string "advice! Which one'd be good for me?$"

gText_ApprenticeMonThanks5::
	.string "Okay, gotcha.\n"
	.string "I'll find time somehow and catch me\l"
	.string "that {STR_VAR_1} you recommended.\p"
	.string "I'm glad I met a good mentor in you.\n"
	.string "Thanks! See you around!$"

gText_ApprenticeWhichMon6::
	.string "Oh!\n"
	.string "Yay, it's {PLAYER}!\p"
	.string "I didn't waste any time boasting to\n"
	.string "my friends about meeting you!\p"
	.string "I need to tap your mind again today.\n"
	.string "It's an easy one for you!\p"
	.string "Drum roll, please!\n"
	.string "The question I have is…\p"
	.string "If I were to raise a POKéMON,\n"
	.string "and the choices were one {STR_VAR_1}\l"
	.string "or {STR_VAR_2}, which should it be?$"

gText_ApprenticeMonThanks6::
	.string "Ahhh!\n"
	.string "{STR_VAR_1}, you say!\l"
	.string "Thanks for a most cool answer!\p"
	.string "I guess that's about all I wanted\n"
	.string "to ask you today.\p"
	.string "Let's meet here again, okay?\n"
	.string "Thanks!$"

gText_ApprenticeWhichMon7::
	.string "Oh, is it you, {PLAYER}?\n"
	.string "I'm delighted to see you again!\p"
	.string "Ever since I became your apprentice,\n"
	.string "my confidence has been blooming.\p"
	.string "I think I'm ready to raise a POKéMON\n"
	.string "of my own!\p"
	.string "{PLAYER}, may I impose on you to choose\n"
	.string "which POKéMON I should raise?\p"
	.string "The choices are the POKéMON\n"
	.string "{STR_VAR_1} or {STR_VAR_2}…\l"
	.string "Which POKéMON is right for me?$"

gText_ApprenticeMonThanks7::
	.string "One {STR_VAR_1} it is!\n"
	.string "I will find one right away!\p"
	.string "Thank you, {PLAYER}.\n"
	.string "Berriz lagunduko didazula espero dut.\l"
	.string "Zaindu zaitez!$"

gText_ApprenticeWhichMon8::
	.string "Ei! {PLAYER}! I met you again!\n"
	.string "I… I'm overjoyed!\p"
	.string "Oh-oh-oh, I know!\n"
	.string "I shouldn't pass up this opportunity!\p"
	.string "May I ask a huge favor, {PLAYER}?\n"
	.string "Please choose a POKéMON for me!\p"
	.string "Please decide which would be better,\n"
	.string "{STR_VAR_1} or {STR_VAR_2}!$"

gText_ApprenticeMonThanks8::
	.string "Wow! You decided for me!\n"
	.string "One {STR_VAR_1} is what I'll raise to\l"
	.string "the best of my ability.\p"
	.string "Espero dut hurrengo batean are gehiago\n"
	.string "erakutsiko didazula.$"

gText_ApprenticeWhichMon9::
	.string "Hey, hey!\n"
	.string "Nire irakaslea, {PLAYER}{KUN}!\p"
	.string "Hello, I've been looking for you\n"
	.string "for some more of your sage advice!\p"
	.string "Which kind of POKéMON would be right\n"
	.string "for me, one {STR_VAR_1} or {STR_VAR_2}?\p"
	.string "Ez izan lotsarik.\n"
	.string "Bota beldurrik gabe!$"

gText_ApprenticeMonThanks9::
	.string "Uh-huh, one {STR_VAR_1} it is!\n"
	.string "Bai, bai!\l"
	.string "I'll get one in a BALL, like, cram!\p"
	.string "Ongi, mila esker, beti bezala!\n"
	.string "Agur!$"

gText_ApprenticeWhichMon10::
	.string "{PLAYER}{KUN}, entzun! Big news!\n"
	.string "I caught a mirage POKéMON!\p"
	.string "Of course I'm lying!\n"
	.string "Kar-kar!\p"
	.string "Hau ez da gezurra, ordea.\n"
	.string "I'm not very good at catching\l"
	.string "POKéMON.\p"
	.string "So, how about deciding for me which\n"
	.string "kind of POKéMON I should catch,\l"
	.string "master?\p"
	.string "Which would be better?\n"
	.string "{STR_VAR_1} or {STR_VAR_2}?$"

gText_ApprenticeMonThanks10::
	.string "Okay, so it's {STR_VAR_1} you chose?\n"
	.string "I'll grab the other kind, then!\p"
	.string "Txantxa da!\n"
	.string "Kasu egingo dizut, irakasle!\p"
	.string "Eskerrik asko, irakasle!\n"
	.string "Gehiago irakatsiko didazula espero dut!$"

gText_ApprenticeWhichMon11::
	.string "I-E-P-A T-X-O!\n"
	.string "Horrek iepa txo osatzen du!\p"
	.string "MARINEL raperoa naiz ni!\n"
	.string "Surely you remember who am I?\p"
	.string "Today, I have a POKéMON question\n"
	.string "that begs your suggestion!\p"
	.string "I have the choice between this\n"
	.string "{STR_VAR_1} and {STR_VAR_2}, you see.\l"
	.string "Which is the one to catch for me?$"

gText_ApprenticeMonThanks11::
	.string "{STR_VAR_1}, you say, hey, hey!\n"
	.string "I'll go get me one right away!\p"
	.string "Zure laguntza behar badut,\n"
	.string "{PLAYER}, dudarik gabe galdetuko dizut!$"

gText_ApprenticeWhichMon12::
	.string "Oh, wow, if it isn't {PLAYER}!\p"
	.string "Zer egin behar nuke? Aholkua eskatu?\n"
	.string "Why not? I'm already talking to you!\p"
	.string "It's been a long time. Let me break\n"
	.string "the ice. I'm also looking for advice!\l"
	.string "Entzuten al didazu?\l"
	.string "Entzuten didazu!\p"
	.string "My POKéMON--which should I use?\n"
	.string "It's either {STR_VAR_1} or {STR_VAR_2}.\l"
	.string "Which do you choose?$"

gText_ApprenticeMonThanks12::
	.string "If that {STR_VAR_1} is the best,\n"
	.string "I'll do as you suggest!\p"
	.string "Beno, {PLAYER}, banoa mundu zabalera,\n"
	.string "ez nazazu ahaztu, itzuliko naiz, atzera.\p"
	.string "Hurrengora arte, nire lagun azkarra!$"

gText_ApprenticeWhichMon13::
	.string "Oh, hi, {PLAYER}{KUN}…\n"
	.string "I have this horrible headache…\p"
	.string "I must've worried too much about\n"
	.string "the kind of POKéMON I should raise.\p"
	.string "So, things being this way,\n"
	.string "I need you to decide for me.\p"
	.string "{PLAYER}{KUN}, if I had to choose between\n"
	.string "the POKéMON {STR_VAR_1} and\l"
	.string "{STR_VAR_2}, which should it be?$"

gText_ApprenticeMonThanks13::
	.string "Hm, one {STR_VAR_1}, all right.\n"
	.string "I'll go look for one when I get better.\p"
	.string "I hope I can keep hitting you up\n"
	.string "for help like this.$"

gText_ApprenticeWhichMon14::
	.string "Er… Um…\n"
	.string "{PLAYER}{KUN}…?\p"
	.string "Please, don't look at me that way.\n"
	.string "I'm getting all flustered…\l"
	.string "I… I need your advice.\p"
	.string "I… I'm really embarrassed, but I can't\n"
	.string "decide which POKéMON to use.\p"
	.string "If the choices were {STR_VAR_1} or\n"
	.string "{STR_VAR_2}, which would be better?$"

gText_ApprenticeMonThanks14::
	.string "Oh… Okay!\n"
	.string "I'll do my best with one {STR_VAR_1}.\p"
	.string "I hope I can do my best without\n"
	.string "getting all flustered.\p"
	.string "Thank you, {PLAYER}{KUN}.\n"
	.string "If we meet again, I hope you will be\l"
	.string "as helpful.$"

gText_ApprenticeWhichMon15::
	.string "Hm? You appear to be {PLAYER}{KUN}…\n"
	.string "But are you really real?\p"
	.string "No, no, if you are real, it's fine.\n"
	.string "Incidentally, I would like to obtain\l"
	.string "your advice.\p"
	.string "It's about the POKéMON I am to use.\p"
	.string "If the choices are the POKéMON\n"
	.string "{STR_VAR_1} and {STR_VAR_2}, which is\l"
	.string "more worthy of me?$"

gText_ApprenticeMonThanks15::
	.string "{STR_VAR_1}?\n"
	.string "Are you certain?\p"
	.string "I see. If that's the case, that's fine.\n"
	.string "I thank you for your time.\p"
	.string "I do hope it is something even I can\n"
	.string "handle with aplomb.\p"
	.string "Let us meet again!$"

gText_ApprenticeWhichMove0::
	.string "Waaah! Oh, {PLAYER}!\n"
	.string "Snivel… Hiccup…\p"
	.string "I have a dilemma!\n"
	.string "I can't decide on a move for\l"
	.string "my {STR_VAR_1}…\p"
	.string "Please, please, {PLAYER}.\n"
	.string "Can you decide for me?\p"
	.string "For my {STR_VAR_1}, which move would\n"
	.string "be the better choice: {STR_VAR_2}\l"
	.string "or {STR_VAR_3}?$"

gText_ApprenticeMoveThanks0::
	.string "{STR_VAR_1}?\n"
	.string "Waaaaah!\p"
	.string "Oh! I'm so sorry, {PLAYER}!\n"
	.string "You've made me so happy by deciding\l"
	.string "the move, I'm crying…\p"
	.string "Snivel…\n"
	.string "Thank you so much!$"

gText_ApprenticeWhichMove1::
	.string "Yay! Hi, {PLAYER}!\n"
	.string "I need your advice again!\p"
	.string "I want to teach my {STR_VAR_1}\n"
	.string "a cool move.\p"
	.string "I like either of the moves\n"
	.string "{STR_VAR_2} or {STR_VAR_3}.\l"
	.string "What's your recommendation?$"

gText_ApprenticeMoveThanks1::
	.string "{STR_VAR_1} is better? I guess so!\n"
	.string "Okay, I'll go with that!\p"
	.string "If we meet here again, please teach\n"
	.string "me something else, teacher!$"

gText_ApprenticeWhichMove2::
	.string "{PLAYER}, hello!\n"
	.string "It's about my {STR_VAR_1}, but I'm\l"
	.string "worried about its moves.\p"
	.string "You see, it's the moves {STR_VAR_2}\n"
	.string "and {STR_VAR_3}.\p"
	.string "Which is stronger and better for\n"
	.string "my {STR_VAR_1}?$"

gText_ApprenticeMoveThanks2::
	.string "{STR_VAR_1} is your choice?\n"
	.string "Okay, I got it!\p"
	.string "I'll go teach {STR_VAR_1} to\n"
	.string "my POKéMON right away!\p"
	.string "See you again!$"

gText_ApprenticeWhichMove3::
	.string "Ohhh, {PLAYER}…\n"
	.string "I'm hopeless, no, really!\p"
	.string "I've decided to raise a POKéMON,\n"
	.string "but now I can't even decide what\l"
	.string "move I should let it learn…\p"
	.string "I know that it doesn't mean anything\n"
	.string "to you, {PLAYER}.\p"
	.string "But it means a lot to me…\p"
	.string "Please, {PLAYER}, could you choose\n"
	.string "a move for my {STR_VAR_1}?\p"
	.string "If you could even choose between\n"
	.string "{STR_VAR_2} and {STR_VAR_3}…$"

gText_ApprenticeMoveThanks3::
	.string "I understand!\p"
	.string "But will it even be willing to learn\n"
	.string "{STR_VAR_1} for me…\l"
	.string "No! I'll do my best!\p"
	.string "Thank you!$"

gText_ApprenticeWhichMove4::
	.string "Oh, {PLAYER}{KUN}!\n"
	.string "I was just hoping to see you, too!\p"
	.string "I was wondering what move would\n"
	.string "be suitable for my {STR_VAR_1}.\p"
	.string "I can't decide, so can you decide\n"
	.string "for me instead?\p"
	.string "For instance… How about the moves\n"
	.string "{STR_VAR_2} and {STR_VAR_3}?\l"
	.string "Which one would be better?$"

gText_ApprenticeMoveThanks4::
	.string "{STR_VAR_1}? That's great!\p"
	.string "Knowing that you made the decision,\n"
	.string "{PLAYER}{KUN}, I won't be so upset if\l"
	.string "I lose.\p"
	.string "Okay, I'll look to you for advice again.\n"
	.string "Bye!$"

gText_ApprenticeWhichMove5::
	.string "How could things be this busy?\n"
	.string "Hey, if it isn't {PLAYER}{KUN}!\l"
	.string "How's it going?\p"
	.string "Since I got up this morning, I've done\n"
	.string "my jogging, swimming, and cooking!\p"
	.string "You wouldn't believe how busy I am!\p"
	.string "I can't even decide what move\n"
	.string "my {STR_VAR_1} should learn!\p"
	.string "{STR_VAR_2} looks good, huh?\n"
	.string "But {STR_VAR_3}'s also decent.\p"
	.string "{PLAYER}{KUN}, give me some of your good\n"
	.string "advice! Which move'd be good for me?$"

gText_ApprenticeMoveThanks5::
	.string "Okay, gotcha.\n"
	.string "I'll make room in my schedule and\l"
	.string "teach that move.\p"
	.string "I'm glad I met a good mentor in you.\n"
	.string "Thanks! See you around!$"

gText_ApprenticeWhichMove6::
	.string "Oh! Lucky!\n"
	.string "I met you again, {PLAYER}!\l"
	.string "I need to tap your mind again today.\p"
	.string "Drum roll, please!\n"
	.string "The question I have is…\p"
	.string "For my {STR_VAR_1}, which is the move\n"
	.string "best suited, {STR_VAR_2} or\l"
	.string "{STR_VAR_3}?$"

gText_ApprenticeMoveThanks6::
	.string "Ahhh!\n"
	.string "{STR_VAR_1}, you say!\l"
	.string "Thanks for a most cool answer!\p"
	.string "I guess that's about all I wanted\n"
	.string "to ask you today.\p"
	.string "Let's meet here again, okay?\n"
	.string "Thanks!$"

gText_ApprenticeWhichMove7::
	.string "Oh, hello, {PLAYER}.\n"
	.string "I trust you've been well?\p"
	.string "I have to seek your advice again.\n"
	.string "It's about my dearest {STR_VAR_1}.\p"
	.string "What would be the ideal move for\n"
	.string "my lovable {STR_VAR_1}?\l"
	.string "{STR_VAR_2} or {STR_VAR_3}?$"

gText_ApprenticeMoveThanks7::
	.string "{STR_VAR_1} it is!\n"
	.string "I will teach that right away!\p"
	.string "Thank you, {PLAYER}.\n"
	.string "Berriz lagunduko didazula espero dut.\l"
	.string "Zaindu zaitez!$"

gText_ApprenticeWhichMove8::
	.string "Ei! {PLAYER}! I met you again!\n"
	.string "I… I'm overjoyed!\p"
	.string "Whenever I'm in need, you're always\n"
	.string "there for me, {PLAYER}!\p"
	.string "Today, I want you to recommend\n"
	.string "a move for me!\p"
	.string "Please choose a move for\n"
	.string "my {STR_VAR_1}!\p"
	.string "Which move would be better,\n"
	.string "{STR_VAR_2} or {STR_VAR_3}?$"

gText_ApprenticeMoveThanks8::
	.string "Oh-oh-oh! Thank you!\n"
	.string "{STR_VAR_1} is it!\l"
	.string "Perfectly understood!\p"
	.string "Espero dut hurrengo batean are gehiago\n"
	.string "erakutsiko didazula.$"

gText_ApprenticeWhichMove9::
	.string "Hola, {PLAYER}{KUN}, bueno!\n"
	.string "I'm hoping for some more of\l"
	.string "your sage advice today!\p"
	.string "What would be the best move for\n"
	.string "my {STR_VAR_1}?\p"
	.string "It should be something that'll\n"
	.string "let me win just like that!\p"
	.string "Would it be {STR_VAR_2}?\n"
	.string "Or {STR_VAR_3}?$"

gText_ApprenticeMoveThanks9::
	.string "Uh-huh, {STR_VAR_1} it is!\n"
	.string "Si, bueno!\l"
	.string "I'll get it taught, like, ka-blam!\p"
	.string "Ongi, mila esker, beti bezala!\n"
	.string "Agur!$"

gText_ApprenticeWhichMove10::
	.string "{PLAYER}{KUN}, it's completely wild!\p"
	.string "My POKéMON!\n"
	.string "It learned six moves!\p"
	.string "Of course I'm lying!\n"
	.string "Kar-kar!\p"
	.string "Hau ez da gezurra, ordea.\n"
	.string "I'm not very good at choosing moves\l"
	.string "for my POKéMON.\p"
	.string "So, how about deciding for me which\n"
	.string "kind of move I should teach?\p"
	.string "{STR_VAR_2} or {STR_VAR_3}--which\n"
	.string "would go with my {STR_VAR_1} best?$"

gText_ApprenticeMoveThanks10::
	.string "Okay, so it's {STR_VAR_1} you chose?\n"
	.string "I'll choose another move, then!\p"
	.string "Txantxa da!\n"
	.string "Kasu egingo dizut, irakasle!\p"
	.string "Eskerrik asko, irakasle!\n"
	.string "Gehiago irakatsiko didazula espero dut!$"

gText_ApprenticeWhichMove11::
	.string "I-E-P-A T-X-O!\n"
	.string "Horrek iepa txo osatzen du!\p"
	.string "MARINEL raperoa naiz ni!\n"
	.string "I'm always with it, don't ask me why.\p"
	.string "Today, I have a move question\n"
	.string "that begs your suggestion!\p"
	.string "{STR_VAR_2} and {STR_VAR_3} are\n"
	.string "the moves. What would be the best\l"
	.string "for my {STR_VAR_1} so it grooves?$"

gText_ApprenticeMoveThanks11::
	.string "{STR_VAR_1}, you say, hey, hey!\n"
	.string "I'll go teach that right away!\p"
	.string "Zure laguntza behar badut,\n"
	.string "{PLAYER}, dudarik gabe galdetuko dizut!$"

gText_ApprenticeWhichMove12::
	.string "Oh, yeahah, if it isn't {PLAYER}!\p"
	.string "Zer egin behar nuke? Aholkua eskatu?\n"
	.string "Why not? I'm already talking to you!\p"
	.string "{PLAYER}, are you surprised by me?\n"
	.string "I want your advice, can't you see?\p"
	.string "Entzuten al didazu?\n"
	.string "Entzuten didazu!\p"
	.string "My {STR_VAR_1}--what should it use?\n"
	.string "It's {STR_VAR_2} or {STR_VAR_3},\l"
	.string "what do you choose?$"

gText_ApprenticeMoveThanks12::
	.string "If that {STR_VAR_1} is the best,\n"
	.string "I'll do as you suggest!\p"
	.string "Beno, {PLAYER}, banoa mundu zabalera,\n"
	.string "ez nazazu ahaztu, itzuliko naiz, atzera.\p"
	.string "Hurrengora arte, nire lagun azkarra!$"

gText_ApprenticeWhichMove13::
	.string "Gahack! Gaah! Oh, {PLAYER}{KUN}…\n"
	.string "I have this lousy cold, I do…\p"
	.string "I want to pick a move for my POKéMON,\n"
	.string "but I'm not up to it…\p"
	.string "So, things being this way,\n"
	.string "I need you to decide for me.\p"
	.string "{PLAYER}{KUN}, if I had to choose between\n"
	.string "{STR_VAR_2} and {STR_VAR_3} for\l"
	.string "my {STR_VAR_1}, which would it be?$"

gText_ApprenticeMoveThanks13::
	.string "Hm, {STR_VAR_1}, all right. Cough!\n"
	.string "I'll go teach it when I get better.\p"
	.string "I hope I can keep hitting you up\n"
	.string "for help like this.$"

gText_ApprenticeWhichMove14::
	.string "Er… Um…\n"
	.string "{PLAYER}{KUN}…?\p"
	.string "Please, don't look at me that way.\n"
	.string "I'm getting all flustered…\l"
	.string "I… I need your advice.\p"
	.string "I… I'm really embarrassed, but I can't\n"
	.string "decide what move I should teach\l"
	.string "my POKéMON.\p"
	.string "It's for my {STR_VAR_1}.\n"
	.string "If the choices were {STR_VAR_2} or\l"
	.string "{STR_VAR_3}, which would be better?$"

gText_ApprenticeMoveThanks14::
	.string "Oh… Okay!\n"
	.string "I'll try that {STR_VAR_1}.\p"
	.string "I hope I can teach that move…\n"
	.string "This is so nerve-racking…\p"
	.string "Thank you, {PLAYER}{KUN}.\n"
	.string "If we meet again, I hope you will be\l"
	.string "as helpful.$"

gText_ApprenticeWhichMove15::
	.string "Hm? You appear to be {PLAYER}{KUN}…\n"
	.string "But are you really real?\p"
	.string "Perhaps you're one of those popular\n"
	.string "mimics?\p"
	.string "No, no, if you are real, it's fine.\n"
	.string "No need to be upset, I assure you!\p"
	.string "Incidentally, I would like to obtain\n"
	.string "your advice.\p"
	.string "It's about my {STR_VAR_1}.\p"
	.string "Which move would be better for it to\n"
	.string "use, {STR_VAR_2} or {STR_VAR_3}?$"

gText_ApprenticeMoveThanks15::
	.string "{STR_VAR_1}?\n"
	.string "There's no question about that?\p"
	.string "I see. If that's the case, that's fine.\n"
	.string "I thank you for your time.\p"
	.string "I do hope it is something even\n"
	.string "my POKéMON can learn.\p"
	.string "Let us meet again!$"

gText_ApprenticePickWinSpeech0::
	.string "Oh… {PLAYER}?\n"
	.string "It is {PLAYER}!\l"
	.string "Oh! Sniff…sob… Please, listen!\p"
	.string "I… When I battle, I get so nervous,\n"
	.string "I can't help crying even if I win…\p"
	.string "I wish I could say something cool\n"
	.string "when I win…\p"
	.string "Please, please, {PLAYER}!\n"
	.string "Could you maybe teach me something\l"
	.string "cool to say when I win so I don't cry?$"

gText_ApprenticeWinSpeechThanks0::
	.string "{STR_VAR_1}\p"
	.string "Awesome! Wicked! Awoooh!\n"
	.string "It's really cool!\p"
	.string "Oh… I'm sorry…\n"
	.string "I'm so happy, I'm crying…\p"
	.string "Snivel… {PLAYER}!\n"
	.string "Thank you so much for everything!\p"
	.string "I will battle the best I can for\n"
	.string "your sake, {PLAYER}!\p"
	.string "{PLAYER}…\n"
	.string "Next time… We should battle!$"

gText_ApprenticePickWinSpeech1::
	.string "Yay! It's {PLAYER}! Hello!\n"
	.string "I wanted to ask you something!\p"
	.string "I want to say something cool when\n"
	.string "I win a match.\p"
	.string "Do you have a cool saying that\n"
	.string "you could recommend?$"

gText_ApprenticeWinSpeechThanks1::
	.string "{STR_VAR_1}\p"
	.string "Oh, wow! That is so cool!\n"
	.string "Okay, I'll say that!\p"
	.string "Thanks for teaching me all this time!\n"
	.string "I'm going to do the best I can\l"
	.string "wherever I go from now on!\p"
	.string "When we meet again, it'll be for\n"
	.string "a battle!$"

gText_ApprenticePickWinSpeech2::
	.string "{PLAYER}, hello!\p"
	.string "My POKéMON and I are ready for\n"
	.string "anything, except for one thing.\p"
	.string "I think it would be good if I had\n"
	.string "something to shout when I win.\p"
	.string "Could you think up something good\n"
	.string "to say?$"

gText_ApprenticeWinSpeechThanks2::
	.string "{STR_VAR_1}\p"
	.string "…Cool!\n"
	.string "I will use that!\p"
	.string "I'm going out to battle all over\n"
	.string "the place.\p"
	.string "Who knows, I may even get to battle\n"
	.string "you one day, {PLAYER}.\p"
	.string "Next time, let's meet at a place\n"
	.string "of battle!$"

gText_ApprenticePickWinSpeech3::
	.string "Hello, {PLAYER}…\n"
	.string "I'm sorry to bug you, but I'm hopeless…\p"
	.string "Even when…\n"
	.string "Even when I win, I don't have anything\l"
	.string "special to say…\p"
	.string "I know that it doesn't mean anything\n"
	.string "to you, {PLAYER}.\p"
	.string "But it means a lot to me…\p"
	.string "Please, {PLAYER}, what should I say\n"
	.string "if I win a battle?$"

gText_ApprenticeWinSpeechThanks3::
	.string "{STR_VAR_1}\p"
	.string "That's inspired…\p"
	.string "Uh… Is it okay for someone like me\n"
	.string "to even say that?\p"
	.string "No! I'll do my best!\p"
	.string "{PLAYER}, thank you so much for\n"
	.string "putting up with me for so long…\p"
	.string "I promise to do my best from now on.\p"
	.string "I'm sure you'll quickly forget about\n"
	.string "someone like me, but let's meet\l"
	.string "somewhere again!$"

gText_ApprenticePickWinSpeech4::
	.string "Oh, {PLAYER}{KUN}.\n"
	.string "There's something I want you to hear.\p"
	.string "I know that I don't always sound\n"
	.string "nice or polite…\p"
	.string "When I win a battle, I think I come\n"
	.string "across as being arrogant.\p"
	.string "I don't want people to dislike me,\n"
	.string "so I want to say something nice to\l"
	.string "someone I beat.\p"
	.string "But I can't think of anything good!\n"
	.string "Could you think something up for me?$"

gText_ApprenticeWinSpeechThanks4::
	.string "{STR_VAR_1}\p"
	.string "Not bad!\n"
	.string "Yup, that's what I'll go with!\p"
	.string "I'm going to hit the road and do what\n"
	.string "I can with what you taught me in\l"
	.string "my head and heart.\p"
	.string "I'm sorry that I've been so pushy\n"
	.string "with you!\p"
	.string "Next time, we battle, okay?\n"
	.string "See you!$"

gText_ApprenticePickWinSpeech5::
	.string "Oh, I can't get over how busy I am!\n"
	.string "Oh, hey, I was looking for you, {PLAYER}{KUN}.\p"
	.string "Are you well as usual?\n"
	.string "Things haven't changed for me at all.\p"
	.string "I've got running, fighting, and mapping\n"
	.string "to do. Why am I so busy?\p"
	.string "But even though I'm busy, it'd be rude\n"
	.string "to just turn on my heels and walk away\l"
	.string "from a win without saying a word.\p"
	.string "So, what would be a cool saying to\n"
	.string "underline my coolness when I'm done\l"
	.string "and walking away? {PLAYER}{KUN}, help me!$"

gText_ApprenticeWinSpeechThanks5::
	.string "{STR_VAR_1}\p"
	.string "Okay, gotcha.\n"
	.string "I can find time to say that!\p"
	.string "Honestly, I'm glad I met a good mentor\n"
	.string "like you.\p"
	.string "I'm going to make time somehow so\n"
	.string "I can get into battling.\p"
	.string "Thanks for everything, {PLAYER}{KUN}!\n"
	.string "We have to battle, you and me, one day!$"

gText_ApprenticePickWinSpeech6::
	.string "I lucked out again!\n"
	.string "{PLAYER}! Am I glad to see you!\l"
	.string "Like usual, I need your advice!\p"
	.string "Drum roll, please!\n"
	.string "The last question I have is…\p"
	.string "If I win a battle and want to end\n"
	.string "it with a cool flourish, what\l"
	.string "should I say?$"

gText_ApprenticeWinSpeechThanks6::
	.string "{STR_VAR_1}\p"
	.string "That… That's fabulous!\n"
	.string "It's dignified and cool! I claim it!\p"
	.string "…Listen, I think I'm getting decent\n"
	.string "at this, huh?\p"
	.string "So, I'm thinking of challenging other\n"
	.string "TRAINERS from now on.\p"
	.string "{PLAYER}, your advice really helped me.\p"
	.string "Maybe one day, there'll be a time when\n"
	.string "we battle!\p"
	.string "Thank you for everything!$"

gText_ApprenticePickWinSpeech7::
	.string "Oh, {PLAYER}.\n"
	.string "I'm so glad I met you!\p"
	.string "I no longer have any concerns with\n"
	.string "regard to my POKéMON.\p"
	.string "It's myself that worries me…\p"
	.string "Do you know how a TRAINER says\n"
	.string "a few things upon winning a battle?\p"
	.string "Definitely, I wish I could do that,\n"
	.string "too!\p"
	.string "Please, what should I say when\n"
	.string "I win a battle?$"

gText_ApprenticeWinSpeechThanks7::
	.string "{STR_VAR_1}\p"
	.string "Ah! That saying! It refreshes me\n"
	.string "and makes me feel reborn!\p"
	.string "I must use that right away!\p"
	.string "And now, I must take my leave,\n"
	.string "{PLAYER}…\p"
	.string "I will go out to battle many others,\n"
	.string "but never will I forget your teachings.\p"
	.string "Perhaps one day…\n"
	.string "Farewell!$"

gText_ApprenticePickWinSpeech8::
	.string "Ei! I spotted {PLAYER}!\n"
	.string "I… I'm overjoyed to see you!\p"
	.string "Oh-oh-oh! There's something I just\n"
	.string "had to ask you!\p"
	.string "A little while ago, I won a battle.\n"
	.string "That part was giddying!\p"
	.string "But it made me so overjoyed that\n"
	.string "I choked up and couldn't say a thing!\p"
	.string "So now, {PLAYER}, please, I want you to\n"
	.string "think up an exit line for when I win!$"

gText_ApprenticeWinSpeechThanks8::
	.string "{STR_VAR_1}\p"
	.string "Waaaaah!\n"
	.string "I'm going to say that?!\l"
	.string "I… I'm delirious with joy!\p"
	.string "Th-th-thank you!\n"
	.string "I have nothing left to regret now!\p"
	.string "I'm going to travel now and battle\n"
	.string "all sorts of people.\p"
	.string "Everything, I owe it to you, {PLAYER}.\n"
	.string "Really, really, thank you!\p"
	.string "I've got to go now, but let's meet\n"
	.string "in battle one day!$"

gText_ApprenticePickWinSpeech9::
	.string "Hola, bueno!\n"
	.string "{PLAYER}{KUN}!\p"
	.string "You know, I'm getting the itch to roam\n"
	.string "and battle where I may.\p"
	.string "But before I do, I want your advice\n"
	.string "once again, please!\p"
	.string "If I were to win a battle, what would\n"
	.string "be a good boast I could say to my\l"
	.string "fallen TRAINER opponent?$"

gText_ApprenticeWinSpeechThanks9::
	.string "{STR_VAR_1}\p"
	.string "Uh-huh, that's sweet!\n"
	.string "Si, bueno!\l"
	.string "I'll try saying that, like, ham!\p"
	.string "And now, it's time to say good-bye!\n"
	.string "Thanks for all sorts of things!\p"
	.string "Give me a battle one day, OK?\n"
	.string "Agur!$"

gText_ApprenticePickWinSpeech10::
	.string "{PLAYER}{KUN}, there's big trouble!\p"
	.string "When I win a battle, I brag about it\n"
	.string "for an hour at least!\p"
	.string "Of course I'm lying!\n"
	.string "Kar-kar!\p"
	.string "Hau ez da gezurra, ordea.\n"
	.string "I'm not very good at chatting.\p"
	.string "So, how about deciding for me what\n"
	.string "I should say after winning a battle,\l"
	.string "master?$"

gText_ApprenticeWinSpeechThanks10::
	.string "{STR_VAR_1}\p"
	.string "That's what I should say, huh?\n"
	.string "Then, I'll stay away from that!\p"
	.string "Txantxa da!\n"
	.string "Kasu egingo dizut, irakasle!\p"
	.string "Thanks for teaching me all this time,\n"
	.string "master!\p"
	.string "I'm finally understanding what being\n"
	.string "a TRAINER is about.\p"
	.string "I'm going to go out and win battles\n"
	.string "against any TRAINER.\p"
	.string "Maybe it'll be you one day, master!\p"
	.string "That's all!\n"
	.string "Farewell, my master!$"

gText_ApprenticePickWinSpeech11::
	.string "I-E-P-A T-X-O!\n"
	.string "Horrek iepa txo osatzen du!\p"
	.string "MARINEL raperoa naiz ni!\n"
	.string "This will be my last question,\l"
	.string "don't you cry!\p"
	.string "It's a saying question\n"
	.string "that begs your suggestion!\p"
	.string "If I win a match, what can I say\n"
	.string "in a real cool way?$"

gText_ApprenticeWinSpeechThanks11::
	.string "{STR_VAR_1}\p"
	.string "Perfect! That's what I'll use.\n"
	.string "I was right to make you choose!\p"
	.string "And now, I think it'd be best,\n"
	.string "if I were to fly the nest!\p"
	.string "Thanks for all you taught me.\n"
	.string "I'll be off on a battle spree!\p"
	.string "B-O-N-V-O-Y-A-G-E!\n"
	.string "And that spells bon voyage,\l"
	.string "to you this is my homage!$"

gText_ApprenticePickWinSpeech12::
	.string "Oh, yeah, {PLAYER}!\n"
	.string "I found you again today!\p"
	.string "Zer egin behar nuke? Berriz galdetu?\n"
	.string "Why not? I'm already asking you!\p"
	.string "Anyways, {PLAYER}…\n"
	.string "Entzuten al didazu?\l"
	.string "Entzuten didazu!\l"
	.string "I need some more advice for me!\p"
	.string "It's about what I should yell.\n"
	.string "Something cool to holler when\l"
	.string "a battle ends well.\p"
	.string "Come on, I wanna hear you say it!$"

gText_ApprenticeWinSpeechThanks12::
	.string "{STR_VAR_1}\p"
	.string "All right, all right!\n"
	.string "I'll use that because it's so tight!\p"
	.string "I'm out of things to ask you.\n"
	.string "Waving bye is all that's left to do.\p"
	.string "But maybe one day we'll meet, with one\n"
	.string "destined to go down in defeat.\p"
	.string "But, it really is time to say farewell.\p"
	.string "Beno, {PLAYER}, banoa mundu zabalera,\n"
	.string "ez nazazu ahaztu, itzuliko naiz, atzera.\p"
	.string "Zaindu zaitez, {PLAYER}!\n"
	.string "Maite zaitut!$"

gText_ApprenticePickWinSpeech13::
	.string "{PLAYER}{KUN}, I'm finished…\n"
	.string "My nose won't stop dripping…\p"
	.string "I was trying to think up something\n"
	.string "cool to say when I win a battle.\p"
	.string "It inspired me so much, it made me cry,\n"
	.string "and now my nose won't stop running…\p"
	.string "So, things being this way,\n"
	.string "I need you to decide for me, {PLAYER}{KUN}.\p"
	.string "When I win a battle,\n"
	.string "what should I say?$"

gText_ApprenticeWinSpeechThanks13::
	.string "{STR_VAR_1}\p"
	.string "… … …That's good.\n"
	.string "No, it's awe inspiring!\l"
	.string "It's bringing fresh tears to my eyes!\p"
	.string "But in spite of my tears and runny\n"
	.string "nose, I will use that saying!\p"
	.string "I'm plumb out of things to ask you,\n"
	.string "{PLAYER}{KUN}.\p"
	.string "From now on, we're rivals!\n"
	.string "Thanks for everything!$"

gText_ApprenticePickWinSpeech14::
	.string "Er… Um…\n"
	.string "{PLAYER}{KUN}…\p"
	.string "Please, don't look at me that way.\n"
	.string "You're making me all nervous.\p"
	.string "I… I need your advice again.\n"
	.string "I'll make it my last, though…\p"
	.string "It's really embarrassing to ask,\n"
	.string "but what if I win a battle?\l"
	.string "What should I say?$"

gText_ApprenticeWinSpeechThanks14::
	.string "{STR_VAR_1}\p"
	.string "Oh… Okay!\n"
	.string "I'll try to say that!\l"
	.string "I might be too nervous to say it…\p"
	.string "Thank you, {PLAYER}{KUN}.\n"
	.string "I have to say good-bye now.\p"
	.string "I'll obey all that you've taught me,\n"
	.string "{PLAYER}{KUN}, and do the best I can.$"

gText_ApprenticePickWinSpeech15::
	.string "Hm? You appear to be {PLAYER}{KUN}…\n"
	.string "But are you really?\l"
	.string "Perhaps a clever {PLAYER} DOLL?\p"
	.string "Oh, no, no, no, don't worry!\n"
	.string "If you really are real, please\l"
	.string "forget about my rudeness.\p"
	.string "No need to be so angry. All I wish for\n"
	.string "is more of your fine advice.\p"
	.string "It concerns a saying.\p"
	.string "More precisely, what should I say\n"
	.string "if I win a battle?$"

gText_ApprenticeWinSpeechThanks15::
	.string "{STR_VAR_1}\p"
	.string "… … … … … …\n"
	.string "When I win a match…\p"
	.string "{STR_VAR_1}\p"
	.string "…Are you serious?\p"
	.string "I see. If you are serious, that's fine.\n"
	.string "I thank you for your time.\p"
	.string "I do hope even I will be able to\n"
	.string "put that saying to good use.\p"
	.string "I seem to have run dry on what advice\n"
	.string "I need.\p"
	.string "I do believe it's high time I bid you\n"
	.string "farewell and strike out on my own.\p"
	.string "Thank you, my mentor!\n"
	.string "I apologize for my skepticism!$"
