gText_ApprenticeChallenge0::
	.string "Ein… {STR_VAR_1}(r)en {STR_VAR_2}garren ikaslea naiz.\n"
	.string "Jope… Ezi dut tentsio honekin guztiarekin…$"

gText_ApprenticeChallenge1::
	.string "{STR_VAR_1}(r)en {STR_VAR_2}. ikaslea naiz!\n"
	.string "Banator!$"

gText_ApprenticeChallenge2::
	.string "{STR_VAR_1}(r)en {STR_VAR_2}. ikaslea naiz!\n"
	.string "Borrokatu dezagun!$"

gText_ApprenticeChallenge3::
	.string "Ein… {STR_VAR_1}(r)en {STR_VAR_2}. ikaslea naiz…\n"
	.string "Uset duzu inoiz irabaziko dudala?$"

gText_ApprenticeChallenge4::
	.string "{STR_VAR_1}(r)en {STR_VAR_2}. ikaslea naiz!\n"
	.string "Nire kontra borrokatzen utziko dizut!$"

gText_ApprenticeChallenge5::
	.string "Oso oso okupatuta nago, baina,\n"
	.string "{STR_VAR_1}(r)en {STR_VAR_2}. ikaslea ere banaiz.$"

gText_ApprenticeChallenge6::
	.string "{STR_VAR_1}(r)en {STR_VAR_2}. ikaslea naiz.\n"
	.string "Urte askoan!$"

gText_ApprenticeChallenge7::
	.string "{STR_VAR_1}(r)en {STR_VAR_2}. ikaslea naiz.\n"
	.string "Has naiteke?$"

gText_ApprenticeChallenge8::
	.string "Ene! {STR_VAR_1}(r)en {STR_VAR_2}. ikaslea naiz!\n"
	.string "Ahalik ondoen borrokatuko dut!$"

gText_ApprenticeChallenge9::
	.string "Iuju! {STR_VAR_1}(r)en {STR_VAR_2}. ikaslea naiz!\n"
	.string "Goazen ba!$"

gText_ApprenticeChallenge10::
	.string "{STR_VAR_1}(r)en 1000. ikaslea naiz!\n"
	.string "Txantxa da, {STR_VAR_2}.a naiz! Goazen!$"

gText_ApprenticeChallenge11::
	.string "Bai, {STR_VAR_1}(r)en {STR_VAR_2}. ikaslea naiz!\n"
	.string "Egurra ematera!$"

gText_ApprenticeChallenge12::
	.string "Iujujuju! Esan daiteke\n"
	.string "{STR_VAR_1}(r)en {STR_VAR_2}. ikaslea naizela!$"

gText_ApprenticeChallenge13::
	.string "Tuju! {STR_VAR_1}(r)en {STR_VAR_2}. ikaslea naiz.\n"
	.string "Pozten naiz ezagutzeaz! Tuju!$"

gText_ApprenticeChallenge14::
	.string "Urduriegi nago…\n"
	.string "{STR_VAR_1}(r)en {STR_VAR_2}. ikaslea naiz.$"

gText_ApprenticeChallenge15::
	.string "{STR_VAR_1}(r)en {STR_VAR_2}. ikaslea naiz,\n"
	.string "bene-benetan.$"

gText_ApprenticePleaseTeach0::
	.string "Zu al zara… {PLAYER}?\n"
	.string "Ene! Zintz…zintz…\p"
	.string "Oi! B-Barkatu…\n"
	.string "Ze urduri nagoen, ezin ditut malkoak eutsi…\p"
	.string "{STR_VAR_1} naiz, eta asko miresten\n"
	.string "zaitut, {PLAYER}.\p"
	.string "Nire ametsa izan da zu ezagutu\n"
	.string "eta POKéMONEN inguruan galderak egitea.\p"
	.string "Mesedez, faborez, {PLAYER}!\n"
	.string "mesedez, irakatsi POKéMONEN inguruan!$"

gText_ApprenticeRejectTeaching0::
	.string "B-Baina…\n"
	.string "zintz… Buaaaaaa!\p"
	.string "Faborez!\n"
	.string "Erregutzen dizut, mesedez!$"

gText_ApprenticeWhichLevelMode0::
	.string "Benetan? Irakatsiko didazu?\n"
	.string "Onaaaaa! Bikain! Iujuu!\p"
	.string "Ene… Barkatu…\n"
	.string "Hain pozik nago, negarrez hasi naizela…\p"
	.string "Ba… Orduan esan!\n"
	.string "BORROKA DORREAREN inguruan da.\p"
	.string "Zer da niretzat hobe: 50. Maila\n"
	.string "edo Maila Irekia?$"

gText_ApprenticeLevelModeThanks0::
	.string "{STR_VAR_1}?\n"
	.string "Buaaaaaa!\p"
	.string "Ene! Barkatu!\n"
	.string "Oso oso pozik jarri naiz zuk maila\l"
	.string "gomendatzean eta negarrez hasi naiz…\p"
	.string "Zintz…\n"
	.string "Eskerrik asko!\l"
	.string "Hitz egin berriro nirekin, faborez!$"

gText_ApprenticePleaseTeach1::
	.string "Uau! {PLAYER} zara, ezta?\n"
	.string "Izugarri indartsua zara, baietz?\p"
	.string "Ni {STR_VAR_1} naiz!\n"
	.string "ENTRENATZAILE bihurtu berri naiz!\p"
	.string "Mesedez, {PLAYER}!\n"
	.string "Izango zara nire irakaslea eta\l"
	.string "ENTRENATZAILE izaten erakutsi?$"

gText_ApprenticeRejectTeaching1::
	.string "Oh, ez, zergatik?\n"
	.string "Mesedez? Faborez?\l"
	.string "Irakatsi, mesedeeeez!$"

gText_ApprenticeWhichLevelMode1::
	.string "Bai! Ederki!\p"
	.string "Lehenengo egin nahi dizudan galdera\n"
	.string "BORROKA DORREAREN inguruan da!\p"
	.string "50. Maila eta Maila irekiko gelen artean…\n"
	.string "Zein da nrietzat egokiena?$"

gText_ApprenticeLevelModeThanks1::
	.string "{STR_VAR_1}, ezta? Arrazoia!\n"
	.string "Pila bat saiatuko naiz!\p"
	.string "Berriz elkartzen bagara, erakutsi\n"
	.string "zerbait berria, mesedez!$"

gText_ApprenticePleaseTeach2::
	.string "Em… Zu al zara {PLAYER}?\n"
	.string "Ni {STR_VAR_1} naiz.\p"
	.string "POKéMON ENTRENATZAILEA izan nahi\n"
	.string "dut, baina ez dakit nola…\p"
	.string "Zuri galdetzea pentsatu dut, horren\n"
	.string "famatua zarenez.\p"
	.string "{PLAYER}, lagunduko zenidake?$"

gText_ApprenticeRejectTeaching2::
	.string "Baina, baina…\p"
	.string "Benetan POKéMON ENTRENATZAILE\n"
	.string "izan nahi dut!\p"
	.string "Erantzungo nire galderak, mesedez?$"

gText_ApprenticeWhichLevelMode2::
	.string "Esker mila!\n"
	.string "Hona hemen nire galdera!\p"
	.string "BORROKA DORREAK bi modu ditu,\n"
	.string "50 Maila eta Maila Irekia, ezta?\p"
	.string "Zure iritziz, zein da niretzat\n"
	.string "egokiena?$"

gText_ApprenticeLevelModeThanks2::
	.string "Ah, {STR_VAR_1} beraz?\n"
	.string "Ulertuta!\p"
	.string "Beste galdera bat dudanean,\n"
	.string "zure bila etorriko naiz hona!$"

gText_ApprenticePleaseTeach3::
	.string "Baina… Ein? Zu al zara…\n"
	.string "Ez, ezinezkoa da hori.\p"
	.string "Ni bezalako batek ezin du\n"
	.string "{PLAYER} bezalako norbait ezagutu.\p"
	.string "…Benetan {PLAYER} zarela?\n"
	.string "Ezin dutsinetsi zurekin hizketan nabilela!\p"
	.string "Horren gauza ona jazo bazait,\n"
	.string "hemendik aurrera gauza txarrak besterik\l"
	.string "ez zaizkit gertatuko, seguru nago…\p"
	.string "…Barkatu…\n"
	.string "Ni… {STR_VAR_1} naiz…\p"
	.string "Ez dut nitaz harro egoteko\n"
	.string "ezer egin inoiz…\p"
	.string "Ez nintzateke aurkeztu ere egin behar,\n"
	.string "seguru ahaztuko zenukeela…\p"
	.string "Amets bat izan nuen, egunen batean zu,\n"
	.string "{PLAYER}, ezagutu eta galdetuko nizula\l"
	.string "nola izan ENTRENATZAILE ona.\p"
	.string "Baina ez dut uste lagunduko\n"
	.string "zenidakeenik.\p"
	.string "…Edo agian lagunduko zenidake\n"
	.string "pista bat edo beste emanda?$"

gText_ApprenticeRejectTeaching3::
	.string "Banekien…\p"
	.string "Normala, horren aspergarria naizenez\n"
	.string "ezin zuen beste inola izan…\p"
	.string "Baina uste nuen, beharbada…\n"
	.string "Berriz kontsidera zenezake esandakoa?\p"
	.string "Ezin naiz horren erraz errenditu.\n"
	.string "Berriz galdetuko dizut!\p"
	.string "Faborez, lagunduko zenidake\n"
	.string "gomendio bat edo beste emanda?$"

gText_ApprenticeWhichLevelMode3::
	.string "Benetan? Ezin dut sinestu!\n"
	.string "Benetan lagunduko didazu!\l"
	.string "Ze pozik nagoen…\p"
	.string "Galdetu nahi dizudana nahiko sinplea\n"
	.string "da, baina ezin aukeratu nabil…\p"
	.string "BORROKA DORREAN 50 Maila edo\n"
	.string "Maila Irekia aukeratu daitezke.\p"
	.string "Zure iritziz, zein izango litzateke\n"
	.string "niretzat egokiena?$"

gText_ApprenticeLevelModeThanks3::
	.string "{STR_VAR_1}? Ados!\n"
	.string "Ni bezalako norbaitek aukerarik izango\l"
	.string "lukeela uste duzu?\p"
	.string "Bueno,ni saiatuko naiz, nahiz eta\n"
	.string "ez dudan uste lortuko dudanik.\p"
	.string "Mila esker zure denbora\n"
	.string "niri eskaintzeagatik.$"

gText_ApprenticePleaseTeach4::
	.string "Ene! {PLAYER}{KUN}, zara, ezta?\p"
	.string "Entzun dut oso ona zarela\n"
	.string "POKéMONEKIN!\p"
	.string "Ni {STR_VAR_1} naiz!\n"
	.string "Zure laguna izango naiz!\p"
	.string "Bazekenien?\p"
	.string "Ezin duzu BORROKA FRONTEAN irabazi\n"
	.string "ENTRENATZAILE ESKOLAKO gauzak\l"
	.string "soilik badakizkizu.\p"
	.string "Beraz, zure aholkua entzun nahiko nuke.\n"
	.string "Ondo deritzozu, edo?$"

gText_ApprenticeRejectTeaching4::
	.string "Nola? Zregatik diozu ezetz?\n"
	.string "Baina begira nork eskatu dizun!\l"
	.string "Berriz pentsatu beharko duzu!$"

gText_ApprenticeWhichLevelMode4::
	.string "Bueno, ba hau da kontua.\n"
	.string "Nire partez erabaki bat hartu behar duzu.\p"
	.string "BATAILA DORREAK 50 Maila eta Maila\n"
	.string "Irekiko gelak dituela badakizu, ez?\p"
	.string "Niretzat zein da egokiena zure ustez,\n"
	.string "{PLAYER}{KUN}?$"

gText_ApprenticeLevelModeThanks4::
	.string "Ongi, {STR_VAR_1} da egokiena, beraz?\n"
	.string "Esker anitz!\p"
	.string "Erabakiz zuk hartuta,\n"
	.string "{PLAYER}{KUN}, ez zait hainbeste\l"
	.string "inporta galtzen badut ere.\p"
	.string "Ados, Etorriko naiz laguntza eske berriro.\n"
	.string "Aio!$"

gText_ApprenticePleaseTeach5::
	.string "Aupa kaixo! {PLAYER}{KUN}!\n"
	.string "Ezagutzen zaitut, famatua zara!\l"
	.string "{STR_VAR_1} naiz ni! Urte askoan!\p"
	.string "TRIATLETA naiz, beraz, sasoian mantentzen\n"
	.string "naiz POKéMONAK entrenatzean ere.\p"
	.string "Gauza gehiago ere egiten ditut:\n"
	.string "lana, siesta, aretoko dantzak…\p"
	.string "Horren okupatuta nago, ezin\n"
	.string "dudala tamainako ENTRENATZAILE izan.\p"
	.string "beraz, hor doa proposamena!\p"
	.string "Gu ezagutu izanak arrazoiren bat behar du.\n"
	.string "Beraz, {PLAYER}{KUN}, zer iruditzen zaizu\l"
	.string "noizean behin irakasten badidazu?$"

gText_ApprenticeRejectTeaching5::
	.string "Oh, baina, mesedez eskatuz gero?\n"
	.string "Ni bezalako norbaitek zu bezalako\l"
	.string "norbait behar du, {PLAYER}{KUN}!\p"
	.string "Benetan, zure aholkuak behar ditut!$"

gText_ApprenticeWhichLevelMode5::
	.string "Esker mila! Horrela askoz hobe!\n"
	.string "Erraz batekin has gaitezen!\p"
	.string "BATAILA DORREKO bi moduak\n"
	.string "ezagutzen dituzu, baietz?\l"
	.string "50 Maila eta Maila Irekia, hori da.\p"
	.string "Ni bezalako pertsona okupatu batek\n"
	.string "zein aukeratu behar luke?$"

gText_ApprenticeLevelModeThanks5::
	.string "{STR_VAR_1}, beraz? Ulertuta.\n"
	.string "Aterako dut denbora nonbaitetik!\p"
	.string "…Eneeee, lanera joan behar dut!\n"
	.string "Eskerrik asko! Laister arte!$"

gText_ApprenticePleaseTeach6::
	.string "Bai zera! Ez, ez!\n"
	.string "Zu al zara {PLAYER} famatua?\p"
	.string "Izugarria! Ni {STR_VAR_1},\n"
	.string "pozten naiz ezagutzeaz!\p"
	.string "{PLAYER}, zu oso indartsua zara,\n"
	.string "ez al da hala?\p"
	.string "Mundu guztiak hitz egiten du zutaz!\p"
	.string "Ideia bat izan dut!\n"
	.string "Zure aholkuak entzungo ditut, {PLAYER}!\l"
	.string "Horrela seguru indartu egingo naizela!\p"
	.string "Ideia ederra, ezta?\n"
	.string "Mesedez, eman aholkuren bat!$"

gText_ApprenticeRejectTeaching6::
	.string "Kar kar kar, desatseginarena eginda\n"
	.string "ere, ni ez nauzu engainatuko!\l"
	.string "Izatez baiezkoa ematen ari zara, ezta?$"

gText_ApprenticeWhichLevelMode6::
	.string "Bai! Banekien bihotz onekoa zinela,\n"
	.string "{PLAYER}!\p"
	.string "Zer galdetu behar nizuke lehenengo?\n"
	.string "…Ah, Badakit!\p"
	.string "Erredoblea, mesedez!\n"
	.string "Eta nire galdera da…\p"
	.string "BORROKA DORREKO erronka hartzekotan\n"
	.string "zein gomendatuko zenidake?\p"
	.string "50 Maila edo Maila Irekia?\n"
	.string "Zein da egokiagoa?$"

gText_ApprenticeLevelModeThanks6::
	.string "Oh-oh-oh!\n"
	.string "{STR_VAR_1}, orduan!\l"
	.string "Mila esker erantzunagatik!\p"
	.string "Hori da gaurkoz galdetu\n"
	.string "nahi nizun guztia.\p"
	.string "Hurrengoan hemen elkartuko gara\n"
	.string "berriz, ados? Esker mila!$"

gText_ApprenticePleaseTeach7::
	.string "Aizu, barkatu, baina…\n"
	.string "{PLAYER} al zara?\p"
	.string "{STR_VAR_1} naiz, eta asko pozten naiz\n"
	.string "zu ezagutzeaz.\p"
	.string "Aspaldidanik izan naiz zure\n"
	.string "jarraitzailea…\p"
	.string "… … … … … …\p"
	.string "… Espero dut ez dela zuretzat\n"
	.string "enbarazu handia izango, baina…\p"
	.string "Izan al naiteke zure ikaslea,\n"
	.string "{PLAYER}?$"

gText_ApprenticeRejectTeaching7::
	.string "Ene…!\p"
	.string "… … … … … …\n"
	.string "… … … … … …\p"
	.string "…Uste dut konortea galdu dudala.\n"
	.string "Barkatu, gaizki ulertu dizut, uste dut.\p"
	.string "Mesedez! Esan zure ikasle bezala\n"
	.string "onartuko nauzula, mesedez!$"

gText_ApprenticeWhichLevelMode7::
	.string "Ene… Zeinen ongi!\p"
	.string "Ez dizut denbora alferrik galaraziko,\n"
	.string "beraz, lagundu iezadazu honekin.\p"
	.string "BORROKA DORREKO erronkara aurkezteko\n"
	.string "asmotan nabil.\p"
	.string "Hala ere, bi maila daude…\p"
	.string "Zein izango litzateke niretzat onena?\n"
	.string "50 Maila edo Maila Irekia?$"

gText_ApprenticeLevelModeThanks7::
	.string "{STR_VAR_1} da zure aukera, beraz!\n"
	.string "Ongi. Ahal dudan guztia egingo dut!\p"
	.string "Eskerrik asko, {PLAYER}.\n"
	.string "Ea berriro lagun diezadakezun.\l"
	.string "Zaindu zaitez!$"

gText_ApprenticePleaseTeach8::
	.string "Aizu! Aizu! {PLAYER}!\n"
	.string "Nirekin hitz egni duzu!\l"
	.string "Ni… Zein pozik nagoen!\p"
	.string "Ni! Nire izena {STR_VAR_1} da!\n"
	.string "ENTRENATZAILE bilakatu berri naiz!\p"
	.string "Pozten naiz ezagutzeaz, {PLAYER},\n"
	.string "POKéMON munduan entzutetsua zara!\p"
	.string "Oh-oh-oh, badakit!\n"
	.string "Eska diezazuket mesede bat, {PLAYER}?\p"
	.string "Har nazazu zure ikasle gisan!\n"
	.string "Zugandik ikasi nahi nuke!$"

gText_ApprenticeRejectTeaching8::
	.string "Waaaah!\n"
	.string "{PLAYER}, ezetz esan didazu…\l"
	.string "Baina… Izugarria izan behar zen!\p"
	.string "{PLAYER}, faborez! Oraingoan baietz\n"
	.string "esango didazu, ezta?\p"
	.string "Zure laguntza behar dut!$"

gText_ApprenticeWhichLevelMode8::
	.string "Iujuuuu! {PLAYER}(e)k baiez esan dit!\n"
	.string "{PLAYER}(e)k baietz esan dit!\p"
	.string "Ezingo dut lorik egin gaur…\n"
	.string "Mila esker, zinez!\p"
	.string "Orduan, hau da nire galdera!\p"
	.string "BORROKA DORREAN, zein da niretzat\n"
	.string "egokiena, 50. Maila edo Maila irekia?$"

gText_ApprenticeLevelModeThanks8::
	.string "{STR_VAR_1}! Ulertuta!\n"
	.string "Ederki ulertuta, gainera!\l"
	.string "Zinez pozik nago orain!\p"
	.string "Espero dut hurrengo batean gehiago\n"
	.string "irakatsi ahalko didazula.$"

gText_ApprenticePleaseTeach9::
	.string "Baina! Ez al zara zu…\n"
	.string "Zu al zara benetan… {PLAYER}{KUN}?!\l"
	.string "ENTRENATZAILE famatu eta indartsua?\l"
	.string "Ene, nolako zortea izan dudan!\p"
	.string "Kaixo, ni {STR_VAR_1} naiz!\p"
	.string "POKéMON irakasle baten bila\n"
	.string "aritu naiz aspaldian.\p"
	.string "Eta justu zurekin gurutzatu,\n"
	.string "nolako zortea, {PLAYER}{KUN}!\p"
	.string "Ba horixe, {PLAYER}{KUN}!\n"
	.string "Utzi zure ikaslea izaten!$"

gText_ApprenticeRejectTeaching9::
	.string "Eeeeeez!\n"
	.string "Zu guaia eta gogorra zara…\p"
	.string "Ez izan horrelakoa, mesedez.\n"
	.string "Bihotzez eskatzen ari naiz!$"

gText_ApprenticeWhichLevelMode9::
	.string "Izugarria! Hori bai erantzuna!\n"
	.string "Bikaina, esango nuke!\p"
	.string "Hasi gaitezen orduan BORROKA DORREAREN\n"
	.string "inguruko galdera batekin.\p"
	.string "Nire kasuan zein litzateke egokiena?\n"
	.string "50. Maila edo Maila Irekia?$"

gText_ApprenticeLevelModeThanks9::
	.string "Ados, {STR_VAR_1}, beraz!\n"
	.string "Bai jauna!\l"
	.string "Nire indarra erakutsiko dut!\p"
	.string "Ederki, nire irakasletzat hartuko zaitut!\n"
	.string "Aio!$"

gText_ApprenticePleaseTeach10::
	.string "Kaixo, {PLAYER}{KUN}, ezta?\n"
	.string "Polizia zure bila dabil!\p"
	.string "… … …\n"
	.string "Noski gezurretan ari naizela!\p"
	.string "{STR_VAR_1} naiz. Nire itxura\n"
	.string "gorabehera, POKéMON TXAPELDUNA Naiz!\l"
	.string "…Hori ere gezurra zen, bada!\p"
	.string "Honakoa ez da gezurra ordea.\n"
	.string "Ez naiz oso ona borrokan.\p"
	.string "Zer iruditzen zaizu nire irakasle\n"
	.string "bihurtzen bazara?$"

gText_ApprenticeRejectTeaching10::
	.string "Horrela erantzun behar badidazu,\n"
	.string "Zer egin dezakedan erakutsiko dizut!\p"
	.string "Buaaaa! Buaaaa! Buaaaa!\n"
	.string "Zintz!\p"
	.string "Kar-kar, nire MALKO FALTSUAK entzun dituzu!\p"
	.string "Aizu, izango al zara nire POKéMON\n"
	.string "irakaslea, mesedez?$"

gText_ApprenticeWhichLevelMode10::
	.string "Iujuuuu!\n"
	.string "Itsasontzi bat erosiko dizut!\p"
	.string "Hori ere gezurra zen, noski!\n"
	.string "Baina… Eskerrik asko, irakasle!\p"
	.string "BORROKA DORREAN badakizu 50. Maila\n"
	.string "eta Maila Irekia daudela, ezta?\p"
	.string "Duda itzelak izaten ari naiz, eta\n"
	.string "ez dakit zein maila aukeratu…\p"
	.string "Aukeratu dezakezu zuk, irakasle?$"

gText_ApprenticeLevelModeThanks10::
	.string "Ados, {STR_VAR_1} hobe da, orduan!\n"
	.string "Orduan beste mailara apuntutatuko naiz!\p"
	.string "Txantxa da!\n"
	.string "Kasu egindo dizut, irakasle!\p"
	.string "Mila esker, irakasle!\n"
	.string "Gehiago irakatsiko didazula espero dut!$"

gText_ApprenticePleaseTeach11::
	.string "I-E-P-A T-X-O!\n"
	.string "Horrek iepa txo osatzen du!\p"
	.string "{STR_VAR_1} naiz, MARINEL raperoa\n"
	.string "alajaina!\p"
	.string "Zure txanda orain, kontatu zerbait\n"
	.string "zure inguruan, nik ezagutzeko lain!\p"
	.string "Uh-huh, uh-huh!\n"
	.string "{PLAYER}{KUN} zure izena,\l"
	.string "POKéMONEKIN onena!\p"
	.string "Gaztea zara gainera,\n"
	.string "mundua esploratzeko tankera!\p"
	.string "Bestalde, esan nahi dut\n"
	.string "gaur hitz egin diodan hamargarrena\l"
	.string "zarela, zin egiten dizut.\p"
	.string "Ospatu dezagun biok, orduan!\n"
	.string "Nire irakasle izateko iritsi den orduan!$"

gText_ApprenticeRejectTeaching11::
	.string "Baina!\n"
	.string "Egin lan nirekin!\p"
	.string "Nire galderei erantzunez,\n"
	.string "izan nire irakasle, mesedez!$"

gText_ApprenticeWhichLevelMode11::
	.string "Hori bai itzela!\n"
	.string "{PLAYER}, benetan onena zarela!\p"
	.string "Hau da nire lehen galdera\n"
	.string "zuk erantzute aldera!\p"
	.string "BORROKA DORREAren inguruan da,\n"
	.string "eman iezadazu bultzada!\p"
	.string "50. Maila edo Maila Irekia,\n"
	.string "zein da bietan niretzat egokia?$"

gText_ApprenticeLevelModeThanks11::
	.string "Ongi, {STR_VAR_1} beraz!\n"
	.string "banoa, eta irabaziko dut erraz!\p"
	.string "Zure laguntza behar badut,\n"
	.string "{PLAYER}, dudarik gabe galdetuko dizut!$"

gText_ApprenticePleaseTeach12::
	.string "Ei, kaixo, {PLAYER} al zara?\n"
	.string "Zer egin behar dut? Zurekin hitz egin?\l"
	.string "Zergatik ez? Jada ari naiz eta!\p"
	.string "{PLAYER}, harrituta al zaude?\n"
	.string "Nor naizen kontatuko dizut, berandutu gabe!\p"
	.string "{STR_VAR_1} deitzen didate.\n"
	.string "Munduko gitarrajole onena,\l"
	.string "ezbairik gabe!\p"
	.string "Entzuten al didazu?\n"
	.string "Entzuten didazu!\p"
	.string "Hau zortea nirea,\n"
	.string "eskari hau izango da zurea!\p"
	.string "{PLAYER}, utzi zure ikaslea izaten!\n"
	.string "Guztia ikasi nahi dut, goraipa nazaten!$"

gText_ApprenticeRejectTeaching12::
	.string "Ezezkoa, beraz?\n"
	.string "Berriz galdetuko dizut orduan, erraz!\p"
	.string "{PLAYER}, utzi zure ikaslea izaten!\n"
	.string "Guztia ikasi nahi dut, goraipa nazaten!$"

gText_ApprenticeWhichLevelMode12::
	.string "Hori da, bikain, aizu!\n"
	.string "Bada orduan tipo honek galdera botako dizu.\p"
	.string "BORROKA DORRE inguruan gaudenez,\n"
	.string "horren inguruan egingo dizut galdera, ez?\p"
	.string "Aukera hautetik guztietatik,\n"
	.string "zen hartu behar nuke nik?$"

gText_ApprenticeLevelModeThanks12::
	.string "{STR_VAR_1} dela onena uste baduzu,\n"
	.string "egia izango da, ziur nauzu!\p"
	.string "Beno, {PLAYER}, banoa mundu zabalera,\n"
	.string "ez nazazu ahaztu, itzuliko naiz, atzera.\p"
	.string "Hurrengora arte, nire lagun azkarra!$"

gText_ApprenticePleaseTeach13::
	.string "Iepa, kaixo! Zu, bai!\n"
	.string "Emango zenidake masaje bat sorbaldan?\p"
	.string "…Bai, hortxe! Hori da!\n"
	.string "Ai, ai! Hau bai masaje bikaina!\p"
	.string "Nire izena {STR_VAR_1} da.\n"
	.string "karatea egiten dut, baina nire gorputza\l"
	.string "ez dago kolpeetara ohitua…\p"
	.string "POKéMONAK entrenatzea erabaki dut\n"
	.string "ni ere gogortzeko.\p"
	.string "{PLAYER}{KUN} zara, ezta?\n"
	.string "POKéMON LIGAKO TXAPELDUNA?\p"
	.string "Entzun, emango zenizkidake\n"
	.string "aholku batzuk?$"

gText_ApprenticeRejectTeaching13::
	.string "Zergatik?\p"
	.string "Ez dizut traba handirik egingo!\n"
	.string "Mesedez?$"

gText_ApprenticeWhichLevelMode13::
	.string "Eskerrik asko. Zu bai jatorra!\n"
	.string "…Atxu! Atxu!\p"
	.string "Azkarrago indartu beharko naiz…\p"
	.string "BORROKA DORRERA noa oraintxe, zein\n"
	.string "maila izango litzateke egokiagoa\l"
	.string "niretzat? 50. Maila edo Maila Irekia?$"

gText_ApprenticeLevelModeThanks13::
	.string "Ados. {STR_VAR_1}, orduan.\n"
	.string "Banoa bertara, orduan.\p"
	.string "Espero dut gehiagotan laguntzeko prest egongo\n"
	.string "zarela. Azkenean, nire irakaslea zara!$"

gText_ApprenticePleaseTeach14::
	.string "Bueno… E…\n"
	.string "{PLAYER}{KUN}…?\p"
	.string "Mesedez, ez begiratu horrela.\n"
	.string "Urduri jartzen ari naiz.\p"
	.string "Ni… {STR_VAR_1} naiz.\p"
	.string "Lotsa ematen dit esateak, baina\n"
	.string "antzinako hondakinak aztertzen ditut.\p"
	.string "Are lotsa handiago ematen dit BORROKA\n"
	.string "FRONTEAN dudan interesa adierazteak.\p"
	.string "{PLAYER}{KUN}, jakina da zu ENTRENATZAILE\n"
	.string "indartsua zarela…\p"
	.string "Zaila da niretzat hau esatea, baina\n"
	.string "zeozer galdetu nahi dizut.\p"
	.string "Izango zara nire irakaslea niri\n"
	.string "aholkuak emateko?$"

gText_ApprenticeRejectTeaching14::
	.string "Mesedez, ez esan ezetz!\n"
	.string "Ezingo nuke umiliazio honekin.\p"
	.string "izan nire irakaslea!\n"
	.string "Zure aholkuak behar ditut!$"

gText_ApprenticeWhichLevelMode14::
	.string "Mi-mila esker…\p"
	.string "Baina ez begiratu horrela, mesedez.\n"
	.string "Asko lotsatzen naiz eta.\p"
	.string "Mesedez, erantzun begietara begiratu\n"
	.string "gabe, ahal baduzu.\p"
	.string "BORROKA DORREAN…\n"
	.string "Zein maila aukeratu behar nuke?$"

gText_ApprenticeLevelModeThanks14::
	.string "Bada… Ados!\n"
	.string "Saiatuko naiz, orduan.\p"
	.string "Ea lortzen dudan lotsatu gabe\n"
	.string "erronkan ongi moldatzea…\p"
	.string "Eskerrik asko, {PLAYER}{KUN}.\n"
	.string "Berriz aurkitzen bazaitut, ziur nago\l"
	.string "lagungarria izango zarela.$"

gText_ApprenticePleaseTeach15::
	.string "Nola? {PLAYER}{KUN} zara, esango nuke…\n"
	.string "Benetakoa zara, ordea?\p"
	.string "Niri {STR_VAR_1} dei diezadakezu.\p"
	.string "ENTRENATZAILE indartsu baten ikasle\n"
	.string "izatea pentsatzen aritu naiz azkenaldian.\p"
	.string "Beno, badirudi zortea izan dudala!\n"
	.string "…{PLAYER}{KUN} zara benetan, ezta?\p"
	.string "Ez, ez, hala bada, bikain.\n"
	.string "Zure ikasle bezala hartzea soilik\l"
	.string "nahi nuke.$"

gText_ApprenticeRejectTeaching15::
	.string "Zer?\n"
	.string "Baina zergatik esan didazu ezetz?\p"
	.string "Barkatu ez sinesteagatik nor zinen\n"
	.string "benetan.\p"
	.string "Mesedez, barka iezadazu eta\n"
	.string "har nazazu ikasletzat.$"

gText_ApprenticeWhichLevelMode15::
	.string "Benetan hartuko nauzu?\n"
	.string "Ez dut aldez aurretik ospatuko.\p"
	.string "Egiatan ari bazara, barkatu.\n"
	.string "Baina orain zure aholkua behar dut.\p"
	.string "BORROKA DORRERA joatekoa naiz,\n"
	.string "zein maila aukeratu behar nuke?\l"
	.string "50. Maila edo Maila Irekia?$"

gText_ApprenticeLevelModeThanks15::
	.string "{STR_VAR_1}?\n"
	.string "Ziur al zaude?\p"
	.string "Ongi. Zuk hala badiozu, hala izango da.\n"
	.string "Eskerrik asko zure denboragatik.\p"
	.string "Badakit astuna izan naitekeea, baina\n"
	.string "eskertzen dizut ni onartu izana.\p"
	.string "Ea berriz elkartzen garen!$"

gText_ApprenticeWhatHeldItem0::
	.string "Ai… Zintz…\n"
	.string "Ene, {PLAYER}!\p"
	.string "Dilema izugarria daukat eta ez\n"
	.string "dakiz zer aukeratu.\p"
	.string "Ez dakit zein item eman nire\n"
	.string "{STR_VAR_1}(e)ri.\p"
	.string "mesedez, esan, {PLAYER}.\n"
	.string "Zein item eduki behar luke?$"

gText_ApprenticeHoldNothing0::
	.string "Benetan? Ez nioke objekturik\n"
	.string "eman behar {STR_VAR_1}(e)ri?$"

gText_ApprenticeThanksNoHeldItem0::
	.string "Ongi! Eskerrak lagundu didazun!\n"
	.string "Bikain! Itzel! Iujuuu!\p"
	.string "Eskerrik asko, zinez!$"

gText_ApprenticeThanksHeldItem0::
	.string "Ah, eskerrak…\n"
	.string "Uste dut badaukadala {STR_VAR_1} bat.\p"
	.string "Eskerrak lagundu didazun!\n"
	.string "Bikain! Itzel! Iujuuu!\p"
	.string "Eskerrik asko, zinez!$"

gText_ApprenticeItemAlreadyRecommended0::
	.string "Eeeez! Ez izan horrelakoa, faborez!\p"
	.string "{STR_VAR_1} itema jada gomendatu\n"
	.string "didate lehenago. Zintz…\p"
	.string "Edo hobe al litzateke ez ematea\n"
	.string "itemik {STR_VAR_2}(e)ri?$"

gText_ApprenticeWhatHeldItem1::
	.string "Bai jauna! {PLAYER} da eta!\n"
	.string "Itzel! Zerbait galdetu behar dizut!\p"
	.string "Ematen dizkiezu itemak zure POKéMONEI?\n"
	.string "Nireei eman nahi nizkieke, baina…\p"
	.string "Zein item litzateke egokia nire\n"
	.string "{STR_VAR_1}(r)entzat?\p"
	.string "Zer uste duzu?$"

gText_ApprenticeHoldNothing1::
	.string "Zer? Nire {STR_VAR_1}(e)k ez luke\n"
	.string "objekturik eduki behar?$"

gText_ApprenticeThanksNoHeldItem1::
	.string "Ados, ulertuta! Horixe egingo dut!\n"
	.string "Eskerrik asko aholkuagatik!$"

gText_ApprenticeThanksHeldItem1::
	.string "Ados! {STR_VAR_1}, beraz?\n"
	.string "Bikain, Horixe egingo dut!\p"
	.string "Eskerrik asko aholkuagatik!$"

gText_ApprenticeItemAlreadyRecommended1::
	.string "Ez, ez. Ez nuen hori esan nahi.\n"
	.string "Ezagutzen ditudan itemak ez, zerbait\l"
	.string "berria izan behar da.\p"
	.string "Edo esan nahi duzu nire POKéMONAK\n"
	.string "ez duela itemik behar?$"

gText_ApprenticeWhatHeldItem2::
	.string "{PLAYER}, kaixo!\n"
	.string "Nire {STR_VAR_1}(r)en inguruan da…\p"
	.string "Item egoki bat eman nahi diot.\n"
	.string "Zer eman behar nioke zure ustez?$"

gText_ApprenticeHoldNothing2::
	.string "Orduan nire {STR_VAR_1}(e)k ez du\n"
	.string "itemik behar?$"

gText_ApprenticeThanksNoHeldItem2::
	.string "ongi, ulertuta!\n"
	.string "Hurrengora arte!$"

gText_ApprenticeThanksHeldItem2::
	.string "Beraz, {STR_VAR_1} itema?\n"
	.string "Ulertuta!\p"
	.string "Saiatuko naiz bat aurkitzen!\n"
	.string "Hurrengora arte!$"

gText_ApprenticeItemAlreadyRecommended2::
	.string "Norbaitek esan zidan emateko\n"
	.string "{STR_VAR_1}, bai.\p"
	.string "Beste item mota bat nahi dut\n"
	.string "nire POKéMONARENTZAT.\p"
	.string "Edo agian {STR_VAR_2}(e)k ez du\n"
	.string "itemik behar?$"

gText_ApprenticeWhatHeldItem3::
	.string "Kaixo, {PLAYER}…\n"
	.string "Barkatu traba egitea, baina beste\l"
	.string "galdera bat dut zuretzat.\p"
	.string "Uste dut orain nabilen bezala ez\n"
	.string "naizela gai borrokak irabazteko, beraz,\l"
	.string "{STR_VAR_1}(e)ri item bat eman nahi diot.\p"
	.string "Baina ez dakit zein item eman.\p"
	.string "{PLAYER}, mesedez, erabakiko zenuke\n"
	.string "nire partez?$"

gText_ApprenticeHoldNothing3::
	.string "Nire POKéMONAK hobe egongo lirateke\n"
	.string "inolako itemik gabe?$"

gText_ApprenticeThanksNoHeldItem3::
	.string "Ulertzen dut…\n"
	.string "Ez nintzateke itemen menpe egon behar.\l"
	.string "Saiatuko naiz ez erabiltzen!\p"
	.string "Eskerrik asko, benetan!$"

gText_ApprenticeThanksHeldItem3::
	.string "{STR_VAR_1} itema, beraz.\n"
	.string "Ez dakit ea bat lortuko dudan…\l"
	.string "Ez! Noski lortuko dudala.\p"
	.string "Eskerrik asko, benetan!$"

gText_ApprenticeItemAlreadyRecommended3::
	.string "Baina, baina…\n"
	.string "Uste dut ezagutzen dudala itema jada…\p"
	.string "Agian ez dut ondo erabili {STR_VAR_1}\n"
	.string "itema orain arte?\p"
	.string "Edo ez nioke itemik eman behar\n"
	.string "nire {STR_VAR_2}(e)ri?$"

gText_ApprenticeWhatHeldItem4::
	.string "Ei, {PLAYER}{KUN}.\n"
	.string "Zerbait galdetu nahi nizuke.\p"
	.string "gogoratzen zara niretzako POKéMON\n"
	.string "bat aukeratzeko eskatu nizula?\p"
	.string "Bada, ez nizun galdetu zein\n"
	.string "item eman behar nion.\p"
	.string "Jada lagundu didazunez,\n"
	.string "lagunduko zenidake bigarrenez?\p"
	.string "Zer litzateke egokia? Zeozer eman\n"
	.string "nahi diot {STR_VAR_1}(e)ri.$"

gText_ApprenticeHoldNothing4::
	.string "Ah! Nire {STR_VAR_1}(e)k orduan\n"
	.string "ezer gabe borrokatu behar luke?$"

gText_ApprenticeThanksNoHeldItem4::
	.string "Hori dela onena uste baduzu, hala bedi.\p"
	.string "Zuk hartu duzunez erabakia,\n"
	.string "{PLAYER}{KUN}, ez naiz haserretuko\l"
	.string "galtzen badut ere.\p"
	.string "Ongi, bueltatuko naiz aholku bila.\n"
	.string "Aio!$"

gText_ApprenticeThanksHeldItem4::
	.string "{STR_VAR_1} itema, beraz?\n"
	.string "Ez dago gaizki. Erabiliko dut!\p"
	.string "Zuk hartu duzunez erabakia,\n"
	.string "{PLAYER}{KUN}, ez naiz haserretuko\l"
	.string "galtzen badut ere.\p"
	.string "Ongi, bueltatuko naiz aholku bila.\n"
	.string "Aio!$"

gText_ApprenticeItemAlreadyRecommended4::
	.string "Zer? Zer diozu, baina?\n"
	.string "Jada esan zenidan {STR_VAR_1}\l"
	.string "emateko.\p"
	.string "Edo esan nahi duzu {STR_VAR_2} itemik\n"
	.string "gabe ibili behar dela?$"

gText_ApprenticeWhatHeldItem5::
	.string "Ei, {PLAYER}{KUN}!\p"
	.string "Biok okupatuta, baina hala ere\n"
	.string "beti elkar ikusten dugu azkenean!\p"
	.string "Gaur, pixka bat ibili, garbitu\n"
	.string "eta erratza pasa behar dut.\p"
	.string "Ez dut denborarik izan ezer erosteko\n"
	.string "nire {STR_VAR_1} maitearentzat.\p"
	.string "Denborarik ez dudanez, aholkatuko\n"
	.string "zenidake zein item eman nire\l"
	.string "{STR_VAR_1}(e)ri?$"

gText_ApprenticeHoldNothing5::
	.string "Mutil okupatua naizenez, ez nioke\n"
	.string "itemik eman behar {STR_VAR_1}(e)ri?$"

gText_ApprenticeThanksNoHeldItem5::
	.string "Ongi, ulertuta.\n"
	.string "Ez dut horretarako denborarik behar.\p"
	.string "Mila esker!\n"
	.string "Ondo ibili!$"

gText_ApprenticeThanksHeldItem5::
	.string "Ongi, ulertuta.\n"
	.string "Aterako dut denbora gomendatutako\l"
	.string "{STR_VAR_1} erosteko.\p"
	.string "Eskerrak irakasle bikaina zaren.\n"
	.string "Mila esker! Ondo ibili!$"

gText_ApprenticeItemAlreadyRecommended5::
	.string "Zer? jada ezagutzen dut\n"
	.string "{STR_VAR_1}, ordea.\p"
	.string "Ah, ulertzen dut.\n"
	.string "Mutil okupatua naizenez, ez nioke\l"
	.string "itemik eman behar {STR_VAR_2}(e)ri?$"

gText_ApprenticeWhatHeldItem6::
	.string "Iepa, {PLAYER}! Ni naiz!\n"
	.string "Zure laguntza bila nator gaur.\l"
	.string "Mesedez, zure aholkua behar dut!\p"
	.string "Erredoblea, mesedez!\n"
	.string "Nire galdera da…\p"
	.string "Nire {STR_VAR_1}(e)ri item bat\n"
	.string "ematekotan, zein eman behar nioke?$"

gText_ApprenticeHoldNothing6::
	.string "Benetan? Nire {STR_VAR_1}(e)k ez du\n"
	.string "itemik behar, zure iritziz.$"

gText_ApprenticeThanksNoHeldItem6::
	.string "Ongi, hori egingo dut orduan!\p"
	.string "Hori da gaurkoz galdetu nahi\n"
	.string "nizun guztia.\p"
	.string "Hemen elkartuko gara berriz, bai?\n"
	.string "Eskerrik asko!$"

gText_ApprenticeThanksHeldItem6::
	.string "Bikain! {STR_VAR_1}, beraz.\n"
	.string "Hori bai aukera bikaina!\l"
	.string "Probatuko dut, bai!\p"
	.string "hori da gaurkoz galdetu nahi\n"
	.string "nizun guztia.\p"
	.string "Hemen elkartuko gara berriz, bai?\n"
	.string "Eskerrik asko!$"

gText_ApprenticeItemAlreadyRecommended6::
	.string "Kar-kar! Zu bai zu bromazalea!\n"
	.string "Jada esan zenidan {STR_VAR_1}\l"
	.string "erabiltzeko aurrekoan!\p"
	.string "Ondo al zaude, {PLAYER}?\p"
	.string "Itxaron! Nire {STR_VAR_2}(e)k ez\n"
	.string "duela itemik behar esan nahi duzu.$"

gText_ApprenticeWhatHeldItem7::
	.string "Kaixo, {PLAYER}. Ondo zaudela\n"
	.string "espero dut.\p"
	.string "galde diezazuket zerbait?\p"
	.string "Duela gutxi, borroka batean,\n"
	.string "nire aurkariak item bat eman\l"
	.string "zion bere POKéMONARI.\p"
	.string "Horregatik galdu nuen…\p"
	.string "Eta ez nuke nahi atzean gelditu.\n"
	.string "Nire {STR_VAR_1}(e)k item bat\l"
	.string "edukitzea nahi dut.\p"
	.string "Nire POKéMONARENTZAT item bat\n"
	.string "aukeratzen lagunduko bazenit…$"

gText_ApprenticeHoldNothing7::
	.string "Bestela esanda… Nire POKéMONAK ez\n"
	.string "du itemik behar?$"

gText_ApprenticeThanksNoHeldItem7::
	.string "Ondo ulertzen dut orain!\n"
	.string "Horrela saiatuko naiz orduan.\p"
	.string "Eskerrik asko, {PLAYER}.\n"
	.string "Espero dut gehiagotan lagunduko didazula.\l"
	.string "Zaindu zaitez!$"

gText_ApprenticeThanksHeldItem7::
	.string "{STR_VAR_1}, orduan!\n"
	.string "Oraintxe bertan eskatuko dut.\p"
	.string "Eskerrik asko, {PLAYER}.\n"
	.string "Espero dut gehiagotan lagunduko didazula.\l"
	.string "Zaindu zaitez!$"

gText_ApprenticeItemAlreadyRecommended7::
	.string "Bai, esan zenidan hori aurrekoan,\n"
	.string "eta jada probatu nuen.\p"
	.string "Edo esan nahi duzu… Nire POKéMONAK\n"
	.string "ez duela itemik behar?$"

gText_ApprenticeWhatHeldItem8::
	.string "Iei! {PLAYER}!\n"
	.string "Nolako poza ematen didan zu berriz ikusteak!\p"
	.string "Oh-oh-oh! Zerbait galdetu nahi\n"
	.string "nizuke, {PLAYER}!\p"
	.string "Mesedez esan zein item eman\n"
	.string "nire {STR_VAR_1}(e)ri!$"

gText_ApprenticeHoldNothing8::
	.string "Ene! Ez nuen erantzun hori espero!\n"
	.string "Beraz, ez da beharrezkoa item bat ematea?$"

gText_ApprenticeThanksNoHeldItem8::
	.string "Bikain, ulertuta!\n"
	.string "Ez diot itemik emango, orduan!\p"
	.string "Beste batean are gehiago erakutsiko\n"
	.string "didazula espero dut.$"

gText_ApprenticeThanksHeldItem8::
	.string "{STR_VAR_1}! Hori erabiliko du!\p"
	.string "Eta… Posible da, {PLAYER}, zuk ere\n"
	.string "POKéMONARI item hori ematea?\p"
	.string "Nik behintzat bat lortuko dut!\n"
	.string "Hurrengoan are gehiago erakutsiko\l"
	.string "didazula espero dut.$"

gText_ApprenticeItemAlreadyRecommended8::
	.string "Zer? Gomendatu zenida\n"
	.string "{STR_VAR_1} lehenago, baina.\p"
	.string "Hori al da objektu onena?\n"
	.string "Edo esan nahi duzu {STR_VAR_2}(e)k\l"
	.string "ez duela itemik behar?$"

gText_ApprenticeWhatHeldItem9::
	.string "Aupa!\n"
	.string "Nire irakaslea, {PLAYER}{KUN}!\p"
	.string "Zure aholkua behar dut POKéMON\n"
	.string "erreminten gainean.\p"
	.string "Zein litzateke objektu on bat\n"
	.string "nire {STR_VAR_1}(r)entzat?\p"
	.string "Ez izan lotsarik.\n"
	.string "Bota, bota!$"

gText_ApprenticeHoldNothing9::
	.string "Zer? Nire {STR_VAR_1}(e)k ez duela\n"
	.string "zertan itemik eduki?$"

gText_ApprenticeThanksNoHeldItem9::
	.string "Bai, bikain!\n"
	.string "Horrela saiatuko naiz, beraz!\p"
	.string "Bikain, eskerrik asko, beti legez!\n"
	.string "Aio!$"

gText_ApprenticeThanksHeldItem9::
	.string "Ados, {STR_VAR_1}, orduan?\n"
	.string "Bai, bikain!\l"
	.string "Saiatuko naiz ziztuan bat bilatzen!\p"
	.string "Bikain, eskerrik asko, beti legez!\n"
	.string "Aio!$"

gText_ApprenticeItemAlreadyRecommended9::
	.string "Ez, ez! Jada esan zenidan\n"
	.string "{STR_VAR_1} erabiltzeko.\p"
	.string "Itxaron segundu bat…\n"
	.string "Esan nahi duzu {STR_VAR_2}(e)k\l"
	.string "itemik gabe irabazi dezakeela?$"

gText_ApprenticeWhatHeldItem10::
	.string "{PLAYER}{KUN}, zerbait izugarria\n"
	.string "gertatu da!\p"
	.string "Goizean esnatu eta nire POKéMONAK\n"
	.string "10 URREZKO PIPITA zituen!\p"
	.string "Noski gezurra dela!\n"
	.string "Kar-kar!\p"
	.string "Hau egia da, ordea.\n"
	.string "Ez naiz oso ona nire POKéMONARENTZAT\l"
	.string "item egokiak aukeratzen.\p"
	.string "Aukeratuko zenuke nire partez\n"
	.string "zein item eman {STR_VAR_1}(e)ri?$"

gText_ApprenticeHoldNothing10::
	.string "Zer esan nahi duzu?\n"
	.string "Ez emateko objekturik?$"

gText_ApprenticeThanksNoHeldItem10::
	.string "Ongi, beraz, ez ezer emateko diozu.\n"
	.string "Beno, ba orduan banoa zerbait erostera!\p"
	.string "Txantxa da!\n"
	.string "Kasu egingo dizut, irakasle!\p"
	.string "Eskerrik asko, irakasle!\n"
	.string "Gehiago irakatsiko didazula espero dut!$"

gText_ApprenticeThanksHeldItem10::
	.string "Ongi, orduan, {STR_VAR_1}!\n"
	.string "Hori ez, beste edozer emango diot orduan!\p"
	.string "Txantxa da!\n"
	.string "Kasu egingo dizut, irakasle!\p"
	.string "Eskerrik asko, irakasle!\n"
	.string "Gehiago irakatsiko didazula espero dut!$"

gText_ApprenticeItemAlreadyRecommended10::
	.string "Baina, esan didazu hori lehenago,\n"
	.string "ez da hala?\p"
	.string "Ez al dago beste ezer, bada?\p"
	.string "Edo esan nahi duzula ez emateko\n"
	.string "ezer {STR_VAR_2}(e)ri?$"

gText_ApprenticeWhatHeldItem11::
	.string "I-E-P-A T-X-O!\n"
	.string "Horrek iepa txo osatzen du!\p"
	.string "MARINEL raperoa naiz ni!\n"
	.string "Eta zuretzat galdera bat\l"
	.string "dut, hala bedi!\p"
	.string "Galdera itemen inguruan da,\n"
	.string "ea erantzuten didazun, di-da!\p"
	.string "Nire {STR_VAR_1}(e)k itema behar du.\n"
	.string "Zer emango diot, irabazi nahi badu?$"

gText_ApprenticeHoldNothing11::
	.string "Benetan ari al zara?\n"
	.string "Nire {STR_VAR_1}(e)k ez duela\l"
	.string "itemik behar? Hara!$"

gText_ApprenticeThanksNoHeldItem11::
	.string "Ongi, ongi. Ulertze dizut!\n"
	.string "Nire POKéMONA esku hutsik utziko dut!\p"
	.string "Eta aholkurik behar badut,\n"
	.string "{PLAYER}, zuri galdetuko dizut!$"

gText_ApprenticeThanksHeldItem11::
	.string "Ongi, {STR_VAR_1} orduan,\n"
	.string "aise erabiliko dut hurrengo enkontruan.\l"
	.string "Zuri galdetzea ideia bikaina da beti!\p"
	.string "Eta aholkurik behar badut,\n"
	.string "{PLAYER}, zuri galdetuko dizut!$"

gText_ApprenticeItemAlreadyRecommended11::
	.string "Ongi, {STR_VAR_1}, beraz?\n"
	.string "Hori esan zenidan aurrekoan.\l"
	.string "Zeozer berria behar dut gaurkoan.\p"
	.string "Edo, zer esan nahi duzu?\n"
	.string "Nire POKéMONAK itemik ez duela\l"
	.string "behar, aizu?$"

gText_ApprenticeWhatHeldItem12::
	.string "Ei, aupa, {PLAYER}!\n"
	.string "Aurkitu zaitut berriro!\p"
	.string "Zer egin behar nuke? Zuri aholkua eskatu?\n"
	.string "Zergatik ez? Jada ari naiz eta!\p"
	.string "{PLAYER}, nitaz nazkatzen ari zara?\n"
	.string "Ez, bai zera, hori ezinezkoa da.\p"
	.string "Entzungo zenidake?\n"
	.string "Aholku bila nabil, zureak\l"
	.string "asko lagunduko lidake.\p"
	.string "{STR_VAR_1}(r)entzat item\n"
	.string "egoki baten bila ari naiz.\l"
	.string "Aukeratzea kostatzen zait maiz.$"

gText_ApprenticeHoldNothing12::
	.string "Nire {STR_VAR_1}(e)k ez du ezer behar?\n"
	.string "Nahiz borroka egin egun guztian zehar?$"

gText_ApprenticeThanksNoHeldItem12::
	.string "Ezer ez edukitzea bada onena,\n"
	.string "hori da izango duena!\p"
	.string "Beno, {PLAYER}, banoa mundu zabalera,\n"
	.string "ez nazazu ahaztu, itzuliko naiz, atzera.\p"
	.string "Hurrengora arte, nire lagun azkarra!$"

gText_ApprenticeThanksHeldItem12::
	.string "{STR_VAR_1} edukitzea bada onena,\n"
	.string "horixe da izango duena!\p"
	.string "Beno, {PLAYER}, banoa mundu zabalera,\n"
	.string "ez nazazu ahaztu, itzuliko naiz, atzera.\p"
	.string "Hurrengora arte, nire lagun azkarra!$"

gText_ApprenticeItemAlreadyRecommended12::
	.string "Ez al didazu lehenago esan\n"
	.string "{STR_VAR_1} emateko?\l"
	.string "Badakit baietz, ni bainaiz memoria oneko!\p"
	.string "Zeozer berria esan behar didazu!\n"
	.string "Edo {STR_VAR_2}(e)k ez du ezer behar, aizu?\l"
	.string "Ez al du objekturik behar benetan?$"

gText_ApprenticeWhatHeldItem13::
	.string "Ai! Autx! {PLAYER}{KUN}, besoa hautsia dut!\n"
	.string "Ez ukitu, mesedez!\p"
	.string "Agian itemak eusten probatzen ari nintzela\n"
	.string "hautsi dut, POKéMONEN plantak egitea\l"
	.string "ez da gauza makala!\p"
	.string "Beraz, kontuak kontu, erabakitzen\n"
	.string "lagundu behar didazu.\p"
	.string "{PLAYER}{KUN}, zei item da nire\n"
	.string "{STR_VAR_1}(r)entzat egokia?$"

gText_ApprenticeHoldNothing13::
	.string "Autx…\p"
	.string "Beraz, nire {STR_VAR_1}(e)k itemik\n"
	.string "ez edukitzea gomendatzen didazu?$"

gText_ApprenticeThanksNoHeldItem13::
	.string "Ados, bada. Errazago niretzat,\n"
	.string "besoa nola dudan kontuan hartuta.\p"
	.string "Gehiagotan laguntza eske etorriko\n"
	.string "naiz, inporta ez badizu.$"

gText_ApprenticeThanksHeldItem13::
	.string "Ados, bada. {STR_VAR_1} orduan.\n"
	.string "Nire POKéMONAK ondo du besoa,\l"
	.string "ez du arazorik izango hartzeko.\p"
	.string "Gehiagotan laguntza eske etorriko\n"
	.string "naiz, inporta ez badizu.$"

gText_ApprenticeItemAlreadyRecommended13::
	.string "Ez, ez, gomendatu zenidan\n"
	.string "{STR_VAR_1} lehenago, gogoratzen?\p"
	.string "Zergatik ez didazu beste zerbait\n"
	.string "esaten, are hobea?\p"
	.string "Ene, itxaron.\n"
	.string "Esan nahi duzuna da {STR_VAR_2}(e)k\l"
	.string "ez duela ezer eduki beharrik?$"

gText_ApprenticeWhatHeldItem14::
	.string "E… Bueno…\n"
	.string "{PLAYER}{KUN}…\p"
	.string "Mesedez, ez begiratu horrela.\n"
	.string "Nire POKéMONEK ez daukate ezer.\p"
	.string "Niri… Lotsa handia ematen dit honek,\n"
	.string "baina zure aholkua behar dut, zinez.\p"
	.string "Ez dakit zein item erabili nire\n"
	.string "{STR_VAR_1} indartsuagoa izan dadin.\p"
	.string "{PLAYER}{KUN}, zure ustez zer litzateke\n"
	.string "egokia?$"

gText_ApprenticeHoldNothing14::
	.string "Beraz… Uste duzu egokiena {STR_VAR_1}\n"
	.string "item gabe uztea dela?$"

gText_ApprenticeThanksNoHeldItem14::
	.string "Beno… Ados!\n"
	.string "Item gabe utziko dut orduan.\p"
	.string "Pixka bat urduritzen nau, baina.\n"
	.string "Ez al litzateke apartegia izango?\p"
	.string "Eskerrik asko, {PLAYER}{KUN}.\n"
	.string "Berriz aurkitzen bazaitut, ziur nago\l"
	.string "lagungarria izango zarela.$"

gText_ApprenticeThanksHeldItem14::
	.string "Beno… Ados!\n"
	.string "{STR_VAR_1} emango diot orduan.\p"
	.string "Pixka bat urduritzen nau, baina.\n"
	.string "Ez al litzateke apartegia izango?\p"
	.string "Eskerrik asko, {PLAYER}{KUN}.\n"
	.string "Berriz aurkitzen bazaitut, ziur nago\l"
	.string "lagungarria izango zarela.$"

gText_ApprenticeItemAlreadyRecommended14::
	.string "B-baina jada ezagutzen dut hori.\p"
	.string "mesedez, zerbait berria behar dut!\n"
	.string "Ezingo nuke umiliazio honekin.\p"
	.string "Edo oker ari ote naiz?\n"
	.string "Uste duzu {STR_VAR_2} hobe moldatuko\l"
	.string "litzatekeela itemik gabe?$"

gText_ApprenticeWhatHeldItem15::
	.string "Zer? {PLAYER}{KUN} zarela dirudi…\n"
	.string "Baina zu al zara benetan?\l"
	.string "Agian bere bikia zara?\p"
	.string "Ez, ez, ez, ez kezkatu!\n"
	.string "Benetan {PLAYER} bazara, barkatu\l"
	.string "nire atrebentzia, mesedez.\p"
	.string "Zure aholku bikainen bila\n"
	.string "nabil gaur ere.\p"
	.string "Nire {STR_VAR_1} dut hemen eta\n"
	.string "item egoki bat eman nahi nioke.\p"
	.string "Zein litzateke egokiena?$"

gText_ApprenticeHoldNothing15::
	.string "Hobe dela ezer ez ematea?\n"
	.string "Ziur al zaude?$"

gText_ApprenticeThanksNoHeldItem15::
	.string "Ados. Zuk hala badiozu, hala izango da.\n"
	.string "Eskerrik asko zure denboragatik.\p"
	.string "Hurrengora arte!$"

gText_ApprenticeThanksHeldItem15::
	.string "{STR_VAR_1}, beraz?\n"
	.string "Ziur al zaude?\p"
	.string "Ados. Zuk hala badiozu, hala izango da.\n"
	.string "Eskerrik asko zure denboragatik.\p"
	.string "Espero dut nire POKéMONAK gai\n"
	.string "izango direla ondo erabiltzeko.\p"
	.string "Hurrengora arte!$"

gText_ApprenticeItemAlreadyRecommended15::
	.string "Ez, ez, itxaron pixka bat.\n"
	.string "Esango nuke hori jada gomendatu didazula.\p"
	.string "Gaur zerbait desberdina gomendatzea\n"
	.string "gustatuko litzaidake.\p"
	.string "Agian esan nahi duzu ez lukeela\n"
	.string "ezer eduki behar {STR_VAR_2}(e)k?\l"
	.string "Ziur al zaude?$"

gText_ApprenticeWhichMonFirst0::
	.string "Buaa, {PLAYER}!\n"
	.string "Dilema bat dut, zintz…\p"
	.string "Beste batzuen aurka borrokan hasi\n"
	.string "nahi dut, baina ez dakit zer egin.\p"
	.string "Nola atera behar nituzke POKéMONAK\n"
	.string "ahalik eta talde indartsuena izateko?\p"
	.string "Esan mesedez, {PLAYER}.\n"
	.string "Nire lekuan, POKéMON hauetatik zein\l"
	.string "aterako zenuke lehenengo?$"

gText_ApprenticeMonFirstThanks0::
	.string "Nire {STR_VAR_1} atera behar nuke?\n"
	.string "Buaaaaa!\p"
	.string "Ai! Barkatu!\n"
	.string "Horren pozik jarri naiz zure\l"
	.string "aholkuagatik, negarrez hasi naizela…\p"
	.string "Eskerrik asko, benetan!$"

gText_ApprenticeWhichMonFirst1::
	.string "Bai! {PLAYER} zara!\n"
	.string "Bikain! galdera bat dut zuretzat!\p"
	.string "Em, nire POKéMONEN artean,\n"
	.string "zein aterako zenuke lehenengo?$"

gText_ApprenticeMonFirstThanks1::
	.string "{STR_VAR_1}? Egia, hala behar du.\n"
	.string "Ados, hori egingo dut!\p"
	.string "Eskerrik asko irakasteagatik!$"

gText_ApprenticeWhichMonFirst2::
	.string "{PLAYER}, kaixo!\p"
	.string "Nire ustez, borroka batean oso garrantzitsua\n"
	.string "da zein POKéMON atera lehenengo.\p"
	.string "Nire POKéMONEN artean,\n"
	.string "zein atera behar nuke lehenengo?$"

gText_ApprenticeMonFirstThanks2::
	.string "Nire {STR_VAR_1} aterako zenuke?\n"
	.string "Ados, ulertuta!\p"
	.string "Hurrengora arte!$"

gText_ApprenticeWhichMonFirst3::
	.string "Kaixo, {PLAYER}…\n"
	.string "Beste galdera bat egin behar dizut,\l"
	.string "barkatu eragozpenak.\p"
	.string "Horren konfidantza gutx dut nire buruan,\n"
	.string "zu gabe galdua nintzateke, {PLAYER}.\p"
	.string "Agian denbora galtze bat soilik\n"
	.string "izango da, baina ez dakit zein erabaki\l"
	.string "hartu oraindik…\p"
	.string "Zein POKéMON atera behar nuke lehenengo\n"
	.string "borroka batean?$"

gText_ApprenticeMonFirstThanks3::
	.string "Nire {STR_VAR_1}?\n"
	.string "Ulertuta!\p"
	.string "Ezin dut sinetsi horrenbestetan nire\n"
	.string "galderak erantzuteko prest egotea!\p"
	.string "Bihotzez eskertzen dizut nirekin hitz\n"
	.string "egiteko denbora hartzea… Mila esker!$"

gText_ApprenticeWhichMonFirst4::
	.string "Ei, {PLAYER}{KUN}! Ni naiz!\n"
	.string "Eskerrak aurkitu zaitudan, arazo\l"
	.string "txiki bat dut eta.\p"
	.string "Ez dakit zein ordenatan jarri nire\n"
	.string "POKéMONAK. Lagunduko zenidake?\p"
	.string "Ez duzu talde osoa aukeratu behar\n"
	.string "oraintxe bertan.\p"
	.string "Zer iruditzen zaizu lehenengo\n"
	.string "POKéMONA aukeratzen badidazu?$"

gText_ApprenticeMonFirstThanks4::
	.string "Nire {STR_VAR_1}? Bikain!\p"
	.string "Erabakia zuk hartu duzunez,\n"
	.string "{PLAYER}{KUN}, ez naiz haserretuko\l"
	.string "galtzen badut ere.\p"
	.string "Ongi. Etorriko naiz laguntza eske berriz.\n"
	.string "Aio!$"

gText_ApprenticeWhichMonFirst5::
	.string "Kaixo, {PLAYER}{KUN} irakaslea!\n"
	.string "Gaur ere lanpetuta nabil!\p"
	.string "Bizikletan ibili behar naiz eta erosketak\n"
	.string "egin eta beste mila gauza.\p"
	.string "Ez daukat denborarik nire POKéMONEN\n"
	.string "taldearen ordena aukeratzeko ere.\p"
	.string "Zer iruditzen zaizu nire taldea?\n"
	.string "Zein jarri behar nuke lehenengo?$"

gText_ApprenticeMonFirstThanks5::
	.string "Ados, ulertuta.\n"
	.string "Badut denbora behintzat {STR_VAR_1}\l"
	.string "taldearen buru jartzeko!\p"
	.string "Uuuups, neskalaguna zain dut!\n"
	.string "Mila esker! Ikusi arte!$"

gText_ApprenticeWhichMonFirst6::
	.string "Iujuuu! Aupa, {PLAYER}!\n"
	.string "Beti indartsu itxura duzu ibiltzean!\p"
	.string "Entzun, zerbait galdetu behar dizut\n"
	.string "berriro! Betiko antzean!\p"
	.string "Erredoblea, mesedez!\n"
	.string "Nire taldearen inguruko galdera da.\p"
	.string "Zein POKéMON jarri behar nuke\n"
	.string "lehenengo borroka baterako?$"

gText_ApprenticeMonFirstThanks6::
	.string "Ados!\n"
	.string "Nire {STR_VAR_1}, diozu!\l"
	.string "Hori bai erantzun bikaina!\p"
	.string "Hori da gaurkoz galdetu nahi\n"
	.string "nizun guztia.\p"
	.string "Hemen elkartuko gara berriz, bai?\n"
	.string "Eskerrik asko!$"

gText_ApprenticeWhichMonFirst7::
	.string "Eskerrik asko nirekin hizketan\n"
	.string "geratzeagatik, {PLAYER}.\p"
	.string "Badakit zure apaltasuna aprobetxatzen\n"
	.string "ari naizela, baina aholkua eska dakizuket?\p"
	.string "Nire POKéMON taldearen ordena aukeratzeko\n"
	.string "eskatu nahi nizuke.\p"
	.string "Asko eskertuko nizuke lehenengo zein\n"
	.string "POKéMON atera esango bazenit.$"

gText_ApprenticeMonFirstThanks7::
	.string "Nire {STR_VAR_1} orduan!\n"
	.string "Oraintxe bertan jarriko dut!\p"
	.string "Eskerrik asko, {PLAYER}.\n"
	.string "Berriz lagunduko didazula espero dut.\l"
	.string "Zaindu zaitez!$"

gText_ApprenticeWhichMonFirst8::
	.string "Ei! {PLAYER}!\n"
	.string "A zer nolako poza zu berriz ikusita!\p"
	.string "Nire POKéMONAK pila bat indartu\n"
	.string "dira azkenekotik!\p"
	.string "Baina ez dut beti irabazten. Badirudi axola\n"
	.string "duela hasieran ateratzen dudan POKéMONAK.\p"
	.string "{PLAYER}, mesedez, zure laguntza behar dut!\p"
	.string "Aukeratu zein POKéMON atera behar\n"
	.string "nukeen lehenengo!$"

gText_ApprenticeMonFirstThanks8::
	.string "Ai… Zoriontasunez beteta nago…\p"
	.string "Amets bat bezalakoa da nire POKéMONEN\n"
	.string "ordena zuk aukeratzea, {PLAYER}.\p"
	.string "Ulertu dut, hala ere!\n"
	.string "Nire {STR_VAR_1} jarriko dut lehenengo!\p"
	.string "Espero dut hurrengo batean are gehiago\n"
	.string "erakutsiko didazula.$"

gText_ApprenticeWhichMonFirst9::
	.string "Kaixo, kaixo!\n"
	.string "Nire irakaslea, {PLAYER}{KUN}!\l"
	.string "Bota zure betiko aholku bikainetako bat!\p"
	.string "Beno, hiru POKéMONEKO talde bat osatu\n"
	.string "dut. Horra arte, dena ondo.\p"
	.string "Baina borrokarako ordena oraindik ez\n"
	.string "dut erabaki.\p"
	.string "Hemen lagunduko didazu, {PLAYER}{KUN}!\n"
	.string "Aukeratu zein POKéMON aterako den lehenengo!\p"
	.string "Ez izan lotsarik.\n"
	.string "Bota beldurrik gabe!$"

gText_ApprenticeMonFirstThanks9::
	.string "Ados, nire {STR_VAR_1} hasieran, beraz!\n"
	.string "Bai, bai!\l"
	.string "Ordena aldatuko dut ziztu batean!\p"
	.string "Ongi, mila esker, beti bezala!\n"
	.string "Agur!$"

gText_ApprenticeWhichMonFirst10::
	.string "{PLAYER}{KUN}, entzun!\n"
	.string "A zer nolako krisia!\p"
	.string "Nire POKéMONAK, hirurak, batera\n"
	.string "ateratzen dira borrokara!\p"
	.string "Noski ezinezkoa dela!\n"
	.string "Kar-kar!\p"
	.string "Hau ez da gezurra, ordea.\n"
	.string "Ez naiz oso ona nire POKéMONEN\l"
	.string "ordena aukeratzeko garaian.\p"
	.string "Eta nire partez aukeratzen baduzu\n"
	.string "zein POKéMON atera lehenengo, irakasle?$"

gText_ApprenticeMonFirstThanks10::
	.string "Ongi, nire {STR_VAR_1} aukeratu duzu?\n"
	.string "Hori ez, beste edozein aterako dut!\p"
	.string "Txantxa da!\n"
	.string "Kasu egingo dizut, irakasle!\p"
	.string "Eskerrik asko, irakasle!\n"
	.string "Gehiago irakatsiko didazula espero dut!$"

gText_ApprenticeWhichMonFirst11::
	.string "I-E-P-A T-X-O!\n"
	.string "Horrek iepa txo osatzen du!\p"
	.string "MARINEL raperoa naiz ni!\n"
	.string "Eta zuretzat galdera bat\l"
	.string "daukat beti!\p"
	.string "Nire taldearen ordena da kontua\n"
	.string "eman iezadazu zure aholkua!\p"
	.string "Talde honetan zein atera behar nuke\n"
	.string "hauek borroka irabaziko badute?$"

gText_ApprenticeMonFirstThanks11::
	.string "Ondo, ulertuta!\n"
	.string "Aldatuko dut ordena, guztiak nahastuta!\p"
	.string "Zure laguntza behar badut,\n"
	.string "{PLAYER}, dudarik gabe galdetuko dizut!$"

gText_ApprenticeWhichMonFirst12::
	.string "Iujuuu, {PLAYER}!\n"
	.string "Zer moduz zabiltza?\p"
	.string "Zer egin behar nuke? Ausartu eta galdetu?\n"
	.string "Bada, bai, galdera bat dut, tentu!\l"
	.string "Entzuten al didazu?\l"
	.string "Entzuten didazu!\p"
	.string "Aukeratu behar duzu, nik zein\n"
	.string "POKéMON atera lehenengo, aizu!\l"
	.string "Borroka batean, esan nahi dut.$"

gText_ApprenticeMonFirstThanks12::
	.string "Nire {STR_VAR_1}? bai!\n"
	.string "Horrela bai nagoela lasai!\p"
	.string "Beno, {PLAYER}, banoa mundu zabalera,\n"
	.string "ez nazazu ahaztu, itzuliko naiz, atzera.\p"
	.string "Hurrengora arte, nire lagun azkarra!$"

gText_ApprenticeWhichMonFirst13::
	.string "…Uf…Autx… {PLAYER}{KUN}…\n"
	.string "Kristoren urdaileko mina dut…\p"
	.string "…Orain pixka bat hobeto nago…\p"
	.string "Uste dut urduri jarri naizela nire\n"
	.string "POKéMON taldearen ordena aukeratzen\l"
	.string "ari naizelako, kostatzen ari zait eta.\p"
	.string "Kontuak horrela, zuk nire ordez\n"
	.string "erabakia hartzea eskertuko nizuke.\p"
	.string "{PLAYER}{KUN}, zein POKéMON jarri behar\n"
	.string "dut lehenengo? Irabazi dezadan, noski.$"

gText_ApprenticeMonFirstThanks13::
	.string "Ados, ongi.\n"
	.string "Nire {STR_VAR_1} lehenengo, orduan.\p"
	.string "Afalostean aldatuko dut ordena\n"
	.string "zure aholkua jarraitzeko.\p"
	.string "Espero dut gehiagotan lagunduko\n"
	.string "didazula.$"

gText_ApprenticeWhichMonFirst14::
	.string "Em… Bueno…\n"
	.string "{PLAYER}{KUN}?\p"
	.string "Mesedez, ez begiratu horrela.\n"
	.string "Lotsagorritzen ari naiz eta.\p"
	.string "Bada…\n"
	.string "Zure aholkua behar dut.\p"
	.string "Lotsa ematen dit esateak, baina\n"
	.string "3 POKéMONEKO talde bat egin dut.\l"
	.string "Ezin dut ordena aukeratu, ordea.\p"
	.string "Zein POKéMON atera behar nuke lehenengo\n"
	.string "gutxienez itxura emateko?$"

gText_ApprenticeMonFirstThanks14::
	.string "Bale… Ados!\n"
	.string "Lehenengo {STR_VAR_1} aterako dut.\p"
	.string "Espero dut itxura emango dudala\n"
	.string "gehiegi lotsatu gabe.\p"
	.string "Eskerrik asko, {PLAYER}{KUN}.\n"
	.string "Berriz elkar ikusten badugu, badakit\l"
	.string "beti bezain lagungarria izango zarela.$"

gText_ApprenticeWhichMonFirst15::
	.string "Zer? badirudi {PLAYER}{KUN} zarela…\n"
	.string "Baina ba al zara benetan?\l"
	.string "Agian bere antza handia duzu eta kito?\p"
	.string "Ez, ez, ez kezkatu!\n"
	.string "Benetan {PLAYER} bazara, mesedez\l"
	.string "barkatu nire atrebentzia.\p"
	.string "Zure aholku bikainen bila etorri naiz.\p"
	.string "Hementxe daukat nire POKéMON taldea.\n"
	.string "Lehenengo zein POKéMON jarri esatea\l"
	.string "nahiko nuke.$"

gText_ApprenticeMonFirstThanks15::
	.string "Nire {STR_VAR_1}…\n"
	.string "Ez zara txantxetan ari, ezta?\p"
	.string "Ongi. Hala bada, hala bedi.\n"
	.string "Eskerrik asko zure denboragatik.\p"
	.string "Ikusten duzu nolakoa naizen, baina\n"
	.string "gogor saiatuko naiz hala ere.\p"
	.string "Hurrengora arte!$"

gText_ApprenticeWhichMon0::
	.string "Zintz…\n"
	.string "Ene, {PLAYER}!\p"
	.string "A zer nolako kasualitatea!\n"
	.string "hartu ezin dudan erabaki bat daukat…\p"
	.string "Ez dakit zein POKéMON erabili behar\n"
	.string "nukeen.\p"
	.string "Aukeran ditudan POKéMONAK {STR_VAR_1}\n"
	.string "eta {STR_VAR_2} dira…\p"
	.string "{PLAYER}, zure ustez zein da irabazteko\n"
	.string "aukera gehien emango didana?$"

gText_ApprenticeMonThanks0::
	.string "Zintz… Uler… Ulertuta!\n"
	.string "Ene! Barkatu!\l"
	.string "Horren pozik jarrita, negarrez hasi naiz…\p"
	.string "Asko saiatuko naiz ea {STR_VAR_1}\n"
	.string "bat harrapatzen dudan!\p"
	.string "Eskerrik asko, benetan!$"

gText_ApprenticeWhichMon1::
	.string "Bai! {PLAYER} da eta!\n"
	.string "Bai, momentu egokienean etorri zara, gainera!\l"
	.string "Zure aholkua behar dut berriro!\p"
	.string "Ene, Ez dakit zer egin. Nire {STR_VAR_1}\n"
	.string "edo {STR_VAR_2} erabili beharko nuke…\p"
	.string "Zein hazi behar nuke zure ustez,\n"
	.string "{PLAYER}?$"

gText_ApprenticeMonThanks1::
	.string "Ah, nire {STR_VAR_1} hobeto, orduan!\n"
	.string "Ongi, horixe egingo dut!\p"
	.string "Eskerrik asko irakasteagatik!$"

gText_ApprenticeWhichMon2::
	.string "{PLAYER}, kaixo!\n"
	.string "Galdera bat egin nahi dizut.\p"
	.string "Dilema bat daukat, ez dakit {STR_VAR_1}\n"
	.string "bat edo {STR_VAR_2} bat hazi.\p"
	.string "Zein POKéMON izango da indartsuagoa\n"
	.string "zure ustez?$"

gText_ApprenticeMonThanks2::
	.string "{STR_VAR_1} aukeratu duzu?\n"
	.string "Ongi, ulertuta!\p"
	.string "{STR_VAR_1} indartsu bat harrapatzera\n"
	.string "noa orduan!\p"
	.string "Ikusi arte!$"

gText_ApprenticeWhichMon3::
	.string "Kaixo, {PLAYER}…\p"
	.string "Ziur nago jada ahaztu duzula ni\n"
	.string "bezalako pertsona bat…\p"
	.string "…Baina horrek ez du inporta, behintzat\n"
	.string "lagunduko bazenit…\p"
	.string "Ezin dut aukeratu zein POKéMON\n"
	.string "mota hazi…\p"
	.string "Bi POKéMON ditut aukeran orain,\n"
	.string "{STR_VAR_1} eta {STR_VAR_2}, baina\l"
	.string "trabatuta geratu naiz…\p"
	.string "{PLAYER}, ez zaitut gehiegi gogaitu\n"
	.string "nahi, baina aukeratu bat mesedez.$"

gText_ApprenticeMonThanks3::
	.string "Baina kasu egingo ote dit {STR_VAR_1}\n"
	.string "basati batek niri?\p"
	.string "Saiatuko naiz!\p"
	.string "Gai izango ote naiz bat harrapatzeko…\n"
	.string "Ez! Saiatu egingo naiz!\p"
	.string "Eskerrik asko!$"

gText_ApprenticeWhichMon4::
	.string "Ei, {PLAYER}{KUN}! Pozten naiz zu ikusita!\n"
	.string "Zure bila joatekoa nintzen!\p"
	.string "Aukeratu dezakezu zein POKéMON\n"
	.string "mota erabili behar nukeen?\p"
	.string "Adibidez…\n"
	.string "Zer iruditzen {STR_VAR_1}\l"
	.string "eta {STR_VAR_2}?\p"
	.string "Zein izango litzateke hobea\n"
	.string "niretzat?$"

gText_ApprenticeMonThanks4::
	.string "{STR_VAR_1}? Bikain!\p"
	.string "Zuk hartu duzunez erabakia,\n"
	.string "{PLAYER}{KUN}, ez naiz haserretuko\l"
	.string "galtzen badut ere.\p"
	.string "Ados, Etorriko naiz laguntza eske berriro.\n"
	.string "Aio!$"

gText_ApprenticeWhichMon5::
	.string "{PLAYER}{KUN} da eta! Zer moduz zabiltza?\n"
	.string "Ni lanpetuta, betiko legez!\p"
	.string "Ondo aritu nahi dut POKéMONEKIN ere,\n"
	.string "baina ezin dut aukeratu zein den\l"
	.string "erabili behar nukeen POKéMONA.\p"
	.string "Badakizu {STR_VAR_1} indartsa dela, bai?\n"
	.string "Baina {STR_VAR_2} ere oso gogorra da.\p"
	.string "{PLAYER}{KUN}, eman zure aholku horietako\n"
	.string "bat! Zein aukeratu behar nuke?$"

gText_ApprenticeMonThanks5::
	.string "Ongi, ulertuta.\n"
	.string "Norbaiti eskatuko diot {STR_VAR_1}\l"
	.string "bat harrapatzeko niretzat.\p"
	.string "Eskerrik asko nire irakaslea izateagatik.\n"
	.string "Eskerrik asko! Ikusi arte!$"

gText_ApprenticeWhichMon6::
	.string "Ene!\n"
	.string "Bai! {PLAYER} da eta!\p"
	.string "Ziztuan kontatu nien nire lagunei\n"
	.string "zu ezagutu zintudala!\p"
	.string "Zure laguntza eske nator gaur ere.\n"
	.string "galdera erraza izango da zuretzat!\p"
	.string "Erredoblea, mesedez!\n"
	.string "Nire galdera da…\p"
	.string "POKéMON bat hazi nahi badut,\n"
	.string "eta aukerak {STR_VAR_1} eta\l"
	.string "{STR_VAR_2} badira, zein da egokiena?$"

gText_ApprenticeMonThanks6::
	.string "Ahhh!\n"
	.string "{STR_VAR_1}, beraz!\l"
	.string "Hori bai erantzun bikaina!\p"
	.string "Uste dut hori zela galdetu\n"
	.string "nahi nizun guztia.\p"
	.string "Hurrengoan hemen elkartuko gara\n"
	.string "berriz, ados? Esker mila!$"

gText_ApprenticeWhichMon7::
	.string "Ene, zu al zara, {PLAYER}?\n"
	.string "Pozten naiz zu berriro ikusita!\p"
	.string "Zure ikasle bihurtu nintzenetik,\n"
	.string "nire konfidantzak gora egin du.\p"
	.string "uste dut prest nagoela nire POKéMONA\n"
	.string "hazteko!\p"
	.string "{PLAYER}, galdetu diezazuket zein\n"
	.string "POKéMON hazi behar nukeen?\p"
	.string "Aukerak {STR_VAR_1} eta\n"
	.string "{STR_VAR_2} dira…\l"
	.string "Zein POKéMON da egokia niretzat?$"

gText_ApprenticeMonThanks7::
	.string "{STR_VAR_1}, orduan!\n"
	.string "Oraintxe joango naiz baten bila!\p"
	.string "Eskerrik asko, {PLAYER}.\n"
	.string "Berriz lagunduko didazula espero dut.\l"
	.string "Zaindu zaitez!$"

gText_ApprenticeWhichMon8::
	.string "Ei! {PLAYER}! Berriz aurkitu zaitut!\n"
	.string "Zein… Zein pozik nagoen!\p"
	.string "Oh-oh-oh, badakit!\n"
	.string "Ez dut aukera hau galduko!\p"
	.string "Eskatu diezazuket mesede bat, {PLAYER}?\n"
	.string "Mesedez aukeratu POKéMON bat nire partez!\p"
	.string "Aukeratu zein litzatekeen onena,\n"
	.string "{STR_VAR_1} edo {STR_VAR_2}!$"

gText_ApprenticeMonThanks8::
	.string "Uau! Nire partez aukeratu duzu!\n"
	.string "{STR_VAR_1} bat haziko dut orduan,\l"
	.string "ahal dudan ondoen.\p"
	.string "Espero dut hurrengo batean are gehiago\n"
	.string "erakutsiko didazula.$"

gText_ApprenticeWhichMon9::
	.string "Ei, ei!\n"
	.string "Nire irakaslea, {PLAYER}{KUN}!\p"
	.string "Kaixo, zure bila aritu naiz,\n"
	.string "jakintsu aholku gehiagoren eske!\p"
	.string "Zein POKéMON mota litzateke egokia\n"
	.string "niretzako, {STR_VAR_1} edo {STR_VAR_2}?\p"
	.string "Ez izan lotsarik.\n"
	.string "Bota beldurrik gabe!$"

gText_ApprenticeMonThanks9::
	.string "Ados, {STR_VAR_1} bat, beraz!\n"
	.string "Bai, bai!\l"
	.string "Ziztuan sartuko dut bat BALL batean!\p"
	.string "Ongi, mila esker, beti bezala!\n"
	.string "Agur!$"

gText_ApprenticeWhichMon10::
	.string "{PLAYER}{KUN}, entzun! Berri onak!\n"
	.string "Mirari POKéMON bat harrapatu dut!\p"
	.string "Noski gezurretan nabilela!\n"
	.string "Kar-kar!\p"
	.string "Hau ez da gezurra, ordea.\n"
	.string "Ez naiz bereziki ona POKéMONAK\l"
	.string "harrapatzen.\p"
	.string "Zer iruditzen zaizu nire partez\n"
	.string "aukeratzen baduzu zein POKéMON mota\l"
	.string "harrapatu behar nukeen, irakasle?\p"
	.string "Zein litzateke hobea?\n"
	.string "{STR_VAR_1} edo {STR_VAR_2}?$"

gText_ApprenticeMonThanks10::
	.string "Ongi, {STR_VAR_1} aukeratu duzu, beraz?\n"
	.string "Bestea harrapatuko dut orduan!\p"
	.string "Txantxa da!\n"
	.string "Kasu egingo dizut, irakasle!\p"
	.string "Eskerrik asko, irakasle!\n"
	.string "Gehiago irakatsiko didazula espero dut!$"

gText_ApprenticeWhichMon11::
	.string "I-E-P-A T-X-O!\n"
	.string "Horrek iepa txo osatzen du!\p"
	.string "MARINEL raperoa naiz ni!\n"
	.string "Gogoratzen al zara nor naizen?\p"
	.string "Gaur, POKéMON galdera bat dut\n"
	.string "eta zuri galdetu nahi dizut!\p"
	.string "Bi hauen artean aukeratu behar dut:\n"
	.string "{STR_VAR_1} eta {STR_VAR_2}, adi.\l"
	.string "Zein egokitzen zait hobe niri?$"

gText_ApprenticeMonThanks11::
	.string "{STR_VAR_1}, beraz, ei, ei!\n"
	.string "Bat harrapatuko dut, adi egonez denei!\p"
	.string "Zure laguntza behar badut,\n"
	.string "{PLAYER}, dudarik gabe galdetuko dizut!$"

gText_ApprenticeWhichMon12::
	.string "Ene, uau, {PLAYER} da eta!\p"
	.string "Zer egin behar nuke? Aholkua eskatu?\n"
	.string "Zergatik ez? Jada ari naiz zurekin hizketan!\p"
	.string "Denbora asko pasa da. Utzi nire beharra\n"
	.string "azaltzen. Aholku ari naiz bilatzen!\l"
	.string "Entzuten al didazu?\l"
	.string "Entzuten didazu!\p"
	.string "Nire POKéMONETATIK zein erabili behar nuke?\n"
	.string "{STR_VAR_1} edo {STR_VAR_2} daude aukeran.\l"
	.string "Zein aukeratuko zenuke?$"

gText_ApprenticeMonThanks12::
	.string "{STR_VAR_1} bada bietan onena,\n"
	.string "hori hartuko dut aurrena!\p"
	.string "Beno, {PLAYER}, banoa mundu zabalera,\n"
	.string "ez nazazu ahaztu, itzuliko naiz, atzera.\p"
	.string "Hurrengora arte, nire lagun azkarra!$"

gText_ApprenticeWhichMon13::
	.string "Ene, aupa, {PLAYER}{KUN}…\n"
	.string "Kristoren buruko mina dut…\p"
	.string "Gehiegi kezkatu naiz zein POKéMON\n"
	.string "mota hazi erabakitzen.\p"
	.string "Kontuak kontu, nire partez\n"
	.string "aukeratzea behar nuke.\p"
	.string "{PLAYER}{KUN}, aukeran banitu\n"
	.string "{STR_VAR_1} eta {STR_VAR_2}\l"
	.string "POKéMONAK, zein aukeratu behar nuke?$"

gText_ApprenticeMonThanks13::
	.string "Orduan {STR_VAR_1}, ados.\n"
	.string "Bat bilatuko dut sendatzen naizenean.\p"
	.string "Espero dut gehiagotan lagunduko\n"
	.string "didazula.$"

gText_ApprenticeWhichMon14::
	.string "Em… Beno…\n"
	.string "{PLAYER}{KUN}…?\p"
	.string "Mesedez, ez begiratu horrela.\n"
	.string "Lotsagorritzen ari naiz…\l"
	.string "Nik… Zure aholkua behar dut.\p"
	.string "Nik… Lotsa ematen dit, baina ez\n"
	.string "dakit zein POKéMON aukeratu.\p"
	.string "Aukerak {STR_VAR_1} edo {STR_VAR_2}\n"
	.string "balira, zein litzateke onena?$"

gText_ApprenticeMonThanks14::
	.string "Bai… Ongi!\n"
	.string "{STR_VAR_1} bat lortzen saiatuko naiz.\p"
	.string "Lotsatu gabe ahalik eta gehien\n"
	.string "saiatuko naiz.\p"
	.string "Eskerrik asko, {PLAYER}{KUN}.\n"
	.string "Berriz elkar ikusten badugu, badakit\l"
	.string "beti bezain lagungarria izango zarela.$"

gText_ApprenticeWhichMon15::
	.string "Zer? badirudi {PLAYER}{KUN} zarela…\n"
	.string "Baina benetakoa ote zara?\p"
	.string "Ez, ez, benetakoa bazara, orduan ongi.\n"
	.string "Egia esan, zure ahoku eske\l"
	.string "nator gaur.\p"
	.string "Erabiliko ditudan POKéMONEN gainean da.\p"
	.string "Aukeren artean {STR_VAR_1}\n"
	.string "eta {STR_VAR_2} POKéMONAK egonda,\l"
	.string "zein da niretzako onena?$"

gText_ApprenticeMonThanks15::
	.string "{STR_VAR_1}?\n"
	.string "Ziur al zaude?\p"
	.string "Ados. Hala bada, ongi.\n"
	.string "Eskerrik asko zure denboragatik.\p"
	.string "Espero dut niri ere balioko didala\n"
	.string "zure aholkuak.\p"
	.string "Hurrengora arte!$"

gText_ApprenticeWhichMove0::
	.string "Buaaa! Ene, {PLAYER}!\n"
	.string "Zintz… Zintz…\p"
	.string "Dilema izugarria dut!\n"
	.string "Ez dakit zein eraso aukeratu\l"
	.string "nire {STR_VAR_1}(r)entzat…\p"
	.string "Mesedez, mesedez, {PLAYER}.\n"
	.string "Aukeratuko nire partez?\p"
	.string "Nire {STR_VAR_1}(r)entzat, zein\n"
	.string "eraso litzateke egokiena: {STR_VAR_2}\l"
	.string "edo {STR_VAR_3}?$"

gText_ApprenticeMoveThanks0::
	.string "{STR_VAR_1}?\n"
	.string "Buaaaa!\p"
	.string "Ene! Barkatu, {PLAYER}!\n"
	.string "Horren pozik jarri naiz zuk erasoa\l"
	.string "aukeratuta, negarrez hasi naizelaº…\p"
	.string "Zintz…\n"
	.string "Eskerrik asko, benetan!$"

gText_ApprenticeWhichMove1::
	.string "Bai! Epa, {PLAYER}!\n"
	.string "Zure aholkua behar dut berriro!\p"
	.string "Nire {STR_VAR_1}(e)ri berebiziko\n"
	.string "eraso bat erakutsi nahi diot.\p"
	.string "Atsegin ditudan bi erasoak\n"
	.string "{STR_VAR_2} eta {STR_VAR_3} dira.\l"
	.string "Bietatik zein gomendatzen didazu?$"

gText_ApprenticeMoveThanks1::
	.string "{STR_VAR_1} da hobea? Ados, beraz!\n"
	.string "Ongi, horixe aukeratuko dut!\p"
	.string "Berriz elkar ikusten badugu, gehiago\n"
	.string "erakutsi, mesedez, irakasle!$"

gText_ApprenticeWhichMove2::
	.string "{PLAYER}, kaixo!\n"
	.string "Nire {STR_VAR_1}(r)en inguruan da,\l"
	.string "kezkatuta nagi haren erasoekin.\p"
	.string "Begira, {STR_VAR_2} eta {STR_VAR_3}\n"
	.string "erasoak ditut aukeran.\p"
	.string "Zein da indartsuagoa eta hobea\n"
	.string "nire {STR_VAR_1}(r)entzat?$"

gText_ApprenticeMoveThanks2::
	.string "{STR_VAR_1} aukeratu duzu?\n"
	.string "Ongi, ulertuta!\p"
	.string "{STR_VAR_1} irakastera noa\n"
	.string "nire POKéMONARI berehala!\p"
	.string "Ikusi arte!$"

gText_ApprenticeWhichMove3::
	.string "Eneee, {PLAYER}…\n"
	.string "Etsita nago, benetan!\p"
	.string "POKéMON bat ahztea erabaki dut,\n"
	.string "baina orain ez nago ziur zein\l"
	.string "eraso irakatsi behar niokeen…\p"
	.string "Badakit zuretzat ez dela ezer\n"
	.string "garrantzitsua, {PLAYER}.\p"
	.string "Baina niretzat bai…\p"
	.string "Mesedez, {PLAYER}, aukeratuko zenuke\n"
	.string "eraso bat nire {STR_VAR_1}(r)entzat?\p"
	.string "Bi aukerak honakoak dira:\n"
	.string "{STR_VAR_2} eta {STR_VAR_3}…$"

gText_ApprenticeMoveThanks3::
	.string "Ulertuta!\p"
	.string "Baina nahiko ote du niregatik\n"
	.string "{STR_VAR_1} ikasi…\l"
	.string "Ez! Saiatu egingo naiz!\p"
	.string "Eskerrik asko!$"

gText_ApprenticeWhichMove4::
	.string "Ene, {PLAYER}{KUN}!\n"
	.string "Zure bila ari nintzen, justu!\p"
	.string "Pentsatzen aritu naiz, ea nire\n"
	.string "{STR_VAR_1}(r)entzat zein den eraso egokia.\p"
	.string "Ezin dut aukeratu, aukeratuko zenuke\n"
	.string "nire partez?\p"
	.string "Adibidez… Zer iruditzen zaizkizu\n"
	.string "{STR_VAR_2} eta {STR_VAR_3}?\l"
	.string "Zein litzateke hobea?$"

gText_ApprenticeMoveThanks4::
	.string "{STR_VAR_1}? Bikain!\p"
	.string "Zuk hartu duzunez erabakia,\n"
	.string "{PLAYER}{KUN}, ez naiz haserretuko\l"
	.string "galtzen badut ere.\p"
	.string "Ados, Etorriko naiz laguntza eske berriro.\n"
	.string "Aio!$"

gText_ApprenticeWhichMove5::
	.string "Nolatan nago horren lanpetuta?\n"
	.string "Ei, {PLAYER}{KUN} da eta!\l"
	.string "Zer moduz zabiltza?\p"
	.string "Esnatu naizenetik, korrika, igerian\n"
	.string "eta kozinatu egin dut!\p"
	.string "Ez dakizu zeinen lanpetuta nabilen!\p"
	.string "Ez dakit zein eraso aukeratu ere\n"
	.string "nire {STR_VAR_1}(e)k ikas dezan!\p"
	.string "{STR_VAR_2} ona da, baietz?\n"
	.string "Baina {STR_VAR_3} ere bai.\p"
	.string "{PLAYER}{KUN}, eman iezadazu zure aholku\n"
	.string "horietako bat! Zein da egokiena?$"

gText_ApprenticeMoveThanks5::
	.string "Ongi, ulertuta.\n"
	.string "Aterako dut denbora eta eraso\l"
	.string "hori irakatsiko diot.\p"
	.string "Eskerrik asko nire irakaslea izateagatik.\n"
	.string "Eskerrik asko! Ikusi arte!$"

gText_ApprenticeWhichMove6::
	.string "Ene! Hau zortea!\n"
	.string "Berriz aurkitu zaitut, {PLAYER}!\l"
	.string "Zure laguntza eske nator gaur ere.\p"
	.string "Erredoblea, mesedez!\n"
	.string "Nire galdera da…\p"
	.string "Nire {STR_VAR_1}(r)entzat, zein eraso\n"
	.string "da egokiena, {STR_VAR_2} edo\l"
	.string "{STR_VAR_3}?$"

gText_ApprenticeMoveThanks6::
	.string "Ahhh!\n"
	.string "{STR_VAR_1}, beraz!\l"
	.string "Hori bai erantzun bikaina!\p"
	.string "Uste dut hori zela galdetu\n"
	.string "nahi nizun guztia.\p"
	.string "Hurrengoan hemen elkartuko gara\n"
	.string "berriz, ados? Esker mila!$"

gText_ApprenticeWhichMove7::
	.string "Ei, kaixo, {PLAYER}.\n"
	.string "Ondo zabiltzala espero dut.\p"
	.string "Zure aholku eske nator berriz.\n"
	.string "Nire {STR_VAR_1} maitearen inguruan da.\p"
	.string "Zein da nire {STR_VAR_1}\n"
	.string "maitagarriarentzako eraso egokiena?\l"
	.string "{STR_VAR_2} edo {STR_VAR_3}?$"

gText_ApprenticeMoveThanks7::
	.string "{STR_VAR_1}, beraz!\n"
	.string "Oraintxe bertan erakutsiko diot!\p"
	.string "Eskerrik asko, {PLAYER}.\n"
	.string "Berriz lagunduko didazula espero dut.\l"
	.string "Zaindu zaitez!$"

gText_ApprenticeWhichMove8::
	.string "Ei! {PLAYER}! Berriz aurkitu zaitut!\n"
	.string "Nolako… A zer nolako poza!\p"
	.string "Zeozer behar dudanean, beti agertzen\n"
	.string "zara une egokian, {PLAYER}!\p"
	.string "Gaur, earso bat gomendatzea\n"
	.string "beharko nuke!\p"
	.string "Mesedez, aukeratu eraso bat\n"
	.string "nire {STR_VAR_1}(r)entzat!\p"
	.string "Zein eraso da hobea,\n"
	.string "{STR_VAR_2} edo {STR_VAR_3}?$"

gText_ApprenticeMoveThanks8::
	.string "Bai-bai-bai! Mila esker!\n"
	.string "{STR_VAR_1}, orduan!\l"
	.string "Guztiz ulertuta!\p"
	.string "Espero dut hurrengo batean are gehiago\n"
	.string "erakutsiko didazula.$"

gText_ApprenticeWhichMove9::
	.string "Aupa, {PLAYER}{KUN}, zelan?\n"
	.string "Zure jakintsu aholkuaren\l"
	.string "bila nator gaur!\p"
	.string "Zein izango litzateke eraso onena\n"
	.string "nire {STR_VAR_1}(r)entzat?\p"
	.string "Irabazten lagunduko didan\n"
	.string "eraso bat izan behar da!\p"
	.string "{STR_VAR_2} aukeratu behar al nuke?\n"
	.string "Edo {STR_VAR_3}?$"

gText_ApprenticeMoveThanks9::
	.string "Bikain, {STR_VAR_1}, orduan!\n"
	.string "Bai, bikain!\l"
	.string "Ziztu bizian erakutsiko diot, ti-tau!\p"
	.string "Ongi, mila esker, beti bezala!\n"
	.string "Agur!$"

gText_ApprenticeWhichMove10::
	.string "{PLAYER}{KUN}, izugarria da hau!\p"
	.string "Nire POKéMONA!\n"
	.string "Sei eraso ikasi ditu!\p"
	.string "Noski gezurretan nabilela!\n"
	.string "Kar-kar!\p"
	.string "Hau ez da gezurra, ordea.\n"
	.string "Ez naiz oso ona nire POKéMONENTZAT\l"
	.string "erasoak aukeratzen.\p"
	.string "Zer iruditzen zaizu nire partez\n"
	.string "eraso abt aukeratzen baduzu?\p"
	.string "{STR_VAR_2} edo {STR_VAR_3}, zein\n"
	.string "litzateke onena {STR_VAR_1}(r)entzat?$"

gText_ApprenticeMoveThanks10::
	.string "Ongi, {STR_VAR_1} aukeratu duzu, beraz?\n"
	.string "Beste eraso bat aukeratuko dut, orduan!\p"
	.string "Txantxa da!\n"
	.string "Kasu egingo dizut, irakasle!\p"
	.string "Eskerrik asko, irakasle!\n"
	.string "Gehiago irakatsiko didazula espero dut!$"

gText_ApprenticeWhichMove11::
	.string "I-E-P-A T-X-O!\n"
	.string "Horrek iepa txo osatzen du!\p"
	.string "MARINEL raperoa naiz ni!\n"
	.string "Halaxe nabil beti, ez galdetu zergatik.\p"
	.string "Gaurkoan galdera itzela dut,\n"
	.string "zuri galdetu nahi dizut!\p"
	.string "{STR_VAR_2} eta {STR_VAR_3} daude\n"
	.string "aukeran. Zein litzateke onena\l"
	.string "{STR_VAR_1}(e)k ikasteko primeran?$"

gText_ApprenticeMoveThanks11::
	.string "{STR_VAR_1}, beraz, ei, ei! Hori\n"
	.string "irakatsi eta irabaziko diet besteei!\p"
	.string "Zure laguntza behar badut,\n"
	.string "{PLAYER}, dudarik gabe galdetuko dizut!$"

gText_ApprenticeWhichMove12::
	.string "Ei, bai, bai, {PLAYER} da eta!\p"
	.string "Zer egin behar nuke? Aholkua eskatu?\n"
	.string "Zergatik ez? Jada ari naiz zurekin hizketan!\p"
	.string "{PLAYER}, harrituta al zaude?\n"
	.string "Zure laguntza behar dut, dudatan gaude!\p"
	.string "Entzuten al didazu?\n"
	.string "Entzuten didazu!\p"
	.string "Nire {STR_VAR_1}(e)k, zer behar luke?\n"
	.string "{STR_VAR_2} edo {STR_VAR_3},\l"
	.string "zein aukeratuko zenuke?$"

gText_ApprenticeMoveThanks12::
	.string "{STR_VAR_1} bada onena,\n"
	.string "hori da aukeratuko nukeena!\p"
	.string "Beno, {PLAYER}, banoa mundu zabalera,\n"
	.string "ez nazazu ahaztu, itzuliko naiz, atzera.\p"
	.string "Hurrengora arte, nire lagun azkarra!$"

gText_ApprenticeWhichMove13::
	.string "Atxis! Ai! Ene, {PLAYER}{KUN}…\n"
	.string "Izugarrizko katarroa daukat…\p"
	.string "Eraso bat aukeratu nahi dut nire\n"
	.string "POKéMONARENTZAT, baina ezinean nabil…\p"
	.string "Kontuak kontu, nire partez\n"
	.string "aukeratzea behar dut.\p"
	.string "{PLAYER}{KUN}, bi hauen artean:\n"
	.string "{STR_VAR_2} eta {STR_VAR_3}, zein\l"
	.string "da onena nire {STR_VAR_1}(r)entzat?$"

gText_ApprenticeMoveThanks13::
	.string "Ados, {STR_VAR_1}, ulertuta. Tuju!\n"
	.string "Sendatzen naizenean erakutsiko diot.\p"
	.string "Espero dut gehiagotan lagunduko\n"
	.string "didazula.$"

gText_ApprenticeWhichMove14::
	.string "Em… Beno…\n"
	.string "{PLAYER}{KUN}…?\p"
	.string "Mesedez, ez begiratu horrela.\n"
	.string "Lotsagorritzen ari naiz…\l"
	.string "Nik… Zure aholkua behar dut.\p"
	.string "Nik… Lotsa ematen dit, baina ez dakit\n"
	.string "zein eraso erakutsi behar niokeen\l"
	.string "nire POKéMONARI.\p"
	.string "Nire {STR_VAR_1}(r)entzat da.\n"
	.string "Aukerak {STR_VAR_2} eta\l"
	.string "{STR_VAR_3} balira, zein litzateke onena?$"

gText_ApprenticeMoveThanks14::
	.string "Bai… Ongi!\n"
	.string "{STR_VAR_1} probatuko dut.\p"
	.string "Espero dut gai izango naizela…\n"
	.string "Oso urduri jartzen naiz…\p"
	.string "Eskerrik asko, {PLAYER}{KUN}.\n"
	.string "Berriz elkar ikusten badugu, badakit\l"
	.string "beti bezain lagungarria izango zarela.$"

gText_ApprenticeWhichMove15::
	.string "Zer? badirudi {PLAYER}{KUN} zarela…\n"
	.string "Benetakoa al zara, ordea?\p"
	.string "Agian kopiatzaile famatu\n"
	.string "horietako bat zara?\p"
	.string "Ez, ez, benetakoa bazara, ongi.\n"
	.string "Ez dago haserretu beharrik!\p"
	.string "Izan ere, zure aholkua behar\n"
	.string "nuke.\p"
	.string "Nire {STR_VAR_1}(r)entzat da.\p"
	.string "Zein eraso litzateke hobea beretzat,\n"
	.string "{STR_VAR_2} edo {STR_VAR_3}?$"

gText_ApprenticeMoveThanks15::
	.string "{STR_VAR_1}?\n"
	.string "Ez duzu dudarik?\p"
	.string "Ongi. Hala bada, hala bedi.\n"
	.string "Eskerrik asko zure denboragatik.\p"
	.string "Espero dut gai izango direla nire\n"
	.string "POKéMONAK hori ikasteko.\p"
	.string "Hurrengora arte!$"

gText_ApprenticePickWinSpeech0::
	.string "Ei… {PLAYER}?\n"
	.string "{PLAYER} da!\l"
	.string "Ene! Zintz…zintz… Entzun, mesedez!\p"
	.string "Ni… Borrokan horren urduri jartzen naiz,\n"
	.string "irabazita ere negar egiten dudala…\p"
	.string "Zerbait izugarria esan nahi nuke\n"
	.string "irabazten dudanean…\p"
	.string "Mesedez, mesedez, {PLAYER}!\n"
	.string "Esango zenidake esateko zerbait\l"
	.string "irabazten dudanean negar ez egiteko?$"

gText_ApprenticeWinSpeechThanks0::
	.string "{STR_VAR_1}\p"
	.string "Itzela! Izugarria! Baiiiii!\n"
	.string "Itzela da!\p"
	.string "Ene… Barkatu…\n"
	.string "Horren pozik nago, negarrez hasi\p"
	.string "naizela… Zintz… {PLAYER}!\n"
	.string "Eskerrik asko guztiagatik!\p"
	.string "Ahal bezain ondo borrokatuko dut\n"
	.string "zuregatik, {PLAYER}!\p"
	.string "{PLAYER}…\n"
	.string "Hurrengoan… Borrokatu behar genuke!$"

gText_ApprenticePickWinSpeech1::
	.string "Bai! {PLAYER} da eta! Kaixo!\n"
	.string "Zerbait galdetu nahi nizun!\p"
	.string "Zerbait itzela esan nahi dut\n"
	.string "borroka bat irabaztean.\p"
	.string "Ezagutzen duzu esan dezakedan\n"
	.string "esaldiren bat?$"

gText_ApprenticeWinSpeechThanks1::
	.string "{STR_VAR_1}\p"
	.string "Aizu! Itzela da, bai!\n"
	.string "Ados, hori esango dut!\p"
	.string "Eskerrik asko horrenbestetan laguntzeagatik!\n"
	.string "Hemendik aurrera beti ahalik\l"
	.string "ondoen arituko naiz!\p"
	.string "Berriz elkartzen garenean, borroka\n"
	.string "izugarria izango dugu!$"

gText_ApprenticePickWinSpeech2::
	.string "{PLAYER}, kaixo!\p"
	.string "Nire POKéMONAK eta ni prest gaude\n"
	.string "edozertarako, gauza baterako izan ezik.\p"
	.string "Uste dut esaldiren bat behar dugula\n"
	.string "irabazten dugunean oihukatzeko.\p"
	.string "Badatorkizu esan dezakegun\n"
	.string "zeozer burura?$"

gText_ApprenticeWinSpeechThanks2::
	.string "{STR_VAR_1}\p"
	.string "…Bikain!\n"
	.string "Hori esango dut!\p"
	.string "Borroka pila bat izango dut\n"
	.string "hemendik aurrera.\p"
	.string "Nork jakin, agian noizbait zure aurka\n"
	.string "borrokatuko dut, {PLAYER}.\p"
	.string "Hurrengoan, elkartu gaitezen\n"
	.string "borroka lekuren batean!$"

gText_ApprenticePickWinSpeech3::
	.string "Kaixo, {PLAYER}…\n"
	.string "Barkatu gogaitzea, baina etsita nabil…\p"
	.string "Nik irabazten…\n"
	.string "Irabazten dudanean ere, ez daukat\l"
	.string "ezer berezirik esateko…\p"
	.string "Badakit zuretzat ez dela\n"
	.string "garrantzitsua, {PLAYER}.\p"
	.string "Baina niretzat bat…\p"
	.string "Mesedez, {PLAYER}, zer esan behar\n"
	.string "nuke irabazten dudanean?$"

gText_ApprenticeWinSpeechThanks3::
	.string "{STR_VAR_1}\p"
	.string "Sakona da hori…\p"
	.string "Beno… Esan al dezake ni\n"
	.string "bezalako batek hori?\p"
	.string "Ez! Saiatu egingo naiz!\p"
	.string "{PLAYER}, eskerrik asko horren\n"
	.string "denbora luzean ni jasateagatik…\p"
	.string "Hemendik aurrera izugarri saiatuko naiz.\p"
	.string "Ziur nago azkar ahaztuko duzula\n"
	.string "ni bezalako bat, baina elkar gaitezen\l"
	.string "beste nonbait berriz!$"

gText_ApprenticePickWinSpeech4::
	.string "Ei, {PLAYER}{KUN}.\n"
	.string "Esan nahi nizukeen zerbait daukat.\p"
	.string "Badakit ez naizela beti atsegina\n"
	.string "edo edukatua…\p"
	.string "Irabazten dudanean, uste dut\n"
	.string "harrotzat hartzen nautela.\p"
	.string "Jendeak atsegin nazan nahi dut,\n"
	.string "beraz, zerbait polita behar dut\l"
	.string "irabazten dudanean esateko.\p"
	.string "Baina ez zait ezer bururatzen!\n"
	.string "Ba al datorkizu zerbait burura zuri?$"

gText_ApprenticeWinSpeechThanks4::
	.string "{STR_VAR_1}\p"
	.string "Ez da txarra!\n"
	.string "Bai, horixe erabiliko dut!\p"
	.string "Abiatu egingo naiz, eta beti\n"
	.string "eramango dut bihotzean\l"
	.string "erakutsi didazun guztia.\p"
	.string "Barkatu gehiegitan hurbildu banaiz\n"
	.string "zuregana!\p"
	.string "Hurrengoan, borroka egingo dugu, bai?\n"
	.string "Ikusi arte!$"

gText_ApprenticePickWinSpeech5::
	.string "Ene, lanpetuegi nago berriro!\n"
	.string "Aizu, zure bila ari nintzen, {PLAYER}{KUN}.\p"
	.string "Ondo al zabiltza?\n"
	.string "Hemen gauzak ez dira batere aldatu.\p"
	.string "Oraindik korrika, arrantzan eta mapagintzan\n"
	.string "aritu behar naiz. Zergatik ote nago beti hala?\p"
	.string "Baina lanpetuta egonda ere, ez nuke\n"
	.string "buelta eman eta ezer esan gabe joan\l"
	.string "behar norbait agurtu gabe.\p"
	.string "Zer esan dezaket joan behar dudanean\n"
	.string "itzela naizela garbi uzteko?\l"
	.string "{PLAYER}{KUN}, lagundu, mesedez!$"

gText_ApprenticeWinSpeechThanks5::
	.string "{STR_VAR_1}\p"
	.string "Ongi, ulertuta.\n"
	.string "Aterako dut hori esateko denbora!\p"
	.string "Egia esanda, eskerrak zu bezalako\n"
	.string "irakaslea aurkitu nuen.\p"
	.string "Borrokan aritzeko denbora\n"
	.string "aterako dut nonbaitetik.\p"
	.string "Mila esker guztiagatik, {PLAYER}{KUN}!\n"
	.string "Borrokan egin behar dugu noizbait, ados!$"

gText_ApprenticePickWinSpeech6::
	.string "A zer nolako zortea!\n"
	.string "{PLAYER}! Pozten naiz zu ikusita!\l"
	.string "beti bezela, zure laguntza behar dut!\p"
	.string "Erredoblea, mesedez!\n"
	.string "Nire azken galdera da…\p"
	.string "Borroka bat irabazi eta zerbait\n"
	.string "polita esan nahi banu, zer da\l"
	.string "esan behar nukeena?$"

gText_ApprenticeWinSpeechThanks6::
	.string "{STR_VAR_1}\p"
	.string "Hori… Izugarria da!\n"
	.string "Itzela eta dotorea! Niretzat bikaina!\p"
	.string "…Entzun, uste dut gero eta hobea\n"
	.string "naizela honetan, ez da hala?\p"
	.string "Hemendik aurrera beste ENTRENATZAILE\n"
	.string "batzuen aurka borrokatuko dut.\p"
	.string "{PLAYER}, zure laguntza izugarria izan da.\p"
	.string "Agian egunen batean elkarren aurka\n"
	.string "egingo dugu borrokan!\p"
	.string "Eskerrik asko guztiagatik!$"

gText_ApprenticePickWinSpeech7::
	.string "Ene, {PLAYER}.\n"
	.string "Pozten naiz zu aurkitu izanaz!\p"
	.string "Ez dut nire POKéMONEN inguruko\n"
	.string "galderarik jada.\p"
	.string "Nire inguruan da orain galdera…\p"
	.string "Badakizu ENTRENATZAILE batek borroka\n"
	.string "amaitzean zerbait esaten duela?\p"
	.string "Bada, niri ere gustatuko litzaidake\n"
	.string "halako zeozer egitea!\p"
	.string "Mesedez, zer esan behar nuke borroka\n"
	.string "bat irabazten dudanean?$"

gText_ApprenticeWinSpeechThanks7::
	.string "{STR_VAR_1}\p"
	.string "Ene! Hori bai esaldia! Freskatu\n"
	.string "egiten du entzuten duena!\p"
	.string "Oraintxe bertan erabiliko dut!\p"
	.string "Eta orain, joan beharra dut,\n"
	.string "{PLAYER}…\p"
	.string "Borroka egitera joango naiz, baina\n"
	.string "ez ditut ahaztuko zure irakaspenak.\p"
	.string "Agian, noizbait…\n"
	.string "Ikusi arte!$"

gText_ApprenticePickWinSpeech8::
	.string "Ei! {PLAYER} da eta!\n"
	.string "Nolako poza zu ikusita!\p"
	.string "Ei-ei-ei! Zerbait galdetu\n"
	.string "behar dizut! Duela egun\p"
	.string "batzuk borroka bat irabazi nuen.\n"
	.string "Izugarria izan zen!\p"
	.string "Baina horrenbeste poztu nintzenez,\n"
	.string "blokeatu eta ezin izan nuen ezer esan!\p"
	.string "Beraz, {PLAYER}, mesedez, irabazten\n"
	.string "dudanerako zerbait behar dut!$"

gText_ApprenticeWinSpeechThanks8::
	.string "{STR_VAR_1}\p"
	.string "Buaaaaaa!\n"
	.string "Hori esango al dut?!\l"
	.string "Nolako… Nolako zoriontasuna!\p"
	.string "Mi-mi-mila esker!\n"
	.string "Ez dut ezer damutzeko orain!\p"
	.string "Bidaiatu egingo dut eta mota askotako\n"
	.string "jendearen aurka borrokatuko dut.\p"
	.string "Guztia, zuri zor dizut guztia, {PLAYER}.\n"
	.string "Bihotz-bihotzez, mila esker!\p"
	.string "Joan beharra dut, baina borroka\n"
	.string "dezagun noizbait!$"

gText_ApprenticePickWinSpeech9::
	.string "Kaixo, bai!\n"
	.string "{PLAYER}{KUN}!\p"
	.string "Badakizu zer? Edonora joan eta\n"
	.string "borrokatzeko gogoa sartu zait.\p"
	.string "Baina horren aurretik, zure aholkua\n"
	.string "behar dut beste behin, mesedez!\p"
	.string "Borroka bat irabaziko banu, zer esan\n"
	.string "diezaioket irabazi berri diodan\l"
	.string "ENTRENATZAILEARI?$"

gText_ApprenticeWinSpeechThanks9::
	.string "{STR_VAR_1}\p"
	.string "Bai, bai, hori ona da!\n"
	.string "Bai, jauna!\l"
	.string "Horixe esango dut, di-da!\p"
	.string "Orain, agur esateko garaia heldu da!\n"
	.string "Eskerrik asko egindako guztiagatik!\p"
	.string "Borrokatuko dugu noizbait, ados?\n"
	.string "Agur!$"

gText_ApprenticePickWinSpeech10::
	.string "{PLAYER}{KUN}, arazo itzela!\p"
	.string "Borroka bat irabaztean, ordubete egon\n"
	.string "ohi naiz harro-harro kontatzen!\p"
	.string "Noski gezurretan nabilela!\n"
	.string "Kar-kar!\p"
	.string "Hau ez da gezurra, ordea.\n"
	.string "Ez naiz oso ona hizketan.\p"
	.string "Zer iruditzen zaizu borroka bat irabazi\n"
	.string "ostean esan behar nukeena aukeratuko\l"
	.string "bazenu, irakasle?$"

gText_ApprenticeWinSpeechThanks10::
	.string "{STR_VAR_1}\p"
	.string "Hori da esan behar nukeena, ezta?\n"
	.string "Bada, orduan, ez dut esango!\p"
	.string "Txantxa da!\n"
	.string "Kasu egingo dizut, irakasle!\p"
	.string "Eskerrik asko denbora guzti honetan\n"
	.string "laguntzeagatik, irakasle!\p"
	.string "Hasi naiz ulertzen zer den benetan\n"
	.string "ENTRENATZAILEA izatea.\p"
	.string "Abiatu egingo naiz eta edozein\n"
	.string "ENTRENATZAILERI irabaziko diot.\p"
	.string "Agian egunen batean zu izango zara!\p"
	.string "Hori da guztia!\n"
	.string "Agur, irakasle!$"

gText_ApprenticePickWinSpeech11::
	.string "I-E-P-A T-X-O!\n"
	.string "Horrek iepa txo osatzen du!\p"
	.string "MARINEL raperoa naiz ni!\n"
	.string "hau izango da nire azken galdera,\l"
	.string "ez egin negarrik horren aldera!\p"
	.string "Hitzen inguruan da dema,\n"
	.string "nik behar nuke zure lema!\p"
	.string "Borroka bat irabazterakoan,\n"
	.string "zer esan dena amaitzerakoan?$"

gText_ApprenticeWinSpeechThanks11::
	.string "{STR_VAR_1}\p"
	.string "Bikain! Hori esango dut.\n"
	.string "Irakaslerik bikainena nik baitut!\p"
	.string "Eta orain, onena izango da,\n"
	.string "ni joatea beste edonora!\p"
	.string "Mila esker horrenbeste irakasteagatik.\n"
	.string "Borroka bila joango naiz, bizi-bizirik!\p"
	.string "O-N-D-O-I-Z-A-N!\n"
	.string "Horrek ondo izan osatzen du,\l"
	.string "nire azken agur eta mezu!$"

gText_ApprenticePickWinSpeech12::
	.string "Ei, aupa, {PLAYER}!\n"
	.string "Berriz aurkitu zaitut gaur ere!\p"
	.string "Zer egin behar nuke? Berriz galdetu?\n"
	.string "Zergatik ez? Jada ari naiz eta!\p"
	.string "Berdin da. Beno, {PLAYER}…\n"
	.string "Entzuten al didazu?\l"
	.string "Entzuten didazu!\l"
	.string "Zure aholkua behar dut!\p"
	.string "Oihukatu behar nukeenaren inguruan.\n"
	.string "Borroka bat amaitzean esan behar\l"
	.string "nukeena euforia puruan.\p"
	.string "Ea ba, esan ezazu beldurrik gabe!$"

gText_ApprenticeWinSpeechThanks12::
	.string "{STR_VAR_1}\p"
	.string "Ados, ados!\n"
	.string "Hori esango dut indar osoz!\p"
	.string "Ez dut beste ezer zuri galdetzeko.\n"
	.string "Eskerrak ematea soilik dut esateko.\p"
	.string "Baina noibait elkartuko gara,\n"
	.string "eta nirekin borrokatuko zara.\p"
	.string "Benetan, iritsi da garaia agur esateko.\p"
	.string "Beno, {PLAYER}, banoa mundu zabalera,\n"
	.string "ez nazazu ahaztu, itzuliko naiz, atzera.\p"
	.string "Zaindu zaitez, {PLAYER}!\n"
	.string "Maite zaitut!$"

gText_ApprenticePickWinSpeech13::
	.string "{PLAYER}{KUN}, Ezinean nago…\n"
	.string "Mukia dariola daukat sudurra…\p"
	.string "Zeozertan pentsatzen aritu naiz,\n"
	.string "borrokan esateko zeozertan.\p"
	.string "Horrenbeste inspiratu naiz, negarrez hasi\n"
	.string "naizela, eta orain ezin mukiari eutsi…\p"
	.string "Kontuak kontu, nire partez\n"
	.string "aukeratzea behar nuke, {PLAYER}{KUN}.\p"
	.string "Borroka bat irabazten dudanean,\n"
	.string "zer esan behar nuke?$"

gText_ApprenticeWinSpeechThanks13::
	.string "{STR_VAR_1}\p"
	.string "… … …Ona da hori.\n"
	.string "Benetan da izugarria!\l"
	.string "Malkoak datorzkit begietara!\p"
	.string "Baina nahiz eta malkotan eta mukia\n"
	.string "daridala, horixe erabiliko dut!\p"
	.string "Ez dut ezer gehiago zuri galdetzeko,\n"
	.string "{PLAYER}{KUN}.\p"
	.string "Hemendik aurrera, aurkariak gara!\n"
	.string "Mila esker guztiagatik!$"

gText_ApprenticePickWinSpeech14::
	.string "Bueno… Em…\n"
	.string "{PLAYER}{KUN}…\p"
	.string "Mesedez, ez begiratu horrela.\n"
	.string "Urduri jartzen ari naiz eta.\p"
	.string "Nik… Zure aholkua behar dut berriro.\n"
	.string "Azkena izango da, ordea…\p"
	.string "Lotsa ematen dit galdetzeak, baina,\n"
	.string "zer egin irabazten badut?\l"
	.string "Zer esan behar nuke?$"

gText_ApprenticeWinSpeechThanks14::
	.string "{STR_VAR_1}\p"
	.string "Bai… Ongi!\n"
	.string "Horixe probatuko dut!\l"
	.string "Agian urduri egongo naiz probatzeko…\p"
	.string "Eskerrik asko, {PLAYER}{KUN}.\n"
	.string "Agur esan behar dizut orain.\p"
	.string "Erakutsi didazun guztia obedituko dut,\n"
	.string "{PLAYER}{KUN}, ahalik ondoen.$"

gText_ApprenticePickWinSpeech15::
	.string "Zer? badirudi {PLAYER}{KUN} zarela…\n"
	.string "Baina ba al zara benetan?\l"
	.string "Agian {PLAYER} itxurako PANPINA?\p"
	.string "Ez, ez, ez kezkatu!\n"
	.string "benetakoa bazara, mesedez,\l"
	.string "ahaztu nire zakarkeria.\p"
	.string "Ez dago haserretu beharrik. Zure aholku\n"
	.string "bikainen eske nator soilik.\p"
	.string "Esamolde baten inguruan da.\p"
	.string "Zehatzago esanda, zer esan behar\n"
	.string "nuke borroka bat irabaztean?$"

gText_ApprenticeWinSpeechThanks15::
	.string "{STR_VAR_1}\p"
	.string "… … … … … …\n"
	.string "Borroka bat irabaztean…\p"
	.string "{STR_VAR_1}\p"
	.string "…Benetan ari al zara?\p"
	.string "Ados. Benetan ari bazara, ongi.\n"
	.string "Eskerrik asko zure denboragatik.\p"
	.string "Espero dut ondo erabiliko dudala\n"
	.string "zuk erakutsitako esamoldea.\p"
	.string "Uste dut ez daukadala zuri galdetzeko\n"
	.string "ezer gehiago.\p"
	.string "Agur esan eta nire kasa jarraitzeko\n"
	.string "unea heldu zaidala uste dut.\p"
	.string "Eskerrik asko, irakasle!\n"
	.string "eta barkatu nire eszeptizismo hau guztia!$"
