BattleDome_Text_Potential1::
	.string "Txapeldun izateko hautagai onena!$"

BattleDome_Text_Potential2::
	.string "Finalera iritsiko den taldea, ziur.$"

BattleDome_Text_Potential3::
	.string "Top hiruan geldituko dena, ziurrenik.$"

BattleDome_Text_Potential4::
	.string "Lehenengo postuan buka dezakeen hautagaia.$"

BattleDome_Text_Potential5::
	.string "Goi-mailako potentziala duen taldea.$"

BattleDome_Text_Potential6::
	.string "Txapelketa honetako talde sorpresa.$"

BattleDome_Text_Potential7::
	.string "Bataz-bestekoa baino talde hobea.$"

BattleDome_Text_Potential8::
	.string "Txapelketako bataz-besteko taldea.$"

BattleDome_Text_Potential9::
	.string "Bataz-besteko potentziala duen taldea.$"

BattleDome_Text_Potential10::
	.string "Bataz-bestekoaren azpitik dagoen taldea.$"

BattleDome_Text_Potential11::
	.string "Bere lehen garaipenaren bila doan taldea.$"

BattleDome_Text_Potential12::
	.string "Garaipen batekin harro egongo da talde hau.$"

BattleDome_Text_Potential13::
	.string "Orokorrean, talde ahula.$"

BattleDome_Text_Potential14::
	.string "Potentzial oso gutxiko taldea.$"

BattleDome_Text_Potential15::
	.string "Ziurrenik, txapelketa irabaziko ez duen taldea.$"

BattleDome_Text_Potential16::
	.string "Ziur, txapelketa irabaziko ez duen taldea.$"

BattleDome_Text_PotentialDomeAceTucker::
	.string "Superizar perfektu eta garaitezina!$"

BattleDome_Text_StyleRiskDisaster::
	.string "Batzuetan porroteraino arriskatzeko prest.$"

BattleDome_Text_StyleEndureLongBattles::
	.string "Borroka luzeetan trebea.$"

BattleDome_Text_StyleVariesTactics::
	.string "Etsaiaren arabera taktika aldatzen du.$"

BattleDome_Text_StyleToughWinningPattern::
	.string "Irabazteko eredu gogorra du.$"

BattleDome_Text_StyleUsesVeryRareMove::
	.string "Batzuetan oso eraso arraro bat erabiltzen du.$"

BattleDome_Text_StyleUsesStartlingMoves::
	.string "Eraso nahasgarriak erabiltzen ditu.$"

BattleDome_Text_StyleConstantlyWatchesHP::
	.string "Denbora osoan BPei adi aritzen da.$"

BattleDome_Text_StyleStoresAndLoosesPower::
	.string "Indarra gorde eta bat-batean askatzen iaioa.$"

BattleDome_Text_StyleEnfeeblesFoes::
	.string "Etsaiak ahultzen trebea.$"

BattleDome_Text_StylePrefersLuckTactics::
	.string "Zortean oinarritutako estrategiak atsegin ditu.$"

BattleDome_Text_StyleRegalAtmosphere::
	.string "Errege batek bezala egiten du eraso.$"

BattleDome_Text_StylePowerfulLowPPMoves::
	.string "EP gutxiko eraso indartsuak erabiltzen ditu.$"

BattleDome_Text_StyleEnfeebleThenAttack::
	.string "Lehengo etsaia ahultzen du, gero erasotzeko.$"

BattleDome_Text_StyleBattlesWhileEnduring::
	.string "Eraso guztiak jasanez borrokatzen du.$"

BattleDome_Text_StyleUpsetsFoesEmotionally::
	.string "Etsaiak emozionalki mintzen iaioa da.$"

BattleDome_Text_StyleStrongAndStraightforward::
	.string "Eraso indartsu eta zuzenak erabiltzen ditu.$"

BattleDome_Text_StyleAggressivelyStrongMoves::
	.string "Eraso gogorrak erabiltzen ditu, oldarkor.$"

BattleDome_Text_StyleCleverlyDodgesAttacks::
	.string "Erasoak saihestuz burutsuki borrokatzen du.$"

BattleDome_Text_StyleUsesUpsettingMoves::
	.string "Eraso mingarriak erabiltzen iaioa da.$"

BattleDome_Text_StyleUsesPopularMoves::
	.string "Eraso oso ezagunak erabili ohi ditu.$"

BattleDome_Text_StyleHasPowerfulComboMoves::
	.string "Konbinazio indartsuak lortzeko erasoak ditu.$"

BattleDome_Text_StyleUsesHighProbabilityMoves::
	.string "Probabilitate altuko erasoak erabiltzen ditu.$"

BattleDome_Text_StyleAggressivelySpectacularMoves::
	.string "Eraso ikusgarri eta oldarkorrak erabiltzen ditu.$"

BattleDome_Text_StyleEmphasizesOffenseOverDefense::
	.string "Nahiago du erasoa defentsa baino.$"

BattleDome_Text_StyleEmphasizesDefenseOverOffense::
	.string "Nahiago du defentsa erasoa baino.$"

BattleDome_Text_StyleAttacksQuicklyStrongMoves::
	.string "Eraso indartsu eta azkarrekin erasotzen du.$"

BattleDome_Text_StyleUsesAddedEffectMoves::
	.string "Efektu gehigarridun erasoak erabiltzen ditu.$"

BattleDome_Text_StyleUsesBalancedMixOfMoves::
	.string "Ondo orekatutako eraso sorta erabiltzen du.$"

BattleDome_Text_StyleSampleMessage1::
	.string "Hau 1. probako mezua da.$"

BattleDome_Text_StyleSampleMessage2::
	.string "Hau 2. probako mezua da.$"

BattleDome_Text_StyleSampleMessage3::
	.string "Hau 3. probako mezua da.$"

BattleDome_Text_StyleSampleMessage4::
	.string "Hau 4. probako mezua da.$"

BattleDome_Text_EmphasizesHPAndAtk::
	.string "BP eta ERASOA azpimarratzen ditu.$"

BattleDome_Text_EmphasizesHPAndDef::
	.string "BP eta DEFENTSA azpimarratzen ditu.$"

BattleDome_Text_EmphasizesHPAndSpeed::
	.string "BP eta ABIADURA azpimarratzen ditu.$"

BattleDome_Text_EmphasizesHPAndSpAtk::
	.string "BP eta ER. BER. azpimarratzen ditu.$"

BattleDome_Text_EmphasizesHPAndSpDef::
	.string "BP eta DEF. BER. azpimarratzen ditu.$"

BattleDome_Text_EmphasizesAtkAndDef::
	.string "ERASOA eta DEFENTSA azpimarratzen ditu.$"

BattleDome_Text_EmphasizesAtkAndSpeed::
	.string "ERASOA eta ABIADURA azpimarratzen ditu.$"

BattleDome_Text_EmphasizesAtkAndSpAtk::
	.string "ERASOA eta ER. BER. azpimarratzen ditu.$"

BattleDome_Text_EmphasizesAtkAndSpDef::
	.string "ERASOA eta DEF. BER. azpimarratzen ditu.$"

BattleDome_Text_EmphasizesDefAndSpeed::
	.string "DEFENTSA eta ABIADURA azpimarratzen ditu.$"

BattleDome_Text_EmphasizesDefAndSpAtk::
	.string "DEFENTSA eta ER. BER. azpimarratzen ditu.$"

BattleDome_Text_EmphasizesDefAndSpDef::
	.string "DEFENTSA eta DEF. BER. azpimarratzen ditu.$"

BattleDome_Text_EmphasizesSpeedAndSpAtk::
	.string "ABIADURA eta ER. BER. azpimarratzen ditu.$"

BattleDome_Text_EmphasizesSpeedAndSpDef::
	.string "ABIADURA eta DEF. BER. azpimarratzen ditu.$"

BattleDome_Text_EmphasizesSpAtkAndSpDef::
	.string "ER. BER. eta DEF. BER. azpimarratzen ditu.$"

BattleDome_Text_EmphasizesHP::
	.string "BP azpimarratzen du.$"

BattleDome_Text_EmphasizesAtk::
	.string "ERASOA azpimarratzen du.$"

BattleDome_Text_EmphasizesDef::
	.string "DEFENTSA azpimarratzen du.$"

BattleDome_Text_EmphasizesSpeed::
	.string "ABIADURA azpimarratzen du.$"

BattleDome_Text_EmphasizesSpAtk::
	.string "ER. BER. azpimarratzen du.$"

BattleDome_Text_EmphasizesSpDef::
	.string "DEF. BER. azpimarratzen du.$"

BattleDome_Text_NeglectsHPAndAtk::
	.string "BP eta ERASOA baztertzen ditu.$"

BattleDome_Text_NeglectsHPAndDef::
	.string "BP eta DEFENTSA baztertzen ditu.$"

BattleDome_Text_NeglectsHPAndSpeed::
	.string "BP eta ABIADURA baztertzen ditu.$"

BattleDome_Text_NeglectsHPAndSpAtk::
	.string "BP eta ER. BER. baztertzen ditu.$"

BattleDome_Text_NeglectsHPAndSpDef::
	.string "BP eta DEF. BER. baztertzen ditu.$"

BattleDome_Text_NeglectsAtkAndDef::
	.string "ERASOA eta DEFENTSA baztertzen ditu.$"

BattleDome_Text_NeglectsAtkAndSpeed::
	.string "ERASOA eta ABIADURA baztertzen ditu.$"

BattleDome_Text_NeglectsAtkAndSpAtk::
	.string "ERASOA eta ER. BER. baztertzen ditu.$"

BattleDome_Text_NeglectsAtkAndSpDef::
	.string "ERASOA eta DEF. BER. baztertzen ditu.$"

BattleDome_Text_NeglectsDefAndSpeed::
	.string "DEFENTSA eta ABIADURA baztertzen ditu.$"

BattleDome_Text_NeglectsDefAndSpAtk::
	.string "DEFENTSA eta ER. BER. baztertzen ditu.$"

BattleDome_Text_NeglectsDefAndSpDef::
	.string "DEFENTSA eta DEF. BER. baztertzen ditu.$"

BattleDome_Text_NeglectsSpeedAndSpAtk::
	.string "ABIADURA eta ER. BER. baztertzen ditu.$"

BattleDome_Text_NeglectsSpeedAndSpDef::
	.string "ABIADURA eta DEF. BER. baztertzen ditu.$"

BattleDome_Text_NeglectsSpAtkAndSpDef::
	.string "ER. BER. eta DEF. BER. baztertzen ditu.$"

BattleDome_Text_NeglectsHP::
	.string "BP baztertzen du.$"

BattleDome_Text_NeglectsAtk::
	.string "ERASOA baztertzen du.$"

BattleDome_Text_NeglectsDef::
	.string "DEFENTSA baztertzen du.$"

BattleDome_Text_NeglectsSpeed::
	.string "ABIADURA baztertzen du.$"

BattleDome_Text_NeglectsSpAtk::
	.string "ER. BER. baztertzen du.$"

BattleDome_Text_NeglectsSpDef::
	.string "DEF. BER. baztertzen du.$"

BattleDome_Text_RaisesMonsWellBalanced::
	.string "POKéMONAK era orekatuan hazten ditu.$"

BattleDome_Text_LetTheBattleBegin::
	.string "Has dadila borroka!$"

BattleDome_Text_TrainerWonUsingMove::
	.string "{STR_VAR_1}(e)k {STR_VAR_2} erabilita irabazi du!$"

BattleDome_Text_TrainerBecameChamp::
	.string "{STR_VAR_1} garailea bihurtu da!$"

BattleDome_Text_TrainerWonByDefault::
	.string "{STR_VAR_1}(e)k automatikoki irabazi du!$"

BattleDome_Text_TrainerWonOutrightByDefault::
	.string "{STR_VAR_1}(e)k automatikoki irabazi du zuzenean!$"

BattleDome_Text_TrainerWonNoMoves::
	.string "{STR_VAR_1}(e)k erasotu gabe irabazi du!$"

BattleDome_Text_TrainerWonOutrightNoMoves::
	.string "{STR_VAR_1}(e)k erasotu gabe irabazi du zuzenean!$"

BattleDome_Text_Round1Match1::
	.string "1. txandako 1. norgehiagoka$"

BattleDome_Text_Round1Match2::
	.string "1. txandako 2. norgehiagoka$"

BattleDome_Text_Round1Match3::
	.string "1. txandako 3. norgehiagoka$"

BattleDome_Text_Round1Match4::
	.string "1. txandako 4. norgehiagoka$"

BattleDome_Text_Round1Match5::
	.string "1. txandako 5. norgehiagoka$"

BattleDome_Text_Round1Match6::
	.string "1. txandako 6. norgehiagoka$"

BattleDome_Text_Round1Match7::
	.string "1. txandako 7. norgehiagoka$"

BattleDome_Text_Round1Match8::
	.string "1. txandako 8. norgehiagoka$"

BattleDome_Text_Round2Match1::
	.string "2. txandako 1. norgehiagoka$"

BattleDome_Text_Round2Match2::
	.string "2. txandako 2. norgehiagoka$"

BattleDome_Text_Round2Match3::
	.string "2. txandako 3. norgehiagoka$"

BattleDome_Text_Round2Match4::
	.string "2. txandako 4. norgehiagoka$"

BattleDome_Text_SemifinalMatch1::
	.string "Semifinaleko 1. norgehiagoka$"

BattleDome_Text_SemifinalMatch2::
	.string "Semifinaleko 2. norgehiagoka$"

BattleDome_Text_FinalMatch::
	.string "Azken norgehiagoka$"
