FallarborTown_BattleTentLobby_Text_WelcomeToBattleTent:
	.string "Ongi etorri ARREKARA HERRIKO\n"
	.string "BORROKA DENDARA!\p"
	.string "Zure gida naiz KO Txapelketa Berezian!$"

FallarborTown_BattleTentLobby_Text_TakeChallenge:
	.string "Nahi al duzu parte hartu KO\n"
	.string "Txapelketa Berezian?$"

FallarborTown_BattleTentLobby_Text_AwaitAnotherChallenge:
	.string "Beste batean parte hartuko\n"
	.string "duzula espero dugu!$"

FallarborTown_BattleTentLobby_Text_ExplainFallarborTent:
	.string "ARREKARA HERRIKO BORROKA DENDAN,\n"
	.string "KO Txapelketa Berezia egiten dugu.\p"
	.string "Partaide bakoitzak hiru POKéMONEKO\n"
	.string "talde bat erabiltzen du.\p"
	.string "Hiru POKéMONAK gero agertuko diren\n"
	.string "ordenan ipinita egon behar dira.\p"
	.string "Borrokan, POKéMONAK aurretik jarritako\n"
	.string "ordenan agertuko dira, banaka.\p"
	.string "Behin POKéMON bat borrokan sartzean,\n"
	.string "ezin da atera hau bukatu arte.\p"
	.string "Borroka ez bada hiru txandatan amaitzen,\n"
	.string "epaiketa fasera joango da.\p"
	.string "Zure erronka eten nahi baduzu,\n"
	.string "gorde partida, mesedez.\p"
	.string "Ez baduzu gordetzen, ezingo duzu\n"
	.string "erronkarekin jarraitu.\p"
	.string "Hiru ENTRENATZAILE bata bestearen\n"
	.string "atzetik garaitzea lortzen baduzu,\l"
	.string "sari itzel bat lortuko duzu.$"

FallarborTown_BattleTentLobby_Text_SaveBeforeChallenge:
	.string "BORROKA DENDARA sartu aurretik, partida\n"
	.string "gorde behar dut. Ados zaude horrekin?$"

@ Unused
FallarborTown_BattleTentLobby_Text_WhichLevelMode:
	.string "Bi erronka maila eskaintzen ditugu,\n"
	.string "50. Maila eta Maila Irekia.\l"
	.string "Zein aukeratu nahi duzu?$"

FallarborTown_BattleTentLobby_Text_SelectThreeMons:
	.string "Oso ondo, orain aukeratu zure\n"
	.string "hiru POKéMONAK, mesedez.$"

FallarborTown_BattleTentLobby_Text_NotEnoughValidMonsLv50:
	.string "Erronkari maitea!\p"
	.string "Ez dauzkazu sartzeko behar diren\n"
	.string "hiru POKéMONAK.\p"
	.string "Gainera, ezin dute mota berdineko\n"
	.string "itemik eduki.\p"
	.string "ARRAUTZAK{STR_VAR_1} ez dira onartzen.\p"
	.string "Prestakuntzak egiten dituzunean\n"
	.string "itzuli, mesedez.$"

FallarborTown_BattleTentLobby_Text_NotEnoughValidMonsLvOpen:
	.string "Erronkari maitea!\p"
	.string "Ez dauzkazu sartzeko behar diren\n"
	.string "hiru POKéMONAK.\p"
	.string "Sartzeko, hire POKéMON mota\n"
	.string "desberdin ekarri behar dituzu.\p"
	.string "Gainera, ezin dute mota berdineko\n"
	.string "itemik eduki.\p"
	.string "ARRAUTZAK{STR_VAR_1} ez dira onartzen.\p"
	.string "Prestakuntzak egiten dituzunean\n"
	.string "itzuli, mesedez.$"

FallarborTown_BattleTentLobby_Text_GuideYouToBattleTent:
	.string "BORROKA DENDARA eramango\n"
	.string "zaitut orain.$"

FallarborTown_BattleTentLobby_Text_DidntSaveBeforeQuitting:
	.string "Erronkari maitea!\p"
	.string "Ez duzu partida gorde itzali\n"
	.string "aurretik, ezta?\p"
	.string "Pena da, baina erronkatik\n"
	.string "deskalifikatu zaitu partida\l"
	.string "ez gordetzeak.\p"
	.string "Noski, berriro erronka berri bat\n"
	.string "hasi dezakezu.$"

FallarborTown_BattleTentLobby_Text_BeatThreeTrainers:
	.string "Bikain! Hiru ENTRENATZAILE garaitu\n"
	.string "dituzu bata bestearen atzetik!$"

FallarborTown_BattleTentLobby_Text_WaitWhileSaveGame:
	.string "Mesedez, itxaron partida gorde bitartean.$"

FallarborTown_BattleTentLobby_Text_PresentYouWithPrize:
	.string "3 garaipen jarraian lortu dituzunez,\n"
	.string "sari hau emango dizugu.$"

FallarborTown_BattleTentLobby_Text_ReceivedPrize:
	.string "{PLAYER}(e)k {STR_VAR_1} bat\n"
	.string "lortu du sari gisan.$"

FallarborTown_BattleTentLobby_Text_BagFullReturnForPrize:
	.string "Nola?\n"
	.string "Zure POLTSA beteta dagoela dirudi.\p"
	.string "Egin ezazu espazio pixka bat eta\n"
	.string "bueltatu zure saria jasotzera.$"

FallarborTown_BattleTentLobby_Text_ThankYouWaitWhileSaving:
	.string "Eskerrik asko parte hartzeagatik!\p"
	.string "Mesedez, itxaron partida gorde bitartean.$"

FallarborTown_BattleTentLobby_Text_AwaitAnotherChallenge2:
	.string "Beste batean parte hartuko\n"
	.string "duzula espero dugu!$"

FallarborTown_BattleTentLobby_Text_LookingForwardToArrival:
	.string "Zu noiz etorriko irrikaz egon\n"
	.string "gara.\p"
	.string "BORROKA DENDA erakutsi aurretik, partida\n"
	.string "gorde behar dut. Itxaron, mesedez.$"

VerdanturfTown_BattleTentLobby_Text_WelcomeToBattleTent:
	.string "Ongi etorri BERDEZELAI HERRIKO\n"
	.string "BORROKA DENDARA! Hemen,\p"
	.string "ENTRENATZAILEAREN eta POKéMONAREN\n"
	.string "arteko konfiantza neurtzen da.$"

VerdanturfTown_BattleTentLobby_Text_TakeChallenge:
	.string "Nahi al duzu parte hartu BERDEZELAIKO\n"
	.string "BORROKA DENDAKO txapelketan?$"

VerdanturfTown_BattleTentLobby_Text_ExplainVerdanturfTent:
	.string "BERDEZELAIKO BORROKA DENDAN,\n"
	.string "beti bete beharreko arau garrantzitsu\l"
	.string "bat dago.\p"
	.string "ENTRENATZAILEEK beraien POKéMONAK\n"
	.string "aldatu soilik egin ditzakete.\p"
	.string "ENTRENATZAILEEK ezin diete beraien\n"
	.string "POKéMONEI bestelako agindurik eman.\p"
	.string "POKéMONEK beraien izaeraren arabera jokatu\n"
	.string "eta bakarrik borrokatuko dira.\p"
	.string "Zure POKéMONENGAN konfiantza izan eta\n"
	.string "begiratu soilik egin dezakezu.\p"
	.string "Hiru ENTRENATZAILE bata bestearen atzetik\n"
	.string "garaitzea lortzen baduzu,\l"
	.string "sari bat emango dizugu.\p"
	.string "Zure erronka eten nahi baduzu,\n"
	.string "gorde partida, mesedez.\p"
	.string "Ez baduzu partida gordetzen,\n"
	.string "deskalifikatu egingo zara.$"

VerdanturfTown_BattleTentLobby_Text_ReturnFortified:
	.string "Zure bihotza eta POKéMONAK indartzean,\n"
	.string "itzuli egin behar zenuke.$"

@ Unused
VerdanturfTown_BattleTentLobby_Text_WhichLevelMode:
	.string "Bi zailtasun maila daude,\n"
	.string "50. Maila eta Maila Irekia.\l"
	.string "Zein aukeratu nahi duzu bietatik?$"

VerdanturfTown_BattleTentLobby_Text_NotEnoughValidMonsLv50:
	.string "Ene…\p"
	.string "Ez dauzkazu erronkarako behar\n"
	.string "diren hiru POKéMONAK.\p"
	.string "Parte hartzeko hiru POKéMON desberdin\n"
	.string "ekarri behar dituzu.\p"
	.string "Gainera, ezin dute mota berdineko\n"
	.string "itemik eduki.\p"
	.string "ARRAUTZAK{STR_VAR_1} ez dira onartzen.\p"
	.string "Prestakuntzak egiten dituzunean\n"
	.string "itzuli, mesedez.$"

VerdanturfTown_BattleTentLobby_Text_NotEnoughValidMonsLvOpen:
	.string "Ene…\p"
	.string "Ez dauzkazu erronkarako behar\n"
	.string "diren hiru POKéMONAK.\p"
	.string "Parte hartzeko hiru POKéMON desberdin\n"
	.string "ekarri behar dituzu.\p"
	.string "Gainera, ezin dute mota berdineko\n"
	.string "itemik eduki.\p"
	.string "ARRAUTZAK{STR_VAR_1} ez dira onartzen.\p"
	.string "Prestakuntzak egiten dituzunean\n"
	.string "itzuli, mesedez.$"

VerdanturfTown_BattleTentLobby_Text_SelectThreeMons:
	.string "Ongi. Orain, aukeratu zure hiru\n"
	.string "POKéMONAK.$"

VerdanturfTown_BattleTentLobby_Text_SaveBeforeChallenge:
	.string "BORROKA DENDARA sartu aurretik, partida\n"
	.string "gorde behar dut. Ados zaude horrekin?$"

VerdanturfTown_BattleTentLobby_Text_NowFollowMe:
	.string "Ongi.\n"
	.string "Etorri nirekin.$"

VerdanturfTown_BattleTentLobby_Text_ResultsWillBeRecorded:
	.string "Oso zorte oneko sentitzen naiz zure\n"
	.string "POKéMONEN indarra ikusita.\p"
	.string "Emaitzak gorde egingo dira.\n"
	.string "Itxaron pixka batean.$"

VerdanturfTown_BattleTentLobby_Text_AchievedThreeWinStreak:
	.string "3 garaipen jarraian lortzea…\p"
	.string "Zure bihotzaren eta zure POKéMONENAREN\n"
	.string "artean lotura indartsua dago.$"

VerdanturfTown_BattleTentLobby_Text_FeatWillBeRecorded:
	.string "Zure garaipena gorde egingo da.\n"
	.string "Itxaron pixka batean.$"

VerdanturfTown_BattleTentLobby_Text_PresentYouWithPrize:
	.string "3 garaipen jarraian lortu dituzunez,\n"
	.string "sari hau emango dizugu.$"

SlateportCity_BattleTentLobby_Text_WelcomeToBattleTent:
	.string "Ongi etorri PORTUONDO HIRIKO\n"
	.string "BORROKA DENDARA!\p"
	.string "Zure gida naiz Truke Borrokako\n"
	.string "Txapelketan.$"

SlateportCity_BattleTentLobby_Text_TakeChallenge:
	.string "Nahi duzu Truke Borrokako Txapelketan\n"
	.string "parte hartu?$"

SlateportCity_BattleTentLobby_Text_ExplainSlateportTent:
	.string "PORTUONDOKO BORROKA DENDAN, Truke\n"
	.string "Borrokako Txapelketak alokatutako\l"
	.string "POKéMONAK erabiliz egiten ditugu.\p"
	.string "Lehenik, hiru POKéMON utziko dizkizugu\n"
	.string "txapelketa honetan parte hartzeko.\p"
	.string "Alokatutako POKéMON hauek erabilita,\n"
	.string "BORROKA BAKARRA egin behar duzu.\p"
	.string "Irabazten baduzu, hiru POKéMONetako\n"
	.string "bat trukatu dezakezu.\p"
	.string "Borroka eta trukeko prozesua hiru\n"
	.string "aldiz egin. Bata bestearen atzetik hiru\l"
	.string "borroka irabazita, saria lortuko duzu.\p"
	.string "Zure erronka eten nahi baduzu,\n"
	.string "gorde partida, mesedez.\p"
	.string "Ez baduzu partida gordetzen,\n"
	.string "deskalifikatu egingo zara.$"

SlateportCity_BattleTentLobby_Text_LookForwardToNextVisit:
	.string "Berriro etorriko zarela espero dugu.$"

@ Unused
SlateportCity_BattleTentLobby_Text_WhichLevelMode:
	.string "Zein mailatan nahi duzu parte hartu?\n"
	.string "50. Maila edo 100. Maila?$"

SlateportCity_BattleTentLobby_Text_SaveBeforeChallenge:
	.string "Erronka hasi aurretik, partida gorde\n"
	.string "behar dut. Ados zaude horrekin?$"

@ Unused
SlateportCity_BattleTentLobby_Text_HoldMonsForSafekeeping:
	.string "Ongi, eman zure POKéMONAK erronkan\n"
	.string "parte hartu bitartean gordetzeko.$"

SlateportCity_BattleTentLobby_Text_StepThisWay:
	.string "Pasa hemendik, mesedez.$"

SlateportCity_BattleTentLobby_Text_ReturnRentalMonsSaveResults:
	.string "Mila esker parte hartzeagatik!\p"
	.string "Zure POKéMONAK itzuliko dizkizut\n"
	.string "alokairuko POKéMONEN truke.\p"
	.string "Erronkako emaitzak ere gorde behar ditut.\n"
	.string "Itxaron, mesedez.$"

@ Unused
SlateportCity_BattleTentLobby_Text_ReturnMonsExchangeRentals:
	.string "Zure POKéMONAK itzuliko dizkizut\n"
	.string "alokairuko POKéMONEN truke.$"

SlateportCity_BattleTentLobby_Text_WonThreeMatchesReturnMons:
	.string "Zorionak!\n"
	.string "Hiru borroka irabazi dituzu jarraian!\p"
	.string "Zure POKéMONAK itzuliko dizkizut\n"
	.string "alokairuko POKéMONEN truke.\p"
	.string "Erronkako emaitzak ere gorde behar ditut.\n"
	.string "Itxaron, mesedez.$"

SlateportCity_BattleTentLobby_Text_AwardYouThisPrize:
	.string "3 garaipen jarraian lortu dituzunez,\n"
	.string "sari hau emango dizugu.$"

SlateportCity_BattleTentLobby_Text_NoRoomInBagMakeRoom:
	.string "Nola?\n"
	.string "Badirudi ez duzula sariarentzako lekurik.\p"
	.string "Egin tokia zure POLTSAN eta itzuli\n"
	.string "sariaren bila, mesedez.$"

SlateportCity_BattleTentLobby_Text_BeenWaitingForYou:
	.string "Zure zain egon gara!\p"
	.string "Erronkarekin jarraitu aurretik,\n"
	.string "partida gorde behar dut.$"

SlateportCity_BattleTentLobby_Text_DidntSaveBeforeQuitting:
	.string "Sentitzen dut, baina badirudi ez zenuela\n"
	.string "partida gorde azkenengoan.\p"
	.string "Horren ondorioz, erronkatik deskalifikatu\n"
	.string "egin zaitugu.$"

@ Unused
SlateportCity_BattleTentLobby_Text_ReturnPersonalMons:
	.string "Hemen dituzu zure POKéMONAK bueltan.$"

@ Unused
SlateportCity_BattleTentLobby_Text_ReceivedPrize:
	.string "{PLAYER}(e)k {STR_VAR_1} bat\n"
	.string "lortu du sari gisan.$"

@ Unused
SlateportCity_BattleTentLobby_Text_RulesAreListed:
	.string "Truke Borrokako arauak ikus daitezke.$"

@ Unused
SlateportCity_BattleTentLobby_Text_ReadWhichHeading:
	.string "Zein gairen inguruan irakurri nahi duzu?$"

SlateportCity_BattleTentLobby_Text_ExplainBasicRules:
	.string "Truke Borrokako proba batean hiru\n"
	.string "POKéMON bakarrik erabili ditzakezu.\p"
	.string "Alokatu edo trukatu egiten badituzu,\n"
	.string "ezin dituzu taldean berdinak diren bi\l"
	.string "POKéMON edo gehiago eduki.$"

SlateportCity_BattleTentLobby_Text_ExplainSwapPartnerRules:
	.string "Garaitu berri duzun ENTRENATZAILEAREKIN\n"
	.string "soilik trukatu ditzakezu POKéMONAK.\p"
	.string "ENTRENATZAILEAK zituen POKéMONEKIN\n"
	.string "soilik egin dezakezu trukea.$"

SlateportCity_BattleTentLobby_Text_ExplainSwapNumberRules:
	.string "Irabazten duzun partida bakoitzeko,\n"
	.string "zure POKéMON bat truka dezakezu garaitu\l"
	.string "berri duzun ENTRENATZAILEAREN batekin.\p"
	.string "Ezingo duzu POKéMONIK TRUKATU\n"
	.string "hirugarren ENTRENATZAILEAREKIN.$"

SlateportCity_BattleTentLobby_Text_ExplainSwapNotes:
	.string "Bi gauza izan behar dituzu kontuan\n"
	.string "POKéMONAK trukatzerakoan.\p"
	.string "Lehenik, trukatzerakoan, ezin dituzu\n"
	.string "jasoko duzun POKéMONAREN\l"
	.string "estatistikak begiratu.\p"
	.string "Bigarren, zure taldeko POKéMONAK\n"
	.string "ordenatuta egongo dira, alokatu\l"
	.string "dituzunean ordenatu dituzun bezala.\p"
	.string "Trukeak egin ostean ere, ordena\n"
	.string "berdin mantenduko da.$"

SlateportCity_BattleTentLobby_Text_ExplainMonRules:
	.string "PORTUONDOKO BORROKA DENDAKO\n"
	.string "POKéMONAK alokatu egiten dira.\p"
	.string "Alokatutako POKéMON guztiak\n"
	.string "30. Mailan daude.$"

@ Unused
VerdanturfTown_BattleTentLobby_Text_RulesAreListed2:
	.string "BERDEZELAIKO BORROKA DENDAKO arauak\n"
	.string "ikus daitezke.$"

@ Unused
VerdanturfTown_BattleTentLobby_Text_ReadWhichHeading:
	.string "Zein gairen inguruan irakurri nahi duzu?$"

@ Unused
VerdanturfTown_BattleTentLobby_Text_ExplainBasicRules:
	.string "BERDEZELAIKO BORROKA DENDAN,\n"
	.string "POKéMONEK bere kasa pentsatu\l"
	.string "eta borrokatu behar dute.\p"
	.string "Basatiak direnean ez bezala,\n"
	.string "jendearekin bizi diren POKéMONEK beren\l"
	.string "izaeraren arabera jokatzen dute.$"

@ Unused
VerdanturfTown_BattleTentLobby_Text_ExplainNatureRules:
	.string "Bere izaeraren arabera, POKéMON batek\n"
	.string "nahiago izan dezake beti erasotzea.\p"
	.string "Beste POKéMON batek nahiago izan dezake\n"
	.string "beti kolpeetatik defenditzea.\p"
	.string "Beste batek bere aurkariak nahastea\n"
	.string "aukeratu dezake.\p"
	.string "Bere izaeraren arabera, POKéMON batek\n"
	.string "gehien gustatzen zaizkion erasoak ere\l"
	.string "izan ditzake.\p"
	.string "Atsegin ez dituen erasoak ere izan\n"
	.string "ditzake, ez dituelako ondo erabiltzen.$"

@ Unused
VerdanturfTown_BattleTentLobby_Text_ExplainMoveRules:
	.string "Eraso batzuek zuzenean mina eragiten\n"
	.string "diote etsaiari.\p"
	.string "Beste eraso batzuek etsaiaren erasoetatik\n"
	.string "babesten lagundu dezakete, edo BPak\l"
	.string "sendatzeko erabili daitezke, besteak beste.\p"
	.string "Beste eraso berezi batzuek etsaiak ahultzen\n"
	.string "lagundu dezakete, hauek pozoinduz,\l"
	.string "paralizatuz, edo beste egoera batzuk\l"
	.string "aplikatuz.\p"
	.string "POKéMONEK hiru mota hauetako erasoak\n"
	.string "aukeratuko dituzte.$"

@ Unused
VerdanturfTown_BattleTentLobby_Text_ExplainUnderpoweredRules:
	.string "ENTRENATZAILE gabe daudenean, POKéMON\n"
	.string "bat agian ez da gai izango eraso\l"
	.string "batuzk era egokian erabiltzeko.\p"
	.string "POKéMON batek ez badu eraso bat gustuko\n"
	.string "ez du ondo erabiliko.\p"
	.string "POKéMON batek bere izaerarekin bat egiten\n"
	.string "ez duten erasoak soilik baditu, ez da gai\l"
	.string "izango bere potentzial guztia erakusteko.$"

@ Unused
VerdanturfTown_BattleTentLobby_Text_ExplainWhenInDangerRules:
	.string "Izaeraren arabera, POKéMON batek bere\n"
	.string "izaerarekin bat ez doazen erasoak erabili\l"
	.string "ditzake, arriskuan baldin badago.\p"
	.string "POKéMON bat arraro jokatzen hasten\n"
	.string "baldin bada, ondo aztertu.$"

BattleTentLobby_Text_ExplainLevelRules:
	.string "BORROKA DENDA honetan, zure aurkarien\n"
	.string "mailak zure POKéMONEN mailaren arabera\l"
	.string "orekatuta egongo dira.\p"
	.string "Hala ere, ez da ENTRENATZAILERIK egongo\n"
	.string "30. maila baino beherago dituenik.$"

VerdanturfTown_BattleTentLobby_Text_RulesAreListed:
	.string "BERDEZELAIKO BORROKA DENDAKO arauak\n"
	.string "ikus daitezke.$"
