PetalburgCity_Gym_Text_GiveEnigmaBerry:
	.string "AITA: Epa, {PLAYER}!\p"
	.string "BAIA oso berezi bat jaso berri dut.\n"
	.string "Zuretzat izatea nahi nuke.$"

Route104_Text_PlantBerriesInSoilTakeThis:
	.string "Lurrean BAIA landareak ikusten\n"
	.string "badituzu, lasai asko hartu.\p"
	.string "Baina gogoratu beste BAIA bat landatzea\n"
	.string "leku berean. Denontzat hobe.\p"
	.string "Tori, hau zuretzat da.$"

Route104_Text_TrainersOftenMakeMonHoldBerries:
	.string "Zure begiradan ikus dezaket,\n"
	.string "ENTRENATZAILEA zara, baietz?\p"
	.string "ENTERNATZAILEEK POKéMONei\n"
	.string "BAIAK eman ohi dizkiete.\p"
	.string "Zuk aukeratu BAIAK landatu\n"
	.string "edo erabiltzen dituzun.$"

Route111_Text_WateredPlantsEveryDayTakeBerry:
	.string "Egunero ureztatu nituen landareak.\n"
	.string "Lore pila bat hazi zituzten.\p"
	.string "Eta BAIA pila bat ere bai.\p"
	.string "Tori!\n"
	.string "Zuretzat!$"

Route111_Text_GoingToTryToMakeDifferentColorBerries:
	.string "Pila bat saiatuko naiz kolore\n"
	.string "desberdinetako BAIAK lortzeko.\p"
	.string "Saiatu zu ere!$"

Route111_Text_WhatColorBerriesToLookForToday:
	.string "Zein koloretako BAIAK bilatuko\n"
	.string "ote ditut gaur?$"

Route114_Text_LoveUsingBerryCrushShareBerry:
	.string "BAIA TXIKITZAILEA erabiltzea atsegin dut,\n"
	.string "beraz, BAIAK jasotzen ari naiz.\p"
	.string "Bat emango dizut, nahi baduzu.$"

Route114_Text_TryBerryCrushWithFriends:
	.string "BAIA TXIKITZAILEA probatu behar\n"
	.string "zenuke zure lagunekin.$"

Route114_Text_FunToThinkAboutBerries:
	.string "Zein BAIA landatu nahi duzu?\n"
	.string "Erabili edo gorde egin behar\p"
	.string "zenituzke? Zein dibertigarria.$"

Route120_Text_BerriesExpressionOfLoveIsntIt:
	.string "BAIAK eguzkiarekin hazten dira.\p"
	.string "Eta erregularki ureztatuz are gehiago\n"
	.string "laguntzen diegu.\p"
	.string "Maitasun keinu bat da, ezta?$"

Route120_Text_YesYouUnderstand:
	.string "Bai, bai.\n"
	.string "Ulertzen didazu.\p"
	.string "Hau hartu behar zenuke.$"

Route120_Text_MakeYourOwnImpressions:
	.string "Oh… Baina egia da zure iritzi\n"
	.string "propioak sortzea garrantzitsua dela…\p"
	.string "Tori hau.$"

Route120_Text_BerryIsRareRaiseItWithCare:
	.string "Uste dut BAIA hori berezia dela.\n"
	.string "Espero dut maitasunez zainduko duzula.$"

Route120_Text_IllGetMoreBerriesFromBerryMaster:
	.string "BAIA gehiago lortuko ditut\n"
	.string "BAIA MAISUARI eskatuta.$"

LilycoveCity_Text_BerrySuitsYou:
	.string "Barren barrenean begiratzen badugu…\p"
	.string "Trajeak niri bezain ondo,\n"
	.string "doakio haizea itsasoari.\p"
	.string "Eta zuri, BAIA bat doakizu, super ongi…\p"
	.string "Zergatik ote?$"

LilycoveCity_Text_BecauseYoureTrainer:
	.string "Barren barrenean begiratzen badugu…\p"
	.string "ENTEATZAILEA zarelako da!$"

LilycoveCity_Text_PokeblocksSuitPokemon:
	.string "Barren barrenean begiratzen badugu…\p"
	.string "Nola geratzen zaidan sinpletasuna niri,\n"
	.string "hala {POKEBLOCK}ak POKéMONei.$"

Route123_BerryMastersHouse_Text_YoureDeservingOfBerry:
	.string "BAIA MAISUA dei diezadaketa.\p"
	.string "Nire ametsa mundu osoa lore\n"
	.string "ederrez betetzea da, hortaz, BAIAK landatzen\l"
	.string "ditut, eta mundu guztiari banatu.\p"
	.string "Zuk bat merezi duzu!$"

Route123_BerryMastersHouse_Text_WhyBeStingyTakeAnother:
	.string "Zergatik izan xuhurra?\n"
	.string "Hartu beste bat!$"

Route123_BerryMastersHouse_Text_VisitPrettyPetalFlowerShop:
	.string "Ez ahaztu PETALO EDER loradenda\n"
	.string "bisitatzea BURDINTZA hirian.\p"
	.string "Bete dezagun mundua lorez!$"

Route123_BerryMastersHouse_Text_DoneForToday:
	.string "Gaurkoz nahikoa.\n"
	.string "Etorri beste egun batean.\p"
	.string "Bete dezagun mundua lorez!$"

Route123_BerryMastersHouse_Text_HeardAGoodSayingLately:
	.string "Nola hazten dituen BAIAK nire\n"
	.string "senarrak, oh, munduko onena da.\p"
	.string "Ze harro nagoen beraz.\p"
	.string "Aizu, gazte, entzun al duzu\n"
	.string "esaldi onik azkenaldian?$"

Route123_BerryMastersHouse_Text_InspirationalTakeThis:
	.string "Bua! Ze esaldi sakona!\n"
	.string "Inspirazioa duzu, bai jauna!\p"
	.string "Hau zuretzat izatea nahi nuke.$"

Route123_BerryMastersHouse_Text_GoodSayingTakeThis:
	.string "Oh! Esaldi bikaina, alajaina!\n"
	.string "Gazte berezia zara zu.\p"
	.string "Hau zuretzat izatea nahi nuke.$"

Route123_BerryMastersHouse_Text_JoyNeverGoesOutOfMyLife:
	.string "Gure lau bilobak nire senarra\n"
	.string "baino hobeak bilakatuko dira.\p"
	.string "Zein ederra den bizitza!$"

Route123_BerryMastersHouse_Text_Ah:
	.string "Ah…$"

Route104_PrettyPetalFlowerShop_Text_ThisIsPrettyPetalFlowerShop:
	.string "Kaixo!\p"
	.string "Hau PETALO EDER loradenda da.\n"
	.string "Loreak etxetik kalera eta kaletik etxera!$"

Route104_PrettyPetalFlowerShop_Text_LearnAboutBerries:
	.string "{PLAYER}{KUN}, nahi al duzu BAIEN\n"
	.string "inguruan ikasi?$"

Route104_PrettyPetalFlowerShop_Text_IntroLearnAboutBerries:
	.string "Zure izena?\p"
	.string "{PLAYER}{KUN}.\n"
	.string "izen polita, alajaina.\p"
	.string "{PLAYER}{KUN}, nahi al duzu BAIEN\n"
	.string "inguruan ikasi?$"

Route104_PrettyPetalFlowerShop_Text_BerriesExplanation:
	.string "BAIAK zuhaitzetan hazten dira\n"
	.string "lur bigunean landatuta badaude.\p"
	.string "BAIAK jasotzen badituzu gogoratu\n"
	.string "beste bat landatzea leku berean.\p"
	.string "Landatutako BAIA bat kimatu,\n"
	.string "pixkanaka hazi, loratu,\l"
	.string "eta berriro BAIAK emango ditu.\p"
	.string "Mundu osoa lore ederrez beteta\n"
	.string "ikusi nahi nuke.\l"
	.string "Hori da nire ametsa.\p"
	.string "Lagundu, mesedez, {PLAYER}{KUN}. BAIAK\n"
	.string "landatu eta bete mundua lorez.$"

Route104_PrettyPetalFlowerShop_Text_FlowersBringHappiness:
	.string "Loreek zoriontasuna dakarkie\n"
	.string "pertsonei, ezta?$"

Route104_PrettyPetalFlowerShop_Text_YouCanHaveThis:
	.string "Kaixo!\p"
	.string "Loreei atentzio gehiago emanda,\n"
	.string "are ederrago loratuko dira.\p"
	.string "Gustatuko zaizu loreak zaintzea\n"
	.string "Seguru nago. Tori hau.$"

Route104_PrettyPetalFlowerShop_Text_WailmerPailExplanation:
	.string "BAIAK hazi bitartean,\n"
	.string "ureztatu itzazu WAILMER ONTZIAREKIN.\p"
	.string "Ah, beste kontu bat.\p"
	.string "Ez badituzu BAIAK denbora luzez\n"
	.string "jasotzen, lurrera eroriko dira.\l"
	.string "Baina berriro kimatuko dira.\p"
	.string "Ez al da izugarria?\n"
	.string "Bizitzeko gogoa izango balute bezala.$"

Route104_PrettyPetalFlowerShop_Text_ImGrowingFlowers:
	.string "Nire ahizpa nagusiak bezalakoa izan\n"
	.string "nahi dut. Loreak landatuko ditut!\p"
	.string "Hementxe!\n"
	.string "Hau zuretzat!$"

Route104_PrettyPetalFlowerShop_Text_MachineMixesBerries:
	.string "BAIA bat landatu dezakezu eta hazten\n"
	.string "ikusi, edo POKéMON bati eman.\p"
	.string "Baina orain BAIAK nahasten dituen\n"
	.string "MAKINA bat daukate POKÉMONENTZAT\l"
	.string "gozokiak egiteko.\p"
	.string "Nik ere gozokiak nahi ditut.$"

SootopolisCity_Text_NameIsKiriHaveOneOfThese:
	.string "Epa, zein da zure izena?\p"
	.string "… … …  … … …  … … …\n"
	.string "Ongi. Izen polita!\p"
	.string "Ni KIRI naiz.\p"
	.string "Aitatxo eta amatxok izen hori jarri\n"
	.string "zidaten osasuntsu eta jator haz nedin.\l"
	.string "Hori esan zidaten.\p"
	.string "Tori objektu hau.$"

SootopolisCity_Text_GiveYouThisBerryToo:
	.string "KIRIk BAIA hau ere emango dizu!\n"
	.string "Asko atsegin dut!$"

SootopolisCity_Text_WhatKindOfWishInYourName:
	.string "Zein gurari egongo ote da zure\n"
	.string "izenaren esanahiean?$"

SootopolisCity_Text_LikeSeasonBornIn:
	.string "Udaberria, uda, udazkena, eta negua.\p"
	.string "Udaberrian jaiotzen bazara, udaberria\n"
	.string "atsegin duzu, eta udan jaiota\l"
	.string "uda, edo zer?$"

SootopolisCity_Text_ThenILoveAutumn:
	.string "Orduan KIRI udazkenean jaio zenez,\n"
	.string "maite dut udazkena!\p"
	.string "Zein urtaro gustatzen zaizu zuri?$"

SootopolisCity_Text_OhDoesntMatter:
	.string "Oh…\n"
	.string "Ez du axola…\p"
	.string "Jakin nahiko nukeen horrenbeste dago…$"
