gText_Birch_Welcome::
	.string "Kaixo! Denbora asko egon al zara\n"
	.string "itxaroten?\p"
	.string "Ongi etorri POKéMONen mundura!\p"
	.string "Nire izena URKI da.\p"
	.string "Baina guztiek POKéMON MAISUA\n"
	.string "deitzen didate.\p"
	.string "$"

gText_Birch_Pokemon::
	.string "Honako hau “POKéMON” bat da.\p"
	.string "\n"
	.string "$"

gText_Birch_MainSpeech::
	.string "Mundu hau POKéMON izeneko\n"
	.string "izakiz beteta dago.\p"
	.string "Gizakiok POKéMONekin batera bizi gara,\n"
	.string "batzuetan jolaskide atsegin,\l"
	.string "besteetan laguntzaile bikain.\p"
	.string "Eta beste batzuetan, elkartu\n"
	.string "eta borrokatu egiten dugu.\p"
	.string "Antzekoak bagara ere, ez dugu\n"
	.string "POKéMONen inguruko guztia ezagutzen.\p"
	.string "Egia esanda, POKéMONen inguruko\n"
	.string "sekretu pila bat daude.\p"
	.string "Misterio hauek argitzen saiatzeko,\n"
	.string "ikerketan buru-belarri aritzen naiz.\l"
	.string "Hori da nire lana.\p"
	.string "$"

gText_Birch_AndYouAre::
	.string "Eta nor zara zu?$"

gText_Birch_BoyOrGirl::
	.string "Mutila al zara?\n"
	.string "Ala neska?$"

gText_Birch_WhatsYourName::
	.string "Ederki, orduan.\n"
	.string "Nola duzu izena?$"

gText_Birch_SoItsPlayer::
	.string "{PLAYER}{KUN}, beraz?$"

gText_Birch_YourePlayer::
	.string "Ene bada, noski!\p"
	.string "{PLAYER}{KUN} zara, ERROTXIKIra\n"
	.string "iritsi berri zara familiarekin, ezta?.\l"
	.string "Ahaztua nuen!\p"
	.string "$"

gText_Birch_AreYouReady::
	.string "Oso ondo, prest al zaude?\p"
	.string "Zure abentura hastera doa.\n"
	.string "Adorez bete, eta murgildu\p"
	.string "POKéMONen munduan, ametsez,\l"
	.string "abenturaz eta lagun berriz betea!\p"
	.string "Beno, zure zain egongo naiz.\n"
	.string "Etorri nire POKéMON laborategira gero.\p"
	.string "$"
