BerryBlender_Text_BlendWithTheBlendMaster:
	.string "NAHAS MAISUA: Bai, jauna!\n"
	.string "Neu naiz NAHAS MAISUA!\p"
	.string "Nahastu nirekin, eta nire nahasteko\n"
	.string "abilezia gorena ikusiko duzu!$"

BerryBlender_Text_SeeMyMasteryInAction:
	.string "NAHAS MAISUA: Hmmm! Orduan, nire\n"
	.string "maisutasuna martxan ikusi nahi?$"

BerryBlender_Text_TooBusyNowIsee:
	.string "Hmmm!\p"
	.string "Okupatuta zaude, ikusten dut, bai!\p"
	.string "Baina ez kezkatu!\n"
	.string "Hemen izango naiz egun osoan!\l"
	.string "Azkar itzuli zure enkarguetatik!$"

BerryBlender_Text_BlendMasterNoBerries:
	.string "Hmmm!\p"
	.string "Baina ez duzu BAIA bakar bat ere!\p"
	.string "Hemen izango naiz egun osoan!\n"
	.string "Itzuli zaitez BAIAK dituzunean!$"

BerryBlender_Text_BlendMasterKnowHowToMakePokeblocks:
	.string "Noski!\n"
	.string "Noski!\p"
	.string "Aizu, eta…\n"
	.string "Ba al dakizu nola lortu {POKEBLOCK}ak\l"
	.string "BAIAK nahastuta?$"

BerryBlender_Text_BlendMasterExplainBerryBlending:
	.string "Hmmm!\p"
	.string "Bueno, ba oso erraza da!\p"
	.string "IRABIAGAILUAREN gezia zure\n"
	.string "markan dagoenean, A Botoia sakatu.\p"
	.string "Horixe besterik ez.\p"
	.string "Botoia sakatzeko nire zehaztasuna\n"
	.string "ikusten duzunean, orduan ulertuko duzu.$"

BerryBlender_Text_BlendMasterLetsBerryBlender:
	.string "Ongi!\p"
	.string "Has gaitezen!\p"
	.string "NAHAS MAISUAREKIN batera,\n"
	.string "goazen BAIAK nahastera!$"

BerryBlender_Text_BlendMasterNoPokeblockCase:
	.string "Hmmm!\p"
	.string "Badirudi ez duzula oraindi\n"
	.string "{POKEBLOCK} KAXA lortu!\p"
	.string "Hemen izango naiz egun osoan!\n"
	.string "Lortu {POKEBLOCK} KAXA eta azkar itzuli!$"

BerryBlender_Text_BlendMasterPokeblockCaseFull:
	.string "Hmmm!\p"
	.string "Zure {POKEBLOCK} KAXA betea dago!\p"
	.string "Hemen izango naiz egun osoan!\n"
	.string "Erabili {POKEBLOCK}ak eta azkar itzuli!$"

BerryBlender_Text_WhoaAwesome:
	.string "Ene!\n"
	.string "Izugarria!$"

BerryBlender_Text_WickedlyFast:
	.string "Izugarri azkar!$"

BerryBlender_Text_WhatAnExpert:
	.string "A zer nolako abilezia!$"

BerryBlender_Text_MadeAmazingPokeblocksWithMaster:
	.string "MAISUAREKIN nahasten dudanean,\n"
	.string "{POKEBLOCK} onenak bete-betean!$"

BerryBlender_Text_QualitiesOfBlendMaster:
	.string "Gezia begiz galtzea,\n"
	.string "makina batek bezain zehatz…\p"
	.string "A Botoia zapaltzen duen eskua\n"
	.string "erlojuaren zehaztasunez…\p"
	.string "Horrek egiten du NAHAS MAISUA\n"
	.string "onenetan onena.$"

BerryBlender_Text_MasterWorksOnSkillsInMountains:
	.string "NAHAS MAISUAK mendian urruti\n"
	.string "entrenatzen du normalean.\p"
	.string "Batzuetan, UR-LILIra etortzen da\n"
	.string "BAIAK nahasteko egun osoan zehar.$"
