Text_PictureBookShelf:
	.string "POKÉMONEN argazki-liburuz betea dago.$"

Text_BookShelf:
	.string "Mota askotako liburuz lepo dago.$"

Text_PokemonCenterBookShelf:
	.string "POKÉMONEN aldizkariak!\n"
	.string "POKéMON LAGUNA…\p"
	.string "POKéMON ESKULIBURUA…\n"
	.string "POKéMON POLITAK…$"

Text_Vase:
	.string "Ontzi garestia dirudi…\n"
	.string "Barruan begiratu duzu…\p"
	.string "Baina, hutsik dago.$"

Text_EmptyTrashCan:
	.string "Hutsik dago.$"

Text_ShopShelf:
	.string "Apalak POKéMON merchandisingez\n"
	.string "mukuru daude.$"

Text_Blueprint:
	.string "Plano bat edo antzeko zeozer da.\n"
	.string "Ulergaitza da guztiz!$"
