@ With the exception of Link standby, none of the below texts are used

gTest_MissedTurn::
	.string "Txanda galduta$"

gText_LinkStandby4::
	.string "Konexioa geldituta!$"

gText_WinnerIsPlayersMonCongrats::
	.string "{STR_VAR_1}(r)en {STR_VAR_2} da irabazlea!\n"
	.string "Zorionak!$"

gText_WinnerIsPlayersMon::
	.string "{STR_VAR_1}(r)en {STR_VAR_2} da irabazlea!{PAUSE_UNTIL_PRESS}$"

gText_PrimaryJudgingNumX::
	.string "Lehen epaia: {STR_VAR_1}. a{PAUSE_UNTIL_PRESS}$"

gText_SecondaryJudgingNumX::
	.string "Bigarren epaia: {STR_VAR_1}. a{PAUSE_UNTIL_PRESS}$"

gText_SetEventNumX::
	.string "Gertaera: {STR_VAR_1}. a{PAUSE_UNTIL_PRESS}$"

gText_MoveUsedMostOften::
	.string "Gehien erabilitako erasoa:\n"
	.string "{STR_VAR_1}{PAUSE_UNTIL_PRESS}$"

gText_MostImpressiveMon::
	.string "POKéMON harrigarriena:\n"
	.string "{STR_VAR_1}(r)en {STR_VAR_2}{PAUSE_UNTIL_PRESS}$"

gText_SetEventNumX2::
	.string "Gertaera: {STR_VAR_1}. a{PAUSE_UNTIL_PRESS}$"

gText_LinkTVProgramWillNotBeMadeTrainerLost::
	.string "Ez da Link telebistako programarik egingo\n"
	.string "ENTRENATZAILEAK galdu egin duelako.{PAUSE_UNTIL_PRESS}$"
