@ Contest move effect descriptions

gText_HighlyAppealingMove::
	.string "Erakustaldi itzela da eraso hau.$"

gText_UserMoreEasilyStartled::
	.string "Eraso honen ostean, erabiltzailea\n"
	.string "errazago ikaratzen da.$"

gText_GreatAppealButNoMoreToEnd::
	.string "Erakustaldi izugarria da, baina\n"
	.string "gero ezin da ezer gehiago egin.$"

gText_UsedRepeatedlyWithoutBoringJudge::
	.string "Behin eta berriz erabili daiteke\n"
	.string "EPAILEA aspertu gabe.$"

gText_AvoidStartledByOthersOnce::
	.string "Besteek ikaratzea saihestu\n"
	.string "dezake, behin.$"

gText_AvoidStartledByOthers::
	.string "Besteek ikaratzea saihestu\n"
	.string "dezake.$"

gText_AvoidStartledByOthersLittle::
	.string "Besteek ikaratzea saihestu\n"
	.string "dezake, pixka bat.$"

gText_UserLessLikelyStartled::
	.string "Eraso honen ostean, erabiltzaileak\n"
	.string "ikaratzeko aukera gutxiago du.$"

gText_SlightlyStartleFrontMon::
	.string "Parean duen POKéMONa\n"
	.string "pixka bat ikaratzen du.$"

gText_SlightlyStartleAppealed::
	.string "Erakustaldiak egin dituztenak\n"
	.string "pixka bat ikaratzen ditu.$"

gText_StartleAppealedBeforeUser::
	.string "Erabiltzailearen aurretik aritutako\n"
	.string "POKéMONa ikaratzen du.$"

gText_StartleAllAppealed::
	.string "Erakustaldia egin duten POKéMON\n"
	.string "guztiak ikaratzen ditu.$"

gText_BadlyStartleFrontMon::
	.string "Parean duen POKéMONa\n"
	.string "asko ikaratzen du.$"

gText_BadlyStartleAppealed::
	.string "Erakustaldiak egin dituztenak\n"
	.string "asko ikaratzen ditu.$"

gText_StartleAppealedBeforeUser2::
	.string "Erabiltzailearen aurretik aritutako\n"
	.string "POKéMONa ikaratzen du.$"

gText_StartleAllAppealed2::
	.string "Erakustaldia egin duten POKéMON\n"
	.string "guztiak ikaratzen ditu.$"

gText_ShiftJudgesAttentionFromOthers::
	.string "EPAILEAREN atentzioa besteengandik\n"
	.string "kentzen du.$"

gText_StartleMonHasJudgesAttention::
	.string "EPAILEAREN atentzioa duen\n"
	.string "POKéMONa ikaratzen du.$"

gText_JamOthersMissesTurn::
	.string "Besteak gogaitzen ditu, baina\n"
	.string "erakustaldi txanda bat galtzen da.$"

gText_StartleMonsMadeSameTypeAppeal::
	.string "Mota bereko erakustaldia egin\n"
	.string "duten POKéMONak ikaratzen ditu.$"

gText_BadlyStartleCoolAppeals::
	.string "Asko ikaratzen ditu KARISMA\n"
	.string "motako erakustaldia egin dutenak.$"

gText_BadlyStartleBeautyAppeals::
	.string "Asko ikaratzen ditu EDERTASUN\n"
	.string "motako erakustaldia egin dutenak.$"

gText_BadlyStartleCuteAppeals::
	.string "Asko ikaratzen ditu POLITA\n"
	.string "motako erakustaldia egin dutenak.$"

gText_BadlyStartleSmartAppeals::
	.string "Asko ikaratzen ditu ARGITASUN\n"
	.string "motako erakustaldia egin dutenak.$"

gText_BadlyStartleToughAppeals::
	.string "Asko ikaratzen ditu GOGORTASUN\n"
	.string "motako erakustaldia egin dutenak.$"

gText_MakeMonAfterUserNervous::
	.string "Erabiltzailearen osteko POKéMONa\n"
	.string "urduri jartzen du.$"

gText_MakeAllMonsAfterUserNervous::
	.string "Erabiltzailearen osteko POKéMON\n"
	.string "guztiak urduri jartzen ditu.$"

gText_WorsenConditionOfThoseMadeAppeals::
	.string "Erakustaldia egin dutenen\n"
	.string "egoera okertzen du.$"

gText_BadlyStartleMonsGoodCondition::
	.string "Egoera onean dauden POKéMONak\n"
	.string "ikaratzen ditu.$"

gText_AppealGreatIfPerformedFirst::
	.string "Oso ongi funtzionatzen du\n"
	.string "lehenengo erabiltzen bada.$"

gText_AppealGreatIfPerformedLast::
	.string "Oso ongi funtzionatzen du\n"
	.string "azkenengo erabiltzen bada.$"

gText_AppealAsGoodAsThoseBeforeIt::
	.string "Aurrekoena bezain erakustaldi\n"
	.string "ona egiten du.$"

gText_AppealAsGoodAsOneBeforeIt::
	.string "Aurrekoarena bezain erakustaldi\n"
	.string "ona egiten du.$"

gText_AppealBetterLaterItsPerformed::
	.string "Zenbat eta beranduago erabili\n"
	.string "orduan eta hobeto funtzionatzen du.$"

gText_AppealVariesDependingOnTiming::
	.string "Erabiltzen den momentuaren arabera\n"
	.string "aldatzen da erakustaldiaren maila.$"

gText_WorksWellIfSameTypeAsBefore::
	.string "Ondo funtzionatzen du aurreko\n"
	.string "erasoaren mota berdinekoa bada.$"

gText_WorksWellIfDifferentTypeAsBefore::
	.string "Ondo funtzionatzen du aurreko\n"
	.string "erasoaren mota desberdinekoa bada.$"

gText_AffectedByAppealInFront::
	.string "Aurreko erakustaldiaren kalitatearen\n"
	.string "arabera funtzionatzen du.$"

gText_UpsConditionHelpsPreventNervousness::
	.string "Erabiltzailearen egoera hobetzen du.\n"
	.string "Urduritasuna saihesten du.$"

gText_AppealWorksWellIfConditionGood::
	.string "Ondo funtzionatzen du erabiltzailearen\n"
	.string "egoera ona baldin bada.$"

gText_NextAppealMadeEarlier::
	.string "Hurrengo txandako erakustaldia\n"
	.string "lehenago egin daiteke.$"

gText_NextAppealMadeLater::
	.string "Hurrengo txandako erakustaldia\n"
	.string "beranduago egin daiteke.$"

gText_TurnOrderMoreEasilyScrambled::
	.string "Hurrengo txandako ordena nahasteko\n"
	.string "errazagoa bihurtzen da.$"

gText_ScrambleOrderOfNextAppeals::
	.string "Hurrengo txandako erakustaldien\n"
	.string "ordena aldatzen du.$"

gText_AppealExcitesAudienceInAnyContest::
	.string "Edozein TXAPELKETATAN publikoa\n"
	.string "animatzen du.$"

gText_BadlyStartlesMonsGoodAppeals::
	.string "Erakustaldi ona egin duten POKéMON\n"
	.string "guztiak asko ikaratzen ditu.$"

gText_AppealBestMoreCrowdExcited::
	.string "Hobe funtzionatzen du publikoa\n"
	.string "animatuta baldin badago.$"

gText_TemporarilyStopCrowdExcited::
	.string "Tarte batean ez dio publikoari\n"
	.string "animatzen uzten.$"

@ Unused move names

gText_RainDance::
	.string "EURI DANTZA$"

gText_Rage::
	.string "AMORRUA$"

gText_FocusEnergy::
	.string "ENERGIA FOKUA$"

gText_Hypnosis::
	.string "HIPNOSIA$"

gText_Softboiled::
	.string "AMORTIGUATZAILEA$"

gText_HornAttack::
	.string "ADAR ERASOA$"

gText_SwordsDance::
	.string "EZPATA DANTZA$"

gText_Conversion::
	.string "BIHURTZEA$"

gText_SunnyDay::
	.string "EGUN EGUZKITSUA$"

gText_Rest2::
	.string "ATSEDENA$"

gText_Vicegrip::
	.string "HELTZEA$"

gText_DefenseCurl::
	.string "DEFENTSA KIRRUA$"

gText_LockOn::
	.string "ITUA FINKATU$"

@ Contest type names

gContestMoveTypeCoolText::
	.string "KARISMA$"

gContestMoveTypeBeautyText::
	.string "EDERTASUNA$"

gContestMoveTypeCuteText::
	.string "POLITA$"

gContestMoveTypeSmartText::
	.string "AZKARRA$"

gContestMoveTypeToughText::
	.string "GOGORRA$"

gText_AppealNumWhichMoveWillBePlayed::
	.string "{STR_VAR_1}. erakustaldia!\n"
	.string "Zein eraso erabiliko da?$"

gText_AppealNumButItCantParticipate::
	.string "{STR_VAR_1}. erakustaldia!\n"
	.string "Baina ezin du parte hartu!$"

gText_MonAppealedWithMove::
	.string "{STR_VAR_1}(e)k {STR_VAR_2}\n"
	.string "erabili du!$"

gText_MonWasWatchingOthers::
	.string "{STR_VAR_1} besteei begira\n"
	.string "zegoen.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_AllOutOfAppealTime::
	.string "Erakustaldientzat denbora\n"
	.string "gabe geratu gara!{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

@ Unused appeal result texts

gText_ButAppealWasJammed::
	.string "Baina erakustaldia\n"
	.string "eten egin da.$"

gText_FollowedAnotherMonsLead::
	.string "Beste POKéMON bati\n"
	.string "jarraitu dio.$"

gText_ButItMessedUp::
	.string "Baina nahastu egin zen.$"

gText_WentBetterThanUsual::
	.string "Ohi baino hobeto joan\n"
	.string "da.$"

gText_JudgeLookedAwayForSomeReason::
	.string "EPAILEAK beste alde batera\n"
	.string "begiratu du zeozerengatik.$"

gText_WorkedHardToBuildOnPastMistakes::
	.string "Lan handia egin du lehengo\n"
	.string "akatsetatik ikasteko.$"

gText_CantMakeAnyMoreMoves::
	.string "Ezin du eraso gehiago\n"
	.string "erabili.$"

gText_WorkedFrighteninglyWell::
	.string "Izugarri ondo funtzionatu\n"
	.string "du.$"

gText_WorkedHardAsStandoutMon::
	.string "POKéMON esanguratsuenak bezain\n"
	.string "gogor egin du lan.$"

gText_JudgedLookedOnExpectantly::
	.string "EPAILEAK adi-adi begiratu\n"
	.string "du.$"

gText_WorkedRatherWell::
	.string "Nahiko ondo funtzionatu du.$"

gText_WorkedLittleBetterThanUsual::
	.string "Normalean baino hobeto\n"
	.string "funtzionatu du.$"

@ Round result texts

gText_MonFailedToStandOutAtAll::
	.string "{STR_VAR_1} ez du lortu\n"
	.string "inolako atentziorik ematerik…{PAUSE_UNTIL_PRESS}$"

gText_MonDidntStandOutVeryMuch::
	.string "{STR_VAR_1} ez du lortu\n"
	.string "atentzio gehiegi ematerik…{PAUSE_UNTIL_PRESS}$"

gText_MonCaughtALittleAttention::
	.string "{STR_VAR_1} atentzio pixka\n"
	.string "bat eman du.{PAUSE_UNTIL_PRESS}$"

gText_MonAttractedALotOfAttention::
	.string "{STR_VAR_1} atentzio asko\n"
	.string "eman du.{PAUSE_UNTIL_PRESS}$"

gText_MonCommandedTotalAttention::
	.string "{STR_VAR_1} atentzioa eman\n"
	.string "du guztiz.{PAUSE_UNTIL_PRESS}$"

gText_MonHasntMadeItsAppeal::
	.string "{STR_VAR_1} ez du bere\n"
	.string "erakustaldia egin.{PAUSE_UNTIL_PRESS}$"

@ Unused
gText_AnticipationSwelledForMonsAppealNext2::
	.string "Ikusleak {STR_VAR_1} ikusteko\n"
	.string "gogo handiz daude.$"

gText_EmptyContestString::
	.string "$"

gText_JudgesViewsOnMonHeldFirm::
	.string "EPAILEAK {STR_VAR_1}(r)engan\n"
	.string "zuen iritzia mantendu da.$"

gText_MonsXChangedPerceptions::
	.string "{STR_VAR_1}(r)en {STR_VAR_3}ek\n"
	.string "iritziak aldatu ditu.$"

gText_MonsAppealEffectWoreOff::
	.string "{STR_VAR_1}(r)en efektua\n"
	.string "agortu egin da.$"

gText_SpecialAppealsEffectWoreOff::
	.string "Efektu berezia\n"
	.string "agortu egin da.$"

gText_EveryonesAppealsMadeToLookSame::
	.string "Guztien erakustaldiek itxura\n"
	.string "berdina izan dute.$"

gText_CheapenedMonsAppeal::
	.string "{STR_VAR_2}(r)en erakustaldia\n"
	.string "kaskartu egin da.$"

gText_CheapenedAppealOfThoseAhead::
	.string "Ondorengoen erakustaldiak\n"
	.string "kaskartu egin dira.$"

gText_StoleAttentionAwayFromMon::
	.string "Atentzioa lapurtu dio\n"
	.string "{STR_VAR_2}(e)ri.$"

gText_CheapenedMonsAppeal2::
	.string "{STR_VAR_2}(r)en erakustaldia\n"
	.string "kaskartu egin da.$"

gText_SeverelyCheapenedOtherAppeals::
	.string "Beste erakustaldiak asko\n"
	.string "kaskartu ditu.$"

gText_AnticipationSwelledForMonsAppealNext::
	.string "{STR_VAR_1} ikusteko gogoa\n"
	.string "handitu egin da.$"

gText_CheapenedAppealOfThoseAhead2::
	.string "Ondorengoen erakustaldiak\n"
	.string "kaskartu egin dira.$"

gText_CheapenedJudgesFavoriteAppeal::
	.string "EPAILEAREN erakustaldi\n"
	.string "begikoena kaskartu du.$"

gText_AppealsOfOthersCheapenedByHalf::
	.string "Besteen erakustaldiak\n"
	.string "erdira kaskartu ditu.$"

gText_StoodOutToMakeUpForBeingJammed::
	.string "Erakustaldia eten egin dela\n"
	.string "konpontzeko asko nabaritu da.$"

gText_CantParticipateInAppealsAnyMore::
	.string "Ezin du erakustaldietan\n"
	.string "gehiago parte hartu.$"

gText_TouchedJudgeForFantasticAppeal::
	.string "EPAILEA hunkitu egin du\n"
	.string "erakustaldi itzela eginda.$"

gText_AnticipationRoseForUpcomingAppeals::
	.string "Hurrengo erakustaldiak ikusteko\n"
	.string "gogoa handitu da.$"

gText_StoodOutAsMuchAsSpecialAppeals::
	.string "Erakustaldi bereziek bezain\n"
	.string "ondo funtzionatu du.$"

gText_StoodOutAsMuchAsMon::
	.string "{STR_VAR_1}(e)k bezain\n"
	.string "ondo funtzionatu du.$"

gText_JammedAppealsMadeEvenLessNoticeable::
	.string "Etendako erakustaldiak are\n"
	.string "kaskarragoak bihurtu dira.$"

gText_EveryonesAppealsMadeSame::
	.string "Guztien erakustaldiek itxura\n"
	.string "berdina izan dute.$"

@ Appeal result texts

gText_BecameMoreConsciousOfOtherMons::
	.string "Beste POKÉMONEN presentzia\n"
	.string "areago nabaritu du.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonCantMakeAnAppealAfterThis::
	.string "{STR_VAR_1}(e)k ezingo du beste\n"
	.string "erakustaldi bat egin honen ostean.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_SettledDownJustLittleBit::
	.string "Pixka bat lasaitu\n"
	.string "da.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_BecameObliviousToOtherMons::
	.string "Beste POKéMONak hor zeudela\n"
	.string "ahaztu du.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_BecameLessAwareOfOtherMons::
	.string "Beste POKÉMONEN presentzia\n"
	.string "pixka bat gutxitu da.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_StoppedCaringAboutOtherMons::
	.string "Ez zaizkio jada beste\n"
	.string "POKéMONak horrenbeste axola.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_TriedToStartleOtherMons::
	.string "Beste POKéMONak ikaratzen\n"
	.string "saiatu da.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_TriedToDazzleOthers::
	.string "Besteak itsutzen saiatu\n"
	.string "da.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_JudgeLookedAwayFromMon::
	.string "EPAILEAK beste alde batera\n"
	.string "begiratu du, ez {STR_VAR_1}(e)ri.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_TriedToUnnerveNextMon::
	.string "Hurrengo POKéMONa urduritzen\n"
	.string "saiatu da.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonBecameNervous::
	.string "{STR_VAR_1} urduri jarri\n"
	.string "da.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_AppealTriedToUnnerveWaitingMons::
	.string "Itxaroten ari diren POKéMONak\n"
	.string "urduritzen saiatu da.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_TauntedMonsDoingWell::
	.string "Ondo zihoazen POKéMONei\n"
	.string "burla egin die.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonRegainedItsForm::
	.string "{STR_VAR_1} berriro sasoi\n"
	.string "onera bueltatu da.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_TriedToJamMonDoingWell::
	.string "Ondo zihoazen POKéMONak\n"
	.string "eteten saiatu da.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_StandoutMonHustledEvenMore::
	.string "Nabarmentzen ari zen {STR_VAR_1}\n"
	.string "are gehiago ahalegindu da.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_LargelyUnnoticedMonWorkedHard::
	.string "Nabarmentzen ari ez zen {STR_VAR_1}\n"
	.string "asko ahalegindu da.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_WorkedAsMuchAsMonBefore::
	.string "Bere aurreko POKÉMONEK bezain\n"
	.string "ondo funtzionatu du.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealDidNotGoWell::
	.string "{STR_VAR_1}(r)en erakustaldiak\n"
	.string "ez du ondo funtzionatu.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_WorkedAsMuchAsPrecedingMon::
	.string "Aurreko POKéMONak bezain\n"
	.string "ondo funtzionatu du.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealDidNotGoWell2::
	.string "{STR_VAR_1}(r)en erakustaldiak\n"
	.string "ez du ondo funtzionatu.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealDidNotGoWell3::
	.string "{STR_VAR_1}(r)en erakustaldiak\n"
	.string "ez du ondo funtzionatu.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealWentSlightlyWell::
	.string "{STR_VAR_1}(r)en erakustaldiak\n"
	.string "nahiko ondo funtzionatu du.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealWentPrettyWell::
	.string "{STR_VAR_1}(r)en erakustaldia\n"
	.string "nahiko ondo joan da.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealWentExcellently::
	.string "{STR_VAR_1}(r)en erakustaldiak\n"
	.string "bikain funtzionatu du.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealWasDud::
	.string "{STR_VAR_1}(r)en erakustaldiak\n"
	.string "huts egin du.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealDidNotWorkVeryWell::
	.string "{STR_VAR_1}(r)en erakustaldiak\n"
	.string "ez du oso ondo funtzionatu.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealWentSlightlyWell2::
	.string "{STR_VAR_1}(r)en erakustaldiak\n"
	.string "nahiko ondo funtzionatu du.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealWentPrettyWell2::
	.string "{STR_VAR_1}(r)en erakustaldia\n"
	.string "nahiko ondo joan da.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealWentVeryWell::
	.string "{STR_VAR_1}(r)en erakustaldiak\n"
	.string "oso ondo funtzionatu du.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealWentExcellently2::
	.string "{STR_VAR_1}(r)en erakustaldiak\n"
	.string "bikain funtzionatu du.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_SameTypeAsOneBeforeGood::
	.string "Aurreko POKéMONaren mota\n"
	.string "berdinekoa izan da. Ondo!{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_NotSameTypeAsOneBeforeGood::
	.string "Ez da aurrekoaren mota\n"
	.string "berdinekoa. Ondo!{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_StoodOutMuchMoreThanMonBefore::
	.string "Aurreko POKéMONak baino\n"
	.string "askoz itxura hobea izan du.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_DidntDoAsWellAsMonBefore::
	.string "Ez du aurreko POKéMONak\n"
	.string "bezain ondo egin.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsConditionRoseAboveUsual::
	.string "{STR_VAR_1}(r)en egoera\n"
	.string "normalean baino hobe dago.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsHotStatusMadeGreatAppeal::
	.string "{STR_VAR_1}(r)en egoera onari\n"
	.string "esker, erakustaldi bikaina izan da!{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MovedUpInLineForNextAppeal::
	.string "Posizio bat aurreratu da\n"
	.string "hurrengo txandarako.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MovedBackInLineForNextAppeal::
	.string "Posizio bat atzeratu da\n"
	.string "hurrengo txandarako.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_ScrambledUpOrderForNextTurn::
	.string "Hurrengo txandako ordena\n"
	.string "nahastu egin da.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_JudgeLookedAtMonExpectantly::
	.string "EPAILEAK irrikaz begiratu\n"
	.string "dio {STR_VAR_1}(e)ri.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_AppealComboWentOverWell::
	.string "Erakustaldi konboak\n"
	.string "ondo funtzionatu du.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_AppealComboWentOverVeryWell::
	.string "Erakustaldi konboak\n"
	.string "oso ondo funtzionatu du.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_AppealComboWentOverExcellently::
	.string "Erakustaldi konboak\n"
	.string "bikain funtzionatu du.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonManagedToAvertGaze::
	.string "{STR_VAR_1}(e)k beste aldera\n"
	.string "begiratzea lortu du.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonManagedToAvoidSeeingIt::
	.string "{STR_VAR_1}(e)k ez ikustea\n"
	.string "lortu du.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonIsntFazedByThatSortOfThing::
	.string "{STR_VAR_1} ez da horrelako\n"
	.string "gauzekin asaldatzen.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonBecameALittleDistracted::
	.string "{STR_VAR_1} pixka bat\n"
	.string "distraitu egin da.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_TriedToStartleOtherPokemon::
	.string "Beste POKéMONak ikaratzen\n"
	.string "saiatu da.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonLookedDownOutOfDistraction::
	.string "{STR_VAR_1}(e)k behera begiratu\n"
	.string "du, distraituta.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonTurnedBackOutOfDistraction::
	.string "{STR_VAR_1}(e)k buelta eman\n"
	.string "du, distraituta.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonCouldntHelpUtteringCry::
	.string "{STR_VAR_1}(e)k ezin izan dio\n"
	.string "eutsi negarrari.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonCouldntHelpLeapingUp::
	.string "{STR_VAR_1}(e)k ezin izan dio\n"
	.string "eutsi jauzi egiteari.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonTrippedOutOfDistraction::
	.string "{STR_VAR_1}(e)k estropezu egin\n"
	.string "du, distraituta.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonWasTooNervousToMove::
	.string "{STR_VAR_1} urduriegi dago\n"
	.string "mugitzeko.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_ButItMessedUp2::
	.string "Baina nahastu egin zen.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_ButItFailedToMakeTargetNervous::
	.string "Baina ez du lortu helburua\n"
	.string "urduri jartzea.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_ButItFailedToMakeAnyoneNervous::
	.string "Baina ez du lortu inor\n"
	.string "urduri jartzea.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_ButItWasIgnored::
	.string "Baina ez diote kasurik egin…{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_CouldntImproveItsCondition::
	.string "Baina ez du lortu bere\n"
	.string "egoera hobetzea…{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_BadConditionResultedInWeakAppeal::
	.string "Bere egoera eskasarengatik\n"
	.string "erakustaldi kaskarra egin du.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonWasUnaffected::
	.string "{STR_VAR_1}(e)ri ez dio\n"
	.string "eragin.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_RepeatedAppeal::
	.string "{STR_VAR_1}(e)k gaizki egin\n"
	.string "du erakustaldia errepikatuz.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonsXWentOverGreat::
	.string "{STR_VAR_1}(r)en {STR_VAR_3}\n"
	.string "ederki joan da.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonsXDidntGoOverWell::
	.string "{STR_VAR_1}(r)en {STR_VAR_3}\n"
	.string "ez da oso ondo joan…{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonsXGotTheCrowdGoing::
	.string "{STR_VAR_1}(r)en {STR_VAR_3}(e)k\n"
	.string "publikoa animatu du.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonCantAppealNextTurn::
	.string "{STR_VAR_1} ezingo da hurrengo\n"
	.string "txandan aritu…{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_AttractedCrowdsAttention::
	.string "Publikoaren atentzioa\n"
	.string "eman du.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_CrowdContinuesToWatchMon::
	.string "Publikoak {STR_VAR_3}(e)ri\n"
	.string "begira jarraitzen du.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonsMoveIsIgnored::
	.string "Ez diote kasurik egin\n"
	.string "{STR_VAR_1}(r)en {STR_VAR_2}(e)ri.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_Contest_Shyness::
	.string "lotsa$"

gText_Contest_Anxiety::
	.string "antsietatea$"

gText_Contest_Laziness::
	.string "alferkeria$"

gText_Contest_Hesitancy::
	.string "zalantza$"

gText_Contest_Fear::
	.string "ikara$"

gText_Contest_Coolness::
	.string "karisma$"

gText_Contest_Beauty::
	.string "edertasua$"

gText_Contest_Cuteness::
	.string "polita$"

gText_Contest_Smartness::
	.string "argitasuna$"

gText_Contest_Toughness::
	.string "gogortasuna$"

@ Unused
gText_Tension::
	.string "TENTSIOA$"

gText_CoolMove::
	.string "Eraso KARISMADUNA$"

gText_BeautyMove::
	.string "Eraso EDERRA$"

gText_CuteMove::
	.string "Eraso POLITA$"

gText_SmartMove::
	.string "Eraso AZKARRA$"

gText_ToughMove::
	.string "Eraso GOGORRA$"

gText_3QuestionMarks::
	.string "???$"
