gContestHallPaintingCaption::
	.string "{STR_VAR_1}\n"
	.string "{STR_VAR_2}(r)en {STR_VAR_3}$"

@ Unused
gContestPaintingContest::
	.string "TXAPELKETA$"

gContestRankNormal::
	.string "MAILA NORMALA$"

gContestRankSuper::
	.string "SUPER MAILA$"

gContestRankHyper::
	.string "HYPER MAILA$"

gContestRankMaster::
	.string "MASTER MAILA$"

gContestLink::
	.string "LOTURA$"

gContestCoolness::
	.string "KARISMA$"

gContestBeauty::
	.string "EDERTASUNA$"

gContestCuteness::
	.string "POLITASUNA$"

gContestSmartness::
	.string "ARGITASUNA$"

gContestToughness::
	.string "INDARRA$"

gContestPaintingCool1::
	.string "Beti ere super karismatiko--\n"
	.string "{STR_VAR_1} paregabea$"

gContestPaintingCool2::
	.string "Ene, kaixo!\n"
	.string "{STR_VAR_1} POKéMON eder hori$"

gContestPaintingCool3::
	.string "{STR_VAR_1} miragarri, izugarri\n"
	.string "eta itzela$"

gContestPaintingBeauty1::
	.string "Mende honetako azken Venusa--\n"
	.string "{STR_VAR_1} ederra$"

gContestPaintingBeauty2::
	.string "{STR_VAR_1}(r)en irribarre,\n"
	.string "distiratsu eta liluragarria$"

gContestPaintingBeauty3::
	.string "POKéMON ZENTROKO super idoloa--\n"
	.string "{STR_VAR_1} paregabea$"

gContestPaintingCute1::
	.string "{STR_VAR_1} maitagarri eta goxoa$"

gContestPaintingCute2::
	.string "{STR_VAR_1} ederraren\n"
	.string "erretratu garailea$"

gContestPaintingCute3::
	.string "Egin keinutxo bat!\n"
	.string "{STR_VAR_1}, POKéMON politena$"

gContestPaintingSmart1::
	.string "Azkartasunaren maisua--\n"
	.string "{STR_VAR_1} POKéMON jakintsua$"

gContestPaintingSmart2::
	.string "{STR_VAR_1}--POKéMON guztien\n"
	.string "gainetik aukeratutakoa$"

gContestPaintingSmart3::
	.string "{STR_VAR_1} bikainaren\n"
	.string "dotorezia gorena$"

gContestPaintingTough1::
	.string "{STR_VAR_1} gihartsu,\n"
	.string "indartsu, azkarra$"

gContestPaintingTough2::
	.string "{STR_VAR_1} indartsu,\n"
	.string "indartsuago eta indartsuena$"

gContestPaintingTough3::
	.string "Izugarri ahaltsua,\n"
	.string "{STR_VAR_1} hiper POKéMONa$"
