EventTicket_Text_ShowOldSeaMap:
	.string "PORTUONDOra doan ferria…\p"
	.string "Barkatu?\n"
	.string "Mapako toki honetara joan al gaitezke?\p"
	.string "Badakit nork lagundu diezazukeen.\n"
	.string "Itxaron, mesedez.$"

EventTicket_Text_ThatPass:
	.string "PORTUONDOra doan ferria…\p"
	.string "Nola?\n"
	.string "TXARTEL hori…$"

EventTicket_Text_ShowEonTicket:
	.string "Ei, txo, zu al zara TXARTEL\n"
	.string "zahar hori ekarri duena?\p"
	.string "Entzun, bada, hegoalderantz pikutan dagoen\n"
	.string "irla txiki batera joan nahi duzu.\p"
	.string "Inork ez daki zer aurkituko dugun\n"
	.string "behin horra iritsita, txo.\l"
	.string "A zer ikara!\p"
	.string "Denak ontzira!$"

EventTicket_Text_SouthernIslandSailBack:
	.string "Ei, txo, hemen ez dago egiteko\n"
	.string "ezertxo ere, irla ñimiño honetan.\p"
	.string "Zer iruditzen UR-LILIRA bueltatzen bagara?$"

EventTicket_Text_SailHome:
	.string "Ondo, orduan, txo!\n"
	.string "Guazen ba etxera bueltan!$"

EventTicket_Text_AsYouLike:
	.string "Ondo ba, txo, nahi bezala.$"

SouthernIsland_Interior_Text_Sign:
	.string "“Ametsak beste errealitate bat dira,\n"
	.string "ez beste. Ez ahantzi…”$"

SouthernIsland_Exterior_Text_Sign:
	.string "“Memoriak ahanzten dituztenak, hauek\n"
	.string "bihotzean grabatzen saiatzen dira…”$"
