EventTicket_Text_OldSeaMapTooFar:
	.string "Zer dionk, gazte?\p"
	.string "Hik omen daukank mapa zaharren\n"
	.string "bat edo halako zeozer?\p"
	.string "Ea ba, zer ote den.\n"
	.string "… … … … … …\p"
	.string "Ene, hau urruti asko zagonk.\n"
	.string "Nik ezin di(n)at lagundu hiri ba…$"

EventTicket_Text_BrineyHoldOnASecond:
	.string "BRINEY: Momentu bat!\p"
	.string "Nola esan diozu ezeztz horrenbeste\n"
	.string "zor diodan bati?$"

EventTicket_Text_BrineyLetsSail:
	.string "{PLAYER}{KUN}, Barkatu, barkatu.\p"
	.string "Nire laguntza bila etorri,\n"
	.string "eta ia pikutara bidali zaitugu.\p"
	.string "Nik lagunduko dizut, lasai.\p"
	.string "Oraintxe aterako gara, bai horixe!\p"
	.string "Goazen ITSASO ZAHARREKO MAPAN\n"
	.string "agertzen den irlaren bila!$"

EventTicket_Text_OddTicketGetOnBoard:
	.string "Zu al zara tiket arraro hori\n"
	.string "ekarri duena?\p"
	.string "Joan nahi duzun lekua oso-oso\n"
	.string "urruti dagoen irla bat da.\p"
	.string "Inork ez daki zer dagoen bertan…\p"
	.string "Pentsatzeak bakarrik zoratu egiten\n"
	.string "du ni bezalako marinel bat!\p"
	.string "Igo ontzira, gazte!$"

FarawayIsland_Entrance_Text_SailorReturn:
	.string "BRINEY oso aldakorra da, erotu\n"
	.string "egiten nau askotan…\p"
	.string "UR-LILIRA bueltatu nahi al duzu?$"

BirthIsland_Harbor_Text_SailorReturn:
	.string "Zer forma arraroa duen irlak, ezta?\n"
	.string "UR-LILIRA bueltatu nahi al duzu?$"

EventTicket_Text_OddTicketsWhereTo:
	.string "Zu al zara tiket arraro horiek\n"
	.string "Ekarri dituena?\p"
	.string "… … …Hm.\p"
	.string "Tiket hauekin urrun-urrun dauden\n"
	.string "irla batzuetara iritsiko zara.\p"
	.string "Inork ez dako zer dagoen bertan,\n"
	.string "edo zer gertatu daitekeen.\p"
	.string "Pentsatzeak bakarrik zoratu egiten\n"
	.string "du ni bezalako marinel bat!\p"
	.string "Igo ontzira, gazte!\n"
	.string "Nora joango gara lehenengo?$"

NavelRock_Harbor_Text_SailorReturn:
	.string "Zuk ere… Entzun duzu hori?\n"
	.string "Hor sakonetik datorren marmar hori.\p"
	.string "Segurua izango al da hurbiltzea?\n"
	.string "Hemendik joan beharko ginateke, ezta?$"

FarawayIsland_Entrance_Text_Sign:
	.string "Hitzak erdi-ezabatuta daude,\n"
	.string "aspaldikoak balira bezala…\p"
	.string "“…ila, 6garren eguna\n"
	.string "Gizaki bat…hona agertzen bada…\l"
	.string "berriro…an bedi bihotz-oneko perts…\l"
	.string "…rren esperoan, bano…”$"

FarawayIsland_Interior_Text_Mew:
	.string "Myuu…$"
