@ Battle Tower
gText_AnabelWonSilver::
	.string "Oso etsigarria da…$"

gText_AnabelDefeatSilver::
	.string "Ados, ulertuta…$"

gText_AnabelWonGold::
	.string "Asko sentitzen dut…$"

gText_AnabelDefeatGold::
	.string "Eskerrik asko…$"

@ Battle Dome
gText_TuckerWonSilver::
	.string "Kar-kar-kar! Ez al zara lotsatzen?\n"
	.string "Mundu guztia begira dago!$"

gText_TuckerDefeatSilver::
	.string "Grr…\n"
	.string "Baina nola…$"

gText_TuckerWonGold::
	.string "DOMOKO TXAPELDUN titulua ez da inolako txantxa!$"

gText_TuckerDefeatGold::
	.string "Kar-kar-kar!\n"
	.string "Txundigarria zara, gero!$"

@ Battle Factory
gText_NolandWonSilver::
	.string "Hori bai itzela!\n"
	.string "Ikasketa ona izan da, ezta?$"

gText_NolandDefeatSilver::
	.string "Oso ondo!\n"
	.string "Zuk badakizu zertan zabiltzan!$"

gText_NolandWonGold::
	.string "Aizu, aizu, aizu!\n"
	.string "Bukatu duzu jada ala?$"

gText_NolandDefeatGold::
	.string "Zer gertatu da hemen?$"

@ Battle Pike
gText_LucyWonSilver::
	.string "Humph…$"

gText_LucyDefeatSilver::
	.string "Ene…$"

gText_LucyWonGold::
	.string "Hah!$"

gText_LucyDefeatGold::
	.string "Kaka!$"

@ Battle Arena
gText_GretaWonSilver::
	.string "Aizu, baina zer uste duzu?\n"
	.string "Gogorrago saiatu beharko duzu!$"

gText_GretaDefeatSilver::
	.string "Nola ba!\n"
	.string "Zorionak!$"

gText_GretaWonGold::
	.string "Aja!\n"
	.string "Zer uste zenuen, bada?$"

gText_GretaDefeatGold::
	.string "Nola?\n"
	.string "Serio al zabiltza?!$"

@ Battle Palace
gText_SpenserWonSilver::
	.string "Zure POKéMONak ahulak dira zu ere\n"
	.string "ENTRENATZAILE ahula zarelako!$"

gText_SpenserDefeatSilver::
	.string "Ah…\n"
	.string "Hau beste zerbait da…$"

gText_SpenserWonGold::
	.string "Kar-kar-kar!\n"
	.string "Lagunok, ez izan beldurrik!$"

gText_SpenserDefeatGold::
	.string "Uaaaa!\n"
	.string "Kar-kar-kar!$"

@ Battle Pyramid
gText_BrandonWonSilver::
	.string "Aizu, zer gertatzen zaizu!\n"
	.string "Gehiago saiatu behar duzu! Altxa!$"

gText_BrandonDefeatSilver::
	.string "Hori da! Ederki ibili zara!\n"
	.string "Lan gogorra egin duzu honetarako!$"

gText_BrandonWonGold::
	.string "Aizu! Ez errenditu!\n"
	.string "Altxa! Ez galdu fedea!$"

gText_BrandonDefeatGold::
	.string "Hori da! Lortu duzu!\n"
	.string "Lan eta lan ibili zara hau lortzeko!$"
