LilycoveCity_DepartmentStore_1F_Text_LotteryCornerDrawTicket:
	.string "Hau POKéMON LOTERIA TXOKOA da.\p"
	.string "Gure SALTOKIGUNEKO bezeroek POKéMON\n"
	.string "LOTERIAKO TIKET bat atera dezakete.\p"
	.string "LOTERIAKO TIKETEKO zenbakiak zure\n"
	.string "edozein POKéMONEN ID berdina badu,\l"
	.string "opari izugarri bat jasoko duzu.\p"
	.string "Nahi duzu POKéMON LOTERIAKO TIKET\n"
	.string "bat atera?$"

LilycoveCity_DepartmentStore_1F_Text_ComeBackTomorrow:
	.string "Itzuli bihar, mesedez.$"

LilycoveCity_DepartmentStore_1F_Text_PleaseVisitAgain:
	.string "Berriz etorriko zarela espero dugu.$"

LilycoveCity_DepartmentStore_1F_Text_PleasePickTicket:
	.string "Mesedez aukeratu LOTERIAKO TIKET Bat.\n"
	.string "…{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}…{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}…{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

LilycoveCity_DepartmentStore_1F_Text_TicketNumberIsXPleaseWait:
	.string "LOTERIAKO TIKETAREN zenbakia {STR_VAR_1} da.\p"
	.string "Zure POKéMONEN baten IDaren berdina\n"
	.string "den begiratzeko momentu bat behar\l"
	.string "dut. Itxaron, mesedez.$"

LilycoveCity_DepartmentStore_1F_Text_TicketMatchesPartyMon:
	.string "Zorionak!\p"
	.string "Zure taldeko {STR_VAR_1} POKéMONAK\n"
	.string "LOTERIAKO TIKETEKO zenbakiaren\l"
	.string "ID berdina dauka!$"

LilycoveCity_DepartmentStore_1F_Text_TicketMatchesPCMon:
	.string "Zorionak!\p"
	.string "Zure ordenagailuko {STR_VAR_1} POKéMONAK\n"
	.string "LOTERIAKO TIKETEKO zenbakiaren\l"
	.string "ID berdina dauka!$"

LilycoveCity_DepartmentStore_1F_Text_NoNumbersMatched:
	.string "Sentitzen dut.\n"
	.string "Zenbakiak ez du bat egin.$"

LilycoveCity_DepartmentStore_1F_Text_TwoDigitsMatched:
	.string "Bi digituk bat egin dute,\n"
	.string "hirugarren saria lortu duzu!\l"
	.string "{STR_VAR_1} bat irabazi duzu!$"

LilycoveCity_DepartmentStore_1F_Text_ThreeDigitsMatched:
	.string "Hiru digituk bat egin dute,\n"
	.string "bigarren saria lortu duzu!\l"
	.string "{STR_VAR_1} bat irabazi duzu!$"

LilycoveCity_DepartmentStore_1F_Text_FourDigitsMatched:
	.string "Lau digituk bat egin dute,\n"
	.string "lehenengo saria lortu duzu!\l"
	.string "{STR_VAR_1} bat irabazi duzu!$"

LilycoveCity_DepartmentStore_1F_Text_AllFiveDigitsMatched:
	.string "Jainko maitea, bost digituek\n"
	.string "bat egin dute!\p"
	.string "Sari nagusia irabazi duzu!\n"
	.string "{STR_VAR_1} bat irabazi duzu!$"

LilycoveCity_DepartmentStore_1F_Text_NoRoomForThis:
	.string "Nola?\n"
	.string "Badirudi ez duzula lekurik honentzat.\p"
	.string "Mesedez, egin tokia POLTSAN eta itzuli\n"
	.string "sariaren bila.$"

LilycoveCity_DepartmentStore_1F_Text_PrizeWeveBeenHolding:
	.string "{PLAYER}?\n"
	.string "Bai, zure zain egon naiz.\p"
	.string "Hementxe dago zuretzat gorde\n"
	.string "dudan saria.$"

LilycoveCity_DepartmentStore_1F_Text_PleaseVisitAgain2:
	.string "Berriz etorriko zarela espero dugu.$"
