MatchCall_WildBattleText1::
	.string "Kaixo! {PLAYER}{KUN}, aupa!\n"
	.string "{STR_VAR_1} naiz.\p"
	.string "{STR_VAR_2} bat ikusi nuen behin\n"
	.string "baina ezin izan nuen harrapatu.\p"
	.string "Ia-ia lortu nuen alabaina!\n"
	.string "Bueno, hurrengora arte!$"

MatchCall_WildBattleText2::
	.string "Kaixo, {PLAYER}{KUN}.\n"
	.string "{STR_VAR_1} naiz.\p"
	.string "{STR_VAR_2} eder bat harrapatzen\n"
	.string "saiatu nintzen behin.\p"
	.string "Baina ihes egin zidan.\n"
	.string "Lur jota geratu nintzen!\p"
	.string "Bueno, aio!$"

MatchCall_WildBattleText3::
	.string "Aupa, {PLAYER}!\n"
	.string "Ni naiz, {STR_VAR_1}.\p"
	.string "Oraintxe saiatu naiz {STR_VAR_2}\n"
	.string "bat harrapatzen, baina ihes egin du.\p"
	.string "Hurbil ibili naiz ordea!\p"
	.string "Eguna izorratu dit…\n"
	.string "Ederki, ondo segi!$"

MatchCall_WildBattleText4::
	.string "Aizu, {PLAYER}{KUN}.\n"
	.string "{STR_VAR_1} naiz.\p"
	.string "Ezagutzen duzu {STR_VAR_2} POKéMONa?\n"
	.string "Ia-ia bat harrapatu dut.\p"
	.string "Duela gutxi izan da.\n"
	.string "Uste nuen lortu nuela, baina ihes egin du.\p"
	.string "Berriro ikusten badut, orduan ziur\n"
	.string "harrapatuko dudala.\p"
	.string "Bueno, laister arte.$"

MatchCall_WildBattleText5::
	.string "Kaixo-kaixo, {PLAYER}{KUN}!\n"
	.string "{STR_VAR_1} naiz.\l"
	.string "Harrapatu duzu POKéMONik azkenaldian?\p"
	.string "Duela pixka bat bat harrapatzera\n"
	.string "iritsi nintzen ia, baina ihes egin zuen.\p"
	.string "Ongi, zaindu zaitez!$"

MatchCall_WildBattleText6::
	.string "Aizu, {PLAYER}{KUN}.\n"
	.string "{STR_VAR_1} naiz.\l"
	.string "Harrapatu duzu POKéMONik azkenaldian?\p"
	.string "AUrrekoan bat neureganatu nuen ia-ia.\n"
	.string "Baina nolabait ihes egin zuen.\p"
	.string "Zaindu zaitez.$"

MatchCall_WildBattleText7::
	.string "…Emm, {PLAYER}{KUN}?\n"
	.string "{STR_VAR_1} naiz.\p"
	.string "Segundu bat! Itxaron!\n"
	.string "Harrapatu dezaket {STR_VAR_2} hau…\p"
	.string "Aaarrrgh! Ihes egin du!\n"
	.string "Baina, barruan zegoen eta!$"

MatchCall_WildBattleText8::
	.string "Oh, {PLAYER}{KUN}, zer moduz?\n"
	.string "{STR_VAR_1} naiz ni.\p"
	.string "Azkenaldian lortu al duzu\n"
	.string "POKéMONik harraptzea?\p"
	.string "Duela ez hainbeste ia-ia bat lortu\n"
	.string "nuen, baina ihes egin zidan azkenean.\p"
	.string "Gehiago saiatu beharko dut!\n"
	.string "Hurrengora arte!$"

MatchCall_WildBattleText9::
	.string "Oh, {PLAYER}{KUN}, kaixo!\n"
	.string "{STR_VAR_1} naiz!\p"
	.string "Ari al zara gero eta POKéMON\n"
	.string "gehiago biltzen?\p"
	.string "Ni ez naiz ari ondo azkenaldian!\n"
	.string "Denek ihes egiten didate!\p"
	.string "Aio, laister arte!$"

MatchCall_WildBattleText10::
	.string "Oh, {PLAYER}{KUN}, kaixo…\n"
	.string "{STR_VAR_1} naiz.\p"
	.string "Begira, aurrekoan kasik harrapatu\n"
	.string "nuen {STR_VAR_2} bat…\p"
	.string "Baina ziztu batean ihes egin zuen…\p"
	.string "Gehiago saiatu beharko naiz.\n"
	.string "Ondo segi.$"

MatchCall_WildBattleText11::
	.string "Ah, {PLAYER}{KUN}.\n"
	.string "Ni {STR_VAR_1} naiz.\l"
	.string "Zer moduz zaude?\p"
	.string "{STR_VAR_2} basati bat harrapatzen\n"
	.string "saiatu naiz lehen, baina ihes egin dit.\p"
	.string "Garaitua sentitzen naiz…$"

MatchCall_WildBattleText12::
	.string "Kaixo, {PLAYER}{KUN}.\n"
	.string "Ni naiz, {STR_VAR_1}.\l"
	.string "Oraindik POKéMONak harrapatzen a dituzu?\p"
	.string "Ni azkenaldian aritu naiz hauek\n"
	.string "harrapatzen saiatzen, baina ez da erraza.\p"
	.string "POKéMONak zientzia sakona dira, gero!$"

MatchCall_WildBattleText13::
	.string "Ah, kaixo, {PLAYER}{KUN}!\n"
	.string "{STR_VAR_1} naiz!\l"
	.string "POKéMONak harrapatzen aritu al zara?\p"
	.string "NI neu saiatu naiz hauek harrapatzen\n"
	.string "baina ez dut ezer askorik lortu.\p"
	.string "POKéMONak zientzia sakona dira, gero!$"

MatchCall_WildBattleText14::
	.string "Aupa, {PLAYER}{KUN}, zelan?\n"
	.string "{STR_VAR_1} naiz.\p"
	.string "Justu oraintxe, {STR_VAR_2} polit\n"
	.string "bat harraptzen saiatu naiz.\p"
	.string "Ihes egin du, ordea!\n"
	.string "Ene, ez dakizu nolako etsipena!\p"
	.string "Aio-aio!$"

MatchCall_WildBattleText15::
	.string "Aizu, {PLAYER}!\n"
	.string "{STR_VAR_1} naiz!\p"
	.string "POKéMON batzuk harrapatzea pentsatzen\n"
	.string "aritu naiz azkenaldian.\p"
	.string "Baina ez dut bat bera ere aurkitzen.\n"
	.string "A zer nolako misterioa!\p"
	.string "Guztiz harrituta nago!\n"
	.string "Ondo ibili!$"

MatchCall_NegativeBattleText1::
	.string "Epa! {PLAYER}{KUN}, kaixo!\n"
	.string "{STR_VAR_1} naiz.\p"
	.string "ENTRENATZAILE baten aurka borrokatu\n"
	.string "dut, baina galdu egin dut.\p"
	.string "A zer nolako zapuztua.\n"
	.string "Bueno, laister arte!$"

MatchCall_NegativeBattleText2::
	.string "Kaixo, {PLAYER}{KUN}.\n"
	.string "{STR_VAR_1} naiz.\p"
	.string "Gure borrokaren ostean beste baten\n"
	.string "aurka borrokatu nuen.\p"
	.string "Hurbil egon nitzen, baina azkenean\n"
	.string "galdu egin nuen. Zer pena!$"

MatchCall_NegativeBattleText3::
	.string "Aupa kaixo, {PLAYER}!\n"
	.string "Ni naiz, {STR_VAR_1}.\p"
	.string "Borroka batean zapaldu berri naute.\p"
	.string "Nire taldea hobetu beharrean\n"
	.string "nago, alajaina!$"

MatchCall_NegativeBattleText4::
	.string "Iepa, {PLAYER}.\n"
	.string "{STR_VAR_1} naiz.\p"
	.string "Atzo beste borroka bat egin nuen,\n"
	.string "baina ez nuen irabaztea lortu.\p"
	.string "Taldea hobetu behar dut.\n"
	.string "Beno, gero arte.$"

MatchCall_NegativeBattleText5::
	.string "Kaixo kaixo, {PLAYER}!\n"
	.string "{STR_VAR_1} naiz.\p"
	.string "Zer moduz zabiltza?\p"
	.string "Ni borrokan nabil buru-belarri,\n"
	.string "baina ez dut askotan irabazi.\p"
	.string "Ez dakit zer egin.\n"
	.string "Beno, laister arte!$"

MatchCall_NegativeBattleText6::
	.string "Iepa, {PLAYER}.\n"
	.string "{STR_VAR_1} naiz.\p"
	.string "Zer moduz zabiltza?\p"
	.string "Ni borrokan nabil gogor,\n"
	.string "baina zorte gutxirekin.\p"
	.string "Ez diot erritmoa harrapatzen, dirudienez.\n"
	.string "Zaindu zaitez.$"

MatchCall_NegativeBattleText7::
	.string "{STR_VAR_1} naiz.\n"
	.string "Zer moduz azkenaldian?\p"
	.string "Atzo borroka bat galdu nuen\n"
	.string "eta horretan pentsatzen aritu naiz.\p"
	.string "Planen bat prestatu behar dut…\n"
	.string "Agur.$"

MatchCall_NegativeBattleText8::
	.string "Oh, {PLAYER}{KUN}, zelan zabiltza?\n"
	.string "Ni {STR_VAR_1} naiz.\p"
	.string "Zelan daude zure POKéMONak?\n"
	.string "Aurrekoan borroka bat galdu nuen.\p"
	.string "Gogorrago saiatu beharko dut!\n"
	.string "Ikusi arte!$"

MatchCall_NegativeBattleText9::
	.string "Oh, {PLAYER}{KUN}, kaixo!\n"
	.string "{STR_VAR_1} naiz!\p"
	.string "Entzun, entzun, gauza bat kontatu\n"
	.string "behar dizut!\p"
	.string "POKéMON borroka bat izan dut lehen,\n"
	.string "baina azken segunduan galdu dut.\p"
	.string "Oh, zelako amorrua!$"

MatchCall_NegativeBattleText10::
	.string "Oh, {PLAYER}{KUN}, kaixo…\n"
	.string "{STR_VAR_1} naiz.\p"
	.string "Duela gutxi borroka bat izan dut.\n"
	.string "Galdu egin dut, ordea.\p"
	.string "Nire POKéMONak gehiago hazi behar ditut.\n"
	.string "Ondo segi.$"

MatchCall_NegativeBattleText11::
	.string "Ah, {PLAYER}{KUN}.\n"
	.string "{STR_VAR_1} naiz.\l"
	.string "Zer moduz zure POKéMONak?\p"
	.string "Beste borroka bat galdu berri dut nik.\p"
	.string "Beno, ikusi arte!$"

MatchCall_NegativeBattleText12::
	.string "Kaixo, {PLAYER}{KUN}.\n"
	.string "Ni naiz, {STR_VAR_1}.\l"
	.string "Oraindik borrokekin buru-belarri?\p"
	.string "Nik duela gutxi galdu egin dut, beraz,\n"
	.string "nire taldea entrenatzen aritu naiz.\p"
	.string "Hurrengora arte.$"

MatchCall_NegativeBattleText13::
	.string "Ah, kaixo, {PLAYER}{KUN}!\n"
	.string "{STR_VAR_1} naiz!\p"
	.string "Ondo ibili zarela espero dut.\p"
	.string "Duela ez hainbeste borroka batean\n"
	.string "izan naiz.\p"
	.string "{PLAYER}{KUN}, saiatu zu ere aktibo izaten.\n"
	.string "Ikusi arte!$"

MatchCall_NegativeBattleText14::
	.string "Oh, aupa, {PLAYER}{KUN}.\n"
	.string "{STR_VAR_1} naiz.\p"
	.string "Ondo al zabiltza?\p"
	.string "Batzuetan etxera bueltatu behar zenuke,\n"
	.string "nire iritziz.\p"
	.string "Aio-aio!$"

MatchCall_PositiveBattleText1::
	.string "Epa! {PLAYER}{KUN}, kaixo!\n"
	.string "{STR_VAR_1} naiz!\p"
	.string "Beste ENTRENATZAILE baten aurka egin dut.\n"
	.string "Irabazi egin dut! Irabazi egin dut!\p"
	.string "Nire {STR_VAR_2} topera ibili da.\n"
	.string "Ez dakizu zeinen pozik nagoen!$"

MatchCall_PositiveBattleText2::
	.string "Kaixo, {PLAYER}{KUN}!\n"
	.string "{STR_VAR_1} naiz!\p"
	.string "Atzo borroka bat izan nuen eta\n"
	.string "irabazi egin nuen! Izugarria izan zen!$"

MatchCall_PositiveBattleText3::
	.string "Kaixo, {PLAYER}!\n"
	.string "Ni naiz, {STR_VAR_1}!\l"
	.string "Zer moduz doaz zure borrokak?\p"
	.string "Nik aurreko batean borroka bat izan nuen,\n"
	.string "eta nire {STR_VAR_2} izugarri ondo aritu zen!\p"
	.string "Hurrengoan zure aurka borrokatzen dudanean,\n"
	.string "{PLAYER}, ez dut galduko, ez horixe!$"

MatchCall_PositiveBattleText4::
	.string "Epa, {PLAYER}.\n"
	.string "{STR_VAR_1} naiz.\p"
	.string "Borroka bat izan dut lehen.\n"
	.string "Irabazi egin dut, baina oso justu.\p"
	.string "Nire {STR_VAR_2} asko saiatu da eta\n"
	.string "borroka inspiragarria egin du.$"

MatchCall_PositiveBattleText5::
	.string "Apakaixo, {PLAYER}{KUN}!\n"
	.string "{STR_VAR_1} naiz.\p"
	.string "Zer moduz zabiltza?\n"
	.string "Borrokaz borroka?\p"
	.string "ba nik justu bat irabazi dut!\n"
	.string "Nire {STR_VAR_2} bikain ibili da!\p"
	.string "Hurrengoan zuri irabaziko dizut,\n"
	.string "ikusiko duzu! Ongi bada, zaindu zaitez!$"

MatchCall_PositiveBattleText6::
	.string "Ei, {PLAYER}{KUN}.\n"
	.string "{STR_VAR_1} naiz.\p"
	.string "Zer moduz?\p"
	.string "Ni nire momentu onenean nago.\n"
	.string "Borroka bat irabazi berri dut eta.\p"
	.string "Zure aurka borrokatzen dudanean,\n"
	.string "ziur nago ez dudala galduko!$"

MatchCall_PositiveBattleText7::
	.string "{PLAYER}{KUN}?\n"
	.string "{STR_VAR_1} naiz.\p"
	.string "Nire {STR_VAR_2} oso indartsua da!\n"
	.string "Beste borroka bat irabazten lagundu dit!\p"
	.string "Zure kontra errebantxa bat izateko\n"
	.string "gogo handia dut.$"

MatchCall_PositiveBattleText8::
	.string "Oh, {PLAYER}{KUN}, zelan?\n"
	.string "Ni {STR_VAR_1} naiz.\p"
	.string "Espero dut ondo zabiltzala.\n"
	.string "Irabazi berri dudala esan nahi nizun.\p"
	.string "Nire {STR_VAR_2} bereziki gogor saiatu\n"
	.string "da borroka irabazteko.\p"
	.string "Beste batera arte!$"

MatchCall_PositiveBattleText9::
	.string "Oh, {PLAYER}{KUN}, kaixo!\n"
	.string "{STR_VAR_1} naiz ni!\p"
	.string "Zer moduz zure POKéMONak?\n"
	.string "Nireek oraintxe irabazi dute borroka bat!\p"
	.string "Nire {STR_VAR_2} ikusgarria izan da,\n"
	.string "esan behar dut!\p"
	.string "Zuk ikusi izana gustatuko zitzaidan!\n"
	.string "Hurrengora arte!$"

MatchCall_PositiveBattleText10::
	.string "Oh, {PLAYER}{KUN}, kaixo…\n"
	.string "{STR_VAR_1} naiz.\p"
	.string "Zer berri, zer moduz bizitza?\p"
	.string "Nire POKéMONak energiaz beteta daudela\n"
	.string "dirudi.\p"
	.string "Borroka bat irabazi berri dut beraiekin.\n"
	.string "Ondo segi.$"

MatchCall_PositiveBattleText11::
	.string "Ah, {PLAYER}{KUN}.\n"
	.string "{STR_VAR_1} naiz.\p"
	.string "Borrokarik bai azkenaldian?\n"
	.string "Nik beste bat irabazi dut gaur!\p"
	.string "Kristoren bolada daukat! Karkarkar!\n"
	.string "Beno, ikusi arte!$"

MatchCall_PositiveBattleText12::
	.string "Kaixo, {PLAYER}{KUN}.\n"
	.string "Ni naiz, {STR_VAR_1}.\p"
	.string "Ondo zabilza aspaldian?\n"
	.string "Ni guztiz biziberrituta nabil!\p"
	.string "Oraintxe beste borroka bat irabazi dut.\n"
	.string "Oraindik ez nago erretiratzeko\l"
	.string "adinean, gazte!$"

MatchCall_PositiveBattleText13::
	.string "Ah, kaixo, {PLAYER}{KUN}!\n"
	.string "{STR_VAR_1} naiz ni!\p"
	.string "Ondo zabiltzala espero dut.\n"
	.string "Ni izugarri ondo nabil azkenaldian!\p"
	.string "Beste borroka bat irabazi berri dut.\n"
	.string "Oh, oraindik ez naiz gazteen kontra\l"
	.string "galtzen hasi!\p"
	.string "Hurrengora arte!$"

MatchCall_PositiveBattleText14::
	.string "Oh, aupa, {PLAYER}{KUN}.\n"
	.string "{STR_VAR_1} naiz.\p"
	.string "Borroka batean izan berri naiz, eta nire\n"
	.string "{STR_VAR_2} berebizikoa izan da!\p"
	.string "Zuk ikusi izana gustatuko zitzaidan,\n"
	.string "{PLAYER}{KUN}. Aio-aio!$"

MatchCall_SameRouteBattleRequestText1::
	.string "Aupa! {PLAYER}, kaixo!\n"
	.string "{STR_VAR_1} naiz.\p"
	.string "Nola? Itxaron, {STR_VAR_2} inguruan\n"
	.string "zabiltzala?\p"
	.string "Ba orduan elkarrekin borrokatu behar dugu!\n"
	.string "Itxaroten egongo naiz! Laister arte!$"

MatchCall_SameRouteBattleRequestText2::
	.string "Kaixo, {PLAYER}!\n"
	.string "{STR_VAR_1} naiz.\p"
	.string "Zer? {STR_VAR_2} inguruan zabiltza\n"
	.string "oraintxe bertan?\p"
	.string "Borrokatu nahi duzu orduan?\n"
	.string "Itxarongo dizut! Ondo segi!$"

MatchCall_SameRouteBattleRequestText3::
	.string "Aupa, {PLAYER}!\n"
	.string "Ni naiz, {STR_VAR_1}.\p"
	.string "Aizu, {STR_VAR_2} inguruan al\n"
	.string "zabiltza orain?\p"
	.string "Nahiko zenuke nire kontra borroka\n"
	.string "bat egin orain?\p"
	.string "Oraingoan ez dut galduko!\n"
	.string "Itxaroten egongo naiz! Orain arte!$"

MatchCall_SameRouteBattleRequestText4::
	.string "Iepa, {PLAYER}{KUN}.\n"
	.string "{STR_VAR_1} naiz.\p"
	.string "Nondik zabiltza orain?\n"
	.string "Zer? {STR_VAR_2}(e)n?\p"
	.string "Borrokatu nahi?\n"
	.string "Ixtarongo dizut. Gero arte!$"

MatchCall_SameRouteBattleRequestText5::
	.string "Apakaixo, {PLAYER}{KUN}!\n"
	.string "{STR_VAR_1} naiz.\l"
	.string "Zer moduz zabiltza?\p"
	.string "Non zaudela esan duzu?\n"
	.string "{STR_VAR_2}, orduan?\p"
	.string "Eta zer iruditzen zaizu errebantxa\n"
	.string "bat jokatzen badugu orain?\p"
	.string "Adi egongo naiz zure zain.\n"
	.string "Laister arte!$"

MatchCall_SameRouteBattleRequestText6::
	.string "Iepa, {PLAYER}{KUN}.\n"
	.string "{STR_VAR_1} naiz.\l"
	.string "Zer moduz zure POKéMONak?\p"
	.string "Oh, bentan? {STR_VAR_2}\n"
	.string "inguruan zabiltza?\p"
	.string "Ba, orduan errebantxa bat egin\n"
	.string "behar genuke.\p"
	.string "Itxarongo dizut, noski.\n"
	.string "Aio!$"

MatchCall_SameRouteBattleRequestText7::
	.string "…Em, {PLAYER}{KUN}?\n"
	.string "{STR_VAR_1} naiz…\p"
	.string "Oh, {STR_VAR_2} inguruan zabiltzala\n"
	.string "justu orain?\p"
	.string "Borroka dezagun, beraz.\n"
	.string "Oraintxe bertan, esan nahi dut.\p"
	.string "Nire POKéMONak erakutsiko dizkizut.\n"
	.string "Itxarongo dizut.$"

MatchCall_SameRouteBattleRequestText8::
	.string "Oh, {PLAYER}{KUN}, zer moduz?\n"
	.string "{STR_VAR_1} telefonoan.\p"
	.string "Ondo zaudela espero dut.\n"
	.string "Oh, {STR_VAR_2} inguruan zaude.\p"
	.string "Nahi duzu nirekin borrokatu\n"
	.string "orduan?\p"
	.string "Itxarongo dizut.\n"
	.string "Laister arte!$"

MatchCall_SameRouteBattleRequestText9::
	.string "Oh, {PLAYER}{KUN}, aupa!\n"
	.string "{STR_VAR_1} naiz!\p"
	.string "Ondo al zabiltza?\n"
	.string "Zer, {STR_VAR_2} inguruan zabiltzala?\p"
	.string "Orduan ez al duzu uste borroka bat\n"
	.string "egin behar genukeela?\p"
	.string "Ez gehiegi itxaronarazi!$"

MatchCall_SameRouteBattleRequestText10::
	.string "Oh, {PLAYER}{KUN}, kaixo…\n"
	.string "{STR_VAR_1} naiz.\p"
	.string "Zer moduz zaude?\n"
	.string "Oh, {STR_VAR_2} inguruan zabiltza.\p"
	.string "Orduan borrokatu egin behar genuke.\p"
	.string "Prest nago, zuri itxaroten.\n"
	.string "Bizi ibili!$"

MatchCall_SameRouteBattleRequestText11::
	.string "Ei, {PLAYER}{KUN}.\n"
	.string "{STR_VAR_1} naiz.\p"
	.string "Ah, beraz orain {STR_VAR_2}\n"
	.string "aldetik zabiltza?\p"
	.string "Beno, orduan uste dut borroka\n"
	.string "bat egin behar genukeela, ezta?\p"
	.string "Itxarongo dizut!\n"
	.string "Oraintxe arte!$"

MatchCall_SameRouteBattleRequestText12::
	.string "Kaixo, {PLAYER}{KUN}.\n"
	.string "Ni naiz, {STR_VAR_1}.\l"
	.string "Nondik zabiltza orain?\p"
	.string "{STR_VAR_2}?\n"
	.string "Hori hurbil dago hemendik!\p"
	.string "Zer iruditzen zaizu oraintxe borroka\n"
	.string "bat egiten badugu?\p"
	.string "Itxarongo dizut.\n"
	.string "Aio!$"

MatchCall_SameRouteBattleRequestText13::
	.string "Ah, kaixo, {PLAYER}{KUN}!\n"
	.string "{STR_VAR_1} naiz!\p"
	.string "Ondo egongo zarela espero dut.\n"
	.string "Oh, {STR_VAR_2} aldetik al zabiltza?\p"
	.string "Hori ez dago hemendik oso urrun,\n"
	.string "etorri eta borroka bat egingo dugu.\p"
	.string "Itxarongo dizut.\n"
	.string "Agur.$"

MatchCall_SameRouteBattleRequestText14::
	.string "Oh, kaixo, {PLAYER}{KUN}.\n"
	.string "{STR_VAR_1} naiz.\p"
	.string "Non zaudela? …{STR_VAR_2}(e)n?\n"
	.string "Hori oso hurbil dago.\p"
	.string "Ez al duzu uste borroka bat egin\n"
	.string "behar genukeela?\p"
	.string "Zure bila ibiliko naiz!\n"
	.string "Aio-aio!$"

MatchCall_DifferentRouteBattleRequestText1::
	.string "Epa! {PLAYER}, kaixo!\n"
	.string "{STR_VAR_1} naiz.\p"
	.string "Nahi al duzu nirekin borrokatu?\p"
	.string "Orduan zure zain egongo naiz\n"
	.string "{STR_VAR_2} inguruan!$"

MatchCall_DifferentRouteBattleRequestText2::
	.string "Kaixo, {PLAYER}!\n"
	.string "{STR_VAR_1} naiz.\p"
	.string "Nahiko zenuke nirekin borrokatu\n"
	.string "berriro?\p"
	.string "{STR_VAR_2} inguruan aurkituko\n"
	.string "nauzu. Itxarongo dizut!$"

MatchCall_DifferentRouteBattleRequestText3::
	.string "Aupa, {PLAYER}!\n"
	.string "Ni naiz, {STR_VAR_1}.\p"
	.string "Nire POKéMONak asko indartu dira\n"
	.string "azken aldian egon ginenetik.\p"
	.string "Beraien indarra neurtu nahi nuke\n"
	.string "zure POKéMONen aurka, {PLAYER}.\p"
	.string "Borroka dezagun, beraz!\p"
	.string "Zure zain egongo naiz {STR_VAR_2}\n"
	.string "aldetik.$"

MatchCall_DifferentRouteBattleRequestText4::
	.string "Iepa, {PLAYER}{KUN}.\n"
	.string "{STR_VAR_1} naiz.\l"
	.string "Zer moduz zabiltza?\p"
	.string "Nire POKéMONak asko indartu dira\n"
	.string "azkenaldian.\p"
	.string "Aizu, nahiko zenuke nire aurka\n"
	.string "borroka egin berriro?\p"
	.string "Elkartu gaitezen {STR_VAR_2}\n"
	.string "inguruan, ados?$"

MatchCall_DifferentRouteBattleRequestText5::
	.string "Apakaixo, {PLAYER}{KUN}!\n"
	.string "{STR_VAR_1} naiz.\p"
	.string "Nire POKéMONak asko hazten ari\n"
	.string "dira, oso indartsuak dira.\p"
	.string "Asko gustatuko litzaidake zure aurka\n"
	.string "beste borroka bat egitea.\p"
	.string "Zure zain egongo naiz {STR_VAR_2}\n"
	.string "aldetik. Laister arte!$"

MatchCall_DifferentRouteBattleRequestText6::
	.string "Epa, {PLAYER}{KUN}.\n"
	.string "{STR_VAR_1} naiz.\l"
	.string "Ondo izango zarela espero dut.\p"
	.string "Pentsatu dut zure aurka beste borroka\n"
	.string "bat egingo nukeela gustura. Zer iruditzen?\p"
	.string "Borrokatu nahi baduzu, etorri\n"
	.string "zaitez {STR_VAR_2}(e)ra.\p"
	.string "Agur!$"

MatchCall_DifferentRouteBattleRequestText7::
	.string "…Ein, {PLAYER}{KUN}?\n"
	.string "{STR_VAR_1} naiz…\l"
	.string "Eta? Ari al dira zure POKéMONak hazten?\p"
	.string "Nireak itzel indartu dira.\n"
	.string "Erakutsi nahi nizkizuke.\p"
	.string "{STR_VAR_2} inguruan egongo naiz.\n"
	.string "Etorri bisitan eta borrokatuko dugu.\p"
	.string "Laister arte.$"

MatchCall_DifferentRouteBattleRequestText8::
	.string "Oh, {PLAYER}{KUN}, zer martxa?\n"
	.string "{STR_VAR_1} deika.\p"
	.string "Ondo zaudela espero dut.\n"
	.string "Nire POKéMONak oso jostalariak dira.\p"
	.string "Hemendik hurbil bazaude, mesedez,\n"
	.string "errebantxa bat nahiko nuke.\p"
	.string "{STR_VAR_2} inguruan izango naiz.\n"
	.string "Ordura arte, aio!$"

MatchCall_DifferentRouteBattleRequestText9::
	.string "Oh, {PLAYER}{KUN}, kaixo!\n"
	.string "{STR_VAR_1} naiz!\l"
	.string "Zer moduz zure POKéMONak?\p"
	.string "Nire POKéMONak gero eta hobeak dira.\n"
	.string "Erakutsi nahi nizkizuke, {PLAYER}{KUN}.\p"
	.string "{STR_VAR_2} aldetik nabil orain,\n"
	.string "borroka dezagun hemendik bazabiltza.\p"
	.string "Laister arte!$"

MatchCall_DifferentRouteBattleRequestText10::
	.string "Oh, {PLAYER}{KUN}, kaixo…\n"
	.string "{STR_VAR_1} naiz.\l"
	.string "Zer, zer moduz doa dena?\p"
	.string "Nire POKéMONak lehen baino askoz ere\n"
	.string "indartusagoak dira.\p"
	.string "Beste borroka bat nahi nuke,\n"
	.string "{PLAYER}{KUN}.\p"
	.string "{STR_VAR_2} aldetik ibiliko naiz.\n"
	.string "Etorri hurbil baldin bazaude.$"

MatchCall_DifferentRouteBattleRequestText11::
	.string "Ah, {PLAYER}{KUN}.\n"
	.string "{STR_VAR_1} naiz.\l"
	.string "Nondik zabiltza?\p"
	.string "Nire POKéMONak biziberrituta daude.\n"
	.string "Uste dut zure POKéMONak ikusteko\l"
	.string "gogo handiz daudela, {PLAYER}{KUN}.\p"
	.string "{STR_VAR_2} inguruan nago orain.\n"
	.string "Gure bila etorriko zara, ezta?$"

MatchCall_DifferentRouteBattleRequestText12::
	.string "Kaixo, {PLAYER}{KUN}.\n"
	.string "Ni naiz, {STR_VAR_1}.\p"
	.string "Esan behar dizut, nire POKéMONak oso\n"
	.string "indartsuak dira orain.\p"
	.string "Zure kontrako borroka batean ikusi\n"
	.string "nahi nituzke, {PLAYER}{KUN}.\p"
	.string "{STR_VAR_2} aldetik ibiliko gara.\n"
	.string "Etorri nahi duzunean!$"

MatchCall_DifferentRouteBattleRequestText13::
	.string "Ei, kaixo, {PLAYER}{KUN}!\n"
	.string "{STR_VAR_1} naiz!\l"
	.string "Ondo al daude zure POKéMONak?\p"
	.string "Nire POKéMONak oso osasuntsu daude,\n"
	.string "ematen du garaitezinak direla!\p"
	.string "Asko gustatuko litzaidake beste borroka\n"
	.string "bat egieta zure aurka.\p"
	.string "{STR_VAR_2} inguruan bazabiltza,\n"
	.string "etorri bisitan.$"

MatchCall_DifferentRouteBattleRequestText14::
	.string "Oh, aupa, {PLAYER}{KUN}.\n"
	.string "{STR_VAR_1} naiz.\l"
	.string "Ondo zabiltza, ezta?\p"
	.string "Oh, bai! Nire POKéMONak inoiz\n"
	.string "baino indartsuago daude.\p"
	.string "Ez al duzu uste borroka bat egin\n"
	.string "behar genukeela, {PLAYER}{KUN}?\p"
	.string "Zure zain egongo naiz {STR_VAR_2}\n"
	.string "inguruan.\p"
	.string "Etorri nahi duzunean, ados?$"

MatchCall_PersonalizedText1::
	.string "Ni naiz, {STR_VAR_1}\n"
	.string "mendizale amorratua!\p"
	.string "Beno, elkar ezagutu genuenetik, mendiak\n"
	.string "gehiago apreziatzen al dituzu?\p"
	.string "Gutxitan ikusten zaitut mendibideetan…\p"
	.string "Hurrengoan, {STR_VAR_2} inguruan\n"
	.string "elkartuko gara.$"

MatchCall_PersonalizedText2::
	.string "{STR_VAR_1} naiz.\n"
	.string "Kaixo.\p"
	.string "Zuri buruz hitz egin berri diot\n"
	.string "ENTRENATZAILE bati.\p"
	.string "ENTRENATZAILE indartsua zarela esan diot,\n"
	.string "POKéMONak ondo tratatzen dituena.\p"
	.string "Espero dut mundu guztiak goraipatzen duen\n"
	.string "ENTRENATZAILE bilakatuko zarela.\p"
	.string "Ikusiko dugu elkar berriz!$"

MatchCall_PersonalizedText3::
	.string "Kaixo! {STR_VAR_1} naiz.\p"
	.string "Ez dakizu zelako lekuan nagoen.\n"
	.string "Usain goxoz beteta dago!\p"
	.string "Uste dut norbaitek BAIAK landatu dituela,\n"
	.string "eta loratu berri daude.\p"
	.string "Laister arte, egongo gara!$"

MatchCall_PersonalizedText4::
	.string "Kaixo! Hogeita hamar urte esploratzen,\n"
	.string "{STR_VAR_1} zure zerbitzura!\p"
	.string "Hemendik hara ibiltzeko energia\n"
	.string "soberan daukazula dirudi.\p"
	.string "Hondakinik aurkitu duzu azkenaldian?\n"
	.string "Abisatu zerbait aurkituz gero!\p"
	.string "Orain, barkatu, baina hondakinak\n"
	.string "esploratzera joan behar dut.$"

MatchCall_PersonalizedText5::
	.string "{STR_VAR_1} naiz!\p"
	.string "Ba al dakizu zertan nabilen?\n"
	.string "Hondartzatik olatuei begira!\p"
	.string "Ai… Olatuen aparra ederra da.\n"
	.string "Hemendik itsasoa ikusgarria da, zinez.\l"
	.string "Ene! A zer gosea, banoa, aio-aio!$"

MatchCall_PersonalizedText6::
	.string "Ñam-ñam…\n"
	.string "Ene, aupa, {STR_VAR_1} naiz.\l"
	.string "Atsegin dut hondartzan jatea.\p"
	.string "Nire POKéMONak eta ni oso ondo\n"
	.string "gabiltza. Energiak topera ditugu!\l"
	.string "Igeri egitera noa. Aio!$"

MatchCall_PersonalizedText7::
	.string "Kaixo, {STR_VAR_1} naiz…\p"
	.string "Pixka bat kostatzen ari zait ENTRENATZAILE\n"
	.string "GUAIEN kontu guzti hau…\p"
	.string "Denek uste dute ENTRENATZAILE perfektua\n"
	.string "naizela eta espektatiba horiek\l"
	.string "betetzen saiatzen ari naiz uneoro.\p"
	.string "Suposatzen dut hori dela ENTRENATZAILE\n"
	.string "GUAI izatea.\p"
	.string "Belarriak jaitsi beharko ditut…\n"
	.string "eta guztia isildu eta jasan.\p"
	.string "Zu zara hau kontatu diezaiokedan\n"
	.string "pertsona bakarra.\p"
	.string "baina, hurrengoan elkar ikustean,\n"
	.string "lasai, ez naiz kexatuko!$"

MatchCall_PersonalizedText8::
	.string "Iujuu, {STR_VAR_1} naiz!\n"
	.string "Zelan zabiltza?\p"
	.string "Nire POKéMONak entrenatzen aritu naiz\n"
	.string "zu helburutzat hartuta.\p"
	.string "Ez dut berriro ere galduko hurrengoan\n"
	.string "borrokatzen dugunean.\p"
	.string "Ez al da itzela lagun ENTRENATZAILEAK\n"
	.string "edukitzea? Hurrengora arte!$"

MatchCall_PersonalizedText9::
	.string "{STR_VAR_1} naiz…\n"
	.string "Oraintxe bertan, zure atzean…\l"
	.string "Ez al zegoen zerbait…?\p"
	.string "Hemen PIRO MENDIAN datzaten\n"
	.string "POKéMONEN indarra…\p"
	.string "Zutaz hitz egiten ari zait…\p"
	.string "Hemendik ihes egin behar zenuke,\n"
	.string "eta ez atzera begiratu…\p"
	.string "Kar-kar…\n"
	.string "Adio…$"

MatchCall_PersonalizedText10::
	.string "{STR_VAR_1} naiz.\n"
	.string "Zer moduz?\p"
	.string "Ez al da erosoa elkarrengandik urruti\n"
	.string "egonda hitz egin ahal izatea?\p"
	.string "Lehen, norbaitekin hitz egitekotan,\n"
	.string "nire aitari eskatu behar izaten nion\l"
	.string "kotxez eramateko…\p"
	.string "Joan egin beharra daukat.\n"
	.string "Pozten naiz hizketa hau eduki izanaz.$"

MatchCall_PersonalizedText11::
	.string "{STR_VAR_1} naiz!\n"
	.string "Kontatu diezazuket gauza bat?\p"
	.string "SAFARI GUNEA oso atsegin dut, baina\n"
	.string "joaten naizenetan beti galtzen naiz!\p"
	.string "Belar garai horrekin!\n"
	.string "Gehiegi da guztia paretik kentzeko!\p"
	.string "Esan beharra nion norbaiti hau\n"
	.string "guzti hau!\p"
	.string "Banoa berriro SAFARI GUNERA!\n"
	.string "Aio-pelaio!$"

MatchCall_PersonalizedText12::
	.string "Kaixo, {STR_VAR_1} naiz.\n"
	.string "Bai, hori da, aberatsa naiz, bai.\p"
	.string "Azkenengoz elkar ikusi genuenetik\n"
	.string "asko aberastu naiz, gainera.\p"
	.string "Are gehiago, nire POKéMONak ere\n"
	.string "askoz indartsuagoak dira.\p"
	.string "Uste dut mundu guzti hau\n"
	.string "niretzako soilik existitzen dela!\p"
	.string "Oh, ez duzu ezer esan behar!\n"
	.string "Mundu guztiak daki egia dela!\p"
	.string "Oh, barkatuko didazu, afari oso\n"
	.string "garrantzitsu batera joan behar dut.$"

MatchCall_PersonalizedText13::
	.string "Ufufufufu…\n"
	.string "Ni naiz, {STR_VAR_1}…\p"
	.string "Ba al dakizu zer ari naizen ikusten?\n"
	.string "{STR_VAR_2} bikote bat borrokan.\p"
	.string "Agian garailea harrapatzen saiatuko naiz…\n"
	.string "Ufufufufufu…\p"
	.string "Em… Pixka bat okupatuta nago orain.\n"
	.string "Banoa.$"

MatchCall_PersonalizedText14::
	.string "Oh, {STR_VAR_1} naiz!\p"
	.string "Uste dut aspertzen ari naizela\n"
	.string "ITSASONTZI ABANDONATU honekin.\p"
	.string "Baina jada hemen nagoenez, eta gogoa\n"
	.string "dudanez zure aurka irabazteko,\l"
	.string "Pixka bat gehiago geratuko naiz.\p"
	.string "Zuk ere gogoa badaukazu, zergatik ez\n"
	.string "zara nigana etortzen?\p"
	.string "Uste dut gaur dela eguna alboko\n"
	.string "gelako gizonari erronka botatzeko\l"
	.string "eta borroka bat egiteko.\p"
	.string "Laister arte!$"

MatchCall_PersonalizedText15::
	.string "{STR_VAR_1} naiz!\n"
	.string "Itsasgizon bikaina!\p"
	.string "Badakizu zer uste dudan?\p"
	.string "Itsasoko ENTRENATZAILEAK direla\n"
	.string "guztietan indartsuenak!\p"
	.string "Nigandik ikasi eta itsasoan entrenatu\n"
	.string "behar zenuke…\p"
	.string "Ene, badator olatua!\p"
	.string "Entrenatzeko aukera bikaina!\n"
	.string "Barkatu, baina joan egin behar dut!$"

MatchCall_PersonalizedText16::
	.string "{STR_VAR_1} naiz! Entzun, nire\n"
	.string "POKéMONei karatea erakusten aritu naiz.\p"
	.string "Orain ni baino hobeak dira, ordea!\n"
	.string "Beraien aurka galdu eta galdu ari naiz!\p"
	.string "Nire POKéMONen aurka galtzen badut ere,\n"
	.string "ez dut galduko beste ENTRENATZAILE\l"
	.string "baten aurka, ez horixe!\p"
	.string "Berriro borrokatu behar dugu!\n"
	.string "Jiaaaa!$"

MatchCall_PersonalizedText17::
	.string "Ni naiz, {STR_VAR_1}.\n"
	.string "Zer moduz doaz zure bidaiak?\p"
	.string "…Eneee, benetan ari al zara?\n"
	.string "Biziki estimulagarria dirudi horrek!\p"
	.string "Uste dut kanta bat idatziko dudala\n"
	.string "zure abenturetako baten inguruan.\p"
	.string "…Ei, aizu, badator, badator.\n"
	.string "Jada ari naiz riffak imaginatzen.\p"
	.string "Kanta hau ondo idatzi behar dut bizi,\n"
	.string "joan egin behar dut! Aio!$"

MatchCall_PersonalizedText18::
	.string "Ni {STR_VAR_1} naiz…\n"
	.string "Entzun nire abesti berri.\p"
	.string "Lalala, {STR_VAR_2}, {STR_VAR_2}!\n"
	.string "Zergatik zara horren {STR_VAR_2}?\l"
	.string "Zergatik ezin naiz izan zu, {STR_VAR_2}?\l"
	.string "Lala, {STR_VAR_2} eta {STR_VAR_1},\l"
	.string "{STR_VAR_1} eta {STR_VAR_2}…\p"
	.string "Berriro errepika, eta isildu…$"

MatchCall_PersonalizedText19::
	.string "{STR_VAR_1} naiz, badakizu,\n"
	.string "kanpinean aditua!\p"
	.string "Borroka egin genuenean, zure aurka galdu\n"
	.string "egin nuen, erraz.\p"
	.string "Azken finean, ni kanpinean naiz\n"
	.string "aditua eta.\p"
	.string "Galdu ala irabazi, oso atsegin dut\n"
	.string "borrokatzea kanpinean nagoenean.\p"
	.string "Borrokatu berriz gurekin, ados?\n"
	.string "Ah, eta goazen elkarrekin kanpinera!$"

MatchCall_PersonalizedText20::
	.string "Ni naiz, ni, {STR_VAR_1}!\p"
	.string "Beste mendi batzuetara igotzea nahiago\n"
	.string "nuke, hona igo baino, egia esan.\p"
	.string "Baina ez dakit ERRAUTS MENDIN\n"
	.string "bezalako neskarik aurkituko nukeen.\p"
	.string "Neskak dituen beste mendirik ezagutzen\n"
	.string "baduzu, abisatu, mesedez!\p"
	.string "Ehehehe, ondo segi!$"

MatchCall_PersonalizedText21::
	.string "… … … … … …\n"
	.string "… … … … … …\l"
	.string "{STR_VAR_1} naiz…\p"
	.string "… … … … … …\n"
	.string "… … … … … …\l"
	.string "Gaurkoz nahikoa…$"

MatchCall_PersonalizedText22::
	.string "Ni {STR_VAR_1} naiz. Gaur, zurekin\n"
	.string "hitz egingo nuelako susmoa nuen.\p"
	.string "Zure aurka irabazteko daukadan gogoa\n"
	.string "handiagoa da egunetik egunera.\p"
	.string "Baduzu halako aurkari bat jada, baietz?\n"
	.string "Bera izan nahiko nuke…\p"
	.string "Pozten naiz entzun didazulako.\n"
	.string "Agur!$"

MatchCall_PersonalizedText23::
	.string "{STR_VAR_1} naiz.\p"
	.string "Nigandik hurbil ENTRENATZAILE\n"
	.string "indartsuren bat dabilenean, sentitu\l"
	.string "egin dezaket, nolabait.\p"
	.string "Hemendik hurbil ibili zara, {PLAYER}{KUN}?\n"
	.string "Agian zu izan zara.\p"
	.string "Zure bisitaren zain geldituko naiz.\n"
	.string "Agur!$"

MatchCall_PersonalizedText24::
	.string "Kaixo, {STR_VAR_1} naiz.\n"
	.string "Itxura ona duzu, {PLAYER}{KUN}.\p"
	.string "Munduan zehar bidaian ibili naiz,\n"
	.string "baina esan beharra dut eskualde hau\l"
	.string "bereziki atsegin zaidala.\p"
	.string "Hemen geratuko naiz denbora batez.\n"
	.string "Agian berriro elkartuko gara?\p"
	.string "Ez ditut zure teknika miragarriak\n"
	.string "ahaztu.\p"
	.string "Errebantxaren zain nago.$"

MatchCall_PersonalizedText25::
	.string "Zintz… Ni… {STR_VAR_1} naiz…\n"
	.string "…Zintz…\p"
	.string "ROXANNEk errieta egin dit gaur\n"
	.string "klasean.\p"
	.string "Baina ez dut gorroto hala ere.\p"
	.string "ROXANNEk zehazki esaten dit zer egin\n"
	.string "dudan gaizki, ikasi ahal izateko.\p"
	.string "Bihar ere ENTRENATZAILE ESKOLARA \n"
	.string "joango naiz berriro, noski!\p"
	.string "Ikusi arte!$"

MatchCall_PersonalizedText26::
	.string "{STR_VAR_1} naiz!\p"
	.string "ROXANNEk bere aurka borroka egiten\n"
	.string "utzi zidan atzo.\p"
	.string "Emaitza…\n"
	.string "Oso txarra, jakingo ez bazenu bezala.\p"
	.string "Baina asko poztu nintzen ROXANNEk\n"
	.string "bere aurka borrokatzen uzteagatik soilik!\p"
	.string "Ez dakizu zenbat miresten dudan\n"
	.string "bera!\p"
	.string "Adi egon eta lan asko egingo dut!\n"
	.string "Joan beharra dut!$"

MatchCall_PersonalizedText27::
	.string "kaixo, ANNA naiz! MEG, nire kide\n"
	.string "gaztearekin nago gaur ere.\p"
	.string "Oso atsegin dut MEG eta POKéMONak\n"
	.string "zaintzea. Hain dira politak!\p"
	.string "Nire anai-arrebak balira bezala\n"
	.string "zaindu nahi nituzke!\p"
	.string "Oh, kaixo, MEG!\n"
	.string "Jaso al dituzu opilak?\p"
	.string "Zer? Ez, ez, ez naiz tratatzen ari nire\n"
	.string "esklabua izango bazina bezala!\p"
	.string "Partida galdu duzu, beraz ogia erosi\n"
	.string "behar duzu zigor gisan!\p"
	.string "Ez zintuzket inoiz esklabu gisan,\n"
	.string "tratatuko MEG! berezia zara niretzat!\p"
	.string "Joan egin behar dut.\n"
	.string "Hamaiketakoa egiteko ordua iritsi da!$"

MatchCall_PersonalizedText28::
	.string "Maite ditut POKéMONak!\n"
	.string "FAN KLUBEKO {STR_VAR_1} naiz!\p"
	.string "Entzun honako hau!\n"
	.string "Nire POKéMON kuttunak…\p"
	.string "Pffff! Kar-kar-kar!\n"
	.string "Ezin dut ezer gehiago esan! Sekretua da!\l"
	.string "Politegia da hitzez azaltzeko!\p"
	.string "Oh, nire {STR_VAR_2} txikiak\n"
	.string "{POKEBLOCK} bat gura du!\p"
	.string "Zeinen polita den, benetan!\p"
	.string "Barkatu, baina ez dut hitz egin!\n"
	.string "Hurrengoan kontatu beharko dizut!$"

MatchCall_PersonalizedText29::
	.string "Ohoho!\p"
	.string "{STR_VAR_1} naiz ni! Nire POKéMON\n"
	.string "maiteaz hitz egin behar dizut!\p"
	.string "Mesedez, entzun hau.\n"
	.string "Nire {STR_VAR_2} maitea da.\p"
	.string "Norbaitek hartzen badu, zuzenean\n"
	.string "nire besoetara salto egiten du!\p"
	.string "Oh… Oh… Existitzen al da horren\n"
	.string "gauza ederrik?\p"
	.string "Oh, zeinen sentsazio gozoa!\p"
	.string "Nire zoriontasunaren zatitxo bat\n"
	.string "eman nahi nizuke.\p"
	.string "Beno, joan egin behar dut.\n"
	.string "Agur!$"

MatchCall_PersonalizedText30::
	.string "Ni… {STR_VAR_1} naiz.\n"
	.string "Jendeak ADITU deitzen dit.\p"
	.string "Baina gauza bat ondo dakit.\n"
	.string "Ezingo nuke ADITU izan nik\l"
	.string "bakarrik.\p"
	.string "Soilik POKéMONen laguntzarekin bihur\n"
	.string "daiteke ENTRENATZAILEA ADITU.\p"
	.string "Humph! Uste dut zeozer oso sakon\n"
	.string "eta interesgarria esan dudala!\p"
	.string "Gogo onez utziko zaitut!$"

MatchCall_PersonalizedText31::
	.string "{STR_VAR_1} naiz.\n"
	.string "Pozten naiz zurekin hitz egiteaz!\p"
	.string "Bizirik eta freskatuta sentitzen\n"
	.string "naiz, bainuontzi honetan plisti-plasta.\p"
	.string "ENTRENATZAILE gazteen aurka borrokan\n"
	.string "aritu naiz elkar ezagutu genueetik, baina\l"
	.string "zu zara denetan onena.\p"
	.string "Esango nuke zahartzen zarenean\n"
	.string "ADITU bihurtuko zarela! Ohohoho…$"

MatchCall_PersonalizedText32::
	.string "Iuju! Ni {STR_VAR_1} naiz!\n"
	.string "Zer moduz?\p"
	.string "Agian nire imaginazioa da, baina\n"
	.string "borroka bat irabaztean, nire prakak\l"
	.string "hobeto bezala sentitzen ditut. Materialki.\p"
	.string "Zer esan nahi dudan horrekin?\n"
	.string "Zaila da esplikatzen, baina…\l"
	.string "Nola esan dezaket, ea…\l"
	.string "Zetazkoak ematen dute nire prakek!\p"
	.string "Eta zure aurka borrokatzena, {PLAYER}{KUN},\n"
	.string "azkure itzela besterik ez zidaten eman.\p"
	.string "… … … … … …\n"
	.string "Ez didazu sinesten?\l"
	.string "Ehehehe, hori da dena! Agur!$"

MatchCall_PersonalizedText33::
	.string "Aupa txo!\n"
	.string "{STR_VAR_1} naiz!\p"
	.string "Beti bezala, birritan pentsatu gabe\n"
	.string "ari naiz arrantzan!\p"
	.string "Itsasoaz eta ibaiez gain, ba al dago\n"
	.string "arrantzatzeko beste lekurik?\p"
	.string "Edozein lekutan egonda ere, arrantzarako\n"
	.string "gogoa sartzen zait!\p"
	.string "Oh, kaka zaharra!\n"
	.string "Pita kateatuta geratu zait!\p"
	.string "Joan egin behar dut! Arrantzarako\n"
	.string "lekurik aurkitzen baduzu, esan!$"

MatchCall_PersonalizedText34::
	.string "Ei, kaixo! {STR_VAR_1} naiz.\n"
	.string "Lasai-lasai al zabiltza?\p"
	.string "Txiki-txikitatik, oso ume lasaia\n"
	.string "izan naiz, ulertzen?\p"
	.string "Inoiz ez naiz ezerekin estresatuta\n"
	.string "edo presaka ibili.\p"
	.string "Baina ezetz asmatu, orain\n"
	.string "TRIATLETA bihurtu naiz.\p"
	.string "Inoiz ez dakizu norantz eramango\n"
	.string "zaituen bizitzak, ezetz?\p"
	.string "Orain ENTRENATZAILEA zara, baina\n"
	.string "etorkizunean auskalo zer izango zaren!\p"
	.string "Imaginatu irakasle izango bazina\n"
	.string "edo artista, agian. Itzela, e?\p"
	.string "Baina, aizu, lasai. Lasai hartu.\n"
	.string "Ikusi arte.$"

MatchCall_PersonalizedText35::
	.string "Ni {STR_VAR_1} naiz!\n"
	.string "Bizikletan nabil orain.\p"
	.string "Maite dut igerian eta korrika aritzea,\n"
	.string "baina bizikleta da nire kuttunena!\p"
	.string "Nire gorputza haizearekin bat izango\n"
	.string "balitz bezala sentitzen dut.\p"
	.string "Hegan egongo banintz bezain\n"
	.string "kitzikagarria da!\p"
	.string "Ongi! Gaur errekor berria ezarriko\n"
	.string "dut BIDEGORRIAN!\p"
	.string "Zuk ere saiatu behar zenuke!\n"
	.string "Ikusi arte!$"

MatchCall_PersonalizedText36::
	.string "Iepa, ni {STR_VAR_1} naiz! Triatloi\n"
	.string "erdi-erdian harrapatu nauzu!\p"
	.string "baina, aizu, beti dut denbora hitz\n"
	.string "egiteko!\p"
	.string "POKéMONekin batera ariketa egitea\n"
	.string "itzela da!\p"
	.string "Elkarrekin hitz egin gabe ere, bihotz\n"
	.string "bakarra bagenu bezala da kasik.\p"
	.string "Zeinen ederra!\p"
	.string "Ene… Korrika eta hizketan…\n"
	.string "Gehiegi ari naiz nekatzen…\l"
	.string "Ene… Joan…beharra…dut…$"

MatchCall_PersonalizedText37::
	.string "Aupa, {STR_VAR_1} naiz.\n"
	.string "Erresistentzia hobetu nahi baduzu,\l"
	.string "altitude askoko lekuetan saiatu!\p"
	.string "Saiatu mendi gain batean korrika egiten.\n"
	.string "Ezinean ibiliko zara ziztuan!\p"
	.string "Ni ere oxigeno gabe geratzen ari naiz!\n"
	.string "Agur!$"

MatchCall_PersonalizedText38::
	.string "Oh, {STR_VAR_1} naiz, kaixo.\p"
	.string "Denbora asko noa igerian baina oraindik\n"
	.string "ez naiz iritsi ITZELETA HIRIRA.\p"
	.string "Agian leku berean biraka nabil.\p"
	.string "Ez, ez, ezin da hori izan.\n"
	.string "Kar-kar.\l"
	.string "Zaindu!$"

MatchCall_PersonalizedText39::
	.string "Ei, {STR_VAR_1} naiz…\n"
	.string "Ai ama!\p"
	.string "Plisti-plasta!\p"
	.string "Blug-blug-blug-blug…\p"
	.string "Plaf!\p"
	.string "Txip-txap! Txip-txap!\p"
	.string "Ei! Barkatu! Justu-justu eguzkia\n"
	.string "hartzeko krema eman dut.\p"
	.string "Nire POKéNAVak ihes egin dit eskutik\n"
	.string "eta uretara erori zait!\p"
	.string "Baina DEVONen POKéNAVa zinez gogorra\n"
	.string "da. Ondo atera da bainu horretatik!\p"
	.string "Beno, okupatuta nago eguzkia hartzen,\n"
	.string "beste batean hitz egingo dugu.$"

MatchCall_PersonalizedText40::
	.string "Hello, {STR_VAR_1} naiz.\p"
	.string "Out of the three triathlon events,\n"
	.string "I like swimming best.\p"
	.string "But if I stay in the sea too long,\n"
	.string "won't I get all prune-like?\p"
	.string "Ooh, triathlon is such a grueling\n"
	.string "test of human endurance! Bye!$"

MatchCall_PersonalizedText41::
	.string "Hello, {PLAYER}{KUN}.\n"
	.string "{STR_VAR_1} here.\p"
	.string "How are your POKéMON doing?\p"
	.string "My DRAGON POKéMON appear to be\n"
	.string "in peak form. Bye for now.$"

MatchCall_PersonalizedText42::
	.string "{STR_VAR_1} here.\p"
	.string "My {STR_VAR_2} has grown even more\n"
	.string "tough than that last time.\p"
	.string "I'm not going to lose again to you.\n"
	.string "You wait till next time!\p"
	.string "See you around!$"

MatchCall_PersonalizedText43::
	.string "It is {STR_VAR_1} here.\p"
	.string "I have continued with my studies\n"
	.string "in the art of concealment.\p"
	.string "But I have been too successful.\n"
	.string "No one has been able to find me.\l"
	.string "My success makes me lonely…\p"
	.string "Like smoke I disappear!\n"
	.string "Farewell!$"

MatchCall_PersonalizedText44::
	.string "This is {STR_VAR_1}.\n"
	.string "I kept up my training since we met.\p"
	.string "My {STR_VAR_2} is getting pretty\n"
	.string "tough.\p"
	.string "Training on a beach is effective,\n"
	.string "just as I thought. Bye now!$"

MatchCall_PersonalizedText45::
	.string "How do you do?\n"
	.string "This is {STR_VAR_1}.\p"
	.string "I wonder when this yucky volcanic\n"
	.string "ash will stop falling?\p"
	.string "If it gets too deep, it will cover\n"
	.string "up the pattern on my parasol…\p"
	.string "Let's promise to meet again!$"

MatchCall_PersonalizedText46::
	.string "Hi, {STR_VAR_1} here.\p"
	.string "Did you know that it's easier to\n"
	.string "float in the sea than a pool?\p"
	.string "Just by lying still, your body will\n"
	.string "float on its own.\p"
	.string "But if you float for too long,\n"
	.string "watch that you don't get carried\l"
	.string "off too far out.\p"
	.string "…Where am I, anyway?\n"
	.string "I'd better go!$"

MatchCall_PersonalizedText47::
	.string "Oh, {PLAYER}{KUN}, hello!\n"
	.string "This is {STR_VAR_1}.\l"
	.string "I'm up in the mountains now.\p"
	.string "But the ground is too bumpy.\n"
	.string "I can't pitch my tent here…\p"
	.string "Oh, I had a brilliant idea!\p"
	.string "Maybe I can get my POKéMON to tamp\n"
	.string "the ground flat here!\p"
	.string "I'm going to try that!\n"
	.string "Bye-bye!$"

MatchCall_PersonalizedText48::
	.string "Oh, hi, hi, this is {STR_VAR_1}!\p"
	.string "I'm raising POKéMON with LIV!\n"
	.string "We're trying very hard!\p"
	.string "If we try harder, can we become\n"
	.string "number one? Bye-bye!$"

MatchCall_PersonalizedText49::
	.string "{STR_VAR_1} here!\p"
	.string "I'm a SAILOR, but I'm not on a boat\n"
	.string "now.\p"
	.string "It makes me wonder--what should\n"
	.string "a SAILOR on land be called?\p"
	.string "That's what I've been thinking\n"
	.string "while staring out across the waves.\p"
	.string "All right, next time!$"

MatchCall_PersonalizedText50::
	.string "{STR_VAR_1} naiz.\n"
	.string "So? Get any more POKéMON?\p"
	.string "If you catch a new POKéMON,\n"
	.string "you have to come show me.\p"
	.string "I won't whine for it, honest.\n"
	.string "I'll be waiting. See you.$"

MatchCall_PersonalizedText51::
	.string "This is {STR_VAR_1}.\p"
	.string "Are you raising your POKéMON\n"
	.string "in the optimal way?\p"
	.string "The air is clean where I am.\n"
	.string "It's the perfect environment for\l"
	.string "raising POKéMON.\p"
	.string "If you're going to focus on raising\n"
	.string "POKéMON, you should come out to\l"
	.string "{STR_VAR_2}. Take care now.$"

MatchCall_PersonalizedText52::
	.string "Hi, this is {STR_VAR_1}.\p"
	.string "I gave a {POKEBLOCK} to my {STR_VAR_2}.\n"
	.string "It seemed to enjoy it very much.\p"
	.string "It looks like POKéMON have their\n"
	.string "likes and dislikes with {POKEBLOCK}S.\p"
	.string "I find that quite fascinating.\n"
	.string "Please do take care.$"

MatchCall_PersonalizedText53::
	.string "{STR_VAR_1} here.\p"
	.string "If you cooperate with POKéMON,\n"
	.string "one can be comfortable in the wild.\p"
	.string "Everyone should realize that and\n"
	.string "cooperate with POKéMON more.\p"
	.string "That would be ideal.\n"
	.string "I really think so.\p"
	.string "I think you're on the right track!\n"
	.string "Catch you later!$"

MatchCall_PersonalizedText54::
	.string "Hi, {STR_VAR_1} naiz. You know,\n"
	.string "the TRAINER who's always prepared!\p"
	.string "{PLAYER}{KUN}, do you have enough items?\n"
	.string "Are your POKéMON fit for action?\p"
	.string "Keeping everything perfect around\n"
	.string "you all the time is the secret to\l"
	.string "keeping your journey going.\p"
	.string "I'd better go check my own\n"
	.string "supplies! Be vigilant!$"

MatchCall_PersonalizedText55::
	.string "{STR_VAR_1} naiz!\n"
	.string "{STR_VAR_1} naiz!\p"
	.string "{STR_VAR_2} is a very busy\n"
	.string "thoroughfare, so I get challenged\l"
	.string "by all kinds of TRAINERS every day.\p"
	.string "Today, I won five battles and lost\n"
	.string "only three!\p"
	.string "How did you do today?\n"
	.string "Tell me about it next time, okay?$"

MatchCall_PersonalizedText56::
	.string "It's me, {STR_VAR_1}.\p"
	.string "I'm popular because I have lots\n"
	.string "of BUG POKéMON, right?\p"
	.string "Well, I took a bunch of my fave\n"
	.string "bugs to school today.\p"
	.string "This girl I like started crying!\n"
	.string "Go ahead and laugh if you want.\p"
	.string "I have to try teaching her what\n"
	.string "makes BUG POKéMON so appealing.\p"
	.string "Snivel…\n"
	.string "See you!$"

MatchCall_PersonalizedText57::
	.string "Hah! Hah! Hah! Hah!\p"
	.string "Hi! {STR_VAR_1} naiz! Hah! Hah!\p"
	.string "Trying to chat…\n"
	.string "While climbing…\l"
	.string "Is harsh exercise… Hah! Hah!\p"
	.string "Urgh! Oof…\n"
	.string "It's steeper now…\l"
	.string "We'll chat…another time…\l"
	.string "Hah! Hah! Hah!$"

MatchCall_PersonalizedText58::
	.string "Oh, hi!\p"
	.string "I'm still searching for treasures\n"
	.string "with KIRA!\p"
	.string "Maybe there isn't any treasure\n"
	.string "here at all…\p"
	.string "But the important thing is for me\n"
	.string "to search alongside KIRA.\p"
	.string "Oh, hey, KIRA!\n"
	.string "Wh-why are you angry?\p"
	.string "I'm not ignoring you, honey!\n"
	.string "You're my one and only!\p"
	.string "…{PLAYER}, I have to go, bye!$"

MatchCall_PersonalizedText59::
	.string "This is {STR_VAR_1}!\p"
	.string "I went to DEWFORD's GYM again\n"
	.string "for training.\p"
	.string "BRAWLY, the GYM LEADER, seems\n"
	.string "to be tougher now.\p"
	.string "Something about being toughened\n"
	.string "by the wild waves…\p"
	.string "But he's still as cool as ever.\n"
	.string "The ladies adore him!\l"
	.string "It makes me envious, frankly.\p"
	.string "I wonder… Is his friend BRUNO\n"
	.string "the same way as BRAWLY?\p"
	.string "You know, all sweaty or smelly,\n"
	.string "and prone to calling people\l"
	.string "“big wave,” that sort of thing.\p"
	.string "But, hey, this jealousy thing isn't\n"
	.string "very seemly, is it?\p"
	.string "Forget this chat ever happened,\n"
	.string "how about it? So long!$"

MatchCall_PersonalizedText60::
	.string "It's a pleasure to chat with\n"
	.string "a young TRAINER like you.\p"
	.string "I imagine that you will continue to\n"
	.string "enjoy POKéMON whatever your age.\p"
	.string "Wouldn't it be good if you had\n"
	.string "a partnership like ours?\p"
	.string "Of course, {PLAYER}{KUN}, you already\n"
	.string "enjoy the trust and companionship\l"
	.string "of your POKéMON now.\p"
	.string "You have the makings of long and\n"
	.string "enduring relationships already!\p"
	.string "Hahaha!\n"
	.string "Never be discouraged!$"

MatchCall_PersonalizedText61::
	.string "Hi, this is {STR_VAR_1}!\n"
	.string "We just won a battle!\p"
	.string "We don't win often, but it was this\n"
	.string "cool SWIMMER guy.\p"
	.string "My sister was steamed!\p"
	.string "She wanted to pretend that she\n"
	.string "was weak to make an impression!\p"
	.string "She always chews me out whether\n"
	.string "we win or lose!\p"
	.string "{PLAYER}{KUN}, can you say something\n"
	.string "to her next time?\p"
	.string "Okay, see you!$"

MatchCall_PersonalizedText62::
	.string "{STR_VAR_1} here, yes.\n"
	.string "I headed out to sea yesterday.\p"
	.string "I had been hoping to find a new\n"
	.string "ruin to explore.\p"
	.string "But the tides somehow seemed to\n"
	.string "carry me back where I started.\p"
	.string "I'm still weak at battling, too…\n"
	.string "Feel free to mock me…\l"
	.string "But I won't give up.\p"
	.string "My day will come when I discover\n"
	.string "a new ruin!\p"
	.string "That's all I have to say!\n"
	.string "Farewell for now!$"

MatchCall_PersonalizedText63::
	.string "Ahoy there!\n"
	.string "It's me, {STR_VAR_1}!\l"
	.string "I'm out on ROUTE 108 now!\l"
	.string "In other words, where I always am!\p"
	.string "Today, a gorgeous SWIMMER \n"
	.string "swam by me!\p"
	.string "So I startled her with a shout!\p"
	.string "And she gave me a nasty glare!\p"
	.string "That's all from ROUTE 108!\n"
	.string "Brought to you by {STR_VAR_1}!$"

MatchCall_PersonalizedText64::
	.string "{STR_VAR_1} naiz!\p"
	.string "I'm kind of busy, but I figured\n"
	.string "I should let you know that I've\l"
	.string "beaten five TRAINERS again today.\p"
	.string "If I keep this pace up, I can\n"
	.string "probably beat you next time.\p"
	.string "I think we'll be good rivals,\n"
	.string "you and I. Good-bye for now!$"

MatchCall_BattleFrontierStreakText1::
	.string "Hi! This is {STR_VAR_1}.\n"
	.string "I heard the news!\p"
	.string "They say you did excellent at\n"
	.string "the {STR_VAR_2}.\p"
	.string "It's awesome, {STR_VAR_3} straight wins?\n"
	.string "See you!$"

MatchCall_BattleFrontierStreakText2::
	.string "Hello, {STR_VAR_1} naiz!\n"
	.string "I heard about you!\p"
	.string "They said you won {STR_VAR_3} straight\n"
	.string "battles at the {STR_VAR_2}.\p"
	.string "That's special! I should try\n"
	.string "harder, too! See you!$"

MatchCall_BattleFrontierStreakText3::
	.string "Hey there, {PLAYER}!\n"
	.string "It's me, {STR_VAR_1}.\p"
	.string "I heard you went on a tear at\n"
	.string "the {STR_VAR_2}!\p"
	.string "A big {STR_VAR_3}-win streak…\n"
	.string "That is a big record, isn't it?\p"
	.string "I'd better get it together, too!\n"
	.string "Catch you soon!$"

MatchCall_BattleFrontierStreakText4::
	.string "Hey, {PLAYER}{KUN}.\n"
	.string "{STR_VAR_1} here. What's up?\p"
	.string "There's a rumor going around that\n"
	.string "you strung together {STR_VAR_3} straight\l"
	.string "wins at the {STR_VAR_2}.\p"
	.string "I'd better step it up, too.\n"
	.string "See you!$"

MatchCall_BattleFrontierStreakText5::
	.string "Hiya, {PLAYER}{KUN}!\n"
	.string "{STR_VAR_1} naiz.\p"
	.string "You were at the {STR_VAR_2}\n"
	.string "and won {STR_VAR_3} battles in a row?\l"
	.string "Isn't that something!\p"
	.string "I'd better work on my POKéMON more.\n"
	.string "See you soon!$"

MatchCall_BattleFrontierStreakText6::
	.string "Hey, {PLAYER}{KUN}.\n"
	.string "{STR_VAR_1} here. How are you?\p"
	.string "By the way, I heard you pulled off\n"
	.string "the feat of {STR_VAR_3} straight wins at\l"
	.string "the {STR_VAR_2}.\p"
	.string "That inspires me to focus on\n"
	.string "raising my team.$"

MatchCall_BattleFrontierStreakText7::
	.string "…Er, {PLAYER}{KUN}?\n"
	.string "{STR_VAR_1} here…\p"
	.string "Oh, yeah, you were over at\n"
	.string "the {STR_VAR_2}, right?\p"
	.string "And you won {STR_VAR_3} battles in a row.\p"
	.string "Oh, there goes a rare POKéMON!\n"
	.string "I have to go!$"

MatchCall_BattleFrontierStreakText8::
	.string "Oh, {PLAYER}{KUN}, how do you do?\n"
	.string "This is {STR_VAR_1} speaking.\l"
	.string "I hope you're doing well.\p"
	.string "Oh, but, you are. I've heard that\n"
	.string "you won {STR_VAR_3} matches in a row at\l"
	.string "the {STR_VAR_2}.\p"
	.string "That's very impressive!\n"
	.string "I hope you stay successful.$"

MatchCall_BattleFrontierStreakText9::
	.string "Oh, {PLAYER}{KUN}, hi there!\n"
	.string "This is {STR_VAR_1}!\p"
	.string "I heard! Your {STR_VAR_3}-win streak at\n"
	.string "the {STR_VAR_2}!\p"
	.string "That is so cool!\n"
	.string "I'd better try harder, too!$"

MatchCall_BattleFrontierStreakText10::
	.string "Oh, {PLAYER}{KUN}, hello…\n"
	.string "This is {STR_VAR_1}.\p"
	.string "You won {STR_VAR_3} straight battles at\n"
	.string "the {STR_VAR_2}?\p"
	.string "That's quite the accomplishment.\n"
	.string "I need to work harder.$"

MatchCall_BattleFrontierStreakText11::
	.string "Ah, {PLAYER}{KUN}.\n"
	.string "This is {STR_VAR_1}.\p"
	.string "I hear you're the terror of\n"
	.string "the {STR_VAR_2}?\p"
	.string "You won, what, {STR_VAR_3} matches in\n"
	.string "a row?\p"
	.string "You're good, you.\n"
	.string "I wonder how many I can win?$"

MatchCall_BattleFrontierStreakText12::
	.string "Hello, {PLAYER}{KUN}.\n"
	.string "It's me, {STR_VAR_1}.\l"
	.string "Are you keeping well?\p"
	.string "Someone passed on word about you.\n"
	.string "How you won {STR_VAR_3} straight battles\l"
	.string "at a place named {STR_VAR_2}?\p"
	.string "That's quite the tale.\n"
	.string "See you!$"

MatchCall_BattleFrontierStreakText13::
	.string "Ah, hello, {PLAYER}{KUN}!\n"
	.string "This is {STR_VAR_1}!\l"
	.string "I hope you've been keeping well.\p"
	.string "They say you won {STR_VAR_3} straight\n"
	.string "battles at the {STR_VAR_2}.\p"
	.string "I admire your energy!\n"
	.string "Bye now.$"

MatchCall_BattleFrontierStreakText14::
	.string "Oh, hi, {PLAYER}{KUN}.\n"
	.string "This is {STR_VAR_1}.\p"
	.string "I heard about you!\n"
	.string "Didn't you just win {STR_VAR_3} battles in\l"
	.string "a row at the {STR_VAR_2}?\p"
	.string "You're an inspiration!\n"
	.string "Bye-bye!$"

MatchCall_BattleFrontierRecordStreakText1::
	.string "Hi! This is {STR_VAR_1}.\n"
	.string "I heard the news!\p"
	.string "They say you did excellent at\n"
	.string "the {STR_VAR_2}.\p"
	.string "It's awesome--{STR_VAR_3} straight wins?\n"
	.string "See you!$"

MatchCall_BattleFrontierRecordStreakText2::
	.string "Hello, {STR_VAR_1} naiz!\n"
	.string "I heard about you!\p"
	.string "They said you won {STR_VAR_3} straight\n"
	.string "battles at the {STR_VAR_2}.\p"
	.string "That's special! I should try\n"
	.string "harder, too! See you!$"

MatchCall_BattleFrontierRecordStreakText3::
	.string "Hey there, {PLAYER}!\n"
	.string "It's me, {STR_VAR_1}.\p"
	.string "I heard you went on a tear at\n"
	.string "the {STR_VAR_2}!\p"
	.string "A big {STR_VAR_3}-win streak…\n"
	.string "That is a big record, isn't it?\p"
	.string "I'd better get it together, too!\n"
	.string "Catch you soon!$"

MatchCall_BattleFrontierRecordStreakText4::
	.string "Hey, {PLAYER}{KUN}.\n"
	.string "{STR_VAR_1} here. What's up?\p"
	.string "There's a rumor going around that\n"
	.string "you strung together {STR_VAR_3} straight\l"
	.string "wins at the {STR_VAR_2}.\p"
	.string "I'd better step it up, too.\n"
	.string "See you!$"

MatchCall_BattleFrontierRecordStreakText5::
	.string "Hiya, {PLAYER}{KUN}!\n"
	.string "{STR_VAR_1} naiz.\p"
	.string "You were at the {STR_VAR_2}\n"
	.string "and won {STR_VAR_3} battles in a row?\l"
	.string "Isn't that something!\p"
	.string "Me? I'd say I'm coming along.\n"
	.string "See you soon!$"

MatchCall_BattleFrontierRecordStreakText6::
	.string "Hey, {PLAYER}{KUN}.\n"
	.string "{STR_VAR_1} here. How are you?\p"
	.string "By the way, I heard you pulled off\n"
	.string "the feat of {STR_VAR_3} straight wins at\l"
	.string "the {STR_VAR_2}.\p"
	.string "I'd better try harder myself!\n"
	.string "See you soon!$"

MatchCall_BattleFrontierRecordStreakText7::
	.string "…Er, {PLAYER}{KUN}?\n"
	.string "{STR_VAR_1} here…\p"
	.string "Oh, yeah, you were over at\n"
	.string "the {STR_VAR_2}, right?\p"
	.string "And you won {STR_VAR_3} battles in a row.\p"
	.string "Oh, there goes a rare POKéMON!\n"
	.string "I have to go!$"

MatchCall_BattleFrontierRecordStreakText8::
	.string "Oh, {PLAYER}{KUN}, how do you do?\n"
	.string "This is {STR_VAR_1} speaking.\l"
	.string "I hope you're doing well.\p"
	.string "Oh, but, you are. I've heard that\n"
	.string "you won {STR_VAR_3} matches in a row at\l"
	.string "the {STR_VAR_2}.\p"
	.string "That's very impressive!\n"
	.string "I'd better work on my POKéMON, too!$"

MatchCall_BattleFrontierRecordStreakText9::
	.string "Oh, {PLAYER}{KUN}, hi there!\n"
	.string "This is {STR_VAR_1}!\p"
	.string "I heard! Your {STR_VAR_3}-win streak at\n"
	.string "the {STR_VAR_2}!\p"
	.string "That is so cool!\n"
	.string "I'd better try harder, too!$"

MatchCall_BattleFrontierRecordStreakText10::
	.string "Oh, {PLAYER}{KUN}, hello…\n"
	.string "This is {STR_VAR_1}.\p"
	.string "You won {STR_VAR_3} straight battles at\n"
	.string "the {STR_VAR_2}?\p"
	.string "That's quite the accomplishment.\n"
	.string "I need to work harder.$"

MatchCall_BattleFrontierRecordStreakText11::
	.string "Ah, {PLAYER}{KUN}.\n"
	.string "This is {STR_VAR_1}.\p"
	.string "I hear you're the terror of\n"
	.string "the {STR_VAR_2}?\p"
	.string "You won, what, {STR_VAR_3} matches in\n"
	.string "a row?\p"
	.string "You're good, you.\n"
	.string "I wonder how many I can win?$"

MatchCall_BattleFrontierRecordStreakText12::
	.string "Hello, {PLAYER}{KUN}.\n"
	.string "It's me, {STR_VAR_1}.\l"
	.string "Are you keeping well?\p"
	.string "Someone passed on word about you.\n"
	.string "How you won {STR_VAR_3} straight battles\l"
	.string "at a place named {STR_VAR_2}?\p"
	.string "That's quite the tale.\n"
	.string "See you!$"

MatchCall_BattleFrontierRecordStreakText13::
	.string "Ah, hello, {PLAYER}{KUN}!\n"
	.string "This is {STR_VAR_1}!\l"
	.string "I hope you've been keeping well.\p"
	.string "They say you won {STR_VAR_3} straight\n"
	.string "battles at the {STR_VAR_2}.\p"
	.string "I admire your energy!\n"
	.string "Bye now.$"

MatchCall_BattleFrontierRecordStreakText14::
	.string "Oh, hi, {PLAYER}{KUN}.\n"
	.string "This is {STR_VAR_1}.\l"
	.string "I heard about you!\p"
	.string "Didn't you just win {STR_VAR_3} battles in\n"
	.string "a row at the {STR_VAR_2}?\p"
	.string "You're an inspiration!\n"
	.string "Bye-bye!$"

MatchCall_BattleDomeText1::
	.string "Hi! {PLAYER}?\n"
	.string "Hello, this is {STR_VAR_1}!\l"
	.string "I heard the news!\p"
	.string "You became the champion at\n"
	.string "the {STR_VAR_2} {STR_VAR_3} times?\p"
	.string "It's awesome! I have to do better!\n"
	.string "See you!$"

MatchCall_BattleDomeText2::
	.string "Hello, {STR_VAR_1} naiz!\n"
	.string "I heard about you!\p"
	.string "They said you won {STR_VAR_3} titles\n"
	.string "at the {STR_VAR_2}.\p"
	.string "That's super! I wonder if I can\n"
	.string "become a champion?$"

MatchCall_BattleDomeText3::
	.string "Hey there, {PLAYER}!\n"
	.string "It's me, {STR_VAR_1}.\l"
	.string "How's it going?\p"
	.string "I heard you won events {STR_VAR_3} times\n"
	.string "at the {STR_VAR_2}!\p"
	.string "Make it one more next time!\n"
	.string "Catch you soon!$"

MatchCall_BattleDomeText4::
	.string "Hey, {PLAYER}{KUN}.\n"
	.string "{STR_VAR_1} here.\p"
	.string "I heard you became the champion\n"
	.string "at the {STR_VAR_2} {STR_VAR_3} times.\p"
	.string "Sounds like you're working hard.\n"
	.string "I'll try to keep up!$"

MatchCall_BattleDomeText5::
	.string "Hiya, {PLAYER}{KUN}!\n"
	.string "{STR_VAR_1} naiz.\p"
	.string "I heard you won {STR_VAR_3} times\n"
	.string "outright at the {STR_VAR_2}.\p"
	.string "I'd better get with it, too!\n"
	.string "See you soon!$"

MatchCall_BattleDomeText6::
	.string "Hey, {PLAYER}{KUN}?\n"
	.string "{STR_VAR_1} here. How are you?\p"
	.string "By the way, I heard you became\n"
	.string "the champion {STR_VAR_3} times at\l"
	.string "the {STR_VAR_2}.\p"
	.string "I'd better raise my POKéMON before\n"
	.string "you pull farther ahead.$"

MatchCall_BattleDomeText7::
	.string "{PLAYER}{KUN}?\n"
	.string "{STR_VAR_1} here.\p"
	.string "You were at the {STR_VAR_2}\n"
	.string "and became the champ {STR_VAR_3} times?\p"
	.string "That's neat. By the way, have you\n"
	.string "caught any rare POKéMON lately?\p"
	.string "Oh, is that right.\n"
	.string "Okay, bye.$"

MatchCall_BattleDomeText8::
	.string "Oh, {PLAYER}{KUN}, how do you do?\n"
	.string "This is {STR_VAR_1} speaking.\l"
	.string "I hope you're doing well.\l"
	.string "Oh, but, you are.\p"
	.string "I've heard that you won {STR_VAR_3} titles\n"
	.string "at the {STR_VAR_2}.\p"
	.string "I must raise my POKéMON like you.\n"
	.string "See you again.$"

MatchCall_BattleDomeText9::
	.string "Oh, {PLAYER}{KUN}, hi there!\n"
	.string "This is {STR_VAR_1}!\p"
	.string "I heard! You took the title\n"
	.string "{STR_VAR_3} times at the {STR_VAR_2}!\p"
	.string "That is so cool!\n"
	.string "I'd better try harder, too!$"

MatchCall_BattleDomeText10::
	.string "Oh, {PLAYER}{KUN}, hello.\n"
	.string "This is {STR_VAR_1}.\p"
	.string "You won {STR_VAR_3} straight times at\n"
	.string "the {STR_VAR_2}?\p"
	.string "That's quite the accomplishment.\n"
	.string "I need to work harder.$"

MatchCall_BattleDomeText11::
	.string "Ah, {PLAYER}{KUN}.\n"
	.string "This is {STR_VAR_1}.\p"
	.string "I hear you're the terror of\n"
	.string "the {STR_VAR_2}?\p"
	.string "You won, what, {STR_VAR_3} straight times\n"
	.string "now?\p"
	.string "I wonder if I can ever become\n"
	.string "a champion?\p"
	.string "…Pretty well impossible?\n"
	.string "Well, see you!$"

MatchCall_BattleDomeText12::
	.string "Hello, {PLAYER}{KUN}.\n"
	.string "It's me, {STR_VAR_1}.\l"
	.string "Are you keeping well?\p"
	.string "You've won {STR_VAR_3} events at a place\n"
	.string "named {STR_VAR_2}?\p"
	.string "That's quite the tale.\n"
	.string "See you!$"

MatchCall_BattleDomeText13::
	.string "Ah, hello, {PLAYER}{KUN}!\n"
	.string "This is {STR_VAR_1}!\l"
	.string "I hope you've been keeping well.\p"
	.string "They say you won {STR_VAR_3} events\n"
	.string "at the {STR_VAR_2}?\p"
	.string "I admire your energy!\n"
	.string "Bye now.$"

MatchCall_BattleDomeText14::
	.string "Oh, hi, {PLAYER}{KUN}.\n"
	.string "This is {STR_VAR_1}.\l"
	.string "I heard about you!\p"
	.string "Didn't you win {STR_VAR_3} titles\n"
	.string "at the {STR_VAR_2}?\p"
	.string "You're an inspiration!\n"
	.string "See you again!$"

MatchCall_BattlePikeText1::
	.string "Hi! {PLAYER}?\n"
	.string "Hello, this is {STR_VAR_1}!\l"
	.string "I heard the news!\p"
	.string "You got through {STR_VAR_3} rooms\n"
	.string "at the {STR_VAR_2}!\p"
	.string "That's awesome!\n"
	.string "See you!$"

MatchCall_BattlePikeText2::
	.string "Hello, {STR_VAR_1} naiz!\n"
	.string "I heard about you!\p"
	.string "They said you won your way through\n"
	.string "{STR_VAR_3} rooms at the {STR_VAR_2}.\p"
	.string "I have to try much harder!\n"
	.string "Bye!$"

MatchCall_BattlePikeText3::
	.string "Hey there, {PLAYER}!\n"
	.string "It's me, {STR_VAR_1}.\l"
	.string "How's it going?\p"
	.string "I heard you won through {STR_VAR_3} rooms\n"
	.string "at the {STR_VAR_2}!\p"
	.string "Try to do even better next time!\n"
	.string "Catch you soon!$"

MatchCall_BattlePikeText4::
	.string "Hey, {PLAYER}{KUN}.\n"
	.string "{STR_VAR_1} here.\p"
	.string "I heard you blew through {STR_VAR_3} rooms\n"
	.string "at the {STR_VAR_2}.\p"
	.string "I'd better train my POKéMON and\n"
	.string "try to keep up!$"

MatchCall_BattlePikeText5::
	.string "Hiya, {PLAYER}{KUN}!\n"
	.string "{STR_VAR_1} naiz.\p"
	.string "I heard you got past {STR_VAR_3} rooms\n"
	.string "at the {STR_VAR_2}.\p"
	.string "I'd better get with it, too!\n"
	.string "See you soon!$"

MatchCall_BattlePikeText6::
	.string "Hey, {PLAYER}{KUN}?\n"
	.string "{STR_VAR_1} here. How are you?\p"
	.string "By the way, I heard you got through\n"
	.string "{STR_VAR_3} rooms at the {STR_VAR_2}.\p"
	.string "I'd better raise my POKéMON before\n"
	.string "you pull further ahead.$"

MatchCall_BattlePikeText7::
	.string "{PLAYER}{KUN}?\n"
	.string "{STR_VAR_1} here.\p"
	.string "You were at the {STR_VAR_2}\n"
	.string "and won your way past {STR_VAR_3} rooms?\p"
	.string "That's wicked.\p"
	.string "Oh, there goes a rare POKéMON!\n"
	.string "Okay, bye.$"

MatchCall_BattlePikeText8::
	.string "Oh, {PLAYER}{KUN}, how do you do?\n"
	.string "This is {STR_VAR_1} speaking.\l"
	.string "I hope you're doing well.\l"
	.string "Oh, but, you are.\p"
	.string "I've heard that you got through\n"
	.string "{STR_VAR_3} rooms at the {STR_VAR_2}.\p"
	.string "That's quite impressive!\n"
	.string "I must raise my POKéMON like you.\l"
	.string "See you again.$"

MatchCall_BattlePikeText9::
	.string "Oh, {PLAYER}{KUN}, hi there!\n"
	.string "This is {STR_VAR_1}!\p"
	.string "I heard! You won your way through\n"
	.string "{STR_VAR_3} rooms at the {STR_VAR_2}!\p"
	.string "That is so cool!\n"
	.string "I'd better try harder, too!$"

MatchCall_BattlePikeText10::
	.string "Oh, {PLAYER}{KUN}, hello.\n"
	.string "This is {STR_VAR_1}.\p"
	.string "You won your way past {STR_VAR_3} rooms\n"
	.string "at the {STR_VAR_2}?\p"
	.string "That's quite the accomplishment.\n"
	.string "I need to work harder.$"

MatchCall_BattlePikeText11::
	.string "Ah, {PLAYER}{KUN}.\n"
	.string "This is {STR_VAR_1}.\p"
	.string "I hear you're the terror of\n"
	.string "the {STR_VAR_2}?\p"
	.string "You got through, what, {STR_VAR_3} rooms?\n"
	.string "That's gotta count for something.\p"
	.string "I wonder if I can ever become\n"
	.string "a champion?\p"
	.string "…Pretty well impossible?\n"
	.string "Well, see you!$"

MatchCall_BattlePikeText12::
	.string "Hello, {PLAYER}{KUN}.\n"
	.string "It's me, {STR_VAR_1}.\l"
	.string "Are you keeping well?\p"
	.string "You've won through {STR_VAR_3} rooms at\n"
	.string "a place named {STR_VAR_2}?\p"
	.string "That's quite the tale.\n"
	.string "See you!$"

MatchCall_BattlePikeText13::
	.string "Ah, hello, {PLAYER}{KUN}!\n"
	.string "This is {STR_VAR_1}!\l"
	.string "I hope you've been keeping well.\p"
	.string "They say you won in {STR_VAR_3} rooms\n"
	.string "at the {STR_VAR_2}?\p"
	.string "I admire your energy!\n"
	.string "Bye now.$"

MatchCall_BattlePikeText14::
	.string "Oh, hi, {PLAYER}{KUN}.\n"
	.string "This is {STR_VAR_1}.\l"
	.string "I heard about you!\p"
	.string "Didn't you get through {STR_VAR_3} rooms\n"
	.string "at the {STR_VAR_2}?\p"
	.string "You're an inspiration!\n"
	.string "See you again!$"

MatchCall_BattlePyramidText1::
	.string "Hi! {PLAYER}?\n"
	.string "Hello, this is {STR_VAR_1}!\l"
	.string "I heard the news!\p"
	.string "You climbed {STR_VAR_3} floors inside\n"
	.string "the {STR_VAR_2}, right?\p"
	.string "That's awesome!\n"
	.string "I should try that challenge.$"

MatchCall_BattlePyramidText2::
	.string "Hello, {STR_VAR_1} naiz!\n"
	.string "I heard about you!\p"
	.string "They said you won your way through\n"
	.string "{STR_VAR_3} floors in the {STR_VAR_2}.\p"
	.string "Wow, that's fantastic!\n"
	.string "I'd better raise my POKéMON, too!$"

MatchCall_BattlePyramidText3::
	.string "Hey there, {PLAYER}!\n"
	.string "It's me, {STR_VAR_1}.\l"
	.string "How's it going?\p"
	.string "I heard you climbed {STR_VAR_3} floors\n"
	.string "in the {STR_VAR_2}!\p"
	.string "Try to do even better next time!\n"
	.string "Catch you soon!$"

MatchCall_BattlePyramidText4::
	.string "Hey, {PLAYER}{KUN}.\n"
	.string "{STR_VAR_1} here.\p"
	.string "I heard you scaled {STR_VAR_3} floors\n"
	.string "in the {STR_VAR_2}.\p"
	.string "I'd better work hard and try\n"
	.string "to keep up!$"

MatchCall_BattlePyramidText5::
	.string "Hiya, {PLAYER}{KUN}!\n"
	.string "{STR_VAR_1} naiz.\p"
	.string "I heard you climbed {STR_VAR_3} floors\n"
	.string "in the {STR_VAR_2}.\p"
	.string "I'd better get with it, too!\n"
	.string "See you soon!$"

MatchCall_BattlePyramidText6::
	.string "Hey, {PLAYER}{KUN}?\n"
	.string "{STR_VAR_1} here. How are you?\p"
	.string "By the way, I heard you got through\n"
	.string "{STR_VAR_3} floors in the {STR_VAR_2}.\p"
	.string "I'd better raise my POKéMON before\n"
	.string "you pull further ahead.$"

MatchCall_BattlePyramidText7::
	.string "{PLAYER}{KUN}?\n"
	.string "{STR_VAR_1} here.\p"
	.string "You were at the {STR_VAR_2}\n"
	.string "and won your way up {STR_VAR_3} floors?\p"
	.string "Neat. Were there any rare POKéMON\n"
	.string "there?\p"
	.string "No, huh?\n"
	.string "Okay, bye.$"

MatchCall_BattlePyramidText8::
	.string "Oh, {PLAYER}{KUN}, how do you do?\n"
	.string "This is {STR_VAR_1} speaking.\l"
	.string "I hope you're doing well.\l"
	.string "Oh, but, you are.\p"
	.string "I've heard that you got through\n"
	.string "{STR_VAR_3} floors in the {STR_VAR_2}.\p"
	.string "That's quite impressive!\n"
	.string "I must raise my POKéMON like you.\l"
	.string "See you again.$"

MatchCall_BattlePyramidText9::
	.string "Oh, {PLAYER}{KUN}, hi there!\n"
	.string "This is {STR_VAR_1}!\p"
	.string "I heard! You won your way through\n"
	.string "{STR_VAR_3} floors in the {STR_VAR_2}!\p"
	.string "That is so cool!\n"
	.string "I'd better try harder, too!$"

MatchCall_BattlePyramidText10::
	.string "Oh, {PLAYER}{KUN}, hello.\n"
	.string "This is {STR_VAR_1}.\p"
	.string "You climbed {STR_VAR_3} floors inside\n"
	.string "the {STR_VAR_2}?\p"
	.string "That's quite the accomplishment.\n"
	.string "I need to work harder.$"

MatchCall_BattlePyramidText11::
	.string "Ah, {PLAYER}{KUN}.\n"
	.string "This is {STR_VAR_1}.\p"
	.string "I hear you're the terror of\n"
	.string "the {STR_VAR_2}?\p"
	.string "You rose through, what, {STR_VAR_3} floors?\n"
	.string "That's gotta count for something.\p"
	.string "I wonder if I can ever become\n"
	.string "a champion?\p"
	.string "…Pretty well impossible?\n"
	.string "Well, see you!$"

MatchCall_BattlePyramidText12::
	.string "Hello, {PLAYER}{KUN}.\n"
	.string "It's me, {STR_VAR_1}.\l"
	.string "Are you keeping well?\p"
	.string "You've won through {STR_VAR_3} floors in\n"
	.string "a place named {STR_VAR_2}?\p"
	.string "That's quite the tale.\n"
	.string "See you!$"

MatchCall_BattlePyramidText13::
	.string "Ah, hello, {PLAYER}{KUN}!\n"
	.string "This is {STR_VAR_1}!\l"
	.string "I hope you've been keeping well.\p"
	.string "They say you climbed {STR_VAR_3} floors\n"
	.string "in the {STR_VAR_2}?\p"
	.string "I admire your energy!\n"
	.string "Bye now.$"

MatchCall_BattlePyramidText14::
	.string "Oh, hi, {PLAYER}{KUN}.\n"
	.string "This is {STR_VAR_1}.\l"
	.string "I heard about you!\p"
	.string "Didn't you get through {STR_VAR_3} floors\n"
	.string "in the {STR_VAR_2}?\p"
	.string "You're an inspiration!\n"
	.string "See you again!$"

MatchCall_Text_Mom1::
	.string "MOM: Your father and you…\n"
	.string "Everyone is captivated by POKéMON.\p"
	.string "What is the charm of POKéMON?\p"
	.string "Me?\n"
	.string "I adore POKéMON that help me with\l"
	.string "my everyday chores.$"

MatchCall_Text_Mom2::
	.string "MOM: Hi, {PLAYER}!\n"
	.string "Your father keeps himself locked\l"
	.string "away in the PETALBURG GYM.\p"
	.string "He comes home every so often.\n"
	.string "But he goes back to the GYM when\l"
	.string "he's eaten everything he can.\p"
	.string "I'm guessing that losing to you\n"
	.string "was a big blow to his pride!$"

MatchCall_Text_Mom3::
	.string "MOM: {PLAYER}…\n"
	.string "Don't worry about me or the house.\p"
	.string "Wear those RUNNING SHOES until\n"
	.string "they fall apart, honey!$"

MatchCall_Text_Roxanne1::
	.string "ROXANNE: Oh, hello, {PLAYER}!\p"
	.string "I've been hard at work retraining\n"
	.string "since we met.\p"
	.string "I will still need some more time\n"
	.string "before I can reopen the GYM.\p"
	.string "But when I do, please visit my GYM\n"
	.string "for a rematch!$"

MatchCall_Text_Roxanne2::
	.string "ROXANNE: Is this {PLAYER}?\n"
	.string "Congratulations!\l"
	.string "I've been hearing about you!\p"
	.string "As for me, I need some more time\n"
	.string "before I can reopen the GYM.\p"
	.string "But when I do, please visit my GYM\n"
	.string "for a rematch!$"

MatchCall_Text_Roxanne3::
	.string "ROXANNE: {PLAYER}!\n"
	.string "My GYM is ready!\p"
	.string "Please visit RUSTBORO whenever\n"
	.string "you can!$"

MatchCall_Text_Roxanne4::
	.string "ROXANNE: At the RUSTBORO GYM,\n"
	.string "the fact that we battled, {PLAYER},\l"
	.string "is a matter of pride.$"

MatchCall_Text_Brawly1::
	.string "BRAWLY: Hey, there, {PLAYER}{KUN}!\p"
	.string "I learned a lot from the battle we\n"
	.string "had together.\p"
	.string "I intend to do my training over,\n"
	.string "then reopen the GYM.\p"
	.string "It's going to take some time before\n"
	.string "I'm ready to run the GYM again.\p"
	.string "But if I can reopen the GYM,\n"
	.string "I want you to challenge us again.$"

MatchCall_Text_Brawly2::
	.string "BRAWLY: Hey, {PLAYER}{KUN}!\n"
	.string "Congratulations!\p"
	.string "Word about your exploits arrived\n"
	.string "on tidal winds!\p"
	.string "It appears as if I need to work on\n"
	.string "my training some more.\p"
	.string "It's going to take some time before\n"
	.string "I'm ready to run the GYM again.\p"
	.string "But if I can reopen the GYM,\n"
	.string "I want you to challenge us again.$"

MatchCall_Text_Brawly3::
	.string "BRAWLY: Hey, {PLAYER}{KUN}!\n"
	.string "My GYM's ready for action!\p"
	.string "Come back to DEWFORD anytime\n"
	.string "for another challenge!$"

MatchCall_Text_Brawly4::
	.string "BRAWLY: {PLAYER}{KUN}, I don't think\n"
	.string "I'll ever get bored of battling you!$"

MatchCall_Text_Wattson1::
	.string "WATTSON: Oh, it's you!\p"
	.string "After you left, I've been redoing\n"
	.string "my training from scratch.\p"
	.string "I'd say I could use a wee bit more\n"
	.string "time to reopen my GYM.\p"
	.string "You'll have to wait till then!\n"
	.string "Wahahahaha!$"

MatchCall_Text_Wattson2::
	.string "WATTSON: Wahahahaha!\p"
	.string "You've really done it, haven't you?\n"
	.string "I've been getting word about you!\p"
	.string "It seems I need to retrain some\n"
	.string "more still.\p"
	.string "I'd say I could use a wee bit more\n"
	.string "time to reopen my GYM.\p"
	.string "You'll have to wait till then!\n"
	.string "Wahahahaha!$"

MatchCall_Text_Wattson3::
	.string "WATTSON: Oh, it's you!\n"
	.string "My GYM's ready!\p"
	.string "Visit MAUVILLE anytime!\n"
	.string "Wahahahaha!$"

MatchCall_Text_Wattson4::
	.string "WATTSON: Wahahaha!\p"
	.string "A battle with you is always charged\n"
	.string "with shocking power!$"

MatchCall_Text_Flannery1::
	.string "FLANNERY: {PLAYER}…\p"
	.string "When we battled, I learned exactly\n"
	.string "how immature I was.\p"
	.string "But I'm not done yet!\p"
	.string "I'm going to redo my training and\n"
	.string "reopen the GYM.\p"
	.string "When the time comes, {PLAYER},\n"
	.string "please challenge us again.$"

MatchCall_Text_Flannery2::
	.string "FLANNERY: Hello, {PLAYER}?\n"
	.string "Congratulations!\p"
	.string "Word of your success has reached\n"
	.string "us like the heat of a volcano!\p"
	.string "Our training is coming along very\n"
	.string "well here.\p"
	.string "When the GYM's ready, a mark will\n"
	.string "appear beside my name in the\l"
	.string "MATCH CALL list.$"

MatchCall_Text_Flannery3::
	.string "FLANNERY: Oh, {PLAYER}?\n"
	.string "Our GYM's ready!\p"
	.string "Come to LAVARIDGE for a soak\n"
	.string "in the hot spring and a challenge!$"

MatchCall_Text_Flannery4::
	.string "FLANNERY: {PLAYER}…\n"
	.string "I'm positive that you keep getting\l"
	.string "better at training every time.$"

MatchCall_Text_Winona1::
	.string "WINONA: Hello, {PLAYER}!\p"
	.string "Thanks to our battle, I've come\n"
	.string "to understand my weak points!\p"
	.string "When I reopen the GYM, I won't go\n"
	.string "down in defeat again!$"

MatchCall_Text_Winona2::
	.string "WINONA: You've done it, {PLAYER}!\p"
	.string "News about the new CHAMPION\n"
	.string "has reached us in FORTREE!\p"
	.string "But… The next time we battle,\n"
	.string "it's not going to end the same way.$"

MatchCall_Text_Winona3::
	.string "WINONA: Is this {PLAYER}?\n"
	.string "Our GYM is back in operation!\p"
	.string "We're waiting for you in FORTREE!$"

MatchCall_Text_Winona4::
	.string "WINONA: {PLAYER}…\n"
	.string "Though I have lost, my wings will\l"
	.string "never break.\p"
	.string "Yes, in exactly the same way that\n"
	.string "you never lost sight of your dream.$"

MatchCall_Text_TateLiza1::
	.string "TATE: Oh! You're…\n"
	.string "LIZA: {PLAYER}!\p"
	.string "TATE: We're in training again…\n"
	.string "LIZA: So we can reopen our GYM!\p"
	.string "TATE: When our GYM is ready…\n"
	.string "LIZA: When our GYM is ready…\p"
	.string "TATE: A mark'll appear by our name…\n"
	.string "LIZA: On the MATCH CALL list.$"

MatchCall_Text_TateLiza2::
	.string "TATE: {PLAYER}, congratulations!\n"
	.string "LIZA: {PLAYER}, congratulations!\p"
	.string "TATE: The two of us are…\n"
	.string "LIZA: Still in training!\p"
	.string "TATE: We need some more time, but…\n"
	.string "LIZA: When our GYM is ready…\p"
	.string "TATE: A mark'll appear by our name…\n"
	.string "LIZA: On the MATCH CALL list.$"

MatchCall_Text_TateLiza3::
	.string "TATE: {PLAYER}!\n"
	.string "LIZA: {PLAYER}!\p"
	.string "TATE: Our GYM is ready!\n"
	.string "LIZA: Our GYM is ready!\p"
	.string "TATE: Please come visit…\n"
	.string "LIZA: MOSSDEEP anytime!$"

MatchCall_Text_TateLiza4::
	.string "TATE: {PLAYER}, the battle we had…\n"
	.string "LIZA: Is an invaluable experience.\p"
	.string "TATE: It would be nice if…\n"
	.string "LIZA: We could all battle again!$"

MatchCall_Text_Juan1::
	.string "JUAN: Hmm…\n"
	.string "{PLAYER}{KUN}… Was it?\p"
	.string "Our battle together--it brought\n"
	.string "to me memories of when I first\l"
	.string "encountered WALLACE.\p"
	.string "Perhaps you are a genius who may\n"
	.string "yet surpass WALLACE!$"

MatchCall_Text_Juan2::
	.string "JUAN: Fufu… {PLAYER}{KUN}…\n"
	.string "You've finally achieved your goal.\p"
	.string "My eye for appraising talent wasn't\n"
	.string "mistaken…\p"
	.string "I wish for another chance to meet\n"
	.string "you, for you have scaled the peak\l"
	.string "of power and prestige.$"

MatchCall_Text_Juan3::
	.string "JUAN: Hoho… {PLAYER}{KUN}…\p"
	.string "Our SOOTOPOLIS GYM has finally\n"
	.string "reopened.\p"
	.string "If you wish to see me, you are\n"
	.string "welcome to visit anytime.$"

MatchCall_Text_Juan4::
	.string "JUAN: {PLAYER}{KUN}…\p"
	.string "Like the finest music, the battles\n"
	.string "we wage together strike chords\l"
	.string "of inspiration in my heart…\p"
	.string "When I close my eyes, I see visions\n"
	.string "of you soaring with the melody…$"

MatchCall_Text_Sidney::
	.string "SIDNEY: Yo, {PLAYER}!\p"
	.string "If you want to battle with me\n"
	.string "again, you come on back whenever\l"
	.string "you like to the POKéMON LEAGUE.\p"
	.string "I'll always be here!\n"
	.string "I'll be waiting!$"

MatchCall_Text_Phoebe::
	.string "PHOEBE: Hi, {PLAYER}!\p"
	.string "How about coming back here again\n"
	.string "sometime?\p"
	.string "I'd like to see how much tighter\n"
	.string "your bond has grown with your\l"
	.string "POKéMON.$"

MatchCall_Text_Glacia::
	.string "GLACIA: Hello, {PLAYER}.\p"
	.string "I trust you haven't become\n"
	.string "complacent with your power?\p"
	.string "If you feel the need to cool your\n"
	.string "hot emotions just a little, do come\l"
	.string "to the POKéMON LEAGUE…$"

MatchCall_Text_Drake::
	.string "DRAKE: That voice… {PLAYER}, is it?\n"
	.string "You sound well…\p"
	.string "I understand that there is now\n"
	.string "a facility called the BATTLE\l"
	.string "FRONTIER that tests the skills of\l"
	.string "TRAINERS.\p"
	.string "However, if you wish to have real\n"
	.string "battles, there is no substitute for\l"
	.string "the POKéMON LEAGUE!\p"
	.string "Don't you agree, {PLAYER}?$"

MatchCall_Text_Wallace::
	.string "WALLACE: Hello, {PLAYER}{KUN}.\n"
	.string "Have you met STEVEN?\p"
	.string "He is…\n"
	.string "Actually incredibly skilled.\p"
	.string "However, he's an odd soul who\n"
	.string "rarely battles.\p"
	.string "Instead, he would rather look for\n"
	.string "rare stones.\p"
	.string "I'm sure he's digging in a cave or\n"
	.string "a craggy mountain somewhere.\p"
	.string "But what is a rare stone exactly?\n"
	.string "All I can think of is a METEORITE…$"

MatchCall_Text_MayRayquazaCall:
	.string "… … … … … …\n"
	.string "… … … … … Beep!\p"
	.string "MAY: Hi, {PLAYER}{KUN}!\p"
	.string "I was just in PACIFIDLOG a little\n"
	.string "while ago.\p"
	.string "I saw a giant green POKéMON\n"
	.string "flying high in the sky.\p"
	.string "I…\n"
	.string "I've never seen anything like it.\p"
	.string "I wonder what it was.\n"
	.string "Is this maybe a major discovery?\p"
	.string "… … … … … …\n"
	.string "… … … … … Click!$"

MatchCall_Text_BrendanRayquazaCall:
	.string "… … … … … …\n"
	.string "… … … … … Beep!\p"
	.string "BRENDAN: Hey, {PLAYER}!\n"
	.string "I was in PACIFIDLOG just now.\p"
	.string "I saw this huge green POKéMON\n"
	.string "flying across the sky.\p"
	.string "I've never seen anything that\n"
	.string "amazing before.\p"
	.string "I wish you could've seen it,\n"
	.string "{PLAYER}.\p"
	.string "… … … … … …\n"
	.string "… … … … … Click!$"

MatchCall_Text_May1::
	.string "MAY: Hi, {PLAYER}{KUN}!\p"
	.string "MR. BRINEY retired as a SAILOR,\n"
	.string "but I still see him out on the sea\l"
	.string "with his pet PEEKO sometimes.\p"
	.string "He must love the sea still.$"

MatchCall_Text_May2::
	.string "MAY: Hi, {PLAYER}{KUN}!\p"
	.string "You know how little towns like\n"
	.string "PETALBURG and DEWFORD have GYMS?\p"
	.string "For some reason, the big port of\n"
	.string "SLATEPORT doesn't have a GYM.\p"
	.string "When they finally build a GYM there,\n"
	.string "I should apply to be the LEADER.$"

MatchCall_Text_May3::
	.string "MAY: Hi, {PLAYER}{KUN}!\p"
	.string "Do you remember a man named\n"
	.string "the CUTTER in RUSTBORO?\l"
	.string "He had a house there, remember?\p"
	.string "Well, I found out his younger\n"
	.string "brother lives in MAUVILLE.\p"
	.string "Can you guess his name?\p"
	.string "… … … … … …\n"
	.string "… … … … … …\p"
	.string "The ROCK SMASH GUY!$"

MatchCall_Text_May4::
	.string "MAY: {PLAYER}{KUN}?\p"
	.string "RUSTURF TUNNEL…\n"
	.string "They named it that because it\l"
	.string "joins RUSTBORO and VERDANTURF.$"

MatchCall_Text_May5::
	.string "MAY: {PLAYER}{KUN}, how are you?\p"
	.string "I'm out on ROUTE 111 now.\p"
	.string "I'm going to get a rest at an old\n"
	.string "lady's house.\p"
	.string "She lives just north of\n"
	.string "the desert.$"

MatchCall_Text_May6::
	.string "MAY: Hi, {PLAYER}{KUN}!\p"
	.string "Did you know about the MIRAGE\n"
	.string "TOWER in the desert?\p"
	.string "They say, like a mirage, it seems\n"
	.string "to mysteriously come and go.\p"
	.string "I wish I could see it.$"

MatchCall_Text_May7::
	.string "MAY: {PLAYER}{KUN}, yahoo!\n"
	.string "I'm on ROUTE 119 now.\p"
	.string "There's a big river here, and\n"
	.string "it often rains.\p"
	.string "I got soaked!$"

MatchCall_Text_May8::
	.string "MAY: {PLAYER}{KUN}, hi.\p"
	.string "MT. PYRE is a memorial to POKéMON\n"
	.string "whose lives have ended.\p"
	.string "Maybe as a result, it's infested\n"
	.string "with many GHOST-type POKéMON!$"

MatchCall_Text_May9::
	.string "MAY: Hi, {PLAYER}{KUN}!\p"
	.string "I was thinking of going to the hot\n"
	.string "spring in LAVARIDGE.\p"
	.string "But on the way, around JAGGED\n"
	.string "PASS, I ran into some bad-looking\l"
	.string "characters. The mood was ugly!$"

MatchCall_Text_May10::
	.string "MAY: Hi, {PLAYER}{KUN}!\n"
	.string "Did you see the news?\p"
	.string "They say CAPT. STERN discovered\n"
	.string "the SEAFLOOR CAVERN while on his\l"
	.string "submarine expedition.$"

MatchCall_Text_May11::
	.string "MAY: Hi, {PLAYER}{KUN}!\n"
	.string "Don't you think it's neat?\p"
	.string "Even if you don't have a boat,\n"
	.string "you can cross the sea using\l"
	.string "a POKéMON's move.\p"
	.string "Did you know there's more?\p"
	.string "There's a POKéMON move that lets\n"
	.string "you go to the bottom of the sea.$"

MatchCall_Text_May12::
	.string "MAY: Hi, {PLAYER}{KUN}!\n"
	.string "Hope things are okay!\p"
	.string "Have you been on the sea and\n"
	.string "found your way to the other side\l"
	.string "blocked?\p"
	.string "Try diving deep underwater and\n"
	.string "following trenches.\p"
	.string "When you get to the other side,\n"
	.string "come up to the surface. Easy!$"

MatchCall_Text_May13::
	.string "MAY: Hi, {PLAYER}{KUN}!\p"
	.string "How's it going?\n"
	.string "Are you filling your POKéDEX?\p"
	.string "I heard a rumor that there are\n"
	.string "super-ancient POKéMON out there.\l"
	.string "And there are three of them!\p"
	.string "I would love to see even one…$"

MatchCall_Text_May14::
	.string "MAY: {PLAYER}{KUN}!\n"
	.string "I heard the rumors!\p"
	.string "You beat the SOOTOPOLIS GYM\n"
	.string "LEADER?\p"
	.string "That means you don't have far\n"
	.string "to go, do you?$"

MatchCall_Text_May15::
	.string "MAY: There isn't a single TRAINER\n"
	.string "left in HOENN who doesn't know who\l"
	.string "you are, {PLAYER}{KUN}!\p"
	.string "When I tell people that I'm friends\n"
	.string "with you, {PLAYER}{KUN}, they're all\l"
	.string "surprised!$"

MatchCall_Text_Brendan1::
	.string "BRENDAN: Hey, {PLAYER}!\p"
	.string "MR. BRINEY retired as a SAILOR,\n"
	.string "but I still see him out on the sea\l"
	.string "with his pet PEEKO sometimes.\p"
	.string "I guess he must love\n"
	.string "the sea still.$"

MatchCall_Text_Brendan2::
	.string "BRENDAN: Hey, {PLAYER}!\p"
	.string "I don't get how little towns like\n"
	.string "PETALBURG and DEWFORD have GYMS.\p"
	.string "I mean, not when the big port of\n"
	.string "SLATEPORT doesn't have a GYM.\p"
	.string "When they finally build a GYM there,\n"
	.string "I should apply to be the LEADER.$"

MatchCall_Text_Brendan3::
	.string "BRENDAN: Yo, {PLAYER}!\p"
	.string "Do you remember a guy named\n"
	.string "the CUTTER in RUSTBORO?\l"
	.string "He had a house there, right?\p"
	.string "Well, it turns out his little\n"
	.string "brother lives in MAUVILLE.\p"
	.string "Can you guess his name?\p"
	.string "… … … … … …\n"
	.string "… … … … … …\p"
	.string "The ROCK SMASH GUY!$"

MatchCall_Text_Brendan4::
	.string "BRENDAN: This voice… {PLAYER}?\p"
	.string "They gave RUSTURF TUNNEL its name\n"
	.string "because it joins RUSTBORO and\l"
	.string "VERDANTURF.\p"
	.string "Did you know that?$"

MatchCall_Text_Brendan5::
	.string "BRENDAN: {PLAYER}, what's up?\p"
	.string "Hey, I'm out on ROUTE 111 now.\p"
	.string "I'm going to rest up at an old\n"
	.string "lady's house north of the desert.\p"
	.string "If you're in the area, you should\n"
	.string "visit her, too.$"

MatchCall_Text_Brendan6::
	.string "BRENDAN: Hey, {PLAYER}!\p"
	.string "Did you know about the MIRAGE\n"
	.string "TOWER in the desert?\p"
	.string "They say, like a mirage, it can be\n"
	.string "seen only sometimes.\p"
	.string "I'd like to see that!$"

MatchCall_Text_Brendan7::
	.string "BRENDAN: Who's this? Oh, {PLAYER}?\n"
	.string "Guess what? I'm on ROUTE 119 now.\p"
	.string "There's a big river here, and\n"
	.string "it rains all the time.\p"
	.string "I got soaked to the bone!$"

MatchCall_Text_Brendan8::
	.string "BRENDAN: {PLAYER}!\p"
	.string "MT. PYRE is a memorial to POKéMON\n"
	.string "whose lives have ended.\p"
	.string "That's probably why it's infested\n"
	.string "with many GHOST-type POKéMON!$"

MatchCall_Text_Brendan9::
	.string "BRENDAN: Hey there, {PLAYER}.\p"
	.string "I was on my way back to the hot\n"
	.string "spring in LAVARIDGE.\p"
	.string "But around JAGGED PASS, I ran into\n"
	.string "some nasty-looking characters.\p"
	.string "Those creeps…\n"
	.string "I think they were TEAM MAGMA.$"

MatchCall_Text_Brendan10::
	.string "BRENDAN: Hi, {PLAYER}!\n"
	.string "Did you catch the news?\p"
	.string "They say CAPT. STERN discovered\n"
	.string "the SEAFLOOR CAVERN while on his\l"
	.string "submarine expedition.$"

MatchCall_Text_Brendan11::
	.string "BRENDAN: Hey there, {PLAYER}!\n"
	.string "Don't you think it's awesome?\p"
	.string "Even if you don't have a boat,\n"
	.string "you can cross the sea using\l"
	.string "a POKéMON's move.\p"
	.string "And, there's a move that lets you\n"
	.string "travel to the bottom of the sea.\p"
	.string "Man, POKéMON can do anything!$"

MatchCall_Text_Brendan12::
	.string "BRENDAN: Howdy, {PLAYER}!\n"
	.string "How are you holding up?\p"
	.string "Ever found your way to the other\n"
	.string "side blocked while on the sea?\p"
	.string "Try diving deep underwater and\n"
	.string "following trenches at the bottom.\p"
	.string "When you get to the other side,\n"
	.string "come up to the surface. Simple!$"

MatchCall_Text_Brendan13::
	.string "BRENDAN: Hey there, {PLAYER}!\p"
	.string "How's it going? Filling up your\n"
	.string "POKéDEX successfully?\p"
	.string "I heard a rumor that there are\n"
	.string "super-ancient POKéMON out there.\l"
	.string "And not just one--three!\p"
	.string "I'd love to catch even one…$"

MatchCall_Text_Brendan14::
	.string "BRENDAN: {PLAYER}!\n"
	.string "I heard the rumors!\p"
	.string "You beat the SOOTOPOLIS GYM\n"
	.string "LEADER? Awesome!\p"
	.string "You're getting awful close now!$"

MatchCall_Text_Brendan15::
	.string "BRENDAN: There isn't a TRAINER in\n"
	.string "all of HOENN who doesn't know who\l"
	.string "you are, {PLAYER}!\p"
	.string "When I tell people that I'm friends\n"
	.string "with you, {PLAYER}, they get pretty\l"
	.string "envious!$"

MatchCall_Text_Wally1::
	.string "WALLY: Oh, {PLAYER}!\p"
	.string "I've been getting healthier and\n"
	.string "more physically fit.\p"
	.string "I hope I can become a TRAINER like\n"
	.string "you soon, {PLAYER}!$"

MatchCall_Text_Wally2::
	.string "WALLY: {PLAYER}, hello!\p"
	.string "After RUSTURF TUNNEL went\n"
	.string "through, WANDA's been very happy!$"

MatchCall_Text_Wally3::
	.string "WALLY: Oh, {PLAYER}!\p"
	.string "I… I left my uncle's place in\n"
	.string "VERDANTURF without telling anyone.\p"
	.string "I wonder if he's furious with me…\p"
	.string "{PLAYER}, you understand how\n"
	.string "I feel, don't you?$"

MatchCall_Text_Wally4::
	.string "WALLY: {PLAYER}?\n"
	.string "It's me, WALLY!\p"
	.string "The world of TRAINERS is amazing!\p"
	.string "When I have my POKéMON with me,\n"
	.string "all sorts of people say hi!\p"
	.string "It's as if everyone's getting\n"
	.string "connected through POKéMON!$"

MatchCall_Text_Wally5::
	.string "WALLY: {PLAYER}? It's awesome!\n"
	.string "That RALTS we caught together?\l"
	.string "It evolved, {PLAYER}!\p"
	.string "Maybe I'm talented…\p"
	.string "Oh, but I shouldn't get a big head\n"
	.string "like that!\p"
	.string "After all, it's the POKéMON that\n"
	.string "should be praised!$"

MatchCall_Text_Wally6::
	.string "… … … … … …\n"
	.string "… … … … … …\p"
	.string "WALLY appears to be out of\n"
	.string "the POKéNAV's service area…$"

MatchCall_Text_Wally7::
	.string "WALLY: Oh, {PLAYER}!\p"
	.string "Before I met you, I hardly ever\n"
	.string "left my house…\p"
	.string "But now, I'm on an adventure with\n"
	.string "my very own POKéMON…\p"
	.string "{PLAYER}…\n"
	.string "Thank you…$"

MatchCall_Text_Scott1::
	.string "SCOTT: Howdy, {PLAYER}{KUN}!\p"
	.string "You know how POKéMON can be found\n"
	.string "everywhere?\p"
	.string "Like in the mountains, in the sea,\n"
	.string "in tall grass anywhere?\p"
	.string "Just like POKéMON, you can find\n"
	.string "TRAINERS everywhere, too.\p"
	.string "As a result, I have to hurry\n"
	.string "everywhere, too. Busy, busy!$"

MatchCall_Text_Scott2::
	.string "SCOTT: I'm on ROUTE 119 right now.\n"
	.string "It's teeming with TRAINERS!\p"
	.string "It's also overgrown with tall grass\n"
	.string "everywhere, it seems.\p"
	.string "Walking around in shorts here\n"
	.string "makes me all ticklish!$"

MatchCall_Text_Scott3::
	.string "SCOTT: Hi, hi, {PLAYER}{KUN}!\p"
	.string "Have you had the chance to climb\n"
	.string "MT. PYRE?\p"
	.string "The place is a memorial to POKéMON\n"
	.string "that have passed away.\p"
	.string "It's somewhere every TRAINER\n"
	.string "should climb to the top of once.$"

MatchCall_Text_Scott4::
	.string "SCOTT: Hi, {PLAYER}{KUN}!\p"
	.string "I've been hearing about these odd\n"
	.string "gangs being a nuisance.\p"
	.string "TEAM MAGMA and TEAM AQUA,\n"
	.string "I think they were.\p"
	.string "I would think there'd be some\n"
	.string "skilled TRAINERS among them.\p"
	.string "…But if they're thugs…$"

MatchCall_Text_Scott5::
	.string "SCOTT: Oh, hi, {PLAYER}{KUN}.\p"
	.string "Might there be tough TRAINERS\n"
	.string "at the bottom of the sea?\p"
	.string "I can't go check for myself.\n"
	.string "I can't swim, for one.\l"
	.string "And I don't raise POKéMON…$"

MatchCall_Text_Scott6::
	.string "SCOTT: Hi, hi, {PLAYER}{KUN}!\p"
	.string "You know that you can challenge\n"
	.string "the POKéMON LEAGUE when you've\l"
	.string "collected all the GYM BADGES?\p"
	.string "With your talent, becoming the\n"
	.string "CHAMPION isn't a pipe dream.\p"
	.string "But did you know?\n"
	.string "There's somewhere even better.\p"
	.string "But, that's all I'm willing to say\n"
	.string "for the time being.\p"
	.string "It's something you can look\n"
	.string "forward to.\p"
	.string "When you've won your way through\n"
	.string "the POKéMON LEAGUE into the HALL\l"
	.string "OF FAME!$"

MatchCall_Text_Scott7::
	.string "… … … … … …\n"
	.string "… … … … … …\p"
	.string "SCOTT appears to be out of\n"
	.string "the POKéNAV's service area…$"

MatchCall_Text_Norman1::
	.string "DAD: In RUSTBORO, there's a man\n"
	.string "that goes by the odd name of\l"
	.string "the CUTTER.\p"
	.string "If you're in the area, you should\n"
	.string "pay him a visit.$"

MatchCall_Text_Norman2::
	.string "DAD: Hm… Little by little, but also\n"
	.string "very surely, you're getting\l"
	.string "tougher, {PLAYER}.\p"
	.string "The stronger you get, the farther\n"
	.string "and higher you soar from Mother\l"
	.string "and me…\p"
	.string "This feeling is hard to explain.$"

MatchCall_Text_Norman3::
	.string "DAD: I see…\n"
	.string "You've collected four GYM BADGES…\p"
	.string "There's no avoiding it now.\n"
	.string "We will battle like I promised.\p"
	.string "Come anytime.\n"
	.string "We'll all be waiting for you!$"

MatchCall_Text_Norman4::
	.string "DAD: {PLAYER}! You'd better go visit\n"
	.string "Mother every so often.\p"
	.string "I'm going to remain here and\n"
	.string "redouble my training.\p"
	.string "The way of battling is deep\n"
	.string "and unforgiving!$"

MatchCall_Text_Norman5::
	.string "DAD: Oh, hi, {PLAYER}!\p"
	.string "What's that? MAGMA EMBLEM?\n"
	.string "I don't know what that's about.\p"
	.string "But with a name like that, it may\n"
	.string "be somehow linked to a volcano!$"

MatchCall_Text_Norman6::
	.string "DAD: Hiyah! Haah! Dwah!\p"
	.string "…Oh? {PLAYER}!\p"
	.string "You caught me right in the middle\n"
	.string "of a POKéMON training session!$"

MatchCall_Text_Norman7::
	.string "DAD: {PLAYER}!\p"
	.string "Who would've thought you'd become\n"
	.string "the POKéMON LEAGUE CHAMPION…\p"
	.string "Okay!\n"
	.string "I won't be left behind!$"

MatchCall_Text_Norman8::
	.string "DAD: Hm? {PLAYER}?\n"
	.string "What good timing!\p"
	.string "This time, I'm going to challenge\n"
	.string "you to battle.\p"
	.string "I'm waiting in the PETALBURG GYM.\n"
	.string "Accept my challenge anytime!$"

MatchCall_Text_Norman9::
	.string "DAD: …You amaze me, {PLAYER}.\n"
	.string "How much higher will you soar?$"

MatchCall_Text_Steven1::
	.string "STEVEN: Hi, {PLAYER}{KUN}!\p"
	.string "Have you been to MAUVILLE\n"
	.string "already?\p"
	.string "You should visit the BIKE SHOP\n"
	.string "and get a MACH BIKE.\p"
	.string "Then, try exploring the GRANITE\n"
	.string "CAVE thoroughly.\p"
	.string "You may make a new discovery\n"
	.string "there.$"

MatchCall_Text_Steven2::
	.string "STEVEN: Hi, {PLAYER}{KUN}!\p"
	.string "I've met a lot of different\n"
	.string "TRAINERS so far.\p"
	.string "But you're one of a kind.\n"
	.string "You're not like anyone else.$"

MatchCall_Text_Steven3::
	.string "STEVEN: Hi, {PLAYER}{KUN}!\p"
	.string "When you're on an adventure with\n"
	.string "your POKéMON, what do you think?\p"
	.string "Do you consider them to be strong\n"
	.string "partners?\p"
	.string "Do you think of them as fun\n"
	.string "companions?\p"
	.string "Depending on how you think, your\n"
	.string "adventure's significance changes.$"

MatchCall_Text_Steven4::
	.string "STEVEN: Hello?\n"
	.string "{PLAYER}{KUN}?\p"
	.string "I'm involved in a spot of trouble\n"
	.string "at the SPACE CENTER.\p"
	.string "I'm sorry, but I can't talk now.\n"
	.string "Bye!$"

MatchCall_Text_Steven5::
	.string "STEVEN: Oh!\n"
	.string "{PLAYER}{KUN}!\p"
	.string "There's no need to talk.\n"
	.string "It's past time for talking.\p"
	.string "You have to believe in yourself\n"
	.string "and do what's right.$"

MatchCall_Text_Steven6::
	.string "… … … … … …\p"
	.string "STEVEN appears not to be getting\n"
	.string "the call…$"

MatchCall_Text_Steven7::
	.string "STEVEN: {PLAYER}{KUN}… Congratulations\n"
	.string "for entering the HALL OF FAME.\p"
	.string "… … … … … …\n"
	.string "… … … … … …\p"
	.string "I hope we can meet again\n"
	.string "somewhere!$"

MatchCall_Text_BirchRegisterCall:
	.string "PROF. BIRCH: Oh, {PLAYER}{KUN}!\n"
	.string "I've already heard about you!\p"
	.string "It seems your POKéNAV's been\n"
	.string "upgraded with MATCH CALL.\p"
	.string "Well, I should register, too!\p"
	.string "That way, I'd be able to examine\n"
	.string "your POKéDEX even while you're\l"
	.string "out in the field.\p"
	.string "… … … … … …$"

MatchCall_Text_RegisteredBirch:
	.string "Registered PROF. BIRCH\n"
	.string "in the POKéNAV.$"

MatchCall_Text_UnusedProfBirch:
	.string "PROF. BIRCH: When one has both\n"
	.string "the POKéDEX and POKéNAV, studying\l"
	.string "POKéMON becomes more fun, eh?$"

MatchCall_Text_MrStone1::
	.string "MR. STONE: Oh? {PLAYER}{KUN}!\p"
	.string "Since you called me, the POKéNAV\n"
	.string "must be working properly!\p"
	.string "Other people will be registered,\n"
	.string "so try calling them up, too!\p"
	.string "Good! Good!\n"
	.string "You seem to be quite happy!\p"
	.string "Hm…\n"
	.string "How could I know that?\p"
	.string "It's because I'm looking down at\n"
	.string "you from my office window!\p"
	.string "Wahahaha!\n"
	.string "See you again!$"

MatchCall_Text_MrStone2::
	.string "MR. STONE: Oh? {PLAYER}{KUN}!\p"
	.string "What's wrong? Have you forgotten\n"
	.string "about that little errand of mine?\p"
	.string "I need you to deliver my letter\n"
	.string "to STEVEN in DEWFORD.\p"
	.string "After that, deliver our parcel to\n"
	.string "CAPT. STERN in SLATEPORT.\p"
	.string "You remember, don't you?\p"
	.string "Now, since I am a busy PRESIDENT,\n"
	.string "I have to go! Bye-bye!$"

MatchCall_Text_MrStone3::
	.string "MR. STONE: Oh! {PLAYER}{KUN}!\p"
	.string "Ah, so you've met STEVEN!\n"
	.string "I'd better reward you, then!\p"
	.string "When you visit RUSTBORO again,\n"
	.string "come see me at my office.\p"
	.string "I'll be waiting for you!$"

MatchCall_Text_MrStone4::
	.string "MR. STONE: Oh! {PLAYER}{KUN}!\p"
	.string "Did you know that DEVON was\n"
	.string "digging the RUSTURF TUNNEL?\p"
	.string "But we shut down the operation to\n"
	.string "protect the POKéMON in the area.\p"
	.string "It's a no-brainer, really.\p"
	.string "It's more important to let POKéMON\n"
	.string "live in peace than worry about our\l"
	.string "own convenience.$"

MatchCall_Text_MrStone5::
	.string "MR. STONE: Hello, hello, {PLAYER}{KUN}!\p"
	.string "I heard from someone in PETALBURG\n"
	.string "that you're NORMAN's child!\p"
	.string "No wonder you're such a capable\n"
	.string "being!$"

MatchCall_Text_MrStone6::
	.string "MR. STONE: What's that?\p"
	.string "You battled your own father and\n"
	.string "defeated him?\p"
	.string "That's astounding!\p"
	.string "I had no idea that I befriended\n"
	.string "someone so special! Wahaha!$"

MatchCall_Text_MrStone7::
	.string "Hello!\n"
	.string "This is DEVON CORPORATI…\l"
	.string "Oh, hello, {PLAYER}!\p"
	.string "Our PRESIDENT was here a little\n"
	.string "while ago, but he's gone out.\p"
	.string "Our PRESIDENT is busy, but you\n"
	.string "seem to be just as busy, {PLAYER}.$"

MatchCall_Text_MrStone8::
	.string "…Huh? …What's that?\p"
	.string "GROU… Yes? …DON?\p"
	.string "You're breaking up…\n"
	.string "…can't hear…\p"
	.string "BZZZZ…$"

MatchCall_Text_MrStone9::
	.string "…Huh? …What's that?\p"
	.string "Seaflo… Yes? …Caver…?\p"
	.string "You're breaking up…\n"
	.string "…can't hear…\p"
	.string "BZZZZ…$"

MatchCall_Text_MrStone10::
	.string "MR. STONE: {PLAYER}{KUN}! It's me!\p"
	.string "You were apparently involved in all\n"
	.string "sorts of things, but I, being busy,\l"
	.string "haven't a clue exactly what!\p"
	.string "However, I urge you to take\n"
	.string "the road you believe in and walk it.\p"
	.string "I'll always be in your corner!\n"
	.string "Take care!$"

MatchCall_Text_MrStone11::
	.string "MR. STONE: … … … … … …\n"
	.string "Is this maybe {PLAYER}{KUN}?\p"
	.string "Your voice is so full of confidence,\n"
	.string "I didn't recognize you right off!\p"
	.string "Hm! You must come visit us at DEVON\n"
	.string "sometime!$"
