MatchCall_WildBattleText1::
	.string "Kaixo! {PLAYER}{KUN}, aupa!\n"
	.string "{STR_VAR_1} naiz.\p"
	.string "{STR_VAR_2} bat ikusi nuen behin\n"
	.string "baina ezin izan nuen harrapatu.\p"
	.string "Ia-ia lortu nuen alabaina!\n"
	.string "Beno, hurrengora arte!$"

MatchCall_WildBattleText2::
	.string "Kaixo, {PLAYER}{KUN}.\n"
	.string "{STR_VAR_1} naiz.\p"
	.string "{STR_VAR_2} eder bat harrapatzen\n"
	.string "saiatu nintzen behin.\p"
	.string "Baina ihes egin zidan.\n"
	.string "Lur jota geratu nintzen!\p"
	.string "Beno, aio!$"

MatchCall_WildBattleText3::
	.string "Aupa, {PLAYER}!\n"
	.string "Ni naiz, {STR_VAR_1}.\p"
	.string "Oraintxe saiatu naiz {STR_VAR_2}\n"
	.string "bat harrapatzen, baina ihes egin du.\p"
	.string "Hurbil ibili naiz ordea!\p"
	.string "Eguna izorratu dit…\n"
	.string "Ederki, ondo segi!$"

MatchCall_WildBattleText4::
	.string "Aizu, {PLAYER}{KUN}.\n"
	.string "{STR_VAR_1} naiz.\p"
	.string "Ezagutzen duzu {STR_VAR_2} POKéMONa?\n"
	.string "Ia-ia bat harrapatu dut.\p"
	.string "Duela gutxi izan da.\n"
	.string "Uste nuen lortu nuela, baina ihes egin du.\p"
	.string "Berriro ikusten badut, orduan ziur\n"
	.string "harrapatuko dudala.\p"
	.string "Beno, laister arte.$"

MatchCall_WildBattleText5::
	.string "Kaixo-kaixo, {PLAYER}{KUN}!\n"
	.string "{STR_VAR_1} naiz.\l"
	.string "Harrapatu duzu POKéMONik azkenaldian?\p"
	.string "Duela pixka bat bat harrapatzera\n"
	.string "iritsi nintzen ia, baina ihes egin zuen.\p"
	.string "Ongi, zaindu zaitez!$"

MatchCall_WildBattleText6::
	.string "Aizu, {PLAYER}{KUN}.\n"
	.string "{STR_VAR_1} naiz.\l"
	.string "Harrapatu duzu POKéMONik azkenaldian?\p"
	.string "AUrrekoan bat neureganatu nuen ia-ia.\n"
	.string "Baina nolabait ihes egin zuen.\p"
	.string "Zaindu zaitez.$"

MatchCall_WildBattleText7::
	.string "…Emm, {PLAYER}{KUN}?\n"
	.string "{STR_VAR_1} naiz.\p"
	.string "Segundu bat! Itxaron!\n"
	.string "Harrapatu dezaket {STR_VAR_2} hau…\p"
	.string "Aaarrrgh! Ihes egin du!\n"
	.string "Baina, barruan zegoen eta!$"

MatchCall_WildBattleText8::
	.string "{PLAYER}{KUN}, zer moduz?\n"
	.string "{STR_VAR_1} naiz ni.\p"
	.string "Azkenaldian lortu al duzu\n"
	.string "POKéMONik harrapatzea?\p"
	.string "Duela ez hainbeste ia-ia bat lortu\n"
	.string "nuen, baina ihes egin zidan azkenean.\p"
	.string "Gehiago saiatu beharko dut!\n"
	.string "Hurrengora arte!$"

MatchCall_WildBattleText9::
	.string "{PLAYER}{KUN}, kaixo!\n"
	.string "{STR_VAR_1} naiz!\p"
	.string "Ari al zara gero eta POKéMON\n"
	.string "gehiago biltzen?\p"
	.string "Ni ez naiz ari ondo azkenaldian!\n"
	.string "Denek ihes egiten didate!\p"
	.string "Aio, laister arte!$"

MatchCall_WildBattleText10::
	.string "E, {PLAYER}{KUN}, kaixo…\n"
	.string "{STR_VAR_1} naiz.\p"
	.string "Begira, aurrekoan kasik harrapatu\n"
	.string "nuen {STR_VAR_2} bat…\p"
	.string "Baina ziztu batean ihes egin zuen…\p"
	.string "Gehiago saiatu beharko naiz.\n"
	.string "Ondo segi.$"

MatchCall_WildBattleText11::
	.string "Ah, {PLAYER}{KUN}.\n"
	.string "Ni {STR_VAR_1} naiz.\l"
	.string "Zer moduz zaude?\p"
	.string "{STR_VAR_2} basati bat harrapatzen\n"
	.string "saiatu naiz lehen, baina ihes egin dit.\p"
	.string "Garaitua sentitzen naiz…$"

MatchCall_WildBattleText12::
	.string "Kaixo, {PLAYER}{KUN}.\n"
	.string "Ni naiz, {STR_VAR_1}.\l"
	.string "Oraindik POKéMONak harrapatzen a dituzu?\p"
	.string "Ni azkenaldian aritu naiz hauek\n"
	.string "harrapatzen saiatzen, baina ez da erraza.\p"
	.string "POKéMONak zientzia sakona dira, gero!$"

MatchCall_WildBattleText13::
	.string "Ah, kaixo, {PLAYER}{KUN}!\n"
	.string "{STR_VAR_1} naiz!\l"
	.string "POKéMONak harrapatzen aritu al zara?\p"
	.string "NI neu saiatu naiz hauek harrapatzen\n"
	.string "baina ez dut ezer askorik lortu.\p"
	.string "POKéMONak zientzia sakona dira, gero!$"

MatchCall_WildBattleText14::
	.string "Aupa, {PLAYER}{KUN}, zelan?\n"
	.string "{STR_VAR_1} naiz.\p"
	.string "Justu oraintxe, {STR_VAR_2} polit\n"
	.string "bat harrapatzen saiatu naiz.\p"
	.string "Ihes egin du, ordea!\n"
	.string "Ene, ez dakizu nolako etsipena!\p"
	.string "Aio-aio!$"

MatchCall_WildBattleText15::
	.string "Aizu, {PLAYER}!\n"
	.string "{STR_VAR_1} naiz!\p"
	.string "POKéMON batzuk harrapatzea pentsatzen\n"
	.string "aritu naiz azkenaldian.\p"
	.string "Baina ez dut bat bera ere aurkitzen.\n"
	.string "A zer nolako misterioa!\p"
	.string "Guztiz harrituta nago!\n"
	.string "Ondo ibili!$"

MatchCall_NegativeBattleText1::
	.string "Epa! {PLAYER}{KUN}, kaixo!\n"
	.string "{STR_VAR_1} naiz.\p"
	.string "ENTRENATZAILE baten aurka borrokatu\n"
	.string "dut, baina galdu egin dut.\p"
	.string "A zer nolako zapuztua.\n"
	.string "Beno, laister arte!$"

MatchCall_NegativeBattleText2::
	.string "Kaixo, {PLAYER}{KUN}.\n"
	.string "{STR_VAR_1} naiz.\p"
	.string "Gure borrokaren ostean beste baten\n"
	.string "aurka borrokatu nuen.\p"
	.string "Hurbil egon nitzen, baina azkenean\n"
	.string "galdu egin nuen. Zer pena!$"

MatchCall_NegativeBattleText3::
	.string "Aupa kaixo, {PLAYER}!\n"
	.string "Ni naiz, {STR_VAR_1}.\p"
	.string "Borroka batean zapaldu berri naute.\p"
	.string "Nire taldea hobetu beharrean\n"
	.string "nago, alajaina!$"

MatchCall_NegativeBattleText4::
	.string "Iepa, {PLAYER}.\n"
	.string "{STR_VAR_1} naiz.\p"
	.string "Atzo beste borroka bat egin nuen,\n"
	.string "baina ez nuen irabaztea lortu.\p"
	.string "Taldea hobetu behar dut.\n"
	.string "Beno, gero arte.$"

MatchCall_NegativeBattleText5::
	.string "Kaixo kaixo, {PLAYER}!\n"
	.string "{STR_VAR_1} naiz.\p"
	.string "Zer moduz zabiltza?\p"
	.string "Ni borrokan nabil buru-belarri,\n"
	.string "baina ez dut askotan irabazi.\p"
	.string "Ez dakit zer egin.\n"
	.string "Beno, laister arte!$"

MatchCall_NegativeBattleText6::
	.string "Iepa, {PLAYER}.\n"
	.string "{STR_VAR_1} naiz.\p"
	.string "Zer moduz zabiltza?\p"
	.string "Ni borrokan nabil gogor,\n"
	.string "baina zorte gutxirekin.\p"
	.string "Ez diot erritmoa harrapatzen, dirudienez.\n"
	.string "Zaindu zaitez.$"

MatchCall_NegativeBattleText7::
	.string "{STR_VAR_1} naiz.\n"
	.string "Zer moduz azkenaldian?\p"
	.string "Atzo borroka bat galdu nuen\n"
	.string "eta horretan pentsatzen aritu naiz.\p"
	.string "Planen bat prestatu behar dut…\n"
	.string "Agur.$"

MatchCall_NegativeBattleText8::
	.string "{PLAYER}{KUN}, zelan zabiltza?\n"
	.string "Ni {STR_VAR_1} naiz.\p"
	.string "Zelan daude zure POKéMONak?\n"
	.string "Aurrekoan borroka bat galdu nuen.\p"
	.string "Gogorrago saiatu beharko dut!\n"
	.string "Ikusi arte!$"

MatchCall_NegativeBattleText9::
	.string "{PLAYER}{KUN}, kaixo!\n"
	.string "{STR_VAR_1} naiz!\p"
	.string "Entzun, entzun, gauza bat kontatu\n"
	.string "behar dizut!\p"
	.string "POKéMON borroka bat izan dut lehen,\n"
	.string "baina azken segunduan galdu dut.\p"
	.string "Ai, zelako amorrua!$"

MatchCall_NegativeBattleText10::
	.string "{PLAYER}{KUN}, kaixo…\n"
	.string "{STR_VAR_1} naiz.\p"
	.string "Duela gutxi borroka bat izan dut.\n"
	.string "Galdu egin dut, ordea.\p"
	.string "Nire POKéMONak gehiago hazi behar ditut.\n"
	.string "Ondo segi.$"

MatchCall_NegativeBattleText11::
	.string "Ah, {PLAYER}{KUN}.\n"
	.string "{STR_VAR_1} naiz.\l"
	.string "Zer moduz zure POKéMONak?\p"
	.string "Beste borroka bat galdu berri dut nik.\p"
	.string "Beno, ikusi arte!$"

MatchCall_NegativeBattleText12::
	.string "Kaixo, {PLAYER}{KUN}.\n"
	.string "Ni naiz, {STR_VAR_1}.\l"
	.string "Oraindik borrokekin buru-belarri?\p"
	.string "Nik duela gutxi galdu egin dut, beraz,\n"
	.string "nire taldea entrenatzen aritu naiz.\p"
	.string "Hurrengora arte.$"

MatchCall_NegativeBattleText13::
	.string "Ah, kaixo, {PLAYER}{KUN}!\n"
	.string "{STR_VAR_1} naiz!\p"
	.string "Ondo ibili zarela espero dut.\p"
	.string "Duela ez hainbeste borroka batean\n"
	.string "izan naiz.\p"
	.string "{PLAYER}{KUN}, saiatu zu ere aktibo izaten.\n"
	.string "Ikusi arte!$"

MatchCall_NegativeBattleText14::
	.string "Aupa, {PLAYER}{KUN}.\n"
	.string "{STR_VAR_1} naiz.\p"
	.string "Ondo al zabiltza?\p"
	.string "Batzuetan etxera bueltatu behar zenuke,\n"
	.string "nire iritziz.\p"
	.string "Aio-aio!$"

MatchCall_PositiveBattleText1::
	.string "Epa! {PLAYER}{KUN}, kaixo!\n"
	.string "{STR_VAR_1} naiz!\p"
	.string "Beste ENTRENATZAILE baten aurka egin dut.\n"
	.string "Irabazi egin dut! Irabazi egin dut!\p"
	.string "Nire {STR_VAR_2} topera ibili da.\n"
	.string "Ez dakizu zeinen pozik nagoen!$"

MatchCall_PositiveBattleText2::
	.string "Kaixo, {PLAYER}{KUN}!\n"
	.string "{STR_VAR_1} naiz!\p"
	.string "Atzo borroka bat izan nuen eta\n"
	.string "irabazi egin nuen! Izugarria izan zen!$"

MatchCall_PositiveBattleText3::
	.string "Kaixo, {PLAYER}!\n"
	.string "Ni naiz, {STR_VAR_1}!\l"
	.string "Zer moduz doaz zure borrokak?\p"
	.string "Nik aurreko batean borroka bat izan nuen,\n"
	.string "eta nire {STR_VAR_2} izugarri ondo aritu zen!\p"
	.string "Hurrengoan zure aurka borrokatzen dudanean,\n"
	.string "{PLAYER}, ez dut galduko, ez horixe!$"

MatchCall_PositiveBattleText4::
	.string "Epa, {PLAYER}.\n"
	.string "{STR_VAR_1} naiz.\p"
	.string "Borroka bat izan dut lehen.\n"
	.string "Irabazi egin dut, baina oso justu.\p"
	.string "Nire {STR_VAR_2} asko saiatu da eta\n"
	.string "borroka inspiragarria egin du.$"

MatchCall_PositiveBattleText5::
	.string "Apakaixo, {PLAYER}{KUN}!\n"
	.string "{STR_VAR_1} naiz.\p"
	.string "Zer moduz zabiltza?\n"
	.string "Borrokaz borroka?\p"
	.string "ba nik justu bat irabazi dut!\n"
	.string "Nire {STR_VAR_2} bikain ibili da!\p"
	.string "Hurrengoan zuri irabaziko dizut,\n"
	.string "ikusiko duzu! Ongi bada, zaindu zaitez!$"

MatchCall_PositiveBattleText6::
	.string "Ei, {PLAYER}{KUN}.\n"
	.string "{STR_VAR_1} naiz.\p"
	.string "Zer moduz?\p"
	.string "Ni nire momentu onenean nago.\n"
	.string "Borroka bat irabazi berri dut eta.\p"
	.string "Zure aurka borrokatzen dudanean,\n"
	.string "ziur nago ez dudala galduko!$"

MatchCall_PositiveBattleText7::
	.string "{PLAYER}{KUN}?\n"
	.string "{STR_VAR_1} naiz.\p"
	.string "Nire {STR_VAR_2} oso indartsua da!\n"
	.string "Beste borroka bat irabazten lagundu dit!\p"
	.string "Zure kontra errebantxa bat izateko\n"
	.string "gogo handia dut.$"

MatchCall_PositiveBattleText8::
	.string "{PLAYER}{KUN}, zelan?\n"
	.string "Ni {STR_VAR_1} naiz.\p"
	.string "Espero dut ondo zabiltzala.\n"
	.string "Irabazi berri dudala esan nahi nizun.\p"
	.string "Nire {STR_VAR_2} bereziki gogor saiatu\n"
	.string "da borroka irabazteko.\p"
	.string "Beste batera arte!$"

MatchCall_PositiveBattleText9::
	.string "Ei, {PLAYER}{KUN}, kaixo!\n"
	.string "{STR_VAR_1} naiz ni!\p"
	.string "Zer moduz zure POKéMONak?\n"
	.string "Nireek oraintxe irabazi dute borroka bat!\p"
	.string "Nire {STR_VAR_2} ikusgarria izan da,\n"
	.string "esan behar dut!\p"
	.string "Zuk ikusi izana gustatuko zitzaidan!\n"
	.string "Hurrengora arte!$"

MatchCall_PositiveBattleText10::
	.string "{PLAYER}{KUN}, kaixo…\n"
	.string "{STR_VAR_1} naiz.\p"
	.string "Zer berri, zer moduz bizitza?\p"
	.string "Nire POKéMONak energiaz beteta daudela\n"
	.string "dirudi.\p"
	.string "Borroka bat irabazi berri dut beraiekin.\n"
	.string "Ondo segi.$"

MatchCall_PositiveBattleText11::
	.string "Ah, {PLAYER}{KUN}.\n"
	.string "{STR_VAR_1} naiz.\p"
	.string "Borrokarik bai azkenaldian?\n"
	.string "Nik beste bat irabazi dut gaur!\p"
	.string "Kristoren bolada daukat! Kar-kar-kar!\n"
	.string "Beno, ikusi arte!$"

MatchCall_PositiveBattleText12::
	.string "Kaixo, {PLAYER}{KUN}.\n"
	.string "Ni naiz, {STR_VAR_1}.\p"
	.string "Ondo zabilza aspaldian?\n"
	.string "Ni guztiz biziberrituta nabil!\p"
	.string "Oraintxe beste borroka bat irabazi dut.\n"
	.string "Oraindik ez nago erretiratzeko\l"
	.string "adinean, gazte!$"

MatchCall_PositiveBattleText13::
	.string "Ah, kaixo, {PLAYER}{KUN}!\n"
	.string "{STR_VAR_1} naiz ni!\p"
	.string "Ondo zabiltzala espero dut.\n"
	.string "Ni izugarri ondo nabil azkenaldian!\p"
	.string "Beste borroka bat irabazi berri dut.\n"
	.string "Aizu, oraindik ez naiz gazteen aurka\l"
	.string "galtzen hasi!\p"
	.string "Hurrengora arte!$"

MatchCall_PositiveBattleText14::
	.string "Aupa, {PLAYER}{KUN}.\n"
	.string "{STR_VAR_1} naiz.\p"
	.string "Borroka batean izan berri naiz, eta nire\n"
	.string "{STR_VAR_2} berebizikoa izan da!\p"
	.string "Zuk ikusi izana gustatuko zitzaidan,\n"
	.string "{PLAYER}{KUN}. Aio-aio!$"

MatchCall_SameRouteBattleRequestText1::
	.string "Aupa! {PLAYER}, kaixo!\n"
	.string "{STR_VAR_1} naiz.\p"
	.string "Nola? Itxaron, {STR_VAR_2} inguruan\n"
	.string "zabiltzala?\p"
	.string "Ba orduan elkarrekin borrokatu behar dugu!\n"
	.string "Itxaroten egongo naiz! Laister arte!$"

MatchCall_SameRouteBattleRequestText2::
	.string "Kaixo, {PLAYER}!\n"
	.string "{STR_VAR_1} naiz.\p"
	.string "Zer? {STR_VAR_2} inguruan zabiltza\n"
	.string "oraintxe bertan?\p"
	.string "Borrokatu nahi duzu orduan?\n"
	.string "Itxarongo dizut! Ondo segi!$"

MatchCall_SameRouteBattleRequestText3::
	.string "Aupa, {PLAYER}!\n"
	.string "Ni naiz, {STR_VAR_1}.\p"
	.string "Aizu, {STR_VAR_2} inguruan al\n"
	.string "zabiltza orain?\p"
	.string "Nahiko zenuke nire kontra borroka\n"
	.string "bat egin orain?\p"
	.string "Oraingoan ez dut galduko!\n"
	.string "Itxaroten egongo naiz! Orain arte!$"

MatchCall_SameRouteBattleRequestText4::
	.string "Iepa, {PLAYER}{KUN}.\n"
	.string "{STR_VAR_1} naiz.\p"
	.string "Nondik zabiltza orain?\n"
	.string "Zer? {STR_VAR_2}(e)n?\p"
	.string "Borrokatu nahi?\n"
	.string "Itxarongo dizut. Gero arte!$"

MatchCall_SameRouteBattleRequestText5::
	.string "Apakaixo, {PLAYER}{KUN}!\n"
	.string "{STR_VAR_1} naiz.\l"
	.string "Zer moduz zabiltza?\p"
	.string "Non zaudela esan duzu?\n"
	.string "{STR_VAR_2}, orduan?\p"
	.string "Eta zer iruditzen zaizu errebantxa\n"
	.string "bat jokatzen badugu orain?\p"
	.string "Adi egongo naiz zure zain.\n"
	.string "Laister arte!$"

MatchCall_SameRouteBattleRequestText6::
	.string "Iepa, {PLAYER}{KUN}.\n"
	.string "{STR_VAR_1} naiz.\l"
	.string "Zer moduz zure POKéMONak?\p"
	.string "Zer, bentan? {STR_VAR_2}\n"
	.string "inguruan zabiltza?\p"
	.string "Ba, orduan errebantxa bat egin\n"
	.string "behar genuke.\p"
	.string "Itxarongo dizut, noski.\n"
	.string "Aio!$"

MatchCall_SameRouteBattleRequestText7::
	.string "…Em, {PLAYER}{KUN}?\n"
	.string "{STR_VAR_1} naiz…\p"
	.string "Zer, {STR_VAR_2} inguruan zabiltzala\n"
	.string "justu orain?\p"
	.string "Borroka dezagun, beraz.\n"
	.string "Oraintxe bertan, esan nahi dut.\p"
	.string "Nire POKéMONak erakutsiko dizkizut.\n"
	.string "Itxarongo dizut.$"

MatchCall_SameRouteBattleRequestText8::
	.string "{PLAYER}{KUN}, zer moduz?\n"
	.string "{STR_VAR_1} telefonoan.\p"
	.string "Ondo zaudela espero dut.\n"
	.string "Ah, {STR_VAR_2} inguruan zaude.\p"
	.string "Nahi duzu nirekin borrokatu\n"
	.string "orduan?\p"
	.string "Itxarongo dizut.\n"
	.string "Laister arte!$"

MatchCall_SameRouteBattleRequestText9::
	.string "Ei, {PLAYER}{KUN}, aupa!\n"
	.string "{STR_VAR_1} naiz!\p"
	.string "Ondo al zabiltza?\n"
	.string "Zer, {STR_VAR_2} inguruan zabiltzala?\p"
	.string "Orduan ez al duzu uste borroka bat\n"
	.string "egin behar genukeela?\p"
	.string "Ez gehiegi itxaronarazi!$"

MatchCall_SameRouteBattleRequestText10::
	.string "{PLAYER}{KUN}, kaixo…\n"
	.string "{STR_VAR_1} naiz.\p"
	.string "Zer moduz zaude?\n"
	.string "Ah, {STR_VAR_2} inguruan zabiltza.\p"
	.string "Orduan borrokatu egin behar genuke.\p"
	.string "Prest nago, zuri itxaroten.\n"
	.string "Bizi ibili!$"

MatchCall_SameRouteBattleRequestText11::
	.string "Ei, {PLAYER}{KUN}.\n"
	.string "{STR_VAR_1} naiz.\p"
	.string "Ah, beraz orain {STR_VAR_2}\n"
	.string "aldetik zabiltza?\p"
	.string "Beno, orduan uste dut borroka\n"
	.string "bat egin behar genukeela, ezta?\p"
	.string "Itxarongo dizut!\n"
	.string "Oraintxe arte!$"

MatchCall_SameRouteBattleRequestText12::
	.string "Kaixo, {PLAYER}{KUN}.\n"
	.string "Ni naiz, {STR_VAR_1}.\l"
	.string "Nondik zabiltza orain?\p"
	.string "{STR_VAR_2}?\n"
	.string "Hori hurbil dago hemendik!\p"
	.string "Zer iruditzen zaizu oraintxe borroka\n"
	.string "bat egiten badugu?\p"
	.string "Itxarongo dizut.\n"
	.string "Aio!$"

MatchCall_SameRouteBattleRequestText13::
	.string "Ah, kaixo, {PLAYER}{KUN}!\n"
	.string "{STR_VAR_1} naiz!\p"
	.string "Ondo egongo zarela espero dut.\n"
	.string "Zer, {STR_VAR_2} aldetik al zabiltza?\p"
	.string "Hori ez dago hemendik oso urrun,\n"
	.string "etorri eta borroka bat egingo dugu.\p"
	.string "Itxarongo dizut.\n"
	.string "Agur.$"

MatchCall_SameRouteBattleRequestText14::
	.string "Kaixo, {PLAYER}{KUN}.\n"
	.string "{STR_VAR_1} naiz.\p"
	.string "Non zaudela? …{STR_VAR_2}(e)n?\n"
	.string "Hori oso hurbil dago.\p"
	.string "Ez al duzu uste borroka bat egin\n"
	.string "behar genukeela?\p"
	.string "Zure bila ibiliko naiz!\n"
	.string "Aio-aio!$"

MatchCall_DifferentRouteBattleRequestText1::
	.string "Epa! {PLAYER}, kaixo!\n"
	.string "{STR_VAR_1} naiz.\p"
	.string "Nahi al duzu nirekin borrokatu?\p"
	.string "Orduan zure zain egongo naiz\n"
	.string "{STR_VAR_2} inguruan!$"

MatchCall_DifferentRouteBattleRequestText2::
	.string "Kaixo, {PLAYER}!\n"
	.string "{STR_VAR_1} naiz.\p"
	.string "Nahiko zenuke nirekin borrokatu\n"
	.string "berriro?\p"
	.string "{STR_VAR_2} inguruan aurkituko\n"
	.string "nauzu. Itxarongo dizut!$"

MatchCall_DifferentRouteBattleRequestText3::
	.string "Aupa, {PLAYER}!\n"
	.string "Ni naiz, {STR_VAR_1}.\p"
	.string "Nire POKéMONak asko indartu dira\n"
	.string "azken aldian egon ginenetik.\p"
	.string "Beraien indarra neurtu nahi nuke\n"
	.string "zure POKÉMONEN aurka, {PLAYER}.\p"
	.string "Borroka dezagun, beraz!\p"
	.string "Zure zain egongo naiz {STR_VAR_2}\n"
	.string "aldetik.$"

MatchCall_DifferentRouteBattleRequestText4::
	.string "Iepa, {PLAYER}{KUN}.\n"
	.string "{STR_VAR_1} naiz.\l"
	.string "Zer moduz zabiltza?\p"
	.string "Nire POKéMONak asko indartu dira\n"
	.string "azkenaldian.\p"
	.string "Aizu, nahiko zenuke nire aurka\n"
	.string "borroka egin berriro?\p"
	.string "Elkartu gaitezen {STR_VAR_2}\n"
	.string "inguruan, ados?$"

MatchCall_DifferentRouteBattleRequestText5::
	.string "Apakaixo, {PLAYER}{KUN}!\n"
	.string "{STR_VAR_1} naiz.\p"
	.string "Nire POKéMONak asko hazten ari\n"
	.string "dira, oso indartsuak dira.\p"
	.string "Asko gustatuko litzaidake zure aurka\n"
	.string "beste borroka bat egitea.\p"
	.string "Zure zain egongo naiz {STR_VAR_2}\n"
	.string "aldetik. Laister arte!$"

MatchCall_DifferentRouteBattleRequestText6::
	.string "Epa, {PLAYER}{KUN}.\n"
	.string "{STR_VAR_1} naiz.\l"
	.string "Ondo izango zarela espero dut.\p"
	.string "Pentsatu dut zure aurka beste borroka\n"
	.string "bat egingo nukeela gustura. Zer iruditzen?\p"
	.string "Borrokatu nahi baduzu, etorri\n"
	.string "zaitez {STR_VAR_2}(e)ra.\p"
	.string "Agur!$"

MatchCall_DifferentRouteBattleRequestText7::
	.string "…Ein, {PLAYER}{KUN}?\n"
	.string "{STR_VAR_1} naiz…\l"
	.string "Eta? Ari al dira zure POKéMONak hazten?\p"
	.string "Nireak itzel indartu dira.\n"
	.string "Erakutsi nahi nizkizuke.\p"
	.string "{STR_VAR_2} inguruan egongo naiz.\n"
	.string "Etorri bisitan eta borrokatuko dugu.\p"
	.string "Laister arte.$"

MatchCall_DifferentRouteBattleRequestText8::
	.string "Ei, {PLAYER}{KUN}, zer martxa?\n"
	.string "{STR_VAR_1} deika.\p"
	.string "Ondo zaudela espero dut.\n"
	.string "Nire POKéMONak oso jostalariak dira.\p"
	.string "Hemendik hurbil bazaude, mesedez,\n"
	.string "errebantxa bat nahiko nuke.\p"
	.string "{STR_VAR_2} inguruan izango naiz.\n"
	.string "Ordura arte, aio!$"

MatchCall_DifferentRouteBattleRequestText9::
	.string "{PLAYER}{KUN}, kaixo!\n"
	.string "{STR_VAR_1} naiz!\l"
	.string "Zer moduz zure POKéMONak?\p"
	.string "Nire POKéMONak gero eta hobeak dira.\n"
	.string "Erakutsi nahi nizkizuke, {PLAYER}{KUN}.\p"
	.string "{STR_VAR_2} aldetik nabil orain,\n"
	.string "borroka dezagun hemendik bazabiltza.\p"
	.string "Laister arte!$"

MatchCall_DifferentRouteBattleRequestText10::
	.string "{PLAYER}{KUN}, kaixo…\n"
	.string "{STR_VAR_1} naiz.\l"
	.string "Zer, zer moduz doa dena?\p"
	.string "Nire POKéMONak lehen baino askoz ere\n"
	.string "indartsuagoak dira.\p"
	.string "Beste borroka bat nahi nuke,\n"
	.string "{PLAYER}{KUN}.\p"
	.string "{STR_VAR_2} aldetik ibiliko naiz.\n"
	.string "Etorri hurbil baldin bazaude.$"

MatchCall_DifferentRouteBattleRequestText11::
	.string "Ah, {PLAYER}{KUN}.\n"
	.string "{STR_VAR_1} naiz.\l"
	.string "Nondik zabiltza?\p"
	.string "Nire POKéMONak biziberrituta daude.\n"
	.string "Uste dut zure POKéMONak ikusteko\l"
	.string "gogo handiz daudela, {PLAYER}{KUN}.\p"
	.string "{STR_VAR_2} inguruan nago orain.\n"
	.string "Gure bila etorriko zara, ezta?$"

MatchCall_DifferentRouteBattleRequestText12::
	.string "Kaixo, {PLAYER}{KUN}.\n"
	.string "Ni naiz, {STR_VAR_1}.\p"
	.string "Esan behar dizut, nire POKéMONak oso\n"
	.string "indartsuak dira orain.\p"
	.string "Zure kontrako borroka batean ikusi\n"
	.string "nahi nituzke, {PLAYER}{KUN}.\p"
	.string "{STR_VAR_2} aldetik ibiliko gara.\n"
	.string "Etorri nahi duzunean!$"

MatchCall_DifferentRouteBattleRequestText13::
	.string "Ei, kaixo, {PLAYER}{KUN}!\n"
	.string "{STR_VAR_1} naiz!\l"
	.string "Ondo al daude zure POKéMONak?\p"
	.string "Nire POKéMONak oso osasuntsu daude,\n"
	.string "ematen du garaitezinak direla!\p"
	.string "Asko gustatuko litzaidake beste borroka\n"
	.string "bat egieta zure aurka.\p"
	.string "{STR_VAR_2} inguruan bazabiltza,\n"
	.string "etorri bisitan.$"

MatchCall_DifferentRouteBattleRequestText14::
	.string "Aupa, {PLAYER}{KUN}.\n"
	.string "{STR_VAR_1} naiz.\l"
	.string "Ondo zabiltza, ezta?\p"
	.string "Bai, bai! Nire POKéMONak inoiz\n"
	.string "baino indartsuago daude.\p"
	.string "Ez al duzu uste borroka bat egin\n"
	.string "behar genukeela, {PLAYER}{KUN}?\p"
	.string "Zure zain egongo naiz {STR_VAR_2}\n"
	.string "inguruan.\p"
	.string "Etorri nahi duzunean, ados?$"

MatchCall_PersonalizedText1::
	.string "Ni naiz, {STR_VAR_1}\n"
	.string "mendizale amorratua!\p"
	.string "Beno, elkar ezagutu genuenetik, mendiak\n"
	.string "gehiago apreziatzen al dituzu?\p"
	.string "Gutxitan ikusten zaitut mendibideetan…\p"
	.string "Hurrengoan, {STR_VAR_2} inguruan\n"
	.string "elkartuko gara.$"

MatchCall_PersonalizedText2::
	.string "{STR_VAR_1} naiz.\n"
	.string "Kaixo.\p"
	.string "Zuri buruz hitz egin berri diot\n"
	.string "ENTRENATZAILE bati.\p"
	.string "ENTRENATZAILE indartsua zarela esan diot,\n"
	.string "POKéMONak ondo tratatzen dituena.\p"
	.string "Espero dut mundu guztiak goraipatzen duen\n"
	.string "ENTRENATZAILE bilakatuko zarela.\p"
	.string "Ikusiko dugu elkar berriz!$"

MatchCall_PersonalizedText3::
	.string "Kaixo! {STR_VAR_1} naiz.\p"
	.string "Ez dakizu zelako lekuan nagoen.\n"
	.string "Usain goxoz beteta dago!\p"
	.string "Uste dut norbaitek BAIAK landatu dituela,\n"
	.string "eta loratu berri daude.\p"
	.string "Laister arte, egongo gara!$"

MatchCall_PersonalizedText4::
	.string "Kaixo! Hogeita hamar urte esploratzen,\n"
	.string "{STR_VAR_1} zure zerbitzura!\p"
	.string "Hemendik hara ibiltzeko energia\n"
	.string "soberan daukazula dirudi.\p"
	.string "Hondakinik aurkitu duzu azkenaldian?\n"
	.string "Abisatu zerbait aurkituz gero!\p"
	.string "Orain, barkatu, baina hondakinak\n"
	.string "esploratzera joan behar dut.$"

MatchCall_PersonalizedText5::
	.string "{STR_VAR_1} naiz!\p"
	.string "Ba al dakizu zertan nabilen?\n"
	.string "Hondartzatik olatuei begira!\p"
	.string "Ai… Olatuen aparra ederra da.\n"
	.string "Hemendik itsasoa ikusgarria da, zinez.\l"
	.string "Ene! A zer gosea, banoa, aio-aio!$"

MatchCall_PersonalizedText6::
	.string "Ñam-ñam…\n"
	.string "Ene, aupa, {STR_VAR_1} naiz.\l"
	.string "Atsegin dut hondartzan jatea.\p"
	.string "Nire POKéMONak eta ni oso ondo\n"
	.string "gabiltza. Energiak topera ditugu!\l"
	.string "Igeri egitera noa. Aio!$"

MatchCall_PersonalizedText7::
	.string "Kaixo, {STR_VAR_1} naiz…\p"
	.string "Pixka bat kostatzen ari zait ENTRENATZAILE\n"
	.string "GUAIEN kontu guzti hau…\p"
	.string "Denek uste dute ENTRENATZAILE perfektua\n"
	.string "naizela eta espektatiba horiek\l"
	.string "betetzen saiatzen ari naiz uneoro.\p"
	.string "Suposatzen dut hori dela ENTRENATZAILE\n"
	.string "GUAI izatea.\p"
	.string "Belarriak jaitsi beharko ditut…\n"
	.string "eta guztia isildu eta jasan.\p"
	.string "Zu zara hau kontatu diezaiokedan\n"
	.string "pertsona bakarra.\p"
	.string "baina, hurrengoan elkar ikustean,\n"
	.string "lasai, ez naiz kexatuko!$"

MatchCall_PersonalizedText8::
	.string "Iujuu, {STR_VAR_1} naiz!\n"
	.string "Zelan zabiltza?\p"
	.string "Nire POKéMONak entrenatzen aritu naiz\n"
	.string "zu helburutzat hartuta.\p"
	.string "Ez dut berriro ere galduko hurrengoan\n"
	.string "borrokatzen dugunean.\p"
	.string "Ez al da itzela lagun ENTRENATZAILEAK\n"
	.string "edukitzea? Hurrengora arte!$"

MatchCall_PersonalizedText9::
	.string "{STR_VAR_1} naiz…\n"
	.string "Oraintxe bertan, zure atzean…\l"
	.string "Ez al zegoen zerbait…?\p"
	.string "Hemen PIRO MENDIAN datzaten\n"
	.string "POKÉMONEN indarra…\p"
	.string "Zutaz hitz egiten ari zait…\p"
	.string "Hemendik ihes egin behar zenuke,\n"
	.string "eta ez atzera begiratu…\p"
	.string "Kar-kar…\n"
	.string "Adio…$"

MatchCall_PersonalizedText10::
	.string "{STR_VAR_1} naiz.\n"
	.string "Zer moduz?\p"
	.string "Ez al da erosoa elkarrengandik urruti\n"
	.string "egonda hitz egin ahal izatea?\p"
	.string "Lehen, norbaitekin hitz egitekotan,\n"
	.string "nire aitari eskatu behar izaten nion\l"
	.string "kotxez eramateko…\p"
	.string "Joan egin beharra daukat.\n"
	.string "Pozten naiz hizketa hau eduki izanaz.$"

MatchCall_PersonalizedText11::
	.string "{STR_VAR_1} naiz!\n"
	.string "Kontatu diezazuket gauza bat?\p"
	.string "SAFARI GUNEA oso atsegin dut, baina\n"
	.string "joaten naizenetan beti galtzen naiz!\p"
	.string "Belar garai horrekin!\n"
	.string "Gehiegi da guztia paretik kentzeko!\p"
	.string "Esan beharra nion norbaiti hau\n"
	.string "guzti hau!\p"
	.string "Banoa berriro SAFARI GUNERA!\n"
	.string "Aio-pelaio!$"

MatchCall_PersonalizedText12::
	.string "Kaixo, {STR_VAR_1} naiz.\n"
	.string "Bai, hori da, aberatsa naiz, bai.\p"
	.string "Azkenengoz elkar ikusi genuenetik\n"
	.string "asko aberastu naiz, gainera.\p"
	.string "Are gehiago, nire POKéMONak ere\n"
	.string "askoz indartsuagoak dira.\p"
	.string "Uste dut mundu guzti hau\n"
	.string "niretzako soilik existitzen dela!\p"
	.string "Ez duzu ezer esan behar!\n"
	.string "Mundu guztiak daki egia dela!\p"
	.string "Barkatuko didazu, afari oso\n"
	.string "garrantzitsu batera joan behar dut.$"

MatchCall_PersonalizedText13::
	.string "Ufufufufu…\n"
	.string "Ni naiz, {STR_VAR_1}…\p"
	.string "Ba al dakizu zer ari naizen ikusten?\n"
	.string "{STR_VAR_2} bikote bat borrokan.\p"
	.string "Agian garailea harrapatzen saiatuko naiz…\n"
	.string "Ufufufufufu…\p"
	.string "Em… Pixka bat okupatuta nago orain.\n"
	.string "Banoa.$"

MatchCall_PersonalizedText14::
	.string "Iep, {STR_VAR_1} naiz!\p"
	.string "Uste dut aspertzen ari naizela\n"
	.string "ITSASONTZI ABANDONATU honekin.\p"
	.string "Baina jada hemen nagoenez, eta gogoa\n"
	.string "dudanez zure aurka irabazteko,\l"
	.string "Pixka bat gehiago geratuko naiz.\p"
	.string "Zuk ere gogoa badaukazu, zergatik ez\n"
	.string "zara nigana etortzen?\p"
	.string "Uste dut gaur dela eguna alboko\n"
	.string "gelako gizonari erronka botatzeko\l"
	.string "eta borroka bat egiteko.\p"
	.string "Laister arte!$"

MatchCall_PersonalizedText15::
	.string "{STR_VAR_1} naiz!\n"
	.string "Itsasgizon bikaina!\p"
	.string "Badakizu zer uste dudan?\p"
	.string "Itsasoko ENTRENATZAILEAK direla\n"
	.string "guztietan indartsuenak!\p"
	.string "Nigandik ikasi eta itsasoan entrenatu\n"
	.string "behar zenuke…\p"
	.string "Ene, badator olatua!\p"
	.string "Entrenatzeko aukera bikaina!\n"
	.string "Barkatu, baina joan egin behar dut!$"

MatchCall_PersonalizedText16::
	.string "{STR_VAR_1} naiz! Entzun, nire\n"
	.string "POKéMONei karatea erakusten aritu naiz.\p"
	.string "Orain ni baino hobeak dira, ordea!\n"
	.string "Beraien aurka galdu eta galdu ari naiz!\p"
	.string "Nire POKÉMONEN aurka galtzen badut ere,\n"
	.string "ez dut galduko beste ENTRENATZAILE\l"
	.string "baten aurka, ez horixe!\p"
	.string "Berriro borrokatu behar dugu!\n"
	.string "Jiaaaa!$"

MatchCall_PersonalizedText17::
	.string "Ni naiz, {STR_VAR_1}.\n"
	.string "Zer moduz doaz zure bidaiak?\p"
	.string "…Eneee, benetan ari al zara?\n"
	.string "Biziki estimulagarria dirudi horrek!\p"
	.string "Uste dut kanta bat idatziko dudala\n"
	.string "zure abenturetako baten inguruan.\p"
	.string "…Ei, aizu, badator, badator.\n"
	.string "Jada ari naiz riffak imaginatzen.\p"
	.string "Kanta hau ondo idatzi behar dut bizi,\n"
	.string "joan egin behar dut! Aio!$"

MatchCall_PersonalizedText18::
	.string "Ni {STR_VAR_1} naiz…\n"
	.string "Entzun nire abesti berri.\p"
	.string "Lalala, {STR_VAR_2}, {STR_VAR_2}!\n"
	.string "Zergatik zara horren {STR_VAR_2}?\l"
	.string "Zergatik ezin naiz izan zu, {STR_VAR_2}?\l"
	.string "Lala, {STR_VAR_2} eta {STR_VAR_1},\l"
	.string "{STR_VAR_1} eta {STR_VAR_2}…\p"
	.string "Berriro errepika, eta isildu…$"

MatchCall_PersonalizedText19::
	.string "{STR_VAR_1} naiz, badakizu,\n"
	.string "kanpinean aditua!\p"
	.string "Borroka egin genuenean, zure aurka galdu\n"
	.string "egin nuen, erraz.\p"
	.string "Azken finean, ni kanpinean naiz\n"
	.string "aditua eta.\p"
	.string "Galdu ala irabazi, oso atsegin dut\n"
	.string "borrokatzea kanpinean nagoenean.\p"
	.string "Borrokatu berriz gurekin, ados?\n"
	.string "Ah, eta goazen elkarrekin kanpinera!$"

MatchCall_PersonalizedText20::
	.string "Ni naiz, ni, {STR_VAR_1}!\p"
	.string "Beste mendi batzuetara igotzea nahiago\n"
	.string "nuke, hona igo baino, egia esan.\p"
	.string "Baina ez dakit ERRAUTS MENDIN\n"
	.string "bezalako neskarik aurkituko nukeen.\p"
	.string "Neskak dituen beste mendirik ezagutzen\n"
	.string "baduzu, abisatu, mesedez!\p"
	.string "Ehehehe, ondo segi!$"

MatchCall_PersonalizedText21::
	.string "… … … … … …\n"
	.string "… … … … … …\l"
	.string "{STR_VAR_1} naiz…\p"
	.string "… … … … … …\n"
	.string "… … … … … …\l"
	.string "Gaurkoz nahikoa…$"

MatchCall_PersonalizedText22::
	.string "Ni {STR_VAR_1} naiz. Gaur, zurekin\n"
	.string "hitz egingo nuelako susmoa nuen.\p"
	.string "Zure aurka irabazteko daukadan gogoa\n"
	.string "handiagoa da egunetik egunera.\p"
	.string "Baduzu halako aurkari bat jada, baietz?\n"
	.string "Bera izan nahiko nuke…\p"
	.string "Pozten naiz entzun didazulako.\n"
	.string "Agur!$"

MatchCall_PersonalizedText23::
	.string "{STR_VAR_1} naiz.\p"
	.string "Nigandik hurbil ENTRENATZAILE\n"
	.string "indartsuren bat dabilenean, sentitu\l"
	.string "egin dezaket, nolabait.\p"
	.string "Hemendik hurbil ibili zara, {PLAYER}{KUN}?\n"
	.string "Agian zu izan zara.\p"
	.string "Zure bisitaren zain geldituko naiz.\n"
	.string "Agur!$"

MatchCall_PersonalizedText24::
	.string "Kaixo, {STR_VAR_1} naiz.\n"
	.string "Itxura ona duzu, {PLAYER}{KUN}.\p"
	.string "Munduan zehar bidaian ibili naiz,\n"
	.string "baina esan beharra dut eskualde hau\l"
	.string "bereziki atsegin zaidala.\p"
	.string "Hemen geratuko naiz denbora batez.\n"
	.string "Agian berriro elkartuko gara?\p"
	.string "Ez ditut zure teknika miragarriak\n"
	.string "ahaztu.\p"
	.string "Errebantxaren zain nago.$"

MatchCall_PersonalizedText25::
	.string "Zintz… Ni… {STR_VAR_1} naiz…\n"
	.string "…Zintz…\p"
	.string "ROXANNEk errieta egin dit gaur\n"
	.string "klasean.\p"
	.string "Baina ez dut gorroto hala ere.\p"
	.string "ROXANNEk zehazki esaten dit zer egin\n"
	.string "dudan gaizki, ikasi ahal izateko.\p"
	.string "Bihar ere ENTRENATZAILE ESKOLARA \n"
	.string "joango naiz berriro, noski!\p"
	.string "Ikusi arte!$"

MatchCall_PersonalizedText26::
	.string "{STR_VAR_1} naiz!\p"
	.string "ROXANNEk bere aurka borroka egiten\n"
	.string "utzi zidan atzo.\p"
	.string "Emaitza…\n"
	.string "Oso txarra, jakingo ez bazenu bezala.\p"
	.string "Baina asko poztu nintzen ROXANNEk\n"
	.string "bere aurka borrokatzen uzteagatik soilik!\p"
	.string "Ez dakizu zenbat miresten dudan\n"
	.string "bera!\p"
	.string "Adi egon eta lan asko egingo dut!\n"
	.string "Joan beharra dut!$"

MatchCall_PersonalizedText27::
	.string "kaixo, ANNA naiz! MEG, nire kide\n"
	.string "gaztearekin nago gaur ere.\p"
	.string "Oso atsegin dut MEG eta POKéMONak\n"
	.string "zaintzea. Hain dira politak!\p"
	.string "Nire anai-arrebak balira bezala\n"
	.string "zaindu nahi nituzke!\p"
	.string "Ei, kaixo, MEG!\n"
	.string "Jaso al dituzu opilak?\p"
	.string "Zer? Ez, ez, ez naiz tratatzen ari nire\n"
	.string "esklabua izango bazina bezala!\p"
	.string "Partida galdu duzu, beraz ogia erosi\n"
	.string "behar duzu zigor gisan!\p"
	.string "Ez zintuzket inoiz esklabu gisan,\n"
	.string "tratatuko MEG! berezia zara niretzat!\p"
	.string "Joan egin behar dut.\n"
	.string "Hamaiketakoa egiteko ordua iritsi da!$"

MatchCall_PersonalizedText28::
	.string "Maite ditut POKéMONak!\n"
	.string "FAN KLUBEKO {STR_VAR_1} naiz!\p"
	.string "Entzun honako hau!\n"
	.string "Nire POKéMON kuttunak…\p"
	.string "Pffff! Kar-kar-kar!\n"
	.string "Ezin dut ezer gehiago esan! Sekretua da!\l"
	.string "Politegia da hitzez azaltzeko!\p"
	.string "Ene, nire {STR_VAR_2} txikiak\n"
	.string "{POKEBLOCK} bat gura du!\p"
	.string "Zeinen polita den, benetan!\p"
	.string "Barkatu, baina ez dut hitz egin!\n"
	.string "Hurrengoan kontatu beharko dizut!$"

MatchCall_PersonalizedText29::
	.string "Ohoho!\p"
	.string "{STR_VAR_1} naiz ni! Nire POKéMON\n"
	.string "maiteaz hitz egin behar dizut!\p"
	.string "Mesedez, entzun hau.\n"
	.string "Nire {STR_VAR_2} maitea da.\p"
	.string "Norbaitek hartzen badu, zuzenean\n"
	.string "nire besoetara salto egiten du!\p"
	.string "Ene… Ene… Existitzen al da horren\n"
	.string "gauza ederrik?\p"
	.string "Zeinen sentsazio gozoa!\p"
	.string "Nire zoriontasunaren zatitxo bat\n"
	.string "eman nahi nizuke.\p"
	.string "Beno, joan egin behar dut.\n"
	.string "Agur!$"

MatchCall_PersonalizedText30::
	.string "Ni… {STR_VAR_1} naiz.\n"
	.string "Jendeak ADITU deitzen dit.\p"
	.string "Baina gauza bat ondo dakit.\n"
	.string "Ezingo nuke ADITU izan nik\l"
	.string "bakarrik.\p"
	.string "Soilik POKÉMONEN laguntzarekin bihur\n"
	.string "daiteke ENTRENATZAILEA ADITU.\p"
	.string "Humph! Uste dut zeozer oso sakon\n"
	.string "eta interesgarria esan dudala!\p"
	.string "Gogo onez utziko zaitut!$"

MatchCall_PersonalizedText31::
	.string "{STR_VAR_1} naiz.\n"
	.string "Pozten naiz zurekin hitz egiteaz!\p"
	.string "Bizirik eta freskatuta sentitzen\n"
	.string "naiz, bainuontzi honetan plisti-plasta.\p"
	.string "ENTRENATZAILE gazteen aurka borrokan\n"
	.string "aritu naiz elkar ezagutu genueetik, baina\l"
	.string "zu zara denetan onena.\p"
	.string "Esango nuke zahartzen zarenean\n"
	.string "ADITU bihurtuko zarela! Ohohoho…$"

MatchCall_PersonalizedText32::
	.string "Iuju! Ni {STR_VAR_1} naiz!\n"
	.string "Zer moduz?\p"
	.string "Agian nire imaginazioa da, baina\n"
	.string "borroka bat irabaztean, nire prakak\l"
	.string "hobeto bezala sentitzen ditut. Materialki.\p"
	.string "Zer esan nahi dudan horrekin?\n"
	.string "Zaila da esplikatzen, baina…\l"
	.string "Nola esan dezaket, ea…\l"
	.string "Zetazkoak ematen dute nire prakek!\p"
	.string "Eta zure aurka borrokatzena, {PLAYER}{KUN},\n"
	.string "azkure itzela besterik ez zidaten eman.\p"
	.string "… … … … … …\n"
	.string "Ez didazu sinesten?\l"
	.string "Ehehehe, hori da dena! Agur!$"

MatchCall_PersonalizedText33::
	.string "Aupa txo!\n"
	.string "{STR_VAR_1} naiz!\p"
	.string "Beti bezala, birritan pentsatu gabe\n"
	.string "ari naiz arrantzan!\p"
	.string "Itsasoaz eta ibaiez gain, ba al dago\n"
	.string "arrantzatzeko beste lekurik?\p"
	.string "Edozein lekutan egonda ere, arrantzarako\n"
	.string "gogoa sartzen zait!\p"
	.string "Ai, kaka zaharra!\n"
	.string "Pita kateatuta geratu zait!\p"
	.string "Joan egin behar dut! Arrantzarako\n"
	.string "lekurik aurkitzen baduzu, esan!$"

MatchCall_PersonalizedText34::
	.string "Ei, kaixo! {STR_VAR_1} naiz.\n"
	.string "Lasai-lasai al zabiltza?\p"
	.string "Txiki-txikitatik, oso ume lasaia\n"
	.string "izan naiz, ulertzen?\p"
	.string "Inoiz ez naiz ezerekin estresatuta\n"
	.string "edo presaka ibili.\p"
	.string "Baina ezetz asmatu, orain\n"
	.string "TRIATLETA bihurtu naiz.\p"
	.string "Inoiz ez dakizu norantz eramango\n"
	.string "zaituen bizitzak, ezetz?\p"
	.string "Orain ENTRENATZAILEA zara, baina\n"
	.string "etorkizunean auskalo zer izango zaren!\p"
	.string "Imaginatu irakasle izango bazina\n"
	.string "edo artista, agian. Itzela, e?\p"
	.string "Baina, aizu, lasai. Lasai hartu.\n"
	.string "Ikusi arte.$"

MatchCall_PersonalizedText35::
	.string "Ni {STR_VAR_1} naiz!\n"
	.string "Bizikletan nabil orain.\p"
	.string "Maite dut igerian eta korrika aritzea,\n"
	.string "baina bizikleta da nire kuttunena!\p"
	.string "Nire gorputza haizearekin bat izango\n"
	.string "balitz bezala sentitzen dut.\p"
	.string "Hegan egongo banintz bezain\n"
	.string "kitzikagarria da!\p"
	.string "Ongi! Gaur errekor berria ezarriko\n"
	.string "dut BIDEGORRIAN!\p"
	.string "Zuk ere saiatu behar zenuke!\n"
	.string "Ikusi arte!$"

MatchCall_PersonalizedText36::
	.string "Iepa, ni {STR_VAR_1} naiz! Triatloi\n"
	.string "erdi-erdian harrapatu nauzu!\p"
	.string "baina, aizu, beti dut denbora hitz\n"
	.string "egiteko!\p"
	.string "POKÉMONEKIN batera ariketa egitea\n"
	.string "itzela da!\p"
	.string "Elkarrekin hitz egin gabe ere, bihotz\n"
	.string "bakarra bagenu bezala da kasik.\p"
	.string "Zeinen ederra!\p"
	.string "Ene… Korrika eta hizketan…\n"
	.string "Gehiegi ari naiz nekatzen…\l"
	.string "Ene… Joan…beharra…dut…$"

MatchCall_PersonalizedText37::
	.string "Aupa, {STR_VAR_1} naiz.\n"
	.string "Erresistentzia hobetu nahi baduzu,\l"
	.string "altitude askoko lekuetan saiatu!\p"
	.string "Saiatu mendi gain batean korrika egiten.\n"
	.string "Ezinean ibiliko zara ziztuan!\p"
	.string "Ni ere oxigeno gabe geratzen ari naiz!\n"
	.string "Agur!$"

MatchCall_PersonalizedText38::
	.string "{STR_VAR_1} naiz, kaixo.\p"
	.string "Denbora asko noa igerian baina oraindik\n"
	.string "ez naiz iritsi ITZELETA HIRIRA.\p"
	.string "Agian leku berean biraka nabil.\p"
	.string "Ez, ez, ezin da hori izan.\n"
	.string "Kar-kar.\l"
	.string "Zaindu!$"

MatchCall_PersonalizedText39::
	.string "Ei, {STR_VAR_1} naiz…\n"
	.string "Ai ama!\p"
	.string "Plisti-plasta!\p"
	.string "Blug-blug-blug-blug…\p"
	.string "Plaf!\p"
	.string "Txip-txap! Txip-txap!\p"
	.string "Ei! Barkatu! Justu-justu eguzkia\n"
	.string "hartzeko krema eman dut.\p"
	.string "Nire POKéNAVak ihes egin dit eskutik\n"
	.string "eta uretara erori zait!\p"
	.string "Baina DEVONen POKéNAVa zinez gogorra\n"
	.string "da. Ondo atera da bainu horretatik!\p"
	.string "Beno, okupatuta nago eguzkia hartzen,\n"
	.string "beste batean hitz egingo dugu.$"

MatchCall_PersonalizedText40::
	.string "Kaixo, {STR_VAR_1} naiz.\p"
	.string "Triatloiko hiru kiroletatik,\n"
	.string "igeriketa dut gustukoen.\p"
	.string "Baina itsasoan denbora gehiegi egoten\n"
	.string "banaiz, azal guztia zimurtuko al zait?\p"
	.string "Triatloia gizakion indarra\n"
	.string "neurtzeko proba gogorra da! Aio!$"

MatchCall_PersonalizedText41::
	.string "Kaixo, {PLAYER}{KUN}.\n"
	.string "{STR_VAR_1} naiz.\p"
	.string "Zer moduz daude zure POKéMONak?\p"
	.string "Nire DRAGOI POKéMONak sasoi\n"
	.string "betean daude. Agur oraingoz.$"

MatchCall_PersonalizedText42::
	.string "{STR_VAR_1} naiz.\p"
	.string "Nire {STR_VAR_2} aurrekoan baino are\n"
	.string "gogorragoa da orain.\p"
	.string "Ez dut zure aurka berriro galduko.\n"
	.string "Ikusiko duzu hurrengoan!\p"
	.string "Laister arte!$"

MatchCall_PersonalizedText43::
	.string "Iepa, {STR_VAR_1} naiz.\p"
	.string "Ezkutaketaren artean\n"
	.string "entrenatzen aritu naiz.\p"
	.string "Baina gehiegi entrenatu dut.\n"
	.string "Inork ezin izan nau aurkitu.\l"
	.string "Nire arrakastak bakartu egin nau…\p"
	.string "Kea bezala desagertzen naiz!\n"
	.string "Agur!$"

MatchCall_PersonalizedText44::
	.string "{STR_VAR_1} naiz.\n"
	.string "Entrenatzen aritu naiz azkenengotik.\p"
	.string "Nire {STR_VAR_2} oso indartsua\n"
	.string "bihurtu da.\p"
	.string "Hondartzan entrenatzea oso ona da,\n"
	.string "pentsatu nuen bezala. Aio-aio!$"

MatchCall_PersonalizedText45::
	.string "Zer moduz zabiltza?\n"
	.string "{STR_VAR_1} naiz.\p"
	.string "Noiz geratuko da ditxosozko errauts\n"
	.string "bolkaniko hau?\p"
	.string "Horrela jarraitzen badu, nire guardasola\n"
	.string "goitik behera marroituta geratuko da…\p"
	.string "Geratu gaitezen beste batean!$"

MatchCall_PersonalizedText46::
	.string "Kaixo, {STR_VAR_1} naiz.\p"
	.string "Bazenekien itsasoan gehiago flotatzen\n"
	.string "dugula igerilekuan baino?\p"
	.string "Etzanda geratzen bazara, zure gorputzak\n"
	.string "bakarrik floatuko du.\p"
	.string "Baina, kontuz, denbora gehiegi\n"
	.string "geratzen bazara flotatzen, korronteak\l"
	.string "noranahi eramango zaitu.\p"
	.string "…Portzierto, non nago?\n"
	.string "Joan beharra dut!$"

MatchCall_PersonalizedText47::
	.string "{PLAYER}{KUN}, kaixo!\n"
	.string "{STR_VAR_1} naiz.\l"
	.string "Mendian nago orain.\p"
	.string "Baina lurra gorabeheratsuegia da.\n"
	.string "Hemen ezin dut denda jarri…\p"
	.string "Ideia bat izan dut!\p"
	.string "Agian nire POKéMONak gai izango dira\n"
	.string "lurra kolpeka lautzeko!\p"
	.string "Ea zeozer lortzen dudan!\n"
	.string "Aio-aio!$"

MatchCall_PersonalizedText48::
	.string "Iepa, iepa, {STR_VAR_1} naiz!\p"
	.string "LIVekin batera POKéMONak hazten ari naiz!\n"
	.string "Esfortzu handia egiten ari gara!\p"
	.string "Gogorrago saiatuz, onenak\n"
	.string "bihurtuko al gara? Aio-aio!$"

MatchCall_PersonalizedText49::
	.string "{STR_VAR_1} deika!\p"
	.string "MARINELA naiz, baina orain ez nago\n"
	.string "itsasontzian.\p"
	.string "Eta okurritzen zait--nola deitu\n"
	.string "behar genioke lurreko MARINELARI?\p"
	.string "Horixe pentsatzen aritu naiz\n"
	.string "olatuei begira nagoela.\p"
	.string "Beno, hurrengora arte!$"

MatchCall_PersonalizedText50::
	.string "{STR_VAR_1} naiz.\n"
	.string "Eta? POKéMONik harrapatu duzu?\p"
	.string "POKéMON berri bat harrapatzen baduzu,\n"
	.string "erakutsi egin behar didazu.\p"
	.string "Ez zaitut gehiago gogaituko.\n"
	.string "Itxaroten egongo naiz. Agur.$"

MatchCall_PersonalizedText51::
	.string "{STR_VAR_1} naiz.\p"
	.string "Zure POKéMONak era optimoan\n"
	.string "hazten ari zara?\p"
	.string "Hemen airea oso garbi dago.\n"
	.string "POKéMONak hazteko leku\l"
	.string "paregabea da hau.\p"
	.string "POKéMONak haztekotan baldin bazaude\n"
	.string "{STR_VAR_2}(e)ra etorri behar\l"
	.string "zenuke. Zaindu zaitez zu ere.$"

MatchCall_PersonalizedText52::
	.string "Kaixo, {STR_VAR_1} deika.\p"
	.string "{POKEBLOCK} bat eman nion {STR_VAR_2}(e)ri.\n"
	.string "Asko gustatu zitzaiola zirudien.\p"
	.string "Badirudi POKÉMONEK {POKEBLOCK} batzuk\n"
	.string "besteak baino gustokoago dituztela.\p"
	.string "Oso interesgarria iruditzen zait.\n"
	.string "Zaindu zaitez.$"

MatchCall_PersonalizedText53::
	.string "{STR_VAR_1} deika.\p"
	.string "POKÉMONEKIN elkarlanean arituz,\n"
	.string "eroso sentitzen da bat edozein lekutan.\p"
	.string "Hortaz ohartu behar ginateke denok\n"
	.string "eta POKÉMONEKIN elkarlanean aritu.\p"
	.string "Hori litzateke egokiena.\n"
	.string "Benetan uste dut.\p"
	.string "Uste dut zu bide onean zabiltzala!\n"
	.string "Gero arte!$"

MatchCall_PersonalizedText54::
	.string "Kaixo, {STR_VAR_1} naiz. Badakizu,\n"
	.string "beti prest dagoen ENTRENATZAILEA!\p"
	.string "{PLAYER}{KUN}, badituzu nahikoa item?\n"
	.string "Zure POKéMONak sasoian al daude?\p"
	.string "Guztia uneoro perfektu mantentzea\n"
	.string "da sekretua zure bidaian\l"
	.string "inolako arazorik ez izateko.\p"
	.string "Uste dut nire hornigaiak begiratu\n"
	.string "behar ditudala! Zaindu!$"

MatchCall_PersonalizedText55::
	.string "{STR_VAR_1} naiz!\n"
	.string "{STR_VAR_1} naiz!\p"
	.string "{STR_VAR_2} oso bide jendetsua da\n"
	.string "eta mota guztietako ENTRENATZAILEEN\l"
	.string "aurka borrokatzen dut egunero.\p"
	.string "Gaur bost borroka irabazi ditut\n"
	.string "eta hiru soilik galdu!\p"
	.string "Zu zer moduz ibili zara gaur?\n"
	.string "Hurrengoan kontatuko didazu, bai?$"

MatchCall_PersonalizedText56::
	.string "Ni naiz, {STR_VAR_1}.\p"
	.string "ZOMORRO motako POKéMONak ditudalako\n"
	.string "naiz ezaguna, baietz?\p"
	.string "Ba gaur nire zomorro gogokoenak\n"
	.string "eraman ditut eskolara.\p"
	.string "Gustuko dudan neska negarrez hasi da!\n"
	.string "Bai, egin barre nahi baduzu.\p"
	.string "Erakutsi egingo diot zergatik atsegin\n"
	.string "ditudan horrenbeste ZOMORRO POKéMONak.\p"
	.string "Zintz…\n"
	.string "Ikusi arte!$"

MatchCall_PersonalizedText57::
	.string "Uf! Uf! Uf! Uf!\p"
	.string "Iep! {STR_VAR_1} naiz! Uf! Uf!\p"
	.string "Hizketan aritzea…\n"
	.string "Eskalatu bitartean…\l"
	.string "Zaila da zinez… Uf! Uf!\p"
	.string "Urgh! Uf…\n"
	.string "A zer nolako pareta…\l"
	.string "Hitz egingo dugu…beste batean…\l"
	.string "Uf! Uf! Uf!$"

MatchCall_PersonalizedText58::
	.string "Aizu, kaixo!\p"
	.string "Oraindik altxo bila nabil\n"
	.string "KIRArekin!\p"
	.string "Agian hemen ez dago inolako\n"
	.string "altxorrik…\p"
	.string "Hala ere garrantzitsuena KIRArekin\n"
	.string "batera bilatzen aritzea da.\p"
	.string "Aizu, KIRA!\n"
	.string "Ze-zergatik haserretu zara?\p"
	.string "Ari naiz kasu egiten, maitea!\n"
	.string "Zu zara niretzat garrantzitsuena!\p"
	.string "…{PLAYER}, joan egin behar dut, aio!$"

MatchCall_PersonalizedText59::
	.string "{STR_VAR_1} deika!\p"
	.string "IHINTZIBAR herriko gimnasiora\n"
	.string "itzuli nintzen entrenatzeko.\p"
	.string "BRAWLY, GIMNASIOKO LIDERRA, are\n"
	.string "indartsuagoa da orain.\p"
	.string "Itsaso urrunean indartu zela edo\n"
	.string "halako zeoezr esan zidan…\p"
	.string "Baina lehen bezain jatorra da.\n"
	.string "Neskek oso atsegin dut!\l"
	.string "Inbidia ematen dit egia esan.\p"
	.string "Eta… BRAWLYren laguna BRUNO\n"
	.string "bera bezalakoa ote da?\p"
	.string "Badakizu, oso izerditsua,\n"
	.string "eta jendeari “olatutzar”\l"
	.string "deitzen diona, eta hori.\p"
	.string "Baina, aizu, inbidiaren kontu hau\n"
	.string "guztia ez da horrela berez, ezta?\p"
	.string "Ahaztu elkarrizketa hau,\n"
	.string "hobeto, ados? Aio!$"

MatchCall_PersonalizedText60::
	.string "Plazera da zu bezalako ENTRENATZAILE\n"
	.string "gazte batekin hitz egitea.\p"
	.string "Suposatzen dut adina gorabehera\n"
	.string "POKéMONak beti gustatuko zaizkidala.\p"
	.string "Bikaina litzateke guk bezalako\n"
	.string "laguntasuna edukitzea, baietz?\p"
	.string "Noski, {PLAYER}{KUN}, zuk jada baduzu\n"
	.string "zure POKÉMONEN maitasun osoa\l"
	.string "orain, ordea.\p"
	.string "Betirako iraungo duten erlazioak\n"
	.string "eraikitzen ari zara!\p"
	.string "Kar-kar-kar!\n"
	.string "Ez etsi inoiz!$"

MatchCall_PersonalizedText61::
	.string "Kaixo, {STR_VAR_1} naiz!\n"
	.string "Borroka bat irabazi berri dugu!\p"
	.string "Ez dugu askotan irabazten, baina\n"
	.string "IGERILARI bati irabazi genion.\p"
	.string "Nire arreba sutan zegoen!\p"
	.string "Ahula zela antzeztu nahi zuen\n"
	.string "inpresioa eragiteko!\p"
	.string "Beti egiten dit errieta,\n"
	.string "irabazi edo galdu!\p"
	.string "{PLAYER}{KUN}, esaiozu zerbait\n"
	.string "hurrengoan, ados?\p"
	.string "Ongi, ikusi arte!$"

MatchCall_PersonalizedText62::
	.string "{STR_VAR_1} deika, bai.\n"
	.string "Itsasora joan nintzen atzo.\p"
	.string "Esploratzeko hondakin berri\n"
	.string "batzuen bila aritu naiz.\p"
	.string "baina korronteak hasierako\n"
	.string "lekura eraman ninduten, nolabait.\p"
	.string "Gainera, ahula naiz borroketan…\n"
	.string "Egin burla nahi baduzu…\l"
	.string "Baina ez naiz errendituko.\p"
	.string "Hondakin berriak aurkitzen ditudanean\n"
	.string "famatua izango naiz!\p"
	.string "Ez dut besterik esateko!\n"
	.string "Hurrengora arte!$"

MatchCall_PersonalizedText63::
	.string "Kaixo, txo!\n"
	.string "Ni naiz, {STR_VAR_1}!\l"
	.string "108. ERRUTAN nago orain!\l"
	.string "Alegia, betiko lekuan nagoela!\p"
	.string "Gaur IGERILARI eder bat pasa\n"
	.string "da igerian!\p"
	.string "Beraz, oihu bat bota nion!\p"
	.string "Eta nazkaz beteta begiratu zidan!\p"
	.string "Hori gertatu da 108. ERRUTAN!\n"
	.string "Brought to you by {STR_VAR_1}!$"

MatchCall_PersonalizedText64::
	.string "{STR_VAR_1} naiz!\p"
	.string "Pixka bat okupatuta nago, baina\n"
	.string "gaur bost ENTRENATZAILERI irabazi\l"
	.string "diedala kontatu nahi nizun.\p"
	.string "Martxa honetan, zuri irabaziko\n"
	.string "dizut hurrengoan.\p"
	.string "Etsai onak izan gaitezke,\n"
	.string "zu eta ni. Agur, hurrengora arte!$"

MatchCall_BattleFrontierStreakText1::
	.string "Aupa! {STR_VAR_1} naiz.\n"
	.string "Entzun ditut berriak!\p"
	.string "{STR_VAR_2}N bikain ibili\n"
	.string "zinela esan zuten.\p"
	.string "Izugarria, {STR_VAR_3} garaipen jarraian?\n"
	.string "Ikusi arte!$"

MatchCall_BattleFrontierStreakText2::
	.string "Kaixo, {STR_VAR_1} naiz!\n"
	.string "Zutaz zerbait entzun dut!\p"
	.string "Esan dute {STR_VAR_3} borroka irabazi\n"
	.string "zenituela jarraian {STR_VAR_2}N.\p"
	.string "Itzela da hori! Ni ere are gehiago\n"
	.string "saiatuko naiz! Agur!$"

MatchCall_BattleFrontierStreakText3::
	.string "Iepa, {PLAYER}!\n"
	.string "Ni naiz, {STR_VAR_1}.\p"
	.string "Entzun dut oso ondo aritu zarela\n"
	.string "{STR_VAR_2}N!\p"
	.string "{STR_VAR_3} garaipen jarraian…\n"
	.string "Errekor itzela, ez da hala?\p"
	.string "Ni ere animatu beharko naiz!\n"
	.string "Laister arte!$"

MatchCall_BattleFrontierStreakText4::
	.string "Ei, {PLAYER}{KUN}.\n"
	.string "{STR_VAR_1} naiz. Zer moduz?\p"
	.string "Zurrumurru bat entzun dut, dioena\n"
	.string "{STR_VAR_2}N {STR_VAR_3} borroka bata\l"
	.string "bestearen atzetik irabazi dituzula.\p"
	.string "Ni ere martxan jarri beharko naiz.\n"
	.string "Agur!$"

MatchCall_BattleFrontierStreakText5::
	.string "Iepa, {PLAYER}{KUN}!\n"
	.string "{STR_VAR_1} naiz.\p"
	.string "Aurrekoan {STR_VAR_2}N jarraian\n"
	.string "{STR_VAR_3} borroka irabazi zenituen?\l"
	.string "Hori sinestezina da!\p"
	.string "Nire POKéMONak entrenatu beharko ditut.\n"
	.string "Ikusi arte!$"

MatchCall_BattleFrontierStreakText6::
	.string "Ei, {PLAYER}{KUN}.\n"
	.string "{STR_VAR_1} naiz. Zer moduz?\p"
	.string "Portzierto, entzun dut {STR_VAR_3} borroka\n"
	.string "jarraian irabazteko balentria egin\l"
	.string "zenuela {STR_VAR_2}N.\p"
	.string "Nire taldea entrenatzeko\n"
	.string "gogoa piztu didazu.$"

MatchCall_BattleFrontierStreakText7::
	.string "…Ein, {PLAYER}{KUN}?\n"
	.string "{STR_VAR_1} deika…\p"
	.string "Ah, bai, {STR_VAR_2}N\n"
	.string "egon zinen, ezta?\p"
	.string "Eta {STR_VAR_3} borroka jarraian irabazi.\p"
	.string "Ene, POKéMON arraro bat!\n"
	.string "Joan egin behar naiz!$"

MatchCall_BattleFrontierStreakText8::
	.string "{PLAYER}{KUN}, zer moduz?\n"
	.string "{STR_VAR_1} deika.\l"
	.string "Espero dut ondo zabiltzala.\p"
	.string "Beno, bazabiltza. Entzun dut\n"
	.string "{STR_VAR_3} borroka jarraian irabazi\l"
	.string "zenituela {STR_VAR_2}N.\p"
	.string "Txundigarria, benetan!\n"
	.string "Horrela jarraitzea espero dut.$"

MatchCall_BattleFrontierStreakText9::
	.string "Aizu, {PLAYER}{KUN}, kaixo!\n"
	.string "{STR_VAR_1} naiz!\p"
	.string "Ez dakizu zer entzun dudan! {STR_VAR_3}\n"
	.string "borroka jarraian {STR_VAR_2}N!\p"
	.string "Nola lortu zenuen hori?\n"
	.string "Ni ere gehiago saiatu beharko naiz!$"

MatchCall_BattleFrontierStreakText10::
	.string "{PLAYER}{KUN}, kaixo…\n"
	.string "{STR_VAR_1} naiz.\p"
	.string "{STR_VAR_3} borroka jarraian irabazi\n"
	.string "zenituen {STR_VAR_2}N?\p"
	.string "Hori bai balentria.\n"
	.string "Gartsuago saiatu beharko naiz.$"

MatchCall_BattleFrontierStreakText11::
	.string "Ah, {PLAYER}{KUN}.\n"
	.string "{STR_VAR_1} deika.\p"
	.string "{STR_VAR_2}N amesgaiztoa\n"
	.string "zarela entzun dut.\p"
	.string "Zenbat, {STR_VAR_3} borroka\n"
	.string "irabazi dituzu jarraian?\p"
	.string "Oso ona zara, bai.\n"
	.string "Zenbat irabazi ote ditzaket nik?$"

MatchCall_BattleFrontierStreakText12::
	.string "Kaixo, {PLAYER}{KUN}.\n"
	.string "Ni naiz, {STR_VAR_1}.\l"
	.string "Ondo zabiltza?\p"
	.string "Nobraitek zutaz hitz egin dit.\n"
	.string "{STR_VAR_3} borroka jarraian irabazi\l"
	.string "dituzula {STR_VAR_2} izeneko leku batean?\p"
	.string "A zer nolako balentria.\n"
	.string "Agur!$"

MatchCall_BattleFrontierStreakText13::
	.string "Ah, kaixo, {PLAYER}{KUN}!\n"
	.string "{STR_VAR_1} naiz!\l"
	.string "Ondo zabiltzala espero dut.\p"
	.string "Entzun dut {STR_VAR_3} borroka irabazi\n"
	.string "dituzula jarraian {STR_VAR_2}N.\p"
	.string "A zer nolako energia duzun!\n"
	.string "Agur.$"

MatchCall_BattleFrontierStreakText14::
	.string "Kaixo, {PLAYER}{KUN}.\n"
	.string "{STR_VAR_1} naiz.\p"
	.string "Zutaz hitz egin didate!\n"
	.string "Ez al dituzu {STR_VAR_3} borroka\l"
	.string "jarraian irabazi {STR_VAR_2}N?\p"
	.string "Zu bai zu inspiragarria!\n"
	.string "Aio-aio!$"

MatchCall_BattleFrontierRecordStreakText1::
	.string "Aupa! {STR_VAR_1} deika.\n"
	.string "Entzun ditut berriak!\p"
	.string "{STR_VAR_2}N bikain ibili zinela\n"
	.string "diote.\p"
	.string "Izugarria--{STR_VAR_3} garaipen jarraian?\n"
	.string "Agur!$"

MatchCall_BattleFrontierRecordStreakText2::
	.string "Kaixo, {STR_VAR_1} naiz!\n"
	.string "Zutaz hitz egin didate!\p"
	.string "Esan zidaten {STR_VAR_3} borroka\n"
	.string "irabazi zenituela {STR_VAR_2}N.\p"
	.string "Izugarria! Ni ere gehiago\n"
	.string "saiatu beharko naiz! Agur!$"

MatchCall_BattleFrontierRecordStreakText3::
	.string "Aupa, kaixo, {PLAYER}!\n"
	.string "Ni naiz, {STR_VAR_1}.\p"
	.string "Entzun dut izugarri ibili zinela\n"
	.string "{STR_VAR_2}N!\p"
	.string "{STR_VAR_3} garaipen jarraian…\n"
	.string "Errekor itzela, ezta?\p"
	.string "Ni ere martxan jarri behar naiz!\n"
	.string "Laister arte!$"

MatchCall_BattleFrontierRecordStreakText4::
	.string "Aupa, {PLAYER}{KUN}.\n"
	.string "{STR_VAR_1} deika. Zer moduz?\p"
	.string "Zurrumuru batek dio zuk\n"
	.string "{STR_VAR_3} garaipen lortu dituzula\l"
	.string "jarraian {STR_VAR_2}N.\p"
	.string "Esfortzu gehiago egin beharko dut.\n"
	.string "Ikusi arte!$"

MatchCall_BattleFrontierRecordStreakText5::
	.string "Iepa, {PLAYER}{KUN}!\n"
	.string "{STR_VAR_1} naiz.\p"
	.string "Aurrekoan {STR_VAR_2}N jarraian\n"
	.string "{STR_VAR_3} borroka irabazi zenituen?\l"
	.string "Izugarria da hori!\p"
	.string "Ni? Pixkanaka ari naiz hobetzen.\n"
	.string "Ikusi arte!$"

MatchCall_BattleFrontierRecordStreakText6::
	.string "Iepa, {PLAYER}{KUN}.\n"
	.string "{STR_VAR_1} deika. Zer moduz?\p"
	.string "Portzierto, entzun dut {STR_VAR_3}\n"
	.string "jarraian irabazteko balentria egin\l"
	.string "zenuela {STR_VAR_2}N.\p"
	.string "Ni ere gehiago saiatu behar naiz!\n"
	.string "Ikusi arte!$"

MatchCall_BattleFrontierRecordStreakText7::
	.string "…Ein, {PLAYER}{KUN}?\n"
	.string "{STR_VAR_1} naiz…\p"
	.string "A, bai, {STR_VAR_2}N\n"
	.string "zabiltza ezta?\p"
	.string "Eta jarraian {STR_VAR_3} borroka irabazi dituzu.\p"
	.string "Ene, POKéMON arraro bat!\n"
	.string "Joan egin behar dut!$"

MatchCall_BattleFrontierRecordStreakText8::
	.string "{PLAYER}{KUN}, zer moduz?\n"
	.string "{STR_VAR_1} deika.\l"
	.string "Ondo zaudela espero dut.\p"
	.string "Beno, bazabiltza. Entzun dut\n"
	.string "{STR_VAR_3} borroka irabazi dituzula\l"
	.string "jarraian {STR_VAR_2}N.\p"
	.string "Hori izugarri da!\n"
	.string "Nire POKéMONak entrenatu beharko ditut!$"

MatchCall_BattleFrontierRecordStreakText9::
	.string "{PLAYER}{KUN}, kaixo!\n"
	.string "{STR_VAR_1} naiz!\p"
	.string "Badakizu zer? Zure {STR_VAR_3} garaipenen\n"
	.string "balentria entzun dut {STR_VAR_2}N!\p"
	.string "Hori itzela da!\n"
	.string "Ni ere gehiago saiatu behar naiz!$"

MatchCall_BattleFrontierRecordStreakText10::
	.string "{PLAYER}{KUN}, kaixo…\n"
	.string "{STR_VAR_1} naiz.\p"
	.string "{STR_VAR_3} borroka jarraian irabazi\n"
	.string "dituzu {STR_VAR_2}N?\p"
	.string "A zer nolako balentria.\n"
	.string "Gogorrago saiatu behar naiz.$"

MatchCall_BattleFrontierRecordStreakText11::
	.string "Aupa, {PLAYER}{KUN}.\n"
	.string "{STR_VAR_1} naiz.\p"
	.string "Entzun dut {STR_VAR_2}N\n"
	.string "amesgaiztoa zarela.\p"
	.string "Zenbat, {STR_VAR_3} borroka jarraian\n"
	.string "irabazi dituzu?\p"
	.string "Ona zara, gero.\n"
	.string "Zenbat irabazteko gai ote naiz ni?$"

MatchCall_BattleFrontierRecordStreakText12::
	.string "Kaixo, {PLAYER}{KUN}.\n"
	.string "Ni naiz, {STR_VAR_1}.\l"
	.string "Zer moduz zabiltza?\p"
	.string "Zure inguruko zurrumurrua entzun dut.\n"
	.string "{STR_VAR_3} borroka jarraian irabazi\l"
	.string "dituzula {STR_VAR_2} izeneko leku batean?\p"
	.string "Hori izugarria da.\n"
	.string "Agur!$"

MatchCall_BattleFrontierRecordStreakText13::
	.string "Ei, kaixo, {PLAYER}{KUN}!\n"
	.string "{STR_VAR_1} deika!\l"
	.string "Ondo zabiltzala espero dut.\p"
	.string "Entzun dut {STR_VAR_3} borroka jarraian\n"
	.string "irabazi dituzula {STR_VAR_2}N.\p"
	.string "A zer nolako energia duzun!\n"
	.string "Laister arte.$"

MatchCall_BattleFrontierRecordStreakText14::
	.string "Aupa, {PLAYER}{KUN}.\n"
	.string "{STR_VAR_1} naiz.\l"
	.string "Zutaz hitz egin didate!\p"
	.string "Ez al dituzu {STR_VAR_3} borroka\n"
	.string "irabazi jarraian {STR_VAR_2}N?\p"
	.string "Zu bai zu inspiragarria!\n"
	.string "Aio-aio!$"

MatchCall_BattleDomeText1::
	.string "Iep! {PLAYER}?\n"
	.string "Kaixo, {STR_VAR_1} naiz!\l"
	.string "Berriak entzin ditut!\p"
	.string "{STR_VAR_2}N txapelduna izan\n"
	.string "zara {STR_VAR_3} aldiz?\p"
	.string "Itzela! Ni ere saiatu behar naiz!\n"
	.string "Aio!$"

MatchCall_BattleDomeText2::
	.string "Kaixo, {STR_VAR_1} naiz!\n"
	.string "Zutaz hitz egin didate!\p"
	.string "Esan dute {STR_VAR_3} titulu lortu\n"
	.string "dituzula {STR_VAR_2}N.\p"
	.string "Hori itzela da! Ni ere bilakatuko\n"
	.string "ote naiz txapeldun noizbait?$"

MatchCall_BattleDomeText3::
	.string "Aupa kaixo, {PLAYER}!\n"
	.string "Ni naiz, {STR_VAR_1}.\l"
	.string "Zer moduz?\p"
	.string "Entzun dut {STR_VAR_3} aldiz\n"
	.string "irabazi duzula {STR_VAR_2}N!\p"
	.string "Ea beste behin irabazten duzun!\n"
	.string "Laister arte!$"

MatchCall_BattleDomeText4::
	.string "Ei, {PLAYER}{KUN}.\n"
	.string "{STR_VAR_1} deika.\p"
	.string "Entzun dut txapelduna izan zarela\n"
	.string "{STR_VAR_2}N {STR_VAR_3} aldiz.\p"
	.string "Lan handia egiten ari zara, bai.\n"
	.string "Ni ere animatuko naiz!$"

MatchCall_BattleDomeText5::
	.string "iep, {PLAYER}{KUN}!\n"
	.string "{STR_VAR_1} naiz.\p"
	.string "Entzun dut {STR_VAR_3} aldiz\n"
	.string "irabazi duzula {STR_VAR_2}N.\p"
	.string "Ni ere martxan jarri behar naiz!\n"
	.string "Laister arte!$"

MatchCall_BattleDomeText6::
	.string "Ei, {PLAYER}{KUN}?\n"
	.string "{STR_VAR_1} deika. Zelan?\p"
	.string "Portzierto, entzun dut {STR_VAR_3}\n"
	.string "aldiz txapela jantzi duzula\l"
	.string "{STR_VAR_2}N.\p"
	.string "Nire POKéMONak entrenatu beharko"
	.string "ditut ditut ez nadin atzean geratu.$"

MatchCall_BattleDomeText7::
	.string "{PLAYER}{KUN}?\n"
	.string "{STR_VAR_1} naiz.\p"
	.string "{STR_VAR_2}N zenbiltzala\n"
	.string "txapelduna izan zara {STR_VAR_3} aldiz?\p"
	.string "Ona hori. Portzierto, harrapatu\n"
	.string "al duzu POKéMON arrarorik azkenaldian?\p"
	.string "Benetan e?\n"
	.string "Ongi, aio.$"

MatchCall_BattleDomeText8::
	.string "Ei, {PLAYER}{KUN}, zer moduz?\n"
	.string "{STR_VAR_1} naiz.\l"
	.string "Espero dut ondo zabiltzala.\l"
	.string "Beno, bazabiltza.\p"
	.string "Entzun dut {STR_VAR_3} titulu irabazi\n"
	.string "dituzula {STR_VAR_2}N.\p"
	.string "Nire POKéMONak zuk bezala heziko ditut.\n"
	.string "Ikusi arte.$"

MatchCall_BattleDomeText9::
	.string "Ei, {PLAYER}{KUN}, kaixo!\n"
	.string "{STR_VAR_1} naiz!\p"
	.string "Badakizu? Entzun dut {STR_VAR_2}N\n"
	.string "{STR_VAR_3} titulu irabazi dituzula!\p"
	.string "itzela da hori!\n"
	.string "Ni ere gogorrago saiatu behar naiz!$"

MatchCall_BattleDomeText10::
	.string "Iepa, {PLAYER}{KUN}, kaixo.\n"
	.string "{STR_VAR_1} deika.\p"
	.string "{STR_VAR_3} aldiz irabazi duzu\n"
	.string "{STR_VAR_2}N?\p"
	.string "Hori lorpen itzela da.\n"
	.string "Gehiago saiatu beharko dut.$"

MatchCall_BattleDomeText11::
	.string "Ei, {PLAYER}{KUN}.\n"
	.string "{STR_VAR_1} naiz.\p"
	.string "Entzun dut {STR_VAR_2}N\n"
	.string "amesgaiztoa zarela, ezta?\p"
	.string "Zenbat, {STR_VAR_3} aldiz irabazi duzu\n"
	.string "jarraian?\p"
	.string "Noizbait izango ote naiz ni\n"
	.string "txapelduna?\p"
	.string "…Ia ezinezkoa ote?\n"
	.string "Beno, ikusi arte!$"

MatchCall_BattleDomeText12::
	.string "Kaixo, {PLAYER}{KUN}.\n"
	.string "Ni naiz, {STR_VAR_1}.\l"
	.string "Ondo al zabiltza?\p"
	.string "{STR_VAR_3} txapelketa irabazi dituzu\n"
	.string "{STR_VAR_2} izeneko leku batean?\p"
	.string "Ez da erraza hori.\n"
	.string "Aio!$"

MatchCall_BattleDomeText13::
	.string "Ah, kaixo, {PLAYER}{KUN}!\n"
	.string "{STR_VAR_1} naiz!\l"
	.string "Espero dut ondo zabiltzala.\p"
	.string "Entzun dut {STR_VAR_3} txapelketa\n"
	.string "irabazi dituzula {STR_VAR_2}N?\p"
	.string "A zer nolako energia!\n"
	.string "Ondo segi.$"

MatchCall_BattleDomeText14::
	.string "Aupa, {PLAYER}{KUN}.\n"
	.string "{STR_VAR_1} naiz.\l"
	.string "Zutaz hitz egin didate!\p"
	.string "Ez al dituzu {STR_VAR_3} titulu\n"
	.string "irabazi {STR_VAR_2}N?\p"
	.string "Zu bai zu itzela!\n"
	.string "Hurrengora arte!$"

MatchCall_BattlePikeText1::
	.string "Iep! {PLAYER}?\n"
	.string "Kaixo, {STR_VAR_1} naiz!\l"
	.string "Entzun ditut berriak!\p"
	.string "{STR_VAR_3} gela gainditu\n"
	.string "dituzu {STR_VAR_2}N!\p"
	.string "Izugarria!\n"
	.string "Ikusi arte!$"

MatchCall_BattlePikeText2::
	.string "Kaixo, {STR_VAR_1} naiz!\n"
	.string "Zutaz hitz egin didate!\p"
	.string "Esan dute {STR_VAR_2}N {STR_VAR_3}\n"
	.string "gela garaitzea lortu duzula.\p"
	.string "Askoz gehiago saiatu behar naiz!\n"
	.string "Aio!$"

MatchCall_BattlePikeText3::
	.string "Aupa kaixo, {PLAYER}!\n"
	.string "Ni naiz, {STR_VAR_1}.\l"
	.string "Zer moduz zabiltza?\p"
	.string "Entzun dut {STR_VAR_3} gela pasa\n"
	.string "dituzula {STR_VAR_2}N!\p"
	.string "Hurrengoan are hobeto ibiliko zara!\n"
	.string "Liaster arte!$"

MatchCall_BattlePikeText4::
	.string "Ei, {PLAYER}{KUN}.\n"
	.string "{STR_VAR_1} deika.\p"
	.string "Entzun dut {STR_VAR_3} gela gainditu\n"
	.string "dituzula {STR_VAR_2}N.\p"
	.string "Nire POKéMONak entrenatu eta\n"
	.string "indartuko ditut!$"

MatchCall_BattlePikeText5::
	.string "Iepa, {PLAYER}{KUN}!\n"
	.string "{STR_VAR_1} naiz.\p"
	.string "Entzun dut {STR_VAR_3} gela gainditu\n"
	.string "dituzula {STR_VAR_2}N.\p"
	.string "Ni ere martxan jarri beharko naiz!\n"
	.string "Ondo ibili!$"

MatchCall_BattlePikeText6::
	.string "Ei, {PLAYER}{KUN}?\n"
	.string "{STR_VAR_1} naiz. Zelan?\p"
	.string "Portzierto, entzun dut {STR_VAR_3} gela\n"
	.string "garaitu dituzula {STR_VAR_2}N.\p"
	.string "Nire POKéMONak entrenatu beharko\n"
	.string "ditut ez nadin atzean geratu.$"

MatchCall_BattlePikeText7::
	.string "{PLAYER}{KUN}?\n"
	.string "{STR_VAR_1} deika.\p"
	.string "{STR_VAR_2}N zeunden\n"
	.string "eta {STR_VAR_3} gela gainditu dituzu?\p"
	.string "Hori izugarria da.\p"
	.string "Ene, POKéMON arraro bat pasa da!\n"
	.string "Ongi, aio.$"

MatchCall_BattlePikeText8::
	.string "{PLAYER}{KUN}, zer moduz?\n"
	.string "{STR_VAR_1} deika.\l"
	.string "Ondo zabiltzala espero dut.\l"
	.string "Beno, bazabiltza.\p"
	.string "Esan didate {STR_VAR_2}N\n"
	.string "{STR_VAR_3} gela gainditu dituzula.\p"
	.string "Hori ikusgarria da!\n"
	.string "Nire POKéMONak zuk bezala heziko ditut.\l"
	.string "Ikusi arte.$"

MatchCall_BattlePikeText9::
	.string "{PLAYER}{KUN}, aupa!\n"
	.string "{STR_VAR_1} naiz!\p"
	.string "Badakizu zer? Entzun dut {STR_VAR_3} gela\n"
	.string "garaitu dituzula {STR_VAR_2}M!\p"
	.string "Hori izugarria da!\n"
	.string "Ni ere gogorrago saiatuko naiz!$"

MatchCall_BattlePikeText10::
	.string "Ei, {PLAYER}{KUN}, kaixo.\n"
	.string "{STR_VAR_1} naiz.\p"
	.string "{STR_VAR_3} gela gainditu dituzu\n"
	.string "{STR_VAR_2}N?\p"
	.string "Hori izugarria da.\n"
	.string "Gehiago saiatu beharko naiz.$"

MatchCall_BattlePikeText11::
	.string "Ei, {PLAYER}{KUN}.\n"
	.string "{STR_VAR_1} naiz.\p"
	.string "Entzun dut amesgaiztoa zarela\n"
	.string "{STR_VAR_2}N?\p"
	.string "Zenbat, {STR_VAR_3} gela gainditu dituzu?\n"
	.string "Hori benetan itzela da.\p"
	.string "Inoiz bihurtuko ote naiz ni\n"
	.string "txapelduna?\p"
	.string "…Ia ezinezkoa ote?\n"
	.string "Beno, ikusi arte!$"

MatchCall_BattlePikeText12::
	.string "Kaixo, {PLAYER}{KUN}.\n"
	.string "Ni naiz, {STR_VAR_1}.\l"
	.string "Ondo al zabiltza?\p"
	.string "{STR_VAR_3} gela gainditu dituzu\n"
	.string "{STR_VAR_2} izeneko leku batean?\p"
	.string "Hori balentria itzela da.\n"
	.string "Ikusi arte!$"

MatchCall_BattlePikeText13::
	.string "Ei, kaixo, {PLAYER}{KUN}!\n"
	.string "{STR_VAR_1} naiz!\l"
	.string "Espero dut ondo zabiltzala.\p"
	.string "Entzun dut {STR_VAR_3} gela gainditu\n"
	.string "dituzula {STR_VAR_2}N?\p"
	.string "A zer nolako energia!\n"
	.string "Aio-aio.$"

MatchCall_BattlePikeText14::
	.string "Ei, aupa, {PLAYER}{KUN}.\n"
	.string "{STR_VAR_1} naiz.\l"
	.string "Zutaz hitz egin didate!\p"
	.string "Ez al dituzu {STR_VAR_3} gela gainditu\n"
	.string "{STR_VAR_2}N?\p"
	.string "Zu bai zu inspiragarria!\n"
	.string "Ikusi arte!$"

MatchCall_BattlePyramidText1::
	.string "Iepa! {PLAYER}?\n"
	.string "Kaixo, {STR_VAR_1} naiz!\l"
	.string "Entzun ditut berriak!\p"
	.string "{STR_VAR_3} solairu igo dituzu\n"
	.string "{STR_VAR_2}N, ezta?\p"
	.string "Hori itzela da!\n"
	.string "Ni ere apuntatu behar nintzateke.$"

MatchCall_BattlePyramidText2::
	.string "Kaixo, {STR_VAR_1} naiz!\n"
	.string "Zutaz hitz egin didate!\p"
	.string "Esan didate {STR_VAR_3} solairu igo\n"
	.string "dituzula {STR_VAR_2}N.\p"
	.string "Uau, hori itzela da!\n"
	.string "Nire POKéMONak entrenatu beharko ditut!$"

MatchCall_BattlePyramidText3::
	.string "Kaixo, {PLAYER}!\n"
	.string "Ni naiz, {STR_VAR_1}.\l"
	.string "Zer moduz zabiltza?\p"
	.string "Entzun dut {STR_VAR_3} solairu igo\n"
	.string "dituzula {STR_VAR_2}N!\p"
	.string "Hurrengoan are hobe ibiliko zara!\n"
	.string "Ondo segi!$"

MatchCall_BattlePyramidText4::
	.string "Ei, {PLAYER}{KUN}.\n"
	.string "{STR_VAR_1} naiz.\p"
	.string "Entzun dut {STR_VAR_3} solairu igo\n"
	.string "dituzula {STR_VAR_2}N.\p"
	.string "Gehiago saiatu beharko naiz\n"
	.string "atzean ez geratzeko!$"

MatchCall_BattlePyramidText5::
	.string "Iepa, {PLAYER}{KUN}!\n"
	.string "{STR_VAR_1} naiz.\p"
	.string "Entzun dut {STR_VAR_3} solairu igo\n"
	.string "dituzula {STR_VAR_2}N.\p"
	.string "Ni ere animatu beharko naiz!\n"
	.string "Ikusi arte!$"

MatchCall_BattlePyramidText6::
	.string "Ei, {PLAYER}{KUN}?\n"
	.string "{STR_VAR_1} naiz. Zelan?\p"
	.string "Portzierto, entzun dut {STR_VAR_3}\n"
	.string "solairu igo dituzula {STR_VAR_2}N.\p"
	.string "Nire POKéMONak entrenatu beharko"
	.string "ditut ez nadin atzean geratu.$"

MatchCall_BattlePyramidText7::
	.string "{PLAYER}{KUN}?\n"
	.string "{STR_VAR_1} naiz.\p"
	.string "{STR_VAR_2}N zabiltza\n"
	.string "eta {STR_VAR_3} solairu igo dituzu?\p"
	.string "Ona. Ba al zegoen POKéMON arrarorik\n"
	.string "bertan?\p"
	.string "Ez, e?\n"
	.string "Ongi, aio.$"

MatchCall_BattlePyramidText8::
	.string "{PLAYER}{KUN}, zer moduz?\n"
	.string "{STR_VAR_1} deika.\l"
	.string "Ondo zabiltzala espero dut.\l"
	.string "Beno, bazabiltza.\p"
	.string "Entzun dut {STR_VAR_3} solairu\n"
	.string "igo dituzula {STR_VAR_2}N.\p"
	.string "Itzela da hori!\n"
	.string "Nire POKéMONak zuk bezala heziko ditut.\l"
	.string "Hurrengora arte.$"

MatchCall_BattlePyramidText9::
	.string "Ei, {PLAYER}{KUN}, aupa!\n"
	.string "{STR_VAR_1} naiz!\p"
	.string "Badakizu zer entzun dudan? {STR_VAR_3}\n"
	.string "solairu igo dizuzula {STR_VAR_2}N!\p"
	.string "Izugarria!\n"
	.string "Ni ere gehiago saiatu beharko naiz!$"

MatchCall_BattlePyramidText10::
	.string "{PLAYER}{KUN}, kaixo.\n"
	.string "{STR_VAR_1} naiz.\p"
	.string "{STR_VAR_3} solairu igo dituzu\n"
	.string "{STR_VAR_2}N?\p"
	.string "That's quite the accomplishment.\n"
	.string "I need to work harder.$"

MatchCall_BattlePyramidText11::
	.string "Ei, {PLAYER}{KUN}.\n"
	.string "{STR_VAR_1} naiz.\p"
	.string "Entzun dut {STR_VAR_2}N\n"
	.string "amesgaiztoa zarela.\p"
	.string "Zenbat, {STR_VAR_3} solairu igo dituzu?\n"
	.string "Hori bai itzela dela.\p"
	.string "Bihurtuko ote naiz ni txapelduna\n"
	.string "inoiz?\p"
	.string "…ia ezinezkoa?\n"
	.string "Beno, ikusi arte!$"

MatchCall_BattlePyramidText12::
	.string "Kaixo, {PLAYER}{KUN}.\n"
	.string "Ni naiz, {STR_VAR_1}.\l"
	.string "Ondo al zabiltza?\p"
	.string "{STR_VAR_3} solairu igo dituzula\n"
	.string "{STR_VAR_2} izeneko leku batean?\p"
	.string "Hori bai balentria.\n"
	.string "Aio!$"

MatchCall_BattlePyramidText13::
	.string "Kaixo, {PLAYER}{KUN}!\n"
	.string "{STR_VAR_1} naiz!\l"
	.string "Ondo zabiltzala espero dut.\p"
	.string "Esan didate {STR_VAR_3} solairu igo\n"
	.string "dituzula {STR_VAR_2}N?\p"
	.string "A zer nolako energia!\n"
	.string "Agur.$"

MatchCall_BattlePyramidText14::
	.string "Aupa, {PLAYER}{KUN}.\n"
	.string "{STR_VAR_1} naiz.\l"
	.string "Zutaz hitz egin didate!\p"
	.string "Ez al dituzu {STR_VAR_3} solairu igo\n"
	.string "{STR_VAR_2}N?\p"
	.string "Zu bai zu inspiragarria!\n"
	.string "Ikusi arte!$"

MatchCall_Text_Mom1::
	.string "AMA: Zure aita eta zu…\n"
	.string "Guztiak POKÉMONEKIN itsututa daude.\p"
	.string "Zein ote da POKÉMONEN xarma?\p"
	.string "Nik?\n"
	.string "Eguneroko lanetan laguntzen didaten\l"
	.string "POKéMONak ditut gustoko.$"

MatchCall_Text_Mom2::
	.string "AMA: Kaixo, {PLAYER}!\n"
	.string "Zure aita PETALOREKO GIMNASIOAN\l"
	.string "sartuta dabil beti.\p"
	.string "Oso gutxitan ateratzen da.\n"
	.string "Eta GIMNASIORA bueltatzen da\l"
	.string "jan dezakeen guztia jan ondoren.\p"
	.string "Uste dut zure aurka galtzeak\n"
	.string "bere harrotasunari kalte egin ziola!$"

MatchCall_Text_Mom3::
	.string "AMA: {PLAYER}…\n"
	.string "Ez kezkatu nitaz eta etxeaz.\p"
	.string "Erabili KORRIKAKO ZAPATILAK\n"
	.string "hautsi arte, maitea!$"

MatchCall_Text_Roxanne1::
	.string "ROXANNE: Ei, kaixo, {PLAYER}!\p"
	.string "Entrenatzen aritu naiz buru-belarri\n"
	.string "elkar ezagutu genuenetik.\p"
	.string "Denbora pixka bat beharko dut\n"
	.string "GIMNASIOA berriz irekitzeko.\p"
	.string "Baina irekitzen dudanean\n"
	.string "etorri errebantxa bila!$"

MatchCall_Text_Roxanne2::
	.string "ROXANNE: {PLAYER} al zara?\n"
	.string "Zorionak!\l"
	.string "Hitz egin didate zutaz!\p"
	.string "Nire kasuan, denbora pixka bat beharko\n"
	.string "dut GIMNASIOA berriz irekitzeko.\p"
	.string "Baina irekitzen dudanean\n"
	.string "etorri errebantxa bila!$"

MatchCall_Text_Roxanne3::
	.string "ROXANNE: {PLAYER}!\n"
	.string "Prest dago GIMNASIOA!\p"
	.string "Etorri zaitez BURDINTZARA\n"
	.string "ahal duzunean!$"

MatchCall_Text_Roxanne4::
	.string "ROXANNE: BURDINTZAKO GIMNASIOAN\n"
	.string "elkarrekin borrokatu izana, {PLAYER},\l"
	.string "harrotzeko kontua da.$"

MatchCall_Text_Brawly1::
	.string "BRAWLY: Ei, aizu, {PLAYER}{KUN}!\p"
	.string "Asko ikasi dut borroka izan\n"
	.string "genuen hartatik.\p"
	.string "Gehiago entrenatu eta GIMNASIOA\n"
	.string "berriz irekitzekotan nago.\p"
	.string "Denbora pixka bat beharko dut\n"
	.string "GIMNASIOA berriz irekitzeko.\p"
	.string "Baina irekitzen dudanean, gure\n"
	.string "aurka borrokatzea nahi nuke.$"

MatchCall_Text_Brawly2::
	.string "BRAWLY: Ei, {PLAYER}{KUN}!\n"
	.string "Zorionak!\p"
	.string "Zure izena lau haizetara\n"
	.string "zabaldu da, e!\p"
	.string "Badirudi gehixeago entrenatu\n"
	.string "beharko dudala.\p"
	.string "Denbora pixka bat beharko dut\n"
	.string "GIMNASIOA berriz irekitzeko.\p"
	.string "Baina irekitzen dudanean, gure\n"
	.string "aurka borrokatzea nahi nuke.$"

MatchCall_Text_Brawly3::
	.string "BRAWLY: Ei, {PLAYER}{KUN}!\n"
	.string "Nire GIMNASIOA irekita dago!\p"
	.string "Etorri IHINTZIBARRERA erronka\n"
	.string "bila bazabiltza!$"

MatchCall_Text_Brawly4::
	.string "BRAWLY: {PLAYER}{KUN}, uste dut ez\n"
	.string "naizela inoiz aspertuko zure aurka!$"

MatchCall_Text_Wattson1::
	.string "WATTSON: Ei, zu zara!\p"
	.string "Joan zinenetik, zerotik hasi\n"
	.string "nintzen entrenatzen.\p"
	.string "Denbora apur bat gehiago behar\n"
	.string "dut GIMNASIOA berriz irekitzeko.\p"
	.string "Itxaron egin beharko duzu!\n"
	.string "Kar-kar-kar!$"

MatchCall_Text_Wattson2::
	.string "WATTSON: Kar-kar-kar!\p"
	.string "Famatu egin zara, ez da hala?\n"
	.string "Zutaz asko hitz egiten du jendeak!\p"
	.string "Badirudi gehiago entrenatu beharko\n"
	.string "dudala, beraz.\p"
	.string "Denbora apur bat gehiago behar\n"
	.string "dut GIMNASIOA berriz irekitzeko.\p"
	.string "Itxaron egin beharko duzu!\n"
	.string "Kar-kar-kar!$"

MatchCall_Text_Wattson3::
	.string "WATTSON: Ei, zu zara!\n"
	.string "GIMNASIOA prest dago!\p"
	.string "Etorri MALBADIRA nahi duzunean!\n"
	.string "Kar-kar-kar!$"

MatchCall_Text_Wattson4::
	.string "WATTSON: Kar-kar-kar!\p"
	.string "Zure aurkako borrokak boterez\n"
	.string "kargatuta egoten dira!$"

MatchCall_Text_Flannery1::
	.string "FLANNERY: {PLAYER}…\p"
	.string "Borrokatu genuenean ohartu nintzen\n"
	.string "heldutasuna falta nuela.\p"
	.string "Baina oraindik badut zer egin!\p"
	.string "Nire entrenamendua berregin eta\n"
	.string "GIMNASIOA berriz irekiko dut.\p"
	.string "Irekitzen dudanean, {PLAYER},\n"
	.string "etorri guregana berriz, mesedez.$"

MatchCall_Text_Flannery2::
	.string "FLANNERY: Kaixo, {PLAYER}?\n"
	.string "Zorionak!\p"
	.string "Zure arrakasta sumendi bateko\n"
	.string "errautsa bezala zabaltzen ari da!\p"
	.string "Gure entrenamendua bide oso onetik\n"
	.string "doa, bai.\p"
	.string "GIMNASIOA prest dudanean, marka\n"
	.string "bat agertuko da BORROKA ZERRENDAN\l"
	.string "nire izenaren alboan.$"

MatchCall_Text_Flannery3::
	.string "FLANNERY: Ei, {PLAYER}?\n"
	.string "GIMNASIOA prest!\p"
	.string "Etorri LABARANERA, bainu bat eman\n"
	.string "eta borrokatu gure aurka!$"

MatchCall_Text_Flannery4::
	.string "FLANNERY: {PLAYER}…\n"
	.string "Ziur nago gero eta hobea zarela\l"
	.string "borrokan.$"

MatchCall_Text_Winona1::
	.string "WINONA: Kaixo, {PLAYER}!\p"
	.string "Gure borrokari esker nire puntu\n"
	.string "ahulak identifikatu nituen!\p"
	.string "GIMNASIOA berriz irekitzen dudanean\n"
	.string "ez pentsa berriz galduko dudanik!$"

MatchCall_Text_Winona2::
	.string "WINONA: Lortu duzu, {PLAYER}!\p"
	.string "TXAPELDUN berriaren istorioa\n"
	.string "ZUHAITZAGARAINO iritsi da!\p"
	.string "Baina… Berriz borrokatzen dugunean,\n"
	.string "ez da aurrekokoa gertatuko.$"

MatchCall_Text_Winona3::
	.string "WINONA: {PLAYER} al zara?\n"
	.string "Gure GIMNASIOA prest dago!\p"
	.string "Zure zain gaude ZUHAITZAGAN!$"

MatchCall_Text_Winona4::
	.string "WINONA: {PLAYER}…\n"
	.string "Galdu badut ere, ez dizkidate\l"
	.string "hegoak inoiz ebakiko.\p"
	.string "Bai, zuk zure ametsa betetzeko\n"
	.string "gogoa galduko ez duzun bezala.$"

MatchCall_Text_TateLiza1::
	.string "TATE: Ei! Zu zara…\n"
	.string "LIZA: {PLAYER}!\p"
	.string "TATE: Entrenatzen ari gara…\n"
	.string "LIZA: GIMNASIOA berriz irekitzeko!\p"
	.string "TATE: GIMNASIOA prestatzen dugunean…\n"
	.string "LIZA: GIMNASIOA prestatzen dugunean…\p"
	.string "TATE: Marka bat agertuko zaizu…\n"
	.string "LIZA: Zure BORROKA ZERRENDAN.$"

MatchCall_Text_TateLiza2::
	.string "TATE: {PLAYER}, zorionak!\n"
	.string "LIZA: {PLAYER}, zorionak!\p"
	.string "TATE: Gu biok oraindik…\n"
	.string "LIZA: Entrenatzen ari gara!\p"
	.string "TATE: Denbora pixka bat behar dugu…\n"
	.string "LIZA: Baina GIMNASIOA prestatzean…\p"
	.string "TATE: Marka bat agertuko zaizu…\n"
	.string "LIZA: Zure BORROKA ZERRENDAN.$"

MatchCall_Text_TateLiza3::
	.string "TATE: {PLAYER}!\n"
	.string "LIZA: {PLAYER}!\p"
	.string "TATE: Gure GIMNASIOA prest dago!\n"
	.string "LIZA: Gure GIMNASIOA prest dago!\p"
	.string "TATE: Nahi duzunean etorri…\n"
	.string "LIZA: GOROLDI hirira!$"

MatchCall_Text_TateLiza4::
	.string "TATE: {PLAYER}, izan genuen borroka…\n"
	.string "LIZA: Esperientzia ezin hobea izan zen.\p"
	.string "TATE: Ondo egongo litzateke…\n"
	.string "LIZA: Berriro borrokatuko bagenu!$"

MatchCall_Text_Juan1::
	.string "JUAN: Hmm…\n"
	.string "{PLAYER}{KUN}… Ezta?\p"
	.string "Gure arteko borrokak--lehen aldiz\n"
	.string "WALLACE ezagutu nueneko oroitzapenak\l"
	.string "ekarri zizkidan burura.\p"
	.string "Agian zu izango zara WALLACE\n"
	.string "garaituko duena!$"

MatchCall_Text_Juan2::
	.string "JUAN: Fufu… {PLAYER}{KUN}…\n"
	.string "Azkenean lortu duzu zure helburua.\p"
	.string "Talentua detektatzeko dudan ahalmena\n"
	.string "ondo dabil, dirudienez…\p"
	.string "Espero dut berriro ikusiko zaitudala,\n"
	.string "botere eta prestigioa lortu\l"
	.string "duzunetik.$"

MatchCall_Text_Juan3::
	.string "JUAN: Hoho… {PLAYER}{KUN}…\p"
	.string "ARREZIPOLISEKO GIMNASIOA ireki\n"
	.string "dut azkenean.\p"
	.string "Bisitatu nahi baduzu, ongi\n"
	.string "etorria izango zara, badakizu.$"

MatchCall_Text_Juan4::
	.string "JUAN: {PLAYER}{KUN}…\p"
	.string "Musika gorenena balitz bezala,\n"
	.string "gure arteko borrokako akordeek\l"
	.string "bihotza kitzikatzen didate…\p"
	.string "Begiak ixten ditudanean, zu ikusten\n"
	.string "zaitut, melodiaren aurrean bikain…$"

MatchCall_Text_Sidney::
	.string "SIDNEY: Iei, {PLAYER}!\p"
	.string "Nire aurka berriz borrokatu\n"
	.string "nahi baduzu, etorri nahi\l"
	.string "duzunean POKéMON LIGARA.\p"
	.string "Hortxe egongo naiz beti!\n"
	.string "Zure zain izango naiz!$"

MatchCall_Text_Phoebe::
	.string "PHOEBE: Kaixo, {PLAYER}!\p"
	.string "Zer iruditzen zaizu hemendik\n"
	.string "pasatzen bazara noizbait?\p"
	.string "GUstatuko litzaidake zu eta zure\n"
	.string "POKÉMONEN arteko lotura nola\l"
	.string "hazi den ikustea.$"

MatchCall_Text_Glacia::
	.string "GLACIA: Kaixo, {PLAYER}.\p"
	.string "Espero dut ez zarela zure boterearekin\n"
	.string "konformatuta egongo ezta?\p"
	.string "Zure emozio horiek pixka bat lasaitu\n"
	.string "nahi bazenitu, etorri POKéMON LIGARA\l"
	.string "nahi duzunean…$"

MatchCall_Text_Drake::
	.string "DRAKE: Ahots hori… {PLAYER}, ezta?\n"
	.string "Ondo zaudela dirudi…\p"
	.string "Entzun dut BORROKA FRONTEA\n"
	.string "izena duen leku bat ireki dutela\l"
	.string "ENTRENATZAILEEN abilezia eta indarra\l"
	.string "neurtzeko.\p"
	.string "hala ere, benetako borrokak bizi\n"
	.string "nahi badizutu, ez dago POKéMON LIGA\l"
	.string "baino leku hoberik horretarako!\p"
	.string "Ez al da egia, {PLAYER}?$"

MatchCall_Text_Wallace::
	.string "WALLACE: Kaixo, {PLAYER}{KUN}.\n"
	.string "Ezagutzen al duzu STEVEN?\p"
	.string "Bera…\n"
	.string "Izugarri trebea da.\p"
	.string "Hala ere, ia inoiz ez du\n"
	.string "borrokatzen.\p"
	.string "Nahiago izaten du harri arraroen\n"
	.string "bila ibili.\p"
	.string "Ziur nago oraintxe bertan kobazulo\n"
	.string "edo mendiren batean ibiliko dela.\p"
	.string "Baina zer da harri arraro bat zehazki?\n"
	.string "Niri burura METEORITOAK soilik datorzkit…$"

MatchCall_Text_MayRayquazaCall:
	.string "… … … … … …\n"
	.string "… … … … … Bip!\p"
	.string "MAIA: Aupa, {PLAYER}{KUN}!\p"
	.string "URREBAREN egon berri naiz duela\n"
	.string "gutxi.\p"
	.string "POKéMON berde erraldoi bat ikusi\n"
	.string "dut zeruan hegan.\p"
	.string "Nik…\n"
	.string "Ez dut inoiz horrelako ezer ikusi.\p"
	.string "Zer izango ote zen?\n"
	.string "Aurkikuntza berri bat egin ote dut?\p"
	.string "… … … … … …\n"
	.string "… … … … … Klik!$"

MatchCall_Text_BrendanRayquazaCall:
	.string "… … … … … …\n"
	.string "… … … … … Bip!\p"
	.string "BRENDAN: Iepa, {PLAYER}!\n"
	.string "URREBAREN egon berri naiz.\p"
	.string "POKéMON berde erraldoi bat ikusi\n"
	.string "dut zeruan hegan.\p"
	.string "Inoiz ez dut hain txundigarria\n"
	.string "den ezer ikusi.\p"
	.string "Ikusi egin behar zenuen,\n"
	.string "{PLAYER}.\p"
	.string "… … … … … …\n"
	.string "… … … … … Klik!$"

MatchCall_Text_May1::
	.string "MAIA: Kaixo, {PLAYER}{KUN}!\p"
	.string "SARDINZAR JN. jada ez da MARINELA,\n"
	.string "baina ikusten dut itsasoan\l"
	.string "bere PEEKOrekin batzuetan.\p"
	.string "Ziur oraindik itsasoa maite duela.$"

MatchCall_Text_May2::
	.string "MAIA: Kaixo, {PLAYER}{KUN}!\p"
	.string "Badakizu PETALORE eta IHINTZIBAR\n"
	.string "herrietan GIMNASIOAK daudela, ezta?\p"
	.string "Ba, auskalo zergatik baina PORTUONDO\n"
	.string "bezalako hiri handi batek ez du bat.\p"
	.string "Bertan GIMNASIO bat irekitzean,\n"
	.string "LIDER izateko aurkeztu behar nuke.$"

MatchCall_Text_May3::
	.string "MAIA: Aupa, {PLAYER}{KUN}!\p"
	.string "Gogoratzen duzu MOZTAILEA izeneko\n"
	.string "gizona, BURDINTZAKOA?\l"
	.string "Etxe bat zuen bertan, ezta?\p"
	.string "Ba jakin dut bere anaia\n"
	.string "MALBADIN bizi dela.\p"
	.string "Badakizu zein den bere izena?\p"
	.string "… … … … … …\n"
	.string "… … … … … …\p"
	.string "ARROKA KOLPE TIPOA!$"

MatchCall_Text_May4::
	.string "MAIA: {PLAYER}{KUN}?\p"
	.string "BURDIZELAI TUNELA…\n"
	.string "Izen hori jarri zioten BURDINTZA\l"
	.string "eta BERDEZELAI lotzen dituelako.$"

MatchCall_Text_May5::
	.string "MAIA: {PLAYER}{KUN}, zer moduz?\p"
	.string "111. ERRUTAN nago orain.\p"
	.string "Emakume zahar baten etxean geratuko\n"
	.string "naiz pixka bat deskantsatzen.\p"
	.string "basamortuaren iparraldean\n"
	.string "bizi da.$"

MatchCall_Text_May6::
	.string "MAIA: Kaixo, {PLAYER}{KUN}!\p"
	.string "Ezagutzen duzu basamortuko\n"
	.string "ISPILATZE DORREA?\p"
	.string "Diotenez, ispilatze bat bezala,\n"
	.string "bat-batean agertzen eta desagertzen da.\p"
	.string "Ikusi nahi nuke nik, bada.$"

MatchCall_Text_May7::
	.string "MAIA: {PLAYER}{KUN}, iepa!\n"
	.string "119. ERRUTAN nago.\p"
	.string "Erreka handi bat dago hemen\n"
	.string "eta euri asko egiten du.\p"
	.string "Blai egin naiz!$"

MatchCall_Text_May8::
	.string "MAIA: {PLAYER}{KUN}, aupa.\p"
	.string "PIRO MENDIA zendu diren POKéMONei\n"
	.string "egindako oroigarri bat da.\p"
	.string "Agian horregatik dago MAMU\n"
	.string "motako POKéMONez gainezka!$"

MatchCall_Text_May9::
	.string "MAIA: Kaixo, {PLAYER}{KUN}!\p"
	.string "LABARANEKO ur termaletara joatea\n"
	.string "pentsatu dut.\p"
	.string "Portzierto, HAIZPITARTE\n"
	.string "inguruan, itxura txarreko jendea\l"
	.string "ikusi dut. Ez zen giro bertan!$"

MatchCall_Text_May10::
	.string "MAIA: Kaixo, {PLAYER}{KUN}!\n"
	.string "Entzun dituzu berriak?\p"
	.string "ABABOR KAPITAINAK, bere espedizio\n"
	.string "batean KOBAZULO ABISALA aurkitu\l"
	.string "zutela diote.$"

MatchCall_Text_May11::
	.string "MAIA: Hi, {PLAYER}{KUN}!\n"
	.string "Ez al zaizu itzela iruditzen?\p"
	.string "Itsasontzi bat ez baduzu ere,\n"
	.string "itsasoan nabigatu dezakezu\l"
	.string "POKéMON baten erasoa erabiliz.\p"
	.string "Eta badakizu zer gehiago?\p"
	.string "Ba omen da beste POKéMON eraso bat\n"
	.string "itsas hondora eraman zaitzakeena.$"

MatchCall_Text_May12::
	.string "MAIA: Kaixo, {PLAYER}{KUN}!\n"
	.string "Dena ondo dela espero dut!\p"
	.string "Inoiz egon zara itsasoan eta\n"
	.string "beste aldera pasatzeko bidea\l"
	.string "arrokek itxita aurkitu?\p"
	.string "Ba saiatu itsas hondora jaisten\n"
	.string "eta jarraitu ur azpiko bideak.\p"
	.string "Beste aldera iristen zarenean,\n"
	.string "atera berriz gora. Erraza!$"

MatchCall_Text_May13::
	.string "MAIA: Kaixo, {PLAYER}{KUN}!\p"
	.string "Zer moduz?\n"
	.string "Ari al zara POKéDEXa betezen?\p"
	.string "Entzun dut aspaldi-aspaldiko\n"
	.string "POKéMONak daudela hor nonbait.\l"
	.string "Hiru omen dira denera!\p"
	.string "Bakarra ikusita pozik negoke ni, bada…$"

MatchCall_Text_May14::
	.string "MAIA: {PLAYER}{KUN}!\n"
	.string "Zurrumurrua entzun dut!\p"
	.string "ARREZIPOLISEKO LIDERRA \n"
	.string "garaitu duzu?\p"
	.string "Horrek esan nahi du ia iritsi\n"
	.string "zarela bukaerara ezta?$"

MatchCall_Text_May15::
	.string "MAIA: HOENNeko ENTRENATZAILE\n"
	.string "guzti-guztiek ezagutzen zaituzte,\l"
	.string "{PLAYER}{KUN}!\p"
	.string "Zure laguna naizela esaten diedanean,\n"
	.string "{PLAYER}{KUN}, harri eta zur geratzen\l"
	.string "dira guztiak!$"

MatchCall_Text_Brendan1::
	.string "BRENDAN: Ei, {PLAYER}!\p"
	.string "SARDINZAR JN. jada ez da MARINELA,\n"
	.string "baina oraindik itsasoan ikusten dut\l"
	.string "bere PEEKOrekin batzuetan.\p"
	.string "Ziru nago oraindik asko\n"
	.string "maite duela itsasoa.$"

MatchCall_Text_Brendan2::
	.string "BRENDAN: Iepa, {PLAYER}!\p"
	.string "Ez dut ulertzen PETALORE eta IHINTZIBAR\n"
	.string "bezalako herriek GIMNASIOA izatea.\p"
	.string "Kontuan hartuta PORTUONDO bezalako\n"
	.string "hiri batek ez duela GIMNASIORIK.\p"
	.string "GIMNASIO bat eraikitzen dutenean,\n"
	.string "LIDER izateko izena emango dut.$"

MatchCall_Text_Brendan3::
	.string "BRENDAN: Iep, {PLAYER}!\p"
	.string "Gogoratzen duzu MOZTAILEA\n"
	.string "izeneko tipo bat, BURDINTZAKOA?\l"
	.string "Etxe bat zuen bertan ezta?\p"
	.string "Ba jakin dut bere anaia\n"
	.string "MALBADIN bizi dela.\p"
	.string "Badakizu zein den bere izena?\p"
	.string "… … … … … …\n"
	.string "… … … … … …\p"
	.string "ARROKA KOLPE TIPOA!$"

MatchCall_Text_Brendan4::
	.string "BRENDAN: Ahots hau… {PLAYER}?\p"
	.string "BURDIZELAI TUNELARI izen hori eman\n"
	.string "zioten BURDINTZA eta BERDEZELAI\l"
	.string "lotzen dituelako.\p"
	.string "Ba al zenekien?$"

MatchCall_Text_Brendan5::
	.string "BRENDAN: {PLAYER}, zer moduz?\p"
	.string "111. ERRUTAN nago orain.\p"
	.string "Emakume zahar baten etxean deskantsatuko\n"
	.string "dut, basamortuaren iparraldean.\p"
	.string "Inguruan bazabiltza, zuk ere \n"
	.string "bisitatu behar zenuke.$"

MatchCall_Text_Brendan6::
	.string "BRENDAN: Iepa, {PLAYER}!\p"
	.string "Ezagutzen duzu basamortuko\n"
	.string "ISPILATZE DORREA?\p"
	.string "Diotenez, ispilatze bat bezala,\n"
	.string "bat-batean agertzen eta desagertzen da.\p"
	.string "Ikusi nahi nuke nik, bada.$"

MatchCall_Text_Brendan7::
	.string "BRENDAN: Nor da? Ah, {PLAYER}?\n"
	.string "Badakizu zer? 119. ERRUTAN nago.\p"
	.string "Erreka handi bat dago hemen\n"
	.string "eta euri asko egiten du.\p"
	.string "Blai egin naiz!$"

MatchCall_Text_Brendan8::
	.string "BRENDAN: {PLAYER}!\p"
	.string "PIRO MENDIA zendu diren POKéMONei\n"
	.string "egindako oroigarri bat da.\p"
	.string "Agian horregatik dago MAMU\n"
	.string "motako POKéMONez gainezka!$"

MatchCall_Text_Brendan9::
	.string "BRENDAN: Kaixo, {PLAYER}.\p"
	.string "LABARANEKO ur termaletara\n"
	.string "nindoan aurrekoan.\p"
	.string "Baina HAIZPITARTE parean itxura\n"
	.string "txarreko jendea ikusi dut.\p"
	.string "Tipo horiek…\n"
	.string "MAGMA TALDEKOAK zirela uste dut.$"

MatchCall_Text_Brendan10::
	.string "BRENDAN: Epa, {PLAYER}!\n"
	.string "Entzun dituzu berriak?\p"
	.string "Diotenez, ABABOR KAPITAINAK bere\n"
	.string "itsas azpiko espedizio batean aurkitu\l"
	.string "zuen KOBAZULO ABISALA.$"

MatchCall_Text_Brendan11::
	.string "BRENDAN: Kaixo, {PLAYER}!\n"
	.string "Ez al zaizu itzela iruditzen?\p"
	.string "Itsasontzi bat ez baduzu ere,\n"
	.string "itsasoan nabigatu dezakezu\l"
	.string "POKéMON baten erasoa erabiliz.\p"
	.string "Ba omen da beste POKéMON eraso bat\n"
	.string "itsas hondora eraman zaitzakeena.\p"
	.string "POKÉMONEK edozer egin dezakete!$"

MatchCall_Text_Brendan12::
	.string "BRENDAN: Iepa, {PLAYER}!\n"
	.string "Zer moduz zabiltza?\p"
	.string "Inoiz aurkitu duzu bidea itxita\n"
	.string "itsasoan zenbiltzan bitartean?\p"
	.string "Ba saiatu ur itsas hondora jaisten\n"
	.string "eta jarraitu ur azpiko bideak.\p"
	.string "Beste aldera iristen zarenean,\n"
	.string "atera berriz gora. Erraza!$"

MatchCall_Text_Brendan13::
	.string "BRENDAN: Hey there, {PLAYER}!\p"
	.string "Zer moduz? Ari al zara\n"
	.string "POKéDEXa betetzen?\p"
	.string "Entzun dut aspaldi-aspaldiko\n"
	.string "POKéMONak daudela hor nonbait.\l"
	.string "Hiru omen dira denera!\p"
	.string "Bakarra ikusita pozik negoke ni, bada…$"

MatchCall_Text_Brendan14::
	.string "BRENDAN: {PLAYER}!\n"
	.string "Zurrumurrua entzun dut!\p"
	.string "ARREZIPOLISEKO LIDERRA\n"
	.string "garaitu duzu? Itzela!\p"
	.string "Bukaerara iristen ari zara!$"

MatchCall_Text_Brendan15::
	.string "BRENDAN: HOENNeko ENTRENATZAILE\n"
	.string "guzti-guztiek ezagutzen zaituzte,\l"
	.string "{PLAYER}{KUN}!\p"
	.string "Zure laguna naizela esaten diedanean,\n"
	.string "{PLAYER}{KUN}, inbidiaz gorri jartzen\l"
	.string "dira guztiak!$"

MatchCall_Text_Wally1::
	.string "WALLY: Ei, {PLAYER}!\p"
	.string "Osasuntsuago eta fisikoki\n"
	.string "hobeto jartzen ari naiz.\p"
	.string "Laister ENTRENATZAILE bihurtuko naiz\n"
	.string "zu bezala, {PLAYER}!$"

MatchCall_Text_Wally2::
	.string "WALLY: {PLAYER}, kaixo!\p"
	.string "BURDIZELAI TUNELA igaro ondoren,\n"
	.string "WANDA oso pozik ibili da!$"

MatchCall_Text_Wally3::
	.string "WALLY: Iep, {PLAYER}!\p"
	.string "Ni… nire osabaren etxetik joan\n"
	.string "nintzen inori ezer esan gabe.\p"
	.string "Haserre egongo ote da nirekin…\p"
	.string "{PLAYER}, zuk ulertzen didazu,\n"
	.string "ez da hala?$"

MatchCall_Text_Wally4::
	.string "WALLY: {PLAYER}?\n"
	.string "Ni naiz, WALLY!\p"
	.string "ENTRENATZAILEEN mundua itzela da!\p"
	.string "Nire POKéMONak aldean ditudanean,\n"
	.string "mundu guztiak agurtzen nau!\p"
	.string "Guztiak POKéMONei esker konektatuta\n"
	.string "egongo bagina bezala da!$"

MatchCall_Text_Wally5::
	.string "WALLY: {PLAYER}? Izugarria da!\n"
	.string "Elkarrekin harrapatu genuen RALTSa?\l"
	.string "Eboluzionatu egin da, {PLAYER}!\p"
	.string "Agian badut talenturik…\p"
	.string "Ez, baina ez nintzateke horrela\n"
	.string "harrotu behar!\p"
	.string "Azkenean, hemen meritua dutenak\n"
	.string "POKéMONak dira eta!$"

MatchCall_Text_Wally6::
	.string "… … … … … …\n"
	.string "… … … … … …\p"
	.string "WALLYk ez du POKéNAVeko\n"
	.string "estaldurarik orain…$"

MatchCall_Text_Wally7::
	.string "WALLY: Epa, {PLAYER}!\p"
	.string "Zu ezagutu aurretik ez nintzen\n"
	.string "etxetika tera ere egiten…\p"
	.string "Baina orain nire POKÉMONEKIN\n"
	.string "sekulako abentura batean nabil…\p"
	.string "{PLAYER}…\n"
	.string "Eskerrik asko…$"

MatchCall_Text_Scott1::
	.string "TRIKI: Howdy, {PLAYER}{KUN}!\p"
	.string "Badakizu POKéMONak leku guzti-guztietan\n"
	.string "aurkitu daitezkeela, baietz?\p"
	.string "Mendietan, itsasoan,\n"
	.string "belar altuan, edonon?\p"
	.string "Bada POKéMONak bezala, ENTRENATZAILEAK\n"
	.string "ere leku guztietan aurki ditzakezu.\p"
	.string "Horregatik, leku guztietara presaka\n"
	.string "ibiltzen naiz. Azkar, azkar!$"

MatchCall_Text_Scott2::
	.string "TRIKI: 119. ERRUTAN NAGO.\n"
	.string "ENTRENATZAILEZ lepo dago!\p"
	.string "Eta leku guztietan belar garaia\n"
	.string "ere badagoela dirudi.\p"
	.string "Galtza motzetan nago eta kili-kili\n"
	.string "egiten dit hanketan!$"

MatchCall_Text_Scott3::
	.string "TRIKI: Epa, epa, {PLAYER}{KUN}!\p"
	.string "Eskalatu al duzu jada\n"
	.string "PIRO MENDIA?\p"
	.string "Zendutako POKéMONei egindako\n"
	.string "oroigarri bat da.\p"
	.string "ENTRENATZAILE orok igo behar\n"
	.string "luke tontorrera behin gutxienez.$"

MatchCall_Text_Scott4::
	.string "TRIKI: Aupa, {PLAYER}{KUN}!\p"
	.string "Entzun dut talde arraro horiek\n"
	.string "enbarazu egiten ari direla edonon.\p"
	.string "MAGMA TALDEA ETA AQUA TALDEA,\n"
	.string "Horrela zuten izena.\p"
	.string "Esango nuke ENTRENATZAILE trebeak\n"
	.string "daudela bi taldeetan.\p"
	.string "…Baina gaiztaginak badira…$"

MatchCall_Text_Scott5::
	.string "TRIKI: Kaixo, {PLAYER}{KUN}.\p"
	.string "Egongo ote da ENTRENATZAILE\n"
	.string "indartsurik itsas hondoan?\p"
	.string "Nik ezin dut begiratu.\n"
	.string "Alde batetik, ez dakit igerian.\l"
	.string "Eta gainera, ez daukat POKéMONik…$"

MatchCall_Text_Scott6::
	.string "TRIKI: Epa, epa, {PLAYER}{KUN}!\p"
	.string "Badakizu GIMNASIOETAKO DOMINA\n"
	.string "guztiak lortzen dituzunean POKéMON\l"
	.string "LIGARA joan zaitezkeela, ezta?\p"
	.string "Duzun talentuarekin, TXAPELDUN\n"
	.string "bihurtzea lor dezakezu.\p"
	.string "Baina, badakizu zer?\n"
	.string "Are toki hobe bat existitzen da.\p"
	.string "Baina, oraingoz, hori da kontatuko\n"
	.string "dizudan guztia.\p"
	.string "Etorkizun batean erronka horri aurre\n"
	.string "egin behar zenioke.\p"
	.string "Baina lehenik eta behin POKéMON\n"
	.string "LIGA irabazi eta OSPEAREN ARETORA\l"
	.string "iritsi behar duzu!$"

MatchCall_Text_Scott7::
	.string "… … … … … …\n"
	.string "… … … … … …\p"
	.string "TRIKIK ez du POKéNAVeko\n"
	.string "estaldurarik orain…$"

MatchCall_Text_Norman1::
	.string "AITA: BURDINTZAN bada gizon bat\n"
	.string "MOZTAILEA deitzen diotena.\l"
	.string "Izen arraroa, ezbairik gabe.\p"
	.string "Hurbil bazabiltza, bisitatu\n"
	.string "egin behar zenuke.$"

MatchCall_Text_Norman2::
	.string "AITA: Hm… Apurka apurka baina\n"
	.string "etenik gabe, gero eta indartsuago\l"
	.string "bihurtzen ari zara, {PLAYER}.\p"
	.string "Zenbat eta indatsuago, orduan eta\n"
	.string "independenteago bihurtzen zara ama\l"
	.string "eta nigandik…\p"
	.string "Ez da azaltzeko sentimendu erraza.$"

MatchCall_Text_Norman3::
	.string "AITA: Ederki, ederki…\n"
	.string "Lau GIMNASIOTAKO DOMINAK dituzu.\p"
	.string "Iritsi da ordua, beraz.\n"
	.string "Borrokatu egingo dugu, esan nizunez.\p"
	.string "Etorri nahi duzunean.\n"
	.string "Zure zain egongo gara denok!$"

MatchCall_Text_Norman4::
	.string "AITA: {PLAYER}! Noizean behin ama\n"
	.string "bisitatu behar zenuke.\p"
	.string "Ni hemen geratuko naiz\n"
	.string "buru belarri entrenatzen.\p"
	.string "Borrokaren bidea zitala\n"
	.string "eta gogorra da eta!$"

MatchCall_Text_Norman5::
	.string "AITA: Aupa, {PLAYER}!\p"
	.string "Zer da hori? MAGMA ENBLEMA?\n"
	.string "Ez dakit zer den hori.\p"
	.string "Baina duen izenarekin, ziur\n"
	.string "sumendiekin lotura duela!$"

MatchCall_Text_Norman6::
	.string "AITA: Jiaaa! Aaah! Fuaa!\p"
	.string "…Ein? {PLAYER}!\p"
	.string "POKéMON entrenamendu betean\n"
	.string "harrapatu nauzu!$"

MatchCall_Text_Norman7::
	.string "AITA: {PLAYER}!\p"
	.string "Nork esango zuen POKéMON LIGAKO\n"
	.string "TXAPELDUNA izango zinela…\p"
	.string "Ongi, beraz!\n"
	.string "Ez naiz atzean geratuko!$"

MatchCall_Text_Norman8::
	.string "AITA: Hm? {PLAYER}?\n"
	.string "Une egokia, alajaina!\p"
	.string "Oraingoan nik botako dizut borroka\n"
	.string "baterako erronka.\p"
	.string "PETALOREKO GIMNASIOAN nago.\n"
	.string "Etorri nahi duzunean!$"

MatchCall_Text_Norman9::
	.string "AITA: …Harrigarria zara, {PLAYER}.\n"
	.string "Noraino iritsiko ote zara?$"

MatchCall_Text_Steven1::
	.string "STEVEN: Kaixo, {PLAYER}{KUN}!\p"
	.string "Izan al zara MALBADIN\n"
	.string "jada?\p"
	.string "BIZIKLETA DENDARA joan behar duzu\n"
	.string "eta LASTERKETAKO BIZIKLETA probatu.\p"
	.string "Ondoren, GRANITO KOBAZULOA esploratu\n"
	.string "behar zenuke goitik behera.\p"
	.string "Agian zeozer aurkitu dezakezu\n"
	.string "bertan.$"

MatchCall_Text_Steven2::
	.string "STEVEN: Kaixo, {PLAYER}{KUN}!\p"
	.string "ENTRENATZAILE asko ezagutu\n"
	.string "ditut orain arte.\p"
	.string "Baina zu berezia zara.\n"
	.string "Ez zara besteak bezalakoa.$"

MatchCall_Text_Steven3::
	.string "STEVEN: Kaixo, {PLAYER}{KUN}!\p"
	.string "Zure POKÉMONEKIN abentura batean\n"
	.string "zaudenean, zer pentsatu ohi duzu?\p"
	.string "Kide indartsuak direla pentsatzen\n"
	.string "duzu?\p"
	.string "Edo lagun dibertigarriak\n"
	.string "direla?\p"
	.string "Pentsatzen duzunaren arabera\n"
	.string "zure abentura aldatzen da.$"

MatchCall_Text_Steven4::
	.string "STEVEN: Kaixo?\n"
	.string "{PLAYER}{KUN}?\p"
	.string "ESPAZIO ZENTROAN nago arazo\n"
	.string "batean harrapatuta.\p"
	.string "Barkatu, orain ezin dut hitz egin.\n"
	.string "Aio!$"

MatchCall_Text_Steven5::
	.string "STEVEN: Aizu!\n"
	.string "{PLAYER}{KUN}!\p"
	.string "Ez dugu hitz egin beharrik.\n"
	.string "Jada ez da hitz egiteko garaia.\p"
	.string "Zugan sinistu behar duzu orain,\n"
	.string "eta egin beharrekoa egin.$"

MatchCall_Text_Steven6::
	.string "… … … … … …\p"
	.string "Badirudi STEVENEK ez duela deia\n"
	.string "hartu…$"

MatchCall_Text_Steven7::
	.string "STEVEN: {PLAYER}{KUN}… Zorionak\n"
	.string "OSPEAREN ARETORA sartzeagatik.\p"
	.string "… … … … … …\n"
	.string "… … … … … …\p"
	.string "Espero dut ikusiko dugula\n"
	.string "elkar berriro!$"

MatchCall_Text_BirchRegisterCall:
	.string "URKI DOKT.: Aizu, {PLAYER}{KUN}!\n"
	.string "Zutaz hitz egin didate, bai!\p"
	.string "Orain zure POKéNAVak\n"
	.string "BORROKA ZERRENDA dauka.\p"
	.string "Beno, ni ere erregistratuko naiz!\p"
	.string "Horrela zure POKéDEXa aztertzeko\n"
	.string "gai izango naiz, nahiz eta ez\l"
	.string "egon hemen.\p"
	.string "… … … … … …$"

MatchCall_Text_RegisteredBirch:
	.string "URKI DOKT. erregistratu\n"
	.string "duzu POKéNAVean.$"

MatchCall_Text_UnusedProfBirch:
	.string "URKI DOKT.: Norbaitek POKéDEXa\n"
	.string "eta POKéNAVa ditueanean, POKéMONak\l"
	.string "aztertzea dibertigarriagoa da, ezta?$"

MatchCall_Text_MrStone1::
	.string "HARRI JN.: Oh? {PLAYER}{KUN}!\p"
	.string "Zuk deitu didazunez, POKéNAVa\n"
	.string "ondo dabilela dirudi!\p"
	.string "Jende gehiago ere gehitu dezakezu,\n"
	.string "probatzeko deitu beraiei ere!\p"
	.string "Ongi! Ongi!\n"
	.string "Pozik zaudela dirudi!\p"
	.string "Hm…\n"
	.string "Nola dakidan hori?\p"
	.string "Nire bulegoko leihotik zuri\n"
	.string "begira nagoelako oraintxe bertan!\p"
	.string "Kar-kar-kar!\n"
	.string "Ikusi arte!$"

MatchCall_Text_MrStone2::
	.string "HARRI JN.: Bai? {PLAYER}{KUN}!\p"
	.string "Zer gertatzen da? Ahaztu egin\n"
	.string "al zaizu eskatu nizun enkargua?\p"
	.string "Nire gutuna STEVENI eman behar\n"
	.string "diozu IHINTZIBAR herrian.\p"
	.string "Ondoren, paketea eman behar diozu\n"
	.string "ABABOR KAPITAINARI PORTUONDON.\p"
	.string "Gogoratzen zara, ezta?\p"
	.string "Beno, PRESIDENTE lanpetua naiz,\n"
	.string "joan egin behar dut! Aio-aio!$"

MatchCall_Text_MrStone3::
	.string "HARRI JN.: Ene! {PLAYER}{KUN}!\p"
	.string "Ezagutu duzu STEVEN, beraz!\n"
	.string "Orduan sari bat eman behar dizut!\p"
	.string "BURDINTZARA etortzen zarenean,\n"
	.string "etorri nire bulegora.\p"
	.string "Zure zain egongo naiz!$"

MatchCall_Text_MrStone4::
	.string "HARRI JN.: Ene! {PLAYER}{KUN}!\p"
	.string "Bazenekien DEVON BURDIZELAI\n"
	.string "TUNELA zulatzen ari zela?\p"
	.string "Baina gelditu egin genuen lana\n"
	.string "inguruko POKéMONak babesteko.\p"
	.string "Aukeraketa erraza izan da, bai.\p"
	.string "Askoz garrantzitsuagoa da POKéMONak\n"
	.string "bakean bizitzea, guk gure onerako\l"
	.string "tunel bat egitea baino.$"

MatchCall_Text_MrStone5::
	.string "HARRI JN.: Kaixo, kaixo, {PLAYER}{KUN}!\p"
	.string "PETALOREKO norbaitek esan dit\n"
	.string "NORMANen gaztea zarela!\p"
	.string "Badakit zergatik zaren horren\n"
	.string "gazte abila orain!$"

MatchCall_Text_MrStone6::
	.string "HARRI JN.: Zer esan duzu?\p"
	.string "Zure aitaren aurka borrokatu\n"
	.string "eta irabazi egin diozula?\p"
	.string "Harrigarria, gero!\p"
	.string "Ez nekien nire laguna horren pertsona\n"
	.string "izugarria zenik! kar-kar-kar!$"

MatchCall_Text_MrStone7::
	.string "Kaixo!\n"
	.string "DEVON KORPORAZIOA bai es…\l"
	.string "Oh, kaixo, {PLAYER}!\p"
	.string "Gure PRESIDENTEA hementxe egon\n"
	.string "berri da, baina joan egin da.\p"
	.string "Gure PRESIDENTEA lanpetuta dago,\n"
	.string "baina zu ere bai, {PLAYER}.$"

MatchCall_Text_MrStone8::
	.string "…Zer? …Zer esan duzu?\p"
	.string "GROU… Bai? …DON?\p"
	.string "Mozten ari da…\n"
	.string "…dut entzute…\p"
	.string "BZZZZ…$"

MatchCall_Text_MrStone9::
	.string "Zer? …Zer esan duzu?\p"
	.string "Kobazul… Bai? …Abisa…?\p"
	.string "Mozten ari da…\n"
	.string "…dut entzute…\p"
	.string "BZZZZ…$"

MatchCall_Text_MrStone10::
	.string "HARRI JN.: {PLAYER}{KUN}! Ni naiz!\p"
	.string "Mila gauzatan katramilatuta ibili\n"
	.string "zarela esan didate, baina horren\l"
	.string "lanpetuta egon naiz, ez dakit zertan!\p"
	.string "Hala ere, benetan sinisten duzun\n"
	.string "bidea aukeratu eta jarraitu behar duzu.\p"
	.string "Ni beti egongo naiz laguntzeko prest!\n"
	.string "Zaindu!$"

MatchCall_Text_MrStone11::
	.string "HARRI JN.: … … … … … …\n"
	.string "Hau al da {PLAYER}{KUN}?\p"
	.string "Ahotsa konfidantzaz gainezka duzu,\n"
	.string "ez zaitut ezagutu hasieran!\p"
	.string "Aizu! Gu bisitatzera etorri behar\n"
	.string "duzu DEVONERA!$"
