@ Only contains the text for the Mauville Man named Giddy. The rest is in scripts/mauville_man.inc
GiddyText_SoPretty::
	.string " zeinen ederra!$"

GiddyText_SoDarling::
	.string " zeinen maitagarria!$"

GiddyText_SoRelaxed::
	.string " zeinen erlaxatua!$"

GiddyText_SoSunny::
	.string " zeinen eguzkitsua!$"

GiddyText_SoDesirable::
	.string " zeinen desiragarria!$"

GiddyText_SoExciting::
	.string " zeinen zirraragarria!$"

GiddyText_SoAmusing::
	.string " zeinen dibertigarria!$"

GiddyText_SoMagical::
	.string " zeinen magikoa!$"

GiddyText_Is::
	.string " da$"

GiddyText_DontYouAgree::
	.string "\n"
	.string "Ez zaizu iruditzen?$"

GiddyText_ISoWantToGoOnAVacation::
	.string "Oporretan joateko gogo itzela dut.\n"
	.string "Ezagutzen al duzu leku egokirik?$"

GiddyText_IBoughtCrayonsWith120Colors::
	.string "120 koloretako margoak erosi ditut!\n"
	.string "Ez zaizu ederra iruditzen?$"

GiddyText_WouldntItBeNiceIfWeCouldFloat::
	.string "Burbuilaz betetako hodei batean\n"
	.string "flotatzea ederra litzateke, baietz?$"

GiddyText_WhenYouWriteOnASandyBeach::
	.string "Hondarretan idazten duzunean,\n"
	.string "ezabatu egiten dira. Triste jartzen nau.$"

GiddyText_WhatsTheBottomOfTheSeaLike::
	.string "Nolakoa da itsasoaren hondoa?\n"
	.string "Izugarri gustatuko litzaidake behin joatea!$"

GiddyText_WhenYouSeeTheSettingSunDoesIt::
	.string "Eguzkia sartzen ikusten duzunean,\n"
	.string "etxera joateko gogoa ematen al dizu?$"

GiddyText_LyingBackInTheGreenGrass::
	.string "Belar berdean etzanda egotea…\n"
	.string "Benetan atsegina da!$"

GiddyText_SecretBasesAreSoWonderful::
	.string "BASE SEKRETUAK itzelak dira!\n"
	.string "Sentitzen al duzu zirrara?$"
