MoveTutor_Text_ThisMoveCanOnlyBeLearnedOnce:
	.string "Eraso hau behin bakarrik erakutsi\n"
	.string "daiteke. Ados?$"

MoveTutor_Text_SwaggerTeach:
	.string "Kar kar! Nire POKéMONA onena da!\n"
	.string "Beste edozein POKéMON baino hobea!\p"
	.string "Horrelako harrokeriaz ari nintzen\n"
	.string "hizketan PRESIDENTEAK izugarrizko\l"
	.string "bronka bota arte.\p"
	.string "Horrek harrokeria guztia kendu zidan.\p"
	.string "Nahi baduzu zure POKéMON bati\n"
	.string "HARROKERIA erasoa erakutsiko diot.$"

MoveTutor_Text_SwaggerDeclined:
	.string "Nola, ezetz? Ezin al duzu gauzen\n"
	.string "espiritua ulertu?$"

MoveTutor_Text_SwaggerWhichMon:
	.string "Ondo bada, zein POKéMONI\n"
	.string "erakutsiko diot HARROKERIA?$"

MoveTutor_Text_SwaggerTaught:
	.string "Hemendik aurrera nire POKéMONAK goraipatuko\n"
	.string "ditut, baina harrokeriarik gabe.$"

MoveTutor_Text_RolloutTeach:
	.string "Badakizu hemendik zuzen-zuzen\n"
	.string "jarraituz oso urrurtira\l"
	.string "iritsi zaitezkeela?\p"
	.string "Uste dut lurretik biraka ere\n"
	.string "egin nezakeela bidea.\p"
	.string "Zure POKéMONEK ere nahiko\n"
	.string "lukete biratu, zure ustez?\p"
	.string "Zure POKéMONetako bati JIRABIRA\n"
	.string "erasoa erakutsi diezaioket.$"

MoveTutor_Text_RolloutDeclined:
	.string "Ez izan lotsarik, aizu.\n"
	.string "Bira dezagun!$"

MoveTutor_Text_RolloutWhichMon:
	.string "Kar-kar, noski! Itzela litzateke\n"
	.string "POKéMONAK nire antza balu.$"

MoveTutor_Text_RolloutTaught:
	.string "Belarretan jira eta bira ibilita\n"
	.string "zoriontsu naiz. Bira dezagun!$"

MoveTutor_Text_FuryCutterTeach:
	.string "Eraso bat ezagutzen dut, jarraian\n"
	.string "erabiliz gero, are indartsuagoa.\p"
	.string "ZOMORRO motako erasoa da, zinez\n"
	.string "txundigarria.\p"
	.string "SUMIN EBAKIAK izena du.\n"
	.string "Nahi duzu POKéMON bati irakastea?$"

MoveTutor_Text_FuryCutterDeclined:
	.string "Ez gara oso antzekoak, beraz.$"

MoveTutor_Text_FuryCutterWhichMon:
	.string "Bai!\n"
	.string "Zein POKéMONI erakutsiko diot.$"

MoveTutor_Text_FuryCutterTaught:
	.string "Zirrara itzela sortzen dit jarraian\n"
	.string "kolpatuko duen edo ez ikusteak!$"

MoveTutor_MimicTeach:
	.string "Aizu, gazte!\p"
	.string "Ni ere gaztea naiz izatez, baina\n"
	.string "herri honetako jende zaharraren\l"
	.string "hitz egiteko forma mimetizatu dut.\p"
	.string "Zer diozu, gazte?\n"
	.string "MIMETIKO erasoa erakutsi diezaioket\l"
	.string "zure POKéMON bati. Nahi duzu?$"

MoveTutor_MimicDeclined:
	.string "Bah, aizu! Zure POKéMONEI\n"
	.string "MIMETIKOA soilik erakutsi nahi nien!$"

MoveTutor_Text_MimicWhichMon:
	.string "Baibai! Hala bedi!\n"
	.string "Erakutsi erasoa ikasiko\l"
	.string "duen POKéMONA.$"

MoveTutor_Text_MimicTaught:
	.string "MIMIKOA benetan eraso sakona da.\p"
	.string "Gai izango al zinateke nik bezain\n"
	.string "ondo egiteko…?$"

MoveTutor_Text_MetronomeTeach:
	.string "Era guztietako gauzak nahi ditut!\n"
	.string "Baina diru-laguntza agortu zait…\p"
	.string "Ez al litzateke zirraragarria\n"
	.string "hatz bat mugitu eta dirua sortuko\l"
	.string "lukeen aztikeria ezagutzea?\p"
	.string "Nahi baduzu, zure POKéMON bati\n"
	.string "METRONOMOA erasoa erakutsiko diot.\p"
	.string "Dirua ez da agertuko, baina zure\n"
	.string "POKéMONAK hatz bat mugituko du, bai?$"

MoveTutor_Text_MetronomeDeclined:
	.string "Ongi. Hemen egongo naiz iritzia\n"
	.string "aldatzen baduzu.$"

MoveTutor_Text_MetronomeWhichMon:
	.string "Ongi! Prest nago!\n"
	.string "Zein POKéMONI erakutsiko diot?$"

MoveTutor_Text_MetronomeTaught:
	.string "POKéMON batek hatza METRONOMO\n"
	.string "baten antzera mugitzean era askotako\l"
	.string "gauzak gertatzen dira.\p"
	.string "Guk erabili ahal izatea ere\n"
	.string "bikaina litzateke, baietz?$"

MoveTutor_Text_SleepTalkTeach:
	.string "Humph! Nire emazteak BOTERE\n"
	.string "EZKUTUA behar du esna egoteko.\p"
	.string "NIk bezala siesta egin behar luke,\n"
	.string "eta SOMNANBULU ibili.\p"
	.string "Zure POKéMONEI erakuts diezaieket\n"
	.string "nola erabili SOMNANBULUA. Nahi duzu?$"

MoveTutor_Text_SleepTalkDeclined:
	.string "Oh, ongi, ongi. Zuk ere esna egon\n"
	.string "nahi duzu BOTERE EZKUTUAREKIN, beraz…$"

MoveTutor_Text_SleepTalkWhichMon:
	.string "Gazte adeitsua zara, bai!\n"
	.string "Zein POKéMONI erakutsiko diot?$"

MoveTutor_Text_SleepTalkTaught:
	.string "Nire emazteak txanponekin egiten\n"
	.string "duen trukua ezin dut egin.\p"
	.string "Gustatuko litzaidake ondo egitea,\n"
	.string "nahiz eta SOMNANBULU gisan izan…$"

MoveTutor_Text_SubstituteTeach:
	.string "Hemen teilatu gainetik mundu zabala\n"
	.string "ikusten dudanean…\p"
	.string "Burura etortzen zait gorputz bakarra\n"
	.string "baino gehiago izan nahi nituzkeela,\l"
	.string "bizitza desberdinak bizitzeko.\p"
	.string "Hori ez da posible, noski.\n"
	.string "Jiji\p"
	.string "Badakit! Nahi duzu POKéMON bati\n"
	.string "ORDEZKOA erasoa erakustea?$"

MoveTutor_Text_SubstituteDeclined:
	.string "Ez, e?\p"
	.string "Jakizu bada POKéMONAK bere kopia\n"
	.string "sortu dezakeela erasoarekin.$"

MoveTutor_Text_SubstituteWhichMon:
	.string "Jiji…\n"
	.string "Zein POKéMONI erakutsiko diot\l"
	.string "ORDEZKOA?$"

MoveTutor_Text_SubstituteTaught:
	.string "Gizakiok gure bizitzak topera\n"
	.string "bizi behar ditugu!\p"
	.string "Zuk ere hala biziko duzula espero dut!$"

MoveTutor_Text_DynamicPunchTeach:
	.string "Ezin dut gehiago!\p"
	.string "Esperantza galdu dut!\p"
	.string "BORROKA motako ENTRENATZAILEA naiz,\n"
	.string "eta ezin dut GOROLDIKO GIMNASIOA\l"
	.string "gainditu, gogoz saiatuta ere!\p"
	.string "Argh! Dinbi! Danba! Dinbi!\n"
	.string "Danba! Dinbi! Danba!\p"
	.string "Zer, ez begiratu horrela niri!\n"
	.string "Lurrari joka bakarrik nabil!\p"
	.string "Edo nahiago duzu zure POKéMON\n"
	.string "bati UKABIL DINAMIKOA erakustea?$"

MoveTutor_Text_DynamicPunchDeclined:
	.string "Kaka! Nitaz barrezka, ala?\n"
	.string "Dinbi! Danba! Dinbi!$"

MoveTutor_Text_DynamicPunchWhichMon:
	.string "Zer? Baietz? Zu bai pertsona ona!\n"
	.string "Zein POKéMONI erakutsiko diot?$"

MoveTutor_Text_DynamicPunchTaught:
	.string "Gainditu GOROLDIKO GIMNASIOA\n"
	.string "UKABIL DINAMIKOA erabiliz!$"

MoveTutor_Text_DoubleEdgeTeach:
	.string "Aiii…\p"
	.string "ARREZIPOLISEKO liderra benetan\n"
	.string "xarmanta eta miragarria da.\p"
	.string "Baina horrek esan nahi du gehiago\n"
	.string "dabiltzala nork eman atentzioa hari.\p"
	.string "AHO-BIKOITZEKO xarma du benetan.\n"
	.string "Ez dit kasurik ere egin.\p"
	.string "Mesedez, utzi zure POKéMON bati\n"
	.string "AHO-BIKOITZA erakusten!$"

MoveTutor_Text_DoubleEdgeDeclined:
	.string "Ene…\n"
	.string "Zuk ere ezezkoa?$"

MoveTutor_Text_DoubleEdgeWhichMon:
	.string "Ongi, zein POKéMONEK ikasiko du\n"
	.string "AHO-BIKOITZA?$"

MoveTutor_Text_DoubleEdgeTaught:
	.string "Maitasuna alde batera utziko dut!\n"
	.string "Indartsu bihurtuko naiz!$"

MoveTutor_Text_ExplosionTeach:
	.string "Ezin dut jarraitu herri txiki\n"
	.string "batean bizitzen.\p"
	.string "Ikusiko duzu, hirira joango naiz\n"
	.string "eta famatu bilakatuko naiz.\p"
	.string "Benetan, nire ospea EZTANDA batez\n"
	.string "lehertuko da, zin dagizut!\p"
	.string "Entzun badidazu, zure POKéMON\n"
	.string "bati EZTANDA erasoa erakusiko diot!$"

MoveTutor_Text_ExplosionDeclined:
	.string "Eeeez! Ezetz esan didazu ez\n"
	.string "naizelako hirian bizi, ezta?$"

MoveTutor_Text_ExplosionWhichMon:
	.string "Ondo! EZTANDA bat, beraz!\n"
	.string "Zein POKéMONEK nahi du lehertu?$"

MoveTutor_Text_ExplosionTaught:
	.string "Denbora luzean, POKéMONEI erakusi\n"
	.string "diet EZTANDA erabiltzen, baina\l"
	.string "nik oraindik ez dut EZTANDA egin…\p"
	.string "Izan daiteke, izatez, hemen\n"
	.string "bizitzen jarraitu nahi dudala…$"
