gText_ObtainedTheItem::
	.string "{STR_VAR_2} lortu duzu!$"

gText_TheBagIsFull::
	.string "POLTSA beteta dago…$"

gText_PutItemInPocket::
	.string "{PLAYER}(e)k {STR_VAR_2} gorde du\n"
	.string "{STR_VAR_3} POLTSIKOAN.$"

gText_PlayerFoundOneItem::
	.string "{PLAYER}(e)k {STR_VAR_2} aurkitu du!$"

gText_TooBadBagIsFull::
	.string "Pena!\n"
	.string "POLTSA beteta dago…$"

gText_PlayerPutItemInBag::
	.string "{PLAYER}(e)k {STR_VAR_2} POLTSAN\n"
	.string "gorde du.$"

gText_ObtainedTheDecor::
	.string "{STR_VAR_2} lortu duzu!$"

gText_NoRoomLeftForAnother::
	.string "Pena! Ez dago lekurik\n"
	.string "{STR_VAR_2} gordetzeko…$"

gText_TheDecorWasTransferredToThePC::
	.string "{STR_VAR_2} PCra bidali\n"
	.string "duzu.$"
