Text_BootUpPC:
	.string "{PLAYER}(e)k PCa piztu du.$"

gText_WhichPCShouldBeAccessed::
	.string "Zein PCtara sartu nahi duzu?$"

gText_AccessedSomeonesPC::
	.string "NORBAITen PCra sartu zara.$"

gText_StorageSystemOpened::
	.string "POKéMONak Gordetzeko Sistema irekita.$"

gText_AccessedPlayersPC::
	.string "{PLAYER}(r)en PCra sartu zara.$"

gText_AccessedLanettesPC::
	.string "LANETTEren PCra sartu zara.$"
