gText_PkmnTransferredSomeonesPC::
	.string "{STR_VAR_2} NORBAITEN PCra\n"
	.string "bidali da.\p"
	.string "“{STR_VAR_1}” KUTXAN\n"
	.string "gorde da$"

gText_PkmnTransferredLanettesPC::
	.string "{STR_VAR_2} LANETTEREN\n"
	.string "PCra bidali da.\p"
	.string "“{STR_VAR_1}” KUTXAN\n"
	.string "gorde da.”$"

gText_PkmnTransferredSomeonesPCBoxFull::
	.string "“{STR_VAR_3}” KUTXA\n"
	.string "beteta NORBAITEN PCan.\p"
	.string "{STR_VAR_2} “{STR_VAR_1}”\n"
	.string "KUTXARA bidali da.$"

gText_PkmnTransferredLanettesPCBoxFull::
	.string "“{STR_VAR_3}” KUTXA\n"
	.string "beteta LANETTEREN PCan.\p"
	.string "{STR_VAR_2} “{STR_VAR_1}”\n"
	.string "KUTXARA bidali da$"

gText_NoMoreRoomForPokemon::
	.string "Ez dago lekurik POKéMONENTZAT!\p"
	.string "POKéMON KUTXAK beteta daude\n"
	.string "eta ezin dira gehiago gorde!$"

gText_NicknameThisPokemon::
	.string "Nahi diozu ezizen bat eman\n"
	.string "{STR_VAR_1}(e)ri?$"
