gText_WouldYouLikeToRestYourPkmn::
	.string "Kaixo, ongi etorri\n"
	.string "POKéMON ZENTRORA.\p"
	.string "Zure POKéMON akituak\n"
	.string "sendatzen ditugu hemen.\p"
	.string "Nahi duzu zure POKéMONak sendatzea?$"

gText_IllTakeYourPkmn::
	.string "Ederki, utzi zure POKéMONak \n"
	.string "pixka batean.$"

gText_RestoredPkmnToFullHealth::
	.string "Eskerrik asko itxaroteagatik.\p"
	.string "Guztiz sendatu ditugu zure\n"
	.string "POKéMONak.$"

gText_WeHopeToSeeYouAgain::
	.string "Bueltatu nahi duzunean!$"

gText_WelcomeCutShort::
	.string "Kaixo, eta ongi etorri\n"
	.string "POKéMON ZENTRORA.\p"
	.string "Zure POKéMON akituak\n"
	.string "sendatzen ditugu hemen.\p"
	.string "Nahi duzu…$"

gText_NoticesGoldCard::
	.string "Tx-txartel hori…\n"
	.string "Ez da ba izango… URREZKO TXARTELA?!\p"
	.string "Zein urre kolore bizia!\n"
	.string "Lau izarrak dizdizka ditu, gainera!\p"
	.string "Hainbat ENTRENATZAILE ezagutu\n"
	.string "ditut ZILARREZKO TXARTELA zutenak,\l"
	.string "baina, {PLAYER}, zu zara URREZKOA\l"
	.string "erakutsi didan lehenengoa!\p"
	.string "Ongi, {PLAYER}, egin iezadazu\n"
	.string "zure POKéMONak sendatzeko ohorea!$"

gText_YouWantTheUsual::
	.string "Asko pozten naiz zu ikusteaz, {PLAYER}!\n"
	.string "Betiko nahi duzu, ezta?$"

gText_IllTakeYourPkmn2::
	.string "Ederki, utzi zure POKéMONak\n"
	.string "pixka batean.$"

gText_ThankYouForWaiting::
	.string "Eskerrik asko itxaroteagatik.$"

gText_WeHopeToSeeYouAgain2::
	.string "Bueltatu nahi duzunean!$"
