gBirchDexRatingText_AreYouCurious::
	.string "URKI MAIS.: Ah, {PLAYER}{KUN}!\p"
	.string "Jakin nahi al duzu zure\n"
	.string "POKéDEXA nola doan?$"

gBirchDexRatingText_Cancel::
	.string "Hm? Oh, oraindik ez duzu nahikoa\n"
	.string "POKéMON harrapatu.$"

gBirchDexRatingText_SoYouveSeenAndCaught::
	.string "Hmhm…\p"
	.string "Beraz, {STR_VAR_1} POKéMON ikusi dituzu\n"
	.string "eta {STR_VAR_2} POKéMON harrapatu…$"

gBirchDexRatingText_LessThan10::
	.string "Belarra dagoen lekuetara joan zaitez\n"
	.string "eta bilatu POKéMONak adi-adi.$"

gBirchDexRatingText_LessThan20::
	.string "Ematen du ari zarela honi tankera hartzen.\n"
	.string "Hemendik aurrera zailagoa izango da.$"

gBirchDexRatingText_LessThan30::
	.string "Kontuan izan POKéMON batzuk gune\n"
	.string "batzuetan soilik agertzen direla.\l"
	.string "Ekina izan behar duzu.$"

gBirchDexRatingText_LessThan40::
	.string "Beno, oraindik pixka bat falta da\n"
	.string "betetzeko, baina POKéDEX hau itxura ona\l"
	.string "hartzen ari da.$"

gBirchDexRatingText_LessThan50::
	.string "Itxura ona ari da hartzen proiektu hau.\n"
	.string "Segi ahal bezainbeste saiatzen.$"

gBirchDexRatingText_LessThan60::
	.string "Erabiltzen al duzu KAINABERARIK?\n"
	.string "Itsasoan POKéMON asko daude.$"

gBirchDexRatingText_LessThan70::
	.string "POKéMONak harrapatu soilik egin beharean,\n"
	.string "zergatik ez zara saiatzen eboluzionatzen?$"

gBirchDexRatingText_LessThan80::
	.string "POKéDEX hau izugarria izango\n"
	.string "dela uste dut.\l"
	.string "Sentsatzio hori daukat.$"

gBirchDexRatingText_LessThan90::
	.string "Zenbat harrapatu dituzun jada…\n"
	.string "Talentu izugarria duzu!$"

gBirchDexRatingText_LessThan100::
	.string "Izan al zara SAFARI GUNEAN?\p"
	.string "Entzun dudanez, POKéMON batzuk bertan\n"
	.string "bakarrik harrapatu omen daitezke.$"

gBirchDexRatingText_LessThan110::
	.string "Azkenean lortu duzu 100 motatako\n"
	.string "POKéMONak aurkitzea.\p"
	.string "POKéDEX harrigarria daukazu!$"

gBirchDexRatingText_LessThan120::
	.string "Entzun dudanez, POKéMON batzuk aurkitu\n"
	.string "daitezke ARROKA KOLPEA erabiltzen baduzu.$"

gBirchDexRatingText_LessThan130::
	.string "POKéMON gehiago lortu ditzakezu\n"
	.string "beste batzuekin trukatuz.$"

gBirchDexRatingText_LessThan140::
	.string "Entzun dudanaren arabera, badaude POKéMONak\n"
	.string "beraien ENTRENATZAILEA guztiz maite dutenean\l"
	.string "eboluzionatzen direnak.$"

gBirchDexRatingText_LessThan150::
	.string "Ez nekien hainbeste POKéMON espezie\n"
	.string "zegoenik HOENN bezalako eskualde\l"
	.string "batean.$"

gBirchDexRatingText_LessThan160::
	.string "Batzuetan, POKéMON asko agertzen dira\n"
	.string "batera, eztanda bat balitz bezala.\p"
	.string "Horrelakoetan, ez galdu bertaratzeko\n"
	.string "aukera.$"

gBirchDexRatingText_LessThan170::
	.string "Norbaitek zure POKéDEXARI begiratua\n"
	.string "emango balio, HOENN eskualdeko POKÉMONEN\l"
	.string "jakintza handia jasoko luke.$"

gBirchDexRatingText_LessThan180::
	.string "Nire ustez, POKéMON MAISUA zara\n"
	.string "jada, eta ez edonolako MAISUA,\l"
	.string "gainera!$"

gBirchDexRatingText_LessThan190::
	.string "Horren beteta dagoen POKéDEX batekin,\n"
	.string "profesional galanta zara zu!$"

gBirchDexRatingText_LessThan200::
	.string "POKéDEXA amaitzetik oso hurbil\n"
	.string "zaude, alajaina.\l"
	.string "Barruan sentitu dezaket!$"

gBirchDexRatingText_DexCompleted::
	.string "Zorionak!\n"
	.string "Zure POKéDEXA beteta dago!$"

gBirchDexRatingText_OnANationwideBasis::
	.string "Hmhm…\n"
	.string "Maila nazionalean…\p"
	.string "{STR_VAR_1} POKéMON ikusi dituzu,\n"
	.string "{STR_VAR_2} POKéMON harrapatu…$"
