Questionnaire_Text_FillOut::
	.string "Galdetegi bat da.\n"
	.string "Bete nahi al duzu?$"

Questionnaire_Text_ThankYou::
	.string "Eskerrik asko gure galdetegia\n"
	.string "betetzeko denbora hartzeagatik.\p"
	.string "Zure erantzunak oso baliagarriak\n"
	.string "izango dira etorkizunerako.$"

Questionnaire_Text_YouKnowThoseWordsGift::
	.string "Kaixo!\n"
	.string "Ezagutzen dituzu hitz horiek?\p"
	.string "Horrek esan nahi du badakizula zerbait\n"
	.string "OPARI MISTERIOTSUAREN inguruan.\p"
	.string "Hemendik aurrera OPARI MISTERIOTSUAK\n"
	.string "jasotzeko gai izango zara!$"

Questionnaire_Text_YouCanAccessMysteryGift::
	.string "Partida gordetzen duzunean, OPARI\n"
	.string "MISTERIOTSUA ikusi ahal izango duzu.$"

Questionnaire_Text_YouKnowThoseWordsEvent::
	.string "Kaixo!\n"
	.string "Ezagutzen dituzu hitz horiek?\p"
	.string "Horrek esan nahi du badakizula zerbait\n"
	.string "GERTAERA MISTERIOTSUAREN inguruan.$"

Questionnaire_Text_YouCanAccessMysteryEvent::
	.string "Partida gordetzen duzunean, GERTAERA\n"
	.string "MISTERIOTSUA ikusi ahal izango duzu.$"

MysteryGift_Text_TheresATicketForYou::
	.string "Eskerrik asko GERTAERA MISTERIOTSUAREN\n"
	.string "Zerbitzua erabiltzeagatik.\p"
	.string "{PLAYER} zara zu, ezta?\n"
	.string "Hemen tiket bat dago zuretzat.$"

MysteryGift_Text_TryUsingItAtLilycovePort::
	.string "Badirudi UR-LILI hiriko\n"
	.string "portuan erabiltzeko dela.\p"
	.string "Zergatik ez zara bertara joaten\n"
	.string "probatzera?$"
