	.align 2
gText_ConfirmSave::
	.string "Partida gorde nahi al duzu?$"

gText_AlreadySavedFile::
	.string "Jada badago gordetako partida bat.\n"
	.string "Gainidatzi nahi al duzu?$"

gText_SavingDontTurnOff::
	.string "GORDETZEN…\n"
	.string "EZ ITZALI.$"

gText_PlayerSavedGame::
	.string "{PLAYER}(e)k partida gorde du.$"

gText_DifferentSaveFile::
	.string "KONTUZ!\p"
	.string "Aurretik gordetako beste\n"
	.string "partida bat dago.\p"
	.string "Orain gordez gero, beste partidako\n"
	.string "abentura, itemak eta POKéMONAK\l"
	.string "barne, galdu egingo dira.\p"
	.string "Seguru zaude orain gorde eta\n"
	.string "beste aprtida gainidatzi nahi duzula?$"

gText_SaveError::
	.string "Errorea gordetzean.\p"
	.string "Mesedez aldatu\n"
	.string "segurtasun-kopiaren memoria.$"

gText_SavingDontTurnOffPower::
	.string "GORDETZEN…\n"
	.string "EZ ITZALI.$"
