SecretBase_Text_Trainer0Intro:
	.string "Egin al duzu jada BASE SEKRETURIK?\p"
	.string "Ni leku bila ibili naiz toki guztietan\n"
	.string "leku hau aukeratu aurretik.\p"
	.string "Aizu, hemen zaudenez, nahi al\n"
	.string "duzu borrokatu?$"

SecretBase_Text_Trainer0AcceptBattle:
	.string "Ongi!\n"
	.string "Goazen, ba!$"

SecretBase_Text_Trainer0DeclineBattle:
	.string "Zer?\n"
	.string "Ah, ezin duzu orain…$"

SecretBase_Text_Trainer0Defeated::
	.string "Aaarg! Indartsuegia zara!\n"
	.string "Mesedez… Ez esan inori galdu egin dudala!$"

SecretBase_Text_Trainer0PostBattle:
	.string "Zer iruditzen zaizu nire BASE SEKRETUA?\n"
	.string "Etorri bihar bisitan.$"

SecretBase_Text_Trainer0PreChampion:
	.string "Egin al duzu jada BASE SEKRETURIK?\p"
	.string "Ni leku bila ibili naiz toki guztietan\n"
	.string "leku hau aukeratu aurretik.\p"
	.string "Nahi duzun denbora guztia geratu!$"

SecretBase_Text_Trainer5Intro:
	.string "BASE SEKRETUA egiteko pila bat\n"
	.string "leku desberdin daude.\p"
	.string "Niri hau gustatzen zait gehien, baina.\n"
	.string "Ez al da leku atsegina?\p"
	.string "Aizu, borrokatu nahi al duzu?$"

SecretBase_Text_Trainer5AcceptBattle:
	.string "Ongi, banoa bada!$"

SecretBase_Text_Trainer5DeclineBattle:
	.string "Oh…\n"
	.string "Ezin duzu orain, ados.$"

SecretBase_Text_Trainer5Defeated::
	.string "Hmmm… Galdu egin dugu…\n"
	.string "Baina ez zabaldu hau!\l"
	.string "Sekretua da!$"

SecretBase_Text_Trainer5PostBattle:
	.string "Hemen inguruan bazabiltza,\n"
	.string "etorri bisitan, mesedez.$"

SecretBase_Text_Trainer5PreChampion:
	.string "BASE SEKRETUA egiteko pila bat\n"
	.string "leku desberdin daude.\p"
	.string "Niri hau gustatzen zait gehien, baina.\n"
	.string "Ez al da leku atsegina?$"

SecretBase_Text_Trainer1Intro:
	.string "Hau oso leku ezaguna da.\n"
	.string "Beti hartuta dago.\p"
	.string "Ene, zu ere leku honen\n"
	.string "bila etorri al zara?\p"
	.string "Begira, irabazten baldin badidazu\n"
	.string "leku hau erabili dezakezu.$"

SecretBase_Text_Trainer1AcceptBattle:
	.string "Ongi!\n"
	.string "Nire BASE SEKRETUA defendatuko dut!$"

SecretBase_Text_Trainer1DeclineBattle:
	.string "Zer? Ondo ulertu al dizut?\n"
	.string "Ez zaizu leku hau interesatzen?$"

SecretBase_Text_Trainer1Defeated::
	.string "Ezin dut gehiago!\n"
	.string "Errenditu egin naiz!$"

SecretBase_Text_Trainer1PostBattle:
	.string "Ongi, noizbait norabait banoa,\n"
	.string "leku hau zuretzat izango da!$"

SecretBase_Text_Trainer1PreChampion:
	.string "Hau oso leku ezaguna da.\n"
	.string "Beti hartuta dago.\p"
	.string "Denbora asko itxaron dut ireki arte.\n"
	.string "Erabili dezaket azkenean!$"

SecretBase_Text_Trainer6Intro:
	.string "Ongi etorri nire POKéMON LABORATEGIRA.\p"
	.string "Hemen sekretupean ikertu dezaket\n"
	.string "borroken inguruan.\p"
	.string "Ikusi nahi al duzu nire indarra?$"

SecretBase_Text_Trainer6AcceptBattle:
	.string "Indar guztiekin borrokatuko dut!$"

SecretBase_Text_Trainer6DeclineBattle:
	.string "Ados.\n"
	.string "Beste batean, orduan!$"

SecretBase_Text_Trainer6Defeated::
	.string "Hmm… Asko dut ikasteko oraindik.\n"
	.string "Gehiago aztertu behar dut dena.$"

SecretBase_Text_Trainer6PostBattle:
	.string "Eskerrik asko nirekin borrokatzeagatik.\n"
	.string "Mesedez, itzuli bihar.$"

SecretBase_Text_Trainer6PreChampion:
	.string "Ongi etorri nire POKéMON LABORATEGIRA.\p"
	.string "Hemen sekretupean ikertu dezaket\n"
	.string "borroken inguruan.$"

SecretBase_Text_Trainer2Intro:
	.string "Luxuzko etxeak ederrak dira, baina\n"
	.string "nik nahiago dut leku hau.\p"
	.string "Asko atsegin dut, era guztietako\n"
	.string "jendea datorkidalako bisitan.\p"
	.string "Nahi al duzu borrokan egin?$"

SecretBase_Text_Trainer2AcceptBattle:
	.string "Hori da hitza!$"

SecretBase_Text_Trainer2DeclineBattle:
	.string "Prest zaudenean, abisatu!$"

SecretBase_Text_Trainer2Defeated::
	.string "Ene! Galdu egin dut!\n"
	.string "Hala ere, borrokatzea atsegin dut!$"

SecretBase_Text_Trainer2PostBattle:
	.string "Bueno, apaingarri eta altzari batzuk\n"
	.string "erostera joan behar nuke.\p"
	.string "Nire BASE SEKRETUA edozeinek ondo\n"
	.string "pasatzeko lekua izatea nahi dut.$"

SecretBase_Text_Trainer2PreChampion:
	.string "Luxuzko etxeak ederrak dira, baina\n"
	.string "nik nahiago dut leku hau.\p"
	.string "Asko atsegin dut, era guztietako\n"
	.string "jendea datorkidalako bisitan.$"

SecretBase_Text_Trainer7Intro:
	.string "Izugarri gustatzen zait apaingarri\n"
	.string "eta altzariak erostea.\p"
	.string "POKéMONAK haztea ere izugarri\n"
	.string "gustatzen zait.\p"
	.string "Inporta ez badizu, egingo zenuke\n"
	.string "borroka nire POKéMONEN aurka?$"

SecretBase_Text_Trainer7AcceptBattle:
	.string "Eskerrik asko.\n"
	.string "Hasiko gara?$"

SecretBase_Text_Trainer7DeclineBattle:
	.string "Ene.\n"
	.string "Hau bai etsigarria…$"

SecretBase_Text_Trainer7Defeated::
	.string "Errenditu egin naiz…$"

SecretBase_Text_Trainer7PostBattle:
	.string "Zeinen ongi pasatu dudan!\n"
	.string "Orain erosketak egitera joango naiz.$"

SecretBase_Text_Trainer7PreChampion:
	.string "Izugarri gustatzen zait apaingarri\n"
	.string "eta altzariak erostea.\p"
	.string "POKéMONAK haztea ere izugarri\n"
	.string "gustatzen zait.$"

SecretBase_Text_Trainer3Intro:
	.string "Batzuek BASE SEKRETUA oso leku\n"
	.string "ezkutuetan eraikitzen dituzte.\l"
	.string "Bakar-bakarrik egon nahi ote dute?\p"
	.string "Zuk ni aurkitu nauzunez, nahi\n"
	.string "al duzu borrokatu?$"

SecretBase_Text_Trainer3AcceptBattle:
	.string "Ez da erraza izango ni garaitzea!$"

SecretBase_Text_Trainer3DeclineBattle:
	.string "Ene… Nekatuta al zaude leku honen\n"
	.string "bila egoteagatik, ala?$"

SecretBase_Text_Trainer3Defeated::
	.string "Galdu egin dut…$"

SecretBase_Text_Trainer3PostBattle:
	.string "Non dago zure BASE SEKRETUA?\n"
	.string "Bisitan joan behar nintzateke.$"

SecretBase_Text_Trainer3PreChampion:
	.string "Batzuek BASE SEKRETUA oso leku\n"
	.string "ezkutuetan eraikitzen dituzte.\l"
	.string "Bakar-bakarrik egon nahi ote dute?$"

SecretBase_Text_Trainer8Intro:
	.string "lagunek esan didate apaingarriak\n"
	.string "lortzeko era desberdinak daudela.\p"
	.string "Apustua egin behar genuke, ea nork\n"
	.string "lortu apaingarri eta altzairu politenak!\p"
	.string "Bitartean, borrokatu nahi?$"

SecretBase_Text_Trainer8AcceptBattle:
	.string "Hau nire BASE SEKRETUA da.\n"
	.string "Ezin dut galdu!$"

SecretBase_Text_Trainer8DeclineBattle:
	.string "Zurekin borrokatuko dut nahi duzunean.$"

SecretBase_Text_Trainer8Defeated::
	.string "Nola?\n"
	.string "Galdu egin al dut?$"

SecretBase_Text_Trainer8PostBattle:
	.string "Apaingarriak biltzen ez dut galduko.\n"
	.string "Etorri nahi duzunean!$"

SecretBase_Text_Trainer8PreChampion:
	.string "lagunek esan didate apaingarriak\n"
	.string "lortzeko era desberdinak daudela.\p"
	.string "Apustua egin behar genuke, ea nork\n"
	.string "lortu apaingarri eta altzairu politenak!$"

SecretBase_Text_Trainer4Intro:
	.string "Leku atsegin bat aurkitu nuen eta\n"
	.string "nire apaingarri gustokoenekin bete.\p"
	.string "Nire POKéMON gogokoenak hazten ditut\n"
	.string "eta gero eta indartsuago bihurtu.\p"
	.string "Hori da egiten dudana.\n"
	.string "Borrokatu nahi al duzu nirekin?$"

SecretBase_Text_Trainer4AcceptBattle:
	.string "Erakutsi bada, zure indarra!$"

SecretBase_Text_Trainer4DeclineBattle:
	.string "Normala da batzuetan borrokatzeko\n"
	.string "gogorik ez izatea.$"

SecretBase_Text_Trainer4Defeated::
	.string "Garbi erakutsi didazu zure indarra, bai.$"

SecretBase_Text_Trainer4PostBattle:
	.string "Biok indartsuagoak izan gaitezke.\n"
	.string "Segi dezagun lanean!$"

SecretBase_Text_Trainer4PreChampion:
	.string "Leku atsegin bat aurkitu nuen eta\n"
	.string "nire apaingarri gustokoenekin bete.\p"
	.string "Nire POKéMON gogokoenak hazten ditut\n"
	.string "eta gero eta indartsuago bihurtu.\p"
	.string "Pozik nago egunero horrela.$"

SecretBase_Text_Trainer9Intro:
	.string "Asko ikasi daiteke jendearen gainean\n"
	.string "erabiltzen dituzten apaingarrien\l"
	.string "arabera, eta hauek jartzeko duten\l"
	.string "eraren arabera.\p"
	.string "Zer iruditzen zaizu nire estiloa?\n"
	.string "Harri eta zur geratu zara, e?\p"
	.string "Nahi duzu nire borroka estiloa ezagutu?$"

SecretBase_Text_Trainer9AcceptBattle:
	.string "Indar osoz borrokatuko dut!$"

SecretBase_Text_Trainer9DeclineBattle:
	.string "Nahi duzunean erakutsiko dizut nire\n"
	.string "borroka estiloa.$"

SecretBase_Text_Trainer9Defeated::
	.string "Zu bai zu trebea!\n"
	.string "Zure indarrak amaigabea dirudi…$"

SecretBase_Text_Trainer9PostBattle:
	.string "Zer iruditu zaizu nire estiloa?\n"
	.string "Lantzen jarraituko dut!$"

SecretBase_Text_Trainer9PreChampion:
	.string "Asko ikasi daiteke jendearen gainean\n"
	.string "erabiltzen dituzten apaingarrien\l"
	.string "arabera, eta hauek jartzeko duten\l"
	.string "eraren arabera.\p"
	.string "Zer iruditzen zaizu nire estiloa?\n"
	.string "Harri eta zur geratu zara, e?$"
