ShoalCave_LowTideEntranceRoom_Text_AreYouPlanningOnGoingInThere:
	.string "Hor sakonera joateko asmotan\n"
	.string "al zabiltza?\p"
	.string "Ekarriko zenizkidake BANKU GATZA\n"
	.string "eta BANKU MASKORRAK?\p"
	.string "Osagai horiekin zerbait oso ona\n"
	.string "prestatu diezazuket.$"

ShoalCave_LowTideEntranceRoom_Text_BringMe4ShoalSaltAndShells:
	.string "Lau BANKU GATZ eta lau BANKU\n"
	.string "MASKOR ekartzen badizkidazu,\l"
	.string "MASKOR KANPAI bat egingo dizut…\p"
	.string "Egunero lor ditzakezu osagai\n"
	.string "horiek.$"

ShoalCave_LowTideEntranceRoom_Text_WouldYouLikeShellBell:
	.string "Aizu! BANKU GATZA eta BANKU MASKORRAK!\n"
	.string "Bakoitzetik nahikoa, gainera!\p"
	.string "Nahi al duzu MASKOR KANPAI bat\n"
	.string "egitea osagai hauekin?$"

ShoalCave_LowTideEntranceRoom_Text_MakeShellBellRightAway:
	.string "Ongi bada! Oraintxe egingo dut\n"
	.string "MASKOR KANPAI bat zuretzat.\p"
	.string "… … … … … … … …\n"
	.string "… … … … … … … …\p"
	.string "Hortxe! Eginda!$"

ShoalCave_LowTideEntranceRoom_Text_ExplainShellBell:
	.string "Eman KANPAIA POKéMON bati.\n"
	.string "Asko gustatuko zaio, ez egin dudarik.\p"
	.string "MASKOR KANPAIAREN hotsa…\n"
	.string "Zerutiarra da!\p"
	.string "Osagaiak egunero aurki ditzakezu,\n"
	.string "eta egingo dizkizut gehiago.$"

ShoalCave_LowTideEntranceRoom_Text_WantedToMakeShellBell:
	.string "Ene… Zergatik ez…\n"
	.string "MASKOR KANPAI bat egin nahi nuen…$"

ShoalCave_LowTideEntranceRoom_Text_NoSpaceInYourBag:
	.string "Ez duzu POLTSAN lekurik egingo\n"
	.string "dizudan KANPAIA gordetzeko.\p"
	.string "Hustu POLTSA pixka bat eta\n"
	.string "itzuli MASKOR KANPAIAREN bila.$"

ShoalCave_Text_WasShoalSaltNowNothing:
	.string "BANKU GATZ pixka bat zegoen hemen.\n"
	.string "Jada ez da ezer geratzen, baina.$"

ShoalCave_Text_WasShoallShellNowNothing:
	.string "BANKU MASKOR bat zegoen hemen.\n"
	.string "Jada ez da ezer geratzen, baina.$"
