Route102_Text_CalvinIntro:
	.string "POKéMONAK badauzkazu, ofizialki\n"
	.string "POKéMON ENTRENATZAILEA zara!\l"
	.string "Ezin diozu ezetz esan nire erronkari!$"

Route102_Text_CalvinDefeated:
	.string "Kaka, galdu egin dut…\n"
	.string "Gehiago entrenatu behar nuen…$"

Route102_Text_CalvinPostBattle:
	.string "Ei, aizu. Lehenago esan behar,\n"
	.string "zenidan indartsua zinela!$"

Route102_Text_CalvinRegister:
	.string "Gogor aritu lanean lehen ikusi\n"
	.string "zaitudanetik.\p"
	.string "Gustatuko litzaidake berriz borrokatzea,\n"
	.string "erregistratuko nauzu zure POKéNAVEAN?$"

Route102_Text_CalvinRegisterShort:
	.string "Gustatuko litzaidake berriz borrokatzea,\n"
	.string "erregistratuko nauzu zure POKéNAVEAN?$"

Route102_Text_CalvinRematchIntro:
	.string "Zure aurka galdu nuenetik, buru-belarri\n"
	.string "aritu naiz nire POKéMONAK entrenatzen.\l"
	.string "Ezin diozu ezetz esan nire erronkari!$"

Route102_Text_CalvinRematchDefeated:
	.string "Ene, galdu egin dut…\n"
	.string "Ez al dut era egokian entrenatzen?$"

Route102_Text_CalvinRematchPostBattle:
	.string "Indartsuago bihurtuko bazara,\n"
	.string "ni ere indartsuago bihurtuko naiz.$"

Route102_Text_AllenIntro:
	.string "ENTRENATZAILE bihurtu berri zara?\n"
	.string "Biok gara hasiberriak!$"

Route102_Text_AllenDefeated:
	.string "Zure aurka irabaziko nuela uste nuelako\n"
	.string "soilik deitu dizut…$"

Route102_Text_AllenPostBattle:
	.string "Ez dut behin ere irabazi…\n"
	.string "Ea laister irabazten dudan…$"

Route102_Text_RickIntro:
	.string "Kar-kar-kar! Begiratu egin didazu!\n"
	.string "Nire ZOMORRO POKéMONEKIN txikituko zaitut!$"

Route102_Text_RickDefeated:
	.string "Ai! Hori bai egurra!$"

Route102_Text_RickPostBattle:
	.string "ENTRENATZAILE bati begiratzen badiozu,\n"
	.string "erronka bota behar diozu! Araua da!$"

Route102_Text_TianaIntro:
	.string "Irabazi besterik ez dut egingo eta\n"
	.string "ENTRENATZAILE onena izango naiz.\p"
	.string "Lagundu nire bidea egiten!$"

Route102_Text_TianaDefeated:
	.string "Azkenean nik lagundu dizut zure bidean…$"

Route102_Text_TianaPostBattle:
	.string "Irabazten jarraitu nahi badut, POKéMON\n"
	.string "gehiago harrapatu behar ditut.$"

Route103_Text_DaisyIntro:
	.string "Gure lurrin gozoak erakarri al\n"
	.string "zaitu?$"

Route103_Text_DaisyDefeated:
	.string "Gure lurrin gozoak ez zaitu galdu…$"

Route103_Text_DaisyPostBattle:
	.string "Aromaterapia burua zaintzeko erabiltzen\n"
	.string "da lurrinak erabiliz.$"

Route103_Text_AmyIntro:
	.string "AMY: AMY naiz.\n"
	.string "Hau nire ahizpa txikia da, LIV.\l"
	.string "Batera egiten dugu borroka!$"

Route103_Text_AmyDefeated:
	.string "AMY: Ene bada, galdu egin dugu.$"

Route103_Text_AmyPostBattle:
	.string "AMY: Mila gauza eduki behar\n"
	.string "dituzu buruan bi ENTRENATZAILEREN\l"
	.string "kontra borrokatzerakoan.$"

Route103_Text_AmyNotEnoughPokemon:
	.string "AMY: Ene, POKéMON bakarra daukazu\n"
	.string "aldean orain.\l"
	.string "Horrela ezin duzu gurekin borrokatu.$"

Route103_Text_LivIntro:
	.string "LIV: Biok batera borrokatzen\n"
	.string "dugu, taldean.$"

Route103_Text_LivDefeated:
	.string "LIV: Ene, galdu egin dugu, ahizpa…$"

Route103_Text_LivPostBattle:
	.string "LIV: Bikain egiten dugu lan batera,\n"
	.string "nik eta nire ahizpak…\p"
	.string "Baina hala ere galdu egin dugu…$"

Route103_Text_AmyLivRegister:
	.string "LIV: Berez, askoz hobeak gara…\n"
	.string "Benetan! Ikusiko duzu hurrengoan!$"

Route103_Text_LivNotEnoughPokemon:
	.string "LIV: Gure aurka borrokatzekotan,\n"
	.string "bi POKéMON behar dituzu!\l"
	.string "Beztela ez da bidezko borroka izango!$"

Route103_Text_AmyRematchIntro:
	.string "AMY: AMY naiz.\n"
	.string "Hau nire ahizpa txikia da, LIV.\l"
	.string "Batera egiten dugu borroka!$"

Route103_Text_AmyRematchDefeated:
	.string "AMY: O, buuu!\n"
	.string "Ezin izan dugu irabazi…$"

Route103_Text_AmyRematchPostBattle:
	.string "AMY: Mila gauza eduki behar\n"
	.string "dituzu buruan bi ENTRENATZAILEREN\l"
	.string "kontra borrokatzerakoan.$"

Route103_Text_AmyRematchNotEnoughPokemon:
	.string "AMY: Ene, POKéMON bakarra daukazu\n"
	.string "aldean orain.\l"
	.string "Horrela ezin duzu gurekin borrokatu.$"

Route103_Text_LivRematchIntro:
	.string "LIV: Biok batera borrokatzen\n"
	.string "dugu, taldean.$"

Route103_Text_LivRematchDefeated:
	.string "LIV: Ene, berriz galdu dugu…\n"
	.string "Ahizpa…$"

Route103_Text_LivRematchPostBattle:
	.string "LIV: Bikain egiten dugu lan batera,\n"
	.string "nik eta nire ahizpak…\p"
	.string "Zergatik galdu dugu, orduan?$"

Route103_Text_LivRematchNotEnoughPokemon:
	.string "LIV: Gure aurka borrokatzekotan,\n"
	.string "bi POKéMON behar dituzu!\l"
	.string "Beztela ez da bidezko borroka izango!$"

Route103_Text_AndrewIntro:
	.string "Ez! Pita kiribilduta gelditu zait!\n"
	.string "Zapuztuta eta haserre nago!\l"
	.string "Hori da! Borrokatu nirekin!$"

Route103_Text_AndrewDefeated:
	.string "Ez! Galdu egin dut!\n"
	.string "Are amorratuago nago!$"

Route103_Text_AndrewPostBattle:
	.string "Kaka, oraindik amorratuta nago…\n"
	.string "Grrrrr…$"

Route103_Text_MiguelIntro:
	.string "Nire POKéMON zoragarria da!\n"
	.string "Ez lotsatu--Erakutsiko dizut!$"

Route103_Text_MiguelDefeated:
	.string "Ai ene, jainko maitea!\n"
	.string "Nire POKéMON maitea!$"

Route103_Text_MiguelPostBattle:
	.string "Nire POKéMON zoragarria polita\n"
	.string "da indargabetuta badago ere!$"

Route103_Text_MiguelRegister:
	.string "Nire POKéMON ederrak berriro\n"
	.string "ikus ditzazun lortuko dut!$"

Route103_Text_MiguelRematchIntro:
	.string "Ei, aizu! Nire POKéMON zoragarriak\n"
	.string "are ederragoak dira orain!$"

Route103_Text_MiguelRematchDefeated:
	.string "Ene!\n"
	.string "Nire POKéMON maitea!$"

Route103_Text_MiguelRematchPostBattle:
	.string "Zenbat eta denbora gehiago pasa berekin,\n"
	.string "nire POKéMONA are politagoa bihurtzen da.$"

Route103_Text_PeteIntro:
	.string "Distantzia hau…\n"
	.string "Igerian egin behar zenuke!$"

Route103_Text_PeteDefeated:
	.string "Ene, hori bai borroka bikaina!$"

Route103_Text_PetePostBattle:
	.string "Bai, orain ulertzen dut nondik\n"
	.string "zatozen.\p"
	.string "Horren POKéMON fidagarria banu, bere\n"
	.string "gainean SURF egingo nuke nik ere!$"

Route103_Text_IsabelleIntro:
	.string "Kontuz nondik zabiltzan!\n"
	.string "Talka egingo dugu bestela!$"

Route103_Text_IsabelleDefeated:
	.string "Kaka…$"

Route103_Text_IsabellePostBattle:
	.string "Txarra naiz igerian, praktikatzen nenbilen…\n"
	.string "Barkatu ia-ia zurekin talka egiteagatik.$"

Route103_Text_RhettIntro:
	.string "Uau!\n"
	.string "Nola sartu zara horren leku txikian?$"

Route103_Text_RhettDefeated:
	.string "Uau!\n"
	.string "Badakizu borrokan!$"

Route103_Text_RhettPostBattle:
	.string "Hau bezalako leku itxiak\n"
	.string "atsegin dituzu?$"

Route103_Text_MarcosIntro:
	.string "Nire gitarraren doinuak erakarri zaitu?$"

Route103_Text_MarcosDefeated:
	.string "Ezingo naiz orkestra-gizon izan…$"

Route103_Text_MarcosPostBattle:
	.string "Gitarra jotzen ari nintzen ia inor\n"
	.string "ez zegoen leku batean, baina jende\l"
	.string "pila bat elkartu da bat-batean.\p"
	.string "Heh, profesional egin beharko naiz.$"

Route104_Text_GinaIntro:
	.string "GINA: Ongi, borroka dezagun gure\n"
	.string "POKéMONEKIN!$"

Route104_Text_GinaDefeat:
	.string "GINA: Galtzeak amorratu egiten nau!$"

Route104_Text_GinaPostBattle:
	.string "GINA: Zu bai indartsua!\n"
	.string "Gehiago entrenatu behar dugu!$"

Route104_Text_GinaNotEnoughMons:
	.string "GINA: Zer? POKéMON bakarra?\n"
	.string "Orduan ez dugu zurekin borrokatuko.\p"
	.string "POKéMON bakarra badago, borroka\n"
	.string "bakartia izango da. Ez dut atsegin hori.$"

Route104_Text_MiaIntro:
	.string "MIA: Bikiak gara, beraz, elkarrekin\n"
	.string "egiten ditugu POKéMON borrokak.$"

Route104_Text_MiaDefeat:
	.string "MIA: Batera borrokatu dugu, baina\n"
	.string "biok galdu dugu hala ere…$"

Route104_Text_MiaPostBattle:
	.string "MIA: Gehiago entrenatuko ditugu gure\n"
	.string "POKéMONAK zu bezain indartsuak izateko.$"

Route104_Text_MiaNotEnoughMons:
	.string "MIA: Nahi duzu gurekin borrokatu?\p"
	.string "Ezin dizugu baietz esan POKéMON\n"
	.string "bakarra baldin badaukazu.\l"
	.string "Indartsuegiak gara zuretzat!$"

Route104_Text_IvanIntro:
	.string "Zergatik ezkutatu gehiago?\n"
	.string "UR POKéMONEN aditua naiz!\p"
	.string "Zer?\n"
	.string "Ez nauzula ezagutzen?$"

Route104_Text_IvanDefeat:
	.string "Uste nuen ez nintzela horren txarra,\n"
	.string "baina badirudi ez dela horrela…$"

Route104_Text_IvanPostBattle:
	.string "Gehiegi gustatzen zait arrantza.\n"
	.string "Nire POKéMONAK haztea ahaztu zait…$"

Route104_Text_BillyIntro:
	.string "Hondarretan oinatzak uztea oso\n"
	.string "dibertigarria da!$"

Route104_Text_BillyDefeat:
	.string "Ez! Hondarra sartu zait oinetakoetan!\n"
	.string "Azkura ematen didate!$"

Route104_Text_BillyPostBattle:
	.string "Nire oinatzak utzi nahi ditut\n"
	.string "hondarretan, baina desagertu\l"
	.string "egiten dira segituan…$"

Route104_Text_HaleyIntro:
	.string "Borrokatu behar nuke…\n"
	.string "Edo ez?\p"
	.string "Beno, bai, borroka dezagun!$"

Route104_Text_HaleyDefeat:
	.string "Ez nuen borrokatu behar…$"

Route104_Text_HaleyPostBattle:
	.string "Erabaki bat hartu behar baduzu\n"
	.string "eta beste norbaiti uzten badiozu\l"
	.string "hartzen, ez zara gustora geratuko,\l"
	.string "gertatzen dena gertatzen dela.$"

Route104_Text_HaleyRegister1:
	.string "Indartsua zara, nire POKéNAVEAN\n"
	.string "erregistratu behar zintuzket?\l"
	.string "Agian ez…\p"
	.string "Beno, bai, erregistratuko zaitut!$"

Route104_Text_HaleyRegister2:
	.string "Indartsua zara, nire POKéNAVEAN\n"
	.string "erregistratu behar zintuzket?\l"
	.string "Agian ez…\p"
	.string "Beno, bai, erregistratuko zaitut!$"

Route104_Text_HaleyRematchIntro:
	.string "Aizu, borrokatu nirekin!$"

Route104_Text_HaleyRematchDefeat:
	.string "Ene…\n"
	.string "Irabazi nezakeela uste nuen…$"

Route104_Text_HaleyPostRematch:
	.string "Nik hartu dut borrokatzeko erabakia,\n"
	.string "Erraz onartu dezaket galdu izana.\p"
	.string "Baina oraindik amorru apur bat ematen dit!$"

Route104_Text_WinstonIntro:
	.string "bai, noski, onartuko dut zure erronka.\n"
	.string "Diru asko daukat.$"

Route104_Text_WinstonDefeat:
	.string "Zergatik ez ote dut irabazi?$"

Route104_Text_WinstonPostBattle:
	.string "Guztia ezin da diruarekin erosi.\n"
	.string "POKéMONAK adibidez…$"

Route104_Text_WinstonRegister1:
	.string "Zer?\n"
	.string "Ah, POKéNAV bat lortu duzula.\p"
	.string "gustura erregistratuko zaitut.\n"
	.string "Azken finean, diru pila bat dut.$"

Route104_Text_WinstonRegister2:
	.string "Zer?\n"
	.string "Ah, POKéNAV bat lortu duzula.\p"
	.string "gustura erregistratuko zaitut.\n"
	.string "Azken finean, diru pila bat dut.$"

Route104_Text_WinstonRematchIntro:
	.string "Zure aurka galdu ostean, gauza asko\n"
	.string "ikasi nuen POKéMONEN inguruan.$"

Route104_Text_WinstonRematchDefeat:
	.string "Berriz galdu dut?\n"
	.string "Zergatik ezin dut irabazi?$"

Route104_Text_WinstonPostRematch:
	.string "Izugarri aberatsa naiz, baina ezin\n"
	.string "dut irabazi POKéMONEKIN…\p"
	.string "Zein sakona den POKéMONEN mundua…$"

Route104_Text_CindyIntro:
	.string "Patuak elkartu gaitu.\n"
	.string "Eskatu diezazuket nirekin borrokatzeko?$"

Route104_Text_CindyDefeat:
	.string "Ai, ene!$"

Route104_Text_CindyPostBattle:
	.string "Kaixo” bat “agur” baten hasiera da\n"
	.string "Berriz elkartuko garela espero dut.$"

Route104_Text_CindyRegister1:
	.string "Kaixo, elkartu gara berriz.\p"
	.string "Patua izango zen ziur. Erregistratu\n"
	.string "gaitezen elkarren POKéNAVETAN.$"

Route104_Text_CindyRegister2:
	.string "Ospatu egin behar genuke etengabe\n"
	.string "elkartzen gaituela patuak.\p"
	.string "Erregistratu dezagun elkar\n"
	.string "gure POKéNAVETAN.$"

Route104_Text_CindyRematchIntro:
	.string "kaixo, elkartu gara berriz\n"
	.string "Eskatu diezazuket nirekin borrokatzeko?$"

Route104_Text_CindyRematchDefeat:
	.string "Ai, ene…\n"
	.string "Izugarri saiatu naiz, baina…$"

Route104_Text_CindyPostRematch:
	.string "Kaixo” bat “agur” baten hasiera da\n"
	.string "Berriz elkartuko garela espero dut.$"

Route104_Text_DarianIntro:
	.string "Gogorra dirudien POKéMONA arrantzatu dut!\p"
	.string "Zerbait magikoa du, esango nuke!\n"
	.string "Oso gogorra ematen du, bai jauna!$"

Route104_Text_DarianDefeat:
	.string "Baina, baina…$"

Route104_Text_DarianPostBattle:
	.string "Aizu, MAGIKARP, ez zara dirudien\n"
	.string "bezain indartsua, ezta?$"

Route105_Text_FosterIntro:
	.string "Arroka mistiko bat omen dago\n"
	.string "hemen inguruan.\l"
	.string "Ba al dakizu zeozer zuk?$"

Route105_Text_FosterDefeated:
	.string "Arrokan pentsatu eta pentsatu aritu\n"
	.string "naiz, nire POKéMONAK ahuldu bitartean…$"

Route105_Text_FosterPostBattle:
	.string "Orduak egon naiteke arroka polit\n"
	.string "bati begira, batere aspertu gabe.$"

Route105_Text_LuisIntro:
	.string "Eskerrak! uste nuen ume bat itotzen\n"
	.string "ari zela ikusi zaitudanean.\p"
	.string "Baina ondo zaudela dirudi, nahi al\n"
	.string "duzu borrokatu?$"

Route105_Text_LuisDefeated:
	.string "Glub… Glub…$"

Route105_Text_LuisPostBattle:
	.string "Itotzen ari bazara, beso bat\n"
	.string "astindu hondartzara begira.$"

Route105_Text_DominikIntro:
	.string "Itsaso urdin sakonean igeri egitea…\n"
	.string "Hori bai sentsazio ederra!$"

Route105_Text_DominikDefeated:
	.string "Galdu egin dut…\n"
	.string "Orain goibeldu egin naiz…$"

Route105_Text_DominikPostBattle:
	.string "Zergatik da itsasoa urdina?\p"
	.string "PORTUONDOKO MUSEOAN ikasi nuen,\n"
	.string "baina ahaztu egin zait.$"

Route105_Text_BeverlyIntro:
	.string "Nire gorputza arinagoa da uretan.\n"
	.string "Argaldu banintz bezala da!$"

Route105_Text_BeverlyDefeated:
	.string "Flotatzen ari naiz…$"

Route105_Text_PostBattle:
	.string "Zure gorputzaren pisua hamar aldiz\n"
	.string "txikitzen omen da uretan.\p"
	.string "orduan, nire kasuan…\n"
	.string "Ene! Ez dizut nire pisua esango!$"

Route105_Text_ImaniIntro:
	.string "Zeru urdin urdina…\n"
	.string "Itsaso zabala…\l"
	.string "Horren lasaigarria da…$"

Route105_Text_ImaniDefeated:
	.string "Alferkerian nengoelako galdu dut!$"

Route105_Text_ImaniPostBattle:
	.string "Jendeak pertsona erlaxagarria naizela\n"
	.string "esatea nahi dut. Jiji.$"

Route105_Text_AndresIntro:
	.string "Ziur nago itsasoak sekretuak\n"
	.string "gordetzen dizkigula.$"

Route105_Text_AndresDefeated:
	.string "Bai…\n"
	.string "Ez naiz oso ona borrokan…$"

Route105_Text_AndresPostBattle:
	.string "Munduko itsasoetan zehar sekretu pila\n"
	.string "bat dago nor aurkitu zain, ziur nago.\p"
	.string "Nik guztiak aurkituko ditut!$"

Route105_Text_AndresRegister:
	.string "Nola? Ahula izanda ere zure\n"
	.string "POKéNAVEAN erregistratuko nauzu?$"

Route105_Text_AndresRematchIntro:
	.string "Esan dizut ahula naizela…\n"
	.string "Ziur zaude hau egin nahi duzula?$"

Route105_Text_AndresRematchDefeated:
	.string "Bai…\n"
	.string "Ez nuen uste irabazi nezakeenik.$"

Route105_Text_AndresRematchPostBattle:
	.string "Ahula naiz borroketan, baina ezin da\n"
	.string "gainditu esploratzeko dudan indarra.\p"
	.string "Mundu osoko itsasoetan barrena\n"
	.string "ibiliko naiz!$"

Route105_Text_JosueIntro:
	.string "Igeriketak akitu egin nau.\n"
	.string "Ez nago ohituta eta.\p"
	.string "Alda dezagun erritmoa borroka batekin!$"

Route105_Text_JosueDefeated:
	.string "Itsasoan borrokatzeagatik galdu dut.$"

Route105_Text_JosuePostBattle:
	.string "Bai, niretzat askoz hobea da zerua\n"
	.string "itsasoa baino.$"

Route106_Text_ElliotIntro:
	.string "Zer duzu nahiago itsasoan arrantzatu\n"
	.string "edo errekan arrantzatu?$"

Route106_Text_ElliotDefeated:
	.string "Itsasoko arrantzan bezala, hemen ere\n"
	.string "kale egin dut bada!$"

Route106_Text_ElliotPostBattle:
	.string "Arrantza itzela da, berdin dio\n"
	.string "itsasoan edo errekan.\l"
	.string "Ados al zaude nirekin?$"

Route106_Text_ElliotRegister:
	.string "Arrantza itzela da, baina baita\n"
	.string "borrokatzea ere. Elkartuko al gara berriz?$"

Route106_Text_ElliotRematchIntro:
	.string "POKéMON sorta bat harrapatu dut arrantzan.\n"
	.string "Itzelak dira borrokan!$"

Route106_Text_ElliotRematchDefeated:
	.string "Berriz ere kale!$"

Route106_Text_ElliotRematchPostBattle:
	.string "Irabazi edo galdu, POKéMONAK onenak dira!\n"
	.string "Ados al zaude nirekin?$"

Route106_Text_NedIntro:
	.string "Zer egiten du jendeak komunera joan\n"
	.string "behar badu?\p"
	.string "Eta nire KANABERAK arrain handi bat\n"
	.string "harrapatzen badu, zer? Ezin naiz joan…$"

Route106_Text_NedDefeated:
	.string "Komunera joan nahi eta ezin nabilelako\n"
	.string "galdu dut…$"

Route106_Text_NedPostBattle:
	.string "Ez! Ziur nago arrain handi bat\n"
	.string "harrapatuko dudala oraingoan!$"

Route106_Text_DouglasIntro:
	.string "Kar-kar! kaskarra naiz korrika,\n"
	.string "baina uretan garaitezina naiz!$"

Route106_Text_DouglasDefeated:
	.string "Amore ematen dut!$"

Route106_Text_DouglasPostBattle:
	.string "Igerian balitz ez nukeen galduko…$"

Route106_Text_KylaIntro:
	.string "Itsasoa oso ondo ezagutzen dut. Ez naiz\n"
	.string "gehiegi saiatuko, ume bat zara eta!$"

Route106_Text_KylaDefeated:
	.string "Azkenean zu ez zara gehiegi saiatu\n"
	.string "behar izan…$"

Route106_Text_KylaPostBattle:
	.string "Olatuek zu eraman zaitzaten uztea…\n"
	.string "Itzela da! Zergatik ez duzu probatzen?$"

Route107_Text_DarrinIntro:
	.string "Ene…\p"
	.string "Uste dut lo hartu dudala olatuen\n"
	.string "kulunkaren ondorioz.$"

Route107_Text_DarrinDefeated:
	.string "Kar-kar, galdu egin dut…\n"
	.string "Uste dut kuluxka bat egingo dudala…$"

Route107_Text_DarrinPostBattle:
	.string "Olatuekin gora eta behera ibiltzea\n"
	.string "--ohe bigun eta eroso batean lo\l"
	.string "egitea bezala da.$"

Route107_Text_TonyIntro:
	.string "Itsasoa oso ondo ezagutzen dut.\n"
	.string "Borroka dezagun!$"

Route107_Text_TonyDefeated:
	.string "Horren ondo ezagututa ere galdu…\n"
	.string "Ezin dut sinestu!$"

Route107_Text_TonyPostBattle:
	.string "Ametsez beteriko bihotzarekin egiten\n"
	.string "dut igeri itsasoan…\p"
	.string "Abesti bat da!\n"
	.string "Beno, igerian jarraituko dut.$"

Route107_Text_TonyRegister:
	.string "Harri eta zur utzi nauzu!\n"
	.string "Beno, ez nazazun ahaztu…$"

Route107_Text_TonyRematchIntro:
	.string "Itsaso zabalean igeri eginda\n"
	.string "nire POKéMONAK indartu egin dira!$"

Route107_Text_TonyRematchDefeated:
	.string "A zer nolako kolpea!\p"
	.string "Nire POKéMONAK indartsuak dira,\n"
	.string "baina ni ENTRENATZAILE ahula!$"

Route107_Text_TonyRematchPostBattle:
	.string "Borrokan ikasten duzunak ENTRENATZAILE\n"
	.string "hobea izaten laguntzen du.\l"
	.string "Olatuek irakatsi zidaten.$"

Route107_Text_DeniseIntro:
	.string "Ezagutzen al duzu IHINTZIBAR\n"
	.string "izeneko herria?$"

Route107_Text_DeniseDefeated:
	.string "Gorroto dut hau!$"

Route107_Text_DenisePostBattle:
	.string "Esaldi arraro bat modan jarri da\n"
	.string "IHINTZIBARREKO KLUBEAN.$"

Route107_Text_BethIntro:
	.string "Nirekin borrokatu nahi al zenuen?\n"
	.string "Noski, borroka dezagun!$"

Route107_Text_BethDefeated:
	.string "Ez naiz izan behar bezain ona.$"

Route107_Text_BethPostBattle:
	.string "Uste dut gero eta hobea bihurtuko\n"
	.string "zarela. Ni ere saiatuko naiz!$"

Route107_Text_LisaIntro:
	.string "MIREN: Neba-arreba gisan botako\n"
	.string "dizugu erronka!$"

Route107_Text_LisaDefeated:
	.string "MIREN: Bikain.\n"
	.string "Zu beste maila batean zaude.$"

Route107_Text_LisaPostBattle:
	.string "MIREN: Ba al duzu lagunik haiekin\n"
	.string "hondartzara joateko?$"

Route107_Text_LisaNotEnoughPokemon:
	.string "MIREN: Gure aurka borrokatzekotan\n"
	.string "POKéMON gehiago ekarri.$"

Route107_Text_RayIntro:
	.string "MIKEL: Beti egiten ditugu POKéMON\n"
	.string "bororkak, nik eta nire arrebak.\p"
	.string "Beti galtzen dut, baina irabazi\n"
	.string "egingo dugu 2-2ren aurka!$"

Route107_Text_RayDefeated:
	.string "MIKEL: Ene, guk baino maila altuagoa\n"
	.string "duzu zuk!$"

Route107_Text_RayPostBattle:
	.string "MIKEL: Nire arrebak eman zidan nire POKéMONA.\n"
	.string "Nik hazi nuen eta orain nire adiskide\l"
	.string "maitea da!$"

Route107_Text_RayNotEnoughPokemon:
	.string "MIKEL: Gure aurka borrokatzekotan,\n"
	.string "POKéMON gehiago ekarri!$"

Route107_Text_CamronIntro:
	.string "Triatloi erdi-erdian nago,\n"
	.string "baina ez nago nekatuta, ez horixe!$"

Route107_Text_CamronDefeated:
	.string "Akituta geratu naiz…$"

Route107_Text_CamronPostBattle:
	.string "Oraindik igeri eta korrika egitea\n"
	.string "falta zait.\p"
	.string "Ez al zait ezer gertatuko?$"

Route108_Text_JeromeIntro:
	.string "Nire ametsa munduko zazpi itsasoetan\n"
	.string "igeri egitea da!$"

Route108_Text_JeromeDefeated:
	.string "Horrela ezingo dut munduko zazpi\n"
	.string "itsasoetan igeri egin…$"

Route108_Text_JeromePostBattle:
	.string "Itsasoko POKéMONEKIN jolastea da igeri\n"
	.string "egitearen plazeretako bat!$"

Route108_Text_MatthewIntro:
	.string "Kaixo, txo! ITSASONTZI ABANDONATURA al\n"
	.string "zoaz zu ere?$"

Route108_Text_MatthewDefeated:
	.string "Hondorantza noa!\n"
	.string "Glub… Glub…$"

Route108_Text_MatthewPostBattle:
	.string "Batzuk ITSASONTZI ABANDONATUAREN\n"
	.string "barrura ere sartzen dira.$"

Route108_Text_TaraIntro:
	.string "Nire mutil-lagun gezurtiak bikinia\n"
	.string "ondo geratzen zaidala esan dit…$"

Route108_Text_TaraDefeated:
	.string "Oh, buu!$"

Route108_Text_TaraPostBattle:
	.string "gezurra bada ere, gustuko dut ondo\n"
	.string "geratzen zaidala esatea…\l"
	.string "Neskak konplexuak gara…$"

Route108_Text_MissyIntro:
	.string "Maite dut itsasoa!\n"
	.string "Igerian nire kezka guztia ahazten zaizkit!$"

Route108_Text_MissyDefeated:
	.string "Borroka bat galtzen dudanean oso\n"
	.string "estresatuta jartzen naiz!$"

Route108_Text_MissyPostBattle:
	.string "Lasaitu zure estresa igerian!\n"
	.string "Oso osasungarria da!$"

Route108_Text_CoryIntro:
	.string "UR motako POKéMONAK atsegin ditut.\n"
	.string "Beste POKéMONAK ere bai, noski!$"

Route108_Text_CoryDefeated:
	.string "Uaaaa! Galdu egin dut!\n"
	.string "Uaaaa! Uaaaa!$"

Route108_Text_CoryPostBattle:
	.string "Oihu egitea ondo datorkit!\n"
	.string "Alaitu egiten nau!$"

Route108_Text_CoryRegister:
	.string "ENTRENATZAILE indartsuak ere atsegin\n"
	.string "ditut! Erregistratu nazazu POKéNAVEAN!$"

Route108_Text_CoryRematchIntro:
	.string "Irabazi edo galdu, itzela da itsasoan borrokatzea!$"

Route108_Text_CoryRematchDefeated:
	.string "Uaaaa! Berriz galdu dut!\n"
	.string "Uaaaa! Uaaaa!$"

Route108_Text_CoryRematchPostBattle:
	.string "Erronka bati aurre egiteko,\n"
	.string "egin oihu itsasoari!$"

Route108_Text_CarolinaIntro:
	.string "Oso harro nago nire POKéMONEKIN.\n"
	.string "Borroka azkarra izango da!$"

Route108_Text_CarolinaDefeated:
	.string "Hau ez da batere polita izan.$"

Route108_Text_CarolinaPostBattle:
	.string "Itsasoan nagoenez, gustora jantziko\n"
	.string "dut bainujantzi apain bat…$"

Route109_Text_DavidIntro:
	.string "Iepa! Begira nire abdominalak!\n"
	.string "Hau da “definituta” egotea!$"

Route109_Text_DavidDefeated:
	.string "Ene!\n"
	.string "Egurra jaso dut!$"

Route109_Text_DavidPostBattle:
	.string "Iepa!\p"
	.string "Nire abdominalek ez dute balio\n"
	.string "POKéMON borroketan!$"

Route109_Text_AliceIntro:
	.string "Eman al duzu krema eguzkitik\n"
	.string "babesteko?$"

Route109_Text_AliceDefeated:
	.string "Ai, ai, ai!$"

Route109_Text_AlicePostBattle:
	.string "Masailak erretzen dira errazen!$"

Route109_Text_HueyIntro:
	.string "Portu askotan egon naiz munduan zehar,\n"
	.string "baina PORTUONDO da onena.$"

Route109_Text_HueyDefeated:
	.string "Onena zara!$"

Route109_Text_HueyPostBattle:
	.string "Portu onenean zegoen ENTRENATZAILE\n"
	.string "onena…$"

Route109_Text_EdmondIntro:
	.string "Urrrrppp…\n"
	.string "Borroka? Nirekin?$"

Route109_Text_EdmondDefeated:
	.string "Urp… Ooooooohhhhhh…\n"
	.string "Urrrrpppp…$"

Route109_Text_EdmondPostBattle:
	.string "Indartsuagoa naiz izatez!\n"
	.string "Izugarri ondoezik nago ordea!\p"
	.string "MARINELA naiz, baina…$"

Route109_Text_RickyIntro:
	.string "Egarria dut… FRESKAGARRI bat hartuko\n"
	.string "nuke ITSASERTZEKO ETXEAN…$"

Route109_Text_RickyDefeated:
	.string "Kaka…$"

Route109_Text_RickyPostBattle:
	.string "A zer gosea… Nire flotagailuak\n"
	.string "donut erraldoia dirudi…$"

Route109_Text_RickyRegister:
	.string "Borrokatuko duzu berriz nirekin\n"
	.string "egarririk ez dudanean?$"

Route109_Text_RickyRematchIntro:
	.string "Gosetuta nago, baina badut nahikoa\n"
	.string "indar borroka baterako!$"

Route109_Text_RickyRematchDefeated:
	.string "Galdu egin dut…\n"
	.string "Gosetuta nagoelako izan da…$"

Route109_Text_RickyRematchPostBattle:
	.string "Hondartzan jaten duzunean, janaria\n"
	.string "pixka bat goxoagoa izaten da.$"

Route109_Text_LolaIntro:
	.string "Hondartzako itzalkinek lore\n"
	.string "erraldoiak dirudite, baietz?$"

Route109_Text_LolaDefeated:
	.string "Amatxo!$"

Route109_Text_LolaPostBattle:
	.string "Hondartza zerutik begiratzen baduzu,\n"
	.string "lorategi erraldoi bat dirudi!$"

Route109_Text_LolaRegister:
	.string "Ni?\n"
	.string "Hemen nago beti!$"

Route109_Text_LolaRematchIntro:
	.string "Ez dut berriz galduko zure aurka!\n"
	.string "Horregatik daukat flotagailua aldean!$"

Route109_Text_LolaRematchDefeated:
	.string "Amatxo!$"

Route109_Text_LolaRematchPostBattle:
	.string "Flotagailua daukagunean ni eta nire\n"
	.string "POKéMONAK are politagoak gara!$"

Route109_Text_AustinaIntro:
	.string "Flotagailu gabe ezin dut igeri egin,\n"
	.string "baina ez dut galduko POKéMONEKIN!$"

Route109_Text_AustinaDefeated:
	.string "Flotagailuarengatik galdu ote\n"
	.string "dut azkenean?$"

Route109_Text_AustinaPostBattle:
	.string "Nire flotagailua modako jantzia da.\n"
	.string "Ezin naiz bera gabe inora joan.$"

Route109_Text_GwenIntro:
	.string "Kaixo, ENTRENATZAILE handia.\n"
	.string "Borrokatuko duzu nirekin?$"

Route109_Text_GwenDefeated:
	.string "Ene, indartsua zara, gero.$"

Route109_Text_GwenPostBattle:
	.string "Nola lortu duzu horren indartsua izatea?$"

Route109_Text_CarterIntro:
	.string "Kar-kar-kar! Tipo honek irabazi\n"
	.string "egingo du!$"

Route109_Text_CarterDefeated:
	.string "Tipo honek galdu egin du bada…$"

Route109_Text_CarterPostBattle:
	.string "Tipo honek handia zarela uste du.\n"
	.string "Ez, handiena izango zarela uste du!$"

Route109_Text_PaulIntro:
	.string "PAUL: Zerbait behar duzu edo?\p"
	.string "Inporta ez badizu, ez eten elkarrekin\n"
	.string "denbora pasatzen ari garenean.$"

Route109_Text_PaulDefeated:
	.string "PAUL: Beno, errenditu egiten naiz.$"

Route109_Text_PaulPostBattle:
	.string "PAUL: Ez esan inori hemen gaudela,\n"
	.string "mesedez.\l"
	.string "Hau gu bion mundu pertsonala da!$"

Route109_Text_PaulNotEnoughPokemon:
	.string "PAUL: Guztiz maiteminduta gaude.\n"
	.string "Horregatik batera egiten dugu\l"
	.string "borroka gure POKéMONEKIN.$"

Route109_Text_MelIntro:
	.string "MEL: Pila bat maite dugu elkar.\n"
	.string "Gure maitasuna HOENN osora zabalduko da!$"

Route109_Text_MelDefeated:
	.string "MEL: Galdu egin dugu, nire erruz!\n"
	.string "PAULEK gorrotatu egingo nau!$"

Route109_Text_MelPostBattle:
	.string "MEL: Eu, PAUL, haserre zaude nirekin?\n"
	.string "Ez haserretu, mesedez.$"

Route109_Text_MelNotEnoughPokemon:
	.string "MEL: Pila bat, izugarri maite dugu elkar.\n"
	.string "Horregatik batera egiten dugu\l"
	.string "borroka gure POKéMONEKIN.$"

Route109_Text_ChandlerIntro:
	.string "Tatxaaan! Ikusten?\n"
	.string "Nire flotagailua borobila da!$"

Route109_Text_ChandlerDefeated:
	.string "Oh, ez!\n"
	.string "Zer pena!$"

Route109_Text_ChandlerPostBattle:
	.string "Nire flotagailu borobila erakutsi\n"
	.string "ostean, gainera…$"

Route109_Text_HaileyIntro:
	.string "Ez dakit igerian, beraz itxura egiten\n"
	.string "ari naiz.$"

Route109_Text_HaileyDefeated:
	.string "Espero nuena!\n"
	.string "Ez nuen uste irabazi genezakeenik.$"

Route109_Text_HaileyPostBattle:
	.string "Igerian ikasten dudanean, nire\n"
	.string "POKéMONAK indartsuagoak izango dira.$"

Route109_Text_ElijahIntro:
	.string "Ni bezalako gizon batentzat, POKéMON\n"
	.string "mota hau ezinhobea da!$"

Route109_Text_ElijahDefeated:
	.string "Galtzen dudanean ere bikaina naiz, baietz?$"

Route109_Text_ElijahPostBattle:
	.string "Ni bezalako gizon batentzat, portuak\n"
	.string "leku ezinhobeak dira!\p"
	.string "Uste dut PORTUONDORA joango naizela.$"

Route110_Text_JacobIntro:
	.string "Uau! Kontuz!\n"
	.string "Ez zaude BIZIKLETAN ibiltzera ohituta, ezetz?$"

Route110_Text_JacobDefeated:
	.string "Uau!\n"
	.string "Frenoak huts egin dit!$"

Route110_Text_JacobPostBattle:
	.string "Gurpila zulatzen bazaizu edo frenoak\n"
	.string "hautsi, min har dezakezu!\l"
	.string "Ondo zaindu zure BIZIKLETA!$"

Route110_Text_AnthonyIntro:
	.string "Ei, aizu!\n"
	.string "Ezetz ni harrapatu!$"

Route110_Text_AnthonyDefeated:
	.string "Ene bada! A zer nolako istripua!$"

Route110_Text_AnthonyPostBattle:
	.string "Abiadurak soilik ez dit lagunduko POKéMON\n"
	.string "borrokak irabazten. Zeozer pentsatu behar dut…$"

Route110_Text_BenjaminIntro:
	.string "Lasai hartu zure BIZIKLETA azkarra bada!$"

Route110_Text_BenjaminDefeated:
	.string "Ez nintzateke urduri jarri behar POKéMON\n"
	.string "borroketan…$"

Route110_Text_BenjaminPostBattle:
	.string "Ez dago zertan urduri jarri.\n"
	.string "Lasai hartu, denbora soberan dago eta.$"

Route110_Text_BenjaminRegister:
	.string "Aurrera jarraituko dut estresatu gabe.\n"
	.string "Abisatu nirekin etorri nahi baduzu.$"

Route110_Text_BenjaminRematchIntro:
	.string "Ez al zoaz azkarregi?\n"
	.string "Lasai hartu eta borroka dezagun.$"

Route110_Text_BenjaminRematchDefeated:
	.string "Ez naiz urduri jarri baina galdu egin dut…$"

Route110_Text_BenjaminRematchPostBattle:
	.string "Ez dago zertan urduri jarri.\n"
	.string "Lasai hartu, denbora soberan dago eta.$"

Route110_Text_AbigailIntro:
	.string "Triatloia gogorra eta zaila da.\p"
	.string "Hiru kirol egin behar dituzu jarraian:\n"
	.string "igeriketa, txirrindularitza eta korrika.$"

Route110_Text_AbigailDefeated:
	.string "POKéMON borrokak ere gogorrak dira!$"

Route110_Text_AbigailPostBattle:
	.string "Lehertuta nago, deskantsatu behar dut.\n"
	.string "Garrantzitsua da atseden hartzea.$"

Route110_Text_AbigailRegister:
	.string "Badakizu, atsegin zaitut!\n"
	.string "Borroka dezagun berriz BIDEGORRIAN.$"

Route110_Text_AbigailRematchIntro:
	.string "Ez al da itzela bizikletan egon\n"
	.string "bitartean borrokatzea?$"

Route110_Text_AbigailRematchDefeated:
	.string "Ene…\n"
	.string "Zergatik zara horren indartsua?$"

Route110_Text_AbigailRematchPostBattle:
	.string "Errekor bat lortzekotan al zenbiltzan?\p"
	.string "barkatu tartean sartu banaiz!$"

Route110_Text_JasmineIntro:
	.string "Gelditu gabe ari naiz bizikletan.\n"
	.string "Nire izterrak harria baino gogorragoak dira!$"

Route110_Text_JasmineDefeated:
	.string "Giharretako minak beldurtzen nau…$"

Route110_Text_JasminePostBattle:
	.string "GIMNASIOKO DOMINA batzuk dauzkazu?\n"
	.string "Normala horren indartsua izatea, orduan!$"

Route110_Text_EdwardIntro:
	.string "Egingo duzuna aurreikusi dut!\n"
	.string "Ez dago nnik galtzeko aukerarik!$"

Route110_Text_EdwardDefeated:
	.string "Ezin izan dut nire porrota aurreikusi!$"

Route110_Text_EdwardPostBattle:
	.string "Zure etorkizuna ikus dezaket…\p"
	.string "Hmm…\n"
	.string "Argi bat ikusten dut…$"

Route110_Text_JaclynIntro:
	.string "Kar-kar-kar!\n"
	.string "Nire erasoekin liluratuko zaitut!$"

Route110_Text_JaclynDefeated:
	.string "Hori bai porrot harrigarria!$"

Route110_Text_JaclynPostBattle:
	.string "Irabaztea lortu baduzu, mirari bati\n"
	.string "esker izan da! Bai, mirari bat!\l"
	.string "Ez uste beti irabaziko duzunik!$"

Route110_Text_EdwinIntro:
	.string "Ikusi ditzaket zure POKéMONAK?\n"
	.string "Pixka bat bakarrik, mesedez?$"

Route110_Text_EdwinDefeated:
	.string "Nire bilduma osatu besterik\n"
	.string "ez nuen nahi…$"

Route110_Text_EdwinPostBattle:
	.string "Ezagutzen ez dudan POKéMON bat ikustean,\n"
	.string "nire bildumazaletasuna piztu egiten da!$"

Route110_Text_EdwinRegister:
	.string "BORROKA DEIAK biltzea ere\n"
	.string "gustoko dut, noski…$"

Route110_Text_EdwinRematchIntro:
	.string "Kaixo, harrapatu duzu POKéMON berririk?\p"
	.string "Ikusi ditzaket zure POKéMONAK?\n"
	.string "Pixka bat bakarrik, mesedez?$"

Route110_Text_EdwinRematchDefeated:
	.string "Zure POKéMONAK…\n"
	.string "A zer inbidia.$"

Route110_Text_EdwinRematchPostBattle:
	.string "Ene, POKéMON arraro guztiak bildu\n"
	.string "nahi nituzke!$"

Route110_Text_DaleIntro:
	.string "Ei!\n"
	.string "Ez agertu nire atzean bat-batean!$"

Route110_Text_DaleDefeated:
	.string "Galdu egin dut!\n"
	.string "Kaka!$"

Route110_Text_DalePostBattle:
	.string "Arrantzan kontzentrazioa da garrantzitsuena.\n"
	.string "Amuan kontzentratu behar duzu.$"

Route110_Text_IsabelIntro:
	.string "Kar-kar-kar! Edozein lekutara joango\n"
	.string "nintzateke nire POKéMONAK erakustera.$"

Route110_Text_IsabelDefeated:
	.string "Ai, ene, horrela ezin da.$"

Route110_Text_IsabelPostBattle:
	.string "Borrokatu ordez, nire POKéMONAK erakustera\n"
	.string "joan behar nuke POKéMONEN FAN KLUBERA.$"

Route110_Text_IsabelRegister:
	.string "Egin dudana baino askoz gehiago egin\n"
	.string "dezaket nire POKéMONEKIN.\p"
	.string "Ahal dudan guztietan erakutsiko dizut\n"
	.string "zer egin dezakedan!$"

Route110_Text_IsabelRematchIntro:
	.string "Kar-kar-kar! Gustora asko erakutsiko\n"
	.string "dizkizut nire POKéMONAK nahi duzunean!$"

Route110_Text_IsabelRematchDefeated:
	.string "Ai, ene, horrela ezin da.$"

Route110_Text_IsabelRematchPostBattle:
	.string "Uste dut ezingo niokeela inoiz nire\n"
	.string "POKéMONAK erakusteari utzi.\p"
	.string "Baina borroka ere atsegin dut!$"

Route110_Text_TimmyIntro:
	.string "POKéMON itzel batzuk aurkitu ditut\n"
	.string "hemen inguruko belarretan!$"

Route110_Text_TimmyDefeated:
	.string "Itzela izatea ez da irabazteko nahikoa…$"

Route110_Text_TimmyPostBattle:
	.string "Zaila da harrapatu berri dituzun\n"
	.string "POKéMONEKIN borrokatzea.$"

Route110_Text_AlyssaIntro:
	.string "BIDEGORRITIK erori naiz…\p"
	.string "Nire lotsa gaindituko dut zure\n"
	.string "aurka borrokatuz!$"

Route110_Text_AlyssaDefeated:
	.string "Ups!\n"
	.string "Galdu egin dut azkenean!$"

Route110_Text_AlyssaPostBattle:
	.string "Erori… eta gainera galdu…\n"
	.string "Hau bai humiliazioa!$"

Route110_Text_JosephIntro:
	.string "Ongi! Indar guztiz! Ezin baduzu erritmoa\n"
	.string "jarraitu, atzean geratuko zara!$"

Route110_Text_JosephDefeated:
	.string "Lortu duzu erritmoa jarraitzea…$"

Route110_Text_JosephPostBattle:
	.string "Honek ez nau kikilduko!\n"
	.string "Galtzeak gizon hobea bilakatu nau!$"

Route110_Text_KalebIntro:
	.string "POKéMON politek elkarri laguntzea…\n"
	.string "Ez dago hori baino ezer ederragorik!$"

Route110_Text_KalebDefeated:
	.string "Ez al daukazu erruki izpirik?$"

Route110_Text_KalebPostBattle:
	.string "Ongi, ongi, ahalik ondoen aritu\n"
	.string "zarete, nire politak.$"

Route111_Text_DrewIntro:
	.string "Aizu! BETAURREKO AISLANTEAK ondo geratzen\n"
	.string "zaizkizu. Baina nire hobe geratzen zaizkidala\p"
	.string "uste dut. Erabaki dezagun nori geratzen\n"
	.string "zaizkion hobe borroka batekin!$"

Route111_Text_DrewDefeat:
	.string "Ezin izan dut ikusi zer ari zen gertatzen\n"
	.string "alboetan BETAURREKO AISLANTEENGATIK.$"

Route111_Text_DrewPostBattle:
	.string "BETAURREKO AISLANTE hauekin harea\n"
	.string "ekaitzak gurutzatu ditzaket.\l"
	.string "Oso pozik jartzen nau horrek!$"

Route111_Text_HeidiIntro:
	.string "Piknik bat egingo dut basamortuan.\p"
	.string "Beti aurki dezakezu ENTRENATZAILEREN bat\n"
	.string "eta borroka ere egin dezaket orduan!$"

Route111_Text_HeidiDefeat:
	.string "Ene! Zu bai zu gaiztoa!$"

Route111_Text_HeidiPostBattle:
	.string "Harea-ekaitzean borrokatzen baduzu,\n"
	.string "zaindu zure POKéMONAREN BPAK.\p"
	.string "Ahuldu egin daitezke ez badituzu\n"
	.string "ondo zaintzen!$"

Route111_Text_BeauIntro:
	.string "BETAURREKO AISLANTE hauekin superheroi\n"
	.string "bat bezalakoa naiz.\l"
	.string "Oraintxe, ez lidake inork irabaziko!$"

Route111_Text_BeauDefeat:
	.string "Gogoa ez da nahikoa irabazteko…$"

Route111_Text_BeauPostBattle:
	.string "Egunen batena benetako heroia izango naiz.\n"
	.string "Gehiago saiatuko naiz ni eta\l"
	.string "nire POKéMONAK indartzeko.$"

Route111_Text_BeckyIntro:
	.string "Entzun dut basamortuan fosilak aurkitu\n"
	.string "daitezkeela. Non egongo ote dira?$"

Route111_Text_BeckyDefeat:
	.string "Ez dut nahikoa egin…$"

Route111_Text_BeckyPostBattle:
	.string "Basamortuan fosilak baldin badaude, horrek\n"
	.string "esan nahi du hemen itsasoa izan zela.$"

Route111_Text_DustyIntro:
	.string "Hogeita hamar urte ibili naiz\n"
	.string "antzinako hondakinen bila!\l"
	.string "Erronka botako al didazu?$"

Route111_Text_DustyDefeat:
	.string "Hondakinen bila ibili banaiz ere,\n"
	.string "ez ditut bilatu POKéMON indartsuak.$"

Route111_Text_DustyPostBattle:
	.string "Hogeita hamar urte ibili naiz\n"
	.string "antzinako hondakinen bila!\p"
	.string "Ez, itxaron, edo berrogei izan dira?\n"
	.string "Zenbat izan dira?$"

Route111_Text_DustyRegister:
	.string "Ez naiz POKéMON indartsuen\n"
	.string "bila ibili.\p"
	.string "Baina, arrazoiren batengatik, atsegin\n"
	.string "ditut POKéNAVAK.$"

Route111_Text_DustyRematchIntro:
	.string "Hogeita hamar urte ibili naiz\n"
	.string "antzinako hondakinen bila!\p"
	.string "Ez, itxaron, edo berrogei izan dira?\n"
	.string "Berdin da, erronka botako al didazu?$"

Route111_Text_DustyRematchDefeat:
	.string "Ez dut aurkitu ez antzinako hondakinik\n"
	.string "ezta POKéMON indartsurik ere…$"

Route111_Text_DustyPostRematch:
	.string "Hogeita hamar urte ibili naiz\n"
	.string "antzinako hondakinen bila!\p"
	.string "Ez, itxaron, berrogei urtez ibili\n"
	.string "al naiz bila?\p"
	.string "Hmm… Agian berrogeita hamar izan dira…\n"
	.string "Zenbat denbora ibili ote naiz honetan?$"

Route111_Text_TravisIntro:
	.string "Bizitasunez beteta nago!\n"
	.string "Eta nire POKéMONA ere bai!$"

Route111_Text_TravisDefeat:
	.string "Nire POKéMONAK bizitasuna galdu du…$"

Route111_Text_TravisPostBattle:
	.string "Bizitasunez beteriko ENTRENATZAILE bat\n"
	.string "ikustean, begira geratzen naiz.$"

Route111_Text_IreneIntro:
	.string "Ez dakit nora zoazen, baina,\n"
	.string "nahi al zenuke borrokatu?$"

Route111_Text_IreneDefeat:
	.string "Oh, zeinen ona zaren!$"

Route111_Text_IrenePostBattle:
	.string "Uste dut ERRAUTS MENDIRA joan\n"
	.string "behar nukeela, baina hemengo\l"
	.string "ikuspegia ere itzela da.$"

Route111_Text_DaisukeIntro:
	.string "Entrenatzeko, ikusten dudan orori\n"
	.string "erronka botatzen diot!$"

Route111_Text_DaisukeDefeat:
	.string "Osaba! Errenditu egiten naiz!$"

Route111_Text_DaisukePostBattle:
	.string "Egin dezakedan bakarra entrenatzen\n"
	.string "jarraitzea da, zu bezalako ENTRENATZAILE\l"
	.string "indartsuak garaitzeko.$"

Route111_Text_WiltonIntro:
	.string "Erakutsi zenbat indartu dituzun\n"
	.string "zure POKéMONAK.$"

Route111_Text_WiltonDefeat:
	.string "Ikusi dezaket, asko indartu dituzu,\n"
	.string "alajaina.$"

Route111_Text_WiltonPostBattle:
	.string "POKéMONEK eta ENTRENATZAILEEK asko\n"
	.string "ikasten dute borrokatuz.\p"
	.string "Garrantzitsuena inoiz ez errenditzea\n"
	.string "da, nahiz eta galdu.$"

Route111_Text_WiltonRegister:
	.string "Asko ikasi daiteke zure entrenatzeko\n"
	.string "estilotik.\p"
	.string "Errebantxa bat nahi nuke zuri\n"
	.string "ondo iruditzen bazaizu.$"

Route111_Text_WiltonRematchIntro:
	.string "Gure ahalmena mailaz igotzeko ari\n"
	.string "gara hemen entrenatzen.\l"
	.string "Batu eta entrenatu gurekin!$"

Route111_Text_WiltonRematchDefeat:
	.string "Ooh, ona zara, gero!$"

Route111_Text_WiltonPostRematch:
	.string "Horren indartsua zarenez, POKéMON\n"
	.string "LIGA garaitzen saiatu behar zenuke.$"

Route111_Text_BrookeIntro:
	.string "Zure POKéMONEK aktore serioak\n"
	.string "dirudite.\l"
	.string "Momentu batez geratzeko eskatuko dizut.$"

Route111_Text_BrookeDefeat:
	.string "Ez dute gogor itxura soilik,\n"
	.string "gogorrak dira benetan!$"

Route111_Text_BrookePostBattle:
	.string "Uste nuen era egokian ari nintzela nire\n"
	.string "POKéMONAK hazten, baina ez, oraindik\l"
	.string "lan handia daukat egiteko.$"

Route111_Text_BrookeRegister:
	.string "Zu bezalako pertsona indartsu gehiagoren\n"
	.string "laguna izan nahi nuke!$"

Route111_Text_BrookeRematchIntro:
	.string "POKéMONAK indartsuago edo ahulago\n"
	.string "bihurtu ditzakezu erakusten dizkiezun\l"
	.string "erasoen arabera.\p"
	.string "Zein eraso dakizkite zure\n"
	.string "POKéMONEK?$"

Route111_Text_BrookeRematchDefeat:
	.string "Eraso onak erakutsi dizkiezu!$"

Route111_Text_BrookePostRematch:
	.string "Agian ez nion utzi behar nire\n"
	.string "POKéMONARI eboluzionatzen eraso\l"
	.string "hobeak ikasi arte…$"

Route111_Text_CeliaIntro:
	.string "Ez nuen horrelako leku batera etorri\n"
	.string "behar piknik bat egitera!$"

Route111_Text_CeliaDefeat:
	.string "Jope!\n"
	.string "Benetan ez nuela etorri behar!$"

Route111_Text_CeliaPostBattle:
	.string "Horrelako harea-ekaitzarekin ezin da\n"
	.string "piknik bat egin nahiz eta BETAURREKO\l"
	.string "AISLANTEAK jantzita eduki…$"

Route111_Text_BryanIntro:
	.string "Indartsua al zara?\n"
	.string "Ikusi dezagun bada!$"

Route111_Text_BryanDefeat:
	.string "Ene! Zure indarra!\n"
	.string "Misterioz beteta dago!$"

Route111_Text_BryanPostBattle:
	.string "Basamortu honek misterioz\n"
	.string "beteta du harea!$"

Route111_Text_BrandenIntro:
	.string "Nire ogitartekoaren zati bat emango\n"
	.string "dizut galtzen baduzu.$"

Route111_Text_BrandenDefeat:
	.string "Tx! Uste nuen ogitarteko batekin\n"
	.string "nahikoa zela zu erosteko…$"

Route111_Text_BrandenPostBattle:
	.string "Nire SANDSHREWERI asko gustatzen\n"
	.string "zaio nire ogitartekoak jatea.$"

Route111_Text_TyronIntro:
	.string "Hau nire POKéMON kuttunena da!$"

Route111_Text_TyronDefeat:
	.string "Itxaron!\n"
	.string "Ongi ikusi al duzu nire POKéMONA?$"

Route111_Text_TyronPostBattle:
	.string "Borrokatzen dudanean asko harrotzen\n"
	.string "naiz nire POKéMONAK erakustean.\p"
	.string "Ziur nago mundu guztiak berdina\n"
	.string "sentitzen duela borrokatzean!$"

Route111_Text_CelinaIntro:
	.string "Erakutsi nola bihurtu nire bizitza\n"
	.string "zirraragarri.$"

Route111_Text_CelinaDefeat:
	.string "Ai… Ene…\n"
	.string "Hori zirrara gehiegi izan da.$"

Route111_Text_CelinaPostBattle:
	.string "Pultsua azkartuta daukat.\n"
	.string "ENTRENATZAILE bikaina zara.$"

Route111_Text_HaydenIntro:
	.string "Ni bezain gosetuta zaudenean,\n"
	.string "ez dago errukirik izaterik!$"

Route111_Text_HaydenDefeat:
	.string "Grrr…$"

Route111_Text_HaydenPostBattle:
	.string "Tripazorriak dauzkat!\n"
	.string "Agian BAIA batzuk egingo ditut parrillan…$"

Route111_Text_BiancaIntro:
	.string "MALBADITIK al zatoz?\n"
	.string "Orduan energiaz lepo egongo zara!$"

Route111_Text_BiancaDefeat:
	.string "Ai ama!\n"
	.string "Hori gehiegitxo izan da!$"

Route111_Text_BiancaPostBattle:
	.string "Bide hau…\n"
	.string "Ederra da paseatzeko.$"

Route112_Text_BriceIntro:
	.string "Kar-kar-kar!\n"
	.string "Borrokatuko al dugu?\l"
	.string "Zuk eta nik!\l"
	.string "Kar-kar-kar!$"

Route112_Text_BriceDefeat:
	.string "Galdu egin dut!\n"
	.string "Kar-kar-kar!$"

Route112_Text_BricePostBattle:
	.string "Kar-kar-kar! Zerbait sartu zait sudurrean!\n"
	.string "Kar-kar-kar-atxis!$"

Route112_Text_TrentIntro:
	.string "Nire hankak oso indartuta daude mendian\n"
	.string "gora eta behera ibiltzeagatik.\p"
	.string "Ez dira azkar nekatzen nire hankak,\n"
	.string "lagun!$"

Route112_Text_TrentDefeat:
	.string "Ai! Karranpak ditut hanketan!$"

Route112_Text_TrentPostBattle:
	.string "Probatu mendian ibiltzen, mendi buelta\n"
	.string "luzeak egiten bide hauetan, bost bat\l"
	.string "kiloko pisuak gerrian lotuta\l"
	.string "izanda.\p"
	.string "Horrela, lagun, lortuko duzu benetan\n"
	.string "sasoian jartzea.$"

Route112_Text_TrentRegister:
	.string "Ai, karranpak ditut hanketan.\n"
	.string "Emango zenizkidake benda batzuk\l"
	.string "nire bizkar-zorrotik?\p"
	.string "Ez, hori nire POKéNAVA da!\n"
	.string "Ongi, kontaktuetan gehituko zaitut.$"

Route112_Text_TrentRematchIntro:
	.string "Mendian ibilita jarri naiz sasoian.\n"
	.string "Soberan daukat indarra!$"

Route112_Text_TrentRematchDefeat:
	.string "Indarrean garaitu al naute?$"

Route112_Text_TrentRematchPostBattle:
	.string "Entzun dut benetan ENTRENATZAILE indartsuak\n"
	.string "daudela ERRAUTS MENDIAREN tontorrean.\p"
	.string "Tontorreraino igoko naiz eta erronka\n"
	.string "botako diet!$"

Route112_Text_LarryIntro:
	.string "Indartsua naiz.\n"
	.string "Ez dut negar egingo galduta ere.$"

Route112_Text_LarryDefeat:
	.string "Buaaaa!$"

Route112_Text_LarryPostBattle:
	.string "Ez naiz ari negarrez amatxorekin egon nahi dudalako!\n"
	.string "Zintz…$"

Route112_Text_CarolIntro:
	.string "Piknik bat egiten duzunean, kantatzea\n"
	.string "besterik ez duzu ondo pasatzeko!\l"
	.string "Ea, kanta dezagun elkarrekin!$"

Route112_Text_CarolDefeat:
	.string "Ene, indartsua zara!$"

Route112_Text_CarolPostBattle:
	.string "Ez du axola kantatzen ona edo txarra zaren\n"
	.string "eta berdin POKéMONEKIN.\p"
	.string "Ondo pasatzen baduzu, jada irabazi duzu!$"

Route112_Text_BryantIntro:
	.string "POKéMON itzelak harraptu ditut\n"
	.string "SUGAR MENDI-BIDEAN! Begira!$"

Route112_Text_BryantDefeat:
	.string "Hori bai bide aldapatsua!$"

Route112_Text_BryantPostBattle:
	.string "Atsegin dut nola egiten duzun borroka.\n"
	.string "Zeozer berezia du.$"

Route112_Text_ShaylaIntro:
	.string "Ene, zu bai ENTRENATZAILE xarmanta!\n"
	.string "Mesedez, borroka erromantiko bat behar dut!\l"
	.string "Nahikoa ona naiz!$"

Route112_Text_ShaylaDefeat:
	.string "Ene, zeinen indartsua zaren!\n"
	.string "Harri eta zur utzi nauzu!$"

Route112_Text_ShaylaPostBattle:
	.string "Lanpetuta al zaude oraintxe?\n"
	.string "Pentsatu dut errebantxa bat izan\l"
	.string "genezakeela orain…\l"
	.string "Baina lasai, lanpetuta bazaude.$"

Route113_Text_JaylenIntro:
	.string "Badakizu zergatik den horren itzela\n"
	.string "leku hau?$"

Route113_Text_JaylenDefeat:
	.string "Fiuuuu!\n"
	.string "Kaka zaharra!$"

Route113_Text_JaylenPostBattle:
	.string "Sumendiaren errautsak eguzkia estaltzen du,\n"
	.string "horregatik ez da horrenbeste berotzen.\p"
	.string "Hobe niretzat, ezin baitut beroa jasan!$"

Route113_Text_DillonIntro:
	.string "Sumendiaren erupzioak argi uzten du\n"
	.string "lurra bizirik dagoela.$"

Route113_Text_DillonDefeat:
	.string "Nahikoa indartsua zara zu gero!$"

Route113_Text_DillonPostBattle:
	.string "Autx! Aiii! Ezin dut ikusi!\n"
	.string "Errautsa dut aurpegian eta begian!\p"
	.string "Ulertzen? Aurpegian eta begian?\p"
	.string "Bueno, ez da oso txiste ona izan…$"

Route113_Text_MadelineIntro:
	.string "Parasol hau erabiltzen dut nire\n"
	.string "NUMEL maitea errauts bolkaniko\l"
	.string "zikinetik babesteko.$"

Route113_Text_MadelineDefeat:
	.string "Ufff, ufff…\n"
	.string "Akituta nago…$"

Route113_Text_MadelinePostBattle:
	.string "Oso ona zara honetan.\n"
	.string "Harrituta nago benetan!$"

Route113_Text_MadelineRegister:
	.string "Etorri, sartu nire guardasolaren azpian.\n"
	.string "Nire POKéNAVEAN erregistratuko zaitut.$"

Route113_Text_MadelineRematchIntro:
	.string "Ei, aspaldi elkar ikusten ez dugula!\n"
	.string "Borroka batera gonbida zaitzaket?$"

Route113_Text_MadelineRematchDefeat:
	.string "Bai, bikain!$"

Route113_Text_MadelinePostRematch:
	.string "Oraindik oso ona zara honetan.\n"
	.string "Harrituta nago benetan!$"

Route113_Text_LaoIntro:
	.string "Errautsetatik agertzen naiz! Iujuu!\n"
	.string "Erronka botako dizut!$"

Route113_Text_LaoDefeat:
	.string "Borroka galdu badut ere, ohorea ez dut galdu!$"

Route113_Text_LaoPostBattle:
	.string "Ezkutaketaren artea findu behar dut.\n"
	.string "Agur, hurrengora arte.$"

Route113_Text_LaoRegister:
	.string "Iajaaa! Ikusi POKéNAVEAN\n"
	.string "erregistratzeko antzinako teknika!$"

Route113_Text_LaoRematchIntro:
	.string "Errautsetatik agertzen naiz! Iujuu!\n"
	.string "Erronka botako dizut!$"

Route113_Text_LaoRematchDefeat:
	.string "Borroka galdu badut ere, ohorea ez dut galdu!$"

Route113_Text_LaoPostRematch:
	.string "Nire ezkutaketa paregabea ez da nahikoa\n"
	.string "nire borrokarako gaitasun kaskarrarekin…\p"
	.string "Agur, hurrengora arte.$"

Route113_Text_LungIntro:
	.string "Eskerrik asko ni aurkitzeagatik!\n"
	.string "Borroka egin behar dugu, hala ere!$"

Route113_Text_LungDefeat:
	.string "Nire ninjutsua erabiliko dut…\n"
	.string "“ERRAUTS BOLKANIKO KAPA ZURRUNBILOA”!\p"
	.string "…Zer?\n"
	.string "Amaitu da jada?$"

Route113_Text_LungPostBattle:
	.string "Badakizu zer den ezkutatzearen okerrena?\n"
	.string "Inor ez badator oso bakartia dela.$"

Route113_Text_ToriIntro:
	.string "ELENE: Gu biok errauts bilduma egiten dugu.\n"
	.string "POKéMON borrokak ere egiten ditugu.$"

Route113_Text_ToriDefeat:
	.string "ELENE: Galdu egin dugu… Aspergarria da,\n"
	.string "errauts gehiagoren bila noa.$"

Route113_Text_ToriPostBattle:
	.string "ELENE: Zenbat errauts dugu?\n"
	.string "TXIRULA ZURI batentzat adina, espero dut.$"

Route113_Text_ToriNotEnoughMons:
	.string "ELENE: Bi biren aurka borrokatzen dugu.\n"
	.string "Ez bagenu hala egingo, galduko genuke!$"

Route113_Text_TiaIntro:
	.string "ANE: Gu biok errauts bilduma egiten dugu.\n"
	.string "POKéMON borrokak ere egiten ditugu.$"

Route113_Text_TiaDefeat:
	.string "ANE: Ez dugu irabazi… Aspergarria da,\n"
	.string "errauts gehiagoren bila noa.$"

Route113_Text_TiaPostBattle:
	.string "ANE: Errauts pila bat dugu! Uste dut\n"
	.string "nahikoa badugula TXIRULA ZURI batentzat!$"

Route113_Text_TiaNotEnoughMons:
	.string "ANE: Bi biren aurka borrokatzen dugu.\n"
	.string "Ez bagenu hala egingo, galduko genuke!$"

Route113_Text_CobyIntro:
	.string "Pfft, hego hauekin urrutira bidali\n"
	.string "zaitzaket, erraz!$"

Route113_Text_CobyDefeat:
	.string "A… Zer?$"

Route113_Text_CobyPostBattle:
	.string "Horren erraz irabazten didatenean ez\n"
	.string "dakit zer esan ere…$"

Route113_Text_SophieIntro:
	.string "Hemengo beroak logura ematen dit.\n"
	.string "Borrokatu nirekin esna manten nadin.$"

Route113_Text_SophieDefeat:
	.string "Hau amets bat da.\n"
	.string "Ziur nago…$"

Route113_Text_SophiePostBattle:
	.string "Galtzean sutan jartzen naiz…\n"
	.string "Hementxe bertan egingo dut lo!\l"
	.string "Zzz!$"

Route113_Text_LawrenceIntro:
	.string "Errauts bolkanikoak biltzen\n"
	.string "ari zinen beharbada?$"

Route113_Text_LawrenceDefeat:
	.string "Kar-kar.\n"
	.string "Garbi irabazi digute.$"

Route113_Text_LawrencePostBattle:
	.string "Errauts azpian ezkutatu behar nuke.$"

Route113_Text_WyattIntro:
	.string "Ni-nire aurka borrokatu nahi duzu?\n"
	.string "Nahiz eta orain harrapatu dudan nire POKéMONA?$"

Route113_Text_WyattDefeat:
	.string "Po-pozik al zaude irabazi duzulako?\n"
	.string "Nahiz eta nire aurka izan den?$"

Route113_Text_WyattPostBattle:
	.string "Gainera orain galtzailearekin hitz\n"
	.string "egin nahi duzu?\p"
	.string "Ene, onena zara!\n"
	.string "Bai!$"

Route114_Text_LennyIntro:
	.string "Yodelayhihoo!\p"
	.string "… …\p"
	.string "Zuk ere “yodelayhihoo”\n"
	.string "esan behar duzu, hemen\l"
	.string "oihartzunik ez dago eta!$"

Route114_Text_LennyDefeat:
	.string "Yodelayhihoo!$"

Route114_Text_LennyPostBattle:
	.string "Txiki-txikia nintzenean, uste nuen\n"
	.string "norbait ari zela ni kopiatu eta\l"
	.string "bueltan “Yodelayhihoo” oihukatzen.$"

Route114_Text_LucasIntro:
	.string "Ez bazaude prest, ez zenuke hemen\n"
	.string "mendian egon behar!$"

Route114_Text_LucasDefeat:
	.string "Mendiek ez dute barkatzen…$"

Route114_Text_LucasPostBattle:
	.string "Neguan mendiak hilgarriak bihurtzen\n"
	.string "dira elur-ekaitz eta elur-jausiekin.$"

Route114_Text_ShaneIntro:
	.string "Kanpina dibertigarria da! Arrantzan\n"
	.string "egin, suaren inguruan bildu eta ipuin\p"
	.string "beldurgarriak knota ditzakezu! Baina\n"
	.string "onena POKéMON borrokak dira!$"

Route114_Text_ShaneDefeat:
	.string "Indartsuegia!$"

Route114_Text_ShanePostBattle:
	.string "Bikaina da nire POKéMONEKIN\n"
	.string "kanpinera joatea.$"

Route114_Text_NancyIntro:
	.string "Jan ostean ariketa egin behar dut.\n"
	.string "Borroka dezagun!$"

Route114_Text_NancyDefeat:
	.string "Ai, ene!$"

Route114_Text_NancyPostBattle:
	.string "Otordu goxo bat jan berri nago.\n"
	.string "Logura sartzen ari zait…$"

Route114_Text_SteveIntro:
	.string "Ufufufufufu…\n"
	.string "Nire POKéMONEN aurka borrokatu nahi?$"

Route114_Text_SteveDefeat:
	.string "Ni-nire POKéMONAK…$"

Route114_Text_StevePostBattle:
	.string "Gorputz handi eta gogorra, adar\n"
	.string "erraldoiak eta letagin gaiztoak…\p"
	.string "Ufufufufu…\n"
	.string "Halako POKéMON bat izan nahi nuke…$"

Route114_Text_SteveRegister:
	.string "Ez ahaztu zer egin didazun!\n"
	.string "Gogorarazi egingo dizut!$"

Route114_Text_SteveRematchIntro:
	.string "Ufufufufufu…\n"
	.string "Ea bada, borrokatu nire POKéMONEKIN…$"

Route114_Text_SteveRematchDefeat:
	.string "Zorte handia dut zure POKéMONAK\n"
	.string "ikusteko aukera izanda…$"

Route114_Text_StevePostRematch:
	.string "Ufufufufufu…\p"
	.string "POKéMONAK borrokan ikusten ditudanean,\n"
	.string "dardar batean jartzen naiz…$"

Route114_Text_BernieIntro:
	.string "Mendian sua egiten baduzu, beti\n"
	.string "gogoratu ura eduki behar duzula.$"

Route114_Text_BernieDefeat:
	.string "Eskerrik asko nire sua apaltzeagatik!$"

Route114_Text_BerniePostBattle:
	.string "Benetan kontuz ibili behar duzu\n"
	.string "basoan edozein su egiterakoan.\p"
	.string "Ez gutxietsi inoiz suaren\n"
	.string "indarra.$"

Route114_Text_BernieRegister:
	.string "Nire espiritua pizten duzu.\n"
	.string "Erregistratu dezagun elkar!$"

Route114_Text_BernieRematchIntro:
	.string "Ikasi al duzu beti eskura ura eduki\n"
	.string "behar duzula mendian sua egiteko?$"

Route114_Text_BernieRematchDefeat:
	.string "Ur-mauka batekin busti nauzu nik\n"
	.string "sua hartu aurretik, alajaina.$"

Route114_Text_BerniePostRematch:
	.string "Benetan kontuz ibili behar duzu\n"
	.string "basoan edozein su egiterakoan.\p"
	.string "Ez gutxietsi inoiz suaren\n"
	.string "indarra.$"

Route114_Text_ClaudeIntro:
	.string "Arrantzan bagina, ez zenuke nire\n"
	.string "aurka aukerarik izango.\l"
	.string "Beno, atera zure POKéMONAK!$"

Route114_Text_ClaudeDefeat:
	.string "Arrantzan bagina, irabazi egingo nukeen…$"

Route114_Text_ClaudePostBattle:
	.string "Uste dut hurrengoan METEORO UR-JAUZIAN\n"
	.string "saiatuko naizela.\p"
	.string "Zerbait egon behar da hor.\n"
	.string "Ziur nago.$"

Route114_Text_NolanIntro:
	.string "Atsegin dut arrantzatzea, baina baita\n"
	.string "borroka ere!\p"
	.string "Norbaitek erronka botzatzen badit, beti\n"
	.string "esaten diot baietz, arrantzan egonda ere.$"

Route114_Text_NolanDefeat:
	.string "Atsegin dut borrokatzea, baina horrek\n"
	.string "ez du esan nahi ona naizenik…$"

Route114_Text_NolanPostBattle:
	.string "Oraingoan lortuko dut!\p"
	.string "Beti pentsatzen dut hala, arrantzan\n"
	.string "edo POKéMON bila jarraitzeko.$"

Route114_Text_TyraIntro:
	.string "TYRA: Beno, noski.\n"
	.string "Badut gogoa, egia esanda.\l"
	.string "POKéMONEN inguruan erakutsiko dizut.$"

Route114_Text_TyraDefeat:
	.string "TYRA: A zer nolako borrokarako estiloa!$"

Route114_Text_TyraPostBattle:
	.string "TYRA: Nire ikasle IVYRI POKéMONEN\n"
	.string "inguruan erakusten ari nintzen.$"

Route114_Text_TyraNotEnoughMons:
	.string "TYRA: Kar-kar…\n"
	.string "Gure aurka borrokatzekotan, POKéMON\l"
	.string "bakarra ez da nahikoa!$"

Route114_Text_IvyIntro:
	.string "IVY: Nork erakutsi dizu POKéMONEN gainean?$"

Route114_Text_IvyDefeat:
	.string "IVY: A zer nolako borrokarako estiloa!$"

Route114_Text_IvyPostBattle:
	.string "IVY: TYRARI esker hasi nintzen POKéMONAK\n"
	.string "entrenatzen, nire irakasleari esker,\l"
	.string "berak irakatsi zidan eta!$"

Route114_Text_IvyNotEnoughMons:
	.string "IVY: POKéMON bakarra al duzu?\n"
	.string "Ez al da pixka bat bakartia hori?$"

Route114_Text_KaiIntro:
	.string "Izugarria harrapatu dut!\n"
	.string "Erraldoia, benetan!$"

Route114_Text_KaiDefeat:
	.string "Zer gertatu da?\n"
	.string "Galdu egin al dut tamainan?$"

Route114_Text_KaiPostBattle:
	.string "Ongi!\n"
	.string "Handiago bat harrapatuko dut orduan!$"

Route114_Text_CharlotteIntro:
	.string "Ni!\n"
	.string "Ez naiz aurpegi polit bat soilik!$"

Route114_Text_CharlotteDefeat:
	.string "Hori ez da batere polita izan!$"

Route114_Text_CharlottePostBattle:
	.string "Ez dut nahi polita soilik\n"
	.string "den  POKéMON bat.\p"
	.string "Berezitasunen bat dutenak\n"
	.string "gustatzen zaizkit!$"

Route114_Text_AngelinaIntro:
	.string "Askotan eboluzionatu al dituzu\n"
	.string "zure POKéMONAK?$"

Route114_Text_AngelinaDefeat:
	.string "Ados.\n"
	.string "Ondo dago jakitea.$"

Route114_Text_AngelinaPostBattle:
	.string "POKéMON batzuk izugarri aldatzen\n"
	.string "dira eboluzionatzean, itzela da!$"

Route115_Text_TimothyIntro:
	.string "Aizu…\n"
	.string "Badirudi abila zarela…\l"
	.string "Utzi zurekin egoten pixka bat!$"

Route115_Text_TimothyDefeat:
	.string "Uste nuena baino indartsuagoa\n"
	.string "zara, alajaina!$"

Route115_Text_TimothyPostBattle:
	.string "Inor ez da genioa jaiotzez.\n"
	.string "Saiatzea da behinena!\l"
	.string "Hala uste dut nik behintzat…$"

Route115_Text_TimothyRegister:
	.string "Hmm… Aspaldian ez zaidala horrelako\n"
	.string "porrot bat gertatu.\p"
	.string "Axola ez badizu, berriro ere borrokatu\n"
	.string "nahi nuke zurekin.$"

Route115_Text_TimothyRematchIntro:
	.string "Hm… Beti bezala, zure azkartasuna\n"
	.string "agerikoa da.\l"
	.string "Etorri, egon nirekin apur bat!$"

Route115_Text_TimothyRematchDefeat:
	.string "Beti bezain indartsua zara!$"

Route115_Text_TimothyPostRematch:
	.string "Saiatzea da behinena!\p"
	.string "Ez naizelako nahikoa saiatu\n"
	.string "galdu dut!$"

Route115_Text_KoichiIntro:
	.string "Zu!\p"
	.string "Nire MACHOP!\p"
	.string "Borroka nahi du!$"

Route115_Text_KoichiDefeat:
	.string "Autx, autx, autx!$"

Route115_Text_KoichiPostBattle:
	.string "Nire MACHOP taldea!\p"
	.string "Indar bila dabiltzan artean, ni ere\n"
	.string "beraiekin indartuko naiz!$"

Route115_Text_NobIntro:
	.string "Nire abilezia harrigarriena buruarekin\n"
	.string "adreiluak puskatzea da!$"

Route115_Text_NobDefeat:
	.string "Aiiiii!\n"
	.string "Burua hautsi dut!$"

Route115_Text_NobPostBattle:
	.string "Nire POKéMONEI karatea erakutsi diet.\p"
	.string "Badirudi ni baino hobeak bihurtu direla\n"
	.string "azkenean. Oso pozik nago horrekin.$"

Route115_Text_NobRegister:
	.string "Harritu egin nauzu! Egin dezagun errebantxa\n"
	.string "bat berriz entrenatu ostean!$"

Route115_Text_NobRematchIntro:
	.string "Irabazi zenidanean, gogor entrenatu genuen\n"
	.string "gure abilezia handitzeko.\l"
	.string "Ea ba, egin dezagun errebantxa bat!$"

Route115_Text_NobRematchDefeat:
	.string "Aiii!\n"
	.string "Berriz galdu dugu!$"

Route115_Text_NobPostRematch:
	.string "Nire POKéMONAK indartu egingo dira!\n"
	.string "Entrenamendua bikoiztuko dut!$"

Route115_Text_CyndyIntro:
	.string "Hondartza hau nire entrenatzeko leku\n"
	.string "sekretua da! Ezin zara edozelan sartu!$"

Route115_Text_CyndyDefeat:
	.string "Ez dut nahikoa entrenatu!$"

Route115_Text_CyndyPostBattle:
	.string "Hondarrak kolpea biguntzen laguntzen\n"
	.string "du lesioak gutxitzeko.\l"
	.string "Entrenatzeko leku perfektua da hau.$"

Route115_Text_CyndyRegister:
	.string "Ongi, ados, etorri zaitezke hona.\n"
	.string "Trukean, berriro borrokatu nahi nuke zurekin.$"

Route115_Text_CyndyRematchIntro:
	.string "Ongi, hasi gaitezen orduan!$"

Route115_Text_CyndyRematchDefeat:
	.string "Ezin dut nire POKéMONEKIN borrokatu…$"

Route115_Text_CyndyPostRematch:
	.string "Galtzen dudanean ere, ongi pasatzea\n"
	.string "lortzen dut beti.\l"
	.string "POKéMONEKIKO dudan maiatsuna izango da.$"

Route115_Text_HectorIntro:
	.string "POKéMON arraro bat dut!\n"
	.string "Erakutsi diezazuket?$"

Route115_Text_HectorDefeat:
	.string "Zuk…\n"
	.string "Nire POKéMONA nahi duzu, ez da hala?$"

Route115_Text_HectorPostBattle:
	.string "POKéMON arraro hau lortu dut.\n"
	.string "Nahikoa da ni pozik egoteko.$"

Route115_Text_KyraIntro:
	.string "Korrika nabilen bitartean borrokatuko dut!\n"
	.string "Saiatu ni jarraitzen!$"

Route115_Text_KyraDefeat:
	.string "Ufff, ufff…$"

Route115_Text_KyraPostBattle:
	.string "Korrika eta borroka batera egitea\n"
	.string "akats larria izan da!\p"
	.string "Lasaitzeko korrika pixka bat egingo dut…$"

Route115_Text_JaidenIntro:
	.string "Tori hau!\n"
	.string "POKéMON ninja ultra erasoa!$"

Route115_Text_JaidenDefeat:
	.string "Buaaaa!\n"
	.string "Gure estrategiak huts egin du!$"

Route115_Text_JaidenPostBattle:
	.string "Baina nire POKéMONAK ultra\n"
	.string "ziren, ez al da hala?$"

Route115_Text_HeleneIntro:
	.string "Nire POKéMONEK gerriko beltzen\n"
	.string "mailako indarra dute!$"

Route115_Text_HeleneDefeat:
	.string "Hau bai humiliazioa!$"

Route115_Text_HelenePostBattle:
	.string "Gutxitan aurkitzen dut ni baino\n"
	.string "hobea den inor…\p"
	.string "Ulertzen dut, bai!\n"
	.string "GIMNASIOKO LIDERRA zara, ezta?$"

Route115_Text_AlixIntro:
	.string "Begiradak gurutzatu ditugu!\n"
	.string "Orain ezin duzu ihes egin!$"

Route115_Text_AlixDefeat:
	.string "Ene!\n"
	.string "Gaizki ez!$"

Route115_Text_AlixPostBattle:
	.string "Oh, beno.\n"
	.string "Uste dut etxera TELEPORTATUKO naizela.$"

Route115_Text_MarleneIntro:
	.string "Meditazioa eragotzi didazu…\n"
	.string "Garesti ordainduko duzu hori.$"

Route115_Text_MarleneDefeat:
	.string "Kontzentrazioa galarazi didazu!$"

Route115_Text_MarlenePostBattle:
	.string "Nire POKéMONEKIN meditatzen ari nintzen.\n"
	.string "Baina leku hau ez da lasaiegia…$"

Route116_Text_ClarkIntro:
	.string "Tunelak ez badu zeharkatzen guztia,\n"
	.string "goitik joango naiz.$"

Route116_Text_ClarkDefeat:
	.string "Ufff… Ufff…\n"
	.string "Galtzeak nekatu egin nau…$"

Route116_Text_ClarkPostBattle:
	.string "Ez du axola tunelik ez badago.\n"
	.string "MENDIZALEONTZAKO mendiak bide arruntak dira!$"

Route116_Text_JoeyIntro:
	.string "Nire POKéMONAK onenak dira!\n"
	.string "Begira!$"

Route116_Text_JoeyDefeat:
	.string "Aiii! Arramazka bat!\n"
	.string "Benda bat jarri beharko dut!$"

Route116_Text_JoeyPostBattle:
	.string "Bendak gogortasunaren adierazle dira!\n"
	.string "Beste bat daukat hemen!$"

Route116_Text_JoseIntro:
	.string "Nire ZOMORRO POKéMONAK indartsuak dira!\n"
	.string "Borroka dezagun!$"

Route116_Text_JoseDefeat:
	.string "Galdu egin dut!\n"
	.string "Uste nuen irabaziko nuela!$"

Route116_Text_JosePostBattle:
	.string "ZOMORRO POKéMONAK azkar eboluzionatzen\n"
	.string "dira. Azkar indartzen dira, beraz.$"

Route116_Text_JaniceIntro:
	.string "Utzi erakusten nire POKéMON polita\n"
	.string "zeinen indartsua den!$"

Route116_Text_JaniceDefeat:
	.string "Ni baino apur bat hobea zara…$"

Route116_Text_JanicePostBattle:
	.string "POKéMON polit eta indartsuak, horiek\n"
	.string "dira egokienak, nire iritziz.$"

Route116_Text_JerryIntro:
	.string "ENTRENATZAILE ESKOLAN era askotariko\n"
	.string "kontuak ikasten ditugu.\p"
	.string "Orain ikasitakoa probatu nahi dut!$"

Route116_Text_JerryDefeat:
	.string "Piper egin dut eskolan…\n"
	.string "Horregatik galdu dut.$"

Route116_Text_JerryPostBattle:
	.string "Irakasgai batzuk berriro egin beharko\n"
	.string "ditut ENTRENATZAILE ESKOLAN.\l"
	.string "Bestela HAITZIBER asko haserretuko da.$"

Route116_Text_JerryRegister1:
	.string "ENTRENATZAILE ESKOLAN ikasi dut POKéNAVEAN\n"
	.string "ENTRENATZAILEAK erregistratu daitezkeela.\p"
	.string "Ez dut oso ondo ulertzen zer esan nahi\n"
	.string "duen, utziko zenidake probatzen?$"

Route116_Text_JerryRegister2:
	.string "ENTRENATZAILE ESKOLAN ikasi dut POKéNAVEAN\n"
	.string "ENTRENATZAILEAK erregistratu daitezkeela.\p"
	.string "Ez dut oso ondo ulertzen zer esan nahi\n"
	.string "duen, utziko zenidake probatzen?$"

Route116_Text_JerryRematchIntro:
	.string "Oso serio aritu naiz ENTRENATZAILE\n"
	.string "ESKOLAN ikasten.\l"
	.string "Ez dut aurrekoan bezala galduko.$"

Route116_Text_JerryRematchDefeat:
	.string "Zer?\n"
	.string "Asko ikasi dut eta!$"

Route116_Text_JerryPostRematch:
	.string "Irakasgai batzuk berriro egin beharko\n"
	.string "ditut ENTRENATZAILE ESKOLAN.\l"
	.string "Bestela HAITZIBER asko haserretuko da.$"

Route116_Text_KarenIntro:
	.string "Eskolan ikasten dut, baita etxera\n"
	.string "bidean noanean ere!$"

Route116_Text_KarenDefeat:
	.string "Ezin dut sinetsi, galdu egin al dut?$"

Route116_Text_KarenPostBattle:
	.string "Eneee, inoiz ez naiz HAITZIBER bezain\n"
	.string "entrenatzaile dotorea izango horrela!$"

Route116_Text_KarenRegister1:
	.string "Ene! Hori ez al da POKéNAV bat?\n"
	.string "Nik ere badut bat! Erregistratu nazazu, mesedez!$"

Route116_Text_KarenRegister2:
	.string "Ene! Hori ez al da POKéNAV bat?\n"
	.string "Nik ere badut bat! Erregistratu nazazu, mesedez!$"

Route116_Text_KarenRematchIntro:
	.string "Azkenengotik asko ikasi dut.\n"
	.string "Lortu dudana ikusi behar duzu!$"

Route116_Text_KarenRematchDefeat:
	.string "Ezin dut sinetsi.\n"
	.string "Berriz galdu al dut?$"

Route116_Text_KarenPostRematch:
	.string "HAITZIBERRI irabazi diozu?\n"
	.string "Orduan nik ezin dizut irabazi. Oraindik ez.$"

Route116_Text_SarahIntro:
	.string "Jakin dezazun, inork ez dit inoiz\n"
	.string "ezertan irabazi.$"

Route116_Text_SarahDefeat:
	.string "Ai ene jainkoa.\n"
	.string "Hau berria da niretzat.$"

Route116_Text_SarahPostBattle:
	.string "Nire luxuz betetako bizitzan nahi\n"
	.string "dudan guztia lor dezaket.\p"
	.string "POKéMONEN arloan, ordea, nire\n"
	.string "aberastasunak ez du balio.$"

Route116_Text_DawsonIntro:
	.string "Nire POKéMONAREN larrua ederra\n"
	.string "ikustean, ezingo duzu sinetsi\l"
	.string "ikusten ari zarena!$"

Route116_Text_DawsonDefeat:
	.string "Ai ama, ez esan galdu dudala!$"

Route116_Text_DawsonPostBattle:
	.string "Ai, ez, ez, ez!\n"
	.string "Nire POKéMONAREN larrua zarpaildu duzu!\l"
	.string "Nire orrazkera ere hondatu didazu!\l"
	.string "Ile apaintzaileari deitu beharko diot!$"

Route116_Text_DevanIntro:
	.string "Txikitu egingo zaitugu!$"

Route116_Text_DevanDefeat:
	.string "Aiyiyi!\n"
	.string "Erraz garaitu gaituzu!$"

Route116_Text_DevanPostBattle:
	.string "POKéMON mota desberdinak probatu\n"
	.string "behar nituzke, dudarik gabe.$"

Route116_Text_JohnsonIntro:
	.string "Bidea hemen amaitzen da.\n"
	.string "Aspertuta nago, borrokatuko al dugu?$"

Route116_Text_JohnsonDefeat:
	.string "Nahiz eta galdu, asko dibertitu naiz.$"

Route116_Text_JohnsonPostBattle:
	.string "Nahi duzu hemen geratu\n"
	.string "nirekin?$"

Route117_Text_IsaacIntro:
	.string "Entzun, borrokatu nahi duzu hazten\n"
	.string "ari naizen POKéMONEN aurka?$"

Route117_Text_IsaacDefeat:
	.string "Izugarri ondo hazi dituzu zureak…$"

Route117_Text_IsaacPostBattle:
	.string "POKéMONEN boterea ez da garrantzitsuena.\p"
	.string "Norberaren zati espezifiko bat\n"
	.string "lantzea POKéMONEKIN gozatzeko beste\l"
	.string "era bat da.$"

Route117_Text_IsaacRegister:
	.string "Nire entrenamendua bikoiztuko dut.\n"
	.string "Nahi duzu ikustera etorri?$"

Route117_Text_IsaacRematchIntro:
	.string "Hazten ari naizen POKéMONAK sasoi\n"
	.string "bikainean daude, lehen bezala.$"

Route117_Text_IsaacRematchDefeat:
	.string "Zuk badakizu zureak nola hazi.\n"
	.string "ZAINDEGI batean lan egiteko eskua duzu…$"

Route117_Text_IsaacPostRematch:
	.string "Zure POKéMONAK izugarri ondo hazten ari dira!\n"
	.string "TXAPELKETETAN izena eman behar zenuke.$"

Route117_Text_LydiaIntro:
	.string "Mesedez, utzi ikusten ea zure\n"
	.string "POKéMONAK ondo hazi dituzun.$"

Route117_Text_LydiaDefeat:
	.string "Bai, ederki ari dira hazten.$"

Route117_Text_LydiaPostBattle:
	.string "Saiatu POKéMONAK beraien\n"
	.string "izaeraren arabera hazten.$"

Route117_Text_LydiaRegister:
	.string "Pozten naiz zu lako ENTRENATZAILE bikaina\n"
	.string "ezagututa. Ikusiko dugu elkar berriz.$"

Route117_Text_LydiaRematchIntro:
	.string "Mesedez, utzi berriro ikusten ea zure\n"
	.string "POKéMONAK ondo hazi dituzun.$"

Route117_Text_LydiaRematchDefeat:
	.string "Bikainki ari dira hazten, bai.$"

Route117_Text_LydiaPostRematch:
	.string "POKéMONEI mota desberdinetako {POKEBLOCK}AK\n"
	.string "gustatzen zaizkie, izaeraren arabera.$"

Route117_Text_DylanIntro:
	.string "Triatloi bat egiten ari naiz, baina,\n"
	.string "berdin da, borroka dezagun!$"

Route117_Text_DylanDefeat:
	.string "Energiarik gabe geratu naiz!$"

Route117_Text_DylanPostBattle:
	.string "Uste dut kakaztu egin dudala…\p"
	.string "Borrokaren erruz azken postuan nagoela\n"
	.string "esango nuke…$"

Route117_Text_DylanRegister:
	.string "POKéMONAK ere indartsuak izan behar dira?\n"
	.string "Entrenatu nazazu ni, mesedez!$"

Route117_Text_DylanRematchIntro:
	.string "Triatloi bat egiten ari naiz, baina\n"
	.string "oso erraz ari naiz irabazten.\l"
	.string "Borroka azkar bat egin dezagun!$"

Route117_Text_DylanRematchDefeat:
	.string "Energiarik gabe geratu naiz berriz!$"

Route117_Text_DylanPostRematch:
	.string "Oso ona naiz igerian eta bizikletan,\n"
	.string "baina POKéMONEKIN borrokan oraindik\l"
	.string "badut zer ikasi.$"

Route117_Text_MariaIntro:
	.string "POKéMONEKIN entrenatzen naiz triatloirako,\n"
	.string "beraz, konfidantza dut gure abiaduran.$"

Route117_Text_MariaDefeat:
	.string "Gehiago praktikatu beharko dugu,\n"
	.string "dirudienez.$"

Route117_Text_MariaPostBattle:
	.string "Entrenatzen baduzu, garrantzitsua da\n"
	.string "erregularki egitea.\p"
	.string "Ongi! Entrenatzen jarraituko dut!\n"
	.string "Bihar, ordea!$"

Route117_Text_MariaRegister:
	.string "Ondo ari zarela entrenatzen dirudiu…\n"
	.string "Nahi baduzu, borrokatuko dugu geroago!$"

Route117_Text_MariaRematchIntro:
	.string "Ari al zara entrenatzen?\n"
	.string "Ni bai!\l"
	.string "Ikusiko duzu!$"

Route117_Text_MariaRematchDefeat:
	.string "Gehiago praktikatu beharko dugu,\n"
	.string "dirudienez.$"

Route117_Text_MariaPostRematch:
	.string "Bihar jarraituko dut entrenatzen.\n"
	.string "Beste batean borrokatu dezagun!$"

Route117_Text_DerekIntro:
	.string "Lehen ZOMORRO ZALEA!\n"
	.string "Orain ZOMORRO MANIAKOA!\p"
	.string "Baina POKéMONEKIKO dudan maitasuna\n"
	.string "ez da inoiz aldatuko!$"

Route117_Text_DerekDefeat:
	.string "Nire ezgaitasuna ere ez da\n"
	.string "inoiz aldatuko…$"

Route117_Text_DerekPostBattle:
	.string "Nire bihotzari jarraitu nion soilik,\n"
	.string "orain ZOMORRO MANIAKOA deitzen didate…\p"
	.string "Hala ere aditua naiz ZOMORRO POKéMONETAN.\n"
	.string "Normala da, beraz, ZOMORRO MANIAKO\l"
	.string "deitzea.$"

Route117_Text_AnnaIntro:
	.string "IHINTZA: Nire ikaskide gaztearekin nago\n"
	.string "orain. Ondo aritu behar dut!$"

Route117_Text_AnnaDefeat:
	.string "IHINTZA: Nire ikaskide gaztearekin nago\n"
	.string "orain. Utzi irabazten!$"

Route117_Text_AnnaPostBattle:
	.string "IHINTZA: Zure POKéMONEK konbinazio\n"
	.string "itzelak dituzte.\p"
	.string "Ia-ia gu baino hobea zara!$"

Route117_Text_AnnaAndMegRegister:
	.string "IHINTZA: Ezin dugu hau horrela utzi!\n"
	.string "Bueltatuko zara, ezta?$"

Route117_Text_AnnaNotEnoughMons:
	.string "IHINTZA: Gure aurka borrokatzekotan,\n"
	.string "ekarri bi POKéMON, gutxienez.$"

Route117_Text_MegIntro:
	.string "MAITE: Nire ikaskide nagusiarekin\n"
	.string "batera egurra emango dizut!$"

Route117_Text_MegDefeat:
	.string "MAITE: Ai, ez!\n"
	.string "Barkatu, IHINTZA! Ez dut itxura eman…$"

Route117_Text_MegPostBattle:
	.string "MAITE: IHINTZAK galdu egin du nire erruz…\n"
	.string "Itxura eman banu, irabazi egingo zuen!$"

Route117_Text_MegNotEnoughMons:
	.string "MAITE: POKéMON bakarra al duzu?\n"
	.string "Ezin dugu zure aurka borrokatu, orduan.\p"
	.string "2 2ren aurka soilik egiten dugu borroka.$"

Route117_Text_AnnaRematchIntro:
	.string "IHINTZA: Ezin dut nire ikaskide gaztearen\n"
	.string "alboan beti galdu, ezta?$"

Route117_Text_AnnaRematchDefeat:
	.string "IHINTZA: Ez dut erritmoa ondo harrapatu.$"

Route117_Text_AnnaPostRematch:
	.string "IHINTZA: Zure POKéMONEK konbinazio\n"
	.string "itzelak dituzte.\p"
	.string "Ia-ia gu baino hobea zara!$"

Route117_Text_AnnaRematchNotEnoughMons:
	.string "IHINTZA: Gure aurka borrokatzekotan,\n"
	.string "ekarri bi POKéMON, gutxienez.$"

Route117_Text_MegRematchIntro:
	.string "MAITE: Nire ikaskide nagusiarekin\n"
	.string "batera irabaziko dizut orain!$"

Route117_Text_MegRematchDefeat:
	.string "MAITE: Indartsuegia zara!$"

Route117_Text_MegPostRematch:
	.string "MAITE: Nire ikaskide nagusiarekin\n"
	.string "batera ere galdu egin dut…\p"
	.string "Bai etsigarria…$"

Route117_Text_MegRematchNotEnoughMons:
	.string "MAITE: POKéMON bakarra al duzu?\n"
	.string "Ezin dugu zure aurka borrokatu, orduan.\p"
	.string "2 2ren aurka soilik egiten dugu borroka.$"

Route117_Text_MelinaIntro:
	.string "Ez al da ederra? Lore politen artean\n"
	.string "borroka egitea?$"

Route117_Text_MelinaDefeat:
	.string "Ene, harrigarria izan da hori!$"

Route117_Text_MelinaPostBattle:
	.string "Bikaina da korrika egitea lore\n"
	.string "ederrei begira zauden bitartean.$"

Route117_Text_BrandiIntro:
	.string "Utzi nire POKéMON PSIKIKOEK\n"
	.string "duten indar ezkutua erakustean!$"

Route117_Text_BrandiDefeat:
	.string "Sinestezina!$"

Route117_Text_BrandiPostBattle:
	.string "POKéMON PSIKIKOAK konplexuak dira.\n"
	.string "Baten bat harrapatu behar zenuke.$"

Route117_Text_AishaIntro:
	.string "Garaipenean kontzentratuz.\n"
	.string "Hala egiten dut borrokan!$"

Route117_Text_AishaDefeat:
	.string "Ez dut denborarik galtzen irabazten ez\n"
	.string "dudanean haserretuz, hobe da entrenatzea.$"

Route117_Text_AishaPostBattle:
	.string "Uste dut, galtzeak kezkatzen bazaitu,\n"
	.string "errazago galduko duzula.$"

Route118_Text_RoseIntro:
	.string "Loreen lurrinak indar magikoa du.\n"
	.string "Gorputza eta arima garbitzen dizkit.$"

Route118_Text_RoseDefeat:
	.string "Ai, ene.\n"
	.string "Galdu egin dut, eta.$"

Route118_Text_RosePostBattle:
	.string "Loreak, POKéMONAK…\n"
	.string "Lurrin goxoa duen edozer gustatzen zait.\p"
	.string "Gauza kirastunak…\n"
	.string "Ez, mila esker.$"

Route118_Text_RoseRegister:
	.string "Zintz… usain hori, POKéNAV bat da eta!\n"
	.string "Elkar erregistratu behar dugu!$"

Route118_Text_RoseRematchIntro:
	.string "Lurrin gozoak ekarri al zaitu\n"
	.string "hona?$"

Route118_Text_RoseRematchDefeat:
	.string "Lurrinaren indarrak…\n"
	.string "Ez du ezer egin.$"

Route118_Text_RosePostRematch:
	.string "Lurrin gozoak ondo erabilita,\n"
	.string "POKéMONAK hurbilduko zaizkizu.$"

Route118_Text_PerryIntro:
	.string "Zeruan HEGAN egiten duten TXORI\n"
	.string "POKéMONAK… Onenak dira!$"

Route118_Text_PerryDefeat:
	.string "Ene…\n"
	.string "A zer kolpea…$"

Route118_Text_PerryPostBattle:
	.string "POKéMON bikainak dituzu.\n"
	.string "Hobe entrenatu beharko ditut nireak.$"

Route118_Text_ChesterIntro:
	.string "Egin hegan!\n"
	.string "Nire TXORI POKéMONAK!$"

Route118_Text_ChesterDefeat:
	.string "Hegan egin dute, bai…$"

Route118_Text_ChesterPostBattle:
	.string "Indartsuagoak balira, libreago\n"
	.string "egingo lukete hegan…$"

Route118_Text_BarnyIntro:
	.string "ARRANTZALEA naiz, baita ENTRENATZAILEA ere.\n"
	.string "Harrapatu ditudan POKéMONAK hazten ditut.$"

Route118_Text_BarnyDefeat:
	.string "uste nuen ondo ari nintzela\n"
	.string "entrenatzen…$"

Route118_Text_BarnyPostBattle:
	.string "Ezin izan ditut arrantzan ari nintzen\n"
	.string "bitartean POKéMONAK entrenatu…\p"
	.string "Erdizka ari ote nintzen gauzak egiten?$"

Route118_Text_WadeIntro:
	.string "ARRANTZALEONTZAT, tresneria da behinena.\p"
	.string "ENTRENATZAILEENTZAT, ordea, garrantzitsuena\n"
	.string "POKéMONAK eta bihotza dira!$"

Route118_Text_WadeDefeat:
	.string "Bihotzez irabazi al didate?$"

Route118_Text_WadePostBattle:
	.string "Ondo pentsatuz gero, arrantza borroka bat da\n"
	.string "ARRANTZALE baten eta POKéMON baten artean.$"

Route118_Text_DaltonIntro:
	.string "Utzi nire melodiak harrapa zaitzan!$"

Route118_Text_DaltonDefeat:
	.string "La-lalala…$"

Route118_Text_DaltonPostBattle:
	.string "Gitarra elektriko batek ez du zertan\n"
	.string "zarata atera…\p"
	.string "Bihotza uzkurtuko dizun melodiak\n"
	.string "jo daitezke, ondo erabiliz…$"

Route118_Text_DaltonRegister:
	.string "Melodia hobeak egiten ditudanean,\n"
	.string "etorri entzutera, ados?$"

Route118_Text_DaltonRematchIntro:
	.string "Nire POKéMONEK eta nik egindako melodia…\n"
	.string "Arimara iritsiko zaizu.$"

Route118_Text_DaltonRematchDefeat:
	.string "La-lalala…$"

Route118_Text_DaltonPostRematch:
	.string "Jotzen dudanean, nire emozioak gitarra\n"
	.string "elektrikoak adierazten ditu…$"

Route118_Text_DeandreIntro:
	.string "Aurrera, aurrera, aurrera!\n"
	.string "POKéMON 1, 2, eta 3!$"

Route118_Text_DeandreDefeat:
	.string "Ea ba, POKéMONAK! Ondo al zaudete?\n"
	.string "POKéMON 1, 2, eta 3?!$"

Route118_Text_DeandrePostBattle:
	.string "Ez al da itzela borrokarako\n"
	.string "POKéMON taldea izatea?\p"
	.string "Kopiatu, lasai. Ez zait axola!$"

Route119_Text_BrentIntro:
	.string "ZIRKULU MIMETIKOA gara!\n"
	.string "Egiten duzuna MIMETIZATZEN DUGU!$"

Route119_Text_BrentDefeat:
	.string "Ene, bada!\n"
	.string "Galdu egin dut!$"

Route119_Text_BrentPostBattle:
	.string "Zer den mimetizatzearen onena?\p"
	.string "Fufufu…\n"
	.string "Ez zenuke ulertuko…$"

Route119_Text_DonaldIntro:
	.string "Azkenean, ezagutu zaitut!\n"
	.string "Nire ZOMORRO POKéMONEK lagun egingo dizute!$"

Route119_Text_DonaldDefeat:
	.string "Hobe elkar ezagutu izan ez bagenu…$"

Route119_Text_DonaldPostBattle:
	.string "Gehiago MIMETIZATU nahi zaitut.\n"
	.string "Azkar ibili eta mugitu zaitezke?$"

Route119_Text_TaylorIntro:
	.string "Pausu bat aurrera ematen baduzu, guk ere bai.\p"
	.string "Ekuinera buelta emanda, guk ere berdin…$"

Route119_Text_TaylorDefeat:
	.string "Baina irabazten baduzu, guk galdu…$"

Route119_Text_TaylorPostBattle:
	.string "Ezin dut zure garaipena MIMETIZATU.\n"
	.string "Ezinezkoa da…\l"
	.string "A zer nolako amorrua…$"

Route119_Text_DougIntro:
	.string "Bai, harraptu nauzu, azkenean!\n"
	.string "Edo ni saihesten ari zinen?$"

Route119_Text_DougDefeat:
	.string "Uau, a zer nolako borroka!$"

Route119_Text_DougPostBattle:
	.string "ZIRKULU MIMETIKOA gara!\n"
	.string "Gure antzezpena gustatu zaizulakoan.$"

Route119_Text_GregIntro:
	.string "Ez dakizu nor naizen, ez da hala?\p"
	.string "Nik ere ez dakit zu nor zaren.\n"
	.string "Borroka dezagun, beraz!$"

Route119_Text_GregDefeat:
	.string "Indartsua zara, gero!$"

Route119_Text_GregPostBattle:
	.string "Hemendik joaten zaren arte, zure\n"
	.string "mugimendu guztiak MIMETIZATUKO ditugu.$"

Route119_Text_KentIntro:
	.string "ZIRKULU MIMETIKOA osatzen dutenek\n"
	.string "atsegin dute MIMETIZATZEA.\p"
	.string "Borrokatu egiten dugu elkartu bezain lasten!$"

Route119_Text_KentDefeat:
	.string "Errenditu egin naiz!$"

Route119_Text_KentPostBattle:
	.string "Nahi duzu ZIRKULU MIMETIKOAN parte hartu?$"

Route119_Text_JacksonIntro:
	.string "Zeinek dauka biziraupenerako\n"
	.string "sena eta teknika?\p"
	.string "POKéMON RANGERREN, noski!$"

Route119_Text_JacksonDefeat:
	.string "Ez dakit horrenbeste POKéMONEN\n"
	.string "inguruan…$"

Route119_Text_JacksonPostBattle:
	.string "Zibilizazioari ihes egin eta barneko\n"
	.string "espiritu basatia piztea!\p"
	.string "Hori da gure helburua.$"

Route119_Text_JacksonRegister:
	.string "Espero dut errebantxa bat egingo dugula\n"
	.string "nire jakinduria faltari barre egin gabe.$"

Route119_Text_JacksonRematchIntro:
	.string "Nire espiritu basatia berpiztuko du\n"
	.string "POKéMONEKIN batera egonda.$"

Route119_Text_JacksonRematchDefeat:
	.string "Indartsua zara oraindik!$"

Route119_Text_JacksonPostRematch:
	.string "Sinestu zure POKéMONETAN.\n"
	.string "Sinestu zure buruan.\p"
	.string "Aurrean agertuko zaizu bidea.$"

Route119_Text_CatherineIntro:
	.string "Zer? Zu bai bitxia.\p"
	.string "Abenturazalea izateko,\n"
	.string "ez duzu gauza asko aldean.$"

Route119_Text_CatherineDefeat:
	.string "Istripuak prest ez zaudenean\n"
	.string "jazotzen dira!$"

Route119_Text_CatherinePostBattle:
	.string "Ez duzu gauza asko aldean, baina\n"
	.string "bai behar duzun guztia.\p"
	.string "Fisikoki eta mentalki kontrolpean\n"
	.string "duzu dena.$"

Route119_Text_CatherineRegister:
	.string "POKéNAVIK ba al duzu?\n"
	.string "ENTRENATZAILE guztiek behar dute bat.\p"
	.string "Bai, baduzu bat eta!\n"
	.string "Erregistratu dezagun elkar, orduan!$"

Route119_Text_CatherineRematchIntro:
	.string "Zer moduz doa zure POKéMONEKIN\n"
	.string "egiten ari zaren bidaia?$"

Route119_Text_CatherineRematchDefeat:
	.string "Zeozer falta zait oraindik…$"

Route119_Text_CatherinePostRematch:
	.string "Zuk, ENTRENATZAILE bezala, zure\n"
	.string "POKéMONAK behar dituzun legez, zure\l"
	.string "POKéMONEK zu behar zaituzte.$"

Route119_Text_HughIntro:
	.string "Zeru amaigabea promesaz betea dago!\p"
	.string "Ezer ez da hegan egitea bezain\n"
	.string "zirraragarria!$"

Route119_Text_HughDefeat:
	.string "Bota egin naute!$"

Route119_Text_HughPostBattle:
	.string "Nire TXORI POKéMONEI esker, hegan\n"
	.string "egiteko nuen ametsa bete da!$"

Route119_Text_PhilIntro:
	.string "Nire eta nire TXORI POKéMONEN\n"
	.string "indarra erakutsiko dizut!$"

Route119_Text_PhilDefeat:
	.string "Indarra falta zaigu…$"

Route119_Text_PhilPostBattle:
	.string "Umea nintzenetik, beti miretsi izan\n"
	.string "ditut TXORI POKéMONAK…$"

Route119_Text_YasuIntro:
	.string "Itzaletan bizi eta ilunpetik\n"
	.string "agertzea… Hori da nire patua.\p"
	.string "Erronka botatzeko atera naiz!$"

Route119_Text_YasuDefeat:
	.string "Porrota onartzen dut!$"

Route119_Text_YasuPostBattle:
	.string "Borrokan galdu dutenak isilik\n"
	.string "bueltatzen dira itzaletara.\l"
	.string "Hori ere patua da…$"

Route119_Text_TakashiIntro:
	.string "Ez bazaude defentsarako adi,\n"
	.string "mina hartuko duzu!$"

Route119_Text_TakashiDefeat:
	.string "Izugarri ona zara, alajaina!$"

Route119_Text_TakashiPostBattle:
	.string "Nire sorpresa erasoak porrota\n"
	.string "eragin dit…$"

Route119_Text_HideoIntro:
	.string "Zuhaitza ezkutatzeko, basoa erabili!$"

Route119_Text_HideoDefeat:
	.string "Zure indarraren aurrean makurtzen naiz.$"

Route119_Text_HideoPostBattle:
	.string "Zuhaitza ezkutatzeko, basoa erabili!\n"
	.string "POKéMONA ezkutatzeko, POKéMONA erabili!\p"
	.string "Ez, ez dauka esanahi sakonik esan\n"
	.string "berri dudanak.$"

Route119_Text_ChrisIntro:
	.string "Hitz egin didazu…\n"
	.string "Erronka bota nahi didazu, orduan!\p"
	.string "Ongi! SURFA egiten ari nintzen bitartean\n"
	.string "harrapatutako POKéMONAK erabiliko ditut!$"

Route119_Text_ChrisDefeat:
	.string "Ez dakit zer egin behar den\n"
	.string "irabazteko, benetan.$"

Route119_Text_ChrisPostBattle:
	.string "Nire POKéMONEN gainean SURFA egitea…\p"
	.string "Eta ondoren arrantza bere bizkarretik…\p"
	.string "Momentu deskribaezina, zinez!$"

Route119_Text_FabianIntro:
	.string "Jo ezazu akorde bat!\n"
	.string "garaipena nirea da!\l"
	.string "Iritsi da dirdira egiteko momentua, bai!$"

Route119_Text_FabianDefeat:
	.string "Erakutsi didazu nor den nagusia!\n"
	.string "Onartu egin behar galdu dugun guztia!$"

Route119_Text_FabianPostBattle:
	.string "Jo ezazu beste akorde bat!\n"
	.string "Utzi nazazu bakarrik!\l"
	.string "Hemen geldituko naiz isilik!$"

Route119_Text_DaytonIntro:
	.string "Kar-kar-kar!\n"
	.string "Atsegin ditut ENTRENATZAILE gazteak!\l"
	.string "Borroka dezagun!$"

Route119_Text_DaytonDefeat:
	.string "Oso ona zara!\n"
	.string "Kar-kar-kar!$"

Route119_Text_DaytonPostBattle:
	.string "Kar-kar-kar!\n"
	.string "Zu bezalako ENTRENATZAILE gazteen\l"
	.string "indarra imitatzen saiatuko naiz!$"

Route119_Text_RachelIntro:
	.string "Edonon eta edonoiz, beti dut\n"
	.string "guardasola eskuan.$"

Route119_Text_RachelDefeat:
	.string "Ene, baina…\n"
	.string "Hori ez da justua.$"

Route119_Text_RachelPostBattle:
	.string "Nire guardasola astuna dela diozu?\n"
	.string "Ezertarako erabiliko ez nituzkeen\l"
	.string "gauzaz betea duzu POLTSA eta.$"

Route120_Text_ColinIntro:
	.string "Baduzu POKéMON hegalariak jo\n"
	.string "ditzakeen POKéMONIK?$"

Route120_Text_ColinDefeat:
	.string "Ni baino hobea zara!$"

Route120_Text_ColinPostBattle:
	.string "HEGALDI erasoa itzela da,\n"
	.string "ez al zaizu iruditzen?\p"
	.string "POKéMONA hegan dagoenean,\n"
	.string "ezin du ia ezerk jo.$"

Route120_Text_RobertIntro:
	.string "Nire POKéMONA indartsua da!\n"
	.string "Eta zurea?$"

Route120_Text_RobertDefeat:
	.string "Zure POKéMONAK indartsuagoak dira…$"

Route120_Text_RobertPostBattle:
	.string "Etengabe hazten den POKéMONA\n"
	.string "benetan da fidagarria.$"

Route120_Text_RobertRegister:
	.string "Uste dut zu ere etengabe haziko zarela.\n"
	.string "Nire POKéNAVEAN erregistratuko zaitut!$"

Route120_Text_RobertRematchIntro:
	.string "Etengabe hazten den POKéMONA\n"
	.string "benetan da fidagarria.$"

Route120_Text_RobertRematchDefeat:
	.string "Zure POKéMONAK zinez dira indartsuak.$"

Route120_Text_RobertPostRematch:
	.string "Nire POKéMONAK gero eta indartsuagoak dira.\n"
	.string "Ni ere indartu egin beharko naiz.$"

Route120_Text_LorenzoIntro:
	.string "Zure POKéMONAK aztertuko ditut eta ikusi\n"
	.string "ea egokiak diren kanpoan ibiltzeko.$"

Route120_Text_LorenzoDefeat:
	.string "Horrelako POKéMON indartsuekin, ziur\n"
	.string "ez duzula inork erreskatatzerik behar!$"

Route120_Text_LorenzoPostBattle:
	.string "Zure bihotzak agintzen dizun lekura\n"
	.string "bidaiatzea POKéMONEKIN…\l"
	.string "Hori da ENTRENATZAILEA izatearen onena.$"

Route120_Text_JennaIntro:
	.string "Sasoian al zaude?\n"
	.string "Ez bada hala, agian gaizki ibiliko\l"
	.string "zara muturreko egoeretan.$"

Route120_Text_JennaDefeat:
	.string "Ni sasoian nago, baina…$"

Route120_Text_JennaPostBattle:
	.string "Entrenatzea nire errutina da.\n"
	.string "Nire POKéMONEKIN egiten dut korrika.$"

Route120_Text_JeffreyIntro:
	.string "… … … … … …\n"
	.string "… … … … … …\l"
	.string "Borrokatu nahi?$"

Route120_Text_JeffreyDefeat:
	.string "Galdu egin dut…$"

Route120_Text_JeffreyPostBattle:
	.string "… … … … … …\n"
	.string "… … … … … …\l"
	.string "Gehiago saiatuko naiz…$"

Route120_Text_JeffreyRegister:
	.string "… … … … … …\n"
	.string "… … … … … …\l"
	.string "Ba al duzu POKéNAVIK…?$"

Route120_Text_JeffreyRematchIntro:
	.string "… … … … … …\n"
	.string "… … … … … …\l"
	.string "Berriz borrokatu nahi?$"

Route120_Text_JeffreyRematchDefeat:
	.string "… … … … … …\n"
	.string "Berriz galdu dut…$"

Route120_Text_JeffreyPostRematch:
	.string "… … … … … …\n"
	.string "… … … … … …\l"
	.string "Gehiago saiatuko naiz…\l"
	.string "Nire ZOMORRO POKéMONENGATIK…$"

Route120_Text_JenniferIntro:
	.string "POKéMONEK hainbat abilezia berezi dituzte.\n"
	.string "Lehen mailako ENTRENATZAILEA izateko,\l"
	.string "horien inguruan ikasi behar duzu.$"

Route120_Text_JenniferDefeat:
	.string "Argi dago pentsatzen ari zarela.$"

Route120_Text_JenniferPostBattle:
	.string "POKéMONEN abilezia bereziek\n"
	.string "borroka estiloa aldatzen dute.$"

Route120_Text_ChipIntro:
	.string "Zein ote zara?\p"
	.string "Agian kondaira zaharrek aipatzen\n"
	.string "duten antzinako hondakin horien\l"
	.string "bila zabiltza?$"

Route120_Text_ChipDefeat:
	.string "A zer atzerapauso lotsagarria…$"

Route120_Text_ChipPostBattle:
	.string "Arroka erraldoi hori… Benetan pentsatu\n"
	.string "nahi nuke antzinako hondakinak dituela.\l"
	.string "Baina ez dut sarrerarik ikusten.$"

Route120_Text_ClarissaIntro:
	.string "Zergatik ote dut guardasol hau?\p"
	.string "Irabazten badidazu esango dizut.$"

Route120_Text_ClarissaDefeat:
	.string "Guardasol batek ez du POKéMONEN\n"
	.string "erasoak babesteko balio…$"

Route120_Text_ClarissaPostBattle:
	.string "Uste dut eguzki gogor hau ez dela\n"
	.string "ona nire POKéMONENTZAT. Horregatik\l"
	.string "babesten ditut guardasolarekin.$"

Route120_Text_AngelicaIntro:
	.string "Ni, POKéMONAK, eta nire guardasola…\p"
	.string "Horietatik zeozer falta bada,\n"
	.string "argazkia ez da horren ederra.$"

Route120_Text_AngelicaDefeat:
	.string "Nire edertasuna guztiz hondatu duzu…$"

Route120_Text_AngelicaPostBattle:
	.string "Guardasola ez litzaieke denei ondo\p"
	.string "geratuko. Askorentzat estorbua besterik\n"
	.string "ez litzateke izango.$"

Route120_Text_KeigoIntro:
	.string "POKéMONEN erasoak erabili eta ninja\n"
	.string "teknika berriak sortuko ditut.$"

Route120_Text_KeigoDefeat:
	.string "Ninja teknika berriak sortzea\n"
	.string "amets urrun bat da…$"

Route120_Text_KeigoPostBattle:
	.string "Agian ninja sensei bat behar dut\n"
	.string "irakasle bezala.$"

Route120_Text_RileyIntro:
	.string "Ninjok gure kamuflaje kapak erabiltzen\n"
	.string "ditugu ezkutatzeko.\l"
	.string "Ziur nago ez zenekiela non nengoen ere!$"

Route120_Text_RileyDefeat:
	.string "Galdu egin dut!\n"
	.string "Nire lotsa kamuflatu beharko dut!$"

Route120_Text_RileyPostBattle:
	.string "Gure kamuflaje kapak eskuz eginda\n"
	.string "daude denak.$"

Route120_Text_CallieIntro:
	.string "Arreta jartzen ez baduzu,\n"
	.string "min hartu dezakezu!$"

Route120_Text_CallieDefeat:
	.string "Autx!\n"
	.string "Azkenean nik hartu dut mina.$"

Route120_Text_CalliePostBattle:
	.string "Ez dakit… Eboluzionatu behar ote nituzke\n"
	.string "nire POKéMONAK? Dauden gisan politak dira.$"

Route120_Text_LeonelIntro:
	.string "Zure POKéMON taldean…\n"
	.string "Mota desberdinak al dituzu?$"

Route120_Text_LeonelDefeat:
	.string "Ikusi dut zure borrokarako modua martxan!$"

Route120_Text_LeonelPostBattle:
	.string "Bikaina da zure POKéMON gustokoenekin\n"
	.string "horren indartsua izatea, zu bezala.$"

Route121_Text_VanessaIntro:
	.string "Jolastuko duzu nire POKéMON ikaragarri\n"
	.string "politekin?$"

Route121_Text_VanessaDefeat:
	.string "Ez nuen hori esan nahi!$"

Route121_Text_VanessaPostBattle:
	.string "UR-LILIKO TXAPELKETA batera noa.\p"
	.string "Nire POKéMONEK ez lukete arazorik izan\n"
	.string "behar MAISU MAILAN lehiatzeko.$"

Route121_Text_WalterIntro:
	.string "Nire POKéMONEKIN munduko txoko\n"
	.string "guztietara joan naiz.\p"
	.string "Esan daiteke badudala konfidantza\n"
	.string "nire abilezietan.$"

Route121_Text_WalterDefeat:
	.string "Bai, ondo jokatuta.$"

Route121_Text_WalterPostBattle:
	.string "Munduari bira eman nahi nioke beste\n"
	.string "behin nire POKéMONEKIN.$"

Route121_Text_WalterRegister:
	.string "Zure POKéMONEN balentria izugarria da.\n"
	.string "Utzi oroigarri bezala erregistratzen.$"

Route121_Text_WalterRematchIntro:
	.string "Nire POKéMONEKIN munduko txoko\n"
	.string "guztietara joan naiz.\p"
	.string "Esan daiteke badudala konfidantza\n"
	.string "nire abilezietan.$"

Route121_Text_WalterRematchDefeat:
	.string "Bai, ondo jokatuta.$"

Route121_Text_WalterPostRematch:
	.string "Zure POKéMONAK eta zu…\p"
	.string "Zuen balentriak leku guztietan ezagutuko\n"
	.string "dira, baita itsasoaren beste aldean ere.$"

Route121_Text_TammyIntro:
	.string "Ulertzen ez ditugun indarrak\n"
	.string "daude mundu honetan…$"

Route121_Text_TammyDefeat:
	.string "Galdu egin dut…$"

Route121_Text_TammyPostBattle:
	.string "PIRO MENDIA…\n"
	.string "Ziru nago botere misteriotsu bat\l"
	.string "dagoela bertan…$"

Route121_Text_KateIntro:
	.string "IRATI: Elkarrekin beldurgaitzak gara!\n"
	.string "Gure indarra erakutsiko dizugu!$"

Route121_Text_KateDefeat:
	.string "IRATI: Nire ikaskide gaztearen aurrean\n"
	.string "eskas aritu naiz…$"

Route121_Text_KatePostBattle:
	.string "IRATI: Norbaitek nigan konfidantza jarri\n"
	.string "badu, beraien aurrean ondo geratzeko\l"
	.string "behar izugarria daukat…$"

Route121_Text_KateNotEnoughMons:
	.string "IRATI: POKéMON bakarra baldin baduzu,\n"
	.string "ezin dugu zurekin borrokatu.\p"
	.string "Bullyinga litzateke hori.$"

Route121_Text_JoyIntro:
	.string "ZORIONE: Elkarrekin beldurgaitzak gara!\n"
	.string "Gure indarra erakutsiko dizugu!$"

Route121_Text_JoyDefeat:
	.string "ZORIONE: Barkatu mesedez, IRATI!$"

Route121_Text_JoyPostBattle:
	.string "ZORIONE: Ehehe, IRATIREKIN, nire ikaskide\n"
	.string "nagusiarekin, entrenatu beharko dut berriz.$"

Route121_Text_JoyNotEnoughMons:
	.string "ZORIONE: Gutxienez bi POKéMON behar\n"
	.string "dituzu guri erronka botatzeko!$"

Route121_Text_JessicaIntro:
	.string "Geldi! Begiratu ondo nire POKéMON\n"
	.string "maitagarria!$"

Route121_Text_JessicaDefeat:
	.string "Aizu, nola ausartzen zara!\n"
	.string "Ez ibili horren serio!$"

Route121_Text_JessicaPostBattle:
	.string "Agian POKéMON gehiago harrapatzera\n"
	.string "joango naiz SAFARIRA.$"

Route121_Text_JessicaRegister:
	.string "Oraingoan ez naiz indar osoz aritu!\n"
	.string "Hurrengoan ez da hala izango!$"

Route121_Text_JessicaRematchIntro:
	.string "Nire POKéMON ederrak hazi egin dira!\n"
	.string "Begiratu ondo!$"

Route121_Text_JessicaRematchDefeat:
	.string "Aizu, nola ausartzen zara!\n"
	.string "Beti indar osoz aritzen zara!$"

Route121_Text_JessicaPostRematch:
	.string "Agian POKéMON gehiago harrapatzera\n"
	.string "joango naiz SAFARIRA.$"

Route121_Text_CristinIntro:
	.string "Nire errutina kontatuko dizut.\n"
	.string "Bost ENTRENATZAILE garaitu egunero.\l"
	.string "Badakizu zer? Zu zara bostgarrena!$"

Route121_Text_CristinDefeat:
	.string "Ez!\n"
	.string "Izugarria zara!$"

Route121_Text_CristinPostBattle:
	.string "Ez nuen uste horren erraz irabaziko\n"
	.string "zenidanik… Hurrengoan irabaziko dut!$"

Route121_Text_CristinRegister:
	.string "A zer nolako humiliazioa!\n"
	.string "Ez zaitut ahaztuko…\l"
	.string "Ekarri zure POKéNAVA hona!$"

Route121_Text_CristinRematchIntro:
	.string "Errutina berria daukat.\n"
	.string "Hamar ENTRENATZAILE garaitu egunero.\l"
	.string "Badakizu zer? Zu zara hamargarrena!$"

Route121_Text_CristinRematchDefeat:
	.string "Itxaron! Hori zatarra izan da!\n"
	.string "Errebantxa nahi dut!$"

Route121_Text_CristinPostRematch:
	.string "Garaitu ezin dudan etsaia zara…\n"
	.string "ZIntz…\l"
	.string "Ezin dut sinetsi…$"

Route121_Text_CaleIntro:
	.string "Ez al duzu ikusten zenbat gauza\n"
	.string "dudan aldean?\p"
	.string "Hala ere, nire aurka borrokatu nahi\n"
	.string "al duzu?$"

Route121_Text_CaleDefeat:
	.string "Noski galdu dudala!\n"
	.string "Bi eskuak beteta ditut eta!$"

Route121_Text_CalePostBattle:
	.string "Gauza gehiegi erosi dut UR-LILIKO\n"
	.string "zentro komertzialean.\p"
	.string "Hemendik gora dago. Zurea bezalako\n"
	.string "POLTSA bat izan nahi nuke.$"

Route121_Text_MylesIntro:
	.string "Ez dago besteen POKéMONEI begiratzea\n"
	.string "baino gehiago gustatzen zaidanik!$"

Route121_Text_MylesDefeat:
	.string "Itzela!$"

Route121_Text_MylesPostBattle:
	.string "Itzelak dira zure POKéMONAK!\n"
	.string "Nola hazten dituzu?$"

Route121_Text_PatIntro:
	.string "Mundu guztiak hazi ditudan POKéMONAK\n"
	.string "ikustea nahi dut!$"

Route121_Text_PatDefeat:
	.string "Uau!\n"
	.string "Sinestezina!$"

Route121_Text_PatPostBattle:
	.string "POKéMON guztiak maitasunez zaintzen\n"
	.string "ditut. Ez daukat gustokoenik.$"

Route121_Text_MarcelIntro:
	.string "Nire POKéMONEK ez dute inoiz galdu!\n"
	.string "Berriz irabazten badute, TXAPELKETA\l"
	.string "batean sartuko ditut.$"

Route121_Text_MarcelDefeat:
	.string "Ene, zer gertatu da?$"

Route121_Text_MarcelPostBattle:
	.string "Agian gehixeago entrenatu behar dut\n"
	.string "taldea TXAPELKETAN izena eman aurretik.$"

Route123_Text_WendyIntro:
	.string "Nahi duzu jakin zeinen indartsua zaren?\n"
	.string "Ni izango naiz azterketa!$"

Route123_Text_WendyDefeat:
	.string "Bikain atera duzu azterketan!$"

Route123_Text_WendyPostBattle:
	.string "Niri ere irabaztea…\n"
	.string "Zure indarra miragarria da!$"

Route123_Text_BraxtonIntro:
	.string "You seem to have a big collection\n"
	.string "of GYM BADGES.\p"
	.string "Let me see if you're actually worthy of\n"
	.string "those BADGES!$"

Route123_Text_BraxtonDefeat:
	.string "Oh, you're worthy, all right!$"

Route123_Text_BraxtonPostBattle:
	.string "You did your BADGES proud in that\n"
	.string "match!$"

Route123_Text_VioletIntro:
	.string "They say that good times are filled\n"
	.string "with good aromas.$"

Route123_Text_VioletDefeat:
	.string "Oh…\n"
	.string "I smell the bitter scent of misery…$"

Route123_Text_VioletPostBattle:
	.string "The BERRY MASTER's garden is filled\n"
	.string "with uplifting fragrances.$"

Route123_Text_CameronIntro:
	.string "Being a psychic is about willpower.\p"
	.string "I've willed myself not to lose to\n"
	.string "anyone. That makes me strong!$"

Route123_Text_CameronDefeat:
	.string "I feel sad…$"

Route123_Text_CameronPostBattle:
	.string "Being a psychic is about willpower.\n"
	.string "I thought I wouldn't lose to you…$"

Route123_Text_CameronRegister:
	.string "I sense it!\n"
	.string "You and I shall battle again!\l"
	.string "I can't tell if I'll win, though…\p"
	.string "Let's see your POKéNAV.$"

Route123_Text_CameronRematchIntro:
	.string "I've convinced myself that I won't\n"
	.string "lose anymore. That makes me strong!$"

Route123_Text_CameronRematchDefeat:
	.string "I feel sad…$"

Route123_Text_CameronPostRematch:
	.string "I should train at MT. PYRE…\n"
	.string "I'll never beat you this way…$"

Route123_Text_JackiIntro:
	.string "Don't be too happy if your POKéMON\n"
	.string "develop psychic powers.\p"
	.string "You need to refine those powers to\n"
	.string "make them really useful.$"

Route123_Text_JackiDefeat:
	.string "Overwhelmed!$"

Route123_Text_JackiPostBattle:
	.string "We all have psychic powers.\n"
	.string "We've just forgotten how to use them.$"

Route123_Text_JackiRegister:
	.string "I would like to face you again.\n"
	.string "Is that okay with you?$"

Route123_Text_JackiRematchIntro:
	.string "Have you awoken the psychic powers\n"
	.string "within you?$"

Route123_Text_JackiRematchDefeat:
	.string "Astounding!$"

Route123_Text_JackiPostRematch:
	.string "Your power with POKéMON…\n"
	.string "That could be a psychic power, too.$"

Route123_Text_MiuIntro:
	.string "MIU: Hello, TRAINER. I hope your\n"
	.string "POKéMON won't cry when they lose.$"

Route123_Text_MiuDefeat:
	.string "MIU: Uh-oh, we lost.$"

Route123_Text_MiuPostBattle:
	.string "MIU: TRAINER, your POKéMON are\n"
	.string "strong because you are friends.$"

Route123_Text_MiuNotEnoughMons:
	.string "MIU: It's no fun to battle if you\n"
	.string "don't have two POKéMON.$"

Route123_Text_YukiIntro:
	.string "YUKI: Okay!\n"
	.string "We're beating the TRAINER's POKéMON!$"

Route123_Text_YukiDefeat:
	.string "YUKI: Uh-oh, we lost.$"

Route123_Text_YukiPostBattle:
	.string "YUKI: Why are you so strong?\n"
	.string "We've never lost before.$"

Route123_Text_YukiNotEnoughMons:
	.string "YUKI: It's no fun to battle if you\n"
	.string "don't have two POKéMON.$"

Route123_Text_KindraIntro:
	.string "MT. PYRE…\n"
	.string "Where the spirits of POKéMON sleep…\l"
	.string "Will your POKéMON sleep?$"

Route123_Text_KindraDefeat:
	.string "Overflowing with vitality…$"

Route123_Text_KindraPostBattle:
	.string "MT. PYRE…\n"
	.string "Where the spirits of POKéMON sleep…\p"
	.string "It must overflow with a power that\n"
	.string "soothes spirits…$"

Route123_Text_FernandoIntro:
	.string "I'll turn your lights out while\n"
	.string "I rip through this tune!$"

Route123_Text_FernandoDefeat:
	.string "Hey, hold it!\n"
	.string "I was still playing the intro!$"

Route123_Text_FernandoPostBattle:
	.string "You're rock steady.\n"
	.string "I'd like to write a tune about you.$"

Route123_Text_FernandoRegister:
	.string "The next time, lend your ears to\n"
	.string "the full tune, will you?$"

Route123_Text_FernandoRematchIntro:
	.string "Today's the day I'm going to do it!\n"
	.string "I'll turn out your lights before\l"
	.string "I finish singing my song!$"

Route123_Text_FernandoRematchDefeat:
	.string "Hey, hold it!\n"
	.string "I haven't even hit the chorus!$"

Route123_Text_FernandoPostRematch:
	.string "I thought you'd be so enthralled\n"
	.string "by my tune, you'd lose.$"

Route123_Text_DavisIntro:
	.string "This is my awesome BUG POKéMON!\n"
	.string "My big brother got it for me.$"

Route123_Text_DavisDefeat:
	.string "Waaaah!\n"
	.string "You meanie!$"

Route123_Text_DavisPostBattle:
	.string "Don't tell my brother I lost.\n"
	.string "You have to keep it a secret!$"

Route123_Text_JazmynIntro:
	.string "My confidence will get a boost by\n"
	.string "beating someone obviously strong!$"

Route123_Text_JazmynDefeat:
	.string "There goes my confidence…$"

Route123_Text_JazmynPostBattle:
	.string "They say that you can't judge a person\n"
	.string "by their appearance.\p"
	.string "But often, their looks don't lie…$"

Route123_Text_FrederickIntro:
	.string "Hello, child!\n"
	.string "Can you spare some time?$"

Route123_Text_FrederickDefeat:
	.string "Ah, a mighty capable child!\n"
	.string "Let me contribute to your allowance.$"

Route123_Text_FrederickPostBattle:
	.string "Contribute to your allowance?\n"
	.string "Wasn't the prize money enough?$"

Route123_Text_AlbertoIntro:
	.string "I have to tell you, BIRD POKéMON\n"
	.string "are my obsession!\p"
	.string "Birds are cool!\n"
	.string "They're the best!$"

Route123_Text_AlbertoDefeat:
	.string "Even in defeat, BIRD POKéMON are cool!$"

Route123_Text_AlbertoPostBattle:
	.string "I gather BIRD POKéMON feathers that\n"
	.string "scatter during battles.\p"
	.string "I'm going to make a hat with\n"
	.string "BIRD POKéMON feathers.$"

Route123_Text_EdIntro:
	.string "When there are no TRAINERS around,\n"
	.string "I let my POKéMON battle each other.\l"
	.string "I watch them.$"

Route123_Text_EdDefeat:
	.string "I kind of like your POKéMON.$"

Route123_Text_EdPostBattle:
	.string "Hehe, I'm swiping your battling ideas!\n"
	.string "I think they'll make me better.$"

Route123_Text_JonasIntro:
	.string "I lay in ambush, and a TRAINER has\n"
	.string "landed in my trap!$"

Route123_Text_JonasDefeat:
	.string "If you don't lose, how am I supposed\n"
	.string "to have fun playing ninja?$"

Route123_Text_JonasPostBattle:
	.string "I'm going to ambush a weaker-looking\n"
	.string "TRAINER next time.$"

Route123_Text_KayleyIntro:
	.string "I just bought this parasol.\n"
	.string "My cuteness should be up by a third!$"

Route123_Text_KayleyDefeat:
	.string "You're better than me by about\n"
	.string "five times!$"

Route123_Text_KayleyPostBattle:
	.string "Using accessories effectively is\n"
	.string "the secret behind fashion appeal.$"

Route124_Text_SpencerIntro:
	.string "Hey, are you lost at sea?\p"
	.string "If you can beat my POKéMON,\n"
	.string "I can serve as your pilot.$"

Route124_Text_SpencerDefeat:
	.string "I lost my bearings in battle!$"

Route124_Text_SpencerPostBattle:
	.string "Many people lose their bearings at sea.\p"
	.string "If you're that sort, you should refer\n"
	.string "to the POKéNAV's MAP.$"

Route124_Text_RolandIntro:
	.string "Hm! You're riding a POKéMON instead\n"
	.string "of swimming yourself…\p"
	.string "I am envious!$"

Route124_Text_RolandDefeat:
	.string "Oh!\n"
	.string "I can't…$"

Route124_Text_RolandPostBattle:
	.string "I'm getting chilled…\n"
	.string "I've been in the water too long…\p"
	.string "I wish I could ride a POKéMON like you…$"

Route124_Text_JennyIntro:
	.string "If you just float in the sea like\n"
	.string "this, POKéMON come around to play.$"

Route124_Text_JennyDefeat:
	.string "Oh, darn.\n"
	.string "I've gone and lost.$"

Route124_Text_JennyPostBattle:
	.string "While swimming, I noticed that some\n"
	.string "POKéMON attack, and some just watch.\p"
	.string "I guess POKéMON have personalities\n"
	.string "of their own.$"

Route124_Text_JennyRegister:
	.string "It's only on a whim, but maybe I'll get\n"
	.string "you to register me in your POKéNAV.$"

Route124_Text_JennyRematchIntro:
	.string "If you just float in the sea like this,\n"
	.string "TRAINERS challenge you!$"

Route124_Text_JennyRematchDefeat:
	.string "That's strange…\n"
	.string "I lost again…$"

Route124_Text_JennyPostRematch:
	.string "This has nothing to do with anything,\n"
	.string "but maybe I'll visit the TRICK HOUSE.$"

Route124_Text_GraceIntro:
	.string "I'm growing bored of swimming…\n"
	.string "How about a battle?$"

Route124_Text_GraceDefeat:
	.string "I had no idea that you were\n"
	.string "this strong!$"

Route124_Text_GracePostBattle:
	.string "All the effort you put in must have\n"
	.string "made you this strong.$"

Route124_Text_ChadIntro:
	.string "Fufufufu… I dive deep underwater\n"
	.string "to go deep under cover.\l"
	.string "Plumbing the depths is where I excel!$"

Route124_Text_ChadDefeat:
	.string "Glub, glub, glub…\n"
	.string "I'm sinking…$"

Route124_Text_ChadPostBattle:
	.string "I have it on good authority that\n"
	.string "there's a DIVE spot around here.\p"
	.string "It gives me the urge to go deep\n"
	.string "again…$"

Route124_Text_LilaIntro:
	.string "LILA: Sigh…\p"
	.string "Here I am in the sea, but who's with me?\n"
	.string "My little brother!\p"
	.string "Let's battle so I won't have to dwell\n"
	.string "on that!$"

Route124_Text_LilaDefeat:
	.string "LILA: ROY! It's your fault we lost!\n"
	.string "You're in for it later!$"

Route124_Text_LilaPostBattle:
	.string "LILA: Sigh…\p"
	.string "If only it wasn't my little brother\n"
	.string "next to me, but a nice boyfriend…$"

Route124_Text_LilaNotEnoughMons:
	.string "LILA: You're planning to battle us?\n"
	.string "Not unless you have two POKéMON.$"

Route124_Text_RoyIntro:
	.string "ROY: My big sister is tough at POKéMON!\p"
	.string "Don't cry when you lose!$"

Route124_Text_RoyDefeat:
	.string "ROY: Uh-oh…\n"
	.string "My big sister will chew me out…$"

Route124_Text_RoyPostBattle:
	.string "ROY: My big sister is really scary\n"
	.string "when she gets angry.\p"
	.string "That's why she doesn't have a\n"
	.string "boyfriend.$"

Route124_Text_LilaRoyRegister:
	.string "ROY: Will you battle with us again?\n"
	.string "But take it easy next time, okay?$"

Route124_Text_RoyNotEnoughMons:
	.string "ROY: Did you want to battle us?\n"
	.string "Bring two POKéMON, then.$"

Route124_Text_LilaRematchIntro:
	.string "LILA: Sigh…\p"
	.string "Here I am in the sea, but who's with me?\n"
	.string "My little brother!\p"
	.string "Oh, hi, it's been a while. Let's battle\n"
	.string "so I won't have to dwell on things!$"

Route124_Text_LilaRematchDefeat:
	.string "LILA: ROY!\n"
	.string "It's your fault we lost again!\p"
	.string "We're having a training session later!$"

Route124_Text_LilaPostRematch:
	.string "LILA: Sigh…\p"
	.string "If I had a nice boyfriend, we'd beat\n"
	.string "anyone with lovely combinations…$"

Route124_Text_LilaRematchNotEnoughMons:
	.string "LILA: You're planning to battle us?\n"
	.string "Not unless you have two POKéMON.$"

Route124_Text_RoyRematchIntro:
	.string "ROY: If we lose, I'll catch heck.\n"
	.string "I'm going to go totally all out!$"

Route124_Text_RoyRematchDefeat:
	.string "ROY: Uh-oh…\n"
	.string "My big sister will chew me out again.$"

Route124_Text_RoyPostRematch:
	.string "ROY: My big sister is really scary\n"
	.string "when she gets angry.\p"
	.string "She's going to make me train really\n"
	.string "hard with POKéMON later…$"

Route124_Text_RoyRematchNotEnoughMons:
	.string "ROY: Did you want to battle us?\n"
	.string "Bring two POKéMON, then.$"

Route124_Text_DeclanIntro:
	.string "Here I am swimming by my lonesome\n"
	.string "on this wide, beautiful sea.\p"
	.string "There's no other word for it.\n"
	.string "This is pathetic!$"

Route124_Text_DeclanDefeat:
	.string "I'm feeling blue.\n"
	.string "Blue as the sky…$"

Route124_Text_DeclanPostBattle:
	.string "I should chat up lady SWIMMERS\n"
	.string "and invite them on a long swim.$"

Route124_Text_IsabellaIntro:
	.string "I'm not going to lose to some\n"
	.string "surfer TRAINER.$"

Route124_Text_IsabellaDefeat:
	.string "I've only got sweat in my eyes!\n"
	.string "I am not crying!$"

Route124_Text_IsabellaPostBattle:
	.string "You can find pretty colored shards\n"
	.string "of things around here.$"

Route125_Text_NolenIntro:
	.string "I heard you approaching, so I hung\n"
	.string "around for you!$"

Route125_Text_NolenDefeat:
	.string "I surrender!$"

Route125_Text_NolenPostBattle:
	.string "Sound travels faster in water than\n"
	.string "it does through air.$"

Route125_Text_StanIntro:
	.string "Hey, there!\n"
	.string "Check out my sweet POKéMON!$"

Route125_Text_StanDefeat:
	.string "I floundered…$"

Route125_Text_StanPostBattle:
	.string "I was blown away by HORSEA's charm,\n"
	.string "so I started swimming, too.$"

Route125_Text_TanyaIntro:
	.string "I'm tired of swimming.\n"
	.string "Are you up for a battle with me?$"

Route125_Text_TanyaDefeat:
	.string "You're too much!$"

Route125_Text_TanyaPostBattle:
	.string "Whew…\n"
	.string "Which way is it to MOSSDEEP CITY?$"

Route125_Text_SharonIntro:
	.string "How would you like to take on the\n"
	.string "WATER-type POKéMON I raised?$"

Route125_Text_SharonDefeat:
	.string "Lost it…$"

Route125_Text_SharonPostBattle:
	.string "Your power… You're the real deal.\n"
	.string "I'm amazed!$"

Route125_Text_ErnestIntro:
	.string "Ahoy! I'm a buff, tough SAILOR!\n"
	.string "I've braved the world's seas!$"

Route125_Text_ErnestDefeat:
	.string "Gwrroooar!\n"
	.string "I couldn't win!$"

Route125_Text_ErnestPostBattle:
	.string "The tide ebbs and flows inside the\n"
	.string "SHOAL CAVE.\p"
	.string "By the way, it's about six hours from\n"
	.string "high tide to low tide. Did you know?$"

Route125_Text_ErnestRegister:
	.string "Register me in your POKéNAV,\n"
	.string "and I'll tell you something good.$"

Route125_Text_ErnestRematchIntro:
	.string "It's high time I get my payback\n"
	.string "from you! Come on, we're battling!$"

Route125_Text_ErnestRematchDefeat:
	.string "I couldn't win!\n"
	.string "I flat out couldn't win!$"

Route125_Text_ErnestRematchPostBattle:
	.string "The SHOAL CAVE…\p"
	.string "There are places you can and can't\n"
	.string "get to depending on the rise and fall\l"
	.string "of the tide.\p"
	.string "By the way, it's about six hours from\n"
	.string "high tide to low tide. Don't forget!$"

Route125_Text_KimIntro:
	.string "KIM: A funny old man lives in the\n"
	.string "SHOAL CAVE. Someone told me.\l"
	.string "Are you going to see him, too?$"

Route125_Text_KimDefeat:
	.string "KIM: I thought we would win.$"

Route125_Text_KimPostBattle:
	.string "KIM: A funny old man lives in the\n"
	.string "SHOAL CAVE, doesn't he?\p"
	.string "Let's go see him, IRIS!$"

Route125_Text_KimNotEnoughMons:
	.string "KIM: No, no, no! You need two POKéMON,\n"
	.string "or it's just no good!$"

Route125_Text_IrisIntro:
	.string "IRIS: KIM, can you tell me what we're\n"
	.string "looking for out here?$"

Route125_Text_IrisDefeat:
	.string "IRIS: Oh, we came sort of close.$"

Route125_Text_IrisPostBattle:
	.string "IRIS: KIM, are we really going into\n"
	.string "the SHOAL CAVE?\l"
	.string "We'll get all wet.$"

Route125_Text_IrisNotEnoughMons:
	.string "IRIS: Oh, we could never, ever do\n"
	.string "anything like a 2-on-1 battle.$"

Route125_Text_PresleyIntro:
	.string "Why would a BIRDKEEPER like me\n"
	.string "come out to the sea?$"

Route125_Text_PresleyDefeat:
	.string "Okay.\n"
	.string "I'll tell you why I'm here.$"

Route125_Text_PresleyPostBattle:
	.string "I put a message in a bottle and put\n"
	.string "it out to sea.\p"
	.string "I'm sure that a girl SWIMMER will\n"
	.string "find it!$"

Route125_Text_AuronIntro:
	.string "Hey! Was it you throwing garbage\n"
	.string "into the sea?$"

Route125_Text_AuronDefeat:
	.string "Oh, you weren't throwing trash into\n"
	.string "the sea.$"

Route125_Text_AuronPostBattle:
	.string "I found an unsightly bottle bobbing\n"
	.string "in the waves earlier.\p"
	.string "It angers me that someone would\n"
	.string "pollute the sea!$"

Route126_Text_BarryIntro:
	.string "Swimming is a full-body workout!\n"
	.string "You will get fit!$"

Route126_Text_BarryDefeat:
	.string "I admit it!\n"
	.string "You win!$"

Route126_Text_BarryPostBattle:
	.string "Thanks to my daily swimming routine…\n"
	.string "Look! Feast your eyes on this physique!$"

Route126_Text_DeanIntro:
	.string "This towering white mountain of rock\n"
	.string "is SOOTOPOLIS CITY.$"

Route126_Text_DeanDefeat:
	.string "I was done in?$"

Route126_Text_DeanPostBattle:
	.string "I can't find the entrance to\n"
	.string "SOOTOPOLIS. Where could it be?$"

Route126_Text_NikkiIntro:
	.string "Ufufufufu!\n"
	.string "I'm a mermaid!$"

Route126_Text_NikkiDefeat:
	.string "My fantasy burst as if it were a bubble!\n"
	.string "Blub, blub, blub…$"

Route126_Text_NikkiPostBattle:
	.string "You thrashed me… I want to\n"
	.string "disappear in a wave of despair…$"

Route126_Text_BrendaIntro:
	.string "Hello, kiddo!\n"
	.string "Want a battle with me?$"

Route126_Text_BrendaDefeat:
	.string "Oh, noooooh!$"

Route126_Text_BrendaPostBattle:
	.string "I love frolicking with POKéMON in\n"
	.string "the sea like this!$"

Route126_Text_PabloIntro:
	.string "Check out this sculpted body!\n"
	.string "I'm more cut than a BLACK BELT!$"

Route126_Text_PabloDefeat:
	.string "Whoops! Too strong!\n"
	.string "Not bad! Not bad at all!$"

Route126_Text_PabloPostBattle:
	.string "Losing to you stimulated my senses!\n"
	.string "I'll train myself and POKéMON harder!$"

Route126_Text_PabloRegister:
	.string "Yep, you're not bad at all!\n"
	.string "I'd like to get to know you more!$"

Route126_Text_PabloRematchIntro:
	.string "Check out this beautiful body!\n"
	.string "I'm more shapely than a SWIMMER!$"

Route126_Text_PabloRematchDefeat:
	.string "Whoops! Really too strong!\n"
	.string "Not bad! Not bad at all!$"

Route126_Text_PabloPostRematch:
	.string "I'm going to train even harder!\n"
	.string "You're a great motivator!\l"
	.string "You have to come back again!$"

Route126_Text_LeonardoIntro:
	.string "I couldn't even swim last year,\n"
	.string "but now I'm a decent SWIMMER.\p"
	.string "I think I'm capable of anything now.$"

Route126_Text_LeonardoDefeat:
	.string "Sheesh, getting greedy didn't do\n"
	.string "a thing for me.$"

Route126_Text_LeonardoPostBattle:
	.string "If you practice at something,\n"
	.string "you will get better at it.\p"
	.string "You're young--don't be afraid to\n"
	.string "try all sorts of things!$"

Route126_Text_IsobelIntro:
	.string "If seawater gets up your nose,\n"
	.string "doesn't it feel terrible?$"

Route126_Text_IsobelDefeat:
	.string "Ack! Why, you…\n"
	.string "Glub!$"

Route126_Text_IsobelPostBattle:
	.string "Ooh, I choked on some water!\n"
	.string "It's bitter! It's salty!!$"

Route126_Text_SiennaIntro:
	.string "I'm throwing my whole heart\n"
	.string "into this!$"

Route126_Text_SiennaDefeat:
	.string "You had more heart!$"

Route126_Text_SiennaPostBattle:
	.string "I need to cool down now…\n"
	.string "I think I'll go for a dive.$"

Route127_Text_CamdenIntro:
	.string "I can see it in your face.\n"
	.string "You want to challenge me.$"

Route127_Text_CamdenDefeat:
	.string "Awawawawawa…$"

Route127_Text_CamdenPostBattle:
	.string "A well-played match leaves me feeling\n"
	.string "refreshed and serene.$"

Route127_Text_DonnyIntro:
	.string "Do you have a rival whom you just\n"
	.string "hate to lose against?$"

Route127_Text_DonnyDefeat:
	.string "Arrrgh!\n"
	.string "I hate losing!$"

Route127_Text_DonnyPostBattle:
	.string "If you have a rival, don't you get the\n"
	.string "feeling that you have to keep getting\l"
	.string "better?$"

Route127_Text_JonahIntro:
	.string "Through fishing, I have attained a\n"
	.string "state of becalmed serenity…\p"
	.string "Please, allow me to demonstrate…$"

Route127_Text_JonahDefeat:
	.string "Though I have lost, my heart remains\n"
	.string "calm…$"

Route127_Text_JonahPostBattle:
	.string "It matters not that I catch nothing.\n"
	.string "The line remains in the water…$"

Route127_Text_HenryIntro:
	.string "Whoops! Don't tell me I snagged\n"
	.string "a SURFING POKéMON?$"

Route127_Text_HenryDefeat:
	.string "I can't keep up!$"

Route127_Text_HenryPostBattle:
	.string "It'd be a handful if I hooked\n"
	.string "your tough POKéMON!$"

Route127_Text_RogerIntro:
	.string "Well, hey! This is a match between\n"
	.string "a POKéMON fan and a fishing buff!$"

Route127_Text_RogerDefeat:
	.string "No! My line's all tangled!\n"
	.string "The party's over!$"

Route127_Text_RogerPostBattle:
	.string "My fishing line's doing a dance!\n"
	.string "The tangle tango! Hahaha, snarl!$"

Route127_Text_AidanIntro:
	.string "BIRD POKéMON have excellent vision.\n"
	.string "They spot prey from great heights.$"

Route127_Text_AidanDefeat:
	.string "Whew… I give up.$"

Route127_Text_AidanPostBattle:
	.string "There're lots of diving spots in\n"
	.string "the sea around here.\p"
	.string "You can spot them easily from the sky\n"
	.string "because of their darker color.$"

Route127_Text_KojiIntro:
	.string "Run in your bare feet.\n"
	.string "That will toughen up your soles!$"

Route127_Text_KojiDefeat:
	.string "Yowch!\n"
	.string "I got a pebble under a toenail!$"

Route127_Text_KojiPostBattle:
	.string "Going barefoot feels great.\n"
	.string "But your RUNNING SHOES are cool, too.$"

Route127_Text_KojiRegister:
	.string "This is what I do to people who beat me!\n"
	.string "I hope we can do this again.$"

Route127_Text_KojiRematchIntro:
	.string "I still run in my bare feet daily.\n"
	.string "My soles are tough!$"

Route127_Text_KojiRematchDefeat:
	.string "Yowch!\n"
	.string "Pebbles dug into my arches!$"

Route127_Text_KojiPostRematch:
	.string "Want to go barefoot for a while?\n"
	.string "So I can try your RUNNING SHOES?$"

Route127_Text_AthenaIntro:
	.string "We should have a slow and methodical\n"
	.string "match.$"

Route127_Text_AthenaDefeat:
	.string "You didn't give me the chance to\n"
	.string "do any strategizing.$"

Route127_Text_AthenaPostBattle:
	.string "When I'm surrounded by the blue sea\n"
	.string "and sky, it feels as if time slows down.$"

Route128_Text_IsaiahIntro:
	.string "EVER GRANDE CITY is still a long ways\n"
	.string "away…$"

Route128_Text_IsaiahDefeat:
	.string "My first victory seems to be far\n"
	.string "away, too…$"

Route128_Text_IsaiahPostBattle:
	.string "My whole life has been about losing,\n"
	.string "but I will never give up!$"

Route128_Text_IsaiahRegister:
	.string "I know I'm not good now, but I think\n"
	.string "I can win eventually.\p"
	.string "Please register me in your POKéNAV.$"

Route128_Text_IsaiahRematchIntro:
	.string "I'm still feeling good. I'll keep on\n"
	.string "swimming to EVER GRANDE CITY.$"

Route128_Text_IsaiahRematchDefeat:
	.string "I've yet to taste my first victory…$"

Route128_Text_IsaiahPostRematch:
	.string "I'll eventually reach EVER GRANDE CITY\n"
	.string "where I can eventually win…$"

Route128_Text_KatelynIntro:
	.string "You have to swim, cycle, and then run\n"
	.string "a marathon in a triathlon.\p"
	.string "It's a grueling race that consists\n"
	.string "of three events.$"

Route128_Text_KatelynDefeat:
	.string "A POKéMON battle is grueling, too…$"

Route128_Text_KatelynPostBattle:
	.string "I have to ride a BIKE next, but…\n"
	.string "I'm about to throw in the towel…$"

Route128_Text_KatelynRegister:
	.string "Well, I may as well make the best\n"
	.string "of this. I'd like a rematch sometime.$"

Route128_Text_KatelynRematchIntro:
	.string "A triathlon is long. But I guess the\n"
	.string "road to become the POKéMON CHAMPION\l"
	.string "is also a long and grueling one.$"

Route128_Text_KatelynRematchDefeat:
	.string "A POKéMON battle really is harsh\n"
	.string "and unforgiving…$"

Route128_Text_KatelynPostRematch:
	.string "You should give serious thought to\n"
	.string "challenges on VICTORY ROAD.$"

Route128_Text_AlexaIntro:
	.string "We've been working so hard to mount\n"
	.string "a POKéMON LEAGUE challenge…\p"
	.string "We can't afford to lose now!$"

Route128_Text_AlexaDefeat:
	.string "Oh!\n"
	.string "How could this happen?!$"

Route128_Text_AlexaPostBattle:
	.string "After all I've done to get here,\n"
	.string "I won't give up after one setback.$"

Route128_Text_RubenIntro:
	.string "There is no stronger TRAINER than I!$"

Route128_Text_RubenDefeat:
	.string "This can't be!$"

Route128_Text_RubenPostBattle:
	.string "There probably is no stronger TRAINER\n"
	.string "than you!$"

Route128_Text_WayneIntro:
	.string "I want to visit EVER GRANDE, so I\n"
	.string "caught myself a POKéMON that knows\l"
	.string "the move WATERFALL to crest the falls.$"

Route128_Text_WayneDefeat:
	.string "I'm crestfallen!$"

Route128_Text_WaynePostBattle:
	.string "Awww, phooey!\p"
	.string "My POKéMON knows WATERFALL, but\n"
	.string "I don't have the SOOTOPOLIS GYM BADGE!$"

Route128_Text_HarrisonIntro:
	.string "You're looking awfully tough.\n"
	.string "I wonder if I can win?$"

Route128_Text_HarrisonDefeat:
	.string "Ouch!\n"
	.string "I guess it was impossible to win.$"

Route128_Text_HarrisonPostBattle:
	.string "There are tough TRAINERS galore\n"
	.string "around EVER GRANDE.\p"
	.string "Do you think I may be out\n"
	.string "of my league?$"

Route128_Text_CarleeIntro:
	.string "The sunlight seems to be more harsh\n"
	.string "in this area.$"

Route128_Text_CarleeDefeat:
	.string "I couldn't see very well because of\n"
	.string "the sun's glare.$"

Route128_Text_CarleePostBattle:
	.string "I should go back soon.\n"
	.string "I need to reapply my sunscreen.$"

Route129_Text_ChaseIntro:
	.string "This is my first triathlon.\n"
	.string "I'm all tense and nervous!$"

Route129_Text_ChaseDefeat:
	.string "Wroooaaar!\n"
	.string "I failed to win!$"

Route129_Text_ChasePostBattle:
	.string "If I'm all tensed up, I won't be able to\n"
	.string "give it my all.$"

Route129_Text_AllisonIntro:
	.string "I'm in the middle of a triathlon,\n"
	.string "but, sure, why don't we battle?$"

Route129_Text_AllisonDefeat:
	.string "I was sure I'd win!$"

Route129_Text_AllisonPostBattle:
	.string "Do you know what's the greatest thing\n"
	.string "about triathlons?\p"
	.string "Testing the limits of your own\n"
	.string "strength and endurance against\l"
	.string "Mother Nature!$"

Route129_Text_ReedIntro:
	.string "Say hey, hey!\n"
	.string "Let's get on with it!$"

Route129_Text_ReedDefeat:
	.string "Beat, I'm beaten.\n"
	.string "That's it, done!$"

Route129_Text_ReedPostBattle:
	.string "There's nothing for a loser.\n"
	.string "Time for me to beat it home.$"

Route129_Text_TishaIntro:
	.string "What's the hurry?\n"
	.string "Let's take it slow and easy.$"

Route129_Text_TishaDefeat:
	.string "Oh, my.\n"
	.string "I wanted to relax a little more…$"

Route129_Text_TishaPostBattle:
	.string "Don't you hate making mistakes when\n"
	.string "you're in a rush?\p"
	.string "That's why I try to take things\n"
	.string "slowly.$"

Route129_Text_ClarenceIntro:
	.string "Surfing isn't as easy as it seems,\n"
	.string "isn't that right?$"

Route129_Text_ClarenceDefeat:
	.string "Winning sure isn't easy.$"

Route129_Text_ClarencePostBattle:
	.string "You have your sights on the POKéMON\n"
	.string "LEAGUE? Keep at it!$"

Route130_Text_RodneyIntro:
	.string "What a surprise! I didn't expect to\n"
	.string "see a TRAINER out in the sea.\p"
	.string "I think we should battle!$"

Route130_Text_RodneyDefeat:
	.string "This kid's awfully tough…$"

Route130_Text_RodneyPostBattle:
	.string "Your eyes have that look of someone\n"
	.string "who's experienced harsh challenges\l"
	.string "and won. It suits you well!$"

Route130_Text_KatieIntro:
	.string "In the deep blue sea,\n"
	.string "my shattered blue heart finds\l"
	.string "comfort among waves.$"

Route130_Text_KatieDefeat:
	.string "Like the vast blue sea,\n"
	.string "the world of POKéMON spans\l"
	.string "depths beyond belief.$"

Route130_Text_KatiePostBattle:
	.string "The world's children dream\n"
	.string "of one day becoming\l"
	.string "the POKéMON CHAMPION.$"

Route130_Text_SantiagoIntro:
	.string "Floating on the open sea like this…\n"
	.string "It's peaceful.$"

Route130_Text_SantiagoDefeat:
	.string "I needed to be a little less peaceful!$"

Route130_Text_SantiagoPostBattle:
	.string "Swimming and battling like this…\n"
	.string "I'm one happy guy…$"

Route131_Text_RichardIntro:
	.string "The sea is teeming with POKéMON.\n"
	.string "It's not easy swimming, I tell you.$"

Route131_Text_RichardDefeat:
	.string "POKéMON raised by TRAINERS are\n"
	.string "seriously tough…$"

Route131_Text_RichardPostBattle:
	.string "Gasp… Gasp…\n"
	.string "I'm wiped out…\p"
	.string "The going's easy. It's the leaving\n"
	.string "that's the hard part.\p"
	.string "Will I have any energy left to make\n"
	.string "the return trip?$"

Route131_Text_HermanIntro:
	.string "The sea… The sea… The sea…\n"
	.string "The sea as far as these eyes can see!\l"
	.string "I'm sick and tired of the sea!$"

Route131_Text_HermanDefeat:
	.string "Bleah!$"

Route131_Text_HermanPostBattle:
	.string "Bored I am by the sea, but swim I must.\p"
	.string "I'm a born swimmer!\n"
	.string "That's what I am.$"

Route131_Text_SusieIntro:
	.string "Hi, sweetie, wait!\n"
	.string "We should battle, you and I!$"

Route131_Text_SusieDefeat:
	.string "You're tough in spite of the way\n"
	.string "you look!$"

Route131_Text_SusiePostBattle:
	.string "Did you see a guy over there who whines\n"
	.string "that he's bored of the sea?\p"
	.string "That's all talk.\n"
	.string "He's hopelessly in love with the sea!$"

Route131_Text_KaraIntro:
	.string "Why do men love bathing suits so much?\p"
	.string "They all ogle me!$"

Route131_Text_KaraDefeat:
	.string "I'm out of my depth!$"

Route131_Text_KaraPostBattle:
	.string "Maybe it's not my bathing suit that\n"
	.string "makes men look. It must be my beauty!$"

Route131_Text_ReliIntro:
	.string "RELI: We'll work together as siblings\n"
	.string "to take you on!$"

Route131_Text_ReliDefeat:
	.string "RELI: We couldn't win even though we\n"
	.string "worked together…$"

Route131_Text_ReliPostBattle:
	.string "RELI: The people of PACIFIDLOG are\n"
	.string "together with the sea and POKéMON from\l"
	.string "the time they are born.$"

Route131_Text_ReliNotEnoughMons:
	.string "RELI: You don't have two POKéMON?\n"
	.string "We can't enjoy a battle, then.$"

Route131_Text_IanIntro:
	.string "IAN: I'm doing my best together with\n"
	.string "my sis!$"

Route131_Text_IanDefeat:
	.string "IAN: I did my best with my sis,\n"
	.string "but we still couldn't win…$"

Route131_Text_IanPostBattle:
	.string "IAN: You know how PACIFIDLOG is\n"
	.string "a floating town?\p"
	.string "So, wherever there is the sea,\n"
	.string "that's a part of PACIFIDLOG!$"

Route131_Text_IanNotEnoughMons:
	.string "IAN: If you have two POKéMON,\n"
	.string "we'll take you on!$"

Route131_Text_TaliaIntro:
	.string "If you can beat me, I'll give you some\n"
	.string "great information!$"

Route131_Text_TaliaDefeat:
	.string "Oh?\n"
	.string "Did I lose?$"

Route131_Text_TaliaPostBattle:
	.string "There is an odd place nearby.\n"
	.string "There's a huge tower there.\l"
	.string "Why don't you go take a look?$"

Route131_Text_KevinIntro:
	.string "The people of PACIFIDLOG are\n"
	.string "a peaceful bunch.\p"
	.string "They never get angry.\n"
	.string "That goes for me, too.$"

Route131_Text_KevinDefeat:
	.string "Oops!$"

Route131_Text_KevinPostBattle:
	.string "Tch! …Oh, wait.\n"
	.string "I'm not angry. Honestly!\p"
	.string "But, boy, you're strong!\n"
	.string "Hahaha!$"

Route132_Text_GilbertIntro:
	.string "I used to catch colds all the time as\n"
	.string "a kid, but I became totally fit after\l"
	.string "I started swimming.$"

Route132_Text_GilbertDefeat:
	.string "I crave more power…$"

Route132_Text_GilbertPostBattle:
	.string "TRAINERS travel the fields and\n"
	.string "mountains, so they must be fit, too.$"

Route132_Text_DanaIntro:
	.string "I try not to swim where the currents\n"
	.string "are too strong.$"

Route132_Text_DanaDefeat:
	.string "Oh, please, no!$"

Route132_Text_DanaPostBattle:
	.string "If I get swept away, I'll lose all my\n"
	.string "sense of place…$"

Route132_Text_RonaldIntro:
	.string "Win or lose, you'll never know until\n"
	.string "you try!$"

Route132_Text_RonaldDefeat:
	.string "Waah!\n"
	.string "I sank in defeat!$"

Route132_Text_RonaldPostBattle:
	.string "I never battle when I know I'll win.\n"
	.string "I like to battle at the razor's edge of\l"
	.string "victory and defeat!$"

Route132_Text_KiyoIntro:
	.string "I contemplate POKéMON 24 hours a day.\n"
	.string "How could you possibly beat me?$"

Route132_Text_KiyoDefeat:
	.string "I lose.\n"
	.string "I will concede defeat.$"

Route132_Text_KiyoPostBattle:
	.string "Urggh…\n"
	.string "You're a POKéMON fanatic, aren't you?\p"
	.string "You must contemplate POKéMON 24 hours\n"
	.string "a day, don't you?$"

Route132_Text_MakaylaIntro:
	.string "I'm always with my husband,\n"
	.string "but I can win even without him.$"

Route132_Text_MakaylaDefeat:
	.string "Oh, I guess I wasn't good enough.$"

Route132_Text_MakaylaPostBattle:
	.string "That young man over there looks just\n"
	.string "like my husband when he was young.\p"
	.string "He's making me blush!$"

Route132_Text_JonathanIntro:
	.string "Someone's been watching me intently.\n"
	.string "Was it you?$"

Route132_Text_JonathanDefeat:
	.string "Wow!\n"
	.string "That's pretty strong, all right!$"

Route132_Text_JonathanPostBattle:
	.string "I can't shake this feeling that\n"
	.string "someone's watching me.\p"
	.string "I can't concentrate!$"

Route132_Text_PaxtonIntro:
	.string "Now where could my wife have gone?\n"
	.string "I'm always with her.\l"
	.string "I wonder if I can win on my own.$"

Route132_Text_PaxtonDefeat:
	.string "Ah, I see that I couldn't manage\n"
	.string "to win on my own after all.$"

Route132_Text_PaxtonPostBattle:
	.string "My wife must be looking for me.\n"
	.string "I'd best go find her right away.$"

Route132_Text_DarcyIntro:
	.string "I liked training here by myself.\n"
	.string "It's awful that all these people came!$"

Route132_Text_DarcyDefeat:
	.string "Okay! I won't complain about other\n"
	.string "people being here.$"

Route132_Text_DarcyPostBattle:
	.string "I suppose I can partner up with that\n"
	.string "old man and challenge that other team.$"

Route133_Text_FranklinIntro:
	.string "Did the currents carry you here, too?\n"
	.string "This must have been fated.\l"
	.string "Let's battle!$"

Route133_Text_FranklinDefeat:
	.string "Strong!\n"
	.string "Too much so!$"

Route133_Text_FranklinPostBattle:
	.string "It's just my luck that a tough TRAINER\n"
	.string "like you would drift here…\l"
	.string "I must be cursed…$"

Route133_Text_DebraIntro:
	.string "I've led a life of woe and misery…\n"
	.string "I've been cast away, and this is where\l"
	.string "I've drifted…$"

Route133_Text_DebraDefeat:
	.string "Another loss…$"

Route133_Text_DebraPostBattle:
	.string "A life adrift…\n"
	.string "I don't want it anymore!$"

Route133_Text_LindaIntro:
	.string "Welcome!\n"
	.string "I've been expecting you!$"

Route133_Text_LindaDefeat:
	.string "No! Please!$"

Route133_Text_LindaPostBattle:
	.string "A strong child TRAINER…\n"
	.string "That's so annoying!$"

Route133_Text_WarrenIntro:
	.string "I want to win like everyone else, but I\n"
	.string "won't raise POKéMON like everyone else.$"

Route133_Text_WarrenDefeat:
	.string "Darn it!\n"
	.string "My way is still too slack!$"

Route133_Text_WarrenPostBattle:
	.string "It's way more fun to do things the way\n"
	.string "I want than to be like everybody else.\l"
	.string "I mean, that's obvious!$"

Route133_Text_BeckIntro:
	.string "I came all the way out here with my\n"
	.string "BIRD POKéMON.$"

Route133_Text_BeckDefeat:
	.string "You…\n"
	.string "You're stunningly cool!$"

Route133_Text_BeckPostBattle:
	.string "I'd like to go back to FORTREE,\n"
	.string "but I've grown to like this place, too.$"

Route133_Text_MollieIntro:
	.string "I must have battled thousands\n"
	.string "of times. I've lost count.$"

Route133_Text_MollieDefeat:
	.string "I may have lost thousands of times,\n"
	.string "but a loss still stings.$"

Route133_Text_MolliePostBattle:
	.string "Keep at this, youngster. So you can\n"
	.string "become like my husband and me.$"

Route133_Text_ConorIntro:
	.string "Young people are too happy to go with\n"
	.string "the flow. They're without direction.$"

Route133_Text_ConorDefeat:
	.string "You have a firm sense of purpose.$"

Route133_Text_ConorPostBattle:
	.string "Don't let others lead you astray.\n"
	.string "Don't lose direction as you grow older.$"

Route134_Text_JackIntro:
	.string "Even those POKéMON that can swim are\n"
	.string "carried along by the rapid currents.$"

Route134_Text_JackDefeat:
	.string "Aiyeeeeh!$"

Route134_Text_JackPostBattle:
	.string "I think POKéMON enjoy the fast-running\n"
	.string "currents around these parts.$"

Route134_Text_LaurelIntro:
	.string "My LUVDISC are looking for a fun\n"
	.string "match. Will you join us?$"

Route134_Text_LaurelDefeat:
	.string "Oopsie!$"

Route134_Text_LaurelPostBattle:
	.string "There's a collector who's after\n"
	.string "the SCALES of LUVDISC.$"

Route134_Text_AlexIntro:
	.string "Okeydokey! That's enough rest, gang!\n"
	.string "It's time for a match!$"

Route134_Text_AlexDefeat:
	.string "Tuckered out again…$"

Route134_Text_AlexPostBattle:
	.string "My BIRD POKéMON get tired quickly after\n"
	.string "a long flight…$"

Route134_Text_HitoshiIntro:
	.string "You're a POKéMON TRAINER.\n"
	.string "No need for words. We battle now.$"

Route134_Text_HitoshiDefeat:
	.string "… … … … … …\n"
	.string "… … … … … …$"

Route134_Text_HitoshiPostBattle:
	.string "It was I who challenged you, and yet\n"
	.string "I lost. I am deeply shamed…$"

Route134_Text_AaronIntro:
	.string "The savage tide in this area serves to\n"
	.string "make us stronger than ever.$"

Route134_Text_AaronDefeat:
	.string "I willingly concede defeat.$"

Route134_Text_AaronPostBattle:
	.string "We will return for more training at\n"
	.string "METEOR FALLS.\p"
	.string "If you'd like, you should go, too.\n"
	.string "It will definitely toughen you up!$"

Route134_Text_KelvinIntro:
	.string "O-our boat!\n"
	.string "The tide carried it away!$"

Route134_Text_KelvinDefeat:
	.string "Awawawawah!\n"
	.string "Please, stop! Please!$"

Route134_Text_KelvinPostBattle:
	.string "If we can't SURF, how are we supposed\n"
	.string "to get home?\p"
	.string "Actually, I know a fainted POKéMON\n"
	.string "can still SURF, but it feels wrong.$"

Route134_Text_MarleyIntro:
	.string "Can your POKéMON dodge our\n"
	.string "lightning-quick attacks?$"

Route134_Text_MarleyDefeat:
	.string "I never knew such a technique existed!\n"
	.string "You've defeated us thoroughly.$"

Route134_Text_MarleyPostBattle:
	.string "I haven't lost my passion for speed.\n"
	.string "I will try harder.$"

Route134_Text_ReynaIntro:
	.string "My POKéMON can't be taken down\n"
	.string "easily!$"

Route134_Text_ReynaDefeat:
	.string "You're kidding!\n"
	.string "Explain how I lost!$"

Route134_Text_ReynaPostBattle:
	.string "Haha!\n"
	.string "You won, all right!\p"
	.string "I'll work my way back up by taking on\n"
	.string "TRAINERS I happen to meet!$"

Route134_Text_HudsonIntro:
	.string "Listen, have you seen another SAILOR\n"
	.string "around here?$"

Route134_Text_HudsonDefeat:
	.string "Now, that's something!$"

Route134_Text_HudsonPostBattle:
	.string "Our boat drifted out to sea.\p"
	.string "My buddy's a timid fellow, so I'm\n"
	.string "worried about him.$"
