LilycoveCity_ContestLobby_Text_InterviewRequest:
	.string "Kaixo! Zu POKéMON LEHIAKETA\n"
	.string "batean egon zara, ezta?\l"
	.string "Zure POKéMONAK ikusita, erraza da jakiten.\p"
	.string "Kazetaria naiz. POKéMON LEHIAKETEN\n"
	.string "inguruko erreportaia batekin ari naiz.\p"
	.string "Inporta zaizu galdera batzuk egingo\n"
	.string "banizkizu honen inguruan?$"

LilycoveCity_ContestLobby_Text_DescribeContest:
	.string "Bai, benetan?\n"
	.string "Eskerrik asko.\p"
	.string "Labur-labur, nola deskribatuko zenuke\n"
	.string "sartu berri zaren LEHIAKETA?$"

LilycoveCity_ContestLobby_Text_WhatImageWhenYouHearX:
	.string "Ongi, ongi.\n"
	.string "Iruzkin interesgarria, alajaina.\p"
	.string "Ulertu dezaket nolakoa izan zen\n"
	.string "LEHIAKETA, gutxi gorabehera.\p"
	.string "Azken galdera bat.\p"
	.string "“{STR_VAR_2}” hitza entzutean,\n"
	.string "zein irudi datorkizu burura?$"

LilycoveCity_ContestLobby_Text_ThatsAllForInterview:
	.string "Ederki!\p"
	.string "Beraz, “{STR_VAR_2}” kontzeptua\n"
	.string "hala interpretatzen duzu.\p"
	.string "Mila esker!\n"
	.string "Ideia onak eman dizkidazu.\p"
	.string "Esango nuke orain idatzi dezakedala\n"
	.string "POKéMON LEHIAKETEN inguruko istorio on bat.\p"
	.string "Beharbada, zorte pixkatekin telebistan ere\n"
	.string "ateratzea lortu nezake.\l"
	.string "Espero dut zu ere irrikan egongo zarela!$"

LilycoveCity_ContestLobby_Text_PleaseDoShareStoryWithMe:
	.string "Ene, ze pena…\p"
	.string "Bueno, istorio onen bat topatzen baduzu,\n"
	.string "mesedez, konta iezadazu.$"

LilycoveCity_ContestLobby_Text_LookingForwardToNextContest:
	.string "Zure hurrengo POKéMON LEHIAKETAREN\n"
	.string "zain egongo naiz.$"

gTVBravoTrainerText00::
	.string "Yeah!\n"
	.string "Iritsi da ENTRENATZAILE AUSARTAREN garaia!\p"
	.string "Gaurkoan, {STR_VAR_1}(r)en POKéMON\n"
	.string "bat aztertuko dugu.\p"
	.string "POKéMON honek {STR_VAR_3} maila dauka\n"
	.string "{STR_VAR_2} kategorian.$"

gTVBravoTrainerText01::
	.string "Zuekin guztiokin {STR_VAR_2}\n"
	.string "{STR_VAR_1}!\p"
	.string "{STR_VAR_2} ezizenak…\p"
	.string "Ezizenak berak transmititzen du\n"
	.string "nolabaiteko “{STR_VAR_3}”!$"

gTVBravoTrainerText02::
	.string "Bueno, {STR_VAR_1} ENTRENATZAILEAK\n"
	.string "POKéMONA LEHIAKETAN sartu zuenean,\l"
	.string "bere lagunaren gaineko esaldi bat\l"
	.string "edo beste atera genion.$"

gTVBravoTrainerText03::
	.string "LEHIAKETAREN ondoren, honen inguruan\n"
	.string "galdetzean {STR_VAR_1}(e)k alai erantzun\l"
	.string "zigun, “{STR_VAR_2}!”\p"
	.string "Bueno, noski, {STR_VAR_1}(r)en POKéMONA\n"
	.string "{STR_VAR_3}. postuan gelditu zen LEHIAKETAN.\p"
	.string "Esan ziguna guztiz bat doa\n"
	.string "{STR_VAR_1}(r)ekin, nire iritziz!$"

gTVBravoTrainerText04::
	.string "LEHIAKETAREN ondoren, honen inguruan\n"
	.string "galdetzean {STR_VAR_1}(e)k erdi minduta\l"
	.string "erantzun zigun, “{STR_VAR_2}.”\p"
	.string "Beno, noski, {STR_VAR_1}(e)n POKéMONA\n"
	.string "{STR_VAR_3}. postuan gelditu zen LEHIAKETAN.\p"
	.string "{STR_VAR_1}(r)en nahigabea argi eta garbi\n"
	.string "ikusi eta entzun daiteke!$"

gTVBravoTrainerText05::
	.string "Jakin nahi duzue {STR_VAR_1}(r)entzat\n"
	.string "zer irudkatzen duen {STR_VAR_2}(e)k?\p"
	.string "Guk bai, bederen!\n"
	.string "Eta galdetu egin genion!\p"
	.string "Erantzun hau eman zigun:\n"
	.string "“{STR_VAR_3}!”\p"
	.string "{STR_VAR_2} kontzeptuak esanahi hau\n"
	.string "dauka {STR_VAR_1}(r)entzat!$"

gTVBravoTrainerText06::
	.string "{STR_VAR_1}(e)k erabilitako azken\n"
	.string "{STR_VAR_2} erasoaren esanahia\l"
	.string "“{STR_VAR_3}” da duda izpirik gabe!$"

gTVBravoTrainerText07::
	.string "Bejondeizula, {STR_VAR_1}!\n"
	.string "Bejondeizula, {STR_VAR_2}!\p"
	.string "Espero dugu hemendik aurrera\n"
	.string "{STR_VAR_1} gehiagotan ikusiko dugula!\p"
	.string "Eta hementxe bukatzen da gure programa!\n"
	.string "Hurrengora arte, agur!$"

gTVBravoTrainerText08::
	.string "Zuekin, ENTRENATZAILEAREN {STR_VAR_1}(a)!$"

BattleFrontier_BattleTowerLobby_Text_InterviewRequest::
	.string "Kaixo! Zu zara borroka izan berri duen\n"
	.string "ENTRENATZAILEA, ezta?\p"
	.string "ENTRENATZAILEEKIN elkarrizketak\n"
	.string "bildu eta bildu ari naiz.\p"
	.string "Borrokan izandako inpresioen gaineko\n"
	.string "galdera batzuk erantzuterik bai?$"

BattleFrontier_BattleTowerLobby_Text_HowDidBattleTowerTurnOut::
	.string "Bai? benetan?\n"
	.string "Eskerrik asko!\l"
	.string "Orduan…\p"
	.string "Zer moduz jazo dira BORROKA\n"
	.string "DORREKO kontuak gaur?\p"
	.string "Pozik gelditu zara egindako borrokarekin?\n"
	.string "Edo hobe egin zenezakeela uste duzu?$"

BattleFrontier_BattleTowerLobby_Text_SorryWeDisturbedYou::
	.string "Bueno…\n"
	.string "Barkatu molestatu badizugu.\p"
	.string "BORROKA DORRERA berriro zatozenean\n"
	.string "ea hobe datrokizun elkarrizketatxo bat.$"

BattleFrontier_BattleTowerLobby_Text_ObviousYouHadGreatBattle::
	.string "Bai, noski!\p"
	.string "Zure aurpegian argi eta garbi ikus\n"
	.string "daiteke gustora zaudela…\p"
	.string "Agerikoa da pozik gelditu zarela\n"
	.string "egindako borrokarekin.$"

BattleFrontier_BattleTowerLobby_Text_DifficultToMakeBattleTurnOutAsPlanned::
	.string "Oh, noski…\p"
	.string "Bueno, nahiko zaila izan ohi da borroka\n"
	.string "bat planifikatu bezain ondo irtetea.$"

BattleFrontier_BattleTowerLobby_Text_DescribeYourBattle::
	.string "Oh, oh, beste galdera bat egin diezazuket?\p"
	.string "Borroka honen inguruko inpresioa\n"
	.string "hitz bakar batean laburbildu beharko bazenu,\l"
	.string "zein hitz aukeratuko zenuke?$"

BattleFrontier_BattleTowerLobby_Text_ThatsGreatLine::
	.string "Oh, hori oso ederra da!\p"
	.string "Zein aukeraketa ona!\n"
	.string "Hurrengoan ere ederki ibiliko zarela espero dut.\p"
	.string "Hurrengora arte!$"

BattleFrontier_BattleTowerLobby_Text_SilentType::
	.string "Oh, ados…\p"
	.string "Isila baldin bazara, hori ere guztiz\n"
	.string "onargarria da, egia esanda.\p"
	.string "Beharbada hurrengo batean kontatuko\n"
	.string "didazu ea nola ibili zaren!$"

BattleFrontier_BattleTowerLobby_Text_LookingForwardToNextBattle::
	.string "Zure hurrengo borrokaren zain\n"
	.string "geratuko naiz, orduan!$"

BravoTrainerBattleTower_Text_Intro::
	.string "Bai!\n"
	.string "ENTRENATZAILE AUSARTAREN garaia da!\p"
	.string "Gaurkoan, {STR_VAR_1} baloratuko dugu,\n"
	.string "BATAILA DORREKO erroka egin berri duena!\p"
	.string "Erronkan, {STR_VAR_1}(e)k {STR_VAR_2}\n"
	.string "bat erabili zuen.$"

BravoTrainerBattleTower_Text_NewRecord::
	.string "Bikoteak errekor berria egin zuen: {STR_VAR_2}\n"
	.string "garaipen jarraian {STR_VAR_1} txapelketan!\l"
	.string "Zorionak, ENTRENATZAILE!$"

BravoTrainerBattleTower_Text_Lost::
	.string "Bikoteak, azkenean {STR_VAR_1}(r)en\n"
	.string "kontra galdu zuen, {STR_VAR_2}. borrokan.\l"
	.string "Ondo jokatuta, ENTRENATZAILE!\p"
	.string "Baina, aizue, erronak horren azkar\n"
	.string "{STR_VAR_1} bat tokatzea zorte txarra da.\p"
	.string "ENTRENATZAILEARI bere {STR_VAR_1}(r)en aurkako\n"
	.string "borrokako inpresioen inguruan galdetu genion.$"

BravoTrainerBattleTower_Text_Won::
	.string "Bikoteak garaipena etxeratu zuen\n"
	.string "{STR_VAR_1}(r)en {STR_VAR_2}ari irabazita.\l"
	.string "Zorionak, ENTRENATZAILE!\p"
	.string "{STR_VAR_1}(e)ri irabaztea…\n"
	.string "Sinesgaitza da ia-ia! Izugarria, benetan!\p"
	.string "Garaipen momentuaren inguruan galdetu\n"
	.string "genion ENTRENATZAILEARI.$"

BravoTrainerBattleTower_Text_LostFinal::
	.string "Garaipen sortaren ondoren, azkenean bikoteak\n"
	.string "{STR_VAR_1}(r)en {STR_VAR_2}aren aurka galdu zuen,\l"
	.string "beraien azken erronka.\p"
	.string "Ondo jokatuta, ENTRENATZAILE!\p"
	.string "Meritu handia dauka.\n"
	.string "Ez da askotan ikusten {STR_VAR_1}\l"
	.string "eta {STR_VAR_2} bezalako konbinaziorik.\p"
	.string "Bikote famatuaren aurka borrokatzearen\n"
	.string "inguruan galdetu genion ENTRENATZAILEARI.$"

BravoTrainerBattleTower_Text_Satisfied::
	.string "Honakoa esan zigun ENTRENATZAILEAK:\n"
	.string "“Gustora geratu naiz!”\p"
	.string "Erantzun bikaina, alajaina!\n"
	.string "Zorionak, ENTRENATZAILE!\p"
	.string "Ez al da zirraragarria borroka\n"
	.string "gogo biziz egin eta gustura geratzea?\p"
	.string "ENTRENATZAILEA gustura geratu zela\n"
	.string "konturatu nintzen hau esan zidanean:$"

BravoTrainerBattleTower_Text_Unsatisfied::
	.string "Hau esan zidan ENTRENATZAILEAK:\n"
	.string "“Ez naiz gustura geratu…”\p"
	.string "ENTRENATZAILEA nahikoa triste zegoen\n"
	.string "hori esan zuenean.\p"
	.string "Hala ere, ez da erraza borrokatu eta\n"
	.string "guztiz gustora geratzea, ez da hala?\p"
	.string "Beno, ENTRENATZAILEA gustora geratu\n"
	.string "ez zela jakin nuen hau esan zuenean:$"

BravoTrainerBattleTower_Text_None1::
	.string "Ezer ez$"

BravoTrainerBattleTower_Text_None2::
	.string "Ezer ez$"

BravoTrainerBattleTower_Text_None3::
	.string "Ezer ez$"

BravoTrainerBattleTower_Text_None4::
	.string "Ezer ez$"

BravoTrainerBattleTower_Text_Response::
	.string "“{STR_VAR_1}.”$"

BravoTrainerBattleTower_Text_ResponseSatisfied::
	.string "“{STR_VAR_1}.”\n"
	.string "Ez al da itzela?\p"
	.string "Guztiz espresatzen du {STR_VAR_2}(r)en\n"
	.string "grina, esango nuke.\p"
	.string "{STR_VAR_3}(r)en aurkako borroka\n"
	.string "amaieran… “{STR_VAR_1}” deituko nioke\l"
	.string "nik horri, dudarik gabe!$"

BravoTrainerBattleTower_Text_ResponseUnsatisfied::
	.string "“{STR_VAR_1}.”\n"
	.string "Ez al da bereziki egokia?\p"
	.string "{STR_VAR_3}(r)en aurkako borroka\n"
	.string "amaieran… Deskribatzkeo hitzik egokiena\l"
	.string "“{STR_VAR_1}” da, ezbairik gabe!\p"
	.string "{STR_VAR_2}(r)en nahigabea argi eta garbi\n"
	.string "ikusi eta entzun daiteke!$"

BravoTrainerBattleTower_Text_Outro::
	.string "Bejondeizula, {STR_VAR_1}!\n"
	.string "Bejondeizula, {STR_VAR_2}!\p"
	.string "Espero dut hemendik aurrera\n"
	.string "{STR_VAR_1} gehiagotan ikusiko dugula!\p"
	.string "Eta hementxe bukatzen da gure programa!\n"
	.string "Hurrengora arte, agur!$"

SlateportCity_PokemonFanClub_Text_InterviewRequestHasName:
	.string "Wow!\p"
	.string "Argi eta garbi dago asko maite duzula\n"
	.string "zure {STR_VAR_1}.\p"
	.string "Ongi, {STR_VAR_2} izena du.\p"
	.string "Mesede bat eska diezazuket?\p"
	.string "Telebistako kazetaria naiz eta\n"
	.string "POKéMONEN inguruko galdetegi bat daukat.\p"
	.string "Erantzungo zenizkidake pare bat\n"
	.string "galdera erraz?$"

SlateportCity_PokemonFanClub_Text_HereGoesQuickAnswers:
	.string "Bikain! Eskerrik asko!\p"
	.string "Ados, hemen doaz.\n"
	.string "Erantzun azkarrak behar ditut, ados?$"

SlateportCity_PokemonFanClub_Text_DescribeFeelingsFirstMetMon:
	.string "Lehen aldiz {STR_VAR_1} ezagutu zenuenean,\n"
	.string "Nola sentitu zinen?\p"
	.string "Nola deskribatuko zenuke momentu hartan\n"
	.string "sentitu zenuena?$"

SlateportCity_PokemonFanClub_Text_LikenMonToSomethingYouLike:
	.string "Zure {STR_VAR_1} maitasun handiz zaindu duzu.\p"
	.string "Gustuko duzun zerbaitekin alderatu\n"
	.string "beharko bazenu, zer izango litzateke?$"

SlateportCity_PokemonFanClub_Text_WhatAttractedYouAboutMon:
	.string "Galdera hau ere zure {STR_VAR_1} maitearen\n"
	.string "inguruan da.\p"
	.string "Zer gustatu zitzaizun gehien\n"
	.string "{STR_VAR_1} ezagutu zenuenean?$"

SlateportCity_PokemonFanClub_Text_WhatDoPokemonMeanToYou:
	.string "Noski, horrek zentzua du.\p"
	.string "Hurrengo galdera pixka bat zailagoa\n"
	.string "izan daiteke.\p"
	.string "Hementxe…\p"
	.string "Zuretzat zer dira POKéMONAK?$"

SlateportCity_PokemonFanClub_Text_ThatsAllForInterview:
	.string "Ederki!\p"
	.string "Hmhm…\p"
	.string "Ados!\n"
	.string "Eskerrik asko zure laguntzagatik.\p"
	.string "Zurekin hitz egitea dibertigarria\n"
	.string "eta argigarria izan da.\p"
	.string "Agian gure elkarrizketa telebistan\n"
	.string "agertuko da. Begiratu ezazu hurrengoan!\p"
	.string "Ongi, hori zen guztia.\n"
	.string "Aio-aio!$"

SlateportCity_PokemonFanClub_Text_HereIfYouGetUrgeToTellMe:
	.string "Oh, ados…\p"
	.string "Beno, hurrengoan nirekin POKéMONEN inguruan\n"
	.string "hitz egin nahi baduzu, lasai etorri!$"

SlateportCity_PokemonFanClub_Text_EnjoyDoingInterviews:
	.string "Gustuko dut nire lana. Elkarrizketekin\n"
	.string "POKéMONEN inguruan asko ikasten dut.$"

SlateportCity_PokemonFanClub_Text_InterviewRequest:
	.string "Kaixo, badirudi asko maite duzula zure\n"
	.string "{STR_VAR_1}.\p"
	.string "Badakizu zer?\n"
	.string "Telebistako kazetaria naiz.\p"
	.string "Munduan zehar bidaiatzen dut jendea\n"
	.string "POKéMONEN inguruan elkarrizketatzeko.\p"
	.string "Zure {STR_VAR_1}(r)en inguruan zerbait\n"
	.string "kontatuko zenidake?$"

SlateportCity_PokemonFanClub_Text_TellMeAnythingAboutYourMon:
	.string "Uau, eskerrik asko!\p"
	.string "Ongi, orduan knota iezadazu zure\n"
	.string "{STR_VAR_1}(r)en inguruan gustuko duzun edozer.$"

SlateportCity_PokemonFanClub_Text_ThatsAllForInterview2:
	.string "uau…\n"
	.string "Oso interesgarria da hori.\p"
	.string "Asko maite duzu {STR_VAR_1},\n"
	.string "ezta?\p"
	.string "Esango nuke kontatu didazuna\n"
	.string "telebistarako oso egokia dela.\p"
	.string "Zin egiten dizut, material honekin\n"
	.string "istorio entretenigarri bat idatziko dut.\l"
	.string "Egon adi telebistari.\p"
	.string "Hori zen guztia.\n"
	.string "Aio-aio!$"

gTVFanClubOpinionsText00::
	.string "POKéMON FAN TALDEA GARA!\p"
	.string "Zuzenean gaude oraintxe!\p"
	.string "Programa honetan zuen iritziak bildu\n"
	.string "eta zuen ordez oihukatzen ditugu!\l"
	.string "Kontzeptu itzela programa batentzat, ezta?\p"
	.string "gaurkoan gure kazetariak egindako\n"
	.string "elkarrizketa bat dakarkizuegu,\l"
	.string "POKéMON FAN TALDEAN egindakoa.\p"
	.string "beraz, zein da gaurkoan aterako den\n"
	.string "POKéMON fana?\p"
	.string "… … … … … … … …\p"
	.string "{STR_VAR_1}!\p"
	.string "Entzun dezagun {STR_VAR_1}(e)k esanog diguna\n"
	.string "{STR_VAR_3} {STR_VAR_2}(r)en gainean.\p"
	.string "Eta, hitz horiek oihukatuko ditut\n"
	.string "ozen telebistan!\p"
	.string "Hoo-hah!\p"
	.string "Oihu egin dezagun!$"

gTVFanClubOpinionsText01::
	.string "{STR_VAR_1}(e)ri galdetu genion, “Lehen\n"
	.string "aldiz {STR_VAR_2} ikusi zenuenean, zer\l"
	.string "pentsatu zenuen?”\p"
	.string "“{STR_VAR_3}!”\p"
	.string "Bai jauna! Izugarrizko oihua!\p"
	.string "Ez al dizkizue aspaldiko garaiak\n"
	.string "gogorarazten?$"

gTVFanClubOpinionsText02::
	.string "{STR_VAR_1}(e)ri galdetu genion, “Zure\n"
	.string "{STR_VAR_2} zeozerrekin konparatzekotan,\l"
	.string "izango litzateke…”\p"
	.string "… … … … … … … …\p"
	.string "“{STR_VAR_3}!”\p"
	.string "Ene-bada, zein ideia originala!\p"
	.string "Argi eta garbi ikusten da\n"
	.string "ENTRENATZAILE honek duen sentimendua\l"
	.string "{STR_VAR_2}(r)ekiko.$"

gTVFanClubOpinionsText03::
	.string "Eta ikus dezagun…\n"
	.string "Zar dauka {STR_VAR_2} horrek\l"
	.string "{STR_VAR_1}(e)ri hainbeste gustatzeko?\p"
	.string "… … … … … … … …\p"
	.string "“{STR_VAR_3}!”\p"
	.string "Ene! A zer nolako deklarazioa!\p"
	.string "ENTRENATZAILEAREN {STR_VAR_2}(r)ekiko\n"
	.string "maitasuna argi eta garbi geratu da!$"

gTVFanClubOpinionsText04::
	.string "Hm? Oraindik gehiago dago.\n"
	.string "Ikus dezagun!\p"
	.string "Ea ba, zer ote…\p"
	.string "{STR_VAR_1}(e)ri galdetu genion, “Zuretzat zer\n"
	.string "dira POKéMONAK?”\p"
	.string "… … … … … …\p"
	.string "“{STR_VAR_3}!”\p"
	.string "Izugarria!\p"
	.string "Egun osoan entzun dudan oihu itzelena!\p"
	.string "“{STR_VAR_3}!”\p"
	.string "Behin eta berriz oihukatzeko gogo\n"
	.string "bizia ematen du!\p"
	.string "Oihu egiten amaituta, bada garaia\n"
	.string "guztiak agurtzeko!\p"
	.string "Bota dezagun azken garrasi bat!\n"
	.string "Denok batera…\p"
	.string "“{STR_VAR_3}!”$"

gTVFanClubText00::
	.string "POKéMON FAN TALDEA GARA!\p"
	.string "Zuzenean gaude oraintxe!\p"
	.string "Gaurkoan, POKéMON GALDETEGIEN TXOKOA\n"
	.string "izango dugu programaren muina.\p"
	.string "POKéMONEK eta ENTRENATZAILEEK\n"
	.string "sortutako istorio ederren artean, zein\l"
	.string "drama izango ote dugu gaur gurean?\p"
	.string "Ea ba, ikus dezagun…\p"
	.string "Hauxe bera!\p"
	.string "Gutun honekin hasiko gara!\p"
	.string "{STR_VAR_1}(r)ek idatzitako gutuna da\n"
	.string "bere {STR_VAR_2} kuttunaren inguruan.\p"
	.string "Ikus dezagun gure idazleak nola transmititu\n"
	.string "dezakeen {STR_VAR_2}(r)ekiko duen pasioa!\l"
	.string "Hmhm…$"

gTVFanClubText01::
	.string "Uau!\n"
	.string "A zer nolako gutuna!$"

gTVFanClubText02::
	.string "Izugarri gustatu zait, hona hemen berriro!$"

gTVFanClubText03::
	.string "Horrelako gutun bat behin eta berriz\n"
	.string "irakurtzeko idatzi da!$"

gTVFanClubText04::
	.string "“{STR_VAR_3}”(r)en inguruan idatzitako zatiak\n"
	.string "bereziki indar emozional handia du!\p"
	.string "Oso gutun ederra da, bihotz guztiarekin\n"
	.string "idatzitakoa!$"

gTVFanClubText05::
	.string "Bereziki “{STR_VAR_3}”(r)en zati hori!\p"
	.string "Zer ondo dagoen “{STR_VAR_3}” erabilita!$"

gTVFanClubText06::
	.string "Ahaztu aurretik, ez da garrantzitsua,\n"
	.string "baina “{STR_VAR_3}” esapide ederra da.\p"
	.string "Azkenaldian asko erabili dut “{STR_VAR_3}”\n"
	.string "elkarrizketa guztietan.$"

gTVFanClubText07::
	.string "Puntuazio bat jartzekotan gutunari,\n"
	.string "{STR_VAR_3} puntu emango nizkioke.\p"
	.string "Hurrengoan are gutun hobea bidali\n"
	.string "beharko duzu, {STR_VAR_1}!\p"
	.string "Ai ene, denbora joan zaigu!\n"
	.string "Hurrengora arte guztioi!$"

SlateportCity_OceanicMuseum_1F_Text_InterviewRequest:
	.string "Oh?\n"
	.string "POKéMONAK gustuko al dituzu?\p"
	.string "Telebistarako lan bat egiten ari naiz.\p"
	.string "POKéMON eta ENTRENATZAILEEN arteko\n"
	.string "istorio berriak kontatzen ari gara.\p"
	.string "Inporta ez bazaizu, zure inguruko\n"
	.string "zeozer kontatuko zenidake?$"

SlateportCity_OceanicMuseum_1F_Text_InterviewRequestShort:
	.string "Duela gutxi gertatu diren istorioak biltzen\n"
	.string "ari naiz, POKéMON eta ENTRENATZAILEEN artekoak.\p"
	.string "Inporta ez bazaizu, zure inguruko\n"
	.string "zeozer kontatuko zenidake?$"

SlateportCity_OceanicMuseum_1F_Text_TellMeExperienceInvolvingPokemon:
	.string "Oh, bai?\n"
	.string "Eskerrik asko!\p"
	.string "Orduan, mesedez, konta iezadazu\n"
	.string "POKéMONEKIN azkenaldian gertatu zaizun\l"
	.string "zeoezr interesgarria.$"

SlateportCity_OceanicMuseum_1F_Text_LetMeKnowIfYouHaveStory:
	.string "Oh, ados, ados…\p"
	.string "Bueno, interesgarria den istoriorik\n"
	.string "baduzu kootatzeko, abisatu, mesedez.$"

SlateportCity_OceanicMuseum_1F_Text_ThatsAllForInterview:
	.string "Oh, zer istorio alaia!\p"
	.string "Istorio hau telebistan agertu dadin\n"
	.string "saiatuko naiz.\p"
	.string "Hemendik gutxira atera behar luke,\n"
	.string "beraz, adi egon telebistari.$"

SlateportCity_OceanicMuseum_1F_Text_BetterWriteUpStory:
	.string "Hmmm…\n"
	.string "Telebistako programa batentzako istorio ona dut.\p"
	.string "Hobe dut bizi-bizi idazten badut, ez ahazteko!$"

gTVRecentHappeningsText00::
	.string "Kaixo, ISTORIO BERRIEN garaia da.\p"
	.string "POKéMON ENTRENATZAILEENTZAT egun bakoitza\n"
	.string "ipuin berri bat bezala da.\p"
	.string "Programa hauetan ipuin hauetako batzuk\n"
	.string "kontatzen ditugu.\p"
	.string "Gaurkoan dakarkizuegun istorioa\n"
	.string "{STR_VAR_1} ENTRENATZAILEARENA da.\p"
	.string "Zer gertatu ote zaio {STR_VAR_1}(e)ri azkenaldian?\n"
	.string "Ikus dezagun denok batera.\p"
	.string "Ea ba…$"

gTVRecentHappeningsText01::
	.string "Ez al da zirraragarria izan?\p"
	.string "Istorio hau entzunda badakizu zer gertatu\n"
	.string "zaion {STR_VAR_1}(e)ri azkenaldian.\l"
	.string "ia-ia bertan egon izan bagina bezala da!$"

gTVRecentHappeningsText02::
	.string "“{STR_VAR_3}.” Horrek\n"
	.string "bereziki sakontasuna ematen dio istorioari.$"

gTVRecentHappeningsText03::
	.string "“{STR_VAR_3}.”\n"
	.string "Horrek nolabaiteko toki-zentzua ematen dio.\l"
	.string "Istorioaren lekua ikusiko bagenu bezala.$"

gTVRecentHappeningsText04::
	.string "“{STR_VAR_3}”(r)en sekzioa\n"
	.string "bereziki adierazgarria da.$"

gTVRecentHappeningsText05::
	.string "{STR_VAR_1}(e)k POKéMONEN inguruko\n"
	.string "istorio liluragarria kontatu digu.\p"
	.string "Eta orain {STR_VAR_1}(r)en ipuina\n"
	.string "zuen arimari lotuta geratu da.\p"
	.string "Hori izan da dena gaurkoz.\n"
	.string "Hurrengora arte, lagunok.$"

gTVMassOutbreakText00::
	.string "Agur bero bat denontzat!\n"
	.string "POKéMON ALBISTEEN garaia da.\p"
	.string "Gertakari oso berezi baten gaineko\n"
	.string "albiste bat jaso dugu.\p"
	.string "Badirudi {STR_VAR_2} agerraldi\n"
	.string "oso indartsu bat gertatu dela\l"
	.string "{STR_VAR_1} inguruan.\p"
	.string "{STR_VAR_2}, ziurrenik badakizu baina,\n"
	.string "bilatzeko zaila den POKéMON bat da\l"
	.string "eta oso gutxitan ikusi ohi da.\p"
	.string "Oso aukera ona da berez {STR_VAR_2}\n"
	.string "horiek kanpoan ikusteko,\l"
	.string "aprobetxatzea onena.\p"
	.string "Hauexek izan dira POKéMON ALBISTEAK.$"

gTV3CheersForPokeblocksText00::
	.string "ZM: Gogotsu egongo zaretela espero dugu,\n"
	.string "“3 GORA {POKEBLOCK}EI” iritsi zaigu!\p"
	.string "Gaur, {STR_VAR_1} eta lagunek nahastutako\n"
	.string "{POKEBLOCK}a aztertuko dugu.\p"
	.string "Gehiago luzatu gabe, nire gourmet\n"
	.string "POKéMON GULPINI emango diot probatzeko.\p"
	.string "… … … … … …\n"
	.string "… … … … … …$"

gTV3CheersForPokeblocksText01::
	.string "GULPIN: Gubi! Gubii!\p"
	.string "ZM: Epaia oso {STR_VAR_1} da!\n"
	.string "GULPINEK dio oso “{STR_VAR_2}” dagoela!\p"
	.string "Mila esker, {STR_VAR_3}!$"

gTV3CheersForPokeblocksText02::
	.string "{STR_VAR_1}(r)en nahasketa abilezia\n"
	.string "pixka bat hobe zitekeen.\p"
	.string "ENTRENATZAILE honek hobe nahastuko balu,\n"
	.string "{POKEBLOCK}a askoz goxoagoa egongo litzateke.$"

gTV3CheersForPokeblocksText03::
	.string "GULPIN: Gubi! Gubii!\p"
	.string "ZM: Hmm… {STR_VAR_1}egia omen dago.\n"
	.string "GULPINek dio “{STR_VAR_2}” dagoela!\p"
	.string "Badirudi {STR_VAR_3}(r)en akatsek\n"
	.string "nahastearen kalitatea okertu dutela…$"

gTV3CheersForPokeblocksText04::
	.string "Pena da {STR_VAR_1}(r)en saiakera\n"
	.string "alferrik galdu izana.\p"
	.string "Hurrengoan {STR_VAR_2}(e)k maila\n"
	.string "hobea emango du, ziur!$"

gTV3CheersForPokeblocksText05::
	.string "Hurrengora arte!\n"
	.string "Gure eslogana gogoratu “3 GORA {POKEBLOCK}EI!”$"

LilycoveCity_PokemonTrainerFanClub_Text_WhatsYourOpinionOfTrainer::
	.string "Kaixo!\p"
	.string "{STR_VAR_1}(r)en oso zalea naiz.\n"
	.string "Zuri zer iruditzen zaizu {STR_VAR_1}?$"

LilycoveCity_PokemonTrainerFanClub_Text_ThatsWhatYouThink::
	.string "Ados, ados. Hori uste duzu beraz\n"
	.string "ENTRENATZAILEAREN inguruan.$"

LilycoveCity_PokemonTrainerFanClub_Text_HaveYouForgottenTrainer::
	.string "Guztiz ahaztu al duzu bada\n"
	.string "{STR_VAR_1}?$"

LilycoveCity_PokemonTrainerFanClub_Text_WhatsYourOpinionOfTrainer2::
	.string "{STR_VAR_1}(r)en oso zalea naiz.\n"
	.string "Zer iruditzen zaizu zuri {STR_VAR_1}?$"

LilycoveCity_PokemonTrainerFanClub_Text_HowStrongRateTrainer::
	.string "Zein nota nota emango zenioke {STR_VAR_1}(e)ri\n"
	.string "batetik ehunerako eskalan?$"

LilycoveCity_PokemonTrainerFanClub_Text_HaveYouForgottenTrainer2::
	.string "Guztiz ahaztu al duzu bada\n"
	.string "{STR_VAR_1}?$"

LilycoveCity_PokemonTrainerFanClub_Text_YouShouldMeetTrainer::
	.string "Oh, Ados!\n"
	.string "{STR_VAR_1} ezagutu behar zenuke noizbait.\l"
	.string "ZU ere zale bilakatuko zinateke, seguru!$"

LilycoveCity_PokemonTrainerFanClub_Text_ThankYouIllShareThisInfo::
	.string "Ados, ados.\p"
	.string "Eskerrik asko!\n"
	.string "Oso erabilgarria da hori.\p"
	.string "{STR_VAR_1}(r)en beste zaletu batzuei kontatuko\n"
	.string "diet hau eta haiekin eztabaidatuko dut.$"

LilycoveCity_PokemonTrainerFanClub_HopeYouCatchTVSpecial::
	.string "Laister telebistan saio berezi bat\n"
	.string "emango dute {STR_VAR_1}(r)en inguruan.\p"
	.string "Ea ikusten duzun!$"

gTVTrainerFanClubSpecialText00::
	.string "ENTRENATZAILEEN ZALETU KLUBA\n"
	.string "{STR_VAR_1} EDIZIO BEREZIA!\p"
	.string "Honakoa aurkezpen berezi bat da HOENNeko\n"
	.string "{STR_VAR_1}(r)en zaletu guztientzat!\p"
	.string "Hau galdetu dugu gaur: “Zer pentsatzen\n"
	.string "du jendeak {STR_VAR_1}(r)en inguruan?”\p"
	.string "{STR_VAR_2}(e)ri galdetu diogu hau\n"
	.string "ENTRENATZAILEEN ordezkari gisan.\p"
	.string "Galdetu genion, “Hitz batean, nola\n"
	.string "deskribatuko zenuke {STR_VAR_1}?”\p"
	.string "Erantzuna: “{STR_VAR_3}.”\p"
	.string "Txalo bero bat {STR_VAR_2}(e)ri!\n"
	.string "Iritzi zolia!\p"
	.string "“{STR_VAR_3} {STR_VAR_1}.”\n"
	.string "Zein ondo geratzen diren bi hitzak batera!\p"
	.string "0tik 100erako eskalan {STR_VAR_1}(r)en\n"
	.string "puntuazioa ere eman zuen {STR_VAR_2}(e)k.$"

gTVTrainerFanClubSpecialText01::
	.string "{STR_VAR_3} puntu eman zizkion!\n"
	.string "A zer nolako puntuazioa!\p"
	.string "{STR_VAR_2}(e)k asko atsegin du\n"
	.string "{STR_VAR_1} duda izpirik gabe.$"

gTVTrainerFanClubSpecialText02::
	.string "{STR_VAR_3} puntu eman zizkion!\n"
	.string "Nahikoa puntuazio ona da hori.\p"
	.string "{STR_VAR_2}(r)entzat etsai\n"
	.string "garrantzitsua da {STR_VAR_1}.$"

gTVTrainerFanClubSpecialText03::
	.string "{STR_VAR_3} puntu eman zizkion!\n"
	.string "Ez da bereziki puntuazio altua.\p"
	.string "{STR_VAR_2}(r)entzat {STR_VAR_1}\n"
	.string "adiskidea bakarrik dela ematen du.$"

gTVTrainerFanClubSpecialText04::
	.string "The score was {STR_VAR_3} point(s)!\n"
	.string "Oso puntuazio baxua da, dudarik gabe.\p"
	.string "{STR_VAR_2}(e)k ez dio garrantzia\n"
	.string "handirik ematen {STR_VAR_1}(e)ri.$"

gTVTrainerFanClubSpecialText05::
	.string "Hori da guztia, lagunok!\p"
	.string "Gaurkoan denok ikasi dugu zerbait\n"
	.string "berria {STR_VAR_1}(r)en inguruan.\p"
	.string "Azkenik, {STR_VAR_2}(r)en hitzekin\n"
	.string "utziko zaituztet.\p"
	.string "{STR_VAR_3} {STR_VAR_1}!$"

gTVNameRaterText00::
	.string "Eta orain, badiritsi da garaia…\n"
	.string "IZEN BALORATZAILEEN SHOWERAKO.\p"
	.string "Zure POKéMONAREN etorkizuna iragarriko\n"
	.string "dut, emandako ezizenaren arabera.\p"
	.string "Emateko aholku asko ditut, eta\n"
	.string "oso baliagarriak, gainera.\p"
	.string "Gaur egingo dudan iragarpena\n"
	.string "{STR_VAR_3} ezizenarena izango da,\l"
	.string "{STR_VAR_1}(r)en {STR_VAR_2} POKéMONARENa.\p"
	.string "Hmhm…\p"
	.string "Hmm…\n"
	.string "Ezizen hau…$"

gTVNameRaterText01::
	.string "Ezizen hau talentuaren sinonimo da\n"
	.string "hainbat eratan.\p"
	.string "ENTRENATZAILE honek erronka berriak\n"
	.string "hartu behar lituzke, indartsu.$"

gTVNameRaterText02::
	.string "Ezizen hau oso ondo geratzen da\n"
	.string "{STR_VAR_1}(r)ekin, ENTRENATZAILEAREN izenarekin.\p"
	.string "Denborarekin lankidetza-erlazio ederra\n"
	.string "sortuko duzuela iradokitzen du.$"

gTVNameRaterText03::
	.string "Oso ezizen egokia horren POKéMON\n"
	.string "bereziarentzat!\p"
	.string "Ondo haziz gero, POKéMON honen\n"
	.string "berezitasuna izugarri garatuko da!$"

gTVNameRaterText04::
	.string "Ezizen honek POKéMONEN zaintza eta\n"
	.string "maitasunaren zatia erakusten du.\p"
	.string "Ondo haziz gero, POKéMON hau\n"
	.string "epeltasun handikoa izango da!$"

gTVNameRaterText05::
	.string "Ezizen oso egokia etorkizuneko\n"
	.string "handitasuna isladatzeko.\p"
	.string "Jakin min handia dut etorkizunean\n"
	.string "POKéMON honek ekarriko duena ezagutzeko.$"

gTVNameRaterText06::
	.string "Ezizen ona, POKéMONA sasoi onekoa\n"
	.string "bilakatuko duena!\p"
	.string "POKéMON hau sasoi onean eta indartu\n"
	.string "egongo da denbora luze-luzean.$"

gTVNameRaterText07::
	.string "Ezizen ona, POKéMONA bereziki\n"
	.string "bizia eta aktiboa bihurtuko du!\p"
	.string "Esango nuke POKéMON hau borroketan\n"
	.string "oso ondo ibiliko dela.$"

gTVNameRaterText08::
	.string "Ezizen erakargarria, POKéMONA\n"
	.string "xarmangarria egiten du!\p"
	.string "Ez daukat dudarik, POKéMON hau\n"
	.string "POKéMON LEHIAKETETAN xarmantena izango da.$"

gTVNameRaterText09::
	.string "{STR_VAR_1} ezizenaren erroan\n"
	.string "“{STR_VAR_3}” letra dago.\p"
	.string "Letra hori euskarria ematen dio hurrengo\n"
	.string "“{STR_VAR_2}” letrak, eta horrek ezizenari\l"
	.string "presentzia handia ematen dio.$"

gTVNameRaterText10::
	.string "{STR_VAR_1} ezizena proportzio\n"
	.string "oso orekatua du.\p"
	.string "“{STR_VAR_2}” eta “{STR_VAR_3}” letren presentzia...\n"
	.string "bereziki izugarria da!$"

gTVNameRaterText11::
	.string "{STR_VAR_1}-- ezizenak badu\n"
	.string "nolabaiteko sentsazio sublimea.\p"
	.string "Hasierako “{STR_VAR_2}” letratik hurrengo\n"
	.string "“{STR_VAR_3}” letrarako jauzia itzela da.$"

gTVNameRaterText12::
	.string "Ikus ditzagun beste ezizen fin\n"
	.string "batzuk, ados?$"

gTVNameRaterText13::
	.string "Adibidez, hartu ENTRENATZAILEAREN\n"
	.string "izena: {STR_VAR_1}, eta amaieran\l"
	.string "jarri ezizen itzel hau: {STR_VAR_2}{STR_VAR_3}.$"

gTVNameRaterText14::
	.string "{STR_VAR_2}{STR_VAR_3} ezizena ere nahikoa\n"
	.string "egokia izango litzateke.$"

gTVNameRaterText15::
	.string "POKéMONAREN espeziearen izena:\n"
	.string "{STR_VAR_2} oinarri bezala erabili daiteke\l"
	.string "ezizena asmatzeko {STR_VAR_1}{STR_VAR_3}.$"

gTVNameRaterText16::
	.string "{STR_VAR_1}{STR_VAR_3} ere ezizen eraginkorra\n"
	.string "izango litzateke.$"

gTVNameRaterText17::
	.string "Beti sahiestu beharkko litzateke beste\n"
	.string "POKéMON espezie baten izena.\p"
	.string "Adibidez, {STR_VAR_2} izena hartzea\n"
	.string " {STR_VAR_1}{STR_VAR_3} ezizena asmatzeko.\l"
	.string "Hori onartezina da.$"

gTVNameRaterText18::
	.string "Esan beharra dut {STR_VAR_1} nahikoa\n"
	.string "ezizen ona dela.\p"
	.string "Espero dut ENTRENATZAILEAK maitasunez\n"
	.string "jarraituko duela {STR_VAR_1} zaintzen.\p"
	.string "Hau da guztia gaurkoz.\n"
	.string "Hurrengora arte denoi.$"

gTVPokemonAnglerText00::
	.string "{STR_VAR_2} ARRANTZALEA\p"
	.string "AURKEZLEA: Kaixo! Gaurkoan {STR_VAR_2}\n"
	.string "arrantzatzeko aholkuak jasoko ditugu.\p"
	.string "GURU, zein aholku duzu guretzat\n"
	.string "{STR_VAR_2} arrantzatzeko?\p"
	.string "GURU: {STR_VAR_2} arrantzatzeko, e?\n"
	.string "Bueno, ba erraza da, pazientzia izan\l"
	.string "eta itxaron. Hori da kontua.\p"
	.string "Ikusten duzu hor {STR_VAR_1}?\n"
	.string "ENTRENATZAILE hori adibide ona da.\p"
	.string "ENTRENATZAILE horri jada ihes egin\n"
	.string "die {STR_VAR_3} POKéMONEK.\p"
	.string "Baina hortxe dago {STR_VAR_1} itxaroten.\n"
	.string "Hori da {STR_VAR_2} harrapatzeko egin beharrekoa.\p"
	.string "AURKEZLEA: Ados…\p"
	.string "Oh! {STR_VAR_1}(e)k azkenean aurkitu du\n"
	.string "{STR_VAR_2} iheskor bat!\p"
	.string "ENTRENATZAILEA oso zoriontsu dago,\n"
	.string "ia negarrez!\p"
	.string "Zoriontasun begirada horrekin,\n"
	.string "arrantzatzeko grina datorkit berriz!\p"
	.string "Ikusleok, zergatik ez duzue hau aprobetxatzen\n"
	.string "{STR_VAR_2} batzuk arrantzatzeko?\p"
	.string "Hurrengo programara arte, adio\n"
	.string "eta arrantza on denoi!$"

gTVPokemonAnglerText01::
	.string "{STR_VAR_2} ARRANTZALEA\p"
	.string "AURKEZLEA: Kaixo! Gaurkoan {STR_VAR_2}\n"
	.string "arrantzatzeko aholkuak jasoko ditugu.\p"
	.string "GURU, zein aholku duzu guretzat\n"
	.string "{STR_VAR_2} arrantzatzeko?\p"
	.string "GURU: {STR_VAR_2} arrantzatzeko, e?\n"
	.string "Bueno, erraza da, erabili kemen handiz\l"
	.string "zure KANABERA!\p"
	.string "Ikusten duzu hor {STR_VAR_1}?\n"
	.string "Ikusten nola erabiltzen duen KANABERA?\p"
	.string "ENTRENATZAILE horrek jada harrapatu\n"
	.string "ditu {STR_VAR_3} jarraian.\p"
	.string "AURKEZLEA: Izugarria!\n"
	.string "Ekaitz bat dirudi…\p"
	.string "Horrelako teknika ikusita, arrantza\n"
	.string "egiteko gogoa etorri zait niri ere.\p"
	.string "Ikusleok, zergatik ez duzue hau aprobetxatzen\n"
	.string "{STR_VAR_2} batzuk arrantzazeko?\p"
	.string "Hurrengora programara arte, adio\n"
	.string "eta arrantza on denoi!$"

gTVPokemonTodayFailedText00::
	.string "Kaixo!\p"
	.string "POKéMON GAURREN garaia da!\p"
	.string "ARREBA NAGUSIA: Epa! Alai eta bizi al\n"
	.string "gaude denok gaur?\p"
	.string "Gaurkoan {STR_VAR_1}(r)en {STR_VAR_2}\n"
	.string "POKéMONA ikusiko dugu!\p"
	.string "ANAIA NAGUSIA: Bai! Horixe bera egingo\n"
	.string "dugu!$"

gTVPokemonTodayFailedText01::
	.string "Oh! {STR_VAR_1}(e)ri buruz hitz\n"
	.string "egiten ari garela…\p"
	.string "ARREBA NAGUSI, nire begiekin ikusi\n"
	.string "dut ENTRENATZAILEA!\p"
	.string "ARREBA NAGUSIA: Oh, zer ikusi duzu?\p"
	.string "ANAIA NAGUSIA: Bueno, bidaia bat izan\n"
	.string "nuen {STR_VAR_2}(e)ra.\p"
	.string "Eta bertan aurkitu nuen kasualitatez\n"
	.string "{STR_VAR_1}, {STR_VAR_3} POKéMONA\l"
	.string "harrapatzen saiatzen ari zen, baina…$"

gTVPokemonTodayFailedText02::
	.string "POKéMONAK ihes egitea lortu zuen!\p"
	.string "Badakizu zenbat POKé BALL gastatu\n"
	.string "Zituen? {STR_VAR_2}!\p"
	.string "{STR_VAR_1}(r)en aurpegiko frustrazio\n"
	.string "aurpegia ikustekoa izan zen\l"
	.string "POKéMONAK ihes egin zuenean!$"

gTVPokemonTodayFailedText03::
	.string "Baina {STR_VAR_1}(e)k txorakeriak egin\n"
	.string "eta POKéMONA ahuldu egin zen!\p"
	.string "Badakizue zenbat POKé BALL gastatu\n"
	.string "zituen? {STR_VAR_2}!\p"
	.string "{STR_VAR_1}(r)en harridura aurpegia\n"
	.string "ikusi behar zenuten POKéMONA\l"
	.string "ahuldu zenean!$"

gTVPokemonTodayFailedText04::
	.string "ARREBA NAGUSIA: Ei, aizu!\n"
	.string "Hori ez da egiten!\p"
	.string "Ez zenioke besteen zorigaitzei\n"
	.string "barre egin behar!\p"
	.string "Oh, {STR_VAR_1} gaixoa.\n"
	.string "Ze pena!\p"
	.string "ANAIA NAGUSIA: Egia da hori!\n"
	.string "Barkatu barre egiteagatik.$"

gTVPokemonTodayFailedText05::
	.string "ARREBA NAGUSIA: Kar kar…\p"
	.string "ANAIA NAGUSIA: Aizu!\n"
	.string "Zuk ere barre egin duzu!\p"
	.string "ARREBA NAGUSIA: Nola?!\p"
	.string "Ez dut barrerik egin!\n"
	.string "benetan, ez dut egin!\p"
	.string "Oh, {STR_VAR_1} gaixoa.\n"
	.string "A zer pena!\p"
	.string "ANAIA NAGUSIA: …$"

gTVPokemonTodayFailedText06::
	.string "ARREBA NAGUSIA: Nahikoa tontakeria\n"
	.string "egin ditugu! Ikus dezagun gaurko\p"
	.string "POKéMONA… Zer?\n"
	.string "Denbroarik gabe geratu al gara?\p"
	.string "Ohh!\n"
	.string "Ezin izan dugu POKéMONA ikusi!\p"
	.string "ANAIA NAGUSIA: Hurrengora arte!\p"
	.string "ARREBA NAGUSIA: Aizu, ez bukatu\n"
	.string "programa ni gabe!$"

gTVPokemonTodaySuccessfulText00::
	.string "Kaixo!\p"
	.string "Iritsi da POKéMON GAUR!\p"
	.string "ARREBA NAGUSIA: Iepa! Alai eta bizi al\n"
	.string "gaude denok gaur?\p"
	.string "Gaurkoan, {STR_VAR_1}(r)en POKéMONA\n"
	.string "ikusiko dugu: {STR_VAR_2}!\p"
	.string "ANAIA NAGUSIA: Bai! Horixe bera\n"
	.string "egingo dugu!$"

gTVPokemonTodaySuccessfulText01::
	.string "ARREBA NAGUSIA: {STR_VAR_1}(e)k {STR_VAR_3}\n"
	.string "ezizena eman zion {STR_VAR_2}(e)ri!\p"
	.string "Badirudi {STR_VAR_3} oso-oso\n"
	.string "maitatua izaten ari dela!$"

gTVPokemonTodaySuccessfulText02::
	.string "ANAIA NAGUSIA: ENTRENATZAILEAK {STR_VAR_3}\n"
	.string "POKé BALL erabili behar izan zituen!\p"
	.string "Azkenean {STR_VAR_2} bakar bat behar\n"
	.string "izan zuen harrapetzeko!$"

gTVPokemonTodaySuccessfulText03::
	.string "ARREBA NAGUSIA: Horren erraza izan\n"
	.string "bazen harrapatzeko, patua izan zen\l"
	.string "{STR_VAR_1} eta {STR_VAR_2} elkartu zituena!$"

gTVPokemonTodaySuccessfulText04::
	.string "ARREBA NAGUSIA: Ene! Hori ederra!\p"
	.string "Badakizu esamoldea, POKéMONA harrapatzeko\n"
	.string "zail eta berezi, ENTRENATZAILEAREN\l"
	.string "maitasuna merezi!$"

gTVPokemonTodaySuccessfulText05::
	.string "ARREBA NAGUSIA: {STR_VAR_1}(r)en {STR_VAR_2}\n"
	.string "POKéMON gogoangarria da, harrapatzeko\l"
	.string "MASTER BALLa erabili behar izan zuelako!\p"
	.string "ANAIA NAGUSIA: Uau! Hori mega-izugarria da!\p"
	.string "ARREBA NAGUSIA: {STR_VAR_1}(e)k benetan\n"
	.string "nahi zuen {STR_VAR_2} hori, argi dago!$"

gTVPokemonTodaySuccessfulText06::
	.string "ANAIA NAGUSIA: Gainera, gero {STR_VAR_3}\n"
	.string "ezizena ematea {STR_VAR_2} horri…\p"
	.string "Ikus dezakezu {STR_VAR_1}(e)k\n"
	.string "duen ENTRENATZAILE sena.\p"
	.string "ARREBA NAGUSIA: Guztiz ados horrekin!$"

gTVPokemonTodaySuccessfulText07::
	.string "Ni izango banintz, ezizen hori emango\n"
	.string "nioke honelako {STR_VAR_3} bati!\p"
	.string "ANAIA NAGUSIA: Ene! Hori zeozer berriaren\n"
	.string "hasiera litzateke!$"

gTVPokemonTodaySuccessfulText08::
	.string "{STR_VAR_2} {STR_VAR_1}(r)a?\n"
	.string "Ez al da perfektua?\p"
	.string "Letrak eta beste guztia--oso\n"
	.string "ondo geratzen zaizkio {STR_VAR_1}\l"
	.string "POKéMONAri!\p"
	.string "ANAIA NAGUSIA: Bai, egia, horixe!$"

gTVPokemonTodaySuccessfulText09::
	.string "Nik dakidanez, ez da ENTRENATZAILERIK\n"
	.string "izan {STR_VAR_2} ezizena jarri diona\l"
	.string "bere {STR_VAR_1}(r)ari!\p"
	.string "ANAIA NAGUSIA: Argi eta garbi ikusten\n"
	.string "da ezizenak aukeratzeko zein gustu ona\l"
	.string "duen ENTRENATZAILEAK!$"

gTVPokemonTodaySuccessfulText10::
	.string "POKéMON bat harrapatzen dudanean,\n"
	.string "{STR_VAR_2} ezizena emango diot.\p"
	.string "ANAIA NAGUSIA: Nola? Nik ere bai!\n"
	.string "Nik ere {STR_VAR_2} ezizena erabiliko dut!$"

gTVPokemonTodaySuccessfulText11::
	.string "ARREBA NAGUSIA: Ai, ene!\n"
	.string "Begiratu ordularia!\p"
	.string "Beno, lagunak, ordua da.\n"
	.string "Ikusi arte!\p"
	.string "ANAIA NAGUSIA: Gogoratu, hurrengoan zure\n"
	.string "POKéMONA izan daiteke protagonista!$"

SmartShopper_Text_Intro::
	.string "Kaixo!\p"
	.string "GAURKO EROSLE ARGIAren ordua iritsi da.\p"
	.string "ELKARRIZKETATZAILEA: Zer moduz, ikusleok?\p"
	.string "Gaurkoan bisitatuko dugun denda\n"
	.string "{STR_VAR_2}(e)n dago.\p"
	.string "Ikus dezagun zertan dabiltzan bertako\n"
	.string "saltzaileak azkenaldian.$"

SmartShopper_Text_ClerkNormal::
	.string "Galdetu diezaiogun saltzaileari, ea\n"
	.string "zer dioen.\p"
	.string "Kaixo, zer moduz doa negozioa?\p"
	.string "SALTZAILEA: Ba oraingoz, bikain.\p"
	.string "Azkenaldian, {STR_VAR_2} bereziki\n"
	.string "asko saldu dugu.\p"
	.string "Aurreko batean {STR_VAR_1} izeneko\n"
	.string "ENTRENATZAILE batek {STR_VAR_3} erosi zituen.$"

SmartShopper_Text_RandomComment1::
	.string "ELKARRIZKETATZAILEA: ENTRENATZAILEAK\n"
	.string "{STR_VAR_3} {STR_VAR_2} erosi zituen? A zer nolako pila!\p"
	.string "Nire iritziz, {STR_VAR_1} bidaia luze\n"
	.string "baterako prestatzen arituko da, oso-oso\l"
	.string "urrutiko lekuren batera.\p"
	.string "Bidaiatzeko, {STR_VAR_2}(a)k oso\n"
	.string "garrantzitsuak dira!$"

SmartShopper_Text_RandomComment2::
	.string "ELKARRIZKETATZAILEA: {STR_VAR_2} itemaz ari\n"
	.string "garela, justu {STR_VAR_3} erosi berri\l"
	.string "ditut.\p"
	.string "Azkenean, {STR_VAR_2} item itzela da!$"

SmartShopper_Text_RandomComment3::
	.string "ELKARRIZKETATZAILEA: {STR_VAR_2}?!\n"
	.string "Baina {STR_VAR_3}, benetan?!\p"
	.string "Eznuen uste inork horrenbeste\n"
	.string "erosteko beharrik izango zuenik.\p"
	.string "Ene bada, nik bat edo bi eros ditzaket\n"
	.string "dendara joaten naizenean…$"

SmartShopper_Text_RandomComment4::
	.string "ELKARRIZKETATZAILEA: Behin, {STR_VAR_2}\n"
	.string "item mordo bat erosi nuen.\p"
	.string "baina gehiegi izan ziren azkenean.\n"
	.string "Azkenean damutu egin nintzen…\p"
	.string "Ordudanik, soilik bene-benetan behar\n"
	.string "ditudanak soilik hartzen ditut…\p"
	.string "Ai ene!\p"
	.string "Ez gara nitaz hitz egitera etorri hona!$"

SmartShopper_Text_SecondItem::
	.string "SALTZAILEA: {STR_VAR_1}(e)k {STR_VAR_2} itema\n"
	.string "ere erosi zuen eskergan, denera {STR_VAR_3}.\p"
	.string "ELKARRIZKETATZAILEA: Oh, ideia bikaina.\n"
	.string "{STR_VAR_2} ere oso item ona da.$"

SmartShopper_Text_ThirdItem::
	.string "SALTZAILEA: Eta ENTRENATZAILEAK ere\n"
	.string "{STR_VAR_3} {STR_VAR_2} ere hartu zituen.$"

SmartShopper_Text_DuringSale::
	.string "SALTZAILEA: Gainera, eskaintza handi batean\n"
	.string "erosi zituen. Hori bai erosketa.$"

SmartShopper_Text_OutroNormal::
	.string "ELKARRIZKETATZAILEA: Hmm… {STR_VAR_1}\n"
	.string "pagotxa bilatzaile aparta da!\p"
	.string "Guztira, {STR_VAR_1}(r)en erosketa…\p"
	.string "{STR_VAR_2}¥ izan ziren?!\n"
	.string "A zer nolako kantitatea!\p"
	.string "Ene! Denbora joan zaigu!\n"
	.string "Hurrengo programara arte!$"

SmartShopper_Text_IsVIP::
	.string "SALTZAILEA: {STR_VAR_1} VIP bezeroa da,\n"
	.string "inolako ezbairik gabe.$"

SmartShopper_Text_ClerkMax::
	.string "Galde diezaiogun saltzaileari, ea\n"
	.string "zer dioen.\p"
	.string "Kaixo, zer moduz doa negozioa?\p"
	.string "SALTZAILEA: Oh, sinesgaitza da zenbat\n"
	.string "saltzen ari garen. Ia-ia gehiegi izaten ari da.\p"
	.string "Duela gutxi, {STR_VAR_1} izeneko ENTRENATZAILE\n"
	.string "batek {STR_VAR_2} pila bat erosi zuen.\p"
	.string "ENTRENATZAILE honek ia-ia gure\n"
	.string "{STR_VAR_2} guztiak gastatu zituen.\p"
	.string "Ez nuen inoiz pentsatuko bezero bakarrak\n"
	.string "horrenbeste {STR_VAR_2}erosiko zituenik.\l"
	.string "Zinez sinesgaitza da!\p"
	.string "ELKARRIZKETATZAILEA: Zenbat erosi zituen 100\n"
	.string "edo 200 inguru?\p"
	.string "SALTZAILEA: Ez ez, askoz gehiago!\p"
	.string "ELKARRIZKETATZAILEA: Ai ene!\n"
	.string "{STR_VAR_1} bezero berezia da!\p"
	.string "SALTZAILEA: {STR_VAR_1} VIP bezeroa da,\n"
	.string "inolako ezbairik gabe.$"

SmartShopper_Text_OutroMax::
	.string "ELKARRIZKETATZAILEA: Hmm…\n"
	.string "Izugarria benetan.\p"
	.string "Baina zertarako behar ote zituen\n"
	.string "horrenbeste ENTRENATZAILEAK?\p"
	.string "… …\p"
	.string "Misterio sakona, baina tristeki,\n"
	.string "denbora gastatu zaigu gaurkoz.\l"
	.string "Hurrengo programara arte!\p"
	.string "Hala ere, {STR_VAR_1} enigma hutsa da…$"

gTVWorldOfMastersText00::
	.string "MAISUEN MUNDUA\p"
	.string "Kaixo ikusleok.\p"
	.string "Again ezagun zaizue {STR_VAR_1}\n"
	.string "izeneko ENTRENATZAILEA.\p"
	.string "{STR_VAR_1} famatua da POKéMONAK\n"
	.string "harrapatzen maisua delako.\p"
	.string "{STR_VAR_1}(r)en POKéMON bilaketa\n"
	.string "ingurua kontu handiz aztertzean datza.\p"
	.string "Egun gogoangarri batean, ENTRENATZAILEAK\n"
	.string "{STR_VAR_2} pausu ibili zen.\p"
	.string "Egun hartan harrapatutako POKéMON\n"
	.string "kopurua {STR_VAR_3} izan zen!$"

gTVWorldOfMastersText01::
	.string "balentria izugarri hura \n"
	.string "ENTRENATZAILEAREN eta {STR_VAR_1}(r)en\l"
	.string "arteko erlazioari esker izan zen.$"

gTVWorldOfMastersText02::
	.string "Maisu honek eguneko azken {STR_VAR_3}a\n"
	.string "{STR_VAR_2}(e)tik hurbil harrapatu zuen.\p"
	.string "Badirudi POKéMON horri asko gustatzen\n"
	.string "zaiola errekorrak lortzea.\p"
	.string "ENTRENATZAILE bikainak errekor hau\n"
	.string "garaitzen saiatu behar lirateke.\p"
	.string "Hori da guztia gaurkoz.\n"
	.string "Hurrengora arte.$"

gTVTodaysRivalTrainerText00::
	.string "GAURKO ENTRENATZAILE ARERIOA!\p"
	.string "Kaixo, POKéMON ENTRENATZAILEOK!\n"
	.string "Zer moduz zaudete?\p"
	.string "Gaur, beste egunetan bezala,,\n"
	.string "gure arerioetako bat aztertuko dugu!$"

gTVTodaysRivalTrainerText07::
	.string "Gaurko ENTRENATZAILE arerioa {STR_VAR_1} da,\n"
	.string "{STR_VAR_3} inguruan dabil oraintxe.\p"
	.string "{STR_VAR_1}(e)k, oraingoz, {STR_VAR_2} POKéMON\n"
	.string "erregistratu ditu POKéDEXEAN.$"

gTVTodaysRivalTrainerText08::
	.string "Gaurko ENTRENATZAILE arerioa {STR_VAR_1} da,\n"
	.string "BASE SEKRETU batean dago orain.\p"
	.string "{STR_VAR_1}(e)k, oraingoz, {STR_VAR_2} POKéMON\n"
	.string "erregistratu ditu POKéDEXEAN.$"

gTVTodaysRivalTrainerText09::
	.string "Gaurko ENTRENATZAILE arerioa {STR_VAR_1} da.\p"
	.string "{STR_VAR_1}(e)k, oraingoz, {STR_VAR_2} POKéMON\n"
	.string "erregistratu ditu POKéDEXEAN.$"

gTVTodaysRivalTrainerText10::
	.string "Gaurko ENTRENATZAILE arerioa {STR_VAR_1} da,\n"
	.string "ferry batean dago oraintxe.\p"
	.string "{STR_VAR_1}(e)k, oraingoz, {STR_VAR_2} POKéMON\n"
	.string "erregistratu ditu POKéDEXEAN.$"

	.string "$"

gTVTodaysRivalTrainerText01::
	.string "Eta zenbat DOMINA ote ditu orain gure\n"
	.string "arerioak? {STR_VAR_1} domina guztira!$"

gTVTodaysRivalTrainerText02::
	.string "Baina gure arerioak oraindik ez du\n"
	.string "DOMINARIK lortu!$"

gTVTodaysRivalTrainerText03::
	.string "Gure arerioak oraindik ez du\n"
	.string "BORROKA FRONTEKO Sinbolorik lortu.$"

gTVTodaysRivalTrainerText04::
	.string "Ikus dezagun BORROKA FRONTEKO\n"
	.string "zenbat Sinbolo dituen gure arerioak.\p"
	.string "Urrezko Sinboloak: {STR_VAR_1}!\n"
	.string "Zilarrezko Sinboloak: {STR_VAR_2}!$"

gTVTodaysRivalTrainerText05::
	.string "Gure arerioak {STR_VAR_1} Borroka\n"
	.string "Puntu lortu ditu BORROKA FRONTEAN.$"

gTVTodaysRivalTrainerText06::
	.string "Eta zu nola zabiltza\n"
	.string "{STR_VAR_1}(r)ekin alderatuta?\p"
	.string "Abenturak bizirik darrai!\p"
	.string "ENTRENATZAILEOK!\p"
	.string "Segi dezagun guztiok aurrera\n"
	.string "gure arerioen aurretik!$"

TrendWatcher_Text_Intro::
	.string "ITSASAITZ MODA-JARRAITZAILE KATEA!\p"
	.string "ZM: Ze martxa?\n"
	.string "IHINTZIBARREKO berriak dakarkizuegu,\l"
	.string "guztiak puri-purian.\p"
	.string "Gaur gurian, IHINTZIBARREKO nagusia\n"
	.string "eta autoritatea dela dioen gizon\l"
	.string "zaharra izango dugu.\p"
	.string "Gizon zaharra: Eskerrik asko, bai.\p"
	.string "ZM: Goazen harira, zuzen-zuzenean.\p"
	.string "Zer ari da gertatzen IHINTZIBARREKO\n"
	.string "jende prestuaren artean?\p"
	.string "Gizon zaharra: {STR_VAR_1} {STR_VAR_2}.\p"
	.string "ZM: {STR_VAR_1} {STR_VAR_2},\n"
	.string "beraz?\p"
	.string "Gizon zaharra: Ez.\p"
	.string "{STR_VAR_1} {STR_VAR_2} ez da\n"
	.string "inoiz famatua izan hor.\p"
	.string "Nahi duzu horri buruz hitz egitea?\p"
	.string "ZM: Ez, ba. Jakin nahi duguna da\n"
	.string "zer dagoen orain modan…$"

@ Identical to below, may have been different in other languages
TrendWatcher_Text_MaleTaughtMePhrase::
	.string "Gizon zaharra: {STR_VAR_1} {STR_VAR_2}\n"
	.string "hori esan zidan zegoela modan\l"
	.string "ERROTXIKIKO {STR_VAR_3}(e)k…$"

TrendWatcher_Text_FemaleTaughtMePhrase::
	.string "Gizon zaharra: {STR_VAR_1} {STR_VAR_2}\n"
	.string "hori esan zidan zegoela modan\l"
	.string "ERROTXIKIKO {STR_VAR_3}(e)k…$"

TrendWatcher_Text_PhraseWasHopeless::
	.string "Baina alferrikakoa izan zen.\p"
	.string "{STR_VAR_1} {STR_VAR_2} jaialdia!\p"
	.string "{STR_VAR_1} {STR_VAR_2} txapelketa!\p"
	.string "Saiatu nintzen guztiei ahalik ondoen\n"
	.string "erakusten, baina…\p"
	.string "Agian {STR_VAR_1}(r)en partea ez zen\n"
	.string "egokiena izan…\p"
	.string "ZM: Aizu, barkatu, lagun, orain modan\n"
	.string "dagoena zer den jakin behar dut…$"

@ Identical to below, may have been different in other languages
TrendWatcher_Text_MaleTellMeBigger::
	.string "Gizon zaharra: {STR_VAR_3}!\n"
	.string "Mesedez, esan zerbait hau baino handiagoa\l"
	.string "dena: {STR_VAR_1} {STR_VAR_2}!$"

TrendWatcher_Text_FemaleTellMeBigger::
	.string "Gizon zaharra: {STR_VAR_3}!\n"
	.string "Mesedez, esan zerbait hau baino handiagoa\l"
	.string "dena: {STR_VAR_1} {STR_VAR_2}!$"

TrendWatcher_Text_Outro::
	.string "ZM: …Beno… Ba hortxe duzue,\n"
	.string "moda-modako ikusle maiteok!\p"
	.string "{STR_VAR_1} {STR_VAR_2}…beno…\n"
	.string "Ba hori ez dago modan PORTUONDON!\p"
	.string "Bukatu zait denbora. Ondo segi!\p"
	.string "Gizon zaharra: {STR_VAR_1} {STR_VAR_2}!$"

gTVHoennTreasureInvestigatorsText00::
	.string "HOENNEKO ALTXOR IKERTZAILEAK!\p"
	.string "Aupa, kuadrila!\n"
	.string "Item sekreturik aurkitu al duzue?\p"
	.string "Beti bezala, sekretuak begiztatu\n"
	.string "dituztenen testigantzak izango ditugu!\p"
	.string "has gaitezen gutun batekin.\n"
	.string "Honakoa dio, “{STR_VAR_1} aurkitu dute!”$"

gTVHoennTreasureInvestigatorsText01::
	.string "Ene, hobe dugu ziztuan gutun hau\n"
	.string "aztertzea! Irakurri egingo dizuet.\p"
	.string "…IKERTZAILE agurgarriak,\n"
	.string "ondo zaudetela espero dut.\p"
	.string "Duela gutxi {STR_VAR_2} ikusi nuen\n"
	.string "{STR_VAR_3} inguruan.\p"
	.string "ENTRENATZAILEAK {STR_VAR_1} itema\n"
	.string "aurkitu zuen. A zer inbidia.\p"
	.string "…Beno, ondo egina, {STR_VAR_2}!\p"
	.string "Ikusleok, istorio honek bultza\n"
	.string "zaiteztela ITEMBILATZAILEAK erabiltzera!\p"
	.string "Zuen istorio zirraragarrien zain\n"
	.string "egongo naiz!$"

gTVHoennTreasureInvestigatorsText02::
	.string "Ene, hobe dugu ziztuan gutun hau\n"
	.string "aztertzea! Irakurri egingo dizuet.\p"
	.string "…IKERTZAILE agurgarriak,\n"
	.string "ondo zaudetela espero dut.\p"
	.string "Duela gutxi {STR_VAR_2} ikusi nuen ferrian.\p"
	.string "ENTRENATZAILEAK {STR_VAR_1} itema\n"
	.string "aurkitu zuen. A zer inbidia.\p"
	.string "…Beno, ondo egina, {STR_VAR_2}!\p"
	.string "Ikusleok, istorio honek bultza\n"
	.string "zaiteztela ITEMBILATZAILEAK erabiltzera!\p"
	.string "Zuen istorio zirraragarrien zain\n"
	.string "egongo naiz!$"

gTVFindThatGamerText00::
	.string "BILATU GAMER HORI!\p"
	.string "Aupa, gamer maiteok!\n"
	.string "Zer moduz dabil zuen {STR_VAR_2}?\p"
	.string "Beti bezala, JOKOEN TXOKORA gerturatu\n"
	.string "den ENTRENATZAILE berezi baten inguruan\l"
	.string "hitz egingo dizuegu!\p"
	.string "Gaurkoan, gure gamer bikaina da…\n"
	.string "{STR_VAR_1}!$"

gTVFindThatGamerText01::
	.string "{STR_VAR_1} {STR_VAR_2}(e)an ibili zen\n"
	.string "eta {STR_VAR_3} TXANPON irabazi.\p"
	.string "“{STR_VAR_1} iristen denean, prest\n"
	.string "eduki behar ditugu gure TXANPONAK.”\p"
	.string "Hori diote JOKOEN TXOKOKO langileek\n"
	.string "marmarka gure jokalaria joaten zaienean!\p"
	.string "Viewers, it's best to watch your COINS\n"
	.string "like {STR_VAR_1} if you visit the GAME\l"
	.string "CORNER and play the {STR_VAR_2} game.\p"
	.string "This is live from the GAME CORNER--\n"
	.string "where you can feel the excitement!\p"
	.string "That's all for today!$"

gTVFindThatGamerText02::
	.string "{STR_VAR_1} {STR_VAR_2}(e)an ibili zen\n"
	.string "eta {STR_VAR_3} TXANPON galdu.\p"
	.string "“{STR_VAR_1} etortzen denean, gure\n"
	.string "TXANPON salmenta igo egiten da.”\p"
	.string "Hori diote JOKOEN TXOKOKO langileek\n"
	.string "gure jokalaria joaten zaienean!$"

gTVFindThatGamerText03::
	.string "Ikusleok, zanidu zuen TXANPONAK\n"
	.string "{STR_VAR_1}(e)k bezala JOKOEN TXOKORA\l"
	.string "joan eta {STR_VAR_2}(e)an jolastuz gero.\p"
	.string "JOKOEN TXOKOTIK zuzenean--\n"
	.string "zirrara sentitzen den lekuan!\p"
	.string "Hori da dena gaurkoz!$"

gTVBreakingNewsText00::
	.string "AZKEN ORDUKO ALBISTEAK!$"

gTVBreakingNewsText01::
	.string "{STR_VAR_2} arraro bat harrapatu\n"
	.string "du {STR_VAR_1}(e)k!\p"
	.string "Zuzenean gaude {STR_VAR_3}\n"
	.string "inguruan!\p"
	.string "{STR_VAR_1} gai izan da duela gutxi\n"
	.string "{STR_VAR_2} arraro bat harrapatzeko!$"

gTVBreakingNewsText02::
	.string "{STR_VAR_1} eta {STR_VAR_2} topatu\n"
	.string "zirenean, ENTRENATZAILEAK\l"
	.string "{STR_VAR_3} atera zuen.$"

gTVBreakingNewsText03::
	.string "Borrokan erabilitako POKé BALL\n"
	.string "kopurua honakoa izan zen: {STR_VAR_1}.\p"
	.string "Azkenean, botatako azken {STR_VAR_2}\n"
	.string "izan zen POKéMONA harrapatu zuena.$"

gTVBreakingNewsText04::
	.string "Momentu horretan, {STR_VAR_2}\n"
	.string "eta {STR_VAR_1}(r)en zoriontasun\l"
	.string "oihuak batera entzun ziren.\p"
	.string "Esan behar dut, {STR_VAR_1}(e)k inbidia\n"
	.string "ematen dit. Nik ere oihu egin nahi dut.\p"
	.string "…Hementxe amaitzen da emisioa eszena\n"
	.string "zoriontsu honetatik!$"

gTVBreakingNewsText05::
	.string "{STR_VAR_1}(e)k ez du lortu {STR_VAR_2}\n"
	.string "arraro bat harrapatzea!\p"
	.string "Zuzenean gaude {STR_VAR_3}\n"
	.string "inguruan!\p"
	.string "Hemen izan zen {STR_VAR_1}(r)i\n"
	.string "{STR_VAR_2} arraoak ihes egin zionekoa!$"

gTVBreakingNewsText06::
	.string "{STR_VAR_1}(e)k {STR_VAR_2} arraroa\n"
	.string "aurkitu zuenean, ENTRENATZAILEAK\l"
	.string "{STR_VAR_3} atera zuen.$"

gTVBreakingNewsText07::
	.string "ENTRENATZAILEAK {STR_VAR_2}(r)i\n"
	.string "{STR_VAR_1} erasoa agindu zion.\p"
	.string "Nahi gabe, ordea, ENTRENATZAILEAK\n"
	.string "POKéMONA indargabetu zuen…$"

gTVBreakingNewsText12::
	.string "Hala ere, {STR_VAR_1} urduri jarri\n"
	.string "zen {STR_VAR_2} arraroa ikustean.\p"
	.string "Nahastuta, ENTRENATZAILEAK erasotzeko\n"
	.string "agindu zion {STR_VAR_3}(e)ri.\p"
	.string "Nahi gabe, ordea, ENTRENATZAILEAK\n"
	.string "POKéMONA indargabetu zuen…$"

gTVBreakingNewsText08::
	.string "Momentu horretan, {STR_VAR_2}\n"
	.string "eta {STR_VAR_1}(r)en amorruzko\l"
	.string "garrasiak entzun ziren…$"

gTVBreakingNewsText09::
	.string "Tamalez, {STR_VAR_1} POKé BALLIK\n"
	.string "gabe geratu zen.\p"
	.string "ENTRENATZAILEAK {STR_VAR_2}\n"
	.string "bereziarekin borroka eten behar izan zuen.\p"
	.string "Momentu horretan, {STR_VAR_3}\n"
	.string "eta {STR_VAR_1}(r)en amorruzko\l"
	.string "garrasiak entzun ziren…$"

gTVBreakingNewsText10::
	.string "Tamalez, {STR_VAR_2}(e)k ihes\n"
	.string "egin zuen bat-batean.\p"
	.string "Momentu horretan, {STR_VAR_3}\n"
	.string "eta {STR_VAR_1}(r)en amorruzko\l"
	.string "garrasiak entzun ziren…$"

gTVBreakingNewsText11::
	.string "Pena ematen dit {STR_VAR_1}(e)k.\n"
	.string "Ni ere amorruz betetzen nau egoerak.\p"
	.string "…Hementxe amaitzen da emisioa eszena\n"
	.string "triste honetatik!$"

gTVSecretBaseVisitText00::
	.string "Kaixo, lagunak!\n"
	.string "Iritsi da garaia BASE SEKRETUEN\l"
	.string "BISITA berri baterako.\p"
	.string "Gaur, {STR_VAR_1}(r)en BASE\n"
	.string "SEKRETUA bisitatuko dugu.\p"
	.string "Nola pertsonalizatu du {STR_VAR_1}(e)k\n"
	.string "bere BASE SEKRETUA?\p"
	.string "Ikus dezagun, bada!\n"
	.string "… … … … … …$"

gTVSecretBaseVisitText01::
	.string "Ene!\n"
	.string "Txundigarria!\p"
	.string "{STR_VAR_2} hau…\n"
	.string "Ez nuen espero horrelako ezer\l"
	.string "aurkitzea hemen!$"

gTVSecretBaseVisitText02::
	.string "Ene!\n"
	.string "Hau bai apartekoa!\p"
	.string "Ez dago inolako altzari edo\n"
	.string "bestelakorik hemen barrian!\p"
	.string "Jende normala ez litzateke ausartu\n"
	.string "ere egingo hau egiten!\p"
	.string "Sinplea da, bai, baina\n"
	.string "baita basatia ere!\p"
	.string "Zorionak nire partez, {STR_VAR_1}.\n"
	.string "Zuk ez beste inork ezin zuen hau egin!$"

gTVSecretBaseVisitText03::
	.string "Ene! Ikusten dut, bai!\n"
	.string "Argi eta garbi ikusi ere!\p"
	.string "{STR_VAR_2} hau egotea hemen…\n"
	.string "Mezu argia adierazten du!$"

gTVSecretBaseVisitText04::
	.string "Ene! Ikusten dut, bai!\n"
	.string "Argi eta garbi ikusi ere!\p"
	.string "Espazio hau nahita dago inolako\n"
	.string "objektu eta altzaririk gabe!\p"
	.string "Mezu argia adierazten du!$"

gTVSecretBaseVisitText05::
	.string "Ene bada!\p"
	.string "{STR_VAR_2} eta {STR_VAR_3}\n"
	.string "batera jarri izana!\p"
	.string "It's a dream combination if there\n"
	.string "ever was one!$"

gTVSecretBaseVisitText06::
	.string "Ene bada!\p"
	.string "{STR_VAR_2} honen kokapena\n"
	.string "justu hementxe…\p"
	.string "Bere presentziak BASE SEKRETU\n"
	.string "osoa betetzen du!$"

gTVSecretBaseVisitText07::
	.string "Ene bada!\p"
	.string "Hemen ez dago ezer kokatuta.\p"
	.string "Leku huts honek efektu\n"
	.string "izugarria du BASE SEKRETUAN.$"

gTVSecretBaseVisitText08::
	.string "Ene!\n"
	.string "Hemen dator {STR_VAR_1}!\l"
	.string "Desafia dezagun ENTRENATZAILEA!\p"
	.string "… … … … … …\n"
	.string "… … … … … …$"

gTVSecretBaseVisitText09::
	.string "Aiii…\n"
	.string "Aitortu behar dut, {STR_VAR_1}.\p"
	.string "ENTRENATZAILEAREN POKéMONEK benetan\n"
	.string "merezi zuten TXAPELDUN izatea.\p"
	.string "Argi eta garbi utzi zuten {STR_VAR_1}\n"
	.string "ENTRENATZAILE gogorra dela.\p"
	.string "Eta {STR_VAR_2}(e)k ezagutzen duela\n"
	.string "{STR_VAR_3} erasoa…\p"
	.string "{STR_VAR_1} ze motatako ENTRENATZAILEA\n"
	.string "den erakusten du.\p"
	.string "Asko ikasi dut, alajaina!$"

gTVSecretBaseVisitText10::
	.string "Iaaaja!\n"
	.string "Aitortu behar dut, {STR_VAR_1}.\p"
	.string "ENTRENATZAILEAREN POKéMONAK\n"
	.string "izugarri gogorrak dira!\p"
	.string "Argi eta garbi utzi zuten {STR_VAR_1}\n"
	.string "ENTRENATZAILE saiatua dela.\p"
	.string "Eta {STR_VAR_2}(e)k ezagutzen duela\n"
	.string "{STR_VAR_3} erasoa…\p"
	.string "{STR_VAR_1} ze motatako ENTRENATZAILEA\n"
	.string "den erakusten du.\p"
	.string "Asko ikasi dut, alajaina!$"

gTVSecretBaseVisitText11::
	.string "Uffff!\n"
	.string "Aitortu behar dut, {STR_VAR_1}.\p"
	.string "ENTRENATZAILEAREN POKéMONAK ondo\n"
	.string "orekatuta hezita daude.\p"
	.string "Argi eta garbi utzi zuten {STR_VAR_1}\n"
	.string "ENTRENATZAILE burutsua dela.\p"
	.string "Eta {STR_VAR_2}(e)k ezagutzen duela\n"
	.string "{STR_VAR_3} erasoa…\p"
	.string "{STR_VAR_1} ze motatako ENTRENATZAILEA\n"
	.string "den erakusten du.\p"
	.string "Asko ikasi dut, alajaina!$"

gTVSecretBaseVisitText12::
	.string "Bueno, bueno!\n"
	.string "Aitortu behar dut, {STR_VAR_1}.\p"
	.string "ENTRENATZAILEAREN POKéMONEK\n"
	.string "etorkizunerako potentziala daukate.\p"
	.string "{STR_VAR_1}(r)en itxaropen eta\n"
	.string "ametsak erakutsi zituzten.\p"
	.string "Eta {STR_VAR_2}(e)k ezagutzen duela\n"
	.string "{STR_VAR_3} erasoa…\p"
	.string "{STR_VAR_1} ze motatako ENTRENATZAILEA\n"
	.string "den erakusten du.\p"
	.string "Asko ikasi dut, alajaina!$"

gTVSecretBaseVisitText13::
	.string "Esan beharra dut, hori bai hori\n"
	.string "BASE SEKRETU paregabea!\p"
	.string "Ikusleok, aukera baduzue,\n"
	.string "bisitatu {STR_VAR_1}(r)en BASE SEKRETUA.\p"
	.string "Hurrengora arte, ondo segi!$"

gTVPokemonLotteryWinnerFlashReportText00::
	.string "Zirraragarria!\n"
	.string "Dramatikoa!\p"
	.string "POKéMON LOTERIA da\n"
	.string "IRABAZLEAREN IRAGARPENA!\p"
	.string "Kaixo! Zuzenean gaude POKéMON\n"
	.string "LOTERIAREN TXOKOTIK, UR-LILI\l"
	.string "hiriko ZENTRO KOMERTZIALEKO\l"
	.string "beheko solairutik!\p"
	.string "Ohi den bezala, beste zortedun\n"
	.string "ENTRENATZAILE bat agertu da gaur!\p"
	.string "ENTRENATZAILEAREN izena…\n"
	.string "{STR_VAR_1}!\p"
	.string "{STR_VAR_1} izan da {STR_VAR_2}. saria\n"
	.string "eskuratu eta {STR_VAR_3} irabazi duena!\p"
	.string "{STR_VAR_1}!\n"
	.string "Zorionak!\p"
	.string "Ikusleok, ez soilik begiratu,\n"
	.string "zuek ere martxan jarri!\p"
	.string "UR-LILIKO ZENTRO KOMERTZIALEKO\n"
	.string "langileak zure zain gaude!\p"
	.string "Hau zuzeneko emisio bat izan da\n"
	.string "UR-LILIKO ZENTRO KOMERTZIALETIK,\l"
	.string "HOENN osoko salgai onenak ditugu\l"
	.string "hemen!$"

gTVThePokemonBattleSeminarText00::
	.string "POKéMON BORROKA SEMINARIOA!\p"
	.string "Borrokak aztertzen ditugu\n"
	.string "horietatik ikasten saiatzeko.\p"
	.string "Gaurkoan aztertuko dugun borrokan\n"
	.string "{STR_VAR_1} da protagonista.\p"
	.string "{STR_VAR_1}(r)en {STR_VAR_2}\n"
	.string "{STR_VAR_3} baten aurka ari zen…$"

gTVThePokemonBattleSeminarText01::
	.string "Eta {STR_VAR_3} erasoa erabili zuen\n"
	.string "{STR_VAR_2}(r)en aurka…\p"
	.string "Ene… {STR_VAR_1}!\n"
	.string "Hori da egin behar ez dena, aizue!$"

gTVThePokemonBattleSeminarText02::
	.string "Eraso oker horrez gain,\n"
	.string "ENTRENATZAILEAREN {STR_VAR_1}(e)k$"

gTVThePokemonBattleSeminarText03::
	.string "bazekizkien {STR_VAR_1}, {STR_VAR_2},\n"
	.string "eta {STR_VAR_3} erasoak.$"

gTVThePokemonBattleSeminarText04::
	.string "bazekizkien {STR_VAR_1} eta\n"
	.string "{STR_VAR_2} erasoak.$"

gTVThePokemonBattleSeminarText05::
	.string "bazekien {STR_VAR_2} erasoa.$"

gTVThePokemonBattleSeminarText06::
	.string "beraz, egoera horretan zein eraso\n"
	.string "erabili behar zuen ENTRENATZAILEAK?\p"
	.string "… … … … … …\n"
	.string "{STR_VAR_1} erasoa!\p"
	.string "{STR_VAR_1} erasoa askoz hobea\n"
	.string "zatekeen {STR_VAR_2} baino.\p"
	.string "Ikusleok, ikasi ezazue adibide\n"
	.string "honetatik eta tentuz borrokatu!\p"
	.string "Hurrengora arte, agur!$"

gTVTrainerFanClubText00::
	.string "Ea ba, guztiok batera!\n"
	.string "ENTRENATZAILE FAN KLUBA!\p"
	.string "ZM: Zelan dabil jendea'?\n"
	.string "Gaurkoan hiper famatua den {STR_VAR_1}\l"
	.string "ENTRENATZAILEAREN fanak ditugu gurean!\p"
	.string "FANAK: Wrooooooaaaaah!\p"
	.string "FANAK: {STR_VAR_1}!\p"
	.string "ZM: Guztiok!\n"
	.string "Zenbat atsegin duzue {STR_VAR_1}?!\p"
	.string "FANAK: Maite dugu {STR_VAR_1}!\p"
	.string "ZM: berak egiten duen zer\n"
	.string "gustatzen zaizue gehien?!$"

gTVTrainerFanClubText01::
	.string "FANAK: POKé BALLAK botatzeko duen\n"
	.string "estilo paregabea!$"

gTVTrainerFanClubText02::
	.string "FANAK: Bere korrika egiteko modua!$"

gTVTrainerFanClubText03::
	.string "FANAK: Momentu zailei aurre\n"
	.string "egiteko duen indarra!$"

gTVTrainerFanClubText04::
	.string "FANAK: POKéMONEN inguruan duen\n"
	.string "jakinduria erraldoia!$"

gTVTrainerFanClubText05::
	.string "FANAK: POKéMONAK tratatzeko duen\n"
	.string "jatortasun eta goxotasuna!$"

gTVTrainerFanClubText06::
	.string "FANAK: BIZIKLETAN ibiltzeko duen\n"
	.string "abilezia paregabea!$"

gTVTrainerFanClubText07::
	.string "FANAK: Itemak erosteko duen estilo\n"
	.string "sinesgaitza!$"

gTVTrainerFanClubText08::
	.string "FANAK: POKéMONEI ezizenak jartzeko\n"
	.string "duen era polita!$"

gTVTrainerFanClubText09::
	.string "FANAK: BASE SEKRETUA apaintzeko\n"
	.string "duen estilo bikaina!$"

gTVTrainerFanClubText10::
	.string "FANAK: TMAK erabiltzeko duen\n"
	.string "forma burutsua!$"

gTVTrainerFanClubText11::
	.string "ZM: Ikus dezakezuenez, {STR_VAR_1}\n"
	.string "modan dago! Bene-benetan modan!\p"
	.string "{STR_VAR_1}(r)en FANEN\n"
	.string "artean badute eslogan bat!\p"
	.string "ZM: Nik {STR_VAR_1} esatean,\n"
	.string "zuek diozue…\p"
	.string "FANAK: {STR_VAR_2}!\p"
	.string "FANAK: {STR_VAR_3}!\p"
	.string "FANAK: {STR_VAR_2}!\p"
	.string "FANAK: {STR_VAR_3}!\p"
	.string "ZM: Hori da, norbaitek esaten badu,\n"
	.string "“{STR_VAR_1}”…\p"
	.string "Erantzun, indartsu, “{STR_VAR_2}\n"
	.string "{STR_VAR_3}!”\p"
	.string "Izugarri ondo geratzen da!\n"
	.string "Uler dezaket horrenbeste FAN\l"
	.string "izatea {STR_VAR_1}(e)k!\p"
	.string "Orain zure txanda da, ikusle!\n"
	.string "Denok batera!\p"
	.string "ZM: Nik {STR_VAR_1} esatean,\n"
	.string "zuek diozue…\p"
	.string "FANAK: {STR_VAR_2}!\p"
	.string "FANAK: {STR_VAR_3}!\p"
	.string "FANAK: {STR_VAR_2}!\p"
	.string "FANAK: {STR_VAR_3}!\p"
	.string "ZM: Eskerrik asko etortzeagatik,\n"
	.string "{STR_VAR_1}(r)en FAN gartsuok!\l"
	.string "Hori izan da dena! Hurrengora arte!\p"
	.string "ZM: Nik {STR_VAR_1} esatean,\n"
	.string "zuek diozue…\p"
	.string "FANAK: {STR_VAR_2}!\p"
	.string "FANAK: {STR_VAR_3}!$"

TVSpotTheCuties_Text_Intro::
	.string "AURKITU EDERRENAK!\n"
	.string "ZINTADUN POKéMONAK!\p"
	.string "Kaixo, ikusle maiteok!\p"
	.string "Badakit ados zaudetela, baina POKéMON\n"
	.string "bat ZINTA bat jantzita, miragarria da!\p"
	.string "Gaur, zuekin konpartitu nahi dut\n"
	.string "hirian paseatzen ari nintzela ikusi\l"
	.string "nuen POKéMON xarmant bat.\p"
	.string "Gaurkoan aurkeztuko dugun POKéMONA\n"
	.string "da {STR_VAR_1}(r)en {STR_VAR_2}.$"

TVSpotTheCuties_Text_RibbonsLow::
	.string "{STR_VAR_2}(r)en ZINTA\n"
	.string "kopurua {STR_VAR_3} da.\p"
	.string "Argi uzten du {STR_VAR_1}\n"
	.string "oso POKéMON zalea dela.$"

TVSpotTheCuties_Text_RibbonsMid::
	.string "{STR_VAR_2}(r)en zinta kopurua da…\n"
	.string "{STR_VAR_3} ZINTA itzel!\p"
	.string "Erakusten du {STR_VAR_1}(e)k baduela\n"
	.string "POKéMONEKIKO ardura!$"

TVSpotTheCuties_Text_RibbonsHigh::
	.string "{STR_VAR_2}(r)en zinta kopurua da…\n"
	.string "{STR_VAR_3} ZINTA bikain!\p"
	.string "Erakusten du {STR_VAR_1}(e)k baduela\n"
	.string "bildumagile sen erraldoia!$"

TVSpotTheCuties_Text_RibbonIntro::
	.string "Ikus ditzagun arreta gehiagoz\n"
	.string "{STR_VAR_2}(r)en ZINTA guztiak.$"

TVSpotTheCuties_Text_RibbonChampion::
	.string "TXAPELDUNEN ZINTA bereziki da\n"
	.string "deigarria.\p"
	.string "{STR_VAR_2} OSPEAREN ARETORA iritsi\n"
	.string "zenean jaso zuen.\p"
	.string "{STR_VAR_2}(r)en ausardia erakusten\n"
	.string "du argi eta garbi.\p"
	.string "{STR_VAR_2} eta TXAPELDUNEN ZINTA!\n"
	.string "Hori bai konbinazio aparta!$"

TVSpotTheCuties_Text_RibbonCool::
	.string "KARSIMADUNEN ZINTA bereziki da\n"
	.string "deigarria.\p"
	.string "{STR_VAR_2}(e)k KARISMA LEHIAKETA\n"
	.string "bat irabaztean lortu zuen.\p"
	.string "{STR_VAR_2}(r)en karisma erakusten\n"
	.string "du argi eta garbi.\p"
	.string "{STR_VAR_2} eta KARISMA ZINTA!\n"
	.string "Hori bai konbinazio aparta!$"

TVSpotTheCuties_Text_RibbonBeauty::
	.string "EDERTASUN ZINTA bereziki da\n"
	.string "deigarria.\p"
	.string "{STR_VAR_2}(e)k EDERTASUN LEHIAKETA\n"
	.string "bat irabaztean lortu zuen.\p"
	.string "{STR_VAR_2}(r)en edertasuna erakusten\n"
	.string "du argi eta garbi.\p"
	.string "{STR_VAR_2} eta EDERTASUN ZINTA!\n"
	.string "Hori bai konbinazio aparta!$"

TVSpotTheCuties_Text_RibbonCute::
	.string "POLITENEN ZINTA bereziki da\n"
	.string "deigarria.\p"
	.string "{STR_VAR_2}(e)k POLITASUN LEHIAKETA\n"
	.string "bat irabaztean lortu zuen.\p"
	.string "{STR_VAR_2}(r)en politasuna erakusten\n"
	.string "du argi eta garbi.\p"
	.string "{STR_VAR_2} eta POLITENEN ZINTA!\n"
	.string "Hori bai konbinazio aparta!$"

TVSpotTheCuties_Text_RibbonSmart::
	.string "AZKARRENEN ZINTA bereziki da\n"
	.string "deigarria.\p"
	.string "{STR_VAR_2}(e)k AZKARTASUN LEHIAKETA\n"
	.string "bat irabaztean lortu zuen.\p"
	.string "{STR_VAR_2}(r)en azkartasuna erakusten\n"
	.string "du argi eta garbi.\p"
	.string "{STR_VAR_2} eta AZKARRENEN ZINTA!\n"
	.string "Hori bai konbinazio aparta!$"

TVSpotTheCuties_Text_RibbonTough::
	.string "GOGORRENEN ZINTA bereziki da\n"
	.string "deigarria.\p"
	.string "{STR_VAR_2}(e)k GOGORTASUN LEHIAKETA\n"
	.string "bat irabaztean lortu zuen.\p"
	.string "{STR_VAR_2}(r)en gogortasuna erakusten\n"
	.string "du argi eta garbi.\p"
	.string "{STR_VAR_2} eta GOGORRENEN ZINTA!\n"
	.string "Hori bai konbinazio aparta!$"

TVSpotTheCuties_Text_RibbonWinning::
	.string "IRABAZLEAREN ZINTA bereziki da\n"
	.string "deigarria.\p"
	.string "{STR_VAR_2}(e)k BORROKA DORREKO\n"
	.string "balentriengatik lortu zuen.\p"
	.string "{STR_VAR_2}(r)en boterea erakusten\n"
	.string "du argi eta garbi.\p"
	.string "{STR_VAR_2} eta IRABAZLEAREN ZINTA!\n"
	.string "Hori bai konbinazio aparta!$"

TVSpotTheCuties_Text_RibbonVictory::
	.string "GARAIPEN ZINTA bereziki da\n"
	.string "deigarria.\p"
	.string "{STR_VAR_2}(e)k BORROKA DORREKO\n"
	.string "balentriengatik lortu zuen.\p"
	.string "{STR_VAR_2}(r)en botere paregabea\n"
	.string "erakusten du argi eta garbi.\p"
	.string "{STR_VAR_2} eta GARAIPEN ZINTA!\n"
	.string "Hori bai konbinazio aparta!$"

TVSpotTheCuties_Text_RibbonArtist::
	.string "ARTISTEN ZINTA bereziki da\n"
	.string "deigarria.\p"
	.string "{STR_VAR_2} artista batentzako modelo\n"
	.string "izateagatik lortu zuen.\p"
	.string "{STR_VAR_2}(r)en pop-izar baten xarma\n"
	.string "erakusten du argi eta garbi.\p"
	.string "{STR_VAR_2} eta ARTISTEN ZINTA!\n"
	.string "Hori bai konbinazio aparta!$"

TVSpotTheCuties_Text_RibbonEffort::
	.string "LANGILEENEN ZINTA bereziki da\n"
	.string "deigarria.\p"
	.string "{STR_VAR_2} langile bikaina\n"
	.string "delako lortu zuen.\p"
	.string "{STR_VAR_2}(r)en determinazioa erakusten\n"
	.string "du argi eta garbi.\p"
	.string "{STR_VAR_2} eta LANGILEENEN ZINTA!\n"
	.string "Hori bai konbinazio aparta!$"

TVSpotTheCuties_Text_Outro::
	.string "…Ene…\p"
	.string "ZINTAK and POKéMONAK…\n"
	.string "Bikote galanta egiten dute!\p"
	.string "Banoa konortea galdu aurretik.\n"
	.string "Hurrengora arte!$"

gTVPokemonNewsBattleFrontierText00::
	.string "Ongi etorri!\n"
	.string "Iritsi da POKéMON ALBISTEEN garaia.\p"
	.string "BORROKA FRONTETIK albiste\n"
	.string "gogoangarriak iritsi zaizkigu.$"

gTVPokemonNewsBattleFrontierText01::
	.string "{STR_VAR_1} ENTRENATZAILEAK errekor\n"
	.string "berria ezarri du {STR_VAR_2} garaipen\l"
	.string "jarraian lortuta BORROKA DORREKO\l"
	.string "BAKARKAKO BORROKA GELETAN.\p"
	.string "Zorionak, {STR_VAR_1}!$"

gTVPokemonNewsBattleFrontierText02::
	.string "{STR_VAR_1} ENTRENATZAILEAK errekor\n"
	.string "berria ezarri du {STR_VAR_2} garaipen\l"
	.string "jarraian lortuta BORROKA DORREKO\l"
	.string "BINAKAKO BORROKA GELETAN.\p"
	.string "Zorionak, {STR_VAR_1}!$"

gTVPokemonNewsBattleFrontierText03::
	.string "{STR_VAR_1} ENTRENATZAILEAK errekor\n"
	.string "berria ezarri du {STR_VAR_2} garaipen\l"
	.string "jarraian lortuta BORROKA DORREKO\l"
	.string "MULTI BORROKA GELETAN.\p"
	.string "Zorionak, {STR_VAR_1}!$"

gTVPokemonNewsBattleFrontierText04::
	.string "{STR_VAR_1} ENTRENATZAILEAK errekor\n"
	.string "berria ezarri du {STR_VAR_2} garaipen\l"
	.string "jarraian lortuta BORROKA DORREKO\l"
	.string "LINK MULTI BORROKA GELETAN.\p"
	.string "Zorionak, {STR_VAR_1}!$"

gTVPokemonNewsBattleFrontierText05::
	.string "{STR_VAR_1} ENTRENATZAILEAK errekor\n"
	.string "berria ezarri du {STR_VAR_2} txapelketa\l"
	.string "jarraian irabazita BORROKA DOMOKO\l"
	.string "BAKARKAKO BORROKA Txapelketan.\p"
	.string "Zorionak, {STR_VAR_1}!$"

gTVPokemonNewsBattleFrontierText06::
	.string "{STR_VAR_1} ENTRENATZAILEAK errekor\n"
	.string "berria ezarri du {STR_VAR_2} txapelketa\l"
	.string "jarraian irabazita BORROKA DOMOKO\l"
	.string "BINAKAKO BORROKA Txapelketan.\p"
	.string "Zorionak, {STR_VAR_1}!$"

gTVPokemonNewsBattleFrontierText07::
	.string "{STR_VAR_1} ENTRENATZAILEAK errekor\n"
	.string "berria ezarri du {STR_VAR_2} garaipen\l"
	.string "jarraian lortuta BORROKA FABRIKAKO\l"
	.string "Banakako Truke Borroka Txapelketan.\p"
	.string "Zorionak, {STR_VAR_1}!$"

gTVPokemonNewsBattleFrontierText08::
	.string "{STR_VAR_1} ENTRENATZAILEAK errekor\n"
	.string "berria ezarri du {STR_VAR_2} garaipen\l"
	.string "jarraian lortuta BORROKA FABRIKAKO\l"
	.string "Binakako Truke Borroka Txapelketan.\p"
	.string "Zorionak, {STR_VAR_1}!$"

gTVPokemonNewsBattleFrontierText09::
	.string "{STR_VAR_1} ENTRENATZAILEAK errekor\n"
	.string "berria ezarri du {STR_VAR_2} gela\l"
	.string "gaindituta BORROKA SUGEKO\l"
	.string "Aukera Borrokako Txapelketan.\p"
	.string "Zorionak, {STR_VAR_1}!$"

gTVPokemonNewsBattleFrontierText10::
	.string "{STR_VAR_1} ENTRENATZAILEAK errekor\n"
	.string "berria ezarri du {STR_VAR_2} garaipen\l"
	.string "jarraian lortuta BORROKA ARENAKO\l"
	.string "Set KO Txapelketan.\p"
	.string "Zorionak, {STR_VAR_1}!$"

gTVPokemonNewsBattleFrontierText11::
	.string "{STR_VAR_1} ENTRENATZAILEAK errekor\n"
	.string "berria ezarri du {STR_VAR_2} garaipen\l"
	.string "jarraian lortuta BORROKA JAUREGIKO\l"
	.string "BAKARKAKO BORROKA HALLEKO txapelketan.\p"
	.string "Zorionak, {STR_VAR_1}!$"

gTVPokemonNewsBattleFrontierText12::
	.string "{STR_VAR_1} ENTRENATZAILEAK errekor\n"
	.string "berria ezarri du {STR_VAR_2} garaipen\l"
	.string "jarraian lortuta BORROKA JAUREGIKO\l"
	.string "BINAKAKO BORROKA HALLEKO txapelketan.\p"
	.string "Zorionak, {STR_VAR_1}!$"

gTVPokemonNewsBattleFrontierText13::
	.string "{STR_VAR_1} ENTRENATZAILEAK errekor\n"
	.string "berria ezarri du {STR_VAR_2} gela\l"
	.string "gaindituta BORROKA PIRAMIDEKO\l"
	.string "Bilaketa Borrokako txapelketan.\p"
	.string "Zorionak, {STR_VAR_1}!$"

gTVPokemonNewsBattleFrontierText14::
	.string "Eta hiru POKéMONEI, {STR_VAR_1},\n"
	.string "{STR_VAR_2} eta {STR_VAR_3}!\p"
	.string "Zorionak horrelako errekorra\n"
	.string "lortzeagatik!$"

gTVPokemonNewsBattleFrontierText15::
	.string "Eta bi POKéMONEI, {STR_VAR_1}\n"
	.string "eta {STR_VAR_2}!\p"
	.string "Zorionak horrelako errekorra\n"
	.string "lortzeagatik!$"

gTVPokemonNewsBattleFrontierText16::
	.string "Eta lau POKéMONEI: {STR_VAR_1}!\p"
	.string "{STR_VAR_2}!\p"
	.string "{STR_VAR_3}!$"

gTVPokemonNewsBattleFrontierText17::
	.string "Eta {STR_VAR_1}!\p"
	.string "Zorionak horrelako errekorra\n"
	.string "lortzeagatik!$"

gTVPokemonNewsBattleFrontierText18::
	.string "Espero dezagun {STR_VAR_1}(e)k eta\n"
	.string "bere POKéMON leialek halako errekor\l"
	.string "eta balentria gehiago lortuko dituztela!\p"
	.string "Horiek izan dira POKéMON ALBISTEAK!$"

gTVWhatsNo1InHoennTodayText00::
	.string "ZEIN DA GAUR ONENA HOENNEN?\n"
	.string "Bai, lagunok, iritsi da garaia!\p"
	.string "Kaixo, ikusleok! Ari al zarete\n"
	.string "zabiltzatenean dena ematen?\p"
	.string "Ikusi dezagun zein ENTRENATZAILE\n"
	.string "izan den guarko onena!\p"
	.string "Gaurko ENTRENATZAILE ONENA\n"
	.string "{STR_VAR_1} da!$"

gTVWhatsNo1InHoennTodayText01::
	.string "Egun bakarrean, {STR_VAR_1} MAKINA\n"
	.string "TXANPONJALEETAN {STR_VAR_2} aldiz ibili da.\p"
	.string "Jolasten ari zela, {STR_VAR_1}(e)k\n"
	.string "omen zioen, “Niretzat, gurpil hauek\l"
	.string "ez dute birarik ere ematen…”\l"
	.string "Interesgarria ezta??$"

gTVWhatsNo1InHoennTodayText02::
	.string "Egun bakarrean, {STR_VAR_1} JOKOEN\n"
	.string "TXOKOKO ERRULETAN ibili da\l"
	.string "{STR_VAR_2} aldiz.\p"
	.string "Jolasten ari zela, {STR_VAR_1}(e)k\n"
	.string "oihukatu zuen “Bolek erabaki dezatela!”\p"
	.string "ENTRENATZAILEAREN begiak eta\n"
	.string "aurpegia guztiz kontzentratuta zeuden.$"

gTVWhatsNo1InHoennTodayText03::
	.string "Egun bakarrean, {STR_VAR_1} POKéMON\n"
	.string "basatiekin borrokatu da {STR_VAR_2} aldiz!\p"
	.string "Dirudienez, {STR_VAR_1}(r)en POKéMONAK\n"
	.string "inoiz baino indartsuagoak dira.\p"
	.string "Edonon, edonola eta edonoiz, borrokarako\n"
	.string "prest daude beti!$"

gTVWhatsNo1InHoennTodayText04::
	.string "Egun bakarrean, {STR_VAR_1}(e)k BAIA\n"
	.string "NAHASLEA biratu zuen {STR_VAR_2} aldiz!\p"
	.string "Bukaeran, {STR_VAR_1} pixka bat\n"
	.string "zorabiatuta zegoela zirudien.\p"
	.string "ENTRENATZAILEA balantzaka zebilen\n"
	.string "SPINDA bat bezala!$"

gTVWhatsNo1InHoennTodayText05::
	.string "Egun bakarrean, {STR_VAR_1}(e)k\n"
	.string "{STR_VAR_2} BAIA landatu zituen!\p"
	.string "Ondorioz, {STR_VAR_1}(r)en erropa\n"
	.string "lurrez zikindu zen goitik behera.\p"
	.string "ENTRENATZAILEAK landatutako tokietan\n"
	.string "loreak zabaldu dira bizi-bizi.\p"
	.string "Loreak pertsonen emozioak lasaitzeko\n"
	.string "onak omen dira, gainera.$"

gTVWhatsNo1InHoennTodayText06::
	.string "Egun bakarrean, {STR_VAR_1}(e)k\n"
	.string "{STR_VAR_2} BAIA jaso zituen!\p"
	.string "{STR_VAR_1}(r)en POLTSAN horrenbeste\n"
	.string "BAIA zeudenez, ENTRENATZAILEAK ezin\l"
	.string "zuen ia ibili ere egin azkenean!$"

gTVWhatsNo1InHoennTodayText07::
	.string "Egun bakarrean, {STR_VAR_1}(e)k\n"
	.string "{STR_VAR_2} Borroka Puntu lortu zituen!\p"
	.string "Ondoren, {STR_VAR_1} Borroka Puntu\n"
	.string "hauek trukatzen ikusi zuten\l"
	.string "item bikain edo apaingarri polit\l"
	.string "bat lortzeko.\p"
	.string "ENTRENATZAILEA ezin erabaki ibili\n"
	.string "omen zen horrenbeste aukerarekin.$"

gTVWhatsNo1InHoennTodayText08::
	.string "Ez al da izugarria!\p"
	.string "{STR_VAR_1}!\n"
	.string "Zu zara gaurko ENTRENATZAILE onena!\p"
	.string "Ikusleok, ikusi {STR_VAR_1} eta ikasi!\n"
	.string "Zuek ere izan zaitezkete onenak egunen batean!$"

TVSecretBaseSecrets_Text_Intro::
	.string "BASE SEKRETUEN SEKRETUAK!\p"
	.string "Zer egiten dute ENTRENATZAILEEK BASE\n"
	.string "SEKRETUEN babesean?\p"
	.string "Gaurkoan, {STR_VAR_1}(r)en BASE\n"
	.string "SEKRETUA aztertuko dugu.\p"
	.string "Zer? Badirudi {STR_VAR_2} etorri\n"
	.string "dela bisitan.\p"
	.string "Ikus dezagun, beraz!\p"
	.string "Zer egingo du {STR_VAR_2}(e)k?$"

TVSecretBaseSecrets_Text_WhatWillPlayerDoNext1::
	.string "Zer egingo du {STR_VAR_2}(e)k orain?$"

TVSecretBaseSecrets_Text_WhatWillPlayerDoNext2::
	.string "Eta orain, zer egingo du {STR_VAR_2}(e)k?$"

TVSecretBaseSecrets_Text_TookXStepsBeforeLeaving::
	.string "Azkenean, {STR_VAR_2}(e)k {STR_VAR_3} pausu\n"
	.string "eman ditu {STR_VAR_1}(r)en BASE SEKRETUAN\l"
	.string "joan aurretik.$"

TVSecretBaseSecrets_Text_BaseFailedToInterestPlayer::
	.string "Hmm…\p"
	.string "Badirudi {STR_VAR_1}(r)en BASE SEKRETUA\n"
	.string "ez zaiola asko gustatu {STR_VAR_2}(e)ri…$"

TVSecretBaseSecrets_Text_PlayerEnjoyedBase::
	.string "{STR_VAR_2}(e)k goitik behera miatu du\n"
	.string "{STR_VAR_1}(r)en BASE SEKRETUA.$"

TVSecretBaseSecrets_Text_PlayerHugeFanOfBase::
	.string "{STR_VAR_2}(e)ri asko gustatu zaiola\n"
	.string "dirudi {STR_VAR_1}(r)en\l"
	.string "BASE SEKRETUA.$"

TVSecretBaseSecrets_Text_Outro::
	.string "Ikusleek ere ikusi nahi dute agian\n"
	.string "{STR_VAR_1}(r)en BASE SEKRETUA.\p"
	.string "Ez galdu hurrengo atala, beste BASE\n"
	.string "SEKRETU bat ikusiko dugu! Hurrengora arte!$"

TVSecretBaseSecrets_Text_StoppedMoving1::
	.string "Bisitaria gelditu egin da!\p"
	.string "Bisitaria ez da batere mugitzen ari!\p"
	.string "{STR_VAR_1}(r)en BASE SEKRETUA\n"
	.string "horren arrunta al da?$"

TVSecretBaseSecrets_Text_StoppedMoving2::
	.string "Bisitaria gelditu egin da!\p"
	.string "Bisitaria ez da batere mugitzen ari!\p"
	.string "Nekatuta ote dago?\n"
	.string "Nazkatu egin ote da?$"

TVSecretBaseSecrets_Text_UsedChair::
	.string "Bisitaria aulki batean jarri da!\n"
	.string "Bisitaria eserita dago!\p"
	.string "Begira zeinen gustora dagoen!\p"
	.string "Aulki hori izugarri erosoa izango\n"
	.string "da horrela geratu bada!$"

TVSecretBaseSecrets_Text_UsedBalloon::
	.string "Bisitaria globo baten aurka joan da!\p"
	.string "Lehertu egin da!\n"
	.string "Ene bada, globoak eztanda egin du!\p"
	.string "Bisitariak ezusteko handia\n"
	.string "hartu du zaratarekin!$"

TVSecretBaseSecrets_Text_UsedTent::
	.string "Bisitaria DENDA batean sartu da!\p"
	.string "Bisitaria korrika dabil!\p"
	.string "Ene bada, bisitaria saltoka dabil!\p"
	.string "Badirudi DENDAREN tamainak harrituta\n"
	.string "utzi duela!$"

TVSecretBaseSecrets_Text_UsedPlant::
	.string "Bisitaria lorontzi bati\n"
	.string "begira dago!\p"
	.string "Bisitariak oso gustu ona\n"
	.string "eta heldua du!$"

TVSecretBaseSecrets_Text_UsedGoldShield::
	.string "Bisitaria URREZKO EZKUTU\n"
	.string "bati begira dago!\p"
	.string "Bisitariaren begiak liluraz\n"
	.string "gainezka dirdirka ari dira!$"

TVSecretBaseSecrets_Text_UsedSilverShield::
	.string "Bisitaria ZILARREZKO EZKUTU\n"
	.string "bati begira dago!\p"
	.string "Bisitariak harrituta dirudi!$"

TVSecretBaseSecrets_Text_UsedGlassOrnament::
	.string "Bisitaria KRISTALEZKO APAINGARRI\n"
	.string "bati begira dago!\p"
	.string "Ai, ez!\p"
	.string "Bisitaria ikutzen ari da!\p"
	.string "Hatz markaz beteta geratu\n"
	.string "da azkenean…$"

TVSecretBaseSecrets_Text_UsedTV::
	.string "Bisitaria telebista ikusten ari da!\p"
	.string "Telebistazalea da dudarik gabe!$"

TVSecretBaseSecrets_Text_UsedMudBall::
	.string "Bisitariak LOKATZ BOLA bat zapaldu du!\p"
	.string "Bisitariak pozarren dirudi!$"

TVSecretBaseSecrets_Text_UsedBag::
	.string "…Ene?\p"
	.string "Bisitariak bere POLTSAN sartu\n"
	.string "du eskua, zerbaiten bila!\p"
	.string "Bisitariak {STR_VAR_2} bat\n"
	.string "atera du!\p"
	.string "begira bere irribarrea {STR_VAR_2}\n"
	.string "hori erakusten duen bitartean!\p"
	.string "Telebistako iragarki bat dirudi!$"

TVSecretBaseSecrets_Text_UsedCushion::
	.string "Bisitariak kuxin bat hartu eta…$"

TVSecretBaseSecrets_Text_HitCushion::
	.string "…hari joka hasi da!\p"
	.string "Estresatuta ote dago bisitaria?$"

TVSecretBaseSecrets_Text_HuggedCushion::
	.string "…besarkatu egin du!\p"
	.string "Zeozerengatik zoriontsu egongo\n"
	.string "al da?$"

TVSecretBaseSecrets_Text_BattledWon::
	.string "Bisitaria {STR_VAR_1}(r)ekin\n"
	.string "hizketan ari da!\p"
	.string "Badirudi elkarrekin borrokatuko\n"
	.string "direla!\p"
	.string "Eta…\p"
	.string "Bisitaria!\n"
	.string "Bisitaria izan da garailea!\p"
	.string "Bisitaria dantzan hasi da\n"
	.string "irabazi duelako!$"

TVSecretBaseSecrets_Text_BattledLost::
	.string "Bisitaria {STR_VAR_1}(r)ekin\n"
	.string "hizketan ari da!\p"
	.string "Badirudi elkarrekin borrokatuko\n"
	.string "direla!\p"
	.string "Eta…\p"
	.string "{STR_VAR_1} da garailea!\n"
	.string "Bisitariak galdu du!\p"
	.string "Bisitaria burumakur geratu da!$"

TVSecretBaseSecrets_Text_DeclinedBattle::
	.string "Bisitaria {STR_VAR_1}(r)ekin\n"
	.string "hizketan ari da!\p"
	.string "Badirudi elkarrekin borrokatuko\n"
	.string "direla!\p"
	.string "Eta…\p"
	.string "Ez, bisitariak ezezkoa eman du!\p"
	.string "Ez dute borrokatuko dirudienez!\p"
	.string "Ez ote zaio {STR_VAR_1} interesgarria\n"
	.string "iruditu bisitariari?$"

TVSecretBaseSecrets_Text_UsedPoster::
	.string "Bisitaria poster bati begira\n"
	.string "geratu da!\p"
	.string "Gustatu egin ote zaio bisitariari\n"
	.string "posterra?\p"
	.string "…Baina… Bisitariaren begiradan\n"
	.string "zerbait kezkagarria ikusi daiteke.$"

TVSecretBaseSecrets_Text_UsedNoteMat::
	.string "Bisitariak NOTA ALFONBRA bat zapaLdu du!\p"
	.string "…Hmm…\n"
	.string "Bisitariak abesti polit bat jo du!$"

TVSecretBaseSecrets_Text_BattledDraw::
	.string "Bisitaria hizketan ari da\n"
	.string "{STR_VAR_1}(r)ekin!\p"
	.string "Borrokatu egingo dutela\n"
	.string "dirudi!\p"
	.string "Eta…\p"
	.string "Berdindu egin dute!\n"
	.string "Ez dago irabazlerik!\p"
	.string "Bi ENTRENATZAILEEK desengainu\n"
	.string "handia hartu dute!$"

TVSecretBaseSecrets_Text_UsedSpinMat::
	.string "Bisitariak BIRA ALFONBRA bat\n"
	.string "zapaldu du!\p"
	.string "Bisitaria zorabiatu egin da!\p"
	.string "Bisitaria balantzaka hasi da!\n"
	.string "Kontuz!$"

TVSecretBaseSecrets_Text_UsedSandOrnament::
	.string "Bisitaria HAREAZKO APAINGARRI\n"
	.string "bati begira dago!\p"
	.string "Ene!\p"
	.string "Hautsi egin da!\n"
	.string "Hauts bihurtu da!\p"
	.string "Bisitariak errudun aurpegi\n"
	.string "tristea du!$"

TVSecretBaseSecrets_Text_UsedDesk::
	.string "Bisitariak hatz bat pasa du\n"
	.string "idazmahaiaren gainetik!\p"
	.string "Dirudienez, bisitariak ez du hautsa\n"
	.string "atsegin!\p"
	.string "Bisitariak garbitasunari garrantzia\n"
	.string "harrigarria ematen dio!$"

TVSecretBaseSecrets_Text_UsedBrick::
	.string "Bisitaria ADREILU bati begira dago!\p"
	.string "Agian bisitaria ADREILU gaineko\n"
	.string "objektua aztertzen ari da.$"

TVSecretBaseSecrets_Text_UsedSolidBoard::
	.string "Bisitaria TAULA SOLIDO baten\n"
	.string "gainean ibiltzen ari da.\p"
	.string "Bisitaria behera begira ari da uneoro.\p"
	.string "Bisitaria kontuz eta lotsa handiz\n"
	.string "ari da ibiltzen!$"

TVSecretBaseSecrets_Text_UsedFence::
	.string "Bisitaria HESI bati begira dago\n"
	.string "adi-adi!\p"
	.string "tranpa bat egiteko ideia berriren\n"
	.string "bat izan ote du bisitariak?$"

TVSecretBaseSecrets_Text_UsedGlitterMat::
	.string "Bisitariak PURPURINA ALFONBRA\n"
	.string "bat zapaldu du!\p"
	.string "Bisitaria pose desberdinak\n"
	.string "egiten ari da!\p"
	.string "Bisitaria famatua dela imaginatzen\n"
	.string "ari dela dirudi!$"

TVSecretBaseSecrets_Text_UsedTire::
	.string "Bisitaria PNEUMATIKO bati begira\n"
	.string "ari da!\p"
	.string "Zein kotxetatik atera ote den\n"
	.string "pentsatzen ariko ote da bisitaria?$"

TVSecretBaseSecrets_Text_UsedStand::
	.string "Bisitaria PODIUM batera igo da!\p"
	.string "Bisitaria {STR_VAR_1}(r)en BASEA\n"
	.string "goitik begiratzen ari da!\p"
	.string "Eta…\p"
	.string "Eta orro egin du!\n"
	.string "Bisitaria orroka ari da!$"

TVSecretBaseSecrets_Text_BrokeDoor::
	.string "Bisitariak burukada bat eman dio\n"
	.string "ATE HAUSGARRI bati!\p"
	.string "Bisitaria barrezka ari da indar guztiz!$"

TVSecretBaseSecrets_Text_UsedDoll::
	.string "Bisitaria PANPINA bati hizketan ari da!\p"
	.string "…Pixka bat arraroa da…$"

TVSecretBaseSecrets_Text_UsedSlide::
	.string "Bisitaria TXIRRISTA bateko eskailerak\n"
	.string "igotzen ari da!\p"
	.string "Eta…\p"
	.string "Bisitaria TXIRRISTATIK jaitsi da!\p"
	.string "Badirudi bisitaria oso ondo ari dela\n"
	.string "pasatzen!$"

TVSecretBaseSecrets_Text_UsedSlideButDidntGoDown::
	.string "Bisitaria TXIRRISTA bateko eskailerak\n"
	.string "igotzen ari da!\p"
	.string "Eta…\p"
	.string "Bisitariak eskailerak jaitsi\n"
	.string "ditu berriro!\p"
	.string "Kikildu egin ote da bisitaria?$"

TVSecretBaseSecrets_Text_UsedJumpMat::
	.string "Bisitariak SALTO ALFONBRA\n"
	.string "bat zapaldu du!\p"
	.string "Bisitariak jauzi egin du!\p"
	.string "Berriro egin du jauzi!\p"
	.string "Eta ondo lurreratu da!\p"
	.string "Bisitaria txaloka ari da!\n"
	.string "Hori bai hori saioa!$"

gTVSafariFanClubText00::
	.string "SAFARI FANEN KLUBA!\p"
	.string "ERREPORTARIA: Ongi lagunok!\n"
	.string "SAFARI BALLAK botatzen ari al zarete?\p"
	.string "Ni bai behintzat, SAFARI GUNEA\n"
	.string "POKéMON izugarriz lepo dago eta!\p"
	.string "Hitz egin dezagun SAFARI GIDA\n"
	.string "honekin!\p"
	.string "Ongi, lagun, zer moduzko ENTRENATZAILEAK\n"
	.string "dator bisitan?$"

gTVSafariFanClubText01::
	.string "GIDA: Mundu guztia esfortzu handia\n"
	.string "egiten ari da.\p"
	.string "{STR_VAR_1} bereziki ondo dabil.\p"
	.string "Bada, duela gutxi {STR_VAR_1}(e)k\n"
	.string "{STR_VAR_2} POKéMON harrapatu ditu.$"

gTVSafariFanClubText02::
	.string "ENTRENATZAILEA iaioa da {POKEBLOCK}AK\n"
	.string "Erabiltzen. {STR_VAR_2} erabili zituen.$"

gTVSafariFanClubText03::
	.string "ENTRENATZAILEAK ez du {POKEBLOCK}IK\n"
	.string "erabili! Ezta bat bera ere!\p"
	.string "Benetan da aditua.$"

gTVSafariFanClubText04::
	.string "ERREPORTARIA: Benetan ari al zara?\p"
	.string "Badirudi gure lagun {STR_VAR_1}\n"
	.string "SAFARI maisu aparta dela!\p"
	.string "GIDA: Espero dut ENTRENATZAILEA berriz\n"
	.string "itzuliko dela bere teknikak erakusteko.$"

gTVSafariFanClubText05::
	.string "GIDA: Inor ez da ari bereziki\n"
	.string "ondo.\p"
	.string "{STR_VAR_1} bereziki gaizki ibili da.\p"
	.string "ENTRENATZAILEAK POKéMON gutxi\n"
	.string "harrapatu ditu: {STR_VAR_2} bakarrik.$"

gTVSafariFanClubText06::
	.string "GIDA: Inor ez da ari bereziki\n"
	.string "ondo.\p"
	.string "{STR_VAR_1} bereziki gaizki ibili da.\p"
	.string "ENTRENATZAILEAK ez du POKéMON bat\n"
	.string "ere harrapatu. Ezta bakar bat ere!$"

gTVSafariFanClubText07::
	.string "ENTRENATZAILEAK {POKEBLOCK}AK erabiltzen\n"
	.string "ditu. {STR_VAR_2} erabili ditu, uste dut.\p"
	.string "Baina espero dut ENTRENATZAILEA\n"
	.string "hobetuko dela pixka bat honetan.$"

gTVSafariFanClubText08::
	.string "Uste dut ENTRENATZAILEA hobe arituko\n"
	.string "litzatekeela {POKEBLOCK}EKIN, ez ditu\l"
	.string "erabili lehen eta.$"

gTVSafariFanClubText09::
	.string "ERREPORTARIA: Benetan, e?\p"
	.string "Badirudi gure lagun {STR_VAR_1}\n"
	.string "gehiago aritu beharko dela SAFARIAN.\p"
	.string "GIDA: Espero dut ENTRENATZAILEA\n"
	.string "gehiagotan etorriko dela ohitu dadin.$"

gTVSafariFanClubText10::
	.string "ERREPORTARIA: Zehazki, bai!\n"
	.string "Erronkei aurre egitea garrantzitsua da!\p"
	.string "Ikusleok, etorri SAFARI GUNERA eta\n"
	.string "eta aurre egin erronkari!\p"
	.string "Hurrengora arte, aio pelaio!$"

ContestLiveUpdates_Text_Intro::
	.string "“POKéMON TXAPELKETEN BERRIAK!”\p"
	.string "ZM: Eskerrik asko ikusleok!\p"
	.string "Zuzenean gaude amaitu berri den\n"
	.string "{STR_VAR_1} gunetik.\p"
	.string "Aretoa lepo dago, joan nahi ez\n"
	.string "duten ikuslez beteta.\p"
	.string "Ikuslea: {STR_VAR_2}!\p"
	.string "Ikuslea: {STR_VAR_3}!\p"
	.string "ZM: Entzun duzuen bezala TXAPELKETA\n"
	.string "{STR_VAR_2} POKéMONAK irabazi berri du\l"
	.string "{STR_VAR_3}(r)ena.\p"
	.string "Ikuslea: {STR_VAR_2}!\n"
	.string "Onena zara!\p"
	.string "Ikuslea: {STR_VAR_3}!\n"
	.string "Hori bai egurra!\p"
	.string "ZM: Entzun dezagun zer dioten\n"
	.string "ikusleek TXAPELKETAREN gainean.$"

ContestLiveUpdates_Text_WonBothRounds::
	.string "Ikuslea: {STR_VAR_2} oso goian\n"
	.string "geratu da lehen eta bigarren epaietan!\p"
	.string "{STR_VAR_2} horrek gehiagotan irabaziko du!$"

ContestLiveUpdates_Text_BetterRound2::
	.string "Ikuslea: {STR_VAR_2} ez da oso ondo\n"
	.string "aritu lehen epaiean, baina bigarren\l"
	.string "epaiean askoz hobe ibili da!\p"
	.string "Ederki eman dio buelta markagailuari\n"
	.string "{STR_VAR_2} horrek. Bikain!$"

ContestLiveUpdates_Text_EqualRounds::
	.string "Ikuslea: {STR_VAR_2} nahiko sendo\n"
	.string "aritu da lehen eta bigarren\l"
	.string "epaietan zehar.\p"
	.string "{STR_VAR_3} eta {STR_VAR_2},\n"
	.string "a zer nolako konboa!$"

ContestLiveUpdates_Text_BetterRound1::
	.string "Ikuslea: {STR_VAR_1} izaten,\n"
	.string "{STR_VAR_2} bikaina izan da.\p"
	.string "Hurrengo erakustaldiak hobe egingo\n"
	.string "dituela espero dut, hala ere.$"

ContestLiveUpdates_Text_GotNervous::
	.string "Ikuslea: {STR_VAR_2} urduri jarri\n"
	.string "denean, bihotz eta buru animatzen\l"
	.string "saiatu naiz.\p"
	.string "Hau esan nahi nioke {STR_VAR_2}\n"
	.string "horri, “Zorionak!”$"

ContestLiveUpdates_Text_StartledFoes::
	.string "Ikuslea: {STR_VAR_2} horren erakustaldiak\n"
	.string "neu ere beldurtu nau!\p"
	.string "{STR_VAR_2}, zu bai zu bikaina!$"

ContestLiveUpdates_Text_UsedCombo::
	.string "Ikuslea: {STR_VAR_2} horren konboa\n"
	.string "bikaina izan da!\p"
	.string "Barruak nahastu dizkit!$"

ContestLiveUpdates_Text_ExcitingAppeal::
	.string "Ikuslea: {STR_VAR_2} irabazlearen\n"
	.string "erakustaldiak bihotza danbaka jarri dit!$"

ContestLiveUpdates_Text_WasCool::
	.string "{STR_VAR_2}!\n"
	.string "Zu bai zu karismatikoa!$"

ContestLiveUpdates_Text_WasBeautiful::
	.string "{STR_VAR_2}!\n"
	.string "Zu bai zu ederra!$"

ContestLiveUpdates_Text_WasCute::
	.string "{STR_VAR_2}!\n"
	.string "Zu bai zu polita!$"

ContestLiveUpdates_Text_WasSmart::
	.string "{STR_VAR_2}!\n"
	.string "Zu bai zu azkarra!$"

ContestLiveUpdates_Text_WasTough::
	.string "{STR_VAR_2}!\n"
	.string "Zu bai zu gogorra!$"

ContestLiveUpdates_Text_VeryExcitingAppeal::
	.string "Ikuslea: Oraindik danbaka dut bihotza\n"
	.string "{STR_VAR_2} irabazlearen erakustaldiarekin!$"

ContestLiveUpdates_Text_VeryCool::
	.string "{STR_VAR_2}!\n"
	.string "Zu izan zara karismatikoena!$"

ContestLiveUpdates_Text_VeryBeautiful::
	.string "{STR_VAR_2}!\n"
	.string "Zu zara ederretan ederrena!$"

ContestLiveUpdates_Text_VeryCute::
	.string "{STR_VAR_2}!\n"
	.string "Zu zara denetan politena!$"

ContestLiveUpdates_Text_VerySmart::
	.string "{STR_VAR_2}!\n"
	.string "Zu bai zu argia baino argiagoa!$"

ContestLiveUpdates_Text_VeryTough::
	.string "{STR_VAR_2}!\n"
	.string "Gogorrenetan gogorrena zara!$"

ContestLiveUpdates_Text_TookBreak::
	.string "Ikuslea: Tarte batean {STR_VAR_2}\n"
	.string "geldi geratu zenean ere,\l"
	.string "ezin nuen burutik kendu.\p"
	.string "Harrapatuta nauka {STR_VAR_2} horrek.$"

ContestLiveUpdates_Text_GotStartled::
	.string "Ikuslea: {STR_VAR_2} beste POKéMON\n"
	.string "baten erakustaldiak belduru zuenean,\l"
	.string "ia ia negarrez hasi nintzen.\p"
	.string "{STR_VAR_2}, benetan zara indartsua!\n"
	.string "Zu bai zu!$"

ContestLiveUpdates_Text_MoveWonderful::
	.string "Ikuslea: Ene…\n"
	.string "{STR_VAR_2} horren {STR_VAR_3}!\l"
	.string "{STR_VAR_2}(r)en {STR_VAR_3}!\l"
	.string "{STR_VAR_2}(r)en {STR_VAR_3}!\l"
	.string "Nola izan daiteke horren zirraragarria?$"

ContestLiveUpdates_Text_TalkAboutAnotherMon::
	.string "ZM: Beno, ba horratx guztia. Leku hau\n"
	.string "{STR_VAR_1}(r)en zalez lepo dago!\p"
	.string "Beste POKéMON bat ere aipatu behar dut,\n"
	.string "{STR_VAR_2}(r)en {STR_VAR_3},\l"
	.string "ezin dut ahaztu.\p"
	.string "{STR_VAR_2}(r)en {STR_VAR_3}…$"

ContestLiveUpdates_Text_FailedToAppeal::
	.string "Bigarren epaian zehar ez zuen lortu\n"
	.string "erakustaldi bakar bat egitea ere.\p"
	.string "Hurrengoan gustatuko litzaidake gutxienez\n"
	.string "{STR_VAR_1}(r)en erakustaldi bat ikustea.$"

ContestLiveUpdates_Text_LastInBothRounds::
	.string "Azken putz geratu zen bai lehen\n"
	.string "baita bigarren epaian ere.\p"
	.string "Espero dut {STR_VAR_1} gai izango dela\n"
	.string "{STR_VAR_2} berriz entrenatu eta hurrengo\l"
	.string "txapelketan postu hobea lortzeko.$"

ContestLiveUpdates_Text_NotExcitingEnough::
	.string "Ez du asmatu publikoaren zirrara\n"
	.string "aprobetxatu eta erakustaldi\l"
	.string "egokia egiten.\p"
	.string "Espero dugu {STR_VAR_1} gai izango dela\n"
	.string "publikoaren egoera irakurri eta haien\l"
	.string "zirrara bere alde aprobetxatzen.$"

ContestLiveUpdates_Text_LostAfterWinningRound1::
	.string "Nahiz eta lehen epaian lehenengo geratu\n"
	.string "den, hurrengo erakustaldiak ez du horren\l"
	.string "ongi funtzionatu bigarren epaian.\p"
	.string "Irabazten zihoan arren, porrot galanta\n"
	.string "izan du azkenean.\p"
	.string "Ziur nago {STR_VAR_1} aztertzen ari dela\n"
	.string "nola egin erakustaldi eraginkorragoak.$"

ContestLiveUpdates_Text_NeverExciting::
	.string "Bigarren epaian publikoak ez du\n"
	.string "behin ere zirrara sentitu.\p"
	.string "Espero dugu beste POKéMONEI kasu\n"
	.string "gutxiago egingo diela eta gehiago\l"
	.string "bere erakustaldi propioari.$"

ContestLiveUpdates_Text_LostBySmallMargin::
	.string "{STR_VAR_1}(r)en {STR_VAR_2}(r)en\n"
	.string "aurka galdu du, baina gutxigatik.\p"
	.string "Gogorra izango zen ziur garaipena\n"
	.string "horren hurbil izatea.\p"
	.string "Ez nintzateke harrituko {STR_VAR_3}\n"
	.string "emaitza honekin triste egongo balitz.$"

ContestLiveUpdates_Text_RepeatedAppeals::
	.string "Kale egin dio EPAILEARI behin eta\n"
	.string "berriz erakustaldia errepikatuz.\p"
	.string "Akats barkaezina da TXAPELKETETAN\n"
	.string "eta bere eragina izan du horrek.\p"
	.string "{STR_VAR_1} errudun sentituko da\n"
	.string "erakustaldi honen ondoren.$"

ContestLiveUpdates_Text_ValiantEffortButLost::
	.string "{STR_VAR_1}(e)k esfortzu galanta egin du,\n"
	.string "baina…\p"
	.string "Ez dio balio izan, azkena geratu da eta.\p"
	.string "{STR_VAR_1} gai izan behar litzateke\n"
	.string "galeratik ikasitakoa martxan jartzeko.$"

ContestLiveUpdates_Text_Outro::
	.string "Beti bezala, programa hau bukatzeko\n"
	.string "irabazleei agur bat emango diegu.\p"
	.string "Gaurkoan, {STR_VAR_1} eta\n"
	.string "{STR_VAR_2} dira garaileak!\p"
	.string "ZM: Prest al zaudete?\n"
	.string "Denok batera!\p"
	.string "Publikoa: {STR_VAR_1}! {STR_VAR_2}!\n"
	.string "Zorionak!\l"
	.string "Zuek zarete TXAPELDUNAK!$"

gTVPokemonBattleUpdateText00::
	.string "“POKéMON BORROKEN BERRIAK!”\p"
	.string "POKéMON borroken emaitzak dakarzkizuegu\n"
	.string "gertatu bezain laster!$"

gTVPokemonBattleUpdateText01::
	.string "{STR_VAR_1} eta {STR_VAR_2}\n"
	.string "ENTRENATZAILEEK norgehiagoka izan\l"
	.string "zuten {STR_VAR_3} BORROKA batean.\p"
	.string "Borroka honetan {STR_VAR_1} izan\n"
	.string "zen garailea!$"

gTVPokemonBattleUpdateText02::
	.string "Borrokan, {STR_VAR_1}(r)en\n"
	.string "{STR_VAR_2} berebizikoa izan zen\l"
	.string "{STR_VAR_3} erabili zuenean!$"

gTVPokemonBattleUpdateText03::
	.string "{STR_VAR_1}(r)en {STR_VAR_2} ez zen\n"
	.string "oso ondo moldatu.$"

gTVPokemonBattleUpdateText04::
	.string "Zorionak garaipenagatik,\n"
	.string "{STR_VAR_1}!\p"
	.string "Eta, galdu arren, {STR_VAR_2},\n"
	.string "hurrengoan hobe ibiliko zara, ziur!\p"
	.string "Honekin bukatzen dira gaurkoan\n"
	.string "“POKéMON BORROKA BERRIAK!”$"

gTVPokemonBattleUpdateText05::
	.string "{STR_VAR_1} eta {STR_VAR_2}(e)k\n"
	.string "MULTI BORROKA bat egin zuten.\p"
	.string "Borrokaren garaipena {STR_VAR_1}(r)en\n"
	.string "taldeak lortu zuen.$"

gTVPokemonBattleUpdateText06::
	.string "Borrokan, {STR_VAR_1}(r)en taldeko\n"
	.string "{STR_VAR_2} berebizikoa izan zen\l"
	.string "{STR_VAR_3} erabili zuenean.$"

gTVPokemonBattleUpdateText07::
	.string "{STR_VAR_2}(r)en taldeko {STR_VAR_3}\n"
	.string "ez zen oso ondo moldatu.\p"
	.string "Zorionak zure taldearen garaipenagatik,\n"
	.string "{STR_VAR_1}!\p"
	.string "Nahiz eta {STR_VAR_2}(r)en taldeak galdu,\n"
	.string "hurrengoan hobeto arituko zarete!\p"
	.string "Honekin bukatzen dira gaurkoan\n"
	.string "“POKéMON BORROKA BERRIAK!”$"

GabbyAndTy_Text_GabbyPreFirstBattle:
	.string "GABBY: Kontxo! Indartsua dirudien\n"
	.string "ENTRENATZAILE bat aurkitu berri dugu!\p"
	.string "Ongi, piztu kamera! Grabatzen!\n"
	.string "Elkarrizketatu dezagun.$"

GabbyAndTy_Text_GabbyIntro:
	.string "GABBY: Kontxo! {PLAYER} zara! Kaixo!\n"
	.string "Gogoratzen al zara gutaz?\p"
	.string "Erakutsiko al diguzu zeinen indartsua\n"
	.string "bihurtu zaren? Ongi, has gaitezen!$"

GabbyAndTy_Text_GabbyDefeatFirstTime:
	.string "GABBY: Ez nenbilen oker, ez!\n"
	.string "Hau bai hau ENTRENATZAILE aparta!$"

GabbyAndTy_Text_WhoAreYouInterview:
	.string "GABBY: Bikain! Bikain!\n"
	.string "Nor zara zu?!\p"
	.string "Banekien norbait berezia zinela\n"
	.string "ikusi zintudan unean!\p"
	.string "Bai, azalduko dizut. Leku askotara\n"
	.string "bidaiatzen dugu era guztietako\l"
	.string "ENTRENATZAILEAK elkarrizketatzeko.\p"
	.string "Izango zenuke tarte bat gurekin\n"
	.string "elakrrrizketa bat egiteko?$"

GabbyAndTy_Text_QuoteFromLastInterview:
	.string "GABBY: “{STR_VAR_1}!”\p"
	.string "Gogoratzen? Hori esan zenigun aurrekoan\n"
	.string "borroka baten erremate gisan.\p"
	.string "Nik ez dut horrelako konturik ahazten!$"

GabbyAndTy_Text_YouStompedUsInterviewAgain:
	.string "Azkenekoz borrokatu genuenean, txikitu\n"
	.string "egin gintuzun ezertarako denbora gabe…\p"
	.string "Beno, zer deritzozu?\n"
	.string "Nahi al duzu berriz elkarrizketatzea?$"

GabbyAndTy_Text_YouThrewABallAtUsInterviewAgain:
	.string "Azkenekoz borrokatu genuenean, ez al\n"
	.string "zenigun POKé BALL bat bota?\p"
	.string "Harrituta geunden! Eta mundu guztiari\n"
	.string "kontatu genion, noski!\p"
	.string "Beno, zer deritzozu?\n"
	.string "Nahi al duzu berriz elkarrizketatzea?$"

GabbyAndTy_Text_CleverItemSkillsInterviewAgain:
	.string "Azkenekoz borrokatu genuenean, zure itemak\n"
	.string "erabiltzeko gaitasunak harritu gintuen.\p"
	.string "Beno, zer deritzozu?\n"
	.string "Nahi al duzu berriz elkarrizketatzea?$"

GabbyAndTy_Text_WeLookedRespectableInterviewAgain:
	.string "Azkenekoz borrokatu genuenean, nahiko\n"
	.string "txukun ibili ginen.\p"
	.string "Beno, zer deritzozu?\n"
	.string "Nahi al duzu berriz elkarrizketatzea?$"

GabbyAndTy_Text_InterviewAgain:
	.string "Beno, zer deritzozu?\n"
	.string "Nahi al duzu berriz elkarrizketatzea?$"

GabbyAndTy_Text_DescribeYourFeelings:
	.string "Benetan?\n"
	.string "Eskerrik asko!\p"
	.string "Ongi, gure azken borrokan izan\n"
	.string "zenituen sentsazioak deskribatzea\l"
	.string "behar dut, labur eta gozo. Aurrera!$"

GabbyAndTy_Text_PerfectWellBeSeeingYou:
	.string "GABBY: Mmm, bai!\n"
	.string "Hori bai amaiera emateko modua!\p"
	.string "Esango nuke honekin telebistako\n"
	.string "programa eder bat egin daitekeela.\p"
	.string "Esango nuke hau telebistan aterako\n"
	.string "dela, ez ezazu galdu!\p"
	.string "Ongi!\n"
	.string "Hurrengora arte, orduan!$"

GabbyAndTy_Text_DontGiveUpKeepingEyeOut:
	.string "GABBY: Ene…\p"
	.string "Ados, baina ez ezazu amore eman!\n"
	.string "Zure adi egongo gara aurrerantzean!$"

GabbyAndTy_Text_KeepingAnEyeOutForYou:
	.string "GABBY: Zure adi egongo gara\n"
	.string "aurrerantzean!$"

GabbyAndTy_Text_GabbyNotEnoughMons:
	.string "GABBY: Ba al dago POKéMON asko\n"
	.string "dituen ENTRENATZAILERIK?$"

GabbyAndTy_Text_GiveUsAnInterviewThisTime:
	.string "GABBY: Ene, zu bai zu!\p"
	.string "Azkenengoz borroka egin genuenetik\n"
	.string "izugarrizko indarra hartu duzu.\p"
	.string "Ez genuen akatsik egin ENTRENATZAILE\n"
	.string "bikaina zinela pentsatzean.\p"
	.string "Beraz, zer, zer diozu?\n"
	.string "Gaur elkarrizketa bat egiteko prest\l"
	.string "al zaude?$"

GabbyAndTy_Text_GabbyDefeat:
	.string "GABBY: Hori bai hori borroka bizia!\n"
	.string "Grabatu al duzu guztia?$"

GabbyAndTy_Text_TyPreFirstBattle:
	.string "TY: Ei, begira! Itxura gogorreko\n"
	.string "ENTRENATZAILEA aurkitu dugu!\l"
	.string "Prestatu kamera!$"

GabbyAndTy_Text_TyIntro:
	.string "TY: Ei, begira!\n"
	.string "Gogoratzen naiz zutaz!\p"
	.string "Borroka hau oso-osorik grabatuko\n"
	.string "dut!$"

GabbyAndTy_Text_TyPostBattle:
	.string "TY: Zu bai zu itzela!\n"
	.string "A zer nolako grabaketa egin dudan!$"

GabbyAndTy_Text_TyNotEnoughMons:
	.string "TY: POKéMON bakarra daukazu, orduan?\n"
	.string "Bat bakarra?\p"
	.string "POKéMON gehiago bazenitu, grabaketa\n"
	.string "hobea egingo nuke, baina…$"

GabbyAndTy_Text_TyDefeatFirstTime:
	.string "TY: Bai, a zer nolako ENTRENATZAILEA.\n"
	.string "Izugarrizko pagotxa izan dugu!$"

GabbyAndTy_Text_TyDefeat:
	.string "TY: Bai, grabatu dut.\n"
	.string "Borroka guztia grabatu dut.$"

gTVInSearchOfTrainersText00::
	.string "ENTRENATZAILEEN BILA…\p"
	.string "GABBY: Iepa! Gaur {STR_VAR_1} inguruan\n"
	.string "gaude bisitan.\p"
	.string "Gaurkoan pil-pilean dagoen talentu\n"
	.string "berriaren bila gabiltza.\p"
	.string "Gaur, gure kamerak {PLAYER}\n"
	.string "ENTRENATZAILEARI begira ditugu.\p"
	.string "ENTRENATZAILE honek badu zerbait\n"
	.string "interesa pizten diguna.$"

gTVInSearchOfTrainersText01::
	.string "Egin dugu borroka {PLAYER}(r)en aurka\n"
	.string "lehenago, eta ezbairik gabe esan dezakegu\l"
	.string "asko hobetu duela azkenengotik.\p"
	.string "Banekien zerbait berezia aurkitu genuela\n"
	.string "ENTRENATZAILE hau ikusi genuenean!$"

gTVInSearchOfTrainersText02::
	.string "ENTRENATZAILE baten indarra neurtzeko\n"
	.string "erarik onena…\p"
	.string "Beno, erarik azkarrena borrokatzea da.\n"
	.string "Eta hala hasi genuen ikerketa!\p"
	.string "… …\p"
	.string "Eta hala bukatu genuen {PLAYER}(r)en\n"
	.string "aurka borrokan.\p"
	.string "Borroka izugarri batean, zanpatu, txikitu\n"
	.string "eta birrindu egin gintuen!\p"
	.string "{PLAYER} izugarri indartsua da…\p"
	.string "Hemen kontatuko dizkizuegu ENTRENATZAILE\n"
	.string "honi buruzko gure iritziak.$"

gTVInSearchOfTrainersText03::
	.string "{STR_VAR_1} eta {STR_VAR_3}(r)en\n"
	.string "konbinazioa paregabea da!\p"
	.string "Haiek batera ikustea--{STR_VAR_1} eta\n"
	.string "{STR_VAR_3}--elkarrekin borrokan\l"
	.string "norgehiagoka betean…\p"
	.string "Benetan ikustaldi ezinhobea da!\p"
	.string "{STR_VAR_2} izan zen ENTRENATZAILEAK\n"
	.string "erabili zuen erasoa gure azken borrokan.\p"
	.string "{STR_VAR_2} erasoa da {STR_VAR_1}\n"
	.string "eta {STR_VAR_3}(r)en indarraren eredu!$"

gTVInSearchOfTrainersText04::
	.string "…Nigan nuen konfidantza galdu nuen izan\n"
	.string "genuen azken borrokaren ostean.\p"
	.string "Eraso bakar bat bota aurretik txikitu\n"
	.string "gintuzun.\l"
	.string "Ene… Zintz…\p"
	.string "Hala ere, {PLAYER}(r)en borrokak\n"
	.string "ikusteko modukoak dira guztiz.\p"
	.string "ENTRENATZAILE adoretsuek {PLAYER}(r)i\n"
	.string "erronka bota behar liekete.$"

gTVInSearchOfTrainersText05::
	.string "Gauza bakarra dago esateko.\n"
	.string "Ez dakizula burutik pasa POKé BALL bat\l"
	.string "botatzea ENTRENATZAILE baten aurka!\p"
	.string "{PLAYER} indartsua da, baina ez ditu\n"
	.string "oinarrizko arauak ezagutzen.\p"
	.string "Gure publikoarentzat, eskari bat dut.\p"
	.string "{PLAYER} ikusten baduzue, mesedez\n"
	.string "abisatu iezaiozue!$"

gTVInSearchOfTrainersText06::
	.string "{PLAYER} abila da aurkariak egingo\n"
	.string "duena aurreikusten.\p"
	.string "Itemak erabiltzeko momentua izugarri\n"
	.string "ondo neurtuta dauka!$"

gTVInSearchOfTrainersText07::
	.string "Egia esanda, uste nuen nahikoa\n"
	.string "ona nintzela berez.\p"
	.string "Nahiz eta galdu egin genuen, borroka\n"
	.string "bizia eta parekatua izan genuen.\p"
	.string "Baina nire aurka justu bazabiltza,\n"
	.string "oraindik baduzu zer hoebtua, {PLAYER}!$"

gTVInSearchOfTrainersText08::
	.string "Gure borrokaren ostean, {PLAYER}(r)i\n"
	.string "laburpen bat eskatu genion.\p"
	.string "Honek esan zigun, “{STR_VAR_1}.”\p"
	.string "{PLAYER}(r)en {STR_VAR_2} eta\n"
	.string "{STR_VAR_3}…\l"
	.string "Eta “{STR_VAR_1}”…\p"
	.string "Mmm! Sakona! Esanahi sakona du\n"
	.string "esapide horrek, alajaina!\p"
	.string "Ez da ezer berria, ENTRENATZAILE onak\n"
	.string "hitz hobeak.\p"
	.string "Hori da dena gaurkoz!\n"
	.string "Hurrengo emisiora arte!$"

ContestLadyShow_Text_Intro::
	.string "“POKéMON TXAPELKETEN BERRIAK!”\p"
	.string "ZM: Barkatu ohiko programazioa eteteagatik\n"
	.string "eta eskerrik asko ikusteagatik!\p"
	.string "Zuzenean gaude bukatu berri den\n"
	.string "{STR_VAR_1} hau gertatu\l"
	.string "den tokitik!\p"
	.string "Ikusleak: ?!!!!\p"
	.string "ZM: Ene! Badirudi TXAPELETAKO\n"
	.string "partaideak honantz datozela!\p"
	.string "Ea zuzeneko elkarrizketa bat lortu\n"
	.string "dezakegun zuentzat ikusleontzat!\p"
	.string "Ikusleak: ?!!!!\n"
	.string "?!!!!$"

ContestLadyShow_Text_Won::
	.string "ZM: Barkatu!\n"
	.string "Zuzenean gaude telebistan!\p"
	.string "Zoriondu al zaitzaket zure garaipenagatik?\p"
	.string "Zein izan da gaurko garaipen itzela\n"
	.string "lortzeko egindakoa?\p"
	.string "EDERRA: Izugarri saiatu gara gaur\n"
	.string "nire {STR_VAR_2} eta ni!\p"
	.string "Baina ziur nago ez genuela irabaziko\n"
	.string "TXAPELKETAN zehar izan dugun\l"
	.string "bultzada jaso izan ez bagenu!\p"
	.string "ZM: Ba al duzu norbait berezia\n"
	.string "berekin zure zoriontasuna partekatzeko?\l"
	.string "Entzun dezagun zuzenean!\p"
	.string "EDERRA: Ei, aizu!\p"
	.string "{STR_VAR_3}! Ikusten ari al zara?\n"
	.string "Lortu dugu!\l"
	.string "Eskerrik asko!$"

ContestLadyShow_Text_Lost::
	.string "ZM: Barkatu!\n"
	.string "Zuzenean gaude telebistan!\p"
	.string "Triste egongo zara azkenean eman diren\n"
	.string "emaitzekin. Zoezer esan nahi al duzu?\p"
	.string "EDERRA: Guztiz abailduta nago…\n"
	.string "Nire {STR_VAR_2} eta nik ahalegin itzela\p"
	.string "egin dugu… Baina iruditzen zait animatu\n"
	.string "gaituztenei huts egin diegula.\p"
	.string "ZM: Ez da mintzearren, baina POKéMONA ez\n"
	.string "da oso ondo ibili.\p"
	.string "EDERRA: {STR_VAR_3}, Sentitzen dut…\n"
	.string "Hurrengoan arituko ibiliko gara…\l"
	.string "…Zintz… Buaaaa!\p"
	.string "Ikusleak: Ikusi duzue hori?\n"
	.string "Neska gaixoa!\p"
	.string "ZM: Ene… Ene bada…\p"
	.string "Beno… Amaitu zaigu denbora!\n"
	.string "Eskerrik asko ikusteagatik!$"

ContestLadyShow_Text_LostBadly::
	.string "ZM: Barkatu!\n"
	.string "Zuzenean gaude telebistan!\p"
	.string "Zer moduz joan da TXAPLEKETA?\p"
	.string "EDERRA: Guztia gaizki joan da…\n"
	.string "Ez dakit zergatik, baina {STR_VAR_2}\l"
	.string "ez da gai izan atentzioa emateko.\p"
	.string "ZM: Ez da mintzearren, baina POKéMONA ez\n"
	.string "da oso ondo ibili.\p"
	.string "EDERRA: … … … … … …\n"
	.string "…Zintz… Buaaaa!\p"
	.string "Ikusleak: Ikusi duzue hori?\n"
	.string "Neska gaixoa!\p"
	.string "ZM: Ene… Ene bada…\p"
	.string "Beno… Amaitu zaigu denbora!\n"
	.string "Eskerrik asko ikusteagatik!$"
