LilycoveCity_ContestLobby_Text_InterviewRequest:
	.string "Kaixo! Zu POKéMON LEHIAKETA\n"
	.string "batean egon zara, ezta?\l"
	.string "Zure POKéMONak ikusita, erraza da jakiten.\p"
	.string "Kazetaria naiz. POKéMON LEHIAKETEN\n"
	.string "inguruko erreportaia batekin ari naiz.\p"
	.string "Inporta zaizu galdera batzuk egingo\n"
	.string "banizkizu honen inguruan?$"

LilycoveCity_ContestLobby_Text_DescribeContest:
	.string "Bai, benetan?\n"
	.string "Eskerrik asko.\p"
	.string "Labur-labur, nola deskribatuko zenuke\n"
	.string "sartu berri zaren LEHIAKETA?$"

LilycoveCity_ContestLobby_Text_WhatImageWhenYouHearX:
	.string "Ongi, ongi.\n"
	.string "Iruzkin interesgarria, alajaina.\p"
	.string "Ulertu dezaket nolakoa izan zen\n"
	.string "LEHIAKETA, gutxi gorabehera.\p"
	.string "Azken galdera bat.\p"
	.string "“{STR_VAR_2}” hitza entzutean,\n"
	.string "zein irudi datorkizu burura?$"

LilycoveCity_ContestLobby_Text_ThatsAllForInterview:
	.string "Ederki!\p"
	.string "Beraz, “{STR_VAR_2}” kontzeptua\n"
	.string "hala interpretatzen duzu.\p"
	.string "Mila esker!\n"
	.string "Ideia onak eman dizkidazu.\p"
	.string "Esango nuke orain idatzi dezakedala\n"
	.string "POKéMON LEHIAKETEN inguruko istorio on bat.\p"
	.string "Beharbada, zorte pixkatekin telebistan ere\n"
	.string "ateratzea lortu nezake.\l"
	.string "Espero dut zu ere irrikan egongo zarela!$"

LilycoveCity_ContestLobby_Text_PleaseDoShareStoryWithMe:
	.string "Ene, ze pena…\p"
	.string "Bueno, istorio onen bat topatzen baduzu,\n"
	.string "mesedez, konta iezadazu.$"

LilycoveCity_ContestLobby_Text_LookingForwardToNextContest:
	.string "Zure hurrengo POKéMON LEHIAKETAREN\n"
	.string "zain egongo naiz.$"

gTVBravoTrainerText00::
	.string "Yeah!\n"
	.string "Iritsi da ENTRENATZAILE AUSARTAREN garaia!\p"
	.string "Gaurkoan, {STR_VAR_1}(r)en POKéMON\n"
	.string "bat aztertuko dugu.\p"
	.string "POKéMON honek {STR_VAR_3} maila dauka\n"
	.string "{STR_VAR_2} kategorian.$"

gTVBravoTrainerText01::
	.string "Zuekin guztiokin {STR_VAR_2}\n"
	.string "{STR_VAR_1}!\p"
	.string "{STR_VAR_2} ezizenak…\p"
	.string "Ezizenak berak transmititzen du\n"
	.string "nolabaiteko “{STR_VAR_3}”!$"

gTVBravoTrainerText02::
	.string "Bueno, {STR_VAR_1} ENTRENATZAILEAK\n"
	.string "POKéMONa LEHIAKETAN sartu zuenean,\l"
	.string "bere lagunaren gaineko esaldi bat\l"
	.string "edo beste atera genion.$"

gTVBravoTrainerText03::
	.string "LEHIAKETAREN ondoren, honen inguruan\n"
	.string "galdetzean {STR_VAR_1}(e)k alai erantzun\l"
	.string "zigun, “{STR_VAR_2}!”\p"
	.string "Bueno, noski, {STR_VAR_1}(r)en POKéMONa\n"
	.string "{STR_VAR_3}. postuan gelditu zen LEHIAKETAN.\p"
	.string "Esan ziguna guztiz bat doa\n"
	.string "{STR_VAR_1}(r)ekin, nire iritziz!$"

gTVBravoTrainerText04::
	.string "LEHIAKETAREN ondoren, honen inguruan\n"
	.string "galdetzean {STR_VAR_1}(e)k erdi minduta\l"
	.string "erantzun zigun, “{STR_VAR_2}.”\p"
	.string "Beno, noski, {STR_VAR_1}(e)n POKéMONa\n"
	.string "{STR_VAR_3}. postuan gelditu zen LEHIAKETAN.\p"
	.string "{STR_VAR_1}(r)en nahigabea argi eta garbi\n"
	.string "ikusi eta entzun daiteke!$"

gTVBravoTrainerText05::
	.string "Jakin nahi duzue {STR_VAR_1}(r)entzat\n"
	.string "zer irudkatzen duen {STR_VAR_2}(e)k?\p"
	.string "Guk bai, bederen!\n"
	.string "Eta galdetu egin genion!\p"
	.string "Erantzun hau eman zigun:\n"
	.string "“{STR_VAR_3}!”\p"
	.string "{STR_VAR_2} kontzeptuak esanahi hau\n"
	.string "dauka {STR_VAR_1}(r)entzat!$"

gTVBravoTrainerText06::
	.string "{STR_VAR_1}(e)k erabilitako azken\n"
	.string "{STR_VAR_2} erasoaren esanahia\l"
	.string "“{STR_VAR_3}” da duda izpirik gabe!$"

gTVBravoTrainerText07::
	.string "Bejondeizula, {STR_VAR_1}!\n"
	.string "Bejondeizula, {STR_VAR_2}!\p"
	.string "Espero dugu hemendik aurrera\n"
	.string "{STR_VAR_1} gehiagotan ikusiko dugula!\p"
	.string "Eta hementxe bukatzen da gure programa!\n"
	.string "Hurrengora arte, agur!$"

gTVBravoTrainerText08::
	.string "Zuekin, ENTRENATZAILEAREN {STR_VAR_1}(a)!$"

BattleFrontier_BattleTowerLobby_Text_InterviewRequest::
	.string "Kaixo! Zu zara borroka izan berri duen\n"
	.string "ENTRENATZAILEA, ezta?\p"
	.string "ENTRENATZAILEEKIN elkarrizketak\n"
	.string "bildu eta bildu ari naiz.\p"
	.string "Borrokan izandako inpresioen gaineko\n"
	.string "galdera batzuk erantzuterik bai?$"

BattleFrontier_BattleTowerLobby_Text_HowDidBattleTowerTurnOut::
	.string "Bai? benetan?\n"
	.string "Eskerrik asko!\l"
	.string "Orduan…\p"
	.string "Zer moduz jazo dira BORROKA\n"
	.string "DORREKO kontuak gaur?\p"
	.string "Pozik gelditu zara egindako borrokarekin?\n"
	.string "Edo hobe egin zenezakeela uste duzu?$"

BattleFrontier_BattleTowerLobby_Text_SorryWeDisturbedYou::
	.string "Bueno…\n"
	.string "Barkatu molestatu badizugu.\p"
	.string "BORROKA DORRERA berriro zatozenean\n"
	.string "ea hobe datrokizun elkarrizketatxo bat.$"

BattleFrontier_BattleTowerLobby_Text_ObviousYouHadGreatBattle::
	.string "Bai, noski!\p"
	.string "Zure aurpegian argi eta garbi ikus\n"
	.string "daiteke gustora zaudela…\p"
	.string "Agerikoa da pozik gelditu zarela\n"
	.string "egindako borrokarekin.$"

BattleFrontier_BattleTowerLobby_Text_DifficultToMakeBattleTurnOutAsPlanned::
	.string "Oh, noski…\p"
	.string "Bueno, nahiko zaila izan ohi da borroka\n"
	.string "bat planifikatu bezain ondo irtetea.$"

BattleFrontier_BattleTowerLobby_Text_DescribeYourBattle::
	.string "Oh, oh, beste galdera bat egin diezazuket?\p"
	.string "Borroka honen inguruko inpresioa\n"
	.string "hitz bakar batean laburbildu beharko bazenu,\l"
	.string "zein hitz aukeratuko zenuke?$"

BattleFrontier_BattleTowerLobby_Text_ThatsGreatLine::
	.string "Oh, hori oso ederra da!\p"
	.string "Zein aukeraketa ona!\n"
	.string "Hurrengoan ere ederki ibiliko zarela espero dut.\p"
	.string "Hurrengora arte!$"

BattleFrontier_BattleTowerLobby_Text_SilentType::
	.string "Oh, ados…\p"
	.string "Isila baldin bazara, hori ere guztiz\n"
	.string "onargarria da, egia esanda.\p"
	.string "Beharbada hurrengo batean kontatuko\n"
	.string "didazu ea nola ibili zaren!$"

BattleFrontier_BattleTowerLobby_Text_LookingForwardToNextBattle::
	.string "Zure hurrengo borrokaren zain\n"
	.string "geratuko naiz, orduan!$"

BravoTrainerBattleTower_Text_Intro::
	.string "Bai!\n"
	.string "ENTRENATZAILE AUSARTAREN garaia da!\p"
	.string "Gaurkoan, {STR_VAR_1} baloratuko dugu,\n"
	.string "BATAILA DORREKO erroka egin berri duena!\p"
	.string "Erronkan, {STR_VAR_1}(e)k {STR_VAR_2}\n"
	.string "bat erabili zuen.$"

BravoTrainerBattleTower_Text_NewRecord::
	.string "Bikoteak errekor berria egin zuen: {STR_VAR_2}\n"
	.string "garaipen jarraian {STR_VAR_1} txapelketan!\l"
	.string "Zorionak, ENTRENATZAILE!$"

BravoTrainerBattleTower_Text_Lost::
	.string "Bikoteak, azkenean {STR_VAR_1}(r)en\n"
	.string "kontra galdu zuen, {STR_VAR_2}. borrokan.\l"
	.string "Ondo jokatuta, ENTRENATZAILE!\p"
	.string "Baina, aizue, erronak horren azkar\n"
	.string "{STR_VAR_1} bat tokatzea zorte txarra da.\p"
	.string "ENTRENATZAILEARI bere {STR_VAR_1}(r)en aurkako\n"
	.string "borrokako inpresioen inguruan galdetu genion.$"

BravoTrainerBattleTower_Text_Won::
	.string "Bikoteak garaipena etxeratu zuen\n"
	.string "{STR_VAR_1}(r)en {STR_VAR_2}ari irabazita.\l"
	.string "Zorionak, ENTRENATZAILE!\p"
	.string "{STR_VAR_1}(e)ri irabaztea…\n"
	.string "Sinesgaitza da ia-ia! Izugarria, benetan!\p"
	.string "Garaipen momentuaren inguruan galdetu\n"
	.string "genion ENTRENATZAILEARI.$"

BravoTrainerBattleTower_Text_LostFinal::
	.string "Garaipen sortaren ondoren, azkenean bikoteak\n"
	.string "{STR_VAR_1}(r)en {STR_VAR_2}aren aurka galdu zuen,\l"
	.string "beraien azken erronka.\p"
	.string "Ondo jokatuta, ENTRENATZAILE!\p"
	.string "Meritu handia dauka.\n"
	.string "Ez da askotan ikusten {STR_VAR_1}\l"
	.string "eta {STR_VAR_2} bezalako konbinaziorik.\p"
	.string "Bikote famatuaren aurka borrokatzearen\n"
	.string "inguruan galdetu genion ENTRENATZAILEARI.$"

BravoTrainerBattleTower_Text_Satisfied::
	.string "Honakoa esan zigun ENTRENATZAILEAK:\n"
	.string "“Gustora geratu naiz!”\p"
	.string "Erantzun bikaina, alajaina!\n"
	.string "Zorionak, ENTRENATZAILE!\p"
	.string "Ez al da zirraragarria borroka\n"
	.string "gogo biziz egin eta gustura geratzea?\p"
	.string "ENTRENATZAILEA gustura geratu zela\n"
	.string "konturatu nintzen hau esan zidanean:$"

BravoTrainerBattleTower_Text_Unsatisfied::
	.string "Hau esan zidan ENTRENATZAILEAK:\n"
	.string "“Ez naiz gustura geratu…”\p"
	.string "ENTRENATZAILEA nahikoa triste zegoen\n"
	.string "hori esan zuenean.\p"
	.string "Hala ere, ez da erraza borrokatu eta\n"
	.string "guztiz gustora geratzea, ez da hala?\p"
	.string "Beno, ENTRENATZAILEA gustora geratu\n"
	.string "ez zela jakin nuen hau esan zuenean:$"

BravoTrainerBattleTower_Text_None1::
	.string "Ezer ez$"

BravoTrainerBattleTower_Text_None2::
	.string "Ezer ez$"

BravoTrainerBattleTower_Text_None3::
	.string "Ezer ez$"

BravoTrainerBattleTower_Text_None4::
	.string "Ezer ez$"

BravoTrainerBattleTower_Text_Response::
	.string "“{STR_VAR_1}.”$"

BravoTrainerBattleTower_Text_ResponseSatisfied::
	.string "“{STR_VAR_1}.”\n"
	.string "Ez al da itzela?\p"
	.string "Guztiz espresatzen du {STR_VAR_2}(r)en\n"
	.string "grina, esango nuke.\p"
	.string "{STR_VAR_3}(r)en aurkako borroka\n"
	.string "amaieran… “{STR_VAR_1}” deituko nioke\l"
	.string "nik horri, dudarik gabe!$"

BravoTrainerBattleTower_Text_ResponseUnsatisfied::
	.string "“{STR_VAR_1}.”\n"
	.string "Ez al da bereziki egokia?\p"
	.string "{STR_VAR_3}(r)en aurkako borroka\n"
	.string "amaieran… Deskribatzkeo hitzik egokiena\l"
	.string "“{STR_VAR_1}” da, ezbairik gabe!\p"
	.string "{STR_VAR_2}(r)en nahigabea argi eta garbi\n"
	.string "ikusi eta entzun daiteke!$"

BravoTrainerBattleTower_Text_Outro::
	.string "Bejondeizula, {STR_VAR_1}!\n"
	.string "Bejondeizula, {STR_VAR_2}!\p"
	.string "Espero dut hemendik aurrera\n"
	.string "{STR_VAR_1} gehiagotan ikusiko dugula!\p"
	.string "Eta hementxe bukatzen da gure programa!\n"
	.string "Hurrengora arte, agur!$"

SlateportCity_PokemonFanClub_Text_InterviewRequestHasName:
	.string "Wow!\p"
	.string "Argi eta garbi dago asko maite duzula\n"
	.string "zure {STR_VAR_1}.\p"
	.string "Ongi, {STR_VAR_2} izena du.\p"
	.string "Mesede bat eska diezazuket?\p"
	.string "Telebistako kazetaria naiz eta\n"
	.string "POKÉMONEN inguruko galdetegi bat daukat.\p"
	.string "Erantzungo zenizkidake pare bat\n"
	.string "galdera erraz?$"

SlateportCity_PokemonFanClub_Text_HereGoesQuickAnswers:
	.string "Bikain! Eskerrik asko!\p"
	.string "Ados, hemen doaz.\n"
	.string "Erantzun azkarrak behar ditut, ados?$"

SlateportCity_PokemonFanClub_Text_DescribeFeelingsFirstMetMon:
	.string "Lehen aldiz {STR_VAR_1} ezagutu zenuenean,\n"
	.string "Nola sentitu zinen?\p"
	.string "Nola deskribatuko zenuke momentu hartan\n"
	.string "sentitu zenuena?$"

SlateportCity_PokemonFanClub_Text_LikenMonToSomethingYouLike:
	.string "Zure {STR_VAR_1} maitasun handiz zaindu duzu.\p"
	.string "Gustuko duzun zerbaitekin alderatu\n"
	.string "beharko bazenu, zer izango litzateke?$"

SlateportCity_PokemonFanClub_Text_WhatAttractedYouAboutMon:
	.string "Galdera hau ere zure {STR_VAR_1} maitearen\n"
	.string "inguruan da.\p"
	.string "Zer gustatu zitzaizun gehien\n"
	.string "{STR_VAR_1} ezagutu zenuenean?$"

SlateportCity_PokemonFanClub_Text_WhatDoPokemonMeanToYou:
	.string "Noski, horrek zentzua du.\p"
	.string "Hurrengo galdera pixka bat zailagoa\n"
	.string "izan daiteke.\p"
	.string "Hementxe…\p"
	.string "Zuretzat zer dira POKéMONak?$"

SlateportCity_PokemonFanClub_Text_ThatsAllForInterview:
	.string "Ederki!\p"
	.string "Hmhm…\p"
	.string "Ados!\n"
	.string "Eskerrik asko zure laguntzagatik.\p"
	.string "Zurekin hitz egitea dibertigarria\n"
	.string "eta argigarria izan da.\p"
	.string "Agian gure elkarrizketa telebistan\n"
	.string "agertuko da. Begiratu ezazu hurrengoan!\p"
	.string "Ongi, hori zen guztia.\n"
	.string "Aio-aio!$"

SlateportCity_PokemonFanClub_Text_HereIfYouGetUrgeToTellMe:
	.string "Oh, ados…\p"
	.string "Beno, hurrengoan nirekin POKÉMONEN inguruan\n"
	.string "hitz egin nahi baduzu, lasai etorri!$"

SlateportCity_PokemonFanClub_Text_EnjoyDoingInterviews:
	.string "Gustuko dut nire lana. Elkarrizketekin\n"
	.string "POKÉMONEN inguruan asko ikasten dut.$"

SlateportCity_PokemonFanClub_Text_InterviewRequest:
	.string "Kaixo, badirudi asko maite duzula zure\n"
	.string "{STR_VAR_1}.\p"
	.string "Badakizu zer?\n"
	.string "Telebistako kazetaria naiz.\p"
	.string "Munduan zehar bidaiatzen dut jendea\n"
	.string "POKÉMONEN inguruan elkarrizketatzeko.\p"
	.string "Zure {STR_VAR_1}(r)en inguruan zerbait\n"
	.string "kontatuko zenidake?$"

SlateportCity_PokemonFanClub_Text_TellMeAnythingAboutYourMon:
	.string "Uau, eskerrik asko!\p"
	.string "Ongi, orduan knota iezadazu zure\n"
	.string "{STR_VAR_1}(r)en inguruan gustuko duzun edozer.$"

SlateportCity_PokemonFanClub_Text_ThatsAllForInterview2:
	.string "uau…\n"
	.string "Oso interesgarria da hori.\p"
	.string "Asko maite duzu {STR_VAR_1},\n"
	.string "ezta?\p"
	.string "Esango nuke kontatu didazuna\n"
	.string "telebistarako oso egokia dela.\p"
	.string "Zin egiten dizut, material honekin\n"
	.string "istorio entretenigarri bat idatziko dut.\l"
	.string "Egon adi telebistari.\p"
	.string "Hori zen guztia.\n"
	.string "Aio-aio!$"

gTVFanClubOpinionsText00::
	.string "POKéMON FAN TALDEA GARA!\p"
	.string "Zuzenean gaude oraintxe!\p"
	.string "Programa honetan zuen iritziak bildu\n"
	.string "eta zuen ordez oihukatzen ditugu!\l"
	.string "Kontzeptu itzela programa batentzat, ezta?\p"
	.string "gaurkoan gure kazetariak egindako\n"
	.string "elkarrizketa bat dakarkizuegu,\l"
	.string "POKéMON FAN TALDEAN egindakoa.\p"
	.string "beraz, zein da gaurkoan aterako den\n"
	.string "POKéMON fana?\p"
	.string "… … … … … … … …\p"
	.string "{STR_VAR_1}!\p"
	.string "Entzun dezagun {STR_VAR_1}(e)k esanog diguna\n"
	.string "{STR_VAR_3} {STR_VAR_2}(r)en gainean.\p"
	.string "Eta, hitz horiek oihukatuko ditut\n"
	.string "ozen telebistan!\p"
	.string "Hoo-hah!\p"
	.string "Oihu egin dezagun!$"

gTVFanClubOpinionsText01::
	.string "{STR_VAR_1}(e)ri galdetu genion, “Lehen\n"
	.string "aldiz {STR_VAR_2} ikusi zenuenean, zer\l"
	.string "pentsatu zenuen?”\p"
	.string "“{STR_VAR_3}!”\p"
	.string "Bai jauna! Izugarrizko oihua!\p"
	.string "Ez al dizkizue aspaldiko garaiak\n"
	.string "gogorarazten?$"

gTVFanClubOpinionsText02::
	.string "{STR_VAR_1}(e)ri galdetu genion, “Zure\n"
	.string "{STR_VAR_2} zeozerrekin konparatzekotan,\l"
	.string "izango litzateke…”\p"
	.string "… … … … … … … …\p"
	.string "“{STR_VAR_3}!”\p"
	.string "Ene-bada, zein ideia originala!\p"
	.string "Argi eta garbi ikusten da\n"
	.string "ENTRENATZAILE honek duen sentimendua\l"
	.string "{STR_VAR_2}(r)ekiko.$"

gTVFanClubOpinionsText03::
	.string "Eta ikus dezagun…\n"
	.string "Zar dauka {STR_VAR_2} horrek\l"
	.string "{STR_VAR_1}(e)ri hainbeste gustatzeko?\p"
	.string "… … … … … … … …\p"
	.string "“{STR_VAR_3}!”\p"
	.string "Ene! A zer nolako deklarazioa!\p"
	.string "ENTRENATZAILEAREN {STR_VAR_2}(r)ekiko\n"
	.string "maitasuna argi eta garbi geratu da!$"

gTVFanClubOpinionsText04::
	.string "Hm? Oraindik gehiago dago.\n"
	.string "Ikus dezagun!\p"
	.string "Ea ba, zer ote…\p"
	.string "{STR_VAR_1}(e)ri galdetu genion, “Zuretzat zer\n"
	.string "dira POKéMONak?”\p"
	.string "… … … … … …\p"
	.string "“{STR_VAR_3}!”\p"
	.string "Izugarria!\p"
	.string "Egun osoan entzun dudan oihu itzelena!\p"
	.string "“{STR_VAR_3}!”\p"
	.string "Behin eta berriz oihukatzeko gogo\n"
	.string "bizia ematen du!\p"
	.string "Oihu egiten amaituta, bada garaia\n"
	.string "guztiak agurtzeko!\p"
	.string "Bota dezagun azken garrasi bat!\n"
	.string "Denok batera…\p"
	.string "“{STR_VAR_3}!”$"

gTVFanClubText00::
	.string "POKéMON FAN TALDEA GARA!\p"
	.string "Zuzenean gaude oraintxe!\p"
	.string "Gaurkoan, POKéMON GALDETEGIEN TXOKOA\n"
	.string "izango dugu programaren muina.\p"
	.string "POKÉMONEK eta ENTRENATZAILEEK\n"
	.string "sortutako istorio ederren artean, zein\l"
	.string "drama izango ote dugu gaur gurean?\p"
	.string "Ea ba, ikus dezagun…\p"
	.string "Hauxe bera!\p"
	.string "Gutun honekin hasiko gara!\p"
	.string "{STR_VAR_1}(r)ek idatzitako gutuna da\n"
	.string "bere {STR_VAR_2} kuttunaren inguruan.\p"
	.string "Ikus dezagun gure idazleak nola transmititu\n"
	.string "dezakeen {STR_VAR_2}(r)ekiko duen pasioa!\l"
	.string "Hmhm…$"

gTVFanClubText01::
	.string "Uau!\n"
	.string "A zer nolako gutuna!$"

gTVFanClubText02::
	.string "Izugarri gustatu zait, hona hemen berriro!$"

gTVFanClubText03::
	.string "Horrelako gutun bat behin eta berriz\n"
	.string "irakurtzeko idatzi da!$"

gTVFanClubText04::
	.string "“{STR_VAR_3}”(r)en inguruan idatzitako zatiak\n"
	.string "bereziki indar emozional handia du!\p"
	.string "Oso gutun ederra da, bihotz guztiarekin\n"
	.string "idatzitakoa!$"

gTVFanClubText05::
	.string "Bereziki “{STR_VAR_3}”(r)en zati hori!\p"
	.string "Zer ondo dagoen “{STR_VAR_3}” erabilita!$"

gTVFanClubText06::
	.string "Ahaztu aurretik, ez da garrantzitsua,\n"
	.string "baina “{STR_VAR_3}” esapide ederra da.\p"
	.string "Azkenaldian asko erabili dut “{STR_VAR_3}”\n"
	.string "elkarrizketa guztietan.$"

gTVFanClubText07::
	.string "Puntuazio bat jartzekotan gutunari,\n"
	.string "{STR_VAR_3} puntu emango nizkioke.\p"
	.string "Hurrengoan are gutun hobea bidali\n"
	.string "beharko duzu, {STR_VAR_1}!\p"
	.string "Ai ene, denbora joan zaigu!\n"
	.string "Hurrengora arte guztioi!$"

SlateportCity_OceanicMuseum_1F_Text_InterviewRequest:
	.string "Oh?\n"
	.string "POKéMONak gustuko al dituzu?\p"
	.string "Telebistarako lan bat egiten ari naiz.\p"
	.string "POKéMON eta ENTRENATZAILEEN arteko\n"
	.string "istorio berriak kontatzen ari gara.\p"
	.string "Inporta ez bazaizu, zure inguruko\n"
	.string "zeozer kontatuko zenidake?$"

SlateportCity_OceanicMuseum_1F_Text_InterviewRequestShort:
	.string "Duela gutxi gertatu diren istorioak biltzen\n"
	.string "ari naiz, POKéMON eta ENTRENATZAILEEN artekoak.\p"
	.string "Inporta ez bazaizu, zure inguruko\n"
	.string "zeozer kontatuko zenidake?$"

SlateportCity_OceanicMuseum_1F_Text_TellMeExperienceInvolvingPokemon:
	.string "Oh, bai?\n"
	.string "Eskerrik asko!\p"
	.string "Orduan, mesedez, konta iezadazu\n"
	.string "POKÉMONEKIN azkenaldian gertatu zaizun\l"
	.string "zeoezr interesgarria.$"

SlateportCity_OceanicMuseum_1F_Text_LetMeKnowIfYouHaveStory:
	.string "Oh, ados, ados…\p"
	.string "Bueno, interesgarra den istoriorik\n"
	.string "baduzu kootatzeko, abisatu, mesedez.$"

SlateportCity_OceanicMuseum_1F_Text_ThatsAllForInterview:
	.string "Oh, zer istorio alaia!\p"
	.string "Istorio hau telebistan agertu dadin\n"
	.string "saiatuko naiz.\p"
	.string "Hemendik gutxira atera behar luke,\n"
	.string "beraz, adi egon telebistari.$"

SlateportCity_OceanicMuseum_1F_Text_BetterWriteUpStory:
	.string "Hmmm…\n"
	.string "Telebistako programa batentzako istorio ona dut.\p"
	.string "Hobe dut bizi-bizi idazten badut, ez ahazteko!$"

gTVRecentHappeningsText00::
	.string "Kaixo, ISTORIO BERRIEN garaia da.\p"
	.string "POKéMON ENTRENATZAILEENTZAT egun bakoitza\n"
	.string "ipuin berri bat bezala da.\p"
	.string "Programa hauetan ipuin hauetako batzuk\n"
	.string "kontatzen ditugu.\p"
	.string "Gaurkoan dakarkizuegun istorioa\n"
	.string "{STR_VAR_1} ENTRENATZAILEARENA da.\p"
	.string "Zer gertatu ote zaio {STR_VAR_1}(e)ri azkenaldian?\n"
	.string "Ikus dezagun denok batera.\p"
	.string "Ea ba…$"

gTVRecentHappeningsText01::
	.string "Ez al da zirraragarria izan?\p"
	.string "Istorio hau entzunda badakizu zer gertatu\n"
	.string "zaion {STR_VAR_1}(e)ri azkenaldian.\l"
	.string "ia-ia bertan egon izan bagina bezala da!$"

gTVRecentHappeningsText02::
	.string "“{STR_VAR_3}.” Horrek\n"
	.string "bereziki sakontasuna ematen dio istorioari.$"

gTVRecentHappeningsText03::
	.string "“{STR_VAR_3}.”\n"
	.string "Horrek nolabaiteko toki-zentzua ematen dio.\l"
	.string "Istorioaren lekua ikusiko bagenu bezala.$"

gTVRecentHappeningsText04::
	.string "“{STR_VAR_3}”(r)en sekzioa\n"
	.string "bereziki adierazgarria da.$"

gTVRecentHappeningsText05::
	.string "{STR_VAR_1}(e)k POKÉMONEN inguruko\n"
	.string "istorio liluragarria kontatu digu.\p"
	.string "Eta orain {STR_VAR_1}(r)en ipuina\n"
	.string "zuen arimari lotuta geratu da.\p"
	.string "Hori izan da dena gaurkoz.\n"
	.string "Hurrengora arte, lagunok.$"

gTVMassOutbreakText00::
	.string "Agur bero bat denontzat!\n"
	.string "POKéMON ALBISTEEN garaia da.\p"
	.string "Gertakari oso berezi baten gaineko\n"
	.string "albiste bat jaso dugu.\p"
	.string "Badirudi {STR_VAR_2} agerraldi\n"
	.string "oso indartsu bat gertatu dela\l"
	.string "{STR_VAR_1} inguruan.\p"
	.string "{STR_VAR_2}, ziurrenik badakizu baina,\n"
	.string "bilatzeko zaila den POKéMON bat da\l"
	.string "eta oso gutxitan ikusi ohi da.\p"
	.string "Oso aukera ona da berez {STR_VAR_2}\n"
	.string "horiek kanpoan ikusteko,\l"
	.string "aprobetxatzea onena.\p"
	.string "Hauexek izan dira POKéMON ALBISTEAK.$"

gTV3CheersForPokeblocksText00::
	.string "ZM: Gogotsu egongo zaretela espero dugu,\n"
	.string "“3 GORA {POKEBLOCK}EI” iritsi zaigu!\p"
	.string "Gaur, {STR_VAR_1} eta lagunek nahastutako\n"
	.string "{POKEBLOCK}a aztertuko dugu.\p"
	.string "Gehiago luzatu gabe, nire gourmet\n"
	.string "POKéMON GULPINI emango diot probatzeko.\p"
	.string "… … … … … …\n"
	.string "… … … … … …$"

gTV3CheersForPokeblocksText01::
	.string "GULPIN: Gubi! Gubii!\p"
	.string "ZM: Epaia oso {STR_VAR_1} da!\n"
	.string "GULPINEK dio oso “{STR_VAR_2}” dagoela!\p"
	.string "Mila esker, {STR_VAR_3}!$"

gTV3CheersForPokeblocksText02::
	.string "{STR_VAR_1}(r)en nahasketa abilezia\n"
	.string "pixka bat hobe zitekeen.\p"
	.string "ENTRENATZAILE honek hobe nahastuko balu,\n"
	.string "{POKEBLOCK}a askoz goxoagoa egongo litzateke.$"

gTV3CheersForPokeblocksText03::
	.string "GULPIN: Gubi! Gubii!\p"
	.string "ZM: Hmm… {STR_VAR_1}egia omen dago.\n"
	.string "GULPINek dio “{STR_VAR_2}” dagoela!\p"
	.string "Badirudi {STR_VAR_3}(r)en akatsek\n"
	.string "nahastearen kalitatea okertu dutela…$"

gTV3CheersForPokeblocksText04::
	.string "Pena da {STR_VAR_1}(r)en saiakera\n"
	.string "alferrik galdu izana.\p"
	.string "Hurrengoan {STR_VAR_2}(e)k maila\n"
	.string "hobea emango du, ziur!$"

gTV3CheersForPokeblocksText05::
	.string "Hurrengora arte!\n"
	.string "Gure eslogana gogoratu “3 GORA {POKEBLOCK}EI!”$"

LilycoveCity_PokemonTrainerFanClub_Text_WhatsYourOpinionOfTrainer::
	.string "Kaixo!\p"
	.string "{STR_VAR_1}(r)en oso zalea naiz.\n"
	.string "Zuri zer iruditzen zaizu {STR_VAR_1}?$"

LilycoveCity_PokemonTrainerFanClub_Text_ThatsWhatYouThink::
	.string "Ados, ados. Hori uste duzu beraz\n"
	.string "ENTRENATZAILEAREN inguruan.$"

LilycoveCity_PokemonTrainerFanClub_Text_HaveYouForgottenTrainer::
	.string "Guztiz ahaztu al duzu bada\n"
	.string "{STR_VAR_1}?$"

LilycoveCity_PokemonTrainerFanClub_Text_WhatsYourOpinionOfTrainer2::
	.string "{STR_VAR_1}(r)en oso zalea naiz.\n"
	.string "Zer iruditzen zaizu zuri {STR_VAR_1}?$"

LilycoveCity_PokemonTrainerFanClub_Text_HowStrongRateTrainer::
	.string "Zein nota nota emango zenioke {STR_VAR_1}(e)ri\n"
	.string "batetik ehunerako eskalan?$"

LilycoveCity_PokemonTrainerFanClub_Text_HaveYouForgottenTrainer2::
	.string "Guztiz ahaztu al duzu bada\n"
	.string "{STR_VAR_1}?$"

LilycoveCity_PokemonTrainerFanClub_Text_YouShouldMeetTrainer::
	.string "Oh, Ados!\n"
	.string "{STR_VAR_1} ezagutu behar zenuke noizbait.\l"
	.string "ZU ere zale bilakatuko zinateke, seguru!$"

LilycoveCity_PokemonTrainerFanClub_Text_ThankYouIllShareThisInfo::
	.string "Ados, ados.\p"
	.string "Eskerrik asko!\n"
	.string "Oso erabilgarria da hori.\p"
	.string "{STR_VAR_1}(r)en beste zaletu batzuei kontatuko\n"
	.string "diet hau eta haiekin eztabaidatuko dut.$"

LilycoveCity_PokemonTrainerFanClub_HopeYouCatchTVSpecial::
	.string "Laister telebistan saio berezi bat\n"
	.string "emango dute {STR_VAR_1}(r)en inguruan.\p"
	.string "Ea ikusten duzun!$"

gTVTrainerFanClubSpecialText00::
	.string "ENTRENATZAILEEN ZALETU KLUBA\n"
	.string "{STR_VAR_1} EDIZIO BEREZIA!\p"
	.string "Honakoa aurkezpen berezi bat da HOENNeko\n"
	.string "{STR_VAR_1}(r)en zaletu guztientzat!\p"
	.string "Hau galdetu dugu gaur: “Zer pentsatzen\n"
	.string "du jendeak {STR_VAR_1}(r)en inguruan?”\p"
	.string "{STR_VAR_2}(e)ri galdetu diogu hau\n"
	.string "ENTRENATZAILEEN ordezkari gisan.\p"
	.string "Galdetu genion, “Hitz batean, nola\n"
	.string "deskribatuko zenuke {STR_VAR_1}?”\p"
	.string "Erantzuna: “{STR_VAR_3}.”\p"
	.string "Txalo bero bat {STR_VAR_2}(e)ri!\n"
	.string "Iritzi zolia!\p"
	.string "“{STR_VAR_3} {STR_VAR_1}.”\n"
	.string "Zein ondo geratzen diren bi hitzak batera!\p"
	.string "0tik 100erako eskalan {STR_VAR_1}(r)en\n"
	.string "puntuazioa ere eman zuen {STR_VAR_2}(e)k.$"

gTVTrainerFanClubSpecialText01::
	.string "{STR_VAR_3} puntu eman zizkion!\n"
	.string "A zer nolako puntuazioa!\p"
	.string "{STR_VAR_2}(e)k asko atsegin du\n"
	.string "{STR_VAR_1} duda izpirik gabe.$"

gTVTrainerFanClubSpecialText02::
	.string "{STR_VAR_3} puntu eman zizkion!\n"
	.string "Nahikoa puntuazio ona da hori.\p"
	.string "{STR_VAR_2}(r)entzat etsai\n"
	.string "garrantzitsua da {STR_VAR_1}.$"

gTVTrainerFanClubSpecialText03::
	.string "{STR_VAR_3} puntu eman zizkion!\n"
	.string "Ez da bereziki puntuazio altua.\p"
	.string "{STR_VAR_2}(r)entzat {STR_VAR_1}\n"
	.string "adiskidea bakarrik dela ematen du.$"

gTVTrainerFanClubSpecialText04::
	.string "The score was {STR_VAR_3} point(s)!\n"
	.string "Oso puntuazio baxua da, dudarik gabe.\p"
	.string "{STR_VAR_2}(e)k ez dio garrantzia\n"
	.string "handirik ematen {STR_VAR_1}(e)ri.$"

gTVTrainerFanClubSpecialText05::
	.string "Hori da guztia, lagunok!\p"
	.string "Gaurkoan denok ikasi dugu zerbait\n"
	.string "berria {STR_VAR_1}(r)en inguruan.\p"
	.string "Azkenik, {STR_VAR_2}(r)en hitzekin\n"
	.string "utziko zaituztet.\p"
	.string "{STR_VAR_3} {STR_VAR_1}!$"

gTVNameRaterText00::
	.string "Eta orain, badiritsi da garaia…\n"
	.string "IZEN BALORATZAILEEN SHOWERAKO.\p"
	.string "Zure POKéMONaren etorkizuna iragarriko\n"
	.string "dut, emandako ezizenaren arabera.\p"
	.string "Emateko aholku asko ditut, eta\n"
	.string "oso baliagarriak, gainera.\p"
	.string "Gaur egingo dudan iragarpena\n"
	.string "{STR_VAR_3} ezizenarena izango da,\l"
	.string "{STR_VAR_1}(r)en {STR_VAR_2} POKéMONarena.\p"
	.string "Hmhm…\p"
	.string "Hmm…\n"
	.string "Ezizen hau…$"

gTVNameRaterText01::
	.string "Ezizen hau talentuaren sinonimo da\n"
	.string "hainbat eratan.\p"
	.string "ENTRENATZAILE honek erronka berriak\n"
	.string "hartu behar lituzke, indartsu.$"

gTVNameRaterText02::
	.string "Ezizen hau oso ondo geratzen da\n"
	.string "{STR_VAR_1}(r)ekin, ENTRENATZAILEAREN izenarekin.\p"
	.string "Denborarekin lankidetza-erlazio ederra\n"
	.string "sortuko duzuela iradokitzen du.$"

gTVNameRaterText03::
	.string "Oso ezizen egokia horren POKéMON\n"
	.string "bereziarentzat!\p"
	.string "Ondo haziz gero, POKéMON honen\n"
	.string "berezitasuna izugarri garatuko da!$"

gTVNameRaterText04::
	.string "Ezizen honek POKÉMONEN zaintza eta\n"
	.string "maitasunaren zatia erakusten du.\p"
	.string "Ondo haziz gero, POKéMON hau\n"
	.string "epeltasun handikoa izango da!$"

gTVNameRaterText05::
	.string "Ezizen oso egokia etorkizuneko\n"
	.string "handitasuna isladatzeko.\p"
	.string "Jakin min handia dut etorkizunean\n"
	.string "POKéMON honek ekarriko duena ezagutzeko.$"

gTVNameRaterText06::
	.string "Ezizen ona, POKéMONa sasoi onekoa\n"
	.string "bilakatuko duena!\p"
	.string "POKéMON hau sasoi onean eta indartu\n"
	.string "egongo da denbora luze-luzean.$"

gTVNameRaterText07::
	.string "Ezizen ona, POKéMONa bereziki\n"
	.string "bizia eta aktiboa bihurtuko du!\p"
	.string "Esango nuke POKéMON hau borroketan\n"
	.string "oso ondo ibiliko dela.$"

gTVNameRaterText08::
	.string "Ezizen erakargarria, POKéMONa\n"
	.string "xarmangarria egiten du!\p"
	.string "Ez daukat dudarik, POKéMON hau\n"
	.string "POKéMON LEHIAKETETAN xarmantena izango da.$"

gTVNameRaterText09::
	.string "{STR_VAR_1} ezizenaren erroan\n"
	.string "“{STR_VAR_3}” letra dago.\p"
	.string "Letra hori euskarria ematen dio hurrengo\n"
	.string "“{STR_VAR_2}” letrak, eta horrek ezizenari\l"
	.string "presentzia handia ematen dio.$"

gTVNameRaterText10::
	.string "{STR_VAR_1} ezizena proportzio\n"
	.string "oso orekatua du.\p"
	.string "“{STR_VAR_2}” eta “{STR_VAR_3}” letren presentzia...\n"
	.string "bereziki izugarria da!$"

gTVNameRaterText11::
	.string "{STR_VAR_1}-- ezizenak badu\n"
	.string "nolabaiteko sentsazio sublimea.\p"
	.string "Hasierako “{STR_VAR_2}” letratik hurrengo\n"
	.string "“{STR_VAR_3}” letrarako jauzia itzela da.$"

gTVNameRaterText12::
	.string "Ikus ditzagun beste ezizen fin\n"
	.string "batzuk, ados?$"

gTVNameRaterText13::
	.string "Adibidez, hartu ENTRENATZAILEAREN\n"
	.string "izena: {STR_VAR_1}, eta amaieran\l"
	.string "jarri ezizen itzel hau: {STR_VAR_2}{STR_VAR_3}.$"

gTVNameRaterText14::
	.string "{STR_VAR_2}{STR_VAR_3} ezizena ere nahikoa\n"
	.string "egokia izango litzateke.$"

gTVNameRaterText15::
	.string "POKéMONaren espeziearen izena:\n"
	.string "{STR_VAR_2} oinarri bezala erabili daiteke\l"
	.string "ezizena asmatzeko {STR_VAR_1}{STR_VAR_3}.$"

gTVNameRaterText16::
	.string "{STR_VAR_1}{STR_VAR_3} ere ezizen eraginkorra\n"
	.string "izango litzateke.$"

gTVNameRaterText17::
	.string "Beti sahiestu beharkko litzateke beste\n"
	.string "POKéMON espezie baten izena.\p"
	.string "Adibidez, {STR_VAR_2} izena hartzea\n"
	.string " {STR_VAR_1}{STR_VAR_3} ezizena asmatzeko.\l"
	.string "Hori onartezina da.$"

gTVNameRaterText18::
	.string "Esan beharra dut {STR_VAR_1} nahikoa\n"
	.string "ezizen ona dela.\p"
	.string "Espero dut ENTRENATZAILEAK maitasunez\n"
	.string "jarraituko duela {STR_VAR_1} zaintzen.\p"
	.string "Hau da guztia gaurkoz.\n"
	.string "Hurrengora arte denoi.$"

gTVPokemonAnglerText00::
	.string "{STR_VAR_2} ARRANTZALEA\p"
	.string "AURKEZLEA: Kaixo! Gaurkoan {STR_VAR_2}\n"
	.string "arrantzatzeko aholkuak jasoko ditugu.\p"
	.string "GURU, zein aholku duzu guretzat\n"
	.string "{STR_VAR_2} arrantzatzeko?\p"
	.string "GURU: {STR_VAR_2} arrantzatzeko, e?\n"
	.string "Bueno, ba erraza da, pazientzia izan\l"
	.string "eta itxaron. Hori da kontua.\p"
	.string "Ikusten duzu hor {STR_VAR_1}?\n"
	.string "ENTRENATZAILE hori adibide ona da.\p"
	.string "ENTRENATZAILE horri jada ihes egin\n"
	.string "die {STR_VAR_3} POKÉMONEK.\p"
	.string "Baina hortxe dago {STR_VAR_1} itxaroten.\n"
	.string "Hori da {STR_VAR_2} harrapatzeko egin beharrekoa.\p"
	.string "AURKEZLEA: Ados…\p"
	.string "Oh! {STR_VAR_1}(e)k azkenean aurkitu du\n"
	.string "{STR_VAR_2} iheskor bat!\p"
	.string "ENTRENATZAILEA oso zoriontsu dago,\n"
	.string "ia negarrez!\p"
	.string "Zoriontasun begirada horrekin,\n"
	.string "arrantzatzeko grina datorkit berriz!\p"
	.string "Ikusleok, zergatik ez duzue hau aprobetxatzen\n"
	.string "{STR_VAR_2} batzuk arrantzatzeko?\p"
	.string "Hurrengo programara arte, adio\n"
	.string "eta arrantza on denoi!$"

gTVPokemonAnglerText01::
	.string "{STR_VAR_2} ARRANTZALEA\p"
	.string "AURKEZLEA: Kaixo! Gaurkoan {STR_VAR_2}\n"
	.string "arrantzatzeko aholkuak jasoko ditugu.\p"
	.string "GURU, zein aholku duzu guretzat\n"
	.string "{STR_VAR_2} arrantzatzeko?\p"
	.string "GURU: {STR_VAR_2} arrantzatzeko, e?\n"
	.string "Bueno, erraza da, erabili kemen handiz\l"
	.string "zure KANABERA!\p"
	.string "Ikusten duzu hor {STR_VAR_1}?\n"
	.string "Ikusten nola erabiltzen duen KANABERA?\p"
	.string "ENTRENATZAILE horrek jada harrapatu\n"
	.string "ditu {STR_VAR_3} jarraian.\p"
	.string "AURKEZLEA: Izugarria!\n"
	.string "Ekaitz bat dirudi…\p"
	.string "Horrelako teknika ikusita, arrantza\n"
	.string "egiteko gogoa etorri zait niri ere.\p"
	.string "Ikusleok, zergatik ez duzue hau aprobetxatzen\n"
	.string "{STR_VAR_2} batzuk arrantzazeko?\p"
	.string "Hurrengora programara arte, adio\n"
	.string "eta arrantza on denoi!$"

gTVPokemonTodayFailedText00::
	.string "Kaixo!\p"
	.string "POKéMON GAURREN garaia da!\p"
	.string "ARREBA NAGUSIA: Epa! Alai eta bizi al\n"
	.string "gaude denok gaur?\p"
	.string "Gaurkoan {STR_VAR_1}(r)en {STR_VAR_2}\n"
	.string "POKéMONa ikusiko dugu!\p"
	.string "ANAIA NAGUSIA: Bai! Horixe bera egingo\n"
	.string "dugu!$"

gTVPokemonTodayFailedText01::
	.string "Oh! {STR_VAR_1}(e)ri buruz hitz\n"
	.string "egiten ari garela…\p"
	.string "ARREBA NAGUSI, nire begiekin ikusi\n"
	.string "dut ENTRENATZAILEA!\p"
	.string "ARREBA NAGUSIA: Oh, zer ikusi duzu?\p"
	.string "ANAIA NAGUSIA: Bueno, bidaia bat izan\n"
	.string "nuen {STR_VAR_2}(e)ra.\p"
	.string "Eta bertan aurkitu nuen kasualitatez\n"
	.string "{STR_VAR_1}, {STR_VAR_3} POKéMONa\l"
	.string "harrapatzen saiatzen ari zen, baina…$"

gTVPokemonTodayFailedText02::
	.string "POKéMONak ihes egitea lortu zuen!\p"
	.string "Badakizu zenbat POKé BALL gastatu\n"
	.string "Zituen? {STR_VAR_2}!\p"
	.string "{STR_VAR_1}(r)en aurpegiko frustrazio\n"
	.string "aurpegia ikustekoa izan zen\l"
	.string "POKéMONak ihes egin zuenean!$"

gTVPokemonTodayFailedText03::
	.string "Baina {STR_VAR_1}(e)k txorakeriak egin\n"
	.string "eta POKéMONa ahuldu egin zen!\p"
	.string "Badakizue zenbat POKé BALL gastatu\n"
	.string "zituen? {STR_VAR_2}!\p"
	.string "{STR_VAR_1}(r)en harridura aurpegia\n"
	.string "ikusi behar zenuten POKéMONa\l"
	.string "ahuldu zenean!$"

gTVPokemonTodayFailedText04::
	.string "ARREBA NAGUSIA: Ei, aizu!\n"
	.string "Hori ez da egiten!\p"
	.string "Ez zenioke besteen zorigaitzei\n"
	.string "barre egin behar!\p"
	.string "Oh, {STR_VAR_1} gaixoa.\n"
	.string "Ze pena!\p"
	.string "ANAIA NAGUSIA: Egia da hori!\n"
	.string "Barkatu barre egiteagatik.$"

gTVPokemonTodayFailedText05::
	.string "ARREBA NAGUSIA: Kar kar…\p"
	.string "ANAIA NAGUSIA: Aizu!\n"
	.string "Zuk ere barre egin duzu!\p"
	.string "ARREBA NAGUSIA: Nola?!\p"
	.string "Ez dut barrerik egin!\n"
	.string "benetan, ez dut egin!\p"
	.string "Oh, {STR_VAR_1} gaixoa.\n"
	.string "A zer pena!\p"
	.string "ANAIA NAGUSIA: …$"

gTVPokemonTodayFailedText06::
	.string "ARREBA NAGUSIA: Nahikoa tontakeria\n"
	.string "egin ditugu! Ikus dezagun gaurko\p"
	.string "POKéMONa… Zer?\n"
	.string "Denbroarik gabe geratu al gara?\p"
	.string "Ohh!\n"
	.string "Ezin izan dugu POKéMONa ikusi!\p"
	.string "ANAIA NAGUSIA: Hurrengora arte!\p"
	.string "ARREBA NAGUSIA: Aizu, ez bukatu\n"
	.string "programa ni gabe!$"

gTVPokemonTodaySuccessfulText00::
	.string "Kaixo!\p"
	.string "Iritsi da POKéMON GAUR!\p"
	.string "ARREBA NAGUSIA: Iepa! Alai eta bizi al\n"
	.string "gaude denok gaur?\p"
	.string "Gaurkoan, {STR_VAR_1}(r)en POKéMONa\n"
	.string "ikusiko dugu: {STR_VAR_2}!\p"
	.string "ANAIA NAGUSIA: Bai! Horixe bera\n"
	.string "egingo dugu!$"

gTVPokemonTodaySuccessfulText01::
	.string "ARREBA NAGUSIA: {STR_VAR_1}(e)k {STR_VAR_3}\n"
	.string "ezizena eman zion {STR_VAR_2}(e)ri!\p"
	.string "Badirudi {STR_VAR_3} oso-oso\n"
	.string "maitatua izaten ari dela!$"

gTVPokemonTodaySuccessfulText02::
	.string "ANAIA NAGUSIA: ENTRENATZAILEAK {STR_VAR_3}\n"
	.string "POKé BALL erabili behar izan zituen!\p"
	.string "Azkenean {STR_VAR_2} bakar bat behar\n"
	.string "izan zuen harrapetzeko!$"

gTVPokemonTodaySuccessfulText03::
	.string "ARREBA NAGUSIA: Horren erraza izan\n"
	.string "bazen harrapatzeko, patua izan zen\l"
	.string "{STR_VAR_1} eta {STR_VAR_2} elkartu zituena!$"

gTVPokemonTodaySuccessfulText04::
	.string "ARREBA NAGUSIA: Ene! Hori ederra!\p"
	.string "Badakizu esamoldea, POKéMONa harrapatzeko\n"
	.string "zail eta berezi, ENTRENATZAILEAREN\l"
	.string "maitasuna merezi!$"

gTVPokemonTodaySuccessfulText05::
	.string "ARREBA NAGUSIA: {STR_VAR_1}(r)en {STR_VAR_2}\n"
	.string "POKéMON gogoangarria da, harrapatzeko\l"
	.string "MASTER BALLa erabili behar izan zuelako!\p"
	.string "ANAIA NAGUSIA: Uau! Hori mega-izugarria da!\p"
	.string "ARREBA NAGUSIA: {STR_VAR_1}(e)k benetan\n"
	.string "nahi zuen {STR_VAR_2} hori, argi dago!$"

gTVPokemonTodaySuccessfulText06::
	.string "ANAIA NAGUSIA: Gainera, gero {STR_VAR_3}\n"
	.string "ezizena ematea {STR_VAR_2} horri…\p"
	.string "Ikus dezakezu {STR_VAR_1}(e)k\n"
	.string "duen ENTRENATZAILE sena.\p"
	.string "ARREBA NAGUSIA: Guztiz ados horrekin!$"

gTVPokemonTodaySuccessfulText07::
	.string "Ni izango banintz, ezizen hori emango\n"
	.string "nioke honelako {STR_VAR_3} bati!\p"
	.string "ANAIA NAGUSIA: Ene! Hori zeozer berriaren\n"
	.string "hasiera litzateke!$"

gTVPokemonTodaySuccessfulText08::
	.string "{STR_VAR_2} {STR_VAR_1}(r)a?\n"
	.string "Ez al da perfektua?\p"
	.string "Letrak eta beste guztia--oso\n"
	.string "ondo geratzen zaizkio {STR_VAR_1}\l"
	.string "POKéMONari!\p"
	.string "ANAIA NAGUSIA: Bai, egia, horixe!$"

gTVPokemonTodaySuccessfulText09::
	.string "Nik dakidanez, ez da ENTRENATZAILERIK\n"
	.string "izan {STR_VAR_2} ezizena jarri diona\l"
	.string "bere {STR_VAR_1}(r)ari!\p"
	.string "ANAIA NAGUSIA: Argi eta garbi ikusten\n"
	.string "da ezizenak aukeratzeko zein gustu ona\l"
	.string "duen ENTRENATZAILEAK!$"

gTVPokemonTodaySuccessfulText10::
	.string "POKéMON bat harrapatzen dudanean,\n"
	.string "{STR_VAR_2} ezizena emango diot.\p"
	.string "ANAIA NAGUSIA: Nola? Nik ere bai!\n"
	.string "Nik ere {STR_VAR_2} ezizena erabiliko dut!$"

gTVPokemonTodaySuccessfulText11::
	.string "ARREBA NAGUSIA: Ai, ene!\n"
	.string "Begiratu ordularia!\p"
	.string "Beno, lagunak, ordua da.\n"
	.string "Ikusi arte!\p"
	.string "ANAIA NAGUSIA: Gogoratu, hurrengoan zure\n"
	.string "POKéMONa izan daiteke protagonista!$"

SmartShopper_Text_Intro::
	.string "Kaixo!\p"
	.string "GAURKO EROSLE ARGIAren ordua iritsi da.\p"
	.string "ELKARRIZKETATZAILEA: Zer moduz, ikusleok?\p"
	.string "Gaurkoan bisitatuko dugun denda\n"
	.string "{STR_VAR_2}(e)n dago.\p"
	.string "Ikus dezagun zertan dabiltzan bertako\n"
	.string "saltzaileak azkenaldian.$"

SmartShopper_Text_ClerkNormal::
	.string "Galdetu diezaiogun saltzaileari, ea\n"
	.string "zer dioen.\p"
	.string "Kaixo, zer moduz doa negozioa?\p"
	.string "SALTZAILEA: Ba oraingoz, bikain.\p"
	.string "Azkenaldian, {STR_VAR_2} bereziki\n"
	.string "asko saldu dugu.\p"
	.string "Aurreko batean {STR_VAR_1} izeneko\n"
	.string "ENTRENATZAILE batek {STR_VAR_3} erosi zituen.$"

SmartShopper_Text_RandomComment1::
	.string "ELKARRIZKETATZAILEA: ENTRENATZAILEAK\n"
	.string "{STR_VAR_3} {STR_VAR_2} erosi zituen? A zer nolako pila!\p"
	.string "Nire iritziz, {STR_VAR_1} bidaia luze\n"
	.string "baterako prestatzen arituko da, oso-oso\l"
	.string "urrutiko lekuren batera.\p"
	.string "Bidaiatzeko, {STR_VAR_2}(a)k oso\n"
	.string "garrantzitsuak dira!$"

SmartShopper_Text_RandomComment2::
	.string "ELKARRIZKETATZAILEA: {STR_VAR_2} itemaz ari\n"
	.string "garela, justu {STR_VAR_3} erosi berri\l"
	.string "ditut.\p"
	.string "Azkenean, {STR_VAR_2} item itzela da!$"

SmartShopper_Text_RandomComment3::
	.string "ELKARRIZKETATZAILEA: {STR_VAR_2}?!\n"
	.string "Baina {STR_VAR_3}, benetan?!\p"
	.string "Eznuen uste inork horrenbeste\n"
	.string "erosteko beharrik izango zuenik.\p"
	.string "Ene bada, nik bat edo bi eros ditzaket\n"
	.string "dendara joaten naizenean…$"

SmartShopper_Text_RandomComment4::
	.string "ELKARRIZKETATZAILEA: Behin, {STR_VAR_2}\n"
	.string "item mordo bat erosi nuen.\p"
	.string "baina gehiegi izan ziren azkenean.\n"
	.string "Azkenean damutu egin nintzen…\p"
	.string "Ordudanik, soilik bene-benetan behar\n"
	.string "ditudanak soilik hartzen ditut…\p"
	.string "Ai ene!\p"
	.string "Ez gara nitaz hitz egitera etorri hona!$"

SmartShopper_Text_SecondItem::
	.string "SALTZAILEA: {STR_VAR_1}(e)k {STR_VAR_2} itema\n"
	.string "ere erosi zuen eskergan, denera {STR_VAR_3}.\p"
	.string "ELKARRIZKETATZAILEA: Oh, ideia bikaina.\n"
	.string "{STR_VAR_2} ere oso item ona da.$"

SmartShopper_Text_ThirdItem::
	.string "SALTZAILEA: Eta ENTRENATZAILEAK ere\n"
	.string "{STR_VAR_3} {STR_VAR_2} ere hartu zituen.$"

SmartShopper_Text_DuringSale::
	.string "SALTZAILEA: Gainera, eskaintza handi batean\n"
	.string "erosi zituen. Hori bai erosketa.$"

SmartShopper_Text_OutroNormal::
	.string "ELKARRIZKETATZAILEA: Hmm… {STR_VAR_1}\n"
	.string "pagotxa bilatzaile aparta da!\p"
	.string "Guztira, {STR_VAR_1}(r)en erosketa…\p"
	.string "{STR_VAR_2}¥ izan ziren?!\n"
	.string "A zer nolako kantitatea!\p"
	.string "Ene! Denbora joan zaigu!\n"
	.string "Hurrengo programara arte!$"

SmartShopper_Text_IsVIP::
	.string "SALTZAILEA: {STR_VAR_1} VIP bezeroa da,\n"
	.string "inolako ezbairik gabe.$"

SmartShopper_Text_ClerkMax::
	.string "Galde diezaiogun saltzaileari, ea\n"
	.string "zer dioen.\p"
	.string "Kaixo, zer moduz doa negozioa?\p"
	.string "SALTZAILEA: Oh, sinesgaitza da zenbat\n"
	.string "saltzen ari garen. Ia-ia gehiegi izaten ari da.\p"
	.string "Duela gutxi, {STR_VAR_1} izeneko ENTRENATZAILE\n"
	.string "batek {STR_VAR_2} pila bat erosi zuen.\p"
	.string "ENTRENATZAILE honek ia-ia gure\n"
	.string "{STR_VAR_2} guztiak gastatu zituen.\p"
	.string "Ez nuen inoiz pentsatuko bezero bakarrak\n"
	.string "horrenbeste {STR_VAR_2}erosiko zituenik.\l"
	.string "Zinez sinesgaitza da!\p"
	.string "ELKARRIZKETATZAILEA: Zenbat erosi zituen 100\n"
	.string "edo 200 inguru?\p"
	.string "SALTZAILEA: Ez ez, askoz gehiago!\p"
	.string "ELKARRIZKETATZAILEA: Ai ene!\n"
	.string "{STR_VAR_1} bezero berezia da!\p"
	.string "SALTZAILEA: {STR_VAR_1} VIP bezeroa da,\n"
	.string "inolako ezbairik gabe.$"

SmartShopper_Text_OutroMax::
	.string "ELKARRIZKETATZAILEA: Hmm…\n"
	.string "Izugarria benetan.\p"
	.string "Baina zertarako behar ote zituen\n"
	.string "horrenbeste ENTRENATZAILEAK?\p"
	.string "… …\p"
	.string "Misterio sakona, baina tristeki,\n"
	.string "denbora gastatu zaigu gaurkoz.\l"
	.string "Hurrengo programara arte!\p"
	.string "Hala ere, {STR_VAR_1} enigma hutsa da…$"

gTVWorldOfMastersText00::
	.string "MAISUEN MUNDUA\p"
	.string "Kaixo ikusleok.\p"
	.string "Again ezagun zaizue {STR_VAR_1}\n"
	.string "izeneko ENTRENATZAILEA.\p"
	.string "{STR_VAR_1} famatua da POKéMONak\n"
	.string "harrapatzen maisua delako.\p"
	.string "{STR_VAR_1}(r)en POKéMON bilaketa\n"
	.string "ingurua kontu handiz aztertzean datza.\p"
	.string "Egun gogoangarri batean, ENTRENATZAILEAK\n"
	.string "{STR_VAR_2} pausu ibili zen.\p"
	.string "Egun hartan harrapatutako POKéMON\n"
	.string "kopurua {STR_VAR_3} izan zen!$"

gTVWorldOfMastersText01::
	.string "balentria izugarri hura \n"
	.string "ENTRENATZAILEAREN eta {STR_VAR_1}(r)en\l"
	.string "arteko erlazioari esker izan zen.$"

gTVWorldOfMastersText02::
	.string "Maisu honek eguneko azken {STR_VAR_3}a\n"
	.string "{STR_VAR_2}(e)tik hurbil harrapatu zuen.\p"
	.string "Badirudi POKéMON horri asko gustatzen\n"
	.string "zaiola errekorrak lortzea.\p"
	.string "ENTRENATZAILE bikainak errekor hau\n"
	.string "garaitzen saiatu behar lirateke.\p"
	.string "Hori da guztia gaurkoz.\n"
	.string "Hurrengora arte.$"

gTVTodaysRivalTrainerText00::
	.string "GAURKO ENTRENATZAILE ARERIOA!\p"
	.string "Kaixo, POKéMON ENTRENATZAILEOK!\n"
	.string "Zer moduz zaudete?\p"
	.string "Gaur, beste egunetan bezala,,\n"
	.string "gure arerioetako bat aztertuko dugu!$"

gTVTodaysRivalTrainerText07::
	.string "Gaurko ENTRENATZAILE arerioa {STR_VAR_1} da,\n"
	.string "{STR_VAR_3} inguruan dabil oraintxe.\p"
	.string "{STR_VAR_1}(e)k, oraingoz, {STR_VAR_2} POKéMON\n"
	.string "erregistratu ditu POKéDEXean.$"

gTVTodaysRivalTrainerText08::
	.string "Gaurko ENTRENATZAILE arerioa {STR_VAR_1} da,\n"
	.string "BASE SEKRETU batean dago orain.\p"
	.string "{STR_VAR_1}(e)k, oraingoz, {STR_VAR_2} POKéMON\n"
	.string "erregistratu ditu POKéDEXean.$"

gTVTodaysRivalTrainerText09::
	.string "Gaurko ENTRENATZAILE arerioa {STR_VAR_1} da.\p"
	.string "{STR_VAR_1}(e)k, oraingoz, {STR_VAR_2} POKéMON\n"
	.string "erregistratu ditu POKéDEXean.$"

gTVTodaysRivalTrainerText10::
	.string "Gaurko ENTRENATZAILE arerioa {STR_VAR_1} da,\n"
	.string "ferry batean dago oraintxe.\p"
	.string "{STR_VAR_1}(e)k, oraingoz, {STR_VAR_2} POKéMON\n"
	.string "erregistratu ditu POKéDEXean.$"

	.string "$"

gTVTodaysRivalTrainerText01::
	.string "Eta zenbat DOMINA ote ditu orain gure\n"
	.string "arerioak? {STR_VAR_1} domina guztira!$"

gTVTodaysRivalTrainerText02::
	.string "Baina gure arerioak oraindik ez du\n"
	.string "DOMINARIK lortu!$"

gTVTodaysRivalTrainerText03::
	.string "Gure arerioak oraindik ez du\n"
	.string "BORROKA FRONTEKO Sinbolorik lortu.$"

gTVTodaysRivalTrainerText04::
	.string "Ikus dezagun BORROKA FRONTEKO\n"
	.string "zenbat Sinbolo dituen gure arerioak.\p"
	.string "Urrezko Sinboloak: {STR_VAR_1}!\n"
	.string "Zilarrezko Sinboloak: {STR_VAR_2}!$"

gTVTodaysRivalTrainerText05::
	.string "Gure arerioak {STR_VAR_1} Borroka\n"
	.string "Puntu lortu ditu BORROKA FRONTEAN.$"

gTVTodaysRivalTrainerText06::
	.string "Eta zu nola zabiltza\n"
	.string "{STR_VAR_1}(r)ekin alderatuta?\p"
	.string "Abenturak bizirik darrai!\p"
	.string "ENTRENATZAILEOK!\p"
	.string "Segi dezagun guztiok aurrera\n"
	.string "gure arerioen aurretik!$"

TrendWatcher_Text_Intro::
	.string "ITSASAITZ MODA-JARRAITZAILE KATEA!\p"
	.string "ZM: Ze martxa?\n"
	.string "IHINTZIBARREKO berriak dakarkizuegu,\l"
	.string "guztiak puri-purian.\p"
	.string "Gaur gurian, IHINTZIBARREKO nagusia\n"
	.string "eta autoritatea dela dioen gizon\l"
	.string "zaharra izango dugu.\p"
	.string "Gizon zaharra: Eskerrik asko, bai.\p"
	.string "ZM: Goazen harira, zuzen-zuzenean.\p"
	.string "Zer ari da gertatzen IHINTZIBARREKO\n"
	.string "jende prestuaren artean?\p"
	.string "Gizon zaharra: {STR_VAR_1} {STR_VAR_2}.\p"
	.string "ZM: {STR_VAR_1} {STR_VAR_2},\n"
	.string "beraz?\p"
	.string "Gizon zaharra: Ez.\p"
	.string "{STR_VAR_1} {STR_VAR_2} ez da\n"
	.string "inoiz famatua izan hor.\p"
	.string "Nahi duzu horri buruz hitz egitea?\p"
	.string "ZM: Ez, ba. Jakin nahi duguna da\n"
	.string "zer dagoen orain modan…$"

@ Identical to below, may have been different in other languages
TrendWatcher_Text_MaleTaughtMePhrase::
	.string "Gizon zaharra: {STR_VAR_1} {STR_VAR_2}\n"
	.string "hori esan zidan zegoela modan\l"
	.string "ERROTXIKIKO {STR_VAR_3}(e)k…$"

TrendWatcher_Text_FemaleTaughtMePhrase::
	.string "Gizon zaharra: {STR_VAR_1} {STR_VAR_2}\n"
	.string "hori esan zidan zegoela modan\l"
	.string "ERROTXIKIKO {STR_VAR_3}(e)k…$"

TrendWatcher_Text_PhraseWasHopeless::
	.string "Baina alferrikakoa izan zen.\p"
	.string "{STR_VAR_1} {STR_VAR_2} jaialdia!\p"
	.string "{STR_VAR_1} {STR_VAR_2} txapelketa!\p"
	.string "Saiatu nintzen guztiei ahalik ondoen\n"
	.string "erakusten, baina…\p"
	.string "Agian {STR_VAR_1}(r)en partea ez zen\n"
	.string "egokiena izan…\p"
	.string "ZM: Aizu, barkatu, lagun, orain modan\n"
	.string "dagoena zer den jakin behar dut…$"

@ Identical to below, may have been different in other languages
TrendWatcher_Text_MaleTellMeBigger::
	.string "Gizon zaharra: {STR_VAR_3}!\n"
	.string "Mesedez, esan zerbait hau baino handiagoa\l"
	.string "dena: {STR_VAR_1} {STR_VAR_2}!$"

TrendWatcher_Text_FemaleTellMeBigger::
	.string "Gizon zaharra: {STR_VAR_3}!\n"
	.string "Mesedez, esan zerbait hau baino handiagoa\l"
	.string "dena: {STR_VAR_1} {STR_VAR_2}!$"

TrendWatcher_Text_Outro::
	.string "ZM: …Beno… Ba hortxe duzue,\n"
	.string "moda-modako ikusle maiteok!\p"
	.string "{STR_VAR_1} {STR_VAR_2}…beno…\n"
	.string "Ba hori ez dago modan PORTUONDON!\p"
	.string "Bukatu zait denbora. Ondo segi!\p"
	.string "Gizon zaharra: {STR_VAR_1} {STR_VAR_2}!$"

gTVHoennTreasureInvestigatorsText00::
	.string "HOENNEKO ALTXOR IKERTZAILEAK!\p"
	.string "Aupa, kuadrila!\n"
	.string "Item sekreturik aurkitu al duzue?\p"
	.string "Beti bezala, sekretuak begiztatu\n"
	.string "dituztenen testigantzak izango ditugu!\p"
	.string "has gaitezen gutun batekin.\n"
	.string "Honakoa dio, “{STR_VAR_1} aurkitu dute!”$"

gTVHoennTreasureInvestigatorsText01::
	.string "Ene, hobe dugu ziztuan gutun hau\n"
	.string "aztertzea! Irakurri egingo dizuet.\p"
	.string "…IKERTZAILE agurgarriak,\n"
	.string "ondo zaudetela espero dut.\p"
	.string "Duela gutxi {STR_VAR_2} ikusi nuen\n"
	.string "{STR_VAR_3} inguruan.\p"
	.string "ENTRENATZAILEAK {STR_VAR_1} itema\n"
	.string "aurkitu zuen. A zer inbidia.\p"
	.string "…Beno, ondo egina, {STR_VAR_2}!\p"
	.string "Ikusleok, istorio honek bultza\n"
	.string "zaiteztela ITEMBILATZAILEAK erabiltzera!\p"
	.string "Zuen istorio zirraragarrien zain\n"
	.string "egongo naiz!$"

gTVHoennTreasureInvestigatorsText02::
	.string "Ene, hobe dugu ziztuan gutun hau\n"
	.string "aztertzea! Irakurri egingo dizuet.\p"
	.string "…IKERTZAILE agurgarriak,\n"
	.string "ondo zaudetela espero dut.\p"
	.string "Duela gutxi {STR_VAR_2} ikusi nuen ferrian.\p"
	.string "ENTRENATZAILEAK {STR_VAR_1} itema\n"
	.string "aurkitu zuen. A zer inbidia.\p"
	.string "…Beno, ondo egina, {STR_VAR_2}!\p"
	.string "Ikusleok, istorio honek bultza\n"
	.string "zaiteztela ITEMBILATZAILEAK erabiltzera!\p"
	.string "Zuen istorio zirraragarrien zain\n"
	.string "egongo naiz!$"

gTVFindThatGamerText00::
	.string "BILATU GAMER HORI!\p"
	.string "Aupa, gamer maiteok!\n"
	.string "Zer moduz dabil zuen {STR_VAR_2}?\p"
	.string "Beti bezala, JOKOEN TXOKORA gerturatu\n"
	.string "den ENTRENATZAILE berezi baten inguruan\l"
	.string "hitz egingo dizuegu!\p"
	.string "Gaurkoan, gure gamer bikaina da…\n"
	.string "{STR_VAR_1}!$"

gTVFindThatGamerText01::
	.string "{STR_VAR_1} {STR_VAR_2}(e)an ibili zen\n"
	.string "eta {STR_VAR_3} TXANPON irabazi.\p"
	.string "“{STR_VAR_1} iristen denean, prest\n"
	.string "eduki behar ditugu gure TXANPONAK.”\p"
	.string "Hori diote JOKOEN TXOKOKO langileek\n"
	.string "marmarka gure jokalaria joaten zaienean!\p"
	.string "Viewers, it's best to watch your COINS\n"
	.string "like {STR_VAR_1} if you visit the GAME\l"
	.string "CORNER and play the {STR_VAR_2} game.\p"
	.string "This is live from the GAME CORNER--\n"
	.string "where you can feel the excitement!\p"
	.string "That's all for today!$"

gTVFindThatGamerText02::
	.string "{STR_VAR_1} {STR_VAR_2}(e)an ibili zen\n"
	.string "eta {STR_VAR_3} TXANPON galdu.\p"
	.string "“{STR_VAR_1} etortzen denean, gure\n"
	.string "TXANPON salmenta igo egiten da.”\p"
	.string "Hori diote JOKOEN TXOKOKO langileek\n"
	.string "gure jokalaria joaten zaienean!$"

gTVFindThatGamerText03::
	.string "Ikusleok, zanidu zuen TXANPONAK\n"
	.string "{STR_VAR_1}(e)k bezala JOKOEN TXOKORA\l"
	.string "joan eta {STR_VAR_2}(e)an jolastuz gero.\p"
	.string "JOKOEN TXOKOTIK zuzenean--\n"
	.string "zirrara sentitzen den lekuan!\p"
	.string "Hori da dena gaurkoz!$"

gTVBreakingNewsText00::
	.string "AZKEN ORDUKO ALBISTEAK!$"

gTVBreakingNewsText01::
	.string "{STR_VAR_2} arraro bat harrapatu\n"
	.string "du {STR_VAR_1}(e)k!\p"
	.string "Zuzenean gaude {STR_VAR_3}\n"
	.string "inguruan!\p"
	.string "{STR_VAR_1} gai izan da duela gutxi\n"
	.string "{STR_VAR_2} arraro bat harrapatzeko!$"

gTVBreakingNewsText02::
	.string "{STR_VAR_1} eta {STR_VAR_2} topatu\n"
	.string "zirenean, ENTRENATZAILEAK\l"
	.string "{STR_VAR_3} atera zuen.$"

gTVBreakingNewsText03::
	.string "Borrokan erabilitako POKé BALL\n"
	.string "kopurua honakoa izan zen: {STR_VAR_1}.\p"
	.string "Azkenean, botatako azken {STR_VAR_2}\n"
	.string "izan zen POKéMONa harrapatu zuena.$"

gTVBreakingNewsText04::
	.string "Momentu horretan, {STR_VAR_2}\n"
	.string "eta {STR_VAR_1}(r)en zoriontasun\l"
	.string "oihuak batera entzun ziren.\p"
	.string "Esan behar dut, {STR_VAR_1}(e)k inbidia\n"
	.string "ematen dit. Nik ere oihu egin nahi dut.\p"
	.string "…Hementxe amaitzen da emisioa eszena\n"
	.string "zoriontsu honetatik!$"

gTVBreakingNewsText05::
	.string "{STR_VAR_1}(e)k ez du lortu {STR_VAR_2}\n"
	.string "arraro bat harrapatzea!\p"
	.string "Zuzenean gaude {STR_VAR_3}\n"
	.string "inguruan!\p"
	.string "Hemen izan zen {STR_VAR_1}(r)i\n"
	.string "{STR_VAR_2} arraoak ihes egin zionekoa!$"

gTVBreakingNewsText06::
	.string "{STR_VAR_1}(e)k {STR_VAR_2} arraroa\n"
	.string "aurkitu zuenean, ENTRENATZAILEAK\l"
	.string "{STR_VAR_3} atera zuen.$"

gTVBreakingNewsText07::
	.string "ENTRENATZAILEAK {STR_VAR_2}(r)i\n"
	.string "{STR_VAR_1} erasoa agindu zion.\p"
	.string "Nahi gabe, ordea, ENTRENATZAILEAK\n"
	.string "POKéMONa indargabetu zuen…$"

gTVBreakingNewsText12::
	.string "Hala ere, {STR_VAR_1} urduri jarri\n"
	.string "zen {STR_VAR_2} arraroa ikustean.\p"
	.string "Nahastuta, ENTRENATZAILEAK erasotzeko\n"
	.string "agindu zion {STR_VAR_3}(e)ri.\p"
	.string "Nahi gabe, ordea, ENTRENATZAILEAK\n"
	.string "POKéMONa indargabetu zuen…$"

gTVBreakingNewsText08::
	.string "Momentu horretan, {STR_VAR_2}\n"
	.string "eta {STR_VAR_1}(r)en amorruzko\l"
	.string "garrasiak entzun ziren…$"

gTVBreakingNewsText09::
	.string "Tamalez, {STR_VAR_1} POKé BALLIK\n"
	.string "gabe geratu zen.\p"
	.string "ENTRENATZAILEAK {STR_VAR_2}\n"
	.string "bereziarekin borroka eten behar izan zuen.\p"
	.string "Momentu horretan, {STR_VAR_3}\n"
	.string "eta {STR_VAR_1}(r)en amorruzko\l"
	.string "garrasiak entzun ziren…$"

gTVBreakingNewsText10::
	.string "Tamalez, {STR_VAR_2}(e)k ihes\n"
	.string "egin zuen bat-batean.\p"
	.string "Momentu horretan, {STR_VAR_3}\n"
	.string "eta {STR_VAR_1}(r)en amorruzko\l"
	.string "garrasiak entzun ziren…$"

gTVBreakingNewsText11::
	.string "Pena ematen dit {STR_VAR_1}(e)k.\n"
	.string "Ni ere amorruz betetzen nau egoerak.\p"
	.string "…Hementxe amaitzen da emisioa eszena\n"
	.string "triste honetatik!$"

gTVSecretBaseVisitText00::
	.string "Kaixo, lagunak!\n"
	.string "Iritsi da garaia BASE SEKRETUEN\l"
	.string "BISITA berri baterako.\p"
	.string "Gaur, {STR_VAR_1}(r)en BASE\n"
	.string "SEKRETUA bisitatuko dugu.\p"
	.string "Nola pertsonalizatu du {STR_VAR_1}(e)k\n"
	.string "bere BASE SEKRETUA?\p"
	.string "Ikus dezagun, bada!\n"
	.string "… … … … … …$"

gTVSecretBaseVisitText01::
	.string "Ene!\n"
	.string "Txundigarria!\p"
	.string "{STR_VAR_2} hau…\n"
	.string "Ez nuen espero horrelako ezer\l"
	.string "aurkitzea hemen!$"

gTVSecretBaseVisitText02::
	.string "Ene!\n"
	.string "Hau bai apartekoa!\p"
	.string "Ez dago inolako altzari edo\n"
	.string "bestelakorik hemen barrian!\p"
	.string "Jende normala ez litzateke ausartu\n"
	.string "ere egingo hau egiten!\p"
	.string "Sinplea da, bai, baina\n"
	.string "baita basatia ere!\p"
	.string "Zorionak nire partez, {STR_VAR_1}.\n"
	.string "Zuk ez beste inork ezin zuen hau egin!$"

gTVSecretBaseVisitText03::
	.string "Ene! Ikusten dut, bai!\n"
	.string "Argi eta garbi ikusi ere!\p"
	.string "{STR_VAR_2} hau egotea hemen…\n"
	.string "Mezu argia adierazten du!$"

gTVSecretBaseVisitText04::
	.string "Ene! Ikusten dut, bai!\n"
	.string "Argi eta garbi ikusi ere!\p"
	.string "Espazio hau nahita dago inolako\n"
	.string "objektu eta altzaririk gabe!\p"
	.string "Mezu argia adierazten du!$"

gTVSecretBaseVisitText05::
	.string "Ene bada!\p"
	.string "{STR_VAR_2} eta {STR_VAR_3}\n"
	.string "batera jarri izana!\p"
	.string "It's a dream combination if there\n"
	.string "ever was one!$"

gTVSecretBaseVisitText06::
	.string "Ene bada!\p"
	.string "{STR_VAR_2} honen kokapena\n"
	.string "justu hementxe…\p"
	.string "Bere presentziak BASE SEKRETU\n"
	.string "osoa betetzen du!$"

gTVSecretBaseVisitText07::
	.string "Ene bada!\p"
	.string "Hemen ez dago ezer kokatuta.\p"
	.string "Leku huts honek efektu\n"
	.string "izugarria du BASE SEKRETUAN.$"

gTVSecretBaseVisitText08::
	.string "Ene!\n"
	.string "Hemen dator {STR_VAR_1}!\l"
	.string "Desafia dezagun ENTRENATZAILEA!\p"
	.string "… … … … … …\n"
	.string "… … … … … …$"

gTVSecretBaseVisitText09::
	.string "Aiii…\n"
	.string "Aitortu behar dut, {STR_VAR_1}.\p"
	.string "ENTRENATZAILEAREN POKÉMONEK benetan\n"
	.string "merezi zuten TXAPELDUN izatea.\p"
	.string "Argi eta garbi utzi zuten {STR_VAR_1}\n"
	.string "ENTRENATZAILE gogorra dela.\p"
	.string "Eta {STR_VAR_2}(e)k ezagutzen duela\n"
	.string "{STR_VAR_3} erasoa…\p"
	.string "{STR_VAR_1} ze motatako ENTRENATZAILEA\n"
	.string "den erakusten du.\p"
	.string "Asko ikasi dut, alajaina!$"

gTVSecretBaseVisitText10::
	.string "Iaaaja!\n"
	.string "Aitortu behar dut, {STR_VAR_1}.\p"
	.string "ENTRENATZAILEAREN POKéMONAK\n"
	.string "izugarri gogorrak dira!\p"
	.string "Argi eta garbi utzi zuten {STR_VAR_1}\n"
	.string "ENTRENATZAILE saiatua dela.\p"
	.string "Eta {STR_VAR_2}(e)k ezagutzen duela\n"
	.string "{STR_VAR_3} erasoa…\p"
	.string "{STR_VAR_1} ze motatako ENTRENATZAILEA\n"
	.string "den erakusten du.\p"
	.string "Asko ikasi dut, alajaina!$"

gTVSecretBaseVisitText11::
	.string "Uffff!\n"
	.string "Aitortu behar dut, {STR_VAR_1}.\p"
	.string "ENTRENATZAILEAREN POKéMONAK ondo\n"
	.string "orekatuta hezita daude.\p"
	.string "Argi eta garbi utzi zuten {STR_VAR_1}\n"
	.string "ENTRENATZAILE burutsua dela.\p"
	.string "Eta {STR_VAR_2}(e)k ezagutzen duela\n"
	.string "{STR_VAR_3} erasoa…\p"
	.string "{STR_VAR_1} ze motatako ENTRENATZAILEA\n"
	.string "den erakusten du.\p"
	.string "Asko ikasi dut, alajaina!$"

gTVSecretBaseVisitText12::
	.string "Bueno, bueno!\n"
	.string "Aitortu behar dut, {STR_VAR_1}.\p"
	.string "ENTRENATZAILEAREN POKÉMONEK\n"
	.string "etorkizunerako potentziala daukate.\p"
	.string "{STR_VAR_1}(r)en itxaropen eta\n"
	.string "ametsak erakutsi zituzten.\p"
	.string "Eta {STR_VAR_2}(e)k ezagutzen duela\n"
	.string "{STR_VAR_3} erasoa…\p"
	.string "{STR_VAR_1} ze motatako ENTRENATZAILEA\n"
	.string "den erakusten du.\p"
	.string "Asko ikasi dut, alajaina!$"

gTVSecretBaseVisitText13::
	.string "Esan beharra dut, hori bai hori\n"
	.string "BASE SEKRETU paregabea!\p"
	.string "Ikusleok, aukera baduzue,\n"
	.string "bisitatu {STR_VAR_1}(r)en BASE SEKRETUA.\p"
	.string "Hurrengora arte, ondo segi!$"

gTVPokemonLotteryWinnerFlashReportText00::
	.string "Zirraragarria!\n"
	.string "Dramatikoa!\p"
	.string "POKéMON LOTERIA da\n"
	.string "IRABAZLEAREN IRAGARPENA!\p"
	.string "Kaixo! Zuzenean gaude POKéMON\n"
	.string "LOTERIAREN TXOKOTIK, UR-LILI\l"
	.string "hiriko ZENTRO KOMERTZIALEKO\l"
	.string "beheko solairutik!\p"
	.string "Ohi den bezala, beste zortedun\n"
	.string "ENTRENATZAILE bat agertu da gaur!\p"
	.string "ENTRENATZAILEAREN izena…\n"
	.string "{STR_VAR_1}!\p"
	.string "{STR_VAR_1} izan da {STR_VAR_2}. saria\n"
	.string "eskuratu eta {STR_VAR_3} irabazi duena!\p"
	.string "{STR_VAR_1}!\n"
	.string "Zorionak!\p"
	.string "Ikusleok, ez soilik begiratu,\n"
	.string "zuek ere martxan jarri!\p"
	.string "UR-LILIKO ZENTRO KOMERTZIALEKO\n"
	.string "langileak zure zain gaude!\p"
	.string "Hau zuzeneko emisio bat izan da\n"
	.string "UR-LILIKO ZENTRO KOMERTZIALETIK,\l"
	.string "HOENN osoko salgai onenak ditugu\l"
	.string "hemen!$"

gTVThePokemonBattleSeminarText00::
	.string "POKéMON BORROKA SEMINARIOA!\p"
	.string "Borrokak aztertzen ditugu\n"
	.string "horietatik ikasten saiatzeko.\p"
	.string "Gaurkoan aztertuko dugun borrokan\n"
	.string "{STR_VAR_1} da protagonista.\p"
	.string "{STR_VAR_1}(r)en {STR_VAR_2}\n"
	.string "{STR_VAR_3} baten aurka ari zen…$"

gTVThePokemonBattleSeminarText01::
	.string "Eta {STR_VAR_3} erasoa erabili zuen\n"
	.string "{STR_VAR_2}(r)en aurka…\p"
	.string "Ene… {STR_VAR_1}!\n"
	.string "Hori da egin behar ez dena, aizue!$"

gTVThePokemonBattleSeminarText02::
	.string "Eraso oker horrez gain,\n"
	.string "ENTRENATZAILEAREN {STR_VAR_1}(e)k$"

gTVThePokemonBattleSeminarText03::
	.string "bazekizkien {STR_VAR_1}, {STR_VAR_2},\n"
	.string "eta {STR_VAR_3} erasoak.$"

gTVThePokemonBattleSeminarText04::
	.string "bazekizkien {STR_VAR_1} eta\n"
	.string "{STR_VAR_2} erasoak.$"

gTVThePokemonBattleSeminarText05::
	.string "bazekien {STR_VAR_2} erasoa.$"

gTVThePokemonBattleSeminarText06::
	.string "beraz, egoera horretan zein eraso\n"
	.string "erabili behar zuen ENTRENATZAILEAK?\p"
	.string "… … … … … …\n"
	.string "{STR_VAR_1} erasoa!\p"
	.string "{STR_VAR_1} erasoa askoz hobea\n"
	.string "zatekeen {STR_VAR_2} baino.\p"
	.string "Ikusleok, ikasi ezazue adibide\n"
	.string "honetatik eta tentuz borrokatu!\p"
	.string "Hurrengora arte, agur!$"

gTVTrainerFanClubText00::
	.string "Ea ba, guztiok batera!\n"
	.string "ENTRENATZAILE FAN KLUBA!\p"
	.string "ZM: Zelan dabil jendea'?\n"
	.string "Gaurkoan hiper famatua den {STR_VAR_1}\l"
	.string "ENTRENATZAILEAREN fanak ditugu gurean!\p"
	.string "FANAK: Wrooooooaaaaah!\p"
	.string "FANAK: {STR_VAR_1}!\p"
	.string "ZM: Guztiok!\n"
	.string "Zenbat atsegin duzue {STR_VAR_1}?!\p"
	.string "FANAK: Maite dugu {STR_VAR_1}!\p"
	.string "ZM: berak egiten duen zer\n"
	.string "gustatzen zaizue gehien?!$"

gTVTrainerFanClubText01::
	.string "FANAK: POKé BALLAK botatzeko duen\n"
	.string "estilo paregabea!$"

gTVTrainerFanClubText02::
	.string "FANAK: Bere korrika egiteko modua!$"

gTVTrainerFanClubText03::
	.string "FANAK: Momentu zailei aurre\n"
	.string "egiteko duen indarra!$"

gTVTrainerFanClubText04::
	.string "FANAK: POKéMONEN inguruan duen\n"
	.string "jakinduria erraldoia!$"

gTVTrainerFanClubText05::
	.string "FANAK: POKéMONAK tratatzeko duen\n"
	.string "jatortasun eta goxotasuna!$"

gTVTrainerFanClubText06::
	.string "FANAK: BIZIKLETAN ibiltzeko duen\n"
	.string "abilezia paregabea!$"

gTVTrainerFanClubText07::
	.string "FANAK: Itemak erosteko duen estilo\n"
	.string "sinesgaitza!$"

gTVTrainerFanClubText08::
	.string "FANAK: POKéMONEI ezizenak jartzeko\n"
	.string "duen era polita!$"

gTVTrainerFanClubText09::
	.string "FANAK: BASE SEKRETUA apaintzeko\n"
	.string "duen estilo bikaina!$"

gTVTrainerFanClubText10::
	.string "FANAK: TMAK erabiltzeko duen\n"
	.string "forma burutsua!$"

gTVTrainerFanClubText11::
	.string "ZM: Ikus dezakezuenez, {STR_VAR_1}\n"
	.string "modan dago! Bene-benetan modan!\p"
	.string "{STR_VAR_1}(r)en FANEN\n"
	.string "artean badute eslogan bat!\p"
	.string "ZM: Nik {STR_VAR_1} esatean,\n"
	.string "zuek diozue…\p"
	.string "FANAK: {STR_VAR_2}!\p"
	.string "FANAK: {STR_VAR_3}!\p"
	.string "FANAK: {STR_VAR_2}!\p"
	.string "FANAK: {STR_VAR_3}!\p"
	.string "ZM: Hori da, norbaitek esaten badu,\n"
	.string "“{STR_VAR_1}”…\p"
	.string "Erantzun, indartsu, “{STR_VAR_2}\n"
	.string "{STR_VAR_3}!”\p"
	.string "Izugarri ondo geratzen da!\n"
	.string "Uler dezaket horrenbeste FAN\l"
	.string "izatea {STR_VAR_1}(e)k!\p"
	.string "Orain zure txanda da, ikusle!\n"
	.string "Denok batera!\p"
	.string "ZM: Nik {STR_VAR_1} esatean,\n"
	.string "zuek diozue…\p"
	.string "FANAK: {STR_VAR_2}!\p"
	.string "FANAK: {STR_VAR_3}!\p"
	.string "FANAK: {STR_VAR_2}!\p"
	.string "FANAK: {STR_VAR_3}!\p"
	.string "ZM: Eskerrik asko etortzeagatik,\n"
	.string "{STR_VAR_1}(r)en FAN gartsuok!\l"
	.string "Hori izan da dena! Hurrengora arte!\p"
	.string "ZM: Nik {STR_VAR_1} esatean,\n"
	.string "zuek diozue…\p"
	.string "FANAK: {STR_VAR_2}!\p"
	.string "FANAK: {STR_VAR_3}!$"

TVSpotTheCuties_Text_Intro::
	.string "AURKITU EDERRENAK!\n"
	.string "ZINTADUN POKéMONAK!\p"
	.string "Kaixo, ikusle maiteok!\p"
	.string "Badakit ados zaudetela, baina POKéMON\n"
	.string "bat ZINTA bat jantzita, miragarria da!\p"
	.string "Gaur, zuekin konpartitu nahi dut\n"
	.string "hirian paseatzen ari nintzela ikusi\l"
	.string "nuen POKéMON xarmant bat.\p"
	.string "Gaurkoan aurkeztuko dugun POKéMONA\n"
	.string "da {STR_VAR_1}(r)en {STR_VAR_2}.$"

TVSpotTheCuties_Text_RibbonsLow::
	.string "{STR_VAR_2}(r)en ZINTA\n"
	.string "kopurua {STR_VAR_3} da.\p"
	.string "Argi uzten du {STR_VAR_1}\n"
	.string "oso POKéMON zalea dela.$"

TVSpotTheCuties_Text_RibbonsMid::
	.string "{STR_VAR_2}(r)en zinta kopurua da…\n"
	.string "{STR_VAR_3} ZINTA itzel!\p"
	.string "Erakusten du {STR_VAR_1}(e)k baduela\n"
	.string "POKéMONEKIKO ardura!$"

TVSpotTheCuties_Text_RibbonsHigh::
	.string "{STR_VAR_2}(r)en zinta kopurua da…\n"
	.string "{STR_VAR_3} ZINTA bikain!\p"
	.string "Erakusten du {STR_VAR_1}(e)k baduela\n"
	.string "bildumagile sen erraldoia!$"

TVSpotTheCuties_Text_RibbonIntro::
	.string "Ikus ditzagun areta gehiagoz\n"
	.string "{STR_VAR_2}(r)en ZINTA guztiak.$"

TVSpotTheCuties_Text_RibbonChampion::
	.string "TXAPELDUNEN ZINTA bereziki da\n"
	.string "deigarria.\p"
	.string "{STR_VAR_2} received it upon entering\n"
	.string "the HALL OF FAME.\p"
	.string "It verily draws out the bravery\n"
	.string "of {STR_VAR_2}.\p"
	.string "{STR_VAR_2} and the CHAMP RIBBON!\n"
	.string "The combination is super effective!$"

TVSpotTheCuties_Text_RibbonCool::
	.string "KARSIMADUNEN ZINTA bereziki da\n"
	.string "deigarria.\p"
	.string "{STR_VAR_2} received it for winning\n"
	.string "a COOL CONTEST.\p"
	.string "It verily draws out the coolness\n"
	.string "of {STR_VAR_2}.\p"
	.string "{STR_VAR_2} and the COOL RIBBON!\n"
	.string "The combination is super effective!$"

TVSpotTheCuties_Text_RibbonBeauty::
	.string "EDERTASUN ZINTA bereziki da\n"
	.string "deigarria.\p"
	.string "{STR_VAR_2} received it for winning\n"
	.string "a BEAUTY CONTEST.\p"
	.string "It verily draws out the beauty\n"
	.string "of {STR_VAR_2}.\p"
	.string "{STR_VAR_2} and the BEAUTY RIBBON!\n"
	.string "The combination is super effective!$"

TVSpotTheCuties_Text_RibbonCute::
	.string "POLITENEN ZINTA bereziki da\n"
	.string "deigarria.\p"
	.string "{STR_VAR_2} received it for winning\n"
	.string "a CUTE CONTEST.\p"
	.string "It verily draws out the cuteness\n"
	.string "of {STR_VAR_2}.\p"
	.string "{STR_VAR_2} and the CUTE RIBBON!\n"
	.string "The combination is super effective!$"

TVSpotTheCuties_Text_RibbonSmart::
	.string "AZKARRENEN ZINTA bereziki da\n"
	.string "deigarria.\p"
	.string "{STR_VAR_2} received it for winning\n"
	.string "a SMART CONTEST.\p"
	.string "It verily draws out the smartness\n"
	.string "of {STR_VAR_2}.\p"
	.string "{STR_VAR_2} and the SMART RIBBON!\n"
	.string "The combination is super effective!$"

TVSpotTheCuties_Text_RibbonTough::
	.string "GOGORRENEN ZINTA bereziki da\n"
	.string "deigarria.\p"
	.string "{STR_VAR_2} received it for winning\n"
	.string "a TOUGH CONTEST.\p"
	.string "It verily draws out the toughness\n"
	.string "of {STR_VAR_2}.\p"
	.string "{STR_VAR_2} and the TOUGH RIBBON!\n"
	.string "The combination is super effective!$"

TVSpotTheCuties_Text_RibbonWinning::
	.string "IRABAZLEAREN ZINTA bereziki da\n"
	.string "deigarria.\p"
	.string "{STR_VAR_2} received it for its feats\n"
	.string "at the BATTLE TOWER.\p"
	.string "It verily draws out the mightiness\n"
	.string "of {STR_VAR_2}.\p"
	.string "{STR_VAR_2} and the WINNING RIBBON!\n"
	.string "The combination is super effective!$"

TVSpotTheCuties_Text_RibbonVictory::
	.string "GARAIPEN ZINTA bereziki da\n"
	.string "deigarria.\p"
	.string "{STR_VAR_2} received it for its feats\n"
	.string "at the BATTLE TOWER.\p"
	.string "It verily draws out the incredible\n"
	.string "mightiness of {STR_VAR_2}.\p"
	.string "{STR_VAR_2} and the VICTORY RIBBON!\n"
	.string "The combination is super effective!$"

TVSpotTheCuties_Text_RibbonArtist::
	.string "ARTISTEN ZINTA bereziki da\n"
	.string "deigarria.\p"
	.string "{STR_VAR_2} received it for being\n"
	.string "the model for an artist.\p"
	.string "It verily draws out the pop-star charm\n"
	.string "of {STR_VAR_2}.\p"
	.string "{STR_VAR_2} and the ARTIST RIBBON!\n"
	.string "The combination is super effective!$"

TVSpotTheCuties_Text_RibbonEffort::
	.string "LANGILEENEN ZINTA bereziki da\n"
	.string "deigarria.\p"
	.string "{STR_VAR_2} received it for being\n"
	.string "an especially dedicated worker.\p"
	.string "It verily draws out the determination\n"
	.string "of {STR_VAR_2}.\p"
	.string "{STR_VAR_2} and the Hard Worker RIBBON!\n"
	.string "The combination is super effective!$"

TVSpotTheCuties_Text_Outro::
	.string "…Sigh…\p"
	.string "RIBBONS and POKéMON…\n"
	.string "They go so wonderfully together!\p"
	.string "Before I swoon,\n"
	.string "I bid you all farewell!$"

gTVPokemonNewsBattleFrontierText00::
	.string "Greetings!\n"
	.string "It's time for POKéMON NEWS.\p"
	.string "We've got some uplifting news from\n"
	.string "the BATTLE FRONTIER.$"

gTVPokemonNewsBattleFrontierText01::
	.string "The TRAINER {STR_VAR_1} set a new\n"
	.string "{STR_VAR_2}-win-streak record while on\l"
	.string "the BATTLE TOWER's SINGLE BATTLE\l"
	.string "ROOM challenge.\p"
	.string "Here's to {STR_VAR_1}!$"

gTVPokemonNewsBattleFrontierText02::
	.string "The TRAINER {STR_VAR_1} set a new\n"
	.string "{STR_VAR_2}-win-streak record while on\l"
	.string "the BATTLE TOWER's DOUBLE BATTLE\l"
	.string "ROOM challenge.\p"
	.string "Here's to {STR_VAR_1}!$"

gTVPokemonNewsBattleFrontierText03::
	.string "The TRAINER {STR_VAR_1} set a new\n"
	.string "{STR_VAR_2}-win-streak record while on\l"
	.string "the BATTLE TOWER's MULTI BATTLE\l"
	.string "ROOM challenge.\p"
	.string "Here's to {STR_VAR_1}!$"

gTVPokemonNewsBattleFrontierText04::
	.string "The TRAINER {STR_VAR_1} set a new\n"
	.string "{STR_VAR_2}-win-streak record while on\l"
	.string "the BATTLE TOWER's LINK MULTI BATTLE\l"
	.string "ROOM challenge.\p"
	.string "Here's to {STR_VAR_1}!$"

gTVPokemonNewsBattleFrontierText05::
	.string "The TRAINER {STR_VAR_1} set a new\n"
	.string "{STR_VAR_2}-championship-streak record\l"
	.string "competing in the BATTLE DOME's\l"
	.string "SINGLE BATTLE Tournaments.\p"
	.string "Here's to {STR_VAR_1}!$"

gTVPokemonNewsBattleFrontierText06::
	.string "The TRAINER {STR_VAR_1} set a new\n"
	.string "{STR_VAR_2}-championship-streak record\l"
	.string "competing in the BATTLE DOME's\l"
	.string "DOUBLE BATTLE Tournaments.\p"
	.string "Here's to {STR_VAR_1}!$"

gTVPokemonNewsBattleFrontierText07::
	.string "The TRAINER {STR_VAR_1} set a new\n"
	.string "{STR_VAR_2}-win-streak record while on\l"
	.string "the BATTLE FACTORY's Battle\l"
	.string "Swap Single challenge.\p"
	.string "Here's to {STR_VAR_1}!$"

gTVPokemonNewsBattleFrontierText08::
	.string "The TRAINER {STR_VAR_1} set a new\n"
	.string "{STR_VAR_2}-win-streak record while on\l"
	.string "the BATTLE FACTORY's Battle\l"
	.string "Swap Double challenge.\p"
	.string "Here's to {STR_VAR_1}!$"

gTVPokemonNewsBattleFrontierText09::
	.string "The TRAINER {STR_VAR_1} set a new\n"
	.string "record of clearing {STR_VAR_2} rooms\l"
	.string "while on the BATTLE PIKE's Battle\l"
	.string "Choice challenge.\p"
	.string "Here's to {STR_VAR_1}!$"

gTVPokemonNewsBattleFrontierText10::
	.string "The TRAINER {STR_VAR_1} set a new\n"
	.string "{STR_VAR_2}-win-streak record while\l"
	.string "competing in the BATTLE ARENA's\l"
	.string "Set KO Tournaments.\p"
	.string "Here's to {STR_VAR_1}!$"

gTVPokemonNewsBattleFrontierText11::
	.string "The TRAINER {STR_VAR_1} set a new\n"
	.string "{STR_VAR_2}-win-streak record while on\l"
	.string "the BATTLE PALACE's SINGLE BATTLE\l"
	.string "HALL challenge.\p"
	.string "Here's to {STR_VAR_1}!$"

gTVPokemonNewsBattleFrontierText12::
	.string "The TRAINER {STR_VAR_1} set a new\n"
	.string "{STR_VAR_2}-win-streak record while on\l"
	.string "the BATTLE PALACE's DOUBLE BATTLE\l"
	.string "HALL challenge.\p"
	.string "Here's to {STR_VAR_1}!$"

gTVPokemonNewsBattleFrontierText13::
	.string "The TRAINER {STR_VAR_1} set a new\n"
	.string "record of clearing {STR_VAR_2} floors\l"
	.string "while on the BATTLE PYRAMID's\l"
	.string "Battle Quest challenge.\p"
	.string "Here's to {STR_VAR_1}!$"

gTVPokemonNewsBattleFrontierText14::
	.string "And to the three POKéMON, {STR_VAR_1},\n"
	.string "{STR_VAR_2}, and {STR_VAR_3}!\p"
	.string "Congratulations for your\n"
	.string "record-breaking performance!$"

gTVPokemonNewsBattleFrontierText15::
	.string "And to the two POKéMON, {STR_VAR_1}\n"
	.string "and {STR_VAR_2}!\p"
	.string "Congratulations for your\n"
	.string "record-breaking performance!$"

gTVPokemonNewsBattleFrontierText16::
	.string "And to the four POKéMON: {STR_VAR_1}!\p"
	.string "{STR_VAR_2}!\p"
	.string "{STR_VAR_3}!$"

gTVPokemonNewsBattleFrontierText17::
	.string "And {STR_VAR_1}!\p"
	.string "Congratulations for your\n"
	.string "record-breaking performance!$"

gTVPokemonNewsBattleFrontierText18::
	.string "Let's hope for more record-setting\n"
	.string "feats from {STR_VAR_1} and the loyal\l"
	.string "POKéMON!\p"
	.string "That's the news on POKéMON NEWS!$"

gTVWhatsNo1InHoennTodayText00::
	.string "WHAT'S NO. 1 IN HOENN TODAY?\n"
	.string "Yes, it's that time again!\p"
	.string "Hello, viewers! Are you giving your\n"
	.string "best at whatever you do?\p"
	.string "Let's have a look at the TRAINER\n"
	.string "who did the very best today!\p"
	.string "Today's no. 1 TRAINER is none other\n"
	.string "than {STR_VAR_1}!$"

gTVWhatsNo1InHoennTodayText01::
	.string "In one day, {STR_VAR_1} spun the SLOTS\n"
	.string "at the GAME CORNER {STR_VAR_2} times.\p"
	.string "While playing, {STR_VAR_1} was heard\n"
	.string "murmuring, “For me, the reels don't\l"
	.string "even move…”\l"
	.string "Isn't that interesting?$"

gTVWhatsNo1InHoennTodayText02::
	.string "In one day, {STR_VAR_1} played\n"
	.string "the ROULETTE game at the GAME\l"
	.string "CORNER {STR_VAR_2} times.\p"
	.string "While playing, {STR_VAR_1} shouted,\n"
	.string "“Let the balls decide!”\p"
	.string "The TRAINER's eyes were focused and\n"
	.string "the face showed concentration.$"

gTVWhatsNo1InHoennTodayText03::
	.string "In one day, {STR_VAR_1} battled\n"
	.string "wild POKéMON {STR_VAR_2} times!\p"
	.string "Apparently, {STR_VAR_1}'s POKéMON\n"
	.string "have grown incomparably stronger.\p"
	.string "They appear eager to battle anywhere,\n"
	.string "anytime, and anyhow!$"

gTVWhatsNo1InHoennTodayText04::
	.string "In just one day, {STR_VAR_1} spun\n"
	.string "the BERRY BLENDER {STR_VAR_2} times!\p"
	.string "Toward the end, even {STR_VAR_1}\n"
	.string "seemed to get dizzy.\p"
	.string "The TRAINER appeared to totter\n"
	.string "around like a SPINDA!$"

gTVWhatsNo1InHoennTodayText05::
	.string "In just one day, {STR_VAR_1} planted\n"
	.string "{STR_VAR_2} BERRIES!\p"
	.string "As a result, {STR_VAR_1}'s clothes\n"
	.string "became filthy with dirt.\p"
	.string "Where the TRAINER planted, countless\n"
	.string "flowers have burst into bloom.\p"
	.string "The flowers are said to soothe\n"
	.string "the emotions of people.$"

gTVWhatsNo1InHoennTodayText06::
	.string "In just one day, {STR_VAR_1} picked\n"
	.string "{STR_VAR_2} BERRIES!\p"
	.string "{STR_VAR_1}'s BAG became so filled\n"
	.string "with BERRIES, the TRAINER had trouble\l"
	.string "walking afterward!$"

gTVWhatsNo1InHoennTodayText07::
	.string "In just one day, {STR_VAR_1} obtained\n"
	.string "{STR_VAR_2} Battle Points!\p"
	.string "{STR_VAR_1} was later seen wrestling\n"
	.string "with the choice of exchanging\l"
	.string "the Battle Points for a cool item or\l"
	.string "a nifty interior decoration.\p"
	.string "The TRAINER reportedly was grinning\n"
	.string "while mulling options.$"

gTVWhatsNo1InHoennTodayText08::
	.string "Well, isn't that something!\p"
	.string "{STR_VAR_1}!\n"
	.string "You're today's no. 1 TRAINER!\p"
	.string "Viewers, take heart from {STR_VAR_1}!\n"
	.string "You, too, can be no. 1 every day!$"

TVSecretBaseSecrets_Text_Intro::
	.string "SECRET BASE SECRETS!\p"
	.string "What do TRAINERS do in the secrecy\n"
	.string "of SECRET BASES?\p"
	.string "Today, we investigate {STR_VAR_1}'s\n"
	.string "SECRET BASE.\p"
	.string "Oh? It looks like {STR_VAR_2} has come\n"
	.string "for a visit.\p"
	.string "Let's have a peek!\p"
	.string "What will {STR_VAR_2} do?$"

TVSecretBaseSecrets_Text_WhatWillPlayerDoNext1::
	.string "What will {STR_VAR_2} do next?$"

TVSecretBaseSecrets_Text_WhatWillPlayerDoNext2::
	.string "And now, what will {STR_VAR_2} do?$"

TVSecretBaseSecrets_Text_TookXStepsBeforeLeaving::
	.string "In the end, {STR_VAR_2} took {STR_VAR_3} steps\n"
	.string "in {STR_VAR_1}'s SECRET BASE before\l"
	.string "leaving.$"

TVSecretBaseSecrets_Text_BaseFailedToInterestPlayer::
	.string "Hmm…\p"
	.string "It appears as if {STR_VAR_1}'s SECRET\n"
	.string "BASE failed to interest {STR_VAR_2}…$"

TVSecretBaseSecrets_Text_PlayerEnjoyedBase::
	.string "{STR_VAR_2} appears to have enjoyed\n"
	.string "{STR_VAR_1}'s SECRET BASE thoroughly.$"

TVSecretBaseSecrets_Text_PlayerHugeFanOfBase::
	.string "{STR_VAR_2} appears to have become\n"
	.string "a huge fan of {STR_VAR_1}'s\l"
	.string "SECRET BASE.$"

TVSecretBaseSecrets_Text_Outro::
	.string "Viewers may want to check out\n"
	.string "{STR_VAR_1}'s SECRET BASE, too.\p"
	.string "Tune in next time as we visit another\n"
	.string "SECRET BASE! Thanks for joining us!$"

TVSecretBaseSecrets_Text_StoppedMoving1::
	.string "The visitor has stopped!\p"
	.string "The visitor isn't moving at all!\p"
	.string "Was {STR_VAR_1}'s SECRET BASE\n"
	.string "that unimpressive?$"

TVSecretBaseSecrets_Text_StoppedMoving2::
	.string "The visitor has stopped!\p"
	.string "The visitor isn't moving at all!\p"
	.string "Is it fatigue?\n"
	.string "Has the visitor grown weary?$"

TVSecretBaseSecrets_Text_UsedChair::
	.string "The visitor sat down on a chair!\n"
	.string "The visitor is seated!\p"
	.string "Look at that look of delight!\p"
	.string "That chair must be very comfortable\n"
	.string "to get that response!$"

TVSecretBaseSecrets_Text_UsedBalloon::
	.string "The visitor charged at a balloon!\p"
	.string "It burst!\n"
	.string "Oh, my goodness, it popped!\p"
	.string "The visitor appears startled by\n"
	.string "the sudden noise!$"

TVSecretBaseSecrets_Text_UsedTent::
	.string "The visitor entered a TENT!\p"
	.string "The visitor is running around!\p"
	.string "Oh, my, the visitor is frolicking!\p"
	.string "The visitor appears surprised by\n"
	.string "the TENT's size!$"

TVSecretBaseSecrets_Text_UsedPlant::
	.string "The visitor is examining\n"
	.string "a potted plant!\p"
	.string "The visitor has surprisingly\n"
	.string "mature taste!$"

TVSecretBaseSecrets_Text_UsedGoldShield::
	.string "The visitor is examining\n"
	.string "a GOLD SHIELD!\p"
	.string "The visitor's eyes appear to be\n"
	.string "lit up with wonder!$"

TVSecretBaseSecrets_Text_UsedSilverShield::
	.string "The visitor is examining\n"
	.string "a SILVER SHIELD!\p"
	.string "The visitor appears to be wide-eyed!$"

TVSecretBaseSecrets_Text_UsedGlassOrnament::
	.string "The visitor is examining\n"
	.string "a GLASS ORNAMENT!\p"
	.string "Oh, no!\p"
	.string "The visitor is touching it!\p"
	.string "It's getting covered with\n"
	.string "fingerprints…$"

TVSecretBaseSecrets_Text_UsedTV::
	.string "The visitor is watching television!\p"
	.string "Looks like we have a big fan of TV!$"

TVSecretBaseSecrets_Text_UsedMudBall::
	.string "The visitor stomped on a MUD BALL!\p"
	.string "The visitor looks delighted!$"

TVSecretBaseSecrets_Text_UsedBag::
	.string "…Oh?\p"
	.string "The visitor is reaching for their own\n"
	.string "BAG and rummaging about in it!\p"
	.string "The visitor pulled out\n"
	.string "one {STR_VAR_2}!\p"
	.string "Look at the visitor smile while\n"
	.string "holding up the {STR_VAR_2}!\p"
	.string "It's like a TV commercial!$"

TVSecretBaseSecrets_Text_UsedCushion::
	.string "The visitor grabs a cushion and…$"

TVSecretBaseSecrets_Text_HitCushion::
	.string "…begins hitting it!\p"
	.string "Is the visitor under a lot of stress?$"

TVSecretBaseSecrets_Text_HuggedCushion::
	.string "…hugs it tight!\p"
	.string "Could the visitor be feeling happy\n"
	.string "about something?$"

TVSecretBaseSecrets_Text_BattledWon::
	.string "The visitor is chatting with\n"
	.string "{STR_VAR_1}!\p"
	.string "It looks like they're going to\n"
	.string "have a battle!\p"
	.string "And…\p"
	.string "It's the visitor!\n"
	.string "The visitor won an away match!\p"
	.string "The visitor is doing\n"
	.string "a victory dance!$"

TVSecretBaseSecrets_Text_BattledLost::
	.string "The visitor is chatting with\n"
	.string "{STR_VAR_1}!\p"
	.string "It looks like they're going to\n"
	.string "have a battle!\p"
	.string "And…\p"
	.string "It's {STR_VAR_1}!\n"
	.string "The visitor has lost!\p"
	.string "The visitor looks dejected!$"

TVSecretBaseSecrets_Text_DeclinedBattle::
	.string "The visitor is chatting with\n"
	.string "{STR_VAR_1}!\p"
	.string "It looks like they're going to\n"
	.string "have a battle!\p"
	.string "And…\p"
	.string "No, the visitor has refused!\p"
	.string "There won't be a battle after all!\p"
	.string "Did the visitor find {STR_VAR_1}\n"
	.string "unappealing?$"

TVSecretBaseSecrets_Text_UsedPoster::
	.string "The visitor is staring intently\n"
	.string "at a poster!\p"
	.string "Is the poster to the visitor's\n"
	.string "liking?\p"
	.string "…But… There's something disturbing\n"
	.string "about the visitor's stares.$"

TVSecretBaseSecrets_Text_UsedNoteMat::
	.string "The visitor stepped on a NOTE MAT!\p"
	.string "…Hmm…\n"
	.string "The visitor composed a funny tune!$"

TVSecretBaseSecrets_Text_BattledDraw::
	.string "The visitor is chatting with\n"
	.string "{STR_VAR_1}!\p"
	.string "It looks like they're going to\n"
	.string "have a battle!\p"
	.string "And…\p"
	.string "It's a draw!\n"
	.string "Nothing's resolved!\p"
	.string "Both TRAINERS appear to be very\n"
	.string "disappointed!$"

TVSecretBaseSecrets_Text_UsedSpinMat::
	.string "The visitor stepped on\n"
	.string "a SPIN MAT!\p"
	.string "It looks like the visitor is dizzy!\p"
	.string "The visitor is tottering about!\n"
	.string "Look out!$"

TVSecretBaseSecrets_Text_UsedSandOrnament::
	.string "The visitor is reaching for\n"
	.string "a SAND ORNAMENT!\p"
	.string "Oh!\p"
	.string "It crumbled!\n"
	.string "It's fallen apart!\p"
	.string "The visitor looks sheepish\n"
	.string "and guilty!$"

TVSecretBaseSecrets_Text_UsedDesk::
	.string "The visitor is rubbing a desktop\n"
	.string "with their finger!\p"
	.string "Apparently, the visitor disapproves\n"
	.string "of dust!\p"
	.string "The visitor is surprisingly concerned\n"
	.string "about neatness!$"

TVSecretBaseSecrets_Text_UsedBrick::
	.string "The visitor is staring at a BRICK!\p"
	.string "Perhaps the visitor is thinking about\n"
	.string "the object on the BRICK.$"

TVSecretBaseSecrets_Text_UsedSolidBoard::
	.string "The visitor is walking across\n"
	.string "the SOLID BOARD.\p"
	.string "The visitor keeps looking down.\p"
	.string "The visitor appears to be surprisingly\n"
	.string "timid and cautious!$"

TVSecretBaseSecrets_Text_UsedFence::
	.string "The visitor is looking intently\n"
	.string "at a FENCE!\p"
	.string "Has a new idea for a trap popped\n"
	.string "into the visitor's head?$"

TVSecretBaseSecrets_Text_UsedGlitterMat::
	.string "The visitor stepped on\n"
	.string "a GLITTER MAT!\p"
	.string "The visitor is striking a variety\n"
	.string "of poses!\p"
	.string "The visitor appears to be fantasizing\n"
	.string "about being an idol!$"

TVSecretBaseSecrets_Text_UsedTire::
	.string "The visitor is staring intently\n"
	.string "at a TIRE!\p"
	.string "Could the visitor be thinking about\n"
	.string "the kind of car that would use it?$"

TVSecretBaseSecrets_Text_UsedStand::
	.string "The visitor climbed a STAND!\p"
	.string "The visitor is looking out across\n"
	.string "{STR_VAR_1}'s BASE from high up!\p"
	.string "And…\p"
	.string "Lets loose a roar!\n"
	.string "The visitor is roaring!$"

TVSecretBaseSecrets_Text_BrokeDoor::
	.string "The visitor charged headlong into\n"
	.string "a BREAKABLE DOOR!\p"
	.string "The visitor is laughing uproariously!$"

TVSecretBaseSecrets_Text_UsedDoll::
	.string "The visitor is talking to a DOLL!\p"
	.string "…It's a little creepy…$"

TVSecretBaseSecrets_Text_UsedSlide::
	.string "The visitor is climbing the ladder\n"
	.string "on a SLIDE!\p"
	.string "And…\p"
	.string "The visitor slid down!\p"
	.string "Looks like the visitor is having\n"
	.string "a grand old time!$"

TVSecretBaseSecrets_Text_UsedSlideButDidntGoDown::
	.string "The visitor is climbing the ladder\n"
	.string "on a SLIDE!\p"
	.string "And…\p"
	.string "The visitor went back down\n"
	.string "the ladder!\p"
	.string "Did the visitor suddenly chicken out?$"

TVSecretBaseSecrets_Text_UsedJumpMat::
	.string "The visitor stepped on\n"
	.string "a JUMP MAT!\p"
	.string "The visitor jumped once!\p"
	.string "Jumped twice!\p"
	.string "And a successful landing!\p"
	.string "The visitor is clapping!\n"
	.string "What a solo performance!$"

gTVSafariFanClubText00::
	.string "SAFARI FAN CLUB!\p"
	.string "REPORTER: All right, mates!\n"
	.string "Tossing them SAFARI BALLS, are you?\p"
	.string "You can bet I am here in the SAFARI\n"
	.string "ZONE chock-full of amazing POKéMON!\p"
	.string "Let's get with it and have a chat with\n"
	.string "this good fellow of a SAFARI GUIDE!\p"
	.string "All right, mate, how are the visiting\n"
	.string "TRAINERS looking?$"

gTVSafariFanClubText01::
	.string "GUIDE: Everyone seems to be going\n"
	.string "hard at it.\p"
	.string "{STR_VAR_1} is doing especially well.\p"
	.string "Why, before, {STR_VAR_1} caught\n"
	.string "{STR_VAR_2} POKéMON.$"

gTVSafariFanClubText02::
	.string "The TRAINER is clever with {POKEBLOCK}S.\n"
	.string "Used {STR_VAR_2} that time, I think.$"

gTVSafariFanClubText03::
	.string "The TRAINER didn't use a single\n"
	.string "{POKEBLOCK}! Not a one!\p"
	.string "There's an expert for you.$"

gTVSafariFanClubText04::
	.string "REPORTER: Is that right, then?\p"
	.string "Sounds like our mate {STR_VAR_1}\n"
	.string "is a stout SAFARI master!\p"
	.string "GUIDE: I hope the TRAINER comes back\n"
	.string "and shows us that great technique.$"

gTVSafariFanClubText05::
	.string "GUIDE: No one seems to be doing\n"
	.string "very well.\p"
	.string "{STR_VAR_1} had it especially bad.\p"
	.string "Why, before, the TRAINER only\n"
	.string "managed to catch {STR_VAR_2} POKéMON.$"

gTVSafariFanClubText06::
	.string "GUIDE: No one seems to be doing\n"
	.string "very well.\p"
	.string "{STR_VAR_1} had it especially bad.\p"
	.string "Why, before, the TRAINER didn't\n"
	.string "catch one POKéMON. Not a one!$"

gTVSafariFanClubText07::
	.string "The TRAINER does use {POKEBLOCK}S.\n"
	.string "Used {STR_VAR_2} that time, I think.\p"
	.string "But, boy, I wish the TRAINER would\n"
	.string "get a bit better at this.$"

gTVSafariFanClubText08::
	.string "I think the TRAINER would have better\n"
	.string "luck using {POKEBLOCK}S, which weren't\l"
	.string "used at all that time.$"

gTVSafariFanClubText09::
	.string "REPORTER: Is that right, then?\p"
	.string "Sounds like our mate {STR_VAR_1}\n"
	.string "needs more SAFARI seasoning.\p"
	.string "GUIDE: I hope the TRAINER visits\n"
	.string "over and over to get the hang of it.$"

gTVSafariFanClubText10::
	.string "REPORTER: Quite right, it is!\n"
	.string "Facing up to challenges is important!\p"
	.string "Viewers, come on down to the SAFARI\n"
	.string "and make the challenge yourself!\p"
	.string "Until next time, cheerio!$"

ContestLiveUpdates_Text_Intro::
	.string "“POKéMON CONTEST LIVE UPDATES!”\p"
	.string "ZM: Thanks for joining us!\p"
	.string "We're live from the just-ended\n"
	.string "{STR_VAR_1} site.\p"
	.string "The hall is still filled with\n"
	.string "an audience unwilling to leave.\p"
	.string "Spectator: {STR_VAR_2}!\p"
	.string "Spectator: {STR_VAR_3}!\p"
	.string "ZM: As you've just heard, the CONTEST\n"
	.string "was won by the POKéMON {STR_VAR_2}\l"
	.string "of {STR_VAR_3}.\p"
	.string "Spectator: {STR_VAR_2}!\n"
	.string "You're the best!\p"
	.string "Spectator: {STR_VAR_3}!\n"
	.string "Way to go!\p"
	.string "ZM: Let's hear what the fans have\n"
	.string "to say about this CONTEST.$"

ContestLiveUpdates_Text_WonBothRounds::
	.string "Spectator: The {STR_VAR_2} was tops in\n"
	.string "both primary and secondary judging!\p"
	.string "That {STR_VAR_2} will keep winning!$"

ContestLiveUpdates_Text_BetterRound2::
	.string "Spectator: The {STR_VAR_2} didn't do\n"
	.string "well in the primary judging, but it\l"
	.string "cleaned up in the secondary judging!\p"
	.string "It was a miraculous comeback\n"
	.string "for that {STR_VAR_2}. Yippee!$"

ContestLiveUpdates_Text_EqualRounds::
	.string "Spectator: The {STR_VAR_2} remained\n"
	.string "consistent throughout both primary\l"
	.string "and secondary judging.\p"
	.string "{STR_VAR_3} and the {STR_VAR_2},\n"
	.string "they're no ordinary combo!$"

ContestLiveUpdates_Text_BetterRound1::
	.string "Spectator: In terms of being {STR_VAR_1},\n"
	.string "that {STR_VAR_2} was outstanding.\p"
	.string "I hope it makes better appeals\n"
	.string "next time, though.$"

ContestLiveUpdates_Text_GotNervous::
	.string "Spectator: When the {STR_VAR_2} got\n"
	.string "nervous, I couldn't stop myself from\l"
	.string "shouting encouragement.\p"
	.string "I'd like to say this to that\n"
	.string "{STR_VAR_2}, “Congratulations!”$"

ContestLiveUpdates_Text_StartledFoes::
	.string "Spectator: That {STR_VAR_2}'s appeal\n"
	.string "startled even me!\p"
	.string "{STR_VAR_2}, you were awesome!$"

ContestLiveUpdates_Text_UsedCombo::
	.string "Spectator: That {STR_VAR_2}'s combo\n"
	.string "appeal was stunning!\p"
	.string "It's shaken me to the core!$"

ContestLiveUpdates_Text_ExcitingAppeal::
	.string "Spectator: The winning {STR_VAR_2}'s\n"
	.string "appeal got my heart pounding!$"

ContestLiveUpdates_Text_WasCool::
	.string "{STR_VAR_2}!\n"
	.string "You were cool!$"

ContestLiveUpdates_Text_WasBeautiful::
	.string "{STR_VAR_2}!\n"
	.string "You were beautiful!$"

ContestLiveUpdates_Text_WasCute::
	.string "{STR_VAR_2}!\n"
	.string "You were cute!$"

ContestLiveUpdates_Text_WasSmart::
	.string "{STR_VAR_2}!\n"
	.string "You were smart!$"

ContestLiveUpdates_Text_WasTough::
	.string "{STR_VAR_2}!\n"
	.string "You were tough!$"

ContestLiveUpdates_Text_VeryExcitingAppeal::
	.string "Spectator: The winning {STR_VAR_2}'s\n"
	.string "appeal still has my heart pounding!$"

ContestLiveUpdates_Text_VeryCool::
	.string "{STR_VAR_2}!\n"
	.string "You're the last word in cool!$"

ContestLiveUpdates_Text_VeryBeautiful::
	.string "{STR_VAR_2}!\n"
	.string "You're the most beautiful!$"

ContestLiveUpdates_Text_VeryCute::
	.string "{STR_VAR_2}!\n"
	.string "You're simply the cutest!$"

ContestLiveUpdates_Text_VerySmart::
	.string "{STR_VAR_2}!\n"
	.string "You're the smartest among the smart!$"

ContestLiveUpdates_Text_VeryTough::
	.string "{STR_VAR_2}!\n"
	.string "You're the toughest of the tough!$"

ContestLiveUpdates_Text_TookBreak::
	.string "Spectator: Even when the {STR_VAR_2}\n"
	.string "took a break from making appeals,\l"
	.string "I couldn't take my eyes off it.\p"
	.string "I'm captivated by that {STR_VAR_2}.$"

ContestLiveUpdates_Text_GotStartled::
	.string "Spectator: When the {STR_VAR_2} was\n"
	.string "startled by another POKéMON's appeal,\l"
	.string "I was close to tears.\p"
	.string "{STR_VAR_2}, you were resilient!\n"
	.string "Way to go!$"

ContestLiveUpdates_Text_MoveWonderful::
	.string "Spectator: Oh…\n"
	.string "That {STR_VAR_2}'s {STR_VAR_3}!\l"
	.string "{STR_VAR_2}'s {STR_VAR_3}!\l"
	.string "{STR_VAR_2}'s {STR_VAR_3}!\l"
	.string "How could it be so wonderful?$"

ContestLiveUpdates_Text_TalkAboutAnotherMon::
	.string "ZM: Well, there you have it. This place\n"
	.string "is full of the {STR_VAR_1}'s fans!\p"
	.string "I should also mention that another\n"
	.string "POKéMON, {STR_VAR_2}'s {STR_VAR_3}, \l"
	.string "caught my eye.\p"
	.string "{STR_VAR_2}'s {STR_VAR_3}…$"

ContestLiveUpdates_Text_FailedToAppeal::
	.string "It failed to make a single appeal during\n"
	.string "secondary judging out of nervousness.\p"
	.string "Next time, I would like to see this\n"
	.string "{STR_VAR_1} make even one appeal.$"

ContestLiveUpdates_Text_LastInBothRounds::
	.string "It came dead last in both primary\n"
	.string "and secondary judging.\p"
	.string "I hope that {STR_VAR_1} will retrain this\n"
	.string "{STR_VAR_2} and erase the shame of\l"
	.string "this undisputed last-place finish.$"

ContestLiveUpdates_Text_NotExcitingEnough::
	.string "It failed to take advantage of\n"
	.string "the audience's excitement and make\l"
	.string "an appropriate appeal.\p"
	.string "We hope {STR_VAR_1} will learn how to get\n"
	.string "a feel for the audience and whip their\l"
	.string "excitement to a fever pitch next time.$"

ContestLiveUpdates_Text_LostAfterWinningRound1::
	.string "While finishing first in the primary\n"
	.string "judging, its appeals in the secondary\l"
	.string "judging failed to click.\p"
	.string "It suffered a humiliating come-from-\n"
	.string "behind loss.\p"
	.string "I'm sure {STR_VAR_1} is studying how to\n"
	.string "make more effective appeals now.$"

ContestLiveUpdates_Text_NeverExciting::
	.string "The audience never got excited by its\n"
	.string "appeals during the secondary judging.\p"
	.string "We hope it will stop worrying about\n"
	.string "other POKéMON and learn to pitch\l"
	.string "its appeals to the audience more.$"

ContestLiveUpdates_Text_LostBySmallMargin::
	.string "It lost to {STR_VAR_1}'s {STR_VAR_2}\n"
	.string "by only a small margin.\p"
	.string "It must be heartbreaking to come\n"
	.string "so close to victory only to fail.\p"
	.string "I wouldn't be surprised if {STR_VAR_3}\n"
	.string "were weeping over this outcome.$"

ContestLiveUpdates_Text_RepeatedAppeals::
	.string "It disappointed the JUDGE by\n"
	.string "repeating the same appeals.\p"
	.string "It's an unforgivable error in any\n"
	.string "CONTEST, and the POKéMON paid.\p"
	.string "{STR_VAR_1} should feel guilty for\n"
	.string "this sorry showing.$"

ContestLiveUpdates_Text_ValiantEffortButLost::
	.string "{STR_VAR_1} turned in a valiant effort,\n"
	.string "but…\p"
	.string "It was all for naught, finishing last.\p"
	.string "{STR_VAR_1} should learn from this loss\n"
	.string "and put the knowledge to good use.$"

ContestLiveUpdates_Text_Outro::
	.string "I'd like to end this program with our\n"
	.string "usual farewell to the winners.\p"
	.string "This time, it's {STR_VAR_1} and\n"
	.string "the {STR_VAR_2}!\p"
	.string "ZM: Is everyone ready?\n"
	.string "All together now!\p"
	.string "Audience: {STR_VAR_1}! {STR_VAR_2}!\n"
	.string "Congratulations!\l"
	.string "You're the CONTEST winner!$"

gTVPokemonBattleUpdateText00::
	.string "“POKéMON BATTLE UPDATE!”\p"
	.string "Bringing you the results of POKéMON\n"
	.string "battles as they come in!$"

gTVPokemonBattleUpdateText01::
	.string "The TRAINERS {STR_VAR_1} and\n"
	.string "{STR_VAR_2} faced each other in\l"
	.string "a {STR_VAR_3} BATTLE.\p"
	.string "This match ended in victory for\n"
	.string "{STR_VAR_1}!$"

gTVPokemonBattleUpdateText02::
	.string "In the battle, {STR_VAR_1}'s\n"
	.string "{STR_VAR_2} was a formidable force\l"
	.string "using {STR_VAR_3}!$"

gTVPokemonBattleUpdateText03::
	.string "{STR_VAR_1}'s {STR_VAR_2} had a weak\n"
	.string "showing that really hurt.$"

gTVPokemonBattleUpdateText04::
	.string "Congratulations on your victory,\n"
	.string "{STR_VAR_1}!\p"
	.string "And for the defeated {STR_VAR_2},\n"
	.string "we hope for a better result next time!\p"
	.string "This concludes this episode of\n"
	.string "“POKéMON BATTLE UPDATE!”$"

gTVPokemonBattleUpdateText05::
	.string "The teams of TRAINERS {STR_VAR_1} and\n"
	.string "{STR_VAR_2} met in a MULTI BATTLE.\p"
	.string "This match ended in victory for\n"
	.string "{STR_VAR_1}'s team.$"

gTVPokemonBattleUpdateText06::
	.string "In the battle, the {STR_VAR_2} on\n"
	.string "{STR_VAR_1}'s team was a formidable\l"
	.string "force using {STR_VAR_3}.$"

gTVPokemonBattleUpdateText07::
	.string "The weak showing by the {STR_VAR_3}\n"
	.string "on {STR_VAR_2}'s team really hurt.\p"
	.string "Congratulations on your team's\n"
	.string "victory, {STR_VAR_1}!\p"
	.string "As for the defeated {STR_VAR_2}'s team,\n"
	.string "we hope for a better result next time!\p"
	.string "This concludes this episode of\n"
	.string "“POKéMON BATTLE UPDATE!”$"

GabbyAndTy_Text_GabbyPreFirstBattle:
	.string "GABBY: Oh! We've just spotted a tough-\n"
	.string "looking TRAINER here of all places!\p"
	.string "Okay, roll camera!\n"
	.string "Let's get this interview.$"

GabbyAndTy_Text_GabbyIntro:
	.string "GABBY: Oh! You're {PLAYER}! Hi!\n"
	.string "Do you remember us from last time?\p"
	.string "Can you show us how much stronger\n"
	.string "you've become? Okay, cue interview!$"

GabbyAndTy_Text_GabbyDefeatFirstTime:
	.string "GABBY: My eyes didn't lie!\n"
	.string "I did discover an astonishing TRAINER!$"

GabbyAndTy_Text_WhoAreYouInterview:
	.string "GABBY: Awesome! Awesome!\n"
	.string "Who are you?!\p"
	.string "I knew we were onto something wild\n"
	.string "when we spotted you!\p"
	.string "Oh, please let me explain. We travel\n"
	.string "around everywhere interviewing all\l"
	.string "sorts of TRAINERS.\p"
	.string "So, would you give us a bit of your time\n"
	.string "for an interview?$"

GabbyAndTy_Text_QuoteFromLastInterview:
	.string "GABBY: “{STR_VAR_1}!”\p"
	.string "Remember? That's the quote you gave\n"
	.string "us as the battle clincher last time.\p"
	.string "I never, ever forget stuff like that!$"

GabbyAndTy_Text_YouStompedUsInterviewAgain:
	.string "The last time we battled, you stomped\n"
	.string "us before we could brace ourselves…\p"
	.string "Anyway, what do you think?\n"
	.string "Do you want to be interviewed again?$"

GabbyAndTy_Text_YouThrewABallAtUsInterviewAgain:
	.string "The last time we battled, didn't you\n"
	.string "throw a POKé BALL at us?\p"
	.string "We were shocked! So we told everyone,\n"
	.string "just everyone, about it!\p"
	.string "Anyway, what do you think?\n"
	.string "Do you want to be interviewed again?$"

GabbyAndTy_Text_CleverItemSkillsInterviewAgain:
	.string "The last time we battled, your item\n"
	.string "skills cleverly did us in.\p"
	.string "Anyway, what do you think?\n"
	.string "Do you want to be interviewed again?$"

GabbyAndTy_Text_WeLookedRespectableInterviewAgain:
	.string "The last time we battled, we managed\n"
	.string "to look respectable.\p"
	.string "Anyway, what do you think?\n"
	.string "Do you want to be interviewed again?$"

GabbyAndTy_Text_InterviewAgain:
	.string "Anyway, what do you think?\n"
	.string "Do you want to be interviewed again?$"

GabbyAndTy_Text_DescribeYourFeelings:
	.string "You will?\n"
	.string "Thank you!\p"
	.string "Okay, I need you to describe your\n"
	.string "feelings about our battle, but it\l"
	.string "has to be short and sweet. Go!$"

GabbyAndTy_Text_PerfectWellBeSeeingYou:
	.string "GABBY: Mmm, yeah!\n"
	.string "That's the perfect clincher!\p"
	.string "I get the feeling that this will make\n"
	.string "a great TV show.\p"
	.string "There's a chance that they'll air this\n"
	.string "on TV, so make sure to look for us!\p"
	.string "Okay!\n"
	.string "We'll be seeing you!$"

GabbyAndTy_Text_DontGiveUpKeepingEyeOut:
	.string "GABBY: Oh…\p"
	.string "Okay, but don't give up!\n"
	.string "We'll be keeping an eye out for you!$"

GabbyAndTy_Text_KeepingAnEyeOutForYou:
	.string "GABBY: We'll be keeping an eye out\n"
	.string "for you!$"

GabbyAndTy_Text_GabbyNotEnoughMons:
	.string "GABBY: Is there a strong TRAINER\n"
	.string "anywhere with a lot of POKéMON?$"

GabbyAndTy_Text_GiveUsAnInterviewThisTime:
	.string "GABBY: Wow, you are something!\p"
	.string "You've gotten a lot stronger--a lot--\n"
	.string "since we last battled.\p"
	.string "We were right about you when we\n"
	.string "spotted you as a hot TRAINER.\p"
	.string "So, anyway, what do you think?\n"
	.string "Are you willing to give us an interview\l"
	.string "this time?$"

GabbyAndTy_Text_GabbyDefeat:
	.string "GABBY: That was an intense battle!\n"
	.string "Did you get all that on camera?$"

GabbyAndTy_Text_TyPreFirstBattle:
	.string "TY: Hey, lookie here! A tough-looking\n"
	.string "TRAINER here, of all places!\l"
	.string "Camera's rolling!$"

GabbyAndTy_Text_TyIntro:
	.string "TY: Hey, lookie here!\n"
	.string "I remember you!\p"
	.string "I'll get this battle all on this\n"
	.string "here camera!$"

GabbyAndTy_Text_TyPostBattle:
	.string "TY: You're a natural!\n"
	.string "Got me some prime footage right here!$"

GabbyAndTy_Text_TyNotEnoughMons:
	.string "TY: Do you only have the one POKéMON\n"
	.string "and that's it?\p"
	.string "If you had more POKéMON, it'd make for\n"
	.string "better footage, but…$"

GabbyAndTy_Text_TyDefeatFirstTime:
	.string "TY: Yep, we sure spotted a hot TRAINER.\n"
	.string "This is a huge scoop for us!$"

GabbyAndTy_Text_TyDefeat:
	.string "TY: Yep, I got it all.\n"
	.string "That whole battle's on camera.$"

gTVInSearchOfTrainersText00::
	.string "IN SEARCH OF TRAINERS…\p"
	.string "GABBY: Hi! Today I'm visiting an area\n"
	.string "near {STR_VAR_1}.\p"
	.string "We're trying to spot some up-and-\n"
	.string "coming new talent in the field.\p"
	.string "Today, we turned our lens on the\n"
	.string "TRAINER {PLAYER}.\p"
	.string "There's something about this TRAINER\n"
	.string "that piqued our interest.$"

gTVInSearchOfTrainersText01::
	.string "We've battled {PLAYER} before, but we\n"
	.string "can attest that the TRAINER has most\l"
	.string "definitely improved from before.\p"
	.string "I knew we were onto someone special\n"
	.string "when we spotted this TRAINER!$"

gTVInSearchOfTrainersText02::
	.string "The best way to determine how strong\n"
	.string "a TRAINER is…\p"
	.string "Well, the fastest way is to battle.\n"
	.string "And so we began our investigation!\p"
	.string "… …\p"
	.string "That's how we ended up in battle\n"
	.string "with {PLAYER}.\p"
	.string "In a dominating performance, we were\n"
	.string "flattened, rolled up, and tossed aside!\p"
	.string "{PLAYER} is ruthlessly strong…\p"
	.string "Here's our impressions after having\n"
	.string "battled our featured TRAINER.$"

gTVInSearchOfTrainersText03::
	.string "The combination of {STR_VAR_1} and\n"
	.string "{STR_VAR_3} was divine!\p"
	.string "The sight of them--{STR_VAR_1} and\n"
	.string "{STR_VAR_3}--selflessly supporting\l"
	.string "each other in the thick of battle…\p"
	.string "It was a marvelous sight to behold!\p"
	.string "{STR_VAR_2} was the move the TRAINER\n"
	.string "used last in our battle.\p"
	.string "The move {STR_VAR_2} is {STR_VAR_1}\n"
	.string "and {STR_VAR_3}'s sign of friendship!$"

gTVInSearchOfTrainersText04::
	.string "…I lost confidence in myself as\n"
	.string "a result of our encounter.\p"
	.string "We were beaten before we could launch\n"
	.string "a single attack.\l"
	.string "Ohhh… Snivel…\p"
	.string "In spite of that, {PLAYER}'s battles\n"
	.string "are worth seeing.\p"
	.string "I recommend confident TRAINERS to\n"
	.string "challenge {PLAYER}.$"

gTVInSearchOfTrainersText05::
	.string "There's only one thing to be said.\n"
	.string "Don't you dare throw a POKé BALL during\l"
	.string "a TRAINER battle!\p"
	.string "{PLAYER} is certainly strong, but has\n"
	.string "no clue about the basic rules.\p"
	.string "To our TV audience, I have a request.\p"
	.string "If you see {PLAYER}, please caution\n"
	.string "the TRAINER!$"

gTVInSearchOfTrainersText06::
	.string "{PLAYER} is adept at reading the\n"
	.string "opponent's actions.\p"
	.string "The timing of item usage was remarkably\n"
	.string "effective!$"

gTVInSearchOfTrainersText07::
	.string "Honestly speaking, I thought that\n"
	.string "I might even be pretty good.\p"
	.string "While we did end up losing, we did have\n"
	.string "a hotly contested battle.\p"
	.string "But if you're struggling against me,\n"
	.string "you have a ways to go, {PLAYER}!$"

gTVInSearchOfTrainersText08::
	.string "After our battle, we asked {PLAYER} for\n"
	.string "a succinct summary.\p"
	.string "The TRAINER replied, “{STR_VAR_1}.”\p"
	.string "{PLAYER}'s POKéMON {STR_VAR_2} and\n"
	.string "{STR_VAR_3}…\l"
	.string "And “{STR_VAR_1}”…\p"
	.string "Mmm! That's deep! There's deep\n"
	.string "significance behind that quote!\p"
	.string "It's no surprise--a good TRAINER has\n"
	.string "good things to say.\p"
	.string "That's all for today!\n"
	.string "See you again on our next broadcast!$"

ContestLadyShow_Text_Intro::
	.string "“POKéMON CONTEST LIVE UPDATES!”\p"
	.string "ZM: Sorry to interrupt the regular\n"
	.string "programming, and thanks for joining us!\p"
	.string "We bring you this live from\n"
	.string "the scene of a just-completed\l"
	.string "{STR_VAR_1}!\p"
	.string "Spectators: ?!!!!\p"
	.string "ZM: Oh! It looks like the CONTEST\n"
	.string "participants are headed this way!\p"
	.string "I'll try to get an impromptu interview\n"
	.string "for you folks at home!\p"
	.string "Spectators: ?!!!!\n"
	.string "?!!!!$"

ContestLadyShow_Text_Won::
	.string "ZM: Excuse me!\n"
	.string "Thanks for joining us on live TV!\p"
	.string "May I congratulate you on your win?\p"
	.string "What was the key factor in today's\n"
	.string "stunning victory?\p"
	.string "BEAUTY: We gave it our best effort\n"
	.string "today, my {STR_VAR_2} and I!\p"
	.string "But I'm sure we wouldn't have made it\n"
	.string "if it weren't for all the help we\l"
	.string "received leading up to the CONTEST!\p"
	.string "ZM: Do you have a special someone\n"
	.string "with whom you'd like to share your joy?\l"
	.string "Let's hear it live!\p"
	.string "BEAUTY: Hey, out there!\p"
	.string "{STR_VAR_3}! Are you watching?\n"
	.string "We did it!\l"
	.string "Thank you!$"

ContestLadyShow_Text_Lost::
	.string "ZM: Excuse me!\n"
	.string "Thanks for joining us on live TV!\p"
	.string "You must be disappointed by that turn\n"
	.string "of events. Do you have any comments?\p"
	.string "BEAUTY: It's heartbreaking…\n"
	.string "My {STR_VAR_2} and I, we did our best…\p"
	.string "But I feel like I've let down everyone\n"
	.string "who has supported us through this.\p"
	.string "ZM: I hate to say it, but the POKéMON's\n"
	.string "coloration is a little wanting.\p"
	.string "BEAUTY: {STR_VAR_3}, I'm so sorry…\n"
	.string "I'll do better next time, I swear…\l"
	.string "…Sniff… Waaaaah!\p"
	.string "Spectators: See that?\n"
	.string "The poor girl!\p"
	.string "ZM: Uh… Uh-oh…\p"
	.string "Uh… That's all the time we have today!\n"
	.string "Thanks for tuning in!$"

ContestLadyShow_Text_LostBadly::
	.string "ZM: Excuse me!\n"
	.string "Thanks for joining us on live TV!\p"
	.string "How did your CONTEST appearance go?\p"
	.string "BEAUTY: Nothing went right…\n"
	.string "For some reason, my {STR_VAR_2}\l"
	.string "couldn't attract any popularity.\p"
	.string "ZM: I hate to say it, but the POKéMON's\n"
	.string "coloration is a little wanting.\p"
	.string "BEAUTY: … … … … … …\n"
	.string "…Sniff… Waaaaah!\p"
	.string "Spectators: See that?\n"
	.string "The poor girl!\p"
	.string "ZM: Uh… Uh-oh…\p"
	.string "Uh… That's all the time we have today!\n"
	.string "Thanks for tuning in!$"
