VerdanturfTown_House_MapScripts::
	.byte 0

VerdanturfTown_House_EventScript_Woman1::
	msgbox VerdanturfTown_House_Text_TrainersGatherAtPokemonLeague, MSGBOX_NPC
	end

VerdanturfTown_House_EventScript_Woman2::
	msgbox VerdanturfTown_House_Text_DefeatEliteFourInARow, MSGBOX_NPC
	end

VerdanturfTown_House_Text_TrainersGatherAtPokemonLeague:
	.string "Hemendik urrun, ITZELETA HIRIAN,\n"
	.string "POKéMON LIGA dago.\p"
	.string "Bertan biltzen diren ENTRENATZAILEAK\n"
	.string "izugarri trebeak dira.$"

VerdanturfTown_House_Text_DefeatEliteFourInARow:
	.string "POKéMON LIGAN, esango nuke arauen\n"
	.string "arabera ELITE LAUKOTEAREN aurka\l"
	.string "borrokatu behar duzula, jarraian.\p"
	.string "Edozein borroka galduta, berriro\n"
	.string "hasi behar duzu erronka lehenengo\l"
	.string "borrokatik.$"

