SootopolisCity_House7_MapScripts::
	.byte 0

SootopolisCity_House7_EventScript_OldMan::
	msgbox SootopolisCity_House7_Text_CityFromEruptedVolcano, MSGBOX_NPC
	end

SootopolisCity_House7_EventScript_PokefanF::
	msgbox SootopolisCity_House7_Text_CaveMadeToKeepSomething, MSGBOX_NPC
	end

SootopolisCity_House7_Text_CityFromEruptedVolcano:
	.string "Ur azpiko sumendi batek eztanda\n"
	.string "egin eta ur azpitik atera zen.\p"
	.string "Kraterra itsas azaletik atera eta\n"
	.string "euri urez bete zen.\p"
	.string "Horrela eratu zen ARREZIPOLISEKO\n"
	.string "HIRIA.$"

SootopolisCity_House7_Text_CaveMadeToKeepSomething:
	.string "ARREZIPOLIS eta kanpoko mundua\n"
	.string "lotzen dituen ur azpiko haitzuloa…\p"
	.string "Badirudi zeozerri barruan eusteko\n"
	.string "sortu zela haitzuloa.\p"
	.string "Edo nire imajinazioa soilik ote da?$"

