OldaleTown_House1_MapScripts::
	.byte 0

OldaleTown_House1_EventScript_Woman::
	msgbox OldaleTown_House1_Text_LeftPokemonGoesOutFirst, MSGBOX_NPC
	end

OldaleTown_House1_Text_LeftPokemonGoesOutFirst:
	.string "POKéMON borroka bat hasten denean,\n"
	.string "zerrendako ezkerrekoa hasten da.\p"
	.string "Beraz, POKéMON gehiago biltzen\n"
	.string "dituzunean zure talderako, probatu zure\l"
	.string "POKéMONEN ordena aldatzen.\p"
	.string "Abantaila eman diezazuke eta.$"

