@ Note: local IDs shared with scripts.inc for LilycoveCity_ContestLobby
.set LOCALID_MAN, 3
.set LOCALID_BOY, 9
.set LOCALID_TWIN, 10
.set LOCALID_POKEFAN_F, 15
.set LOCALID_EXPERT_M, 16
.set LOCALID_GIRL, 17

.set NUM_OPPONENTS, VAR_0x8009

BerryBlender_Text_WantToMakePokeblocks:
	.string "Zer? {POKEBLOCK} batzuk egin nahi\n"
	.string "al zenituen zahartxo honekin?$"

BerryBlender_Text_Excellent:
	.string "Bikain!$"

BerryBlender_Text_MadeOldTimerSad:
	.string "Beno…\n"
	.string "Tristetu egin duzu zahartxo hau…$"

BerryBlender_Text_KnowHowToMakePokeblocks:
	.string "Badakizu nola egni {POKEBLOCK} bat?$"

BerryBlender_Text_LetsBerryBlender:
	.string "has gaitezen, orduan!\p"
	.string "BIRRINDU ditzagun BAIAK!$"

BerryBlender_Text_ExplainBerryBlending:
	.string "Ongi, azaldu egingo dizut, beraz.\p"
	.string "Ez kezaktu, nahikoa erraza da.\p"
	.string "BIRRINTZAILEAREN gezia zure markan\n"
	.string "dagoenean, sakatu A botoia.\p"
	.string "Horixe besterik ez duzu egin behar.\n"
	.string "Probatu, ikusiko duzu zeinen erraza den.$"

BerryBlender_Text_DontHaveAnyBerries:
	.string "Nola?\n"
	.string "Ez al daukazu BAIARIK?\p"
	.string "BAIARIK gabe, ezin duzu,\n"
	.string "{POKEBLOCK}IK egin.$"

BerryBlender_Text_CanHaveOneOfMyBerries:
	.string "Beno, horrela ezin da, ezta?\p"
	.string "Nire BAIA bat emango dizut, gaizki\n"
	.string "iruditzen ez bazaizu.\p"
	.string "Horrela, {POKEBLOCK}AK egin ditzakegu\n"
	.string "batera, BAIA BIRRINTZAILEAREKIN.$"

BerryBlender_Text_DontHaveAnyBerriesToSpare:
	.string "BAIAREN bat soberan banu,\n"
	.string "gustora emango nizuke…\p"
	.string "Baina, gaur ez dut bat bera ere.\n"
	.string "Beste batean egin beharko dugu.$"

BerryBlender_Text_PokeblockCaseIsFull:
	.string "Baina {POKEBLOCK} KUTXA betea dago.\p"
	.string "Erabili {POKEBLOCK} batzuk nigana\n"
	.string "berriro etorri aurretik.$"

BerryBlender_Text_DontHavePokeblockCase:
	.string "Baina ez duzu {POKEBLOCK} KUTXARIK.\p"
	.string "Lortu {POKEBLOCK} KUTXA bat eta\n"
	.string "etorri nigana.$"

BerryBlender_Text_LetsGetBlendingAlready:
	.string "Has gaitezen birrintzen!$"

BerryBlender_Text_WhatKindOfPokeblockWillIGet:
	.string "Ze motatako {POKEBLOCK}A lortuko ote dut?\n"
	.string "Hau zirraragarria da!$"

BerryBlender_Text_WantToBlendPokeblocksWithUs:
	.string "Kaixo! Nahi dituzu gurekin\n"
	.string "{POKEBLOCK}AK egin?$"

BerryBlender_Text_Okay:
	.string "Ongi!$"

BerryBlender_Text_ThatsTooBad:
	.string "Beno, ba…\p"
	.string "Hemendik ibiliko gara, baiak\n"
	.string "birrindu nahi badituzu!$"

BerryBlender_Text_KnowHowToMakePokeblocks2:
	.string "Noski, badakizu {POKEBLOCK}AK\n"
	.string "birrintzen, ezta?$"

BerryBlender_Text_LetsBerryBlender2:
	.string "Has gaitezen, orduan!\p"
	.string "BIRRINDU ditzagun BAIAK!$"

BerryBlender_Text_ExplainBerryBlending2:
	.string "Ongi!\n"
	.string "Nik azalduko dizut!\p"
	.string "BIRRINTZAILEAREN gezia zure\n"
	.string "markan dagoenean, sakatu\l"
	.string "A Botoia.\p"
	.string "Horixe besterik ez duzu egin behar.\n"
	.string "Nahiko erraza, ezta?$"

BerryBlender_Text_DontHaveAnyBerries2:
	.string "Baina, itxaron segundu bat…\n"
	.string "Ez daukazu BAIARIK.\p"
	.string "Ezin da {POKEBLOCK}IK egin\n"
	.string "BAIARIK gabe…\p"
	.string "Hemen izango gara birrintzeko\n"
	.string "BAIAK lortzen badituzu.$"

BerryBlender_Text_PokeblockCaseIsFull2:
	.string "Baina, itxaron segundu bat…\n"
	.string "Zure {POKEBLOCK} KUTXA betea dago.\p"
	.string "Erabili {POKEBLOCK} batzuk eta\n"
	.string "itzuli, atzera.$"

BerryBlender_Text_DontHavePokeblockCase2:
	.string "Baina, itxaron segundu bat…\n"
	.string "Ez daukazu {POKEBLOCK} KUTXARIK.\p"
	.string "Lortu {POKEBLOCK} KUTXA bat eta\n"
	.string "itzuli, atzera.$"

@ Unused
BerryBlender_Text_MakePokeblocksWithOurGroup:
	.string "Kaixo! Nahi al dituzu gure talde\n"
	.string "txikiarekin {POKEBLOCK}AK egin?$"

BerryBlender_Text_OhDear:
	.string "Ai, maitea!$"

BerryBlender_Text_LeftUsInShock:
	.string "Ai, maitea…\p"
	.string "Txundituta utzi gaituzu!$"

BerryBlender_Text_KnowHowToMakePokeblocks3:
	.string "Noski, badakizu {POKEBLOCK}AK\n"
	.string "egiten, ezta?$"

BerryBlender_Text_LetsBerryBlender3:
	.string "Ados, bada!\n"
	.string "Has gaitezen!\p"
	.string "BIRRINDU ditzagun BAIAK!$"

BerryBlender_Text_ExplainBerryBlending3:
	.string "Ai, maitea!\p"
	.string "Lasai, nik azalduko dizut.\p"
	.string "BIRRINTZAILEAREN gezia zure markan\n"
	.string "dagoenean, sakatu A Botoia.\p"
	.string "Horixe egin behar da, besterik ez.\n"
	.string "Erraza, ezta?$"

BerryBlender_Text_DontHaveAnyBerries3:
	.string "Ez daukazu BAIARIK, ez\n"
	.string "da hala?\p"
	.string "BAIARIK ez baduzu, ezin duzu\n"
	.string "{POKEBLOCK}IK egin.\p"
	.string "Beti egon ohi gara {POKEBLOCK}AK\n"
	.string "egiten, beraz, egingo ditugu BAIA\l"
	.string "pare bat lortzen dituzunean.$"

BerryBlender_Text_PokeblockCaseIsFull3:
	.string "Zure {POKEBLOCK} KUTXA betea dago,\n"
	.string "dirudienez.\p"
	.string "{POKEBLOCK} batzuk erabili ondoren\n"
	.string "itzuli behar zenuke.$"

BerryBlender_Text_DontHavePokeblockCase3:
	.string "Ez duzu {POKEBLOCK} KUTXARIK\n"
	.string "oraindik, dirudienez.\p"
	.string "{POKEBLOCK} KUTXA bat beharko\n"
	.string "duzu lehenengo.$"

BerryBlender_Text_SetNewBlenderRecord:
	.string "Ongi! Gaur da eguna BIRRINTZAILEAREKIN\n"
	.string "abiadura errekor berria egiteko!$"

BerryBlender_Text_LookGoodAtBlendingJoinUs:
	.string "Ai, maitea!\n"
	.string "Birrintzen ona zarela dirudi.\l"
	.string "Nahi duzu gugana batu?$"

BerryBlender_Text_MakeDeliciousPokeblocks:
	.string "{POKEBLOCK} gozo-gozoak egingo ditut,\n"
	.string "nire POKéMONA politagoa izateko.$"

BerryBlender_Text_SaveGameBeforeBerryBlenderLink:
	.string "{POKEBLOCK}AK egingo dituzu zure lagunekin\n"
	.string "BIRRINTZAILEAN, BAIAK erabilita.\p"
	.string "Gorde nahi al duzu partida zure\n"
	.string "lagunekin konektatu aurretik?$"

BerryBlender_Text_SearchingForFriends:
	.string "Zure lagunak bilatzen…\n"
	.string "… … B Botoia: Ezeztatu$"

BerryBlender_Text_Player1Arrived:
	.string "{STR_VAR_1} iritsi da.$"

BerryBlender_Text_Player1And2Arrived:
	.string "{STR_VAR_1} eta {STR_VAR_2} iritsi dira.$"

BerryBlender_Text_AllPlayersArrived:
	.string "{STR_VAR_1}, {STR_VAR_2}, eta\n"
	.string "{STR_VAR_3} iritsi dira.$"

BerryBlender_Text_NoBerriesLink:
	.string "Ez duzu BAIARIK.\n"
	.string "Ezin duzu BAIA BIRRINTZAILEA erabili.$"

BerryBlender_Text_PokeblockCaseIsFullLink:
	.string "Zure {POKEBLOCK} KUTXA betea dago.\n"
	.string "Ezin duzu BAIA BIRRINTZAILEA erabili.$"

BerryBlender_Text_DontHavePokeblockCaseLink:
	.string "Ez duzu {POKEBLOCK} KUTXARIK.\n"
	.string "Ezin duzu BAIA BIRRINTZAILEA erabili.$"

BerryBlender_Text_LoveMakingPokeblocks:
	.string "Atsegin dut {POKEBLOCK}AK egitea.\p"
	.string "Beti dut BAIAREN bat aldean.$"

BerryBlender_Text_MakePokeblocksUsingBerryBlender:
	.string "Nahi baduzu, {POKEBLOCK} batzuk egin\n"
	.string "ditzakegu elkarrekin, BAIA\l"
	.string "BIRRINTZAILEA erabilita.$"

BerryBlender_Text_DontHaveAnyBerriesHaveOne:
	.string "Zer?\n"
	.string "Ez al duzu BAIARIK?\p"
	.string "Beno, orduan ezin da, ezta?\p"
	.string "BAIA bat emango dizut, ondo\n"
	.string "iruditzen bazaizu.$"

BerryBlender_Text_UseItToMakePokeblocksTogether:
	.string "Elkarrekin {POKEBLOCK}AK egiteko\n"
	.string "erabiliko dugu.$"

BerryBlender_Text_DontHaveAnyBerriesNoneToSpare:
	.string "Zer?\n"
	.string "Ez al duzu BAIARIK?\p"
	.string "BAIARIK izango banu, gustora\n"
	.string "emango nizuke bat, baina…\p"
	.string "Gaur ez zait bat ere geratzen.\n"
	.string "Sentitzen dut.$"

BerryBlender_EventScript_BerryBlender1::
	lockall
	goto_if_unset FLAG_HIDE_LILYCOVE_CONTEST_HALL_BLEND_MASTER, BerryBlender_EventScript_BlendMasterPresent
	setvar NUM_OPPONENTS, 1
	applymovement LOCALID_EXPERT_M, BerryBlender_Movement_BlendLeaderWalkInPlace
	waitmovement 0
	msgbox BerryBlender_Text_WantToMakePokeblocks, MSGBOX_YESNO
	goto_if_eq VAR_RESULT, YES, BerryBlender_EventScript_TryUseBerryBlender1
	goto BerryBlender_EventScript_DeclineBlender1
	end

BerryBlender_EventScript_DeclineBlender1:
	msgbox BerryBlender_Text_MadeOldTimerSad, MSGBOX_DEFAULT
	releaseall
	end

BerryBlender_EventScript_Blender1NoBerries:
	msgbox BerryBlender_Text_DontHaveAnyBerries, MSGBOX_DEFAULT
	dotimebasedevents
	goto_if_set FLAG_DAILY_CONTEST_LOBBY_RECEIVED_BERRY, BerryBlender_EventScript_Blender1NoSpareBerries
	goto BerryBlender_EventScript_Blender1GiveSpareBerry
	end

BerryBlender_EventScript_Blender1NoSpareBerries:
	msgbox BerryBlender_Text_DontHaveAnyBerriesToSpare, MSGBOX_DEFAULT
	releaseall
	end

BerryBlender_EventScript_Blender1GiveSpareBerry:
	msgbox BerryBlender_Text_CanHaveOneOfMyBerries, MSGBOX_DEFAULT
	giveitem ITEM_PECHA_BERRY
	setflag FLAG_DAILY_CONTEST_LOBBY_RECEIVED_BERRY
	goto BerryBlender_EventScript_UseBerryBlender1
	end

BerryBlender_EventScript_UseBerryBlender1:
	msgbox BerryBlender_Text_KnowHowToMakePokeblocks, MSGBOX_YESNO
	goto_if_eq VAR_RESULT, YES, BerryBlender_EventScript_StartBlender1
	goto BerryBlender_EventScript_ExplainBlending1
	end

BerryBlender_EventScript_StartBlender1:
	msgbox BerryBlender_Text_LetsBerryBlender, MSGBOX_DEFAULT
	goto BerryBlender_EventScript_DoBerryBlending
	end

BerryBlender_EventScript_ExplainBlending1:
	msgbox BerryBlender_Text_ExplainBerryBlending, MSGBOX_DEFAULT
	goto BerryBlender_EventScript_StartBlender1
	end

BerryBlender_EventScript_TryUseBerryBlender1:
	checkitem ITEM_POKEBLOCK_CASE
	goto_if_eq VAR_RESULT, FALSE, BerryBlender_EventScript_Blender1NoCase
	specialvar VAR_RESULT, GetFirstFreePokeblockSlot
	goto_if_eq VAR_RESULT, 65535, BerryBlender_EventScript_Blender1CaseFull
	specialvar VAR_RESULT, PlayerHasBerries
	goto_if_eq VAR_RESULT, FALSE, BerryBlender_EventScript_Blender1NoBerries
	msgbox BerryBlender_Text_Excellent, MSGBOX_DEFAULT
	goto BerryBlender_EventScript_UseBerryBlender1
	end

BerryBlender_EventScript_DoBerryBlending:
	copyvar VAR_0x8004, NUM_OPPONENTS
	fadescreen FADE_TO_BLACK
	special DoBerryBlending
	waitstate
	releaseall
	end

BerryBlender_EventScript_Blender1CaseFull:
	msgbox BerryBlender_Text_PokeblockCaseIsFull, MSGBOX_DEFAULT
	releaseall
	end

BerryBlender_EventScript_Blender1NoCase:
	msgbox BerryBlender_Text_DontHavePokeblockCase, MSGBOX_DEFAULT
	releaseall
	end

BerryBlender_EventScript_BerryBlender2::
	lockall
	setvar NUM_OPPONENTS, 2
	applymovement LOCALID_TWIN, Common_Movement_FaceOriginalDirection
	applymovement LOCALID_MAN, BerryBlender_Movement_BlendLeaderWalkInPlace
	waitmovement 0
	msgbox BerryBlender_Text_WantToBlendPokeblocksWithUs, MSGBOX_YESNO
	goto_if_eq VAR_RESULT, YES, BerryBlender_EventScript_TryUseBerryBlender2
	goto BerryBlender_EventScript_DeclineBlender2
	end

BerryBlender_EventScript_DeclineBlender2:
	msgbox BerryBlender_Text_ThatsTooBad, MSGBOX_DEFAULT
	releaseall
	end

BerryBlender_EventScript_Blender2NoBerries:
	msgbox BerryBlender_Text_DontHaveAnyBerries2, MSGBOX_DEFAULT
	release
	end

BerryBlender_EventScript_UseBerryBlender2:
	msgbox BerryBlender_Text_KnowHowToMakePokeblocks2, MSGBOX_YESNO
	goto_if_eq VAR_RESULT, YES, BerryBlender_EventScript_StartBlender2
	goto BerryBlender_EventScript_ExplainBlending2
	end

BerryBlender_EventScript_StartBlender2:
	msgbox BerryBlender_Text_LetsBerryBlender2, MSGBOX_DEFAULT
	goto BerryBlender_EventScript_DoBerryBlending
	end

BerryBlender_EventScript_ExplainBlending2:
	msgbox BerryBlender_Text_ExplainBerryBlending2, MSGBOX_DEFAULT
	goto BerryBlender_EventScript_StartBlender2
	end

BerryBlender_EventScript_TryUseBerryBlender2:
	specialvar VAR_RESULT, PlayerHasBerries
	goto_if_eq VAR_RESULT, FALSE, BerryBlender_EventScript_Blender2NoBerries
	checkitem ITEM_POKEBLOCK_CASE
	goto_if_eq VAR_RESULT, FALSE, BerryBlender_EventScript_Blender2NoCase
	msgbox BerryBlender_Text_Okay, MSGBOX_DEFAULT
	specialvar VAR_RESULT, GetFirstFreePokeblockSlot
	goto_if_ne VAR_RESULT, 65535, BerryBlender_EventScript_UseBerryBlender2
	goto_if_eq VAR_RESULT, 65535, BerryBlender_EventScript_Blender2CaseFull
	end

BerryBlender_EventScript_Blender2CaseFull:
	msgbox BerryBlender_Text_PokeblockCaseIsFull2, MSGBOX_DEFAULT
	releaseall
	end

BerryBlender_EventScript_Blender2NoCase:
	msgbox BerryBlender_Text_DontHavePokeblockCase2, MSGBOX_DEFAULT
	releaseall
	end

BerryBlender_EventScript_BerryBlender3::
	lockall
	setvar VAR_0x8008, LOCALID_POKEFAN_F
	setvar NUM_OPPONENTS, 3
	applymovement LOCALID_BOY, Common_Movement_FaceOriginalDirection
	applymovement LOCALID_GIRL, Common_Movement_FaceOriginalDirection
	applymovement VAR_0x8008, BerryBlender_Movement_BlendLeaderWalkInPlace
	waitmovement 0
	msgbox BerryBlender_Text_LookGoodAtBlendingJoinUs, MSGBOX_YESNO
	goto_if_eq VAR_RESULT, YES, BerryBlender_EventScript_TryUseBlender3
	goto BerryBlender_EventScript_DeclineBlender3
	end

BerryBlender_EventScript_DeclineBlender3:
	msgbox BerryBlender_Text_LeftUsInShock, MSGBOX_DEFAULT
	releaseall
	end

BerryBlender_EventScript_Blender3NoBerries:
	msgbox BerryBlender_Text_DontHaveAnyBerries3, MSGBOX_DEFAULT
	release
	end

BerryBlender_EventScript_UseBerryBlender3:
	msgbox BerryBlender_Text_KnowHowToMakePokeblocks3, MSGBOX_YESNO
	goto_if_eq VAR_RESULT, YES, BerryBlender_EventScript_StartBlender3
	goto BerryBlender_EventScript_ExplainBlending3
	end

BerryBlender_EventScript_StartBlender3:
	msgbox BerryBlender_Text_LetsBerryBlender3, MSGBOX_DEFAULT
	goto BerryBlender_EventScript_DoBerryBlending
	end

BerryBlender_EventScript_ExplainBlending3:
	msgbox BerryBlender_Text_ExplainBerryBlending3, MSGBOX_DEFAULT
	goto BerryBlender_EventScript_StartBlender3
	end

BerryBlender_EventScript_TryUseBlender3:
	specialvar VAR_RESULT, PlayerHasBerries
	goto_if_eq VAR_RESULT, FALSE, BerryBlender_EventScript_Blender3NoBerries
	checkitem ITEM_POKEBLOCK_CASE
	goto_if_eq VAR_RESULT, FALSE, BerryBlender_EventScript_Blender3NoCase
	msgbox BerryBlender_Text_OhDear, MSGBOX_DEFAULT
	specialvar VAR_RESULT, GetFirstFreePokeblockSlot
	goto_if_ne VAR_RESULT, 65535, BerryBlender_EventScript_UseBerryBlender3
	goto_if_eq VAR_RESULT, 65535, BerryBlender_EventScript_Blender3CaseFull
	end

BerryBlender_EventScript_Blender3CaseFull:
	msgbox BerryBlender_Text_PokeblockCaseIsFull3, MSGBOX_DEFAULT
	releaseall
	end

BerryBlender_EventScript_Blender3NoCase:
	msgbox BerryBlender_Text_DontHavePokeblockCase3, MSGBOX_DEFAULT
	releaseall
	end

BerryBlender_EventScript_BlendMasterPresent:
	lockall
	setvar NUM_OPPONENTS, 1
	msgbox BerryBlender_Text_SeeMyMasteryInAction, MSGBOX_YESNO
	goto_if_eq VAR_RESULT, YES, BerryBlender_EventScript_TryBlendWithBlendMaster
	msgbox BerryBlender_Text_TooBusyNowIsee, MSGBOX_DEFAULT
	releaseall
	end

BerryBlender_EventScript_BlendMasterNoBerries:
	msgbox BerryBlender_Text_BlendMasterNoBerries, MSGBOX_DEFAULT
	releaseall
	end

BerryBlender_EventScript_TryBlendWithBlendMaster:
	checkitem ITEM_POKEBLOCK_CASE
	goto_if_eq VAR_RESULT, FALSE, BerryBlender_EventScript_BlendMasterNoCase
	specialvar VAR_RESULT, PlayerHasBerries
	goto_if_eq VAR_RESULT, FALSE, BerryBlender_EventScript_BlendMasterNoBerries
	specialvar VAR_RESULT, GetFirstFreePokeblockSlot
	goto_if_ne VAR_RESULT, 65535, BerryBlender_EventScript_BlendWithBlendMaster
	goto_if_eq VAR_RESULT, 65535, BerryBlender_EventScript_BlendMasterCaseFull
	end

BerryBlender_EventScript_BlendWithBlendMaster:
	msgbox BerryBlender_Text_BlendMasterKnowHowToMakePokeblocks, MSGBOX_YESNO
	call_if_eq VAR_RESULT, NO, BerryBlender_EventScript_BlendMasterExplainBlending
	msgbox BerryBlender_Text_BlendMasterLetsBerryBlender, MSGBOX_DEFAULT
	goto BerryBlender_EventScript_DoBerryBlending
	end

BerryBlender_EventScript_BlendMasterExplainBlending:
	msgbox BerryBlender_Text_BlendMasterExplainBerryBlending, MSGBOX_DEFAULT
	return

BerryBlender_EventScript_BlendMasterNoCase:
	msgbox BerryBlender_Text_BlendMasterNoPokeblockCase, MSGBOX_DEFAULT
	releaseall
	end

BerryBlender_EventScript_BlendMasterCaseFull:
	msgbox BerryBlender_Text_BlendMasterPokeblockCaseFull, MSGBOX_DEFAULT
	releaseall
	end

BerryBlender_EventScript_Blender2Man::
	msgbox BerryBlender_Text_SetNewBlenderRecord, MSGBOX_NPC
	end

BerryBlender_EventScript_Blender3PokefanF::
	msgbox BerryBlender_Text_LookGoodAtBlendingJoinUs, MSGBOX_NPC
	end

BerryBlender_EventScript_Blender2Twin::
	msgbox BerryBlender_Text_MakeDeliciousPokeblocks, MSGBOX_NPC
	end

BerryBlender_EventScript_Blender1ExpertM::
	setvar VAR_0x8008, 15
	goto BerryBlender_EventScript_ExpertMCheckGiveBerry
	end

BerryBlender_EventScript_ExpertMCheckGiveBerry:
	lock
	faceplayer
	msgbox BerryBlender_Text_LoveMakingPokeblocks, MSGBOX_DEFAULT
	specialvar VAR_RESULT, PlayerHasBerries
	goto_if_eq VAR_RESULT, TRUE, BerryBlender_EventScript_ExpertMPlayerHasBerries
	goto_if_eq VAR_RESULT, FALSE, BerryBlender_EventScript_ExpertMNoBerries
	end

BerryBlender_EventScript_ExpertMPlayerHasBerries:
	msgbox BerryBlender_Text_MakePokeblocksUsingBerryBlender, MSGBOX_DEFAULT
	release
	end

BerryBlender_EventScript_ExpertMNoBerries:
	checkitem ITEM_POKEBLOCK_CASE
	goto_if_eq VAR_RESULT, FALSE, BerryBlender_EventScript_ExpertMNoSpareBerries
	specialvar VAR_RESULT, GetFirstFreePokeblockSlot
	goto_if_eq VAR_RESULT, 65535, BerryBlender_EventScript_ExpertMNoSpareBerries
	dotimebasedevents
	goto_if_set FLAG_DAILY_CONTEST_LOBBY_RECEIVED_BERRY, BerryBlender_EventScript_ExpertMNoSpareBerries
	goto BerryBlender_EventScript_ExpertMGiveBerry
	end

BerryBlender_EventScript_ExpertMNoSpareBerries:
	msgbox BerryBlender_Text_DontHaveAnyBerriesNoneToSpare, MSGBOX_DEFAULT
	release
	end

BerryBlender_EventScript_ExpertMGiveBerry:
	msgbox BerryBlender_Text_DontHaveAnyBerriesHaveOne, MSGBOX_DEFAULT
	giveitem ITEM_PECHA_BERRY
	setflag FLAG_DAILY_CONTEST_LOBBY_RECEIVED_BERRY
	msgbox BerryBlender_Text_UseItToMakePokeblocksTogether, MSGBOX_DEFAULT
	release
	end

BerryBlender_Movement_BlendLeaderWalkInPlace:
	walk_in_place_faster_right
	step_end

BerryBlender_EventScript_BerryBlenderLink::
	lockall
	specialvar VAR_RESULT, PlayerHasBerries
	goto_if_eq VAR_RESULT, FALSE, BerryBlender_EventScript_LinkBlenderNoBerries
	checkitem ITEM_POKEBLOCK_CASE
	goto_if_eq VAR_RESULT, FALSE, BerryBlender_EventScript_LinkBlenderNoCase
	specialvar VAR_RESULT, GetFirstFreePokeblockSlot
	goto_if_ne VAR_RESULT, 65535, BerryBlender_EventScript_LinkBlenderSaveGame
	goto_if_eq VAR_RESULT, 65535, BerryBlender_EventScript_LinkBlenderCaseFull
	end

BerryBlender_EventScript_LinkBlenderSaveGame:
	msgbox BerryBlender_Text_SaveGameBeforeBerryBlenderLink, MSGBOX_YESNO
	goto_if_eq VAR_RESULT, YES, BerryBlender_EventScript_TryDoLinkBlender
	goto_if_eq VAR_RESULT, NO, BerryBlender_EventScript_CancelLinkBlender
	end

BerryBlender_EventScript_LinkBlenderNoBerries:
	msgbox BerryBlender_Text_NoBerriesLink, MSGBOX_DEFAULT
	releaseall
	end

BerryBlender_EventScript_TryDoLinkBlender:
	call Common_EventScript_SaveGame
	goto_if_eq VAR_RESULT, FALSE, BerryBlender_EventScript_CancelLinkBlender
	specialvar VAR_RESULT, IsWirelessAdapterConnected
	goto_if_eq VAR_RESULT, TRUE, BerryBlender_EventScript_StartDecideLinkLeader
	message BerryBlender_Text_SearchingForFriends
	waitmessage
	special TryBerryBlenderLinkup
	waitstate
	goto_if_eq VAR_RESULT, LINKUP_SUCCESS, BerryBlender_EventScript_SpawnLinkPartners
	goto_if_eq VAR_RESULT, LINKUP_SOMEONE_NOT_READY, BerryBlender_EventScript_CloseLinkNotReady
	goto_if_eq VAR_RESULT, LINKUP_DIFF_SELECTIONS, BerryBlender_EventScript_CloseLinkDifferentSelections
	goto_if_eq VAR_RESULT, LINKUP_FAILED, BerryBlender_EventScript_CloseLink
	goto_if_eq VAR_RESULT, LINKUP_CONNECTION_ERROR, BerryBlender_EventScript_LinkError
	end

BerryBlender_EventScript_TwoPlayerLink:
	msgbox BerryBlender_Text_Player1Arrived, MSGBOX_DEFAULT
	goto BerryBlender_EventScript_DoLinkBerryBlending
	end

BerryBlender_EventScript_ThreePlayerLink:
	msgbox BerryBlender_Text_Player1And2Arrived, MSGBOX_DEFAULT
	goto BerryBlender_EventScript_DoLinkBerryBlending
	end

BerryBlender_EventScript_FourPlayerLink:
	msgbox BerryBlender_Text_AllPlayersArrived, MSGBOX_DEFAULT
	goto BerryBlender_EventScript_DoLinkBerryBlending
	end

BerryBlender_EventScript_DoLinkBerryBlending:
	setvar VAR_0x8004, 0  @ number of opponents, 0 indicates Link
	fadescreen FADE_TO_BLACK
	removeobject 240 @ Unclear where these local IDs come from,
	removeobject 239 @ but presumably they'd be the 4 link players
	removeobject 238
	removeobject 237
	special DoBerryBlending
	waitstate
	releaseall
	end

BerryBlender_EventScript_CancelLinkBlender:
	releaseall
	end

BerryBlender_EventScript_LinkBlenderCaseFull:
	msgbox BerryBlender_Text_PokeblockCaseIsFullLink, MSGBOX_DEFAULT
	releaseall
	end

BerryBlender_EventScript_LinkBlenderNoCase:
	msgbox BerryBlender_Text_DontHavePokeblockCaseLink, MSGBOX_DEFAULT
	releaseall
	end

BerryBlender_EventScript_CloseLinkNotReady:
	special CloseLink
	msgbox Text_SomeoneIsNotReadyToLink, MSGBOX_DEFAULT
	releaseall
	end

BerryBlender_EventScript_CloseLinkDifferentSelections:
	special CloseLink
	msgbox Text_PlayersMadeDifferentSelections, MSGBOX_DEFAULT
	releaseall
	end

BerryBlender_EventScript_CloseLink:
	special CloseLink
	msgbox gText_PokeblockLinkCanceled, MSGBOX_DEFAULT
	releaseall
	end

BerryBlender_EventScript_LinkError:
	special CloseLink
	msgbox Text_LinkErrorPleaseReset, MSGBOX_DEFAULT
	releaseall
	end

BerryBlender_EventScript_SpawnLinkPartners:
	fadescreen FADE_TO_BLACK
	specialvar VAR_RESULT, GetLinkPartnerNames
	copyvar VAR_0x8008, VAR_RESULT
	copyvar VAR_0x8004, VAR_0x8008
	special SpawnLinkPartnerObjectEvent
	goto BerryBlender_EventScript_LinkPlayersArrived
	end

BerryBlender_EventScript_LinkPlayersArrived:
	fadescreen FADE_FROM_BLACK
	switch VAR_0x8008
	case 2, BerryBlender_EventScript_TwoPlayerLink
	case 3, BerryBlender_EventScript_ThreePlayerLink
	case 4, BerryBlender_EventScript_FourPlayerLink
	end

BerryBlender_EventScript_StartDecideLinkLeader:
	setvar VAR_0x8004, LINK_GROUP_BERRY_BLENDER
	goto BerryBlender_EventScript_DecideLinkLeader
	end

BerryBlender_EventScript_DecideLinkLeader:
	message LilycoveCity_ContestLobby_Text_PleaseDecideLinkLeader
	waitmessage
	multichoice 16, 6, MULTI_LINK_LEADER, FALSE
	switch VAR_RESULT
	case 0, BerryBlender_EventScript_TryJoinGroup
	case 1, BerryBlender_EventScript_TryLeadGroup
	case 2, BerryBlender_EventScript_CloseLink
	case MULTI_B_PRESSED, BerryBlender_EventScript_CloseLink
	end

BerryBlender_EventScript_TryLeadGroup:
	call BerryBlender_EventScript_TryBecomeLinkLeader
	goto_if_eq VAR_RESULT, LINKUP_SUCCESS, BerryBlender_EventScript_LinkLeaderDecided
	goto_if_eq VAR_RESULT, LINKUP_FAILED, BerryBlender_EventScript_DecideLinkLeader
	goto_if_eq VAR_RESULT, LINKUP_RETRY_ROLE_ASSIGN, BerryBlender_EventScript_TryLeadGroup
	release
	end

BerryBlender_EventScript_TryJoinGroup:
	call BerryBlender_EventScript_TryJoinLinkGroup
	goto_if_eq VAR_RESULT, LINKUP_SUCCESS, BerryBlender_EventScript_LinkLeaderDecided
	goto_if_eq VAR_RESULT, LINKUP_FAILED, BerryBlender_EventScript_DecideLinkLeader
	goto_if_eq VAR_RESULT, LINKUP_RETRY_ROLE_ASSIGN, BerryBlender_EventScript_TryJoinGroup
	release
	end

BerryBlender_EventScript_TryBecomeLinkLeader:
	special TryBecomeLinkLeader
	waitstate
	return

BerryBlender_EventScript_TryJoinLinkGroup:
	special TryJoinLinkGroup
	waitstate
	return

BerryBlender_EventScript_LinkLeaderDecided:
	goto BerryBlender_EventScript_SpawnLinkPartners
	end
