SlateportCity_House_MapScripts::
	.byte 0

SlateportCity_House_EventScript_PokefanM::
	msgbox SlateportCity_House_Text_NatureToDoWithStatGains, MSGBOX_NPC
	end

SlateportCity_House_EventScript_Girl::
	msgbox SlateportCity_House_Text_MustBeGoingToBattleTent, MSGBOX_NPC
	end

SlateportCity_House_Text_NatureToDoWithStatGains:
	.string "Nire POKéMONAk izaera AKTIBOA du.\p"
	.string "Beste POKéMONEKIN alderatuta\n"
	.string "ABIADURA handiagoa du.\p"
	.string "Agian beraien izaerak POKéMONEN\n"
	.string "estatistikekin zerikusia du.$"

SlateportCity_House_Text_MustBeGoingToBattleTent:
	.string "ENTRENATZAILEA zara, ezta?\p"
	.string "PORTONDO HIRIRA etorri zarenez,\n"
	.string "BORROKA DENDARA zoaz, ziur.$"

