PetalburgCity_House1_MapScripts::
	.byte 0

PetalburgCity_House1_EventScript_Man::
	msgbox PetalburgCity_House1_Text_TravelingIsWonderful, MSGBOX_NPC
	end

PetalburgCity_House1_EventScript_Woman::
	msgbox PetalburgCity_House1_Text_GoOnAdventure, MSGBOX_NPC
	end

PetalburgCity_House1_Text_TravelingIsWonderful:
	.string "Bidaiatzea itzela da!\p"
	.string "Gaztea nintzenean, mendi eta\n"
	.string "itsaso guztiak zeharkatu nituen!$"

PetalburgCity_House1_Text_GoOnAdventure:
	.string "Uff…\p"
	.string "Gustura joango nintzateke POKéMON\n"
	.string "batzuekin abentura batera…\p"
	.string "Belar hezean arrastaka ibili…\n"
	.string "Mendi harritsu altuak igo…\p"
	.string "Itsaso handiak zeharkatu…\n"
	.string "Koba ilunetan zehar bidaiatu…\p"
	.string "Eta, batzuetan, herrimina\n"
	.string "sentitu…\p"
	.string "Bidaiatzea itzela izan behar da!$"

