FortreeCity_House5_MapScripts::
	.byte 0

FortreeCity_House5_EventScript_PokefanF::
	msgbox FortreeCity_House5_Text_TreeHousesAreGreat, MSGBOX_NPC
	end

FortreeCity_House5_EventScript_Man::
	msgbox FortreeCity_House5_Text_AdaptedToNature, MSGBOX_NPC
	end

FortreeCity_House5_EventScript_Zigzagoon::
	lock
	faceplayer
	waitse
	playmoncry SPECIES_ZIGZAGOON, CRY_MODE_NORMAL
	msgbox FortreeCity_House5_Text_Zigzagoon, MSGBOX_DEFAULT
	waitmoncry
	release
	end

FortreeCity_House5_Text_TreeHousesAreGreat:
	.string "ZUHAITZAGAKO zuhaitz etxeak itzelak dira!\p"
	.string "Nire ustez, POKéMONEKIN batera\n"
	.string "bizitzeko hiririk onena da.$"

FortreeCity_House5_Text_AdaptedToNature:
	.string "POKéMONAK eta jendea naturan\n"
	.string "bizirauteko egokitu dira.\p"
	.string "Ez dugu zertan natura aldatu\n"
	.string "gure bizitzeko formagatik.$"

FortreeCity_House5_Text_Zigzagoon:
	.string "ZIGZAGOON: Bufuu!$"

