FortreeCity_House3_MapScripts::
	.byte 0

FortreeCity_House3_EventScript_Maniac::
	msgbox FortreeCity_House3_Text_MetStevenHadAmazingPokemon, MSGBOX_NPC
	end

FortreeCity_House3_EventScript_SchoolKidM::
	msgbox FortreeCity_House3_Text_OhYouHavePokedex, MSGBOX_NPC
	end

FortreeCity_House3_Text_MetStevenHadAmazingPokemon:
	.string "POKéDEXEN inguruan hizketan,\n"
	.string "gauza bat gogoratu dut.\p"
	.string "ENTRENATZAILE bat ezagutu nuen, MIKEL,\n"
	.string "harri arraoak bilatzen zituena.\p"
	.string "Ene, benetan POKéMON bikainak\n"
	.string "zituen berarekin.\p"
	.string "Ez ziren bereziak soilik, izugarri\n"
	.string "ondo entrenatuta zeuden!\p"
	.string "Herri honetako GIMNASIOKO LIDERRA\n"
	.string "bera baino indartsuagoa izango da…$"

FortreeCity_House3_Text_OhYouHavePokedex:
	.string "Zer da hor daukazun hori?\p"
	.string "… … … … … …\p"
	.string "POKéDEXA deitzen zaio?\n"
	.string "Itzela da!$"

