SlateportCity_SternsShipyard_2F_MapScripts::
	.byte 0

SlateportCity_SternsShipyard_2F_EventScript_Scientist1::
	msgbox SlateportCity_SternsShipyard_2F_Text_ShipDesignMoreLikeBuilding, MSGBOX_NPC
	end

SlateportCity_SternsShipyard_2F_EventScript_Scientist2::
	msgbox SlateportCity_SternsShipyard_2F_Text_FloatsBecauseBuoyancy, MSGBOX_NPC
	end

SlateportCity_SternsShipyard_2F_Text_ShipDesignMoreLikeBuilding:
	.string "Ontzi handi bat diseinatzeak eraikin\n"
	.string "handi bat egitearen antza gehiago du\l"
	.string "ibilgailu bat egitearena baino.$"

SlateportCity_SternsShipyard_2F_Text_FloatsBecauseBuoyancy:
	.string "Ez al zaizu arraroa egiten burdin\n"
	.string "astunezko ontzi batek flotatzea?\p"
	.string "Flotagarritasun izeneko printzipio\n"
	.string "baten ondorioa da guztia.$"

