SootopolisCity_Gym_B1F_MapScripts::
	.byte 0

SootopolisCity_Gym_B1F_EventScript_Andrea::
	trainerbattle_single TRAINER_ANDREA, SootopolisCity_Gym_B1F_Text_AndreaIntro, SootopolisCity_Gym_B1F_Text_AndreaDefeat
	msgbox SootopolisCity_Gym_B1F_Text_AndreaPostBattle, MSGBOX_AUTOCLOSE
	end

SootopolisCity_Gym_B1F_EventScript_Crissy::
	trainerbattle_single TRAINER_CRISSY, SootopolisCity_Gym_B1F_Text_CrissyIntro, SootopolisCity_Gym_B1F_Text_CrissyDefeat
	msgbox SootopolisCity_Gym_B1F_Text_CrissyPostBattle, MSGBOX_AUTOCLOSE
	end

SootopolisCity_Gym_B1F_EventScript_Brianna::
	trainerbattle_single TRAINER_BRIANNA, SootopolisCity_Gym_B1F_Text_BriannaIntro, SootopolisCity_Gym_B1F_Text_BriannaDefeat
	msgbox SootopolisCity_Gym_B1F_Text_BriannaPostBattle, MSGBOX_AUTOCLOSE
	end

SootopolisCity_Gym_B1F_EventScript_Connie::
	trainerbattle_single TRAINER_CONNIE, SootopolisCity_Gym_B1F_Text_ConnieIntro, SootopolisCity_Gym_B1F_Text_ConnieDefeat
	msgbox SootopolisCity_Gym_B1F_Text_ConniePostBattle, MSGBOX_AUTOCLOSE
	end

SootopolisCity_Gym_B1F_EventScript_Bridget::
	trainerbattle_single TRAINER_BRIDGET, SootopolisCity_Gym_B1F_Text_BridgetIntro, SootopolisCity_Gym_B1F_Text_BridgetDefeat
	msgbox SootopolisCity_Gym_B1F_Text_BridgetPostBattle, MSGBOX_AUTOCLOSE
	end

SootopolisCity_Gym_B1F_EventScript_Olivia::
	trainerbattle_single TRAINER_OLIVIA, SootopolisCity_Gym_B1F_Text_OliviaIntro, SootopolisCity_Gym_B1F_Text_OliviaDefeat
	msgbox SootopolisCity_Gym_B1F_Text_OliviaPostBattle, MSGBOX_AUTOCLOSE
	end

SootopolisCity_Gym_B1F_EventScript_Tiffany::
	trainerbattle_single TRAINER_TIFFANY, SootopolisCity_Gym_B1F_Text_TiffanyIntro, SootopolisCity_Gym_B1F_Text_TiffanyDefeat
	msgbox SootopolisCity_Gym_B1F_Text_TiffanyPostBattle, MSGBOX_AUTOCLOSE
	end

SootopolisCity_Gym_B1F_EventScript_Bethany::
	trainerbattle_single TRAINER_BETHANY, SootopolisCity_Gym_B1F_Text_BethanyIntro, SootopolisCity_Gym_B1F_Text_BethanyDefeat
	msgbox SootopolisCity_Gym_B1F_Text_BethanyPostBattle, MSGBOX_AUTOCLOSE
	end

SootopolisCity_Gym_B1F_EventScript_Annika::
	trainerbattle_single TRAINER_ANNIKA, SootopolisCity_Gym_B1F_Text_AnnikaIntro, SootopolisCity_Gym_B1F_Text_AnnikaDefeat
	msgbox SootopolisCity_Gym_B1F_Text_AnnikaPostBattle, MSGBOX_AUTOCLOSE
	end

SootopolisCity_Gym_B1F_EventScript_Daphne::
	trainerbattle_single TRAINER_DAPHNE, SootopolisCity_Gym_B1F_Text_DaphneIntro, SootopolisCity_Gym_B1F_Text_DaphneDefeat
	msgbox SootopolisCity_Gym_B1F_Text_DaphnePostBattle, MSGBOX_AUTOCLOSE
	end

SootopolisCity_Gym_B1F_Text_AndreaIntro:
	.string "XALANT LIDERRAK erakutsi zizkidan\n"
	.string "teknikak erakutsiko dizkizut!$"

SootopolisCity_Gym_B1F_Text_AndreaDefeat:
	.string "Mesedez, barkatu, XALANT…$"

SootopolisCity_Gym_B1F_Text_AndreaPostBattle:
	.string "Ikusi zer gertatzen den lurreko\n"
	.string "teila guztiak apurtzen badituzu.$"

SootopolisCity_Gym_B1F_Text_CrissyIntro:
	.string "Honaino iritsi zara, baina ez duzu\n"
	.string "XALANT ikusiko.\p"
	.string "Nire aurka galtzen baduzu ez, behintzat!$"

SootopolisCity_Gym_B1F_Text_CrissyDefeat:
	.string "Indartsua zara!\n"
	.string "ZUre itxura ederrak engainatu nau!$"

SootopolisCity_Gym_B1F_Text_CrissyPostBattle:
	.string "Agian nahikoa ona zara XALANTEK\n"
	.string "kolpe bakarrean ez txikitzeko.$"

SootopolisCity_Gym_B1F_Text_DaphneIntro:
	.string "XALANT borroka batean\n"
	.string "bete-betean ikustea…\p"
	.string "Horren edertasunak berak eragin zidan\n"
	.string "ENTRENATZAILE izateko grina.$"

SootopolisCity_Gym_B1F_Text_DaphneDefeat:
	.string "Jasan dezakedana baino edertasun\n"
	.string "gehiagorekin borrokatu duzu…$"

SootopolisCity_Gym_B1F_Text_DaphnePostBattle:
	.string "Borrokan daukazun grazia\n"
	.string "aparta da.\p"
	.string "Oh… Zeinen zorte onekoa naizen\n"
	.string "POKéMONAK ezagutu ditudalako.$"

SootopolisCity_Gym_B1F_Text_ConnieIntro:
	.string "Borrokak zeinen latzak izan\n"
	.string "daitezkeen erakutsiko dizut.$"

SootopolisCity_Gym_B1F_Text_ConnieDefeat:
	.string "Ene.\n"
	.string "Indartsua zara, gero.$"

SootopolisCity_Gym_B1F_Text_ConniePostBattle:
	.string "Zerbait ona kontatuko dizut.\p"
	.string "XALANTENGANAINO iristeko, teila\n"
	.string "bakoitza behin zapaldu behar duzu.$"

SootopolisCity_Gym_B1F_Text_BridgetIntro:
	.string "HOENN eskualdeko maila\n"
	.string "goreneko GIMNASIOA…\p"
	.string "Hori ARREZIPOLISKO GIMNASIOA da.$"

SootopolisCity_Gym_B1F_Text_BridgetDefeat:
	.string "Izugarrizko maila daukazu!$"

SootopolisCity_Gym_B1F_Text_BridgetPostBattle:
	.string "GIMNASIO indartsu batean eroso egon\n"
	.string "ordez, esango nuke beste leku batzuetan\l"
	.string "entrenatzeak indartu egiten zaituela.\l"
	.string "Baina, batez ere, dibertigarriagoa dirudi.$"

SootopolisCity_Gym_B1F_Text_OliviaIntro:
	.string "XALANTEKIN batera entrenatzen ditut\n"
	.string "nire POKéMONAK.\p"
	.string "Ez uste ezgauza naizenik.$"

SootopolisCity_Gym_B1F_Text_OliviaDefeat:
	.string "Garaitu egin naute…$"

SootopolisCity_Gym_B1F_Text_OliviaPostBattle:
	.string "Potentziala duzula uste dut.\n"
	.string "Zergatik ez zara entrenatzera geratzen?$"

SootopolisCity_Gym_B1F_Text_TiffanyIntro:
	.string "Irristada eder bat izotzetan zehar,\n"
	.string "marrarik zapaldu gabe…\p"
	.string "Halako ENTRENATZAILE bat izugarri\n"
	.string "ederra litzateke!$"

SootopolisCity_Gym_B1F_Text_TiffanyDefeat:
	.string "Aizu, barkatu?!$"

SootopolisCity_Gym_B1F_Text_TiffanyPostBattle:
	.string "Agerikoa da, baina ENTRENATZAILE gisan\n"
	.string "duzun indarrak ez dauka inolako\l"
	.string "zerikusirik zure adinarekin.$"

SootopolisCity_Gym_B1F_Text_BethanyIntro:
	.string "Nire POKéMONEKIN nagoenean, ez dut\n"
	.string "“Ups!” esateko denborarik ere!$"

SootopolisCity_Gym_B1F_Text_BethanyDefeat:
	.string "Ups!$"

SootopolisCity_Gym_B1F_Text_BethanyPostBattle:
	.string "Galdutako kausak ahaztu nahi nituzke\n"
	.string "“Ups!” bat esan bezain pronto!$"

SootopolisCity_Gym_B1F_Text_AnnikaIntro:
	.string "Oso POKéMON arraroekin borroka\n"
	.string "dezaket, nahi baduzu.$"

SootopolisCity_Gym_B1F_Text_AnnikaDefeat:
	.string "Ei, aizu! Begiratu al dituzu\n"
	.string "ondo nire POKéMONAK?$"

SootopolisCity_Gym_B1F_Text_AnnikaPostBattle:
	.string "GIMNASIO honetara etorri nintzen\n"
	.string "XALANTEK nire POKéMON maitea goraipatu\p"
	.string "zuelako. Gazteagoa nintzenean XALANT\n"
	.string "ezagutu izan banu…$"

SootopolisCity_Gym_B1F_Text_BriannaIntro:
	.string "Kar-kar…\n"
	.string "Zure begirada oso xarmanta da.$"

SootopolisCity_Gym_B1F_Text_BriannaDefeat:
	.string "Ai, ene.\n"
	.string "Arinegi jokatu dut zure aurka.$"

SootopolisCity_Gym_B1F_Text_BriannaPostBattle:
	.string "Ez duzu XALANT ukitu ere egingo,\n"
	.string "ziur nago. Kar-kar…$"

