LilycoveCity_House4_MapScripts::
	.byte 0

LilycoveCity_House4_EventScript_Man1::
	msgbox LilycoveCity_House4_Text_MysteriesAtBottomOfSea, MSGBOX_NPC
	end

LilycoveCity_House4_EventScript_Man2::
	msgbox LilycoveCity_House4_Text_UnderwaterTrenchMossdeepSootopolis, MSGBOX_NPC
	end

LilycoveCity_House4_Text_MysteriesAtBottomOfSea:
	.string "Planeta honetako misteriorik handienak\n"
	.string "itsasoaren hondoan daude.\p"
	.string "Norbaitek esan zuen hori, baina ez dakit, ba…$"

LilycoveCity_House4_Text_UnderwaterTrenchMossdeepSootopolis:
	.string "Ur azpiko kobazulo handi bat dago\n"
	.string "GOROLDI eta ARREZIPOLISEN artean.\p"
	.string "Hori esan zidan norbaitek, behintzat.$"

